os/drivers/task_manager/task_manager_drv.c
if no error, ret value should be set to OK.
=> drivers/task_manager: Add return value setting for task_manager_restart

framework/include/media/DataSource.h, framework/include/media/InputDataSource.h, framework/include/media/OutputDataSource.h, framework/src/media/DataSource.cpp, framework/src/media/InputDataSource.cpp, framework/src/media/OutputDataSource.cpp
mAudioType was a member of InputDataSource and OutputDataSource.
Move it to base class; DataSource.
=> framework/media: Move mAudioType to DataSource

apps/system/utils/netcmd.c, apps/system/utils/netcmd_dhcpd.c, external/include/protocols/dhcpd.h, external/ntpclient/ntpclient.c
netcmd.c: In function 'cmd_ifconfig':
netcmd.c:359:9: warning: variable 'result' set but not used [-Wunused-but-set-variable]
int result;
^~~~~~
=> remove the result variable
CC:  netcmd_dhcpd.c
netcmd_dhcpd.c: In function 'cmd_dhcpd':
netcmd_dhcpd.c:131:7: warning: implicit declaration of function 'dhcpd_status' [-Wimplicit-function-declaration]
if (dhcpd_status()) {
^~~~~~~~~~~~
=> add prototype at protocol/dhcpd.h
netcmd_dhcpd.c:137:7: warning: implicit declaration of function 'netlib_getifstatus' [-Wimplicit-function-declaration]
if (netlib_getifstatus(argv[2], &flags) == ERROR) {
^~~~~~~~~~~~~~~~~~
=> include <netutils/netlib.h>
netcmd_dhcpd.c:158:4: warning: implicit declaration of function 'dhcpd_stop' [-Wimplicit-function-declaration]
dhcpd_stop();
^~~~~~~~~~
=> add prototype at …
=> fix build warnings on network features

framework/include/eventloop/eventloop.h, framework/src/eventloop/Make.defs, framework/src/eventloop/eventloop_async.c
Add thread safe functioncall functionlity to eventloop.
User can call callback thread safely in the own eventloop by using eventloop_thread_safe_func_call() API.
=> framework/eventloop: Add thread safe fucntioncall functionality

apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp, framework/src/media/audio/audio_manager.c
- fclose missed before error returns are added in utc_media_mediarecorder.cpp and audio_manager.c
=> framework/media: Fix critical svace issues in media framework

os/tools/download.bat, os/tools/zipdownload.sh
1. Make partition_map.cfg for ARTIK boards
2. Remove making signing binary for ARTIK secure boards
3. Fix wrong name of openocd for Cypress board
4. Check the existance of openocd tool
5. Add "Done" sentence at end of download
=> tools/download: tidy up

os/dbuild.sh
- '-it' option is only for 'menuconfig'
- in general, '-i' would be used.
=> docker/dbuild.sh: change docker options for sevral build env.

os/dbuild.sh
The applist and appupdate are hidden menu of make, because
only IDE uses them. For IDE, in build option selection,
if you type applist or appupdate or ./dbuild.sh applist (appupdate),
it will work.
=> dbuild: add applist and appupdate support

apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
An error occurs when audio_utc executes twice.
because it dose not do pcm_close when end.
so added pcm_close.
=> testcase/audio: Fix audio_utc error

apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
Before testing setVolume, save previous volume and restore after test
=> media/utc: Restore volume after test

os/drivers/audio/alc5658.c, os/drivers/audio/audio_null.c
alc5658.c line 855 : space prohibited before that ':'
audio_null.c line 856 : please, no spaces at the start of a line
=> drivers/audio: fix coding rule violations

framework/include/eventloop/eventloop.h, framework/src/eventloop/eventloop_event.c
Fix wrong word in doxygen and typo in source file.
=> framework/eventloop: Fix wrong word in doxygen and typo

framework/src/task_manager/task_manager_core.c
task manager checks whether callback data is null or not. because of this, callback data should be initialized when allocated.
=> framework/task_manager: Modify allocation for stop/exit callback data

os/kernel/task/task_restart.c
After restarting the task, sigprocmask should be restored.
=> kernel/task_restart : Restarted was had sigprocmask set.

framework/src/task_manager/task_manager_core.c, os/drivers/task_manager/task_manager_drv.c, os/include/tinyara/fs/ioctl.h
after task_restart, sigprocmask sets to NULL by default.
So task manager does not need to set.
=> framework/task_manager: Remove setting sigprocmask to NULL after restart

framework/src/task_manager/Kconfig, framework/src/task_manager/task_manager_core.c
if task is not stopped yet(task status is TM_APP_STATE_CANCELLING), unregister is passed to lpwork.
if task is stopped well, unregister the information immediately.
=> framework/task_manager : Modify to unregister based on task status

os/fs/driver/Make.defs, os/fs/driver/mtd/Kconfig, os/fs/driver/mtd/w25.c, os/include/tinyara/fs/mtd.h
This driver is back ported from NuttX.
Reason:
1. There is no separate winbond w25 driver
2. Current winbond W25Q64FV support in m25px driver is not good
to continue in terms of both modularity and maintainability
Additional changes:
1. There is an assert during mtd read due to below additional code
for checking write completion status.
status = w25_waitwritecomplete(priv);
DEBUGASSERT((status & (W25_SR_WEL | W25_SR_BP_MASK)) == 0);
Hence this additional debug assert statement is removed.
2. There is an infinite travers of mtd nodes in mtd_register if
the whole mtd is registered first in the driver and then
if we try to register mtd partitions.
- w25 driver is trying to register the whole mtd as below.
mtd_register(&priv->mtd, "w25");
- board initialization code would try to register mtd …
=> driver/mtd: add winbond w25 driver

apps/examples/testcase/le_tc/network/tc_net_getpeername.c
- Add a logic to close the socket before return in getpeername_client function
=> apps/examples/network_tc: Add a missing socket close

apps/examples/wifi_manager_sample/wm_test.c
- Add a logic to verify that ap_auth_type is vaild, not to make an overflow in print_wifi_ap_profile function
=> apps/wm_test: Add a logic to check ap_auth_type to avoid buffer overflow

framework/src/task_manager/task_manager_set_callback.c
WID:8682905 After having been compared to NULL value at task_manager_set_callback.c:96, pointer 'data->si_value' is dereferenced at task_manager_set_callback.c:101.
=> framework/task_manager : Add NULL checking before calling stop callback

apps/system/utils/README.md, build/configs/artik053/hello/README.md, build/configs/qemu/HowToRunNetworkStackOnQemu.md, build/configs/qemu/README.md, build/configs/sidk_s5jt200/README.md, docs/HowToPortTizenRTOnWiFiChipset.md, docs/HowToSetEnv.md, docs/HowToUseAudio.md, docs/HowToUseLoggingSystem.md, docs/HowToUseMPU.md, docs/HowToUsePeripheral.md, docs/HowToUseTinyAlsa.md, external/aws/CHANGELOG.md, external/aws/PortingGuide.md, external/grpc/README.md, external/iotivity/README.md, external/iotjs/docs/contributing/Community-Guidelines.md, external/iotjs/docs/devs/Coding-Style-Guidelines.md, external/iotjs/docs/devs/Test-Guidelines.md, external/protobuf/README.md, external/protobuf/cmake/README.md, external/protobuf/java/README.md, external/protobuf/protoc-artifacts/README.md, tools/ramdump/HowToUseRamdump.md
commit 1. Fix some misspelling in *.md file.
commit 2. Fix not consistency to *.md file
The following two principles have been applied in commit 2.
1. The first letter of the sentence is capitalized, the rest is written in lowercase
2. The abbreviation or the name used in KCONFIG is an exception
=> docs: Fix  *.md file for usability

apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c, framework/src/tinyalsa/tinyalsa.c
Currently we check only first buffer index, so apb is always null
Add extra logic to check whole buffers
=> framework/audio : Fix tinyalsa pcm_wait logic

framework/src/media/FileOutputDataSource.cpp
=> framework/media: fix a violation of coding rule

apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c
changes are as follows:
1. use tmpfs instead of smartfs suggested by developer.
2. consider the case of threads in bcm43909
3. add thread check  for buffer state  during capture and playback
Signed-off-by: Manoj Gupta <manoj.g2@samsung.com>
=> apps/example/testcase : Fix audio ITC

external/include/slsi_wifi/slsi_wifi_api.h, external/slsi_wifi/slsi_wifi_api.c, framework/src/wifi_manager/Kconfig, framework/src/wifi_manager/wifi_manager.c, framework/src/wifi_manager/wifi_utils.h, framework/src/wifi_manager/wpa_wifi_utils.c
framework/wifi_manager: 
1. WIFIMGR_DISABLE_EXTERNAL_AUTOCONNECT, to disable an external autoconnect operation defined in wifi dirver
2. WIFIMGR_ENABLE_INTERNAL_AUTOCONNECT, to enable an internal autoconnect operation defined in Wi-Fi Manager
3. WIFIMGR_INTERNAL_AUTOCONNECT_INTERVAL, to set an interval of internal autoconnect operation
external/slsi_wifi: 
1. Add definition of WPA_AUTOCONNECT to enable/disable WPA's AUTOCONNECT operation
=>  framework/wifi_manager: Add configurations for autoconnect operation

framework/src/media/audio/audio_manager.c
- Some wrong accesses to member variables are fixed.
=> framework/media: Fix builds error in medvdbg of audio_manager.c

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_set_callback.c, framework/src/task_manager/task_manager_state.c
1.     framework/task_manager: Modify late unregister with pthread instead of lpwork
If there is no lpwork, task manager cannot support late unregister.
So changed to pthread which treats the late unregister functionality.
2.     testcase/task_manager : Modify tc for removing unnecessary semaphore and add sleep
=> framework/task_manager: Modify late unregister with pthread

framework/src/task_manager/task_manager_core.c
Without pthread_detach, pjoin will be remained and it can be leak.
Because of adding pthread_detach after pthread creation, pthread_detach after task_manager_stop is not needed anymore.
=> framework/task_manager: Add pthread_detach after pthread_create and Remove it in task_manager_stop

os/net/lwip/src/core/ipv4/ip4.c, os/net/netdev/netdev_ioctl.c
- Add a logic to handle two types of broadcast address when assigning the network interface in lwip;
1) general baddr 0xffffffff
2) specific baddr belonging to subnet
Note that lwip fails to match a proper network interface without this modification, expecially when the NIC is mappted into the several (virtual) interfaces such as wl1 and wl2.
=> os/net/lwip: Add a logic to handle broadcast address

os/tools/mkconfig.c
This commit is cherry-picked from Nuttx, commit 599c796.
This resolves a compilation waring as shown below:
os/include/tinyara/config.h:481:5: warning: "CONFIG_NSOCKET_DESCRIPTORS" is not defined [-Wundef]
^~~~~~~~~~~~~~~~~~~~~~~~~~
When CONFIG_NET is disabled, CONFIG_NSOCKET_DESCRIPTORS is not defined.
But every source code uses it without checking definition because
it is a mandatory CONFIG.
This commit guarantees the definition of CONFIG_NSOCKET_DESCROPTORS.
=> Took too much out of tools/mkconfig.c recently.

os/include/tinyara/pm/pm.h, os/pm/pm_changestate.c
pm_querystate function returns the current power management state
Back Ported from Nuttx
(https://bitbucket.org/nuttx/nuttx/commits/7d9787d530bc4c05f354f682cf1d2aa140eb9160)
Signed-off-by: Shadakshari K P <shari.kps@samsung.com>
=> pm: Add pm_querystate function

framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager_broadcast.c, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_set_callback.c, os/drivers/task_manager/task_manager_drv.c, os/include/tinyara/task_manager_drv.h, os/kernel/init/os_bringup.c, os/kernel/task/task_exithook.c
framework/task_manager: Modify file name and declared variable names.
In order to reduce the opportunity of misreadings, file name and several variable names were changed.
1. File name change
- include/tinyara/task_manager_internal.h -> include/tinyara/task_manager_drv.h
2. Variable name chage
- typedef of callback (_tm_unicast_t -> tm_unicast_callback_t / _tm_broadcast_t -> tm_broadcast_callback_t / _tm_termination_t -> tm_termination_callback_t)
framework/task_manager: Modify internal function (taskmgr_getinfo_with_name).
According to the type of task/thread (built_in task, task, pthread), the lists that stores name of task/thread are different.
Therefore, an invalid referencing can occur which can result in an assert problem.
The procedure of selecting the lists to find the name of …
=> framework/task_manager: Modify naming and internal fucntion.

framework/src/task_manager/task_manager_core.c, os/drivers/task_manager/task_manager_drv.c, os/include/tinyara/fs/ioctl.h, os/include/tinyara/task_manager_drv.h
Previously, when pthread is created by task manager (when task_manager_start() is called), the group of pthread's tcb is set as the group of task manager.
The group of pthreads' tcb needs to be set as the group of the caller.
Otherwise, this can leed to a inappropriate result.
Therefore, additional procedures were added to prevent this problem.
After a pthread is created by task manager, the group of pthread's tcb is detached from the task manager.
Then, the group of pthread's tcb is joined to the group of caller.
=> framework/task_manager: Add procedure to change the group of tcb.

build/configs/artik05x/scripts/partition_gen.sh
This commit removes the warning message when downloading
the binary
=> build/configs/artik05x: Change board Kconfig filepath

build/configs/artik05x/artik05x_download.sh, build/configs/artik05x/artik05x_make_bin.sh, build/configs/artik05x/artik05x_ota.sh, build/configs/artik05x/scripts/partition_gen.sh, build/configs/cy4390x/cy4390x_make_bin.sh, build/configs/sidk_s5jt200/sidk_s5jt200_download.sh, build/configs/sidk_s5jt200/sidk_s5jt200_make_bin.sh, build/configs/sidk_s5jt200/tools/openocd/partition_gen.sh, tools/fs/mkromfsimg.sh, tools/memory/g_var_profiler.sh
Many sh files get a current path using PWD command. But it
is changed where you run it.
For example, if you run a shell script on aa/bb folder, PWD is aa/bb.
But if you run it like bb/xx.sh on aa folder, PWD is aa.
The location of executing shell script affects working of shell script.
This commit gets the current path from location of shell script which
is fixed. Wherever you run it, it works.
=> Get the current location from script file path on shell scripts

os/arch/arm/src/armv7-m/up_assert.c, os/arch/arm/src/armv7-r/arm_assert.c
1. change a format of task information
```
Previousely displaying format of task information at assert is
little difficult to see.
up_showtasks: *******************************************
up_showtasks: List of all tasks in the system:
up_showtasks: *******************************************
up_taskdump: Idle Task: PID=0 PRI=0 Stack Used=0 of 0
up_taskdump: hpwork: PID=1 PRI=224 Stack Used=164 of 2028
up_taskdump: tash: PID=3 PRI=125 Stack Used=372 of 4076
up_taskdump: appmain: PID=4 PRI=100 Stack Used=372 of 2028
This commit aligns items as shown below:
up_showtasks: *******************************************
up_showtasks: List of all tasks in the system:
up_showtasks: *******************************************
up_showtasks:    NAME   |  PID  |  PRI |    USED /  TOTAL STACK …
```
=> arch/arm: enhence assert display

framework/src/media/BufferOutputDataSource.cpp, framework/src/media/FileOutputDataSource.cpp, framework/src/media/SocketOutputDataSource.cpp
0 length fwrite(FileOutputDataSource) or array(BufferOutputSource)
are not verified. So just return 0 if size is 0
=> media: Return 0 when OutputDatasource size is 0

apps/examples/wifi_manager_sample/wm_test_stress.c, framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/wifi_utils.h, framework/src/wifi_manager/wpa_wifi_utils.c
- Add enterprise security types into wifi_manager and wifi_utils
- Modify phy_mode to denote the supported standard version
=> framework/wifi_manager: Security type and phy mode management

apps/examples/wifi_manager_sample/wm_test.c, framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/wifi_manager.c
- Add a AP_RECONNECTING status
- Add the new state handling on _convert_state_to_info
- Modify wm_test to recognize the reconnect state and print it
=> framework/wifi_manager: Add RECONNECT status and update its log

framework/src/media/MediaRecorderImpl.cpp, framework/src/media/OutputHandler.cpp, framework/src/media/OutputHandler.h
MediaRecorder::stopRecorder calls OutputHandler::flush.
It ensure that all data are written.
=> media: Flush outputhandler when recorder stops

framework/src/task_manager/task_manager_core.c
Sometimes task state is not updated instantly. So before getting task information, task state should be updated.
i.e. Normal termination of task will not update the task state itself.
=> framework/task_manager: Add state update logic before getinfo

framework/src/media/audio/audio_manager.c
if register_stream_in_device_process_handler is not NULL,
process_handler is already registered.
So just return AUDIO_MANAGER_SUCCESS
=> media: Check if process_handler is already set

apps/system/iperf/README.txt, external/json/cJSON.c
iperf app uses cJSON library sending and receiving app results including the bytes sent.
When you send the large bytes to a server, especially using 5GHz WiFi,
the 'number_buffer' array, which is temporary used to print the number in cJSON, can be overrun.
That will cause sending results error, and you will see the log : "error - unable to send results".
The size of 'number_buffer' array was set to 27 to solve the error, that is enough to get the large bytes.
If you encounter the same problem, however, check the 'number_buffer' array size again in cJSON.
=> Resize number_buffer array in cJSON.c to solve the buffer overrun issue.

framework/src/media/audio/audio_manager.c, os/drivers/audio/audio_null.c
Since mq_open is called in audio_manager,
mq_close should be called in audio_manager too.
And set config->process_handler as NULL at unregisteration
=> media: Add handler_refcnt

framework/src/media/OutputHandler.cpp
Allocated array should be deallocated by delete[]
=> media: Use delete[] to free array

os/mm/mm_heap/mm_heapinfo.c
There is a possibility of overflow over 32 bit while multiplying
large free size with 100.
Example overflowed heapinfo output:
Total                           : 125870864 (100%)
- Allocated (Current / Peak)  : 1204032 (0%) / 1245776 (0%)
- Free (Current)              : 124666800 (30%)
- Reserved                    : 32
=> mm_heap/heapinfo: fix overflow in percentage calculation

apps/examples/testcase/le_tc/kernel/itc_pthread.c, apps/examples/testcase/le_tc/network/itc_net_connect.c
Changes are as below:
itc_pthread.c ->
1. add return check for api pthread_sigmask()
itc_net_connect.c ->
1. integer underflow resolved by increasing length by 1
2. change recv_len type to unsigned int for avoide integer range
Signed-off-by: Manoj Gupta <manoj.g2@samsung.com>
=> apps/exaple/testcase/ : fix svace issue for kernel and network ITC

framework/include/media/MediaPlayer.h, framework/include/media/MediaRecorder.h
The definition of the error code
has been modified to make it easier to understand.
=> media: modify definition for errorcode

framework/src/st_things/things_stack/utils/things_ping.c
Shared variables such as 'mutex_ping_list' and 'mutex_state' weren't locked before being accessed
in check_ping_thread() and unset_mask respectively. This patch addresses the problem.
=> framework/st_things: Added missed-out mutex lock and unlock in ping.

apps/examples/st_things/light/sample_light_things.c
AS IS: things_notify_observers() - This is an internal function which is not supposed to be called from application.
TO BE: st_things_notify_observers() - Actual function which is supposed to be called.
=> apps/st_things: Avoiding the usage of internal function.

framework/src/task_manager/task_manager_core.c
When user uses task_manager_set_broadcast_cb() with 'NULL' value as the cb_data, an assert problem occurs.
In order to prevent this problem, NULL check procedure is added.
=> framework/task_manager: Add NULL check procedure

apps/examples/iotjs_startup/iotjs_startup_main.c
This will improve connectivity reliability.
Change-Id: Ie4a5bcb397fb7959f2c5954d7a7569052ccc39fb
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=>  iotjs: Fix (re)connected status in callback

os/drivers/audio/audio_null.c
null_unregisterprocess should check process_threadid not workerthreadid
=> drivers/audio:Fix errata in null_unregisterprocess

framework/src/arastorage/index_manager.c
index_load function, after alloc index, when find_index_api
return NULL, need to release index before return error.
@Taejun-Kwon
=> framework/arastorage:fix index memb release issue

framework/src/arastorage/storage_interface.c
1. storage_put_relation ,when create new tuple file,
file may exist because of the first random_rand value
maybe the same(typically 'tup0') after reboot device,
need to check file exist before call
storage_generate_file to create new file directly
2. correct the log format, remove redundant %d
@jeongarmy @Taejun-Kwon
=> framework/arastorage: fix tuple file overwrite issue

lib/libc/signal/Make.defs, lib/libc/signal/sigwait.c, os/include/signal.h
This is back-ported from Nuttx bf7839d.
=> libc/signal:  Add support for sigwait().

framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/wifi_manager.c
- By adding these APIs, applications on TizenRT can get wi-fi events max 3 by default. 
- Note that the 0th index of the callback array is allocated by initializing Wi-Fi Manager, wifi_manager_init.
=> network/wifi_manager: Add register, unregister callback API

external/curl/curl_config.h
- the size of long is 32bit in TizenRT
=> external/curl: set curl config in TizenRT

lib/libc/stdio/lib_sscanf.c
libs/libc/stdio/lib_sscanf.c: Fix conversion for format specifiers that appear right after a floating point format specifier
When performing a floating point conversion the parsing code could
consume more than required characters from the input buffer. This made
impossible to convert input of form "1.1K" using format "%f%c".
Fix the issue by advancing the input buffer with the actual characters
converted as a float point number.
Back ported from NuttX
=> sscanf: Fix conversion for format specifiers

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager_broadcast.c, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_set_callback.c
In order to match the input parameter type of broadcast callback with the unicast callback, the input parameter type of broadcast callbakc was changed.
Previous: typedef void (*tm_broadcast_callback_t)(void *broadcast_data, void *cb_data);
Present: typedef void (*tm_broadcast_callback_t)(tm_msg_t *broadcast_data, tm_msg_t *cb_data);
Furthermore, to prevent build error, the utc of task manager was also modified according to the revisions.
=> framework/task_manager: Modify the input parameter type of broadcast callback

apps/appgen/README.md, apps/appgen/template_Kconfig_task_manager, apps/appgen/template_task_manager_sample_main.c_source, os/tools/appgen.sh
- Add templates for a sample application
Sample application using the task manager of TizenRT
- Modify the appgen.sh in order to select the type of sample application.
- Revise the README.md according to the added templates and procedures.
=> apps/appgen: Add templates for a sample application of the task manager

apps/builtin/builtin_list.c, apps/include/builtin.h, framework/src/task_manager/Kconfig, framework/src/task_manager/task_manager_core.c
Previous Task Manager cannot run without builtin-apps.
But, now Task Manager can run without builtin-apps.
=> Remove unnecessary check for builtin count and Fix unregister return value

framework/src/task_manager/task_manager_core.c
Previoulsly, there was too many type casting, as one internal function of task manager core (taskmgr_set_msg_cb()) was shared by the two roles (task_manager_set_unicast_cb() and task_manager_set_broadcast_cb()).
In order to improve the reability, the internal function of task manager core (taskmgr_set_msg_cb()) was split into two internal fuction (taskmgr_set_unicast_cb() and taskmgr_set_broadcast_cb()).
=> framework/task_manager: Split the internal function of task manager core

lib/libc/string/lib_strcoll.c, os/include/string.h
This patch modifies API definitions in string.h as per coding rule and
adds valid arguments names to each one of them.
=> os/include: Fill argument names for API's in all string.h definitions

apps/examples/mediaplayer/mediaplayer_main.cpp, apps/examples/mediarecorder/mediarecorder_main.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp, framework/include/media/MediaPlayer.h, framework/include/media/MediaRecorder.h, framework/src/media/MediaPlayer.cpp, framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaPlayerImpl.h, framework/src/media/MediaRecorder.cpp, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/MediaRecorderImpl.h, framework/src/media/audio/audio_manager.c
- getMaxVolume() API is added to media recorder and player source code, respectively.
- UTCs for getMaxVolume() is added also.
- The command to call getMaxVolume() is added also into media examples.
=> framework/media: Add APIs and UTCs to get maximum audio volume

apps/examples/testcase/ta_tc/media/itc/Make.defs, apps/examples/testcase/ta_tc/media/itc/itc_media_bufferoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_fileinputdatasource.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_fileoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_focusmanager.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_focusrequest.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_main.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_mediaplayer.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_mediarecorder.cpp
changes are as below:
itc_media_bufferoutputdatasource.cpp->
1. develope 5 ITC for new api, itc are as below
itc_media_BufferOutputDataSource_getChannels_setChannels_p
itc_media_BufferOutputDataSource_getSampleRate_setSampleRate_p
itc_media_BufferOutputDataSource_getPcmFormat_setPcmFormat_p
itc_media_BufferOutputDataSource_getAudioType_setAudioType_p
itc_media_BufferOutputDataSource_reopen_p
itc_media_fileinputdatasource.cpp->
fix build issue due to namespace media class change
itc_media_fileoutputdatasource.cpp->
fix build issue due to namespace media class change
itc_media_focusmanager.cpp->
1. develope 2 ITC for new api, itc are as below
itc_media_FocusManager_getFocusManager_p
itc_media_FocusManager_requestFocus_p
itc_media_focusrequest.cpp->
1. develope 2 ITC for new api, itc are as …
=> apps/example/testcase/ : fix media ITC build fail and new ITC develope

lib/libc/stdio/lib_sscanf.c
C library: modify sscanf to read more than 128byte string
Modify C library vsscanf() as described below.
1) Due to MAXLN of 128 bytes, sscanf scan only upto 128 bytes string. This is issue reported by
ST things team since ST things SDK needs to scan more than 2K data.
2) So remove the 128 byte upper limit for string case, Hence it can scan any string range
3)Test procedure:
--------------------------
char *buf = "ABCDXXXX..... . .. .Z"(say 555 char)
char tmp[124];
ret = sscanf(buf,"%s", tmp)
printf("Post scan: %s\n", tmp);
--------------------------
a) O/P (without fix) : 128 characters only
b) O/P (with fix) : All 555 chars
Signed-off-by: Shadakshari K P <shari.kps@samsung.com>
=> C library: modify sscanf to read more than 128byte

framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_set_callback.c
1. taskmgr_get_drvfd() and ioctl() were unified to taskmgr_handle_tcb().
According to the change, taskmgr_adj_pthread_parent() and taskmgr_broadcast() were modified.
(taskmgr_get_drvfd() and ioctl() were replaced with taskmgr_handle_tcb())
2. In order to avoid the misreading, TM_STOP_INFO(X) and TM_EXIT_INFO(X) were changed to TM_STOP_CB_INFO(X) and TM_EXIT_CB_INFO(X).
=> framework/task_manager: Refactoring task manager core

external/iotivity/iotivity_1.2-rel/extlibs/libcoap/SConscript
AS IS: libcoap.a library was not removed after 'make clean'.
TO BE: Remove libcoap.a after 'make clean'.
=> [external/iotivity]: Remove libcoap.a from external/libcoap/ for 'make clean'

apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c, framework/src/wifi_manager/wifi_manager.c
- Deinitialize callback function pointer when deinit is executed
- Add two UTCs for newly added APIs; wifi_manager_register_cb and wifi_manager_unregister_cb
=> framework/wifi_manager: Modify deinit API and add UTC for new APIs

framework/src/wifi_manager/wifi_profile.c
- Load SSID and PASSPHRASE string information using ssid_length and passphrase_length variables in wifi_profiles
- Add a logic to verify that loaded ssid_length and passphrase_length are within the proper range
=> framework/wifi_manager: Modify save and load of AP configurations

framework/src/media/audio/audio_manager.c, os/drivers/audio/alc5658.c
ac_format, ac_controls are filled in alc5658_getcaps.
Replace ac_format with ac_subtype.
=> drivers/audio: Modify alc5658_getcaps logic

build/configs/artik053/st_things/defconfig
- Add CONFIG_NET_NETMON=y into defconfig for st_things configuration
=> framework/st_things: Enable network monitor by default

apps/system/utils/kdbg_heapinfo.c, os/include/tinyara/mm/mm.h, os/mm/mm_heap/mm_heapinfo.c
'-e HEAP_IDX'(HEAP_IDX'th heap information) and '-r'(region information) options are added.
The results are below:
1. -e option
```
TASH>>heapinfo -e 1
****************************************************************
HEAP[1] Allocation Info- (Size in Bytes)
****************************************************************
REGION #0 Start=0x2032800, End=0x20467f0, Size=81920
****************************************************************
MemAddr |   Size   | Status |    Owner   |  Pid  |
----------|----------|--------|------------|-------|
0x2032800 |       16 |   A    | 0x    dead |   0   |
0x2032810 |       32 |   A    | 0x 40d3570 |   4   |
0x2032830 |     4112 |   A    | 0x 40d3580 |   4   |
0x2033840 |    77744 |   F    |            |       |
** PID(S) in Pid colum means that mem is …
```
=> utils/heapinfo : Support multi-heap heapinfo command

apps/examples/fs_helper/Kconfig, apps/examples/fs_helper/Makefile, apps/examples/fs_helper/fs_rw_test.c
This test is intended to test the R/W performance of the filesystem
=> examples/fs_helper: Add fs r/w test in fs_helper

external/iotivity/iotivity_1.2-rel/extlibs/libcoap/SConscript
The 'make clean' will show below message and wait the user confirm.
'rm: remove write-protected regular file '*/external/iotivity/iotivity_1.2-rel/extlibs/libcoap/libcoap.a'?'
But it doesn't need and it will not be showing when user uses './dbulid.sh menu' to clean.
So the rm command is able to use '-f' option.
=> external/iotivity: Force delete libcoap.a from external/libcoap for 'make clean'.

framework/src/st_things/things_stack/Make.defs, framework/src/st_things/things_stack/cloud/cloud_connector.c, framework/src/st_things/things_stack/cloud/cloud_manager.c, framework/src/st_things/things_stack/easy-setup/easysetup_manager.c, framework/src/st_things/things_stack/easy-setup/resource_handler.c, framework/src/st_things/things_stack/framework/things_data_manager.c, framework/src/st_things/things_stack/framework/things_req_handler.c, framework/src/st_things/things_stack/framework/things_resource.c, framework/src/st_things/things_stack/framework/things_security_manager.c, framework/src/st_things/things_stack/framework/things_server_builder.c, framework/src/st_things/things_stack/things_iotivity_lock.c, framework/src/st_things/things_stack/things_iotivity_lock.h, framework/src/st_things/things_stack/things_stack.c, framework/src/st_things/things_stack/utils/things_ping.c
Used mutex (recursive) to synchronize the usage of IoTivity APIs.
**IoTivity Path:** external/iotivity
**IoTivity CSDK API Path:** external\iotivity\iotivity_1.2-rel\resource\csdk\stack\include\ocstack.h
IoTivity CSDK (C API) is not thread-safe. As per its design, it doesn't allow multiple threads to call its functions at the same time. User of the APIs is required to maintain a single lock for all IoTivity API calls to protect the functions from thread synchronization issues.
**Reference:** 
IoTivity CPP SDK (C++ API) maintains a single lock for calling IoTivity CSDK APIs.
It's path: external\iotivity\iotivity_1.2-rel\resource\src\InProcServerWrapper.cpp
=> framework/st_things: Using IoTivity APIs with Thread-Safety.

framework/src/st_things/things_stack/framework/things_req_handler.c, framework/src/st_things/things_stack/framework/things_req_handler.h
Request handler has unused variables which are related to maintaining resource list and a callback to get the observer uri.
This patch removes those lines of dead code.
=> framework/st_things: Removed unused code in request handler.

framework/src/st_things/things_stack/easy-setup/easysetup_manager.c, framework/src/st_things/things_stack/framework/things_server_builder.c, framework/src/st_things/things_stack/framework/things_server_builder.h
Code related to broadcasting presence is not used.
So it's better to remove. If needed in the future, we can bring it back.
=> framework/st_things: Removed unused code in server builder.

framework/src/st_things/things_stack/easy-setup/easysetup_manager.c, framework/src/st_things/things_stack/easy-setup/es_common.h, framework/src/st_things/things_stack/easy-setup/resource_handler.c, framework/src/st_things/things_stack/easy-setup/resource_handler.h, framework/src/st_things/things_stack/framework/things_req_handler.c, framework/src/st_things/things_stack/things_def.h, framework/src/st_things/things_stack/things_types.h, framework/src/st_things/things_stack/utils/things_network.c
1. Add EncType value WEP_SHARED,WPA_PSK,WPA2_PSK
2. Add SecType value WEP-64,WEP-128,TKIP,AES,TKIP_AES
Signed-off-by: harish191 <harish.191@samsung.com>
=> framework/st_things : Add EncType and SecType values for AP scan list

docs/HowToUseMultiHeap.md, os/include/tinyara/mm/mm.h, os/mm/umm_heap/umm_calloc.c, os/mm/umm_heap/umm_malloc.c, os/mm/umm_heap/umm_memalign.c, os/mm/umm_heap/umm_realloc.c, os/mm/umm_heap/umm_zalloc.c
Xalloc_at APIs can be used to allocate memory for a specific heap.
=> docs/multiheap: Add supported APIs description

external/dhcpc/Makefile, external/dhcpd/Makefile
- By default, complie dhcpc.c/dhcpd.c, not checking CONFIG_NET_DHCP
=> external/DHCP: Modify Makefile to minimize defconfig modification

os/include/tinyara/mm/mm.h
Due to missing header file, there is a compilation error as shown below:
/root/tizenrt/os/include/tinyara/mm/mm.h:211:30: error: 'regionx_start' undeclared (first use in this function)
The prototype of regionx_start is in heap_regioninfo.h so that
including header is necessary.
=> include/mm: include heap_regioninfo.h header file

framework/src/st_things/things_stack/framework/things_req_handler.c, framework/src/st_things/things_stack/things_api.h, framework/src/st_things/things_stack/things_stack.c, framework/src/st_things/things_stack/things_types.h
POST on /sec/provisioning resource are for "abort" and "reset" from cloud.
"abort" is neither used nor fully implemented.
"reset" is fully implemented but unused.
We will implement them later based on future requirements.
=> framework/st_things: Remove POST request handling for /sec/provisioninginfo

external/mbedtls/pk_wrap.c, external/mbedtls/ssl_tls.c, external/mbedtls/x509_crl.c, os/arch/arm/src/s5j/sss/isp_define.h
sssfw does not support SHA2_224, but there is SHA2_224 in source code.
When fail to parse crl, do not free pem resource.
reference :
https://www.bountysource.com/issues/40064024-memory-leak-in-mbedtls_x509_crl_parse
This commit changes the behaviour of mbedtls_ssl_parse_certificate
to make the two authentication modes MBEDTLS_SSL_VERIFY_REQUIRED and
MBEDTLS_SSL_VERIFY_OPTIONAL be in the following relationship:
Mode == MBEDTLS_SSL_VERIFY_REQUIRED <=> Mode == MBEDTLS_SSL_VERIFY_OPTIONAL + check verify result
Also, it changes the behaviour to perform the certificate chain
verification even if the trusted CA chain is empty. Previously, the
function failed in this case, even when using optional verification,
which was brought up in Samsung#864.
(Samsung#864 ARMmbed/mbedtls#864)
=> external/mbedtls: update mbedtls patch

external/dhcpc/dhcpc.c
- Change 'broadcast' to 'unicast' of bootp flag in DHCP discover packet hdr
=> external/dhcpc: Modify DHCP discover flag

external/dhcpc/dhcpc.c
- Change 'broadcast' to 'unicast' of bootp flag in DHCP request packet hdr
=> external/dhcpc: Modify DHCP request flag

apps/examples/mediaplayer/BufferInputDataSource.cpp, apps/examples/mediaplayer/BufferInputDataSource.h, apps/examples/testcase/ta_tc/media/itc/itc_media_fileinputdatasource.cpp, apps/examples/testcase/ta_tc/media/itc/itc_media_fileoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_fileinputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_fileoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_bufferoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp, framework/include/media/BufferOutputDataSource.h, framework/include/media/DataSource.h, framework/include/media/FileInputDataSource.h, framework/include/media/FileOutputDataSource.h, framework/include/media/HttpInputDataSource.h, framework/include/media/SocketOutputDataSource.h, framework/src/media/BufferOutputDataSource.cpp, framework/src/media/FileInputDataSource.cpp, framework/src/media/FileOutputDataSource.cpp, framework/src/media/HttpInputDataSource.cpp, framework/src/media/InputHandler.cpp, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/OutputHandler.cpp, framework/src/media/SocketOutputDataSource.cpp
Rename DataSource::isPrepare() to DataSource::isPrepared().
`is prepared` means data source is ready to read/write.
@Taejun-Kwon
=> framework/media: Rename DataSource interface

os/fs/inode/fs_inode.c, os/fs/inode/fs_inodereserve.c, os/fs/smartfs/smartfs.h
- Weird expressions and words are modified.
- cformatter is applied.
=> os/fs: Fix typos in comments

os/tools/mkexport.sh
"make export" makes TizenRT as a library, but there is a incorrect naming rule.
The output file name is tizenrt-export-x.y.zip.(x, y is a version for TizenRT)
=> os/tools/mkexport.sh: Change exported library name to tizenrt

framework/src/media/audio/audio_manager.c
if direct == INPUT, type_chr is initially assigned as 'p' and
re-assigned as 'c'
=> media/audio: Remove duplicated assignment

os/mm/umm_heap/umm_calloc.c, os/mm/umm_heap/umm_memalign.c, os/mm/umm_heap/umm_zalloc.c
for using mdbg, #include <debug.h> is required.
=> mm/umm_heap: Add missing include about debug

framework/src/media/InputHandler.cpp
Remove code because header parsing is already implemented
=> framework/media: Remove unnecessary code

framework/src/media/streaming/audio_encoder.cpp
Remove unnecessary TODO comments.
@Taejun-Kwon
=> framework/media: Remove unnecessary TODO comment in audio encoder

docs/HowToSetEnv.md
HowtoSetEnv.md and HowtoInstallKconfigFrontend.md are
in same directory depth, docs folder so that link should not have
"docs/" in a link.
=> docs/HowToSetEnv.md: fix wrong path of installing Kconfig-frontend link

os/syscall/syscall.csv, os/syscall/syscall_lookup.h
1. syscall 'execv' is not used.
2. fix typos.
=> os/syscall: delete unused syscall and fix typos.

framework/src/media/utils/MediaUtils.cpp
- Compares whether the size returned by fwrite is equal to the size of the data to be written.
=> framework/media : Handling errors according to fwrite return value

framework/src/media/Make.defs
CONFIG_MEDIA depends on CONFIG_AUDIO.
All Mediaframework files will build only if CONFIG_MEDIA is defined.
=> framework/media: Modify Make.defs

apps/examples/st_things/Makefile, apps/examples/st_things/blink/Make.defs, apps/examples/st_things/light/Make.defs, apps/examples/st_things/msghandling/Make.defs
1. Modify the Makefile to remove  generated  object file from
sub directory after make clean.
2. Add 'Make.defs' file in each folder(light,blink,msghandling) to provide the
sample application file to the Makefile of st_things example.
Signed-off-by: harish191 <harish.191@samsung.com>
=> apps/examples/st_things: Fix remove object file after make clean.

apps/system/utils/Kconfig, apps/system/utils/kdbg_kill.c, os/include/signal.h, os/include/tinyara/sched.h, os/kernel/Kconfig, os/kernel/signal/sig_action.c, os/kernel/task/task_activate.c
When creating a task/pthread, SIGKILL handler will be registered by default.
Its handler terminates itself when a task/pthread gets SIGKILL signal.
But there is no garbage collection for teminating, so if user wants to free the allocates,
user should register the user's own handler for SIGKILL.
=> apps/utils/kill: support a thread termination in kernel context with SIGKILL signal

apps/examples/sensorbd_demo/examples/gpio_ledonoff.c, apps/examples/sensorbd_demo/examples/gpio_starterled.c, apps/examples/sensorbd_demo/examples/i2c_mpu9250.c, apps/examples/sensorbd_demo/examples/i2c_tcs34725.c, apps/examples/sensorbd_demo/examples/pwm_buzzer.c, apps/examples/sensorbd_demo/examples/pwm_led.c, apps/examples/sensorbd_demo/examples/spi_k6ds3.c, apps/examples/sensorbd_demo/examples/spi_lis3lv02qd.c
The up_mdelay() should be only used inside kernel context,
user should not.
Let's use sleep() and usleep() instead of it.
=> examples/sensorbd_demo: use sleep()/usleep() instead of up_mdelay()

os/arch/xtensa/src/esp32/esp32_start.c
1. Add g_idle_topstack to fix a build issue.
2. Fix the path description in nuttx licence.
=> arch/xtensa: Fix a build issue.

framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/audio/audio_manager.c, framework/src/media/audio/audio_manager.h
Call find_audio_card in audio_manager_init.
Remove init_audio_stream_out, init_audio_stream_in, init_audio_stream,
find_audio_card_if_empty.
=> framework/media: Find audio cards at init time

os/arch/xtensa/src/esp32/esp32_start.c, os/arch/xtensa/src/xtensa/xtensa_createstack.c, os/arch/xtensa/src/xtensa/xtensa_initialstate.c
1. Enable FPU if XTENSA_CP_ALLSET does not equal 0;
2. update current FPU state into tcb_s when thread is created.
=> os/arch/xtensa: Enable FPU co-processor;

apps/examples/setjmp/setjmp_longjmp_test.c, os/crypto/blake2s.c, os/crypto/random_pool.c, os/fs/inode/fs_inode.c, os/fs/inode/fs_inodereserve.c, os/fs/smartfs/smartfs.h, os/include/tinyara/crypto/blake2s.h, os/include/tinyara/random.h
setjmp/setjmp_longjmp_test.c: add missing variables in function
add missing variables in function at line 144, 158.
================================================================
crypto: fix violations of coding rules and alignment
1. space required after that ','
2. please, no spaces at the start of a line
3. space required before the open parenthesis '('
4. space prohibited after that open square bracket '['
=========================================================
os/fs: Fix typos in comments
- Weird expressions and words are modified.
- cformatter is applied.
=> fix typo and fix violations of coding rules

framework/src/arastorage/db_options.h
DB_TUPLE_LIMIT is a maximum number of tuples in a relation.
This value should be set according to use case.
A arastorage utc has test cases with more than 800 tuples.
So DB_TUPLE_LIMIT should be bigger than this value.
=> framework/arastorage: set a maximum value of tuples defined in db_options.h

lib/libc/libc.csv, lib/libc/net/Make.defs, lib/libc/net/lib_htonl.c, lib/libc/net/lib_htons.c, lib/libc/net/lib_inetaddr.c, lib/libc/net/lib_inetaton.c, lib/libc/net/lib_inetntoa.c, lib/libc/net/lib_inetntop.c, lib/libc/net/lib_inetpton.c, os/net/socket/bsd_socket_api.c
**APIs added**
htonl()
ntohl()
htons()
ntohs()
inet_addr()
inet_aton()
inet_ntoa()
inet_ntop()
inet_pton()
This is back-ported from Nuttx commit cf99fb4 and 5c8a975.
Add build files in libc/net and disable some lwip APIs
=> libc/net: Add network C libraries

.travis.yml
- TizenRT docker image is updated (ver. 1.5.0)
- new toolchain, xtensa-esp32-elf is added.
=> travis: modify .travis.yml to maintain latest docker image

apps/examples/testcase/le_tc/kernel/itc_sched.c, apps/examples/testcase/le_tc/kernel/kernel_tc_main.c, apps/examples/testcase/le_tc/kernel/tc_clock.c, apps/examples/testcase/le_tc/kernel/tc_internal.h, apps/examples/testcase/le_tc/kernel/tc_roundrobin.c, apps/examples/testcase/le_tc/kernel/tc_sched.c, apps/examples/testcase/le_tc/kernel/tc_signal.c, apps/examples/testcase/le_tc/kernel/tc_tash_heapinfo.c, apps/examples/testcase/le_tc/kernel/tc_timer.c, os/drivers/testcase/Make.defs, os/drivers/testcase/testcase_drv.c, os/include/tinyara/testcase_drv.h
1. Register an os api that is not registered with syscall.
2. In the case of tcb, only brought the information I needed for the state.
=> testcase/kernel : Use a virtual driver to test kernel internal APIs.

framework/src/media/Decoder.cpp, framework/src/media/Decoder.h, framework/src/media/FileInputDataSource.cpp, framework/src/media/InputHandler.cpp, framework/src/media/Make.defs, framework/src/media/audio/audio_manager.c, framework/src/media/audio/resample/samplerate.c, framework/src/media/audio/resample/samplerate.h, framework/src/media/codecs/wav_decoder_api.cpp, framework/src/media/codecs/wav_decoder_api.h, framework/src/media/streaming/audio_decoder.cpp, framework/src/media/streaming/audio_decoder.h, framework/src/media/utils/MediaUtils.cpp, framework/src/media/utils/MediaUtils.h, framework/src/media/utils/remix.cpp, framework/src/media/utils/remix.h
1. Add remix.c to convert multichannel to stereo/mono.
2. Update samplerate.c to support rechannel in src_simple().
3. Modify Decoder.cpp and other files to support multichannel *.wav.
@Taejun-Kwon @junmin-kim @jsdosa @JeonginKim
=> framework/media: Add audio rechannel feature for multi channel audio

os/dbuild.sh
1. Use the BINFILE variable to check output file of each board
Each board uses specific output file to program on a board.
This commit makes a line change to support new board binary type
by separating operation codes and a definition which can be
different by each board.
2. Show the download option
FIND_BINFILE function checks existing of output file and updates
STATUS so that we don't need to check it again to show the download
option. Let's use STATUS for that.
3. Update STATUS after build
Let's use UPDATE_STATUS function which we already support.
4. Rename STATUS function to UPDATE_STATUS
That function checks and updates the STATUS variable so that
UPDATE is better than CHECK as a function name.
=> dbuild: define BINFILE to say output file of each board and tidy up

os/arch/Kconfig
=> os/arch: Fix Kconfig syntax error at FS_TMPFS_HEAP_INDEX config

apps/system/utils/kdbg_heapinfo.c, apps/system/utils/kdbg_ps.c, apps/system/utils/kdbg_stackmonitor.c
kdbg commands use strtok for tokenizing stat info of proc.
But strtok is not thread-safe because it use a global variable, g_saveptr.
So it should be changed to strtok_r.
=> utils/kdbg: fix bug and change strtok to strtok_r for tokenizing stat info of proc

os/syscall/syscall_stublookup.c
=> syscall: fix wrong type in STUB_boardctl

os/arch/xtensa/src/esp32/esp32_gpio_lowerhalf.c
- before changing gpio direction, previous flag should be disabled.
- if INPUT & OUTPUT are set together, it occurs bugs.
=> arch/esp32/gpio: disable previous GPIO direction before changing

apps/examples/testcase/le_tc/network/tc_net_ioctl.c, external/curl/curl_config.h, external/grpc/third_party/cares/config-tizenrt.h, os/include/net/lwip/sockets.h, os/net/netdev/netdev_ioctl.c, os/net/socket/bsd_socket_api.c
- Current ioctlsocket() calls lwip_ioctl() but ioctlsocket API is for Window OS, so it needs to be replaced with ioctl().
Not to call lwip_ioctl() from the user space, socket ioctl operation with FIONREAD/FIONBIO commands will be handled in netdev ioctl.
=> Replace ioctlsocket() with ioctl()

lib/libc/netdb/lib_freeaddrinfo.c, lib/libc/netdb/lib_getaddrinfo.c
- netutils/netlib.h is in the external directory, can not be used in libc.
=> libc/netdb: Remove netutils/netlib.h header file reference

external/include/libcxx/locale, external/libcxx/string.cxx, lib/libc/stdlib/lib_wctomb.c, lib/libc/time/lib_localtime.c
direct write on errno may not be possible when syscall is enabled
=> libc, libcxx: fix direct use of errno

apps/examples/dnsclient_test/dnsclient_main.c, external/dhcpc/dhcpc.c, os/include/netdb.h, os/net/netdev/netdev_ioctl.c
- Existing dns client app and dhcpc call dns_setserver() which is in the kernel space directly.
The new code is added to call it by the ioctl function.
=> Add DNSSETSERVER type for a lwip ioctl to call dns_setserver()

os/mm/mm_heap/mm_malloc.c
In mm_size2ndx(), there is the logic that check if the request size is bigger than MM_MAX_CHUNK. So it's not necessary to have the same logic right before entering mm_size2ndx().
=> mm_heap/mm_malloc: remove redundant logic when getting nodelist index.

build/configs/artik05x/artik05x_download.sh
This commit adds provision to download/update a SINGLE binary for a single partition.
This don't verify against parrtitions in Kconfig/.config.
Example: make download bl2/BL2  <update only bl2>
make download ALL/all  <update all binaries for all partitions
menioned in .config or default paritions in Kconfig>
make download          <same as ALL/all >
=> Artik download script changes

README.md
To build on Windows,
Need git config before git clone.
=> Modify README.md for Windows build

os/drivers/task_manager/task_manager_drv.c, os/fs/procfs/fs_procfsproc.c, os/include/tinyara/sched.h, os/kernel/sched/sched_waitid.c, os/kernel/sched/sched_waitpid.c, os/kernel/task/task_exithook.c, os/kernel/task/task_reparent.c, os/kernel/task/task_setup.c
- sched/: Move fields related to parent/child task relationship out of TCB into group structure.
- sched/group : Update location of ppid according to the changes from tcb to group structure.
=> sched/group: Move fields related to parent/child task relationship out of TCB into group structure.

apps/examples/testcase/le_tc/network/tc_net_ioctl.c, os/include/net/lwip/sockets.h
The ioctl command FIONREAD is defined twice both in tinyara/fs/ioctl.h and net/lwip/sockets.h,
and lwip_ioctl fuction uses the command defined in tinyara/fs/ioctl.h.
We disable FIONREAD in net/lwip/sockets.h to avoid conflict.
The testcase 'tc_net_ioctl_fionread_n' was passed because the parameter FIONREAD which is defined in net/lwip/sockets.h didn't match that used in lwip_ioctl function.
So we change this testcase to a positive case because it works well with FIONREAD command.
=> Fix the network testcase 'tc_net_ioctl_fionread_n'

build/configs/artik05x/artik05x_download.sh
"make download ROMFS|romfs" doesn't work and is no more a valid interface.
It is replaced with "make download ROM|rom"
This patches adds necessary changes to make "make download ROM|rom" work
=> configs/artik05x: fix romfs download

apps/examples/testcase/ta_tc/media/utc/utc_media_focusrequest.cpp, framework/include/media/FocusManager.h, framework/include/media/FocusRequest.h, framework/include/media/stream_info.h, framework/src/media/FocusManager.cpp, framework/src/media/FocusRequest.cpp
User don't have to call FocusRequest methods directly.
FocusManager will call them internally.
=> framework/media: Conceal FocusRequest methods

apps/examples/testcase/le_tc/kernel/tc_roundrobin.c, apps/examples/testcase/le_tc/kernel/tc_umm_heap.c, apps/system/utils/kdbg_stackmonitor.c, external/libtuv/source/tinyara/uv_tinyara_signal.c, framework/src/eventloop/eventloop_loop.c, os/fs/procfs/fs_procfsproc.c, os/include/tinyara/mm/mm.h, os/include/tinyara/sched.h, os/kernel/sched/sched.h, os/kernel/sched/sched_cpuload.c, os/kernel/sched/sched_gettcb.c, os/kernel/sched/sched_verifytcb.c, os/kernel/task/task_activate.c, os/mm/mm_heap/mm_heapinfo.c
In each module, there is a pid hash definition, but all are same. So integrated them to one.
=> kernel: Unify the pid hash

.gitignore
ESP32 flash tools use python scripts,  pyc file pattern need to be added in gitignore.
=> gitignore: add pyc file pattern

os/net/lwip/src/api/sockets.c
- NET_DEVNAME is used nowhere.
=> os/net: Delete unnecessary defines

apps/system/utils/README.md
1. heapinfo supports -e, -r and -k options, but there was no description in README.
and for using heapinfo cmd, CONFIG_DEBUG_MM_HEAPINFO is mandantory, so changing the explanation for enabling the heapinfo cmd.
2. CONFIG_ENABLE_HEAPINFO is changed to CONFIG_ENABLE_HEAPINFO_CMD.
3. fix typo for irqinfo
=> system/utils/README : Update heapinfo cmd information

os/board/artik05x/userspace/Makefile
board/artik05x/userspace/tinyara_user.elf is copied to
build/output/bin/ and no longer required.
Verification:
run git status after build
=> board/artik05x: remove stale elf file after protected build

framework/src/wifi_manager/wifi_manager.c
- Return WIFI_MANAGER_ALREADY_CONNECTED when EVT_CONNECT occurs in connected state
=> framework/wifi_manager: Return already_connected in connected state

framework/src/st_things/things_stack/framework/things_data_manager.c
There can be a case which device has not enough memory to allocate.
And things_malloc can return NULL.
=> framework/st_things: Add error handling logic for data manager.

framework/src/wifi_manager/wifi_manager.c
- Return WIFI_MANAGER_FAIL for RECONNECT/RECONNECTING state,  when an invalid command (join/leave) comes from user application. Note that RECONNECT or RECONNECTING state should wait driver's callback not user command (except EVT_DEINIT).
=> framework/wifi_manager: Return WIFI_MANAGER_FAIL for invalid command

apps/examples/testcase/le_tc/filesystem/Kconfig
I made filesystem TC dependent on the !BUILD_PROTECTED setting.
reason1 : The file system TC has an API that calls the kernel context. Therefore, it is disabled in the BUILD_PROTECTED state.
reason2 : Because the file system TC is created for testing purposes, not for actual code, disabling BUILD_PROTECTED does not cause any problems
=> apps/examples/testcase: Add dependency configuration filesystem tc

os/board/common/partitions.c, os/fs/romfs/Kconfig
Since romfs uses FTL, it must be initialized when MTD_FTL is enable.
=> board/common : Modify the conditional statements when use romfs

framework/src/st_things/things_stack/framework/things_req_handler.c, framework/src/st_things/things_stack/logging/things_logger.c, framework/src/st_things/things_stack/logging/things_logger.h, framework/src/st_things/things_stack/utils/things_network.c
It can show the payload what attributes are included
when enabled the CONFIG_DEBUG_ST_THINGS_DEBUG config.
log format example:
IncomingRequest: (id: 0)
- resourceHandle: 0x00000000
- uri: "/capability/switch/main/0"
- property: 0x0
- flag: 0x0
REQUEST
OBSERVE
- method: 1
GET
- query: 'if=oic.if.baseline'
- values:
{"power":  "off"}
- dev_addr: adapter:00, flags:0x00, port:000
OutgoingResponse:
- resourceHandle: 0x0000000
- result: 0
- resourceUri: ''
- persistentBufferFlag: 0
- payload-type: 4 (Representation)
- uri: /capability/switch/main/0
- types:
x.com.st.powerswitch
x.com.st.powerswitch
- interfaces:
oic.if.baseline
oic.if.a
oic.if.baseline
oic.if.a
- values:
{"power":  "off"}
=> framework/st_things: Add function to debug payload for request/response.

build/configs/artik05x/scripts/user-space.ld, os/arch/arm/src/common/up_allocateheap.c, os/arch/arm/src/common/up_userspace.c, os/board/artik05x/userspace/up_userspace.c, os/include/tinyara/kmalloc.h, os/include/tinyara/mm/mm.h, os/include/tinyara/userspace.h, os/kernel/init/os_start.c, os/mm/mm_heap/mm_getheap.c, os/mm/umm_heap/umm_addregion.c, os/mm/umm_heap/umm_brkaddr.c, os/mm/umm_heap/umm_calloc.c, os/mm/umm_heap/umm_extend.c, os/mm/umm_heap/umm_heap.h, os/mm/umm_heap/umm_initialize.c, os/mm/umm_heap/umm_mallinfo.c, os/mm/umm_heap/umm_malloc.c, os/mm/umm_heap/umm_memalign.c, os/mm/umm_heap/umm_realloc.c, os/mm/umm_heap/umm_sem.c, os/mm/umm_heap/umm_zalloc.c
This commit contains below changes for MM:
- Back port Nuttx patch (59cc4a7a7b119536089a72ca91c5cb4d3399245a) for protected build MM changes to TizenRT.
- Make changes to handle mmheap structure as part of shared userspace object.
- Move the shared userspace object from Flash to RAM at beginning of user ram area.
=> Back-port Nuttx patch for protected build MM

os/board/Kconfig, os/board/common/Kconfig
A sub-title of flash partition was in board/Kconfig and it
prints sub-title before sourcing board/common/Kconfig.
Because of this, when it is not available, only sub-title
is come up without any config as shown below:
(4096) Page size of external flash memory (in bytes)
*** Board-Partition Options ***
To hidden it when it is not available, move it inside of
board/common/Kconfig and cover it using conditionals.
=> board/common: change a location of sub-title in Kconfig

os/mm/mm_heap/mm_getheap.c
os/mm/mm_heap/mm_getheap.c:50: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/mm/mm_heap/mm_getheap.c:50: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/mm/mm_heap/mm_getheap.c:51: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/mm/mm_heap/mm_getheap.c:51: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
=> mm: fix violations of coding rules

external/mbedtls/ssl_tls.c
- Remove a comparison logic of mallinfo fordblks and MBEDTLS_MAXIMUM_HANDSHAKE_MEMORY_USAGE
1) It increases unnecessary time overhead
2) fordblks shows the whole (discontinuous) heap size
3) Memory allocation failure will be returned if it fails
=> external/mbedtls: Remove redundant heap memory check logic

os/mm/mm_heap/mm_getheap.c
- Check the given memory address in all regions of user heaps.
- Refer the logic in `bool kmm_heapmember(FAR void *mem)`
@xixidodo @sunghan-chang
=> os/mm: Fix mm_get_heapindex logic

.gitignore, framework/src/iotbus/iotbus_spi.c, os/.gitignore, os/arch/arm/src/s5j/s5j_spi.c, os/arch/arm/src/s5j/s5j_spi.h, os/board/artik05x/src/artik05x_boot.c, os/drivers/spi/Kconfig, os/drivers/spi/Make.defs, os/drivers/spi/spi_uio.c, os/include/tinyara/fs/ioctl.h, os/include/tinyara/spi/spi.h
- Change the interface of spi driver in kernel to VFS
- Register SPI driver at /dev directory
- Change iotbus SPI API to operate to new SPI interface.
- Fix a bug in s5j spi driver
=> iotbus: Modifying SPI in iotbus to support binary separation

external/include/mbedtls/config.h, external/mbedtls/Makefile
- Unused mbedtls threading options are disabled.
- Unused source files are discarded from makefile.
=> external/mbedtls: Remove unused configs and source files

external/mbedtls/Makefile, external/mbedtls/easy_tls.c
- Several APIs defined easy_tls.c are used in applications such as CoAP and other branches.
- Add easy_tls.c in mbedtls Makefile
- Build error fix: type casting for malloc
=> external/mbedtls: Add easy_tls.c in Makefile

external/mbedtls/see_api.c
Add type casting logic to avoid warning(or build error) messages.
=> external/mbedtls: fix build warnings.

lib/libc/netdb/Make.defs, lib/libc/netdb/lib_freeaddrinfo.c, lib/libc/netdb/lib_gethostbyname.c, lib/libc/netdb/lib_getnameinfo.c, os/include/netdb.h, os/net/netdev/netdev_ioctl.c, os/net/socket/bsd_socket_api.c
Remove the implementation of gethostbyname and getnameinfo in bsd_socket_api.c,
and add them to libc/netdb not to directly call from user space to kernal space.
=> libc/netdb: Add gethostbyname and getnameinfo

os/include/tinyara/progmem.h
That is used in mtd_progmem.c file but there is no
prototype so that it causes a compilation warning as shown below:
driver/mtd/mtd_progmem.c:388:22: warning: implicit declaration of function 'up_progmem_blocksize' [-Wimplicit-function-declaration]
size_t blocksize = up_progmem_blocksize();
^~~~~~~~~~~~~~~~~~~~
Because other progmem prototypes like up_progmem_pagesize
are in progmem.h, let's add this there as well.
=> progmem: add prototype of up_progmem_blocksize

framework/src/st_things/things_stack/framework/things_sss_manager.c
We need some hash prefix based device uuid.
and it can have NULL('\0') character middle of string.
In previous, It has been using strlen to get length of hash
and it can return wrong length why the hash can get NULL in middle of string.
Now, It will use fixed length(32) for device UUID.
=> framework/st_things: fix bug which it can generate wrong hash value.

os/fs/tmpfs/fs_tmpfs.h, os/include/tinyara/kmalloc.h
Redefine memory alloc function when using multi heap at tmpfs header file
=> os/fs/tmpfs: Fix define memory alloc function

apps/examples/testcase/le_tc/kernel/tc_umm_heap.c, apps/system/utils/kdbg_stackmonitor.c, os/fs/procfs/fs_procfsproc.c, os/kernel/sched/sched_releasetcb.c, os/kernel/task/task_activate.c, os/mm/mm_heap/mm_heapinfo.c, os/mm/mm_heap/mm_sem.c, os/mm/umm_heap/umm_sem.c
1.     fs/procfs : Modify for getting Idle task's heap information in proc_entry_stat
Idle task's stack pointer is not in the heap. So that mm_get_heap with idle task's stack ptr returns NULL.
For getting idle task's heap information, called mm_get_heap_with_index(0).
2.     mm : Add NULL checking after mm_get_heap
mm_get_heap can return NULL, but there are no error checking, so it can be crashed.
=> mm : Modify about using mm_get_heap for NULL case

framework/src/media/stream_info.c
Fix a warning reported by SVACE, it's an invalid checking.
@Taejun-Kwon @junmin-kim
=> framework/media: Correct null pointer checking

apps/examples/testcase/le_tc/kernel/tc_timer.c, os/drivers/testcase/kernel_testcase_drv.c, os/include/tinyara/testcase_drv.h
Variables 'g_freetimers' and 'g_alloctimers' are required to
operate 'tc_timer_timer_initialize'. They are in kernel space.
so timer_initialize must test in virual driver.
=> testcase/kernel : Test timer_initialize in virtual driver

os/binfmt/libelf/gnu-elf.ld
Userspace memory allocator is statically linked to each application
and hence it would leverage the allocator to use per app heap object
which would be initialized during binary load time.
=> binfmt/libelf : place holder to keep user space heap object pointer

os/arch/xtensa/src/esp32/esp32_i2c.c, os/board/esp32_devkit/include/board.h
1. Keep the broad clock frequency same to the bootloader.
Otherwise, the clock in ESP32 would not be accurate.
2 .Update ESP32 i2c driver.
a. Fix the assert issue when no slave device connected.
b. Add large data transmission.
c. Update interrupt handler function of driver.
=>  arch/xtensa： Modify board clock frequency & update esp32 i2c driver.

build/configs/esp32_DevKitC/scripts/esp32_flash.ld, build/configs/esp32_DevKitC/scripts/esp32_iram.ld, build/configs/esp_wrover_kit/scripts/esp32_flash.ld, build/configs/esp_wrover_kit/scripts/esp32_iram.ld
Move section .data before .bss
Otherwise, when .bss section size is large, loader can not load .data to ram. 
There's error like below:
```text
I (113) esp_image: segment 0: paddr=0x00010020 vaddr=0x3ffe1f80 size=0x024b0 (  9392) load
E (122) esp_image: Segment 0 end address 0x3ffe4430 too high (bootloader stack 0x3ffe3be0 limit 0x3ffdfbe0)
E (133) boot: Factory app partition is not bootable
E (138) boot: No bootable app partitions in the partition table
```
@sunghan-chang 
@xixidodo 
@xiarihf
=> build/configs: Modify ld scripts for esp32

build/configs/artik05x/scripts/user-space.ld, os/arch/arm/src/common/up_allocateheap.c, os/include/tinyara/kmalloc.h, os/include/tinyara/mm/mm.h, os/include/tinyara/userspace.h, os/kernel/init/os_start.c, os/mm/mm_heap/mm_getheap.c, os/mm/umm_heap/umm_addregion.c, os/mm/umm_heap/umm_brkaddr.c, os/mm/umm_heap/umm_calloc.c, os/mm/umm_heap/umm_extend.c, os/mm/umm_heap/umm_free.c, os/mm/umm_heap/umm_heap.h, os/mm/umm_heap/umm_initialize.c, os/mm/umm_heap/umm_mallinfo.c, os/mm/umm_heap/umm_malloc.c, os/mm/umm_heap/umm_memalign.c, os/mm/umm_heap/umm_realloc.c, os/mm/umm_heap/umm_sem.c, os/mm/umm_heap/umm_zalloc.c
- Backport MM changes from nuttx
- Fix coding rule violations in previous commit
This is a resubmission of https://github.com/Samsung/TizenRT/pull/2746 after fixing all issues.
=> Memory management for binary separation

os/board/imxrt1050-evk/Kconfig
This patch eliminates the dependency of "MTD_FTL" option since "FS_ROMFS"
already depends on the "MTD_FTL".
=> board/imxrt1050-evk/Kconfig: Eliminate recursive dependecy on MTD_FTL

os/net/socket/bsd_socket_api.c
- A path for mbedtls missed in the example makefile is added.
- Duplicated typedefs for primitive data types are deleted in some network source code.
=> os/net: Modify return types of bsd socket APIs.

apps/examples/testcase/le_tc/kernel/tc_umm_heap.c
mem_ptr[alloc_cnt-1] maybe NULL because of invalid size,
then mm_get_heap will get default g_mmheap[0], that is
incorrect logic for multi-region case
@sunghan-chang @jeongchanKim
=> le_tc/kernel: refine tc_umm_heap_random_malloc

os/Kconfig.debug, os/arch/arm/src/stm32/stm32_spi.c, os/board/stm32f407-disc1/src/stm32_spi.c, os/board/stm32f429i-disco/src/stm32_spi.c, os/drivers/spi/spi_bitbang.c, os/drivers/spi/spi_uio.c, os/include/debug.h, os/include/tinyara/spi/spi_bitbang.c, os/include/tinyara/spi/spi_bitbang.h
SPI has the spidbg to print debug messages.
SPI debug message is definitely not important enough to use
dbg instead of spidbg.
Because of this, spi messages are printed at every boot time
when debug is enabled without spi debug.
up_spiinitialize: Prepare SPI0 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214
spi_uioregister: Registering /dev/spi-0
up_spiinitialize: Prepare SPI1 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214
spi_uioregister: Registering /dev/spi-1
up_spiinitialize: Prepare SPI2 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214
spi_uioregister: Registering /dev/spi-2
up_spiinitialize: Prepare SPI3 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214 …
=> drivers/spi: remove redifinition of spidbg to dbg

os/mm/mm_heap/mm_addfreechunk.c
in ascending order of physical address when the size is the same.
This can prevent higher address memory from being allocated
when lower address memory is available in the free nodelist.
Therefore, memory fragmentation can be mitigated.
=> mm_heap/mm_addfreechunk : sorting the free nodelist

os/board/esp32_devkit/src/Makefile
Object file partition.o isn't removed via "make clean",
then if changing related config, the file partition.c 
will not rebuild. 
Set DEVPATH,VPATH in Makefile to fix this issue.
=> Fix  esp32  board's Makefile issue.

framework/src/media/streaming/audio_decoder.cpp
If an 'else if' has a brace on one side, it should have it on both
=> framework/media: Add brace for readability

os/board/artik05x/src/Makefile
- A DEPPATH is added to fix a build error completely caused by partitions.o
=> os/board: Update the makefile of artik05x

build/configs/imxrt1050-evk/nxp_demo/defconfig, os/arch/arm/src/imxrt/imxrt_lowputc.c, os/arch/arm/src/imxrt/imxrt_lowputc.h, os/arch/arm/src/imxrt/imxrt_serial.c, os/include/debug.h
Kernel debug logs are not coming since some implementation for lldbg and dbg is missing. 
In this PR, I have done following:
- Fix implementation of lldbg
- Redirect dbg to lldbg (This is temporary and will be reverted when dbg implementation in imxrt is fixed)
- Enabled CONFIG_DEBUG and CONFIG_DEBUG_ERROR
=> imxrt : Fix kernel debug logs

os/arch/arm/src/imxrt/Make.defs, os/arch/arm/src/imxrt/imxrt_start.c
Fix build error due to MPU init in flat build.
Include mpu init under protected build config.
=> Fix build error due to MPU init

os/arch/arm/include/armv7-m/irq_lazyfpu.h, os/arch/arm/src/armv7-m/up_copyarmstate.c, os/arch/arm/src/imxrt/Make.defs, os/arch/arm/src/imxrt/imxrt_allocateheap.c, os/arch/arm/src/imxrt/imxrt_mpuinit.c, os/arch/arm/src/imxrt/imxrt_start.c
MPU settings are not done properly. This results in build and boot up
issues in flat and protected build. Make changes to fix this.
- Remove MPU registers from list of context registers
- Remove code to initialize or save MPU registers in context
- Fix src and Makefile with proper usage of CONFIG_PROTECTED flag
=> Fix issues with MPU settings

os/binfmt/Makefile, os/binfmt/binfmt_loadbinary.c, os/binfmt/elf.c, os/binfmt/libelf/libelf_init.c, os/binfmt/libelf/libelf_read.c, os/include/tinyara/binfmt/binfmt.h, os/include/tinyara/binfmt/elf.h
elf size will be read from header instead of stats
elf offset will be shifted by the size of binary header
config name will be corrected to binary manager config later.
=> libelf: Support for binary loading from MTD part 

os/board/common/partitions.c, os/fs/driver/mtd/mtd_partition.c, os/include/tinyara/fs/mtd.h
drivers/mtd/mtd_partition.c: Copy the partition name to internal buffer so that the caller can free the name argument
drivers/mtd/mtd_partition.c: Remove the hard code partition name length
os/board/common : Fix a partition name parsing logic in 'configure_partitions'
=> partition : Modify about the name in mtd

apps/system/utils/kdbg_heapinfo.c, os/binfmt/binfmt_execmodule.c, os/binfmt/libelf/libelf_addrenv.c, os/binfmt/libelf/libelf_ctors.c, os/binfmt/libelf/libelf_dtors.c, os/drivers/heapinfo/heapinfo_drv.c, os/include/tinyara/fs/ioctl.h, os/mm/mm_heap/mm_heapinfo.c
1. Change no syscall API to syscall API : sched_gettcb to sched_getparam
2. Remove unnecessary codes
3. Add return address param for mm_malloc
=> heapinfo : Modify heapinfo to run in protected build

os/mm/mm_heap/mm_malloc.c
1. mm/mm_heap/malloc: change a dbg level to error for failure case 
2. mm/mm_heap/malloc: fix a typo and tidyup
=> mm/mm_heap/malloc: tidyup

os/arch/Kconfig, os/include/tinyara/kmalloc.h, os/mm/Kconfig, os/mm/umm_heap/umm_calloc.c, os/mm/umm_heap/umm_malloc.c, os/mm/umm_heap/umm_zalloc.c
Allow alloc memory on spiram with common malloc/calloc/zalloc
1.apply simple strategy use CONFIG_RAM_MALLOC_PRIOR_INDEX in umm api.
start alloc from this index, default 0, while set 1 to malloc from spiram
2. in kmalloc.h, when enable spiram, use alloc_at(0) for kumm and kmm api
to alloc internal ram for them
@sunghan-chang
=> os/mm/umm_heap: add common logic to support esp spiram

framework/include/media/stream_info.h
This statement is needed to use C linkage
=> framework/media: Add missed extern C

os/board/common/partitions.c, os/board/esp32_devkit/src/Makefile, os/board/esp32_devkit/src/esp32_boot.c
Add header file for building partitions.c, to clean up build warnings.
=> Add header for fixing build warnings of file partitions.c

external/esp_idf_port/esp32/esp32_wifi_os_adapter.c
A crash may happens when we call work_cancel() and
pass an uninitialized work_s structure (work_s.worker is not NULL).
Apply this patch to initilize work_s structure after allocated.
Signed-off-by: zhouxinhe xinhe.zhou@samsung.com
=> external/esp_idf: Initialize timer structure before using

os/arch/xtensa/src/xtensa/xtensa_blocktask.c, os/arch/xtensa/src/xtensa/xtensa_unblocktask.c
If CONFIG_RR_INTERVAL is not defined, there are build errors.
=> arch/xtensa: fix build error when CONFIG_RR_INTERVAL is not defined

external/websocket/websocket.c
When handshake, client informs "error key length". Client should use WEBSOCKET_ACCEPT_KEY_LEN to judge the length of accept key instead of WEBSOCKET_CLIENT_KEY_LEN.
=> external/websocket : fix key length error

os/tools/mkchecksum.py
This script prepends the binary file with the crc32 hash value.
=> os/tools : Create a crc32 hash value with file data for verification

build/configs/esp32_DevKitC/scripts/esp32.template, build/configs/esp_wrover_kit/scripts/esp32.template
Narrow the range of esp32's dram0 segment as extral
memory during booting is not available.
after booting, the additional memory will add to heap usage.
=> build/configs: Narrow the range of esp32's dram0 segment.

apps/examples/elf/Makefile
This patch fix the build error due to previous distclean failure.
=> apps/examples/elf: add distclean command support

build/tools/esp32/esptool_py/Makefile
Modify the image downloading command from "make download APP" to "make download OS".
=> build/tools: Fix image downloading issue for esp32 board.

apps/examples/testcase/le_tc/kernel/tc_libc_misc.c, apps/examples/testcase/le_tc/kernel/tc_libc_syslog.c, os/arch/arm/src/armv7-m/mpu.h, os/include/debug.h
* First patch adds dependency on Protected build on the following TC's: lldbg, llvdbg, lowsyslog, lowvsyslog. These API's call up_lowputc which is not accessible from userspace.
* Second patch eliminates the redirection of dbg to lldbg commands.
* Also, "dbg" cannot be called prior to driver registration since it uses write system call. So, this patch changes "dbg" to "lldbg" prior to driver registration.
=> os/include/debug.h : Revert dbg commands re-direction.

apps/examples/wifi_manager_sample/wm_test.c, framework/include/wifi_manager/wifi_manager.h
- Add various authentication and crypto methods defined in wifi_manager
- AUTH: open, wep_shared, wpa, wpa2, wpa12, wps, and enterprise
- CRPYTO: none, wep_shared 64/128, aes, tkip, mixed, and enterprise
=> apps/examples/wifi_manager_sample: Supporting various auth/crypto

external/esp_idf_port/esp32/esp32_wifi_os_adapter.c
Add logic for SPIRAM enable case in wifi_os_adapter,
to alloc from DRAM instead of external ram for internal alloc api
@sunghan-chang
=> external/esp_idf_port: refine wifi internal alloc api

os/arch/arm/src/imxrt/imxrt_start.c
Boot failure happening due to improper FlexRAM configuration in case of
DTCM usage. It is mandatory to have 64KB FlexRAM allocated for OCRAM at
all times. Due to this max size of DTCM is limited to 256KB. Issue was
happening because we were configuring complete 512KB FlexRAM as DTCM.
Change this configuration to reserve 64KB for OCRAM and 256KB for DTCM.
=> arch/arm/imxrt : Configure FlexRAM banks for DTCM and 64KB OCRAM

os/mm/umm_heap/umm_malloc.c, os/mm/umm_heap/umm_zalloc.c
For protected build, USR_HEAP will be automatically mapped to user heap address.
Sometimes, g_mmheap is not the meaning of the user heap anymore.
=> mm/umm_heap : Change g_mmheap to USR_HEAP

os/ProtectedLibs.mk
For using framework in user, libframework should be included to USERLIB
=> ProtectedLibs.mk : Add libframework to USERLIB

os/arch/arm/src/imxrt/imxrt_start.c
Fix build error in imxrt1020x/nxp_demo config by adding proper
config.h file based on IMXRT chip version.
=> os/arch/arm/src/imxrt: Fix imxrt config include path

apps/examples/elf/Makefile, apps/examples/elf/micomapp/Makefile, apps/examples/elf/wifiapp/Makefile
Add verification of elf using nm command,  since the elf are relocatable undefined symbols will not be considered as error during linking. With this check build will stop if any undefined symbols is observed during build.
=> Exit build on undefined symbols in elf

apps/examples/security_test/see_api/see_test_main.c
- Add '#include <stdlib.h>' in see_test_main.c to use 'atoi'
=> apps/examples/security_test: Add stdlib.h for atoi in see test app

apps/examples/wifi_manager_sample/wm_test.c
- result[2] used in get_auth_type function can be null when the network is not enterprise WiFi. Therefore, we add null check logic of result[2], not to be used as an input of strcmp, which causes crash in specific board.
=> apps/wm_test: Add string null check logic in get_auth_type

os/arch/xtensa/src/esp32/esp32_allocateheap.c, os/arch/xtensa/src/xtensa/xtensa.h, os/board/esp32_devkit/src/esp32_boot.c
move forward the spiram initialization, before os_start, to make
this external memory available during os_start. it's necessary
for the module like net(lwip) initialization
@xixidodo @sunghan-chang
=> os\arch\xtensa:refine the esp32 spiram initialization

framework/src/st_things/things_stack/framework/things_data_manager.c, framework/src/st_things/things_stack/framework/things_security_manager.c
"certificate" and "privatekey" attributes are not needed
when the H/W certification feature is enabled.
=> framework/st_things: disable attributes when enable H/W certifications.

os/Makefile.unix
remove duplicate prerequisite for include/arch/board target
=> os/Makefile.unix: remove duplicate prerequisite

build/configs/imxrt1050-evk/imxrt1050-evk_download.sh, os/kernel/binary_manager/binary_manager_load.c, os/kernel/binary_manager/binary_manager_recovery.c
- build/imxrt1050: fix wrong path of binary output
- kernel/binary_manager: modify free to kmm_free in binary manager
=> binary_manager: Fix wrong usages of binary manager

os/include/debug.h, os/se/Kconfig, os/se/sss/Kconfig, os/se/sss/security_hal_wrapper.c
- Remove printf in security_hal_wrapper.c
- Define debug configs and corresponding modules in debug.h
- Use sidbg (or sivdbg) instead of printf
=> os/se/sss: Add security hal isp wrapper debug in debug.h

apps/examples/err_report_demo/err_report_main.c
Add application feature to print error report information. This feature is particularly useful when the device does not have an active network connection to a error reporting server.
=> [apps/examples/err_report_demo]: Fetch error report from console

os/arch/arm/src/imxrt/Make.defs, os/arch/arm/src/imxrt/imxrt_flexram.c, os/arch/arm/src/imxrt/imxrt_flexram.h, os/arch/arm/src/imxrt/imxrt_semc.c, os/arch/arm/src/imxrt/imxrt_semc.h, os/arch/arm/src/imxrt/imxrt_semc_sdram.c, os/arch/arm/src/imxrt/imxrt_semc_sdram.h, os/board/imxrt1020-evk/src/imxrt_boot.c
SDRAM can be access by SEMC
in menuconfig, the following setting should be enabled
Built-in Libraries
[*] sizeof(_Bool) is 8-bits
=> Add sdram function by SEMC interface in IMXRT

apps/examples/testcase/le_tc/kernel/tc_timer.c
Timer make direct calls to kernel specific structures
which results in assert. In continuation with PR no: 3003
So this patch adds config dependency for above mentioned kernel testcase.
Signed-off-by: Nilabh <n.shant@partner.samsung.com>
=> testcase/le_tc/kernel: Add protected build dependency in timer testcases to resolve asserts

external/esp_idf_port/esp32/esp32_wifi_utils.c
external/esp_idf_port: Reduce ESP32 softAP beacon interval.
Reduce ESP32 softAP beacon interval from max(60000ms) to 100ms,
to fix station join is not stable issue.
=> Fix station join is not stable for ESP32 wifi sotfap mode.

os/arch/arm/src/imxrt/Kconfig, os/arch/arm/src/imxrt/Make.defs, os/board/imxrt1020-evk/src/imxrt_boot.c, os/board/imxrt1050-evk/src/imxrt_boot.c
Configuration of SEMC is not working with source code.
There are some configurations in Kconfig of imxrt but they are not used.
Let's cover semc source files with appropriatary configs.
To use SEMC, CONFIG_C99_BOOL8 should be turned on.
Let's make a dependency with it to enable it automatically.
=> imxrt/semc: make a dependency with C99_BOOL8 and cover it with CONFIG

os/arch/arm/src/armv7-m/mpu.h, os/binfmt/binfmt_exec.c
os/arch/arm/src/armv7-m/mpu.h:664: ERROR: [BRC_M_FTN] open brace '{' following function declarations go on the next line
os/binfmt/binfmt_exec.c:215: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/binfmt/binfmt_exec.c:215: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
=> fix violations of coding rules

os/dbuild.sh
CONFIG_BUILD_PROTECTED and CONFIG_APP_BINARY_SEPARATION use
different type of binary. Let's add them in dbuild to support
download command.
=> dbuild: add imxrt binary types for binary separation

os/kernel/init/os_bringup.c
The preapp task which launches TASH and system tasks does not
have any dependency with binary manager.
So, it should be outside of binary manager conditional.
This commit fixes an issue that TASH is not come up.
=> kernel/init: start the preapp task regardless of binary manager

os/kernel/init/os_bringup.c
preapp task should be created regardless of Binary Manager until now.
It will be modified to be merged into binary manager.
=> init/os_bringup : Move the preapp task creation

os/board/imxrt1020-evk/Kconfig, os/drivers/seclink/Kconfig
This commit fixes belows:
drivers/seclink/Kconfig:14:warning: multi-line strings not supported
fs/romfs/Kconfig:6:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
fs/romfs/Kconfig:6:	symbol FS_ROMFS depends on MTD_FTL
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
fs/driver/mtd/Kconfig:63:	symbol MTD_FTL is selected by IMXRT_AUTOMOUNT_ROMFS
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
board/imxrt1020-evk/Kconfig:74:	symbol IMXRT_AUTOMOUNT_ROMFS depends on FS_ROMFS
=> driver/seclink, board/imxrt1020-evk: fix errors of Kconfig usages

apps/examples/binary_update/binary_update_main.c
User can decide execution repetition count like below:
Usage : binary_update [OPTIONS]
Options:
-r start : Execute Binary Update Example infinitely until stop cmd.
stop  : Stop the Binary Update Example infinite execution.
-n COUNT : Execute Binary Update Example COUNT-iterations.
Expected result for one-time execution>
```
TASH>>binary_update
** Binary Update Example : executes one-time.
** Binary Update GETINFO [micom] test.
========= binary [micom] info ==========
Version | Partsize | Inactive part
---------------------------------------
20190421 |   131072 | /dev/mtdblock3
========================================
** Binary Update GETINFO [wifi] test.
========= binary [wifi] info ==========
Version | Partsize | Inactive part
---------------------------------------
20190412 |   262144 | …
```
=> apps/examples/binary_update : Add example repetition functionality.

build/configs/imxrt1050-evk/imxrt1050-evk_download.sh, build/configs/imxrt1050-evk/imxrt1050-evk_get_filename.sh, build/configs/imxrt1050-evk/imxrt1050-evk_make_bin.sh, build/configs/imxrt1050-evk/loadable_elf_apps/Make.defs, build/configs/imxrt1050-evk/messaging_sample/Make.defs, build/configs/imxrt1050-evk/nxp_demo/Make.defs, build/configs/imxrt1050-evk/nxp_demo_protected/Make.defs, build/configs/imxrt1050-evk/tc-protected/Make.defs
1. configs/imxrt1050-evk: add MAKE_BOARD_SPECIFIC_BIN support
2. configs/imxrt1050-evk: split a part of making imxrt-specific binary from download script
=> configs/imxrt1050-evk: split making imxrt-specific binary from download script

build/configs/imxrt1050-evk/scripts/memory.ld
The linker script has the length of each part in kilbytes, not in kilobits.
To avoid giving wrong information, let's modify Kb to KB.
=> configs/imxrt1050-evk: fix description of ld script, Kb -> KB

os/arch/arm/src/armv7-m/up_assert.c, os/arch/arm/src/armv7-r/arm_syscall.c, os/include/assert.h, os/kernel/binary_manager/binary_manager.c, os/kernel/binary_manager/binary_manager_recovery.c
This patch adds support of abort handling in fault manger for armv7-m architecture.
All kinds of hard faults is handled by fault manager.
=>  arch/armv7-m/up_assert: Add abort handling in fault manager for armv7-m

os/arch/arm/src/imxrt/imxrt_mpuinit.c, os/arch/arm/src/imxrt/mpu-reg.h
If SD RAM is enabled, then we allocate kernel heap region on SD RAM.
This patch adds MPU protection for this heap region. Also, we will
use enum based region type to region number mapping.
=> Add MPU setting for SD-RAM kernel heap

os/arch/arm/src/imxrt/Make.defs
When LPSRTC is enabled, its config enables hprtc by selecting.
It means that Make.defs does not need the hprtc file to include
compilation under lpsrtc. Make.defs can include hprtc under hprtc
conditional.
=> arch/imxrt: split hprtc conditional from lpsrtc in Make.defs

build/configs/esp32_DevKitC/scripts/esp32.template, build/configs/esp_wrover_kit/scripts/esp32.template
the main modifcation is as below.
1) modify iram0_2_seg length.
2) modify drom0_0_seg offset and length.
and the modification is  originated from esp-idf 
(1) commit id: c230e4280c039b0b709d54e974f63eed358c1c2a
Limit DROM/IROM section lengths correctly
(2) d92c541b1a75d7ced244e73b5c840511f03e348a
esptool: Optimise generated image size by using RAM-loaded data for padding
=> build/configs: modify esp32 link script's IROM/DROM layout

external/esp_idf_port/Makefile
Rename esp32 wpa_supplicant crypto filename as below:
md5.c->md-5.c, sha1.c->sha-1.c, sha256.c->sha-256.c
as files by the same name also exist at directory TizenRT/external/mbedtls,
when linking libexternal.a, these files will lead collision.
=> external/esp_idf_port: Rename esp32 wpa_supplicant crypto filenames.

docs/HowToAddStaticLibrary.md, os/Makefile.unix, os/Makefile.win, os/arch/arm/src/Makefile, os/arch/xtensa/src/Makefile
APP's Makefile uses BIN_DIR to save installable application
binary with Kernel build. It is duplicated with BIN_DIR of
Makefile.unix. Let's rename BIN_DIR to OUTBIN_DIR at os side.
=> Makefile: rename BIN_DIR to OUTBIN_DIR at os side

os/kernel/binary_manager/binary_manager.c, os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_load.c, os/kernel/binary_manager/binary_manager_recovery.c
Binary manager handles fault recovery without recovery thread
=> kernel/binary_manager: remove binary recovery thread

apps/examples/iotbus_test/iotbus_test_main.c, apps/examples/st_things/blink/blink.c, apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c, framework/include/iotbus/iotbus_gpio.h, framework/src/iotbus/iotbus_gpio.c
Commit 8bea8eb: 
framework/iotbus: Add enumerator for GPIO signal vale
- Define IOTBUS_GPIO_LOW and IOTBUS_GPIO_HIGH as 0 and 1, respectively
- Modify iotbus_gpio_write function input from int to enum
Commit 737e676
apps/examples: Modify GPIO utc of iotbus_gpio_write
- Apply the new definition of IOTBUS_GPIO_LOW and IOTBUS_GPIO_HIGH for iotbus_gpio_write function input
=>  framework/iotbus: Add enumerator for GPIO signal vale

os/Makefile.unix
It is possible to get several types of binary output files like
getting both hex and bin. So, let's revert a part of commit 9b36e2e.
=> Makefile: revert unifying codes of making binary output files

os/drivers/lwnl/Kconfig, os/drivers/lwnl/slsi_drv.c, os/include/debug.h, os/include/tinyara/lwnl/slsi_drv.h
- Modify SLSI driver to a generic vendor-specific driver log in debug.h
- Modify the corresponding log in slsi_drv.c and slsi_drv.h
- Add DEBUG_ERROR or DEBUG_VERBOSE dependency in Kconfig
=> os/debug: Remove vendor-specific dependency in debug

apps/system/binary_update/binary_update.c, os/include/tinyara/binary_manager.h, os/kernel/binary_manager/binary_manager.c, os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_load.c, os/kernel/binary_manager/binary_manager_recovery.c
In fault recovery, remove all tcb of tasks/pthreads created by same loaded task from readytorunlist only without calling task_terminate.
After that, they are terminated before binary manager reload binary.
=> kernel/binary_manager: refactor binary manager recovery

os/kernel/binary_manager/binary_manager.h
Binary manager has the highest priority, 255 and loading thread is created with priority 200.
=> kernel/binary_manager: change priority of threads and loading thread name

os/board/imxrt1050-evk/src/Makefile
To build a file from another path, DEPPATH should be added.
This commit fixes a compilation error as below:
make[2]: Entering directory '/TinyAra/Forked_TizenRT/os/board/imxrt1050-evk/src'
Makefile:126: recipe for target '.depend' failed
make[2]: *** [.depend] Error 1
=> board/imxrt1050-evk: fix a compilation error

os/binfmt/binfmt_loadbinary.c
The task loaded by binary manager has same signal mask with binary manager.
That's because when a task or thread is created, it inherits signal mask from parent task.
Binary manager blocks all signals excluding SIGKILL so we need to clean it.
=> binfmt/loadbinary: Set signal mask of task loaded by binary manager

os/include/fixedmath.h, os/include/limits.h, os/include/tinyara/math.h
This patch fixes coding violations in the header files.
=> os/include: Fix coding guideline violations in headers

os/Kconfig.debug
a(ll)(v)dbg are defined in debug.h but there is no config in Kconfig.
It makes not available to use debug messages on adc.
This commit adds CONFIG_DEBUG_ANALOG(_ERROR, _WARN, _INFO).
=> Add adc debug configs support in Kconfig.debug

build/configs/imxrt1050-evk/imxrt1050-evk_make_bin.sh
When script makes final binary, it adds padding upto partition size.
But if partition size is smaller than binary size, it becomes a huge value
because of negative.
This commit prevents to make wrong binary with huge size.
=> configs/imxrt1050-evk: add comparing partition size and binary size

os/board/imxrt1050-evk/userspace/imxrt_userspace.c, os/include/tinyara/userspace.h
This patch adds config check for system pre-application init.
Signed-off-by: Nilabh <n.shant@partner.samsung.com>
=> imxrt1050-evk/userspace: Add config dependency (CONFIG_SYSTEM_PREAPP_INIT)

framework/src/iotbus/iotbus_spi.c, os/arch/arm/src/s5j/s5j_spi.c, os/board/imxrt1050-evk/src/imxrt_boot.c, os/drivers/spi/spi_uio.c, os/include/tinyara/spi/spi.h
TizenRT register SPI to driver following format "spi-{bus}", But
iotbus tried to open it with spi{bus} so it causes errors on ITC and
UTC.
Issues found: TizenRT Daily Quality Status [ Platform - 2019-05-18 ]
=> iotbus: fix spi open error in iotbus

os/fs/vfs/fs_ioctl.c
A header file called "net/if.h" is needed when network module is
on. so it should be inside CONFIG_NET macro.
=> network: fix build error while network feature turn off.

apps/system/utils/Kconfig, apps/system/utils/utils_stackmonitor.c, os/arch/xtensa/src/xtensa/xtensa_checkstack.c
For esp32 case, the peek stack size of stack-monitor-daemon is more than 1024 bytes.
- It's necessary to increase the default size
- Remove a building error when stkmon enabled.
=>  apps/system/utils: Increase stack monitor daemon stack size

os/arch/xtensa/include/stdarg.h
`stdarg.h` is required in some modules.
=> arch/xtensa: add header file stdarg.h

os/include/tinyara/mm/mm.h, os/mm/mm_heap/mm_getheap.c, os/mm/mm_heap/mm_partition_mgr.c
When App Separation is enabled, then we are getting error log from mm_get_heap.
This is because, the mm_get_heap is designed to search for the address in kernel
and user heap only. However, since we added new heaps for each application and
also a different heap for partition manager, we need to add more logic to the
mm_get_heap() API to search for the address in the app heaps if it could not be
found in the kernel and user heap.
=> os/mm/mm_heap: Fix error in mm_get_heap when App separation is enabled

os/arch/arm/src/armv7-m/mpu.h, os/include/debug.h
* This patch eliminates the re-direction of dbg to lldbg
commands.
* Also, "dbg" cannot be called prior to driver registration
since it uses write system call. So, this patch changes
"dbg" to "lldbg" prior to driver registration.
=> os/include/debug.h: Remove re-direction of dbg to lldbg

os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_recovery.c
When binary manager handles a fault, All children created in a same binary are excluded from scheduling.
At this time, we need to remove the TCB from the task list associated with the state.
=> kernel/binary_manager: Remove the TCB from the task list associated with the state in recovery

external/esp_idf_port/esp32/esp32_wifi_os_adapter.c
Replace CONFIG_MM_REGIONS to CONFIG_MM_NHEAPS.
For malloc_at functions relates to memory Heaps, not Regions.
=> external/esp_idf_port: Fix a memory heap region macro usage error.

apps/examples/elf/micomapp/Makefile, apps/examples/elf/wifiapp/Makefile, os/binfmt/binfmt_loadbinary.c, os/binfmt/binfmt_loadmodule.c, os/binfmt/elf.c, os/include/tinyara/binary_manager.h, os/include/tinyara/binfmt/binfmt.h, os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_load.c, os/tools/mkbinheader.py
Added binary priority and stack size to the binary header.
It can set the priority and stack size when loading binary
by loading header.
=> kernel/binary_manager : Set priority and stack size when loading binary

apps/examples/elf/Kconfig, apps/examples/elf/micomapp/Makefile, apps/examples/elf/micomapp/messaging.c, apps/examples/elf/micomapp/micomapp.c, apps/examples/elf/micomapp/micomapp_internal.h, apps/examples/elf/wifiapp/Makefile, apps/examples/elf/wifiapp/messaging.c, apps/examples/elf/wifiapp/wifiapp.c
This sample tests the messaging framework.
Micom is a receiver and Wifi is a sender for communication.
Repetition version will be updated with another commit.
Expected Result>
=== Messaging F/W Test : 1-th iteration. ===
--- Sync Send & Block Receive Test. ---
[WIFI] - Send [sync_block_msg] data with sync mode.
[MICOM] Success to receive with block mode in receiver. msg : [sync_block_msg]
[MICOM] - Reply to sender [reply_msg] data.
[WIFI] Success to receive reply from receiver. msg : [reply_msg]
--- NoReply Send & NonBlock Receive Test. ---
[WIFI] - Send [noreply_data] data with noreply mode.
[MICOM] Success to receive with non-block mode in recv callback from PID(8). msg : [noreply_data]
--- Multicast Send & Receive Test. ---
[WIFI] - Send Multicast [multi_msg] data.
[MICOM] Success to …
=> examples/elf : Add Messaging F/W Sample

os/arch/arm/src/armv7-r/arm_assert.c
As binary manager is updated a bit. This patch modifies the
assert handler to work with binary manager for armv7-r.
updated the message queue used in assert handler to use the binary manager message queue.
=> os/arch/arm/src/armv7-r/arm_assert: Update assert handler

apps/examples/mediaplayer/mediaplayer_main.cpp, framework/src/media/utils/MediaUtils.cpp
1. Trying to free an uninitialized pointer `header` is dangerous.
2. Add missing `break`.
=> framework/media: Remove unnecessary code and add missing break

apps/examples/testcase/ta_tc/security/utc/utc_auth.c, apps/examples/testcase/ta_tc/security/utc/utc_keymgr.c, apps/examples/testcase/ta_tc/security/utc/utc_ss.c, framework/src/security/security_auth.c, os/se/virtual/hal_virtual.c
There are several issues in security UTC.
1) confuse asymmetric key list and symmetric key list which are
defined at UTC. so it causes unexpected errors
2) there is no logic that checks whether seconds public key is
exist. so it allocate unused memory for key and make an error.
=> security/utc: Fix security UTC bug

apps/examples/testcase/le_tc/kernel/tc_libc_math.c
Add libc math gamma testcase to improve coverage.
artik053 log :
U-Boot 2017.01-g59977f7 (Nov 23 2017 - 16:09:49 +0900)
CPU:   Exynos200 @ 320 MHz
Model: ARTIK-053 based on Exynos T20
DRAM:  946 KiB
WARNING: Caches not enabled
BL1 released at 2017-3-13 15:00
SSS released at 2017-09-12
WLAN released at 2017-11-30
Flash: 8 MiB
*** Warning - bad CRC, using default environment
In:    serial@80180000
Out:   serial@80180000
Err:   serial@80180000
Hit any key to stop autoboot:  0
gpio: pin gpg16 (gpio 46) value is 1
s5j_sflash_init: FLASH Quad Enabled
i2c_uioregister: Registering /dev/i2c-0
i2c_uioregister: Registering /dev/i2c-1
up_spiinitialize: Prepare SPI0 for Master operation
up_spiinitialize: Prepare SPI1 for Master operation
up_spiinitialize: Prepare SPI2 for Master operation …
=> apps/examples/testcase : add libc math testcase

os/binfmt/Kconfig
Currently BINFMT_CONSTRUCTORS and SYMTAB_ORDEREDBYNAME are outside of
!BINFMT_DISABLE conditional. But they are valid in !BINFMT_DISABLE conditional.
Let's cover them also.
=> os/binfmt: cover all of configs with !BINFMT_DISABLE

os/kernel/Kconfig, os/kernel/binary_manager/binary_manager.c
Add some dependencies of binary manager, APP_BINARY_SEPARATION, BINFMT_LOADABLE, !DISABLE_MQUEUE, FLASH_PARTITION, MTD_FTL and MTD_PARTITION_NAMES.
and missing !CONFIG_DISABLE_SIGNALS for using signal.
=> kernel/binary_manager: Add dependency of binary manager

os/arch/Kconfig, os/arch/arm/src/armv7-m/up_doirq.c, os/arch/arm/src/armv7-m/up_lazyexception.S
This patch adds the support of nested interrupts for armv7-m
architecture.
Signed-off-by: Drashti Parikh <p.drashti@partner.samsung.com>
=> arch/arm/src/armv7-m: Add support of nested interrupts

os/arch/arm/src/imxrt/imxrt_gpt.c
There are two functions of setting clock divider, imxrt_gpt_setclockdivider and
imxrt_gpt_setoscclockdivider.
When clock source is kGPT_ClockSource_Osc, imxrt_gpt_setoscclockdivider should
be used to set.
But imxrt_gpt_init function only uses setclockdivider so that it is wrong with
OSC clock.
This commit adds a conditional to check clock source and uses proper function.
=> arch/imxrt/gpt: set proper divider with clock source in imxrt_gpt_init

os/board/imxrt1050-evk/src/imxrt_boot.c
1. Include <stdio.h> and <stdint.h>
stdio.h for snprintf
stdint.h for uint8_t
2. Remove duplicated <tinyara/gpio.h>
There are two includings.
3. Remove unnecessary headers for imxrt1020-evk
The imxrt_boot.c under os/board/imxrt1050-evk/src folder is built
only when imxrt1050-evk is selected.
It is never built with imxrt1020-evk.
=> board/imxrt1050-evk: tidyup including headers in imxrt_boot.c

os/se/sss/security_hal_wrapper.c
- Return success for sss_hal_init and sss_hal_deinit
- Remove unnecessary empty space
=> os/se/sss: Modify return value of sss wrapping layer

os/kernel/Kconfig
FLASH_PART_SIZE, FLASH_PART_TYPE and FLASH_PART_NAME have a string type, not bool type.
So we need to make a condition that these values are not NULL.
=> kernel/binary_manager: Fix wrong dependency conditions

framework/src/st_things/things_stack/utils/things_network.c
Error has been showing during Wi-Fi state changing.
It guesses that side effect of IPC changes. 
And now, there is no callback api about Wi-Fi state changes like "stop_softap_done".
So, It is one of refactoring point for st_things. 
In future, sleep will be changed to some callback to get result of Wi-Fi state changing.
=> framework/st_things: Increase sleep time to apply Wi-Fi state changing.

apps/examples/esp32_wifi_demo/Kconfig, apps/examples/esp32_wifi_demo/Make.defs, apps/examples/esp32_wifi_demo/Makefile, apps/examples/esp32_wifi_demo/esp32_wifi_demo.c, apps/examples/esp32_wifi_demo/softap.c, apps/examples/esp32_wifi_demo/station.c
Add espressif esp32 wifi demo program, this code directly call
wifi driver interface instead of TizenRT WiFi Manager. Adding it
helps debug wifi defect.
it mainly implement below function:
1) if choose station mode, configure proper AP ssid and passwd,
it can connect to AP  and get ip address (DHCP)
2) if choose softap mode,  it runs as AP with configured AP ssid and passwd.
then other client can connect it if know the passwd, and can assign ip to connect client. (DHCP)
=> apps/examples/esp32_wifi_demo: Add espressif wifi demo.

os/arch/arm/src/imxrt/imxrt_gpio_lowerhalf.c
- if gpio irq config is not configured, disable irq attach logic
=> arch/imxrt: modify gpio irq attach logic depending on IRQ config

os/kernel/Kconfig
CONFIG_FLASH_PART_SIZE and CONFIG_FLASH_PART_TYPE have string type and are defined if CONFIG_FLASH_PARTITION is enabled.
Similarly CONFIG_FLASH_PART_NAME is enabled, if CONFIG_FLASH_PARITION and CONFIG_MTD_PARTITION_NAMES are enabled.
So binary manager has a dependency on CONFIG_FLASH_PARTITION and CONFIG_MTD_PARTITION_NAMES.
=> kernel/binary_manager: Fix wrong dependency

apps/examples/grpc_greeter_client/.gitignore, apps/examples/grpc_route_client/.gitignore
- `./` doesn't mean current directory.
- `*.grpc.pb.h`, `*.grpc.pb.cc` are unnecessary since `*.pb.h`,
`*.pb.cc` include them.
=> examples/grpc_*: Fix .gitignore

os/kernel/messaging/messaging.c
This commit fixes build break as shown below:
LD: tinyara
os/../build/output/libraries/libkernel.a(messaging.o): In function `messaging_append_receiver':
os/kernel/messaging/messaging.c:115: undefined reference to `kmm_malloc'
os/../build/output/libraries/libkernel.a(messaging.o): In function `messaging_save_receiver':
os/kernel/messaging/messaging.c:202: undefined reference to `kmm_malloc'
os/../build/output/libraries/libkernel.a(messaging.o): In function `messaging_remove_list':
os/kernel/messaging/messaging.c:314: undefined reference to `kmm_free'
os/kernel/messaging/messaging.c:321: undefined reference to `kmm_free'
Makefile:195: recipe for target '../build/output/bin/tinyara' failed
=> kernel/messaging: include <tinyara/kmalloc.h> to use kmm_xxx APIs

os/mm/mm_heap/mm_addfreechunk.c
Reverts Samsung/TizenRT#2869
Need to have more tests about memory fragmentation.
=> Revert "mm_heap/mm_addfreechunk : sorting the free nodelist"

external/esp_idf_port/soc/Makefile
there is no CONFIG_XXX used in the external/esp_idf_port/soc/Makefile,
Remove useless included ".config" file.
@sunghan-chang
=> external/esp_idf_port: Remove useless config file in Makefile.

build/configs/imxrt1020-evk/nxp_demo/Make.defs, build/configs/imxrt1050-evk/nxp_demo/Make.defs, build/configs/imxrt1050-evk/tc/Make.defs
Folder path and board name is configured by .config.
Let's get them from .config.
=> configs/imxrt1050-evk, imxrt1020-evk: get board name and path configured

os/board/imxrt1020-evk/src/Makefile
This fixes build warning as shown below:
make[2]: Entering directory '/home/sunghan/Work/TinyAra/Forked_TizenRT/os/board/imxrt1020-evk/src'
Makefile:126: recipe for target '.depend' failed
make[2]: *** [.depend] Error 1
make[2]: Leaving directory '/home/sunghan/Work/TinyAra/Forked_TizenRT/os/board/imxrt1020-evk/src'
Makefile:223: recipe for target '.depend' failed
make[1]: *** [.depend] Error 2
=> board/imxrt1020-evk: add DEPPATH in flash partition conditional

os/arch/Kconfig, os/arch/arm/src/armv7-m/up_doirq.c
This patch adds the support of stack overflow check for nested interrupt.
If stack grows more than the configured interrupt stack size then
this check will assert the system.
=> arch/arm/src/armv7-m : Add stack overflow check for nested interrupts

os/arch/arm/src/imxrt/imxrt_usbhost.c
Calling task_create() fails in binary protection mode.
so change it to kernel_thread
=> driver/usb: Change the creation of task

os/fs/procfs/fs_procfs.c, os/fs/procfs/fs_procfsereport.c
Procfs for `error_report` module throws errors with Filesystem testcase when trying to read from `/proc/ereport`. This was caused by a lack of proper foldername name matching, and is addressed in this commit. Additionally, procfs for `error_report` now includes a `stat` function to allow directory listing.
=> [fs/procfs]: Fix procfs for error report

external/esp_idf_port/esp32/Makefile
".config" is made via issuing configure.sh, if not exist, run "make clean"
will report error "No such file", change including mode with prefix "-"
will fix this issue.
@sunghan-chang
=> external/esp_idf_port: change including ".config" mode in Makefile.

os/FlatLibs.mk, os/ProtectedLibs.mk
Somecases, application requires external library and
main purpose of external library is supporting some features to apps.
Let's build external before apps builds start.
=> build: start external build before apps

os/ProtectedLibs.mk
Same purpose of commit a027c6c.
Somecases, apps use iotivity feature. Then, iotivity should
be built first.
=> build: start iotivity build before apps

framework/include/iotbus/iotbus_uart.h, framework/src/iotbus/iotapi_dev_handler.c, framework/src/iotbus/iotapi_dev_handler.h, framework/src/iotbus/iotbus_adc.c, framework/src/iotbus/iotbus_uart.c, os/arch/arm/src/imxrt/imxrt_adc.c
- add trigger logic for starting adc conversion.
- add param in callback function for identifying the uart device.
=> framework/iotbus: implement ADC/UART APIs in iotbus

apps/system/init/init.c, apps/system/utils/Makefile
FS commands can be used in protected build now.
=> apps/system: Support fs commands in protected build

apps/system/utils/fscmd.c, apps/system/utils/utils_heapinfo.c, apps/system/utils/utils_proc.c, apps/system/utils/utils_ps.c, apps/system/utils/utils_stackmonitor.c
- system/utils: Check the length of input data in tash_echo
- system/utils: Initialize local variable 'ret' in function
- system/utils: Free allocated memory after usage in log message on failure
=> system/utils: Fix wrong logics

build/configs/imxrt1020-evk/scripts/flash-ocram.ld, build/configs/imxrt1050-evk/scripts/flash-ocram.ld
Modify linker scripts to fix flexspi flash configuration issue
In case of XIP, flexispi and hyperflash objects run on top of flash,
if we copy these in flash itself then unexpected behavior results.
So these are copied to data section to execute the flash init and config
from outside.
=> build/configs: Fix reset issue at imxrt flash init

framework/include/messaging/messaging.h, framework/src/messaging/messaging_cleanup.c, os/kernel/messaging/messaging.c
Previous cleanup logic removes all data which related with port_name.
But in that case with multicast, before receiving, some internal data can be removed because of another receivers.
So cleanup should be remove only its data.
=> framework/messaging : cleanup internal data only if that data is from itself

os/arch/arm/src/armv7-m/mpu.h, os/arch/arm/src/armv7-m/up_svcall.c, os/arch/arm/src/imxrt/imxrt_mpuinit.c, os/arch/arm/src/imxrt/mpu-reg.h
Enabling the MPU and adding MPU regions is causing a degradation
of system performance. Each additional MPU region setting results
in a reduction of performance. Hence, we need to make sure that
we are using the minimum required MPU regions.
This commit contains following changes:
- Remove Kernel MPU regions, since Kernel has access to complete address space
- Enable USER_CODE and USER_DATA region only if user app is enabled
- Fix issues that happen during task start and context switch
=> os/arch/arm/src: Fix performance issue caused by MPU settings

os/arch/arm/src/imxrt/Kconfig, os/arch/arm/src/imxrt/Make.defs, os/board/imxrt1020-evk/src/imxrt_bringup.c, os/board/imxrt1020-evk/src/imxrt_userleds.c, os/board/imxrt1020-evk/userspace/imxrt_userspace.c, os/board/imxrt1050-evk/src/imxrt_boot.c
When one of timer is enabled and timer driver is enabled,
timer initialization is necessary to use timer driver.
This commit adds CONFIG_IMXRT_TIMER_INTERFACE for that and
fix build break as shown below.
LD: tinyara
build/output/libraries/libkarch.a(imxrt_timer_lowerhalf.o): In function `imxrt_gpt_setcallback':
os/arch/arm/src/chip/imxrt_timer_lowerhalf.c:334: undefined reference to `imxrt_gpt_setisr'
os/arch/arm/src/chip/imxrt_timer_lowerhalf.c:338: undefined reference to `imxrt_gpt_setisr'
build/output/libraries/libkarch.a(imxrt_timer_lowerhalf.o): In function `imxrt_gpt_stop':
os/arch/arm/src/chip/imxrt_timer_lowerhalf.c:216: undefined reference to `imxrt_gpt_setisr'
build/output/libraries/libkarch.a(imxrt_timer_lowerhalf.o): In function `imxrt_gpt_start': …
=> imxrt: add CONFIG_IMXRT_TIMER_INTERFACE support

apps/examples/timer/timer_main.c
Timer thread stack size increase from 512->1024 to avoid stack corruption with protection builds.
=> apps/examples/timer: Increase timer thread stack size.

os/mm/umm_heap/umm_free.c
umm_free can fail under the below scenario:
- Two tasks are running
- Task 1 exits. Task 2 is now active
- The task 1 clean up code calls kumm_free to free its stack
- umm_free() tries to get heap using mm_get_heapindex() API
- Since, task 2 is now active, this API returns -1
The issue is fixed by replacing mm_get_heapindex() with mm_get_heap()
which has the logic to search all the app heaps to find a match for
the given address.
=> os/mm/umm_heap: Fix memory leak in umm_free

os/tools/compression/.gitignore, os/tools/compression/Makefile
Compression tool generates temp files and executable for
binary compression which need not to be added to git.
=> os/tools/compression: Add gitignore for compression folder

framework/src/st_things/things_stack/things_stack.c
'abs_json_path' buffer is allocated with length 'len_of_path', write to index 'len_of_path' is out-of-bound
=> framework/st_things: fix an array write out-of-bound issue

os/board/Kconfig
i.MXRT1020-evk board is same as i.MXRT1050-evk requires auto generated
memory linker script. Let's add same selection at i.MXRT1020-evk config.
=> board : Add AUTOGEN_MEMORY_LDSCRIPT selection on imxrt1020-evk config

apps/system/utils/netcmd_ping.c
1. Release the heap when ping_recv function returns.
2. Fix coding rule issue.
=> apps/system/utils: Fix memory leak issue in ping command.

framework/src/iotbus/iotbus_adc.c
- Remove label 'iobus_adc_read_done'
- Remove empty space
=> framework/iotbus: Remove unused label and empty space

apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
- CONFIG_BUILD_PROTECTED is added to some of file system testcases to prevent
errors from protected build cases.
=> apps/examples: Add ifdefs to exclude some fscmd functions in protected build

apps/system/utils/Makefile
SYSTEM_CMDS, FS_CMDS and NET_CMDS are separated commands sets.
They should be in SYSTEM_CMDS conditional.
=> apps/system/utils: fix wrong conditional for netcmd and fscmd

apps/examples/memory_fragmentation_test/Kconfig, apps/examples/memory_fragmentation_test/Kconfig_ENTRY, apps/examples/memory_fragmentation_test/Make.defs, apps/examples/memory_fragmentation_test/Makefile, apps/examples/memory_fragmentation_test/README.txt, apps/examples/memory_fragmentation_test/memory_fragmentation_test.c
This app allocates and releases small and large memory segments in a mixed-up manner repeatedly
in order to intentionally fragment the heap memory.
'heapinfo' shows how the heap is fragmented.
Note that fragmentation tends to become severe when the lifetime of small memory
is relatively longer than that of large memory.
=> apps/examples : add a memory fragmentation test

os/arch/xtensa/src/esp32/esp32_gpio.c, os/arch/xtensa/src/esp32/esp32_gpio_lowerhalf.c
1. Enable the gpio enble interface in esp32 gpio driver.
2. Modify the interrupt handler.
3. Clear the pending gpio interruption flag，when disable this gpio.
=> Update esp32 gpio driver.

apps/examples/heap_performance_test/Kconfig, apps/examples/heap_performance_test/Kconfig_ENTRY, apps/examples/heap_performance_test/Make.defs, apps/examples/heap_performance_test/Makefile, apps/examples/heap_performance_test/README.txt, apps/examples/heap_performance_test/heap_performance_test.c, os/include/tinyara/mm/mm.h, os/mm/mm_heap/mm_addfreechunk.c, os/mm/mm_heap/mm_initialize.c, os/mm/mm_heap/mm_malloc.c, os/mm/mm_heap/mm_size2ndx.c
Current algorithm:
Free nodes are managed by n double-linked lists called 'mm_nodelist'.
The head of each list is not a real free node but discrimiates where each list starts.
i-th list includes free nodes whose size ranges [2^(i+4) 2^(i+5)[.
When memory allocation is requested, the current procedure is as follows:
1.compute 'ndx' with size
2.search an available node from 'mm_nodelist[ndx]
3.remove the node from the list.
Here are two problems. At the second step, we may not find an available node from ndx-th list.
Let's see an example.
The table depicted below shows the initial status of the heap memory.
When 32 bytes allocation is requested, from the step 1 the index is 1.
However, mm_nodelist[1] doesn't have any free nodes.
To handle this situation, each head is doubly-linked with …
=> mm/mm_heap : algorithm enhancement to reduce temporal cost of malloc()

build/configs/imxrt1020-evk/loadable_elf_apps/defconfig, os/kernel/Kconfig
- kernel/binary_manager: Add dependency of BCH driver
- configs/imxrt1020-evk: Enable BCH driver by default
=> binary_manager: Add dependency of BCH and enable it in imxrt1020-evk/loadable_elf_apps

os/board/imxrt1020-evk/src/imxrt_boot.c
To use timer driver on apps, timer initialization should be done.
=> board/imxrt1020-evk/boot: add timer initialization

apps/examples/testcase/le_tc/filesystem/fs_main.c
tc_fs_driver_ramdist_ops calls ramdisk_register which can't be called in user side when protected build.
=> testcase/filesystem: Disable ramdisk testcase in protected build

external/dhcpc/dhcpc_lwip.c, external/dhcpd/dhcpd_lwip.c, os/net/netdev/netdev_dhcpc.c, os/net/netdev/netdev_dhcpd.c, os/net/netdev/netdev_ioctl.c
- Replace 0 to OK and -1 to ERROR
- Return valid error type for lwip_func_ioctl
- Replace printf to ndbg
=> net/dhcp: Fix bad logic and return values

os/arch/arm/src/imxrt/imxrt_usbhost.c, os/drivers/usbhost/rtl8723d.c, os/drivers/wireless/realtek/os/tizenrt/tizenrt_service.c, os/drivers/wireless/realtek/platform/usb/usb_io_realtek.c, os/drivers/wireless/realtek/platform/usb/usb_io_realtek.h, os/drivers/wireless/realtek/wifi_util_interface/rtk_drv_lwnl80211.c
os/drivers: Support binary separation for usbhost driver
- Replace pthread_create to kernel_thread
- Replace printf to udbg
os/drivers/wireless: Support binary separation
- Replace task_create or pthread_create to kernel_thread
- Replace free to kmm_free
=>  os/drivers/wireless: Support binary separation

os/arch/arm/src/imxrt/imxrt_gpt.c, os/arch/arm/src/imxrt/imxrt_gpt.h, os/arch/arm/src/imxrt/imxrt_timer_lowerhalf.c, os/include/tinyara/timer.h
When using Board IMXRT10x, it supports clock freq and ticks
in timer status.
=> arch/arm/imxrt : Support ticks and clock freq in timer status

apps/AppLibs.mk
This patch adds --gc-sections flag in application makefile.
this tells linker to remove unused sections from the code,
which results in reducing code size.
=> apps : Add --gc-sections flag in application Makefile

tools/ramdump/gui_dumpParser.py
Since gui_dumpParser.py use relative dir, change directory when the
script starts.
=> tools: chdir to use gui_dumpParser in another dir

os/net/netdev/netdev_ioctl.c
- When addrinfo structure has no canon name, skip copying it for safety
=> os/net/netdev_ioctl: Fix a bug in copy address info

os/arch/arm/src/imxrt/imxrt_gpt.h, os/arch/arm/src/imxrt/imxrt_timer_lowerhalf.c, os/include/tinyara/timer.h
By default, a timer is running with Restart mode that timeleft is set as interval when timeout.
User can set or unset FreeRun mode with ioctl like ioctl(fd, TCIOC_SETFREERUN, true or false).
=> imxrt/timer: Support to set FreeRun mode for gpt with ioctl

external/esp_idf_port/Makefile
Add depend PHONY in makefile to fix the make error as below
make[2]: Leaving directory '/root/tizenrt/external/esp_idf_port'
make[2]: *** No rule to make target 'depend'.  Stop.
=> external/esp_idf_port: Add depend PHONY in makefile.

framework/src/st_things/Kconfig
The ST_THINGS_ARTIK_HW_CERT_KEY has been changed to
ST_THINGS_HW_CERT_KEY why It looks like to have a dependency
for board implicitly.
=> framework/st_things: modify Kconfig.

os/arch/arm/src/imxrt/imxrt_timer_lowerhalf.c, os/include/tinyara/timer.h
User can set a priority of timer irq using ioctl with TCIOC_SETIRQPRIO.
=> imxrt/timer: Support to set irq proirity with ioctl

os/arch/arm/src/imxrt/imxrt_adc.c
They are dedeicated UART TXD and RXD on i.MXRT1050-evk board.
=> arch/imxrt/adc: block ADC1_IN2 and ADC1_IN1 setting for imxrt1050-evk

framework/src/messaging/Kconfig, os/binfmt/binfmt.h, os/binfmt/binfmt_dumpmodule.c, os/binfmt/elf.c, os/syscall/syscall.csv
binfmt, syscall: remove duplicated conditionals
framework/messaging: set disabled by default
=> tidyup on binfmt and set messaging framework disabled by default

os/mm/mm_heap/mm_heapinfo.c
Heap management has been changed where each free nodelist ranges ]2^i, 2^(i+1)] instead of [2^i, 2^(i+1)[.
For example, the second list ranges [33, 64] instead of [32, 63].
=> mm_heap/heapinfo : modify the range of each free nodelist

os/kernel/binary_manager/binary_manager_recovery.c
It is hard to read because there is no '\n' and loo long.
so changed simple and added '\n'.
=> kernel/binary_manager : Improve the readability of logs

apps/examples/elf/micomapp/Makefile, apps/examples/elf/wifiapp/Makefile, os/Makefile.unix, os/binfmt/libelf/gnu-elf.ld
The up_userspace.c is used by the app binaries as well as user binary.
But since the file is already build by the app build process, it is not
re-built during the user binary build. This is causing issues since the
user binary is missing some of the variables in the userspace object.
In order to fix this issue, we will delete the up_userspace.o object file
before the user binary build.
=> Fix boot-up issue due to userspace object

build/tools/esp32/esptool_py/romfs_flash_address.sh
In ubuntu environment, "dash" is default shell, it does not support
built-in "let" command and comparsion operator "==", so modify it
to work in both "bash" and "dash".
@sunghan-chang, this PR is reviewed by internal team and other team, could you help merge it?
=> build/tools/esp32: Modify command and operator that "dash" not support.

apps/examples/testcase/le_tc/kernel/tc_clock.c, os/drivers/testcase/kernel_testcase_drv.c, os/include/tinyara/testcase_drv.h
Tset clock_abstime2ticks through the virtual driver.
=> testcase/kernel : Fix the abstime2tikcs test scenario

apps/shell/tash_command.c, apps/shell/tash_internal.h, apps/shell/tash_main.c, apps/system/utils/utils_stackmonitor.c, framework/src/task_manager/task_manager_core.c
TASH prompt is used in tash_main.c and it is never changed.
Let's use a definition, TASH_PROMPT instead of const char *tash_prompt.
The tash_running is used to stop and it is rarelly used.
Let's make it as static and provide a function, tash_stop() to stop.
=> framework/task_manager, apps/shell: use a static variable and a definition instead of globals

os/fs/smartfs/smartfs_smart.c
If both journaling(CONFIG_SMARTFS_JOURNALING) and smart crc(CONFIG_MTD_SMART_ENABLE_CRC),
compilation error occurs in smartfs_sync_internal.
smartfs/smartfs_smart.c: In function 'smartfs_sync_internal':
smartfs/smartfs_smart.c:602:21: error: unused variable 't_offset' [-Werror=unused-variable]
uint16_t t_sector, t_offset;
This patch eliminates the build error.
=> fs/smartfs: Change config dependency on variables

apps/examples/timer/timer_main.c
This patch is to mitigate nested signal issues with
high-resolution timer interrupts. Nested signal situation
occurs if the time-period is smaller and next timer interrupt
occurs before the current interrupt signal is delivered.
This causes stack corruption due to multiple pending signals
This patch implements a dedicated thread that waits on sigwait()
It provides a deterministic wake-up time when the signal occurs
With this, we can achieve upto 30us timer events without suppressing
timer interrupts.
For more resolution requirement, we need to increase the stack for the thread waiting for signal
=> apps/examples/timer: dedicated timer thread with sigwait()

build/tools/esp32/esptool_py/Makefile
Enhance 1)
build/tools/esp32: erasing entire flash before downloading all images.
Add step of erasing entire flash before downloading all images
to flash, it helps fix unexpected read/write issue for file systems
based on flash. 
Enhance 2)
build/tools/esp32: Remove dependent for make target "romfs"
if dependent "ROMFS_IMG" image not exist, "No rule to make target"
error will report, and this image will be checked by another script,
so this dependent can be removed.
@sunghan-chang
=> build/tools/esp32: erasing entire flash before downloading all images.

framework/src/iotbus/Make.defs
iotapi_dev_handler.c file should be include to build at Make.defs.
This commit fixes build breaks as shown below:
CC:  up_userspace.c
build/output/libraries//libframework.a(iotbus_uart.o): In function `iotbus_uart_set_int':
framework/src/iotbus/iotbus_uart.c:583: undefined reference to `iotapi_dev_get_int_type'
framework/src/iotbus/iotbus_uart.c:584: undefined reference to `iotapi_dev_unregister'
framework/src/iotbus/iotbus_uart.c:571: undefined reference to `iotapi_dev_init'
framework/src/iotbus/iotbus_uart.c:572: undefined reference to `iotapi_dev_register'
framework/src/iotbus/iotbus_uart.c:571: undefined reference to `iotapi_dev_init'
framework/src/iotbus/iotbus_uart.c:572: undefined reference to `iotapi_dev_register'
Makefile:112: recipe for target 'tinyara_user.elf' failed …
=> fixup! framework/iotbus: add system I/O interrupt handling process

os/Kconfig.debug, os/arch/arm/src/stm32/Kconfig, os/arch/arm/src/stm32/stm32_otgfshost.c, os/drivers/serial/Kconfig
The patch will fix the listed issues
1) Cant enable usbhost CDCACM mode from menuconfig
2) Cant enable any of the USB logs from menuconfig
3) with "stm32-f4-discovery" board, /dev/ttyACM0 node not populating creating in usb host mode.
3.1) Verified the Tx case from stm32 board to connected device, thru LeCroy usb pkt analyser.
3.2) Cant verify the Rx case, as no suitable test device not found.
=> stm32-f4-discovery: Fix acm not working in usbhost mode

os/drivers/Makefile, os/drivers/wireless/realtek/Make.defs, os/drivers/wireless/realtek/platform/ethernetif_tizenrt.c, os/drivers/wireless/realtek/platform/ethernetif_tizenrt.h, os/drivers/wireless/realtek/platform/lwip_intf_tizenrt.c, os/drivers/wireless/realtek/platform/usb/usb_io_realtek.h, os/drivers/wireless/realtek/wifi_util_interface/rtk_lwip_netconf.c, os/drivers/wireless/realtek/wifi_util_interface/rtk_lwip_netconf.h, os/drivers/wireless/realtek/wifi_util_interface/wifi_interactive_mode.c
including (TOPDIR)/include causes unexpected errors which is hard to
find. therefore remove the script line and fix the referenced path.
=> network/realtek: fix build path

apps/system/utils/Kconfig, apps/system/utils/utils_proc.h, apps/system/utils/utils_stackmonitor.c, os/include/sys/prctl.h, os/include/tinyara/sched.h, os/kernel/sched/Make.defs, os/kernel/sched/sched_releasetcb.c, os/kernel/sched/sched_save_terminated_stackinfo.c, os/kernel/task/task_prctl.c
Previously, kernel used app/system resource(stkmon_arr) for logging terminated task information.
Now kernel has resource for logging, and stackmonitor in app/system copies the data when they need.
=> system/utils/stackmonitor : Move terminated task logging func to kernel

os/arch/arm/src/imxrt/imxrt_qtmr.c, os/arch/arm/src/imxrt/imxrt_qtmr.h, os/board/imxrt1050-evk/src/imxrt_boot.c
This patch implements quad timer in TizenRT with each timer having
four different channels. But each timer with only one channel will get registered due to non-availability of irq lines.
Co-authored-by: Amandeep Chauhan <a.chauhan@samsung.com>
=> arch/arm/src/imxrt: Implement QuadTimer

os/kernel/init/os_start.c
In tinyara/mm/mm.h, there is a user heap definition as BASE_HEAP.
But USR_HEAP is in mm/umm_heap, so kernel cannot use the USR_HEAP.
=> Change USR_HEAP to BASE_HEAP for initializing user heap

framework/include/media/media_init.h
Add void argument to fix `warning: function declaration isn't a prototype [-Wstrict-prototypes]`
=> framework/media: Fix buildwarning

os/arch/arm/src/imxrt/imxrt_qtmr.c, os/arch/arm/src/imxrt/imxrt_qtmr.h, os/board/imxrt1020-evk/src/imxrt_boot.c
This patch adds support of quad timer on imxrt1020-evk
chipset
=> board/imxrt1020-evk: Add Quad Timer support for imxrt1020

os/include/sys/prctl.h, os/kernel/task/task_prctl.c
Previous prctl only supports PR_SET_NAME, and PR_GET_NAME. For supporting more types, changed to enum value.
=> include/sys/prctl.h : Change prctl type to enum value

framework/src/iotbus/iotbus_pwm.c, os/arch/arm/src/imxrt/Kconfig, os/arch/arm/src/imxrt/imxrt_pwm.c, os/board/imxrt1020-evk/src/imxrt_bringup.c
iMXRT flexpwm controller has several pwm channels, they are
organized like:
flexpwm controller 0 ---> submodule 0 ---> channel [A, B, X]
|--> submodule 1 ---> channel [A, B, X]
|--> submodule 2 ---> channel [A, B, X]
|--> submodule 3 ---> channel [A, B, X]
Each submodule has one source clock, so the three channels: A, B, X
will work at the same output frequency, but each of the duty can be
set separately. Channel A and B can also work on complementary for
motor control, and channel X has some specific charecters.
In general, channel A and B can be configured as normal pwm output
working in individual mode. This pwm driver supports to enable and
use the channels under the individual mode, and numbers all channels
in uniform.
For RT1020, there are 2 flexpwm controllers, each controller has …
=> arch/imxrt/flexpwm: Update the flexpwm driver based on channel

os/arch/arm/src/common/up_usestack.c
We cannot check the used stack size for pre-allocated stack, because pre-allocated stack is not filled with color.
up_use_stack() sets up the stack-related information in the TCB, so add up_stack_color() at the end of the up_use_stack().
=> arch/arm/common : Add up_stack_color() in up_usestack()

loadable_apps/Makefile
Following build error happens during protected build.
nm: '/home/kishore/tinyara/TizenRT_kishore/loadable_apps/micomapp/micom': No such file
CC: /home/kishore/tinyara/TizenRT_kishore/os/board/common/userspace/up_userspace.c
/home/kishore/tinyara/TizenRT_kishore/os/board/common/userspace/up_userspace.c:57:28: fatal error: tinyara/config.h: No such file or directory
#include <tinyara/config.h>
^
compilation terminated.
In order to fix this error, we disable building of loadable apps in
protected build configuration.
=> loadable_apps: Fix build error during protected build

os/tools/mkbinheader.py
…ack size
Malloc the binary into the dynamic ram area. So Dynamic ram size should
be bigger than Binary stack size.
=> os/tools/mkbinheader.py : Compare Binary stack size and Dynamic ram size 

os/fs/procfs/fs_procfsproc.c, os/kernel/init/os_start.c
Idle task's tcb doesn't have stack information(stack size and stack alloc pointer), because it is not allocated by mm.
For debugging, we need idle task's stack information.(Ex: stack monitor, heapinfo, assert log.)
=>  kernel/init : Fill idle stack information in g_idletcb when os boot up.

framework/src/wifi_manager/slsi_wifi_utils.c
Presently, wifi utils does not allow connection to WiFi access point in unsecured mode. This pull request makes the necessary fixes to allow the feature.
=> [framework/wifi_manager]: Fix wifi utils to allow connection to open AP

apps/examples/binary_update/binary_update_main.c
…ccess
It made a sample test by adding the situation where the download
failed and the situation that succeeded.
** Binary Update example : executes 1-times.
** Binary Update Example 1-th Iteration.
** Binary Update GETINFO [micom] test.
========= binary [micom] info ==========
Version | Partsize | Inactive part
---------------------------------------
20190423 |   262144 | /dev/mtdblock2
========================================
** Binary Update Download [/dev/mtdblock2] Fail case test.
Failed to download
** Binary Update RELOAD [micom] test.
RELOAD [micom] SUCCESS
** Binary Update GETINFO [micom] test.
========= binary [micom] info ==========
Version | Partsize | Inactive part
---------------------------------------
20190423 |   262144 | /dev/mtdblock2 …
=> examples/binary_update : Add sample scenario for download valid and invalid binary

os/arch/arm/src/armv7-m/up_assert.c, os/arch/arm/src/armv7-r/arm_assert.c, os/kernel/init/os_start.c
Idle task's tcb has stack information now, so we can display the current used stack size when asserted.
=> arch/arm/assert : Display used stack size of idle task when asserted.

os/kernel/init/os_start.c
'g_idle_topstack - 4' should be set to idle task's adj_stack_ptr, not adj_stack_size.
=> kernel/init/os_start : Fix wrong assignment for idle stack information

loadable_apps/Kconfig, loadable_apps/micomapp/Makefile, loadable_apps/micomapp/micomapp.c, loadable_apps/micomapp/micomapp_internal.h, loadable_apps/micomapp/timer.c, loadable_apps/wifiapp/wifiapp.c
We can test timer in micom app.
CONFIG_EXAMPLES_MICOM_TIMER_REPEAT and CONFIG_EXAMPLES_MICOM_TIMER_INTERVAL should be set for testing.
=> loadable_apps : Add timer test in micom app

apps/system/iperf/iperf_api.c, apps/system/iperf/iperf_client_api.c, apps/system/iperf/iperf_net.c, apps/system/iperf/iperf_tcp.c
- Use set/get_errno() APIs instead of direct access
=> apps/iperf: fix direct access to errno

os/kernel/Kconfig
Under APP_BINARY_SEPARATION and BINARY_MANAGER conditionals,
user main task is not launching from os_bringup. so that
USERMAIN_STACKSIZE is not necessary.
This commit makes it disapeared under conditionals above.
=> kernel: add a BINARY_MANAGER dependency in USERMAIN_STACKSIZE

os/include/tinyara/binary_manager.h, os/kernel/binary_manager/binary_manager.c, os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_getinfo.c
User can set the different size for each partition.
=> kernel/binary_manager: Set the size for each partition in binary table

framework/src/st_things/things_stack/framework/things_data_manager.c
memory size shall be char size multiple sizeof string literal
=> framework/st_things: fix an arithmetic operator misuse

lib/libc/time/lib_calendar2utc.c, lib/libc/time/lib_mktime.c
1. fix wrong calculation of month in mktime()
The month index starts from 0, not from 1 so that
mktime has not to add 1 for clock_calendar2utc().
2. remove unncessary codes for mktime()
There are two mktime() functions with CONFIG_GREGORIAN_TIME.
But they are same so that let's remove one.
3. fix wrong calculation of leap year in clock_calendar2utc
To calculate the days of leap years, it has to subtract 1969
from year value. But it misses ( ) so that it does 1971.
=> libc/time: fix wrong calculation and remove unnecessary codes

apps/system/init/init.c, framework/include/task_manager/task_manager.h, os/include/tinyara/init.h, os/kernel/init/os_bringup.c
The creation of task manager is not the kernel role, so moved to preapp.
=> framework/task_manager : Move task manager creation to preapp

os/arch/arm/src/imxrt/imxrt_ehci.c
- When worker handler is not available,
we should free usb_asynch_work structure in imxrt_ehci.c
=> arch/imxrt_ehci: Fix mem leak for exceptional logic

apps/shell/tash_internal.h
- Build errors that occur due to shvdbg when TASH debug config is enabled
are fixed.
=> app/shell: Fix definitions of TASH debug

framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaPlayerImpl.h
Don't call stop at the playback finish time to prevent
playback_stopped and playback_finished callback from being called
together.
=> framework/media: Fix logic when playback is finish

external/include/libcxx/cstddef
This commit is taken from nuttx
=> include/cxx/cstddef: Add C11++ std::nullptr_t

os/binfmt/binfmt_exit.c, os/binfmt/binfmt_loadbinary.c, os/include/tinyara/binfmt/binfmt.h, os/include/tinyara/sched.h, os/kernel/group/group_leave.c
When binary manager terminates task/pthreads for update or recovery, it doesn't need to free resources in user memory.
That's because user RAM partition is freed when main task is unloaded in binary separation.
=> kernel/sched: Remove resources in RAM partition to be unloaded from a list of delayed free before unloading

os/arch/arm/src/imxrt/Make.defs, os/arch/arm/src/imxrt/imxrt_wdog.h, os/arch/arm/src/imxrt/imxrt_wdog_lowerhalf.c, os/board/imxrt1020-evk/src/imxrt_boot.c, os/drivers/watchdog.c, os/include/tinyara/watchdog.h
For using watchdog in user context, mapping the imxrt watchdog functions to watchdog drivers.
=> imxrt/watchdog : Support watchdog interface

os/arch/arm/src/armv7-m/up_mpu.c
Shareability is not required for applications, it is used only when multiprocessor or DMA operation is required.
=> arch/arm/src/armv7-m: Disabling MPU shareablity for user memory.

build/tools/esp32/esptool_py/Makefile
Remove erase entire flash command before downloading all images,
as it will take side effect for applications involves SPIRAM.
=> build/tools: Remove erase entire flash command.

os/tools/mksyscall.c
This patch fixes the below warnings in the protected build
/TizenRT/os/include/unistd.h: In function '_exit':
proxies/PROXY__exit.c:10:1: warning: 'noreturn' function does return
}
^
/TizenRT/os/include/stdlib.h: In function 'exit':
proxies/PROXY_exit.c:10:1: warning: 'noreturn' function does return
}
^
/TizenRT/os/include/pthread.h: In function 'pthread_exit':
proxies/PROXY_pthread_exit.c:12:1: warning: 'noreturn' function does return
}
Verification:
1. ./tools/configure.sh imxrt1050-evk/loadable_elf_apps
2. make
Confirming to:
gcc version 6.3.1 20170215 (release) [ARM/embedded-6-branch revision 245512]
=> proxies : fix warning - 'noreturn' function does return

os/drivers/analog/adc.c, os/drivers/pipes/pipe_common.c, os/drivers/serial/serial.c, os/fs/vfs/fs_poll.c, os/include/poll.h
Check if file pointer is registered in a list of waiters for polling.
For example, when task A is blocked by calling poll and task B try to terminate task A, a pollfd of A remains in this list.
If it is, it should be cleared.
=> fs/poll: Clear slot for the poll structure reference when closing file

external/libcxx/system_error.cxx
errno can be rvalue, and it makes build error.
=> external/libcxx: Replace errno with set/get_errno

external/include/libcxx/ctime
asctime, ctime, localtime needs CONFIG_LIBC_LOCALTIME
=> external/libcxx: Add #ifdef statement in ctime

os/arch/arm/src/common/up_initialize.c
Add bluetooth null driver to test the blueooth feature
=> os/arch: Enable bluetooth null driver

os/board/Kconfig
The macro is already been renamed to CONFIG_BOARD_ASSERT_SYSTEM_HALT
in file armv7-m/up_assert.c
So this patch rename the macro BOARD_ASSERT_SYSTEM_BLOCK to
CONFIG_BOARD_ASSERT_SYSTEM_HALT in os/board/Kconfig file.
Signed-off-by: Drashti Parikh <p.drashti@partner.samsung.com>
=> os/board/Kconfig : Rename macro BOARD_ASSERT_SYSTEM_BLOCK

framework/src/media/StreamBuffer.cpp, framework/src/media/StreamBuffer.h
Replace rb_s with the pointer of rb_s.
This change increases the size of StreamBuffer class by 24 bytes,
but removes memory allocation and null pointer check statement.
=> framework/media: Refactor StreamBuffer

apps/system/utils/utils_cpuload.c, os/kernel/sched/sched_cpuload.c
Define and use static variable for time constant values instead of extern variable, g_cpuload_timeconstant because these values are defined in config.h.
=> utils/cpuload: Print time constant values directly without assigning them to array

framework/src/media/Decoder.h, framework/src/media/Make.defs, framework/src/media/codec/audio_decoder.cpp, framework/src/media/codec/audio_decoder.h, framework/src/media/codec/audio_encoder.cpp, framework/src/media/codec/audio_encoder.h, framework/src/media/codec/wav/wav_decoder_api.c, framework/src/media/codec/wav/wav_decoder_api.h
- rename wav_decoder_api.cpp to wav_decoder_api.c
- remove media namespace from head files
- use namespace media in audio_decoder.cpp & audio_encoder.cpp,
because media::audio_type_t is reused in these two files.
=> framework/media: Move codec functions out of media namespace

framework/include/media/BufferObserverInterface.h, framework/src/media/InputHandler.cpp
- BufferObserverInterface needs <sys/types.h> becase of ssize_t
- InputHandler needs <debug.h> because of meddbg
=> framework/media: Add missed header

os/include/net/lwip/arch.h
Debug formatter `X8_F` corrected in this commit.
=> [net/lwip]: Fix debug formatter for lwip

apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
This patch adds config check for smartfs while running the smartfs testcases.
=> testcase/le_tc/filesystem: Add config dependency (CONFIG_FS_SMARTFS)

external/iotivity/iotivity_1.2-rel/resource/csdk/connectivity/src/tcp_adapter/catcpserver.c
If DNS is not working(e.g. AP is unplugged), then Iotivity attempts to
connect to the cloud server with wrong IP address that AP give. Some
AP reply a wrong IP address even though internet is not connected. So
Iotivity stack fails to connect, but it doesn't call close().
So it caused a socket list to run out. therefore it makes socket error code 23
=> iotivity: socket error fix with code 23

os/kernel/sched/sched.h, os/kernel/sched/sched_cpuload.c, os/kernel/sched/sched_releasetcb.c
Define function to clear cpuload count of defunct thread and call it when releasing pid
=> sched/cpuload: Define function to clear cpuload count of defunct thread

apps/system/utils/utils_heapinfo.c, os/fs/procfs/fs_procfsproc.c, os/mm/mm_heap/mm_initialize.c
1. change getting user heap with temp allocated memory
2. show whole task/pthread current and peak heap usage
3. add initialization for total and peak alloc size of user heap
=> apps/system/utils/heapinfo : Support heapinfo for binary separation

framework/src/seclink/seclink.c, framework/src/security/security_auth.c, framework/src/security/security_ss.c, framework/src/security/security_utils.c
if it doesn't allocate memory in security layer it'll cause crash
becuase of dangling pointer. furthermore sl_init function doesn't
deallocate handle when it fails to call ioctl or to get error message
from SE driver. handle should be freed both cases
=> framework/security: fix security bug

os/drivers/Kconfig, os/drivers/Makefile, os/drivers/otp/Make.defs, os/drivers/otp/otp.c, os/drivers/otp/otpnull.c, os/include/tinyara/otp.h
To provide otp service to applications and kernel modules otp driver
need to be defined. Applications can access otp by refering
"tinyara/otp.h" header. but it's not allowed to write otp. however,
kernel modules can write otp to store device specific data.
=> driver/otp: Add otp driver to access one time program area

os/kernel/task/task_exithook.c
Ppid initialization is not needed when task/pthread is terminated.
Because, even if one of the task/pthread in group is terminated, the remaining may be needed the ppid.
=> kernel/task_exithook : Remove ppid initialization when task termination

framework/src/wifi_manager/wifi_manager.c
- Remove comment lines in _wifimgr_save_connected_config internal API
=> framework/wifi_manager: Re-enable saving connected AP config

apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
Change function name because it violates tc naming rule
=> testcase/arastorage/utc : Add _p to utc_arastorage_db_index_exec

apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c, apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c, apps/examples/testcase/ta_tc/systemio/utc/utc_uart.c
- remove unused utc funtion.
- modify typing errors of function name.
=> framework/iotbus: adjust TC coding rule.

os/kernel/binary_manager/binary_manager_recovery.c
…uling
We need to recover mq and sem before state changes.
=> kernel/binary_manager : Recover mq and sem before state changes

apps/system/utils/utils_heapinfo.c, os/arch/arm/src/common/up_createstack.c, os/binfmt/binfmt_exec.c, os/binfmt/binfmt_loadbinary.c, os/drivers/heapinfo/heapinfo_drv.c, os/include/tinyara/binary_manager.h, os/include/tinyara/heapinfo_drv.h, os/include/tinyara/mm/mm.h, os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_load.c, os/mm/mm_heap/mm_getheap.c, os/mm/mm_heap/mm_partition_mgr.c
- arch/arm/up_createstack : Add missing header include
- kernel/binary_manager : Add app name in each app heap structure
- apps/system/utils : Support heapinfo for binary separation 
Changed heapinfo options are like below.
1. which heap to check
: k - normal heap / kernel_heap when protected build
: u - user heap when protected build
: b - binary(app) heap when binary separation
2. heapinfo mode
: a - allocation details per task/pthread
: f - free details per task/pthread
: p [pid] - allocation/free details of specific(pid) task/pthread
=> Heapinfo modification for binary separation

os/compression/Kconfig, os/compression/compress_read.c, os/include/tinyara/binfmt/compression/compress_read.h, os/tools/compression/Makefile
This PR makes following changes:
- Implements block caching to reduce time for loading block-wise compressed binaries.
- Replace malloc with kmm_malloc for dynamic memory allocation in compress_read.c file.
- Remove CROSS_COMPILE from CC assignment in Makefile for building compression tool. Use host PC's gcc compiler.
=> Reduce loading time for block-wise compressed binaries

apps/system/utils/Kconfig
The kill command supports protected build so that "depends on !BUILD_PROTECTED"
is unnecessary.
=> utils/kill: remove unnecessary BUILD_PROTECTED conditional

apps/system/utils/README.md, apps/system/utils/utils_heapinfo.c
1. apps/system/utils : Modify heapinfo explanation in README.md
Heapinfo was expanded to show kernel, user and specific binary heap information.
Add explanation about target for heapinfo.
2. apps/system/utils/heapinfo : Remove unnecessary description
If CONFIG_BUILD_PROTECTED is not enabled, there is only total heap, not kernel or user.
=> apps/system/utils : Modify heapinfo explanation in README.md

os/binfmt/libelf/libelf_load.c, os/include/tinyara/mm/mm.h, os/mm/mm_heap/mm_heapinfo.c
Because, binary heap contains text and data region size,
but those should not be calculated for heap usage.
=> mm/mm_heap/mm_heapinfo : Exclude static RAM usage in binary heap

os/arch/arm/src/common/up_initialize.c, os/arch/arm/src/imxrt/imxrt_wdog.c, os/drivers/Kconfig, os/include/tinyara/arch.h, os/kernel/sched/sched_processtimer.c
1. imxrt/watchdog : Implement watchdog for irq
If there is no irq within interval, watchdog resets the system.
2. kernel/sched/sched_processtimer : Add watchdog for irq on every system timer
On every system timer events, reset the watchdog for irq.
If not, watchdog resets the system.
=> Implement watchdog for irq

loadable_apps/Makefile, loadable_apps/loadable_sample/Makefile, loadable_apps/loadable_sample/micomapp/Makefile, loadable_apps/loadable_sample/wifiapp/Makefile, os/Makefile.unix
External folder path is not used and loadable_apps' path is necessary.
This commit passes the loadable_apps folder path instead of EXTDIR.
=> loadable_apps: pass loadable_apps' path

os/Makefile.unix, os/Makefile.win
For deleting the previous built *dat file in built-in registry, this command is needed.
But if it is in previous line, *dat files are deleted after generating from contextdir.
=> os/Makefile : Move command for deleting the built-in registry file

os/kernel/pthread/pthread_create.c
If alive task count is same max task count, we can't make pthread.
=> kernel/pthread : Check alive task count when make pthread

framework/src/task_manager/Kconfig
Since task_manager does not use workqueue,
there is no need to select work queue config.
=> framework/task_manager : Remove 'select workqueue config' in Kconfig

os/arch/Kconfig
1. SUPPRESS_INTERRUPTS : Do not enable interrupts
2. SUPPRESS_TIMER_INTS : Do not initialize or enable the system timer
=> os/arch/Kconfig : Add suppress configs for interrupt and timer interrupt

os/binfmt/binfmt_execmodule.c, os/binfmt/libelf/libelf_load.c
Loading thread uses the binary's heap for loading, so it saves the alloc data in binary's heap.
But loading thread is not in its binary, exclude those data for calculating the heap usage per threads.
=> binfmt : Move user binary heap initialization for heap usage

os/net/lwip/src/core/mem.c
- Use globally declared ram_heap instaed of malloc inside mem_init()
=> net/lwip: Generalize lwip mem init logic

os/wqueue/work_process.c
The irqrestore is not needed before sigwait or usleep because
the context switch occurs during sigwait or usleep.
=> os/wqueue : Enable interrupts at the end of work process

lib/libc/semaphore/sem_init.c, os/include/semaphore.h, os/include/tinyara/semaphore.h, os/kernel/binary_manager/binary_manager_recovery.c, os/kernel/semaphore/Make.defs, os/kernel/semaphore/sem_destroy.c, os/kernel/semaphore/sem_holder.c, os/kernel/semaphore/sem_list.c, os/kernel/semaphore/sem_post.c, os/kernel/semaphore/sem_wait.c, os/kernel/semaphore/semaphore.h
- Manage the list of semaphore holder with enabling binary manager recovery
- Release all kernel semaphores taken by all task/pthreads when binary is reloaded by searching a list
=> kernel/binary_manager: Release all kernel semaphores taken by all threads in binary when binary recovery

framework/src/media/HttpInputDataSource.cpp
Abstract Content-Type value between `Content-Type: ` and `\r`.
=> framework/media: Correct http head parsing fault

framework/src/media/InputHandler.cpp
If the channel of InputDataSource is zero, InputHandler::open returns
false.
=> media/Inputhandler: Return false if channel is 0

os/board/imxrt1050-evk/src/imxrt_boot.c, os/include/tinyara/watchdog.h
Add imxrt 1050 watchdog initialization in boot code.
There are two watchdogs in imxrt1050, but now we use only one temporarily.(WDOG1)
=> board/imxrt1050-evk/imxrt_boot.c : Add watchdog initialization

os/arch/xtensa/src/esp32/spi_flash/esp32_flash.c
This patch removes redundant assignment of a variable
'result' to itself.
Note: This patch solve SonarQube issue
Signed-off-by: Nilabh <n.shant@partner.samsung.com>
=> xtensa/src/esp32/spi_flash: Remove redundant assignment.

apps/examples/heavy_signal_message_test/.gitignore, apps/examples/heavy_signal_message_test/Kconfig, apps/examples/heavy_signal_message_test/Kconfig_ENTRY, apps/examples/heavy_signal_message_test/Make.defs, apps/examples/heavy_signal_message_test/Makefile, apps/examples/heavy_signal_message_test/heavy_signal_message_test.h, apps/examples/heavy_signal_message_test/heavy_signal_message_test_main.c, apps/examples/heavy_signal_message_test/heavy_signal_message_test_receiver.c, apps/examples/heavy_signal_message_test/heavy_signal_message_test_sender.c, apps/examples/heavy_signal_message_test/heavy_signal_message_test_stop.c
Mary tasks work usleep, mq_receive, mq_send, sem_timedwait and so on.
It should work without dying while multiple context switches occur.
=> apps/kernel_stability_test : Test kernel stability for many context switch

os/crypto/random_pool.c
When using void pointers in calculations, the behavior is undefined.
Arithmetic operations on 'void *' is a GNU C extension,
which defines the 'sizeof(void)' to be 1.
Note: This patch solve SonarQube issue
=> os/crypto/random_pool.c:Typecast 'void *' to 'size_t *' for correct calculations

apps/examples/testcase/le_tc/network/itc_net_inet.c, apps/examples/testcase/le_tc/network/itc_net_send.c
- The first input of inet_aton should not be NULL, because it will cause a crash. Instead, Change it to '-1' which is never used for network addr.
- Send socket operation is able to send NULL msg to the target socket. Therefore, itc_net_send_n_msg is actually, positive case, expecting return 0, not -1.
- strlen(NULL) is not allowed
=> app/testcase: Modify network tc

lib/libc/time/lib_localtime.c, lib/libc/unistd/lib_getcwd.c, os/kernel/task/task_setup.c, os/tools/mkdeps.c
strcpy, strcmp, strcat are vulnerable functions, so changed to strncpy, strncmp, strncat.
=> os, libc : Change strXXX to strnXXX for safe

lib/libc/time/lib_localtime.c
On converting from strcpy to strncpy, should apply "+1" for null termination.
=> lib/libc/lib_localtime : Fix miscalculation on strncpy

build/configs/artik05x/artik05x_download.sh, build/configs/imxrt1020-evk/imxrt1020-evk_download.sh, os/Makefile.unix, os/include/debug.h, os/include/tinyara/fs/fs.h, os/include/tinyara/fs/ioctl.h, os/include/tinyara/fs/mtd.h, os/include/tinyara/math.h, os/include/tinyara/mqueue.h, os/tools/mksmartfsimg.sh, tools/nxfuse/.gitignore, tools/nxfuse/Makefile, tools/nxfuse/README.txt, tools/nxfuse/include/tinyara/nxfuse_kmalloc.h, tools/nxfuse/man/nxfuse.1, tools/nxfuse/mknxfuse.sh, tools/nxfuse/src/filemtd.c, tools/nxfuse/src/linux_ops.c, tools/nxfuse/src/main.c, tools/nxfuse/src/nxfuse.c, tools/nxfuse/src/nxfuse.h, tools/nxfuse/src/tinyara_services.c
* First commit adds support for downloading Smartfs image onto the flash memory in artik05x.
* Second commit contains the sources for nxfuse tool which is required for generation of Smartfs image.
This patch has been back-ported from nuttx.
=> tools/nxfuse: Add support for generating smartfs image

os/binfmt/libelf/Kconfig, os/binfmt/libelf/Make.defs, os/binfmt/libelf/libelf.h, os/binfmt/libelf/libelf_cache.c, os/binfmt/libelf/libelf_init.c, os/binfmt/libelf/libelf_read.c, os/binfmt/libelf/libelf_uninit.c, os/compression/Kconfig, os/compression/compress_read.c, os/include/tinyara/binfmt/compression/compress_read.h
This patch will reduce the elf_load time performance
Issues:
1) ELF loading time quite high, when we are testing with smartfs
2) Specifically wifi app took ~29sec to load a 182KB file
Fix:
1) ELF_read is trying to access the same location a file/location multiple times, which in turn makes smartFS read overhead. So using the cache memory, we store the copies of data which are frequently used smarfFS file location.
2) Now the time has been reduced to 12ms for the same 182KB wifi file
=> binfmt/libelf: Optimize elf loading by caching frequently accessed area

os/arch/arm/src/armv7-m/up_assert.c, os/board/common/partitions.c, os/include/tinyara/binary_manager.h, os/kernel/binary_manager/binary_manager.c, os/kernel/binary_manager/binary_manager.h
- Remove unused variable for loadparam partition
- Call functions to use static gloable variables
=> kernel/binary_manager: Remove unused variable and call functions to use static global variables

os/include/tinyara/task_monitor.h, os/kernel/task/task_prctl.c, os/kernel/task/task_terminate.c, os/kernel/task_monitor/Kconfig, os/kernel/task_monitor/task_monitor.c, os/kernel/task_monitor/task_monitor_internal.h, os/kernel/task_monitor/task_monitor_utils.c
By setting the interval and the maximum interval,
It can check the task to the interval multiples.
If it config TASK_MONITOR_INTERVAL to 5 and TASK_MONITOR_MAX_INTERVAL to 20,
The available interval are 5, 10, 15 and 20.
=> kernel/task_monitor : Support a variety of intervals to check the task

os/arch/arm/src/common/up_watchdog.h, os/arch/arm/src/imxrt/imxrt_wdog.c, os/arch/arm/src/s5j/s5j_watchdog.c, os/board/artik05x/src/Makefile, os/board/common/crashdump.c, os/board/imxrt1020-evk/src/Makefile, os/board/imxrt1050-evk/src/Makefile
1.    arch/arm/src : Add up_watchdog_disable
up_watchdog_disable calls board specific watchdog disable function.
2.     board/crashdump : Make crashdump.c for common
For using crashdump with another board, make crashdump.c in board/common, and remove artik specific crashdump.c
=> Make crashdump for common

lib/libc/semaphore/sem_init.c, os/fs/vfs/fs_fdopen.c, os/kernel/binary_manager/binary_manager_recovery.c, os/kernel/semaphore/sem_destroy.c
- fs/vfs: Remove duplicated code to initialize stream structure
- kernel/binary_manager: Exclude semaphore for signaling for a list of kernel semaphores
=> kernel/semaphore: Remove unnecessary code for semaphore list

os/net/lwip/src/api/sockets.c
- Modify strcpy to strncpy for thread name copy
=> net/lwip: Replace strcpy to strncpy for safety

lib/libc/time/lib_localtime.c
p is assigned to TZDIR, and TZDIR cannot be NULL.
So there is no needed to check that p is NULL.
=> lib/libc/lib_localtime : Remove unnecessary NULL check

tools/ramdump/dumpParser.py
This patch will add line and file information to callstack as
below
CALL STACK of Aborted task:
*******************************************************************
[<40c9990>] save_cpuctxt_regs+0x54 [Line 585 of arm_assert.c]
[<40c9cb4>] up_assert+0x250 [Line 374 of irq.h]
[<40d5674>] hello_main+0x18 [Line 77 of hello_main.c]
[<40cca6c>] task_start+0x50 [Line 166 of task_start.c]
=> dumparser: Adding line information to callstack

apps/examples/wifi_manager_sample/wm_test.c, framework/src/wifi_manager/slsi_wifi_utils.c, os/drivers/lwnl/slsi_drv.c
- Modify example to make `security mode` parameter to be optional for join command.
- Modify wifi_manager slsi util, in case of unknown security mode, scan AP in surrounding and choose suitable AP (same `ssid` with highest `rssi`).
=> wifi_manager: support unspecified security mode when joining AP

apps/examples/wifi_manager_sample/wm_test.c
- Refactor wm_test
1) Remove redundant definitions and declarations
2) Modify typos and coding rule breakers
3) Remove 'coverage' command, which will be replaced with WiFi Manager UTC
4) Modify parsing commands logic to reduce if/else depth
=> apps/example: Refactor WiFi Manager sample application

framework/src/media/StreamHandler.cpp
mStreamBuffer should be reset in createWorker.
@zhouxinhe found this bug.
=> framework/media: Fix a bug in StreamHandler

os/fs/procfs/fs_procfsproc.c
There is a missing change about getting kernel heap(commit 0be6d2a5e3e16f)
Change to get the kernel heap with kmm_get_heap API instead of direct access
=> fs/procfs/fs_procfsproc : Fix missing change about getting kernel heap

apps/examples/bluetooth/Kconfig, apps/examples/bluetooth/bt_unit_test.c, framework/src/bluetooth/adaptation/bt-adatation-adapter.c
framework/bluetooth: Add set_local_name function,
=> examples/bluetooth: Supplement bt_unit_test code

framework/src/wifi_manager/wifi_manager.c
- Remove WIFIMGR_SOFTAP_DISCONNECTING_STATE used by when the mode transition event occurs from the STA connected-mode to SoftAP mode
- Provide a general disconnecting state feature; 1) normal operation of event disconnect, 2) disconnect due to deinit, and 3) disconnect due to Softap transision,
waiting DISCONNECT CALLBACK from the driver for case 2) and 3).
=> framework/wifi_manager: Modify disconnecting state

external/esp_idf_port/esp32/esp32_wifi_utils.c, external/rtk_wifi/include/rtk_wifi_utils.h, framework/src/wifi_manager/wifi_profile.c, framework/src/wifi_manager/wifi_utils.h, os/drivers/wireless/realtek/wifi_util_interface/rtk_drv_lwnl80211.h, os/drivers/wireless/realtek/wifi_util_interface/wifi_interactive_mode.c, os/include/tinyara/wifi/wifi_common.h
- wifi_common.h is widely used from kernel to user space
- Prevent WiFi kernel driver from reffering to the header defined in the framework
=> os/include/tinyara: Move wifi_common.h from framework to tinyara

os/drivers/lwnl/lwnl80211.c
- Provide easy-to-read internal APIs to clean up ops functions executed inside switch case
=> os/drivers: Clean up ioctl commands of lwnl80211

framework/src/wifi_manager/wifi_manager.c
- Calling _dhcps_add_node((dhcp_node_s *)node) after verification that node is not NULL
=> framework/wifi_manager: dhcp node NULL check

os/net/netdev/netdev_ioctl.c
- Replace sizeof((char *)x) to strlen(x)
=> os/net/netdev: Malloc size bug fix in copy_addrinfo

external/include/error_report/error_report.h
Remove unnecessary #defines in `error_report.h`
=> [external/error_report] Refactor and remove unused definitions

apps/examples/testcase/le_tc/kernel/tc_pthread.c, os/kernel/pthread/Make.defs, os/kernel/pthread/pthread.h, os/kernel/pthread/pthread_join_internal.c, os/kernel/pthread/pthread_tryjoin_np.c
The pthread_join and pthread_tryjoin_np are almost the same except
blocking. It causes many codes duplication.
This commit adds pthread_join_internal function and
pthread_join and pthread_tryjoin_np calls it with blocking option.
It already gets rtcb through this_task() so that it does not
need to call getpid for pid value.
Let's get it directly from rtcb structure.
=> kernel/pthread: make internal pthread_join function to remove duplication

external/esp_idf_port/esp32/event_loop/event_default_handlers.c, external/esp_idf_port/include/esp_intr.h
Remove unused code and unnecessary header file reference.
=> external/esp_idf_port:remove redundant code

apps/examples/testcase/le_tc/kernel/tc_group.c, os/drivers/testcase/kernel_testcase_drv.c, os/include/tinyara/testcase_drv.h
group_removechild, group_freechild, group_findchild and so on
are kernel api. So it is not available in app.
So I made it available through the virtual driver.
=> apps/testcase : Test group api in virtual driver

os/wqueue/work_process.c
I fixed build warning below.
work_process.c:220:4: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
while (work_lock() < 0);
^~~~~
work_process.c:224:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'while'
work = (FAR struct work_s *)wqueue->q.head;
^~~~
=> os/wqueue : Fix build warning in work_process

os/fs/vfs/fs_select.c
- Add _reset_fds() internal API to reset readfds, writefds, and exceptfds,
after poll()
=> fs/vfs/fs_select: Mem initialization after poll()

external/curl/Kconfig, external/curl/curl_setup.h, external/curl/vtls/Make.defs, external/include/mbedtls/config.h
The curl has a dependency for mbedtls or openssl to use https protocols.
But the dependency was ignored.
=> external/curl: fix logical build error.

apps/system/utils/utils_heapinfo.c, apps/system/utils/utils_ps.c
I fixed svace issue below.
WID:1355883 Tainted integer 'state' obtained at utils_ps.c:111
that may have values in [9, +inf] is used as an index, which can
lead to buffer overflow at utils_ps.c:119; make sure this value
is within bounds.
WID:1355930 The handle 'heapinfo_fd' was created at utils_heapinfo.c:286
by calling function 'open' and lost at utils_heapinfo.c:294.
=> apps/system/utils : Add missing conditional and close fd on error

apps/examples/testcase/le_tc/kernel/tc_libc_signal.c
Initialize st_timer_spec_val that caused the error to zero
=> testcase/kernel/tc_libc_signal : Initialize st_timer_spec_val to zero

apps/examples/dnsclient_test/dnsclient_main.c, apps/system/netdb/netdb_main.c, external/mdns/mdnsd.c
- Remove h_errno, LwIP's DNS errno in kernel
- Use ioctl to get IP addr
- Use syscall to execute ntoa
=> apps/dns: Use ioctl to get IP addr instead of kernel API

framework/src/wifi_manager/wifi_utils_lwnl80211.c, os/drivers/lwnl/lwnl80211.c
- Assign NULL for scan_list->next if scan_list is well malloced
- Remove redundant code in lwnl80211_close
=> os/drivers: lwnl80211 bug fix

os/drivers/usbhost/rtl8723d.c, os/drivers/usbhost/usbhost_enumerate.c
- Remove unreachable code
- Modify function address type to uint8_t to int, returend by usbhost_devaddr_create
=> os/drivers: USBhost driver bug fix

os/drivers/usbhost/usbhost_enumerate.c
- Part of struct usbhost_id_s *id should be initialized in usbhost_configdesc.
Currently, the whole id is memset by 0, which occurs misoperation.
=> os/drivers/usbhost: Rearrange memset range

os/board/common/partitions.c
If MTD_SMART and FS_SMARTFS are not configure build error occurs.
So I added the parentheses and the else conditional statement.
=> board/common : Add conditional statement

os/drivers/usbhost/rtl8723d.c
- Check whether kmm_malloc for priv is set or not
=> os/drivers/usbhost: Add missing malloc result check

framework/include/araui/ui_widget.h
The prototype of deleted API was remained, and therefore remove the declaration of this prototype.
=> framework/araui: Remove the prototype of deleted API.

os/kernel/signal/sig_deliver.c, os/kernel/task/task.h, os/kernel/task/task_activate.c, os/kernel/task/task_terminate.c
When up_signal_dispatch is executed, it is converted to the user space.
However, thread_termination_handler is a kernel space, so if
thread_termination_handler works, it should work in kernel space.
=> kernel/signal : Operate thread_termination_handler in kernel space

framework/include/araui/ui_widget.h, framework/src/araui/core/ui_core.c, framework/src/araui/include/ui_widget_internal.h, framework/src/araui/widgets/ui_widget.c
- `ui_widget_body_t` has the animation finished callback function
- `animation_callback` is removed, the UI core use animation function directly
=> framework/araui: Add animation finished callback function

framework/src/araui/core/ui_core.c, framework/src/araui/core/ui_window.c, framework/src/araui/include/ui_commons_internal.h, framework/src/araui/include/ui_renderer.h, framework/src/araui/include/ui_widget_internal.h, framework/src/araui/renderer/ui_renderer.c, framework/src/araui/widgets/ui_image_widget.c, framework/src/araui/widgets/ui_text_widget.c, framework/src/araui/widgets/ui_widget.c
Previously, partial display update algorithm was not applied to the rotate and scale APIs.
(ui_widget_set_rotation(), ui_widget_set_scale())
From now on, partial display update algorithm is usable when rotate and scale APIs are called.
In order to provide this feature, the below modifications are applied.
1. transformation matrix is stored to the widget.
2. update transform matrix step is added before rendering widgets.
3. ui_window_add_redraw_list() is only called at the core.
(except ui_widget_set_position(). For this case, the previous location also needed to be update.)
=> framework/araui: Apply partial display update to rotate and scale APIs.

os/drivers/testcase/kernel_testcase_drv.c
Fix wrong printf format for long type
=> os/driver/testcase/kernel_testcase_drv : Fix wrong printf format

apps/platform/gnu/Kconfig, apps/system/init/init.c, os/kernel/init/os_bringup.c
The cxxinitialize function is in application context, not kernel context.
So, let's do it in preapp task which is running on application context.
Additionally let's make a dependancy between HAVE_CXXINITIALIZE and
SYSTEM_PREAPP_INIT to run preapp task automatically when cxx is enabled.
=> apps/system: do cxxinitialize from preapp task

os/arch/arm/src/imxrt/chip/imxrt102x_dmamux.h
IMXRT_DMACHAN_ACMP3 is duplicated because there is typo in imxrt102x_dmamux.h
So I changed the typo to fit its original purpose
=> os/arch/arm/src/imxrt/chip/imxrt102x_dmamux : Rename duplicate macro

apps/system/utils/fscmd.c
- printf in fscmd.c are modified.
- closedir are added to prevent resource leaks.
=> apps/system: Modify invalid formats of printf arguments.

loadable_apps/loadable_sample/micomapp/micomapp.c
Fix printf arg count mismatch because there is a printf with an incorrect number of args in micomapp
=> loadable_apps/micomapp : Fix printf arg count mismatch

loadable_apps/loadable_sample/wifiapp/wifiapp.c
Fix printf arg count mismatch because there is a printf with an incorrect number of args in wifiapp.c
=> loadable_apps/wifiapp : Fix printf arg count mismatch

apps/examples/testcase/ta_tc/messaging/utc/utc_messaging_recv.c, apps/examples/testcase/ta_tc/messaging/utc/utc_messaging_send.c
Fix coverity issues that uninitialized pointer read in utc_messaging_send.c and double free in utc_messaging_recv.c
=> apps/example/ta_tc/messaging/utc : Fix coverity issues

apps/examples/testcase/le_tc/kernel/tc_pthread.c
If g_cond_sig_val is not same with VAL_ONE run pthread_mutex_destroy.
So I added that unlock g_mutex before pthread_mutex_destory.
=> testcase/kernel : Unlock mutex before pthread_mutex_destroy

framework/src/araui/core/ui_core.c, framework/src/araui/include/ui_widget_internal.h, framework/src/araui/widgets/ui_widget.c
Previously, there are several recursive function calls in the AraUI.
In order to reduce using stack memories, these recursive function calls are changed in to the loop structure.
=> framework/araui: Modify recursive function calls to the loop structure.

apps/examples/testcase/le_tc/filesystem/fs_main.c
- 'defined(CONFIG_FLASH_PARTITION)' is added to correct the build error of a ftl TC.
=> apps/examples: Fix a FS TC build error

lib/libc/string/lib_stpncpy.c
CONFIG'C'_ is a typo, let's remove 'C'.
=> libc/string: fix typo, CONFIGC_ARCH_STPNCPY

os/binfmt/libelf/libelf.h, os/binfmt/libelf/libelf_cache.c
- The logic for setting cut-off ratio for number of blocks to be used for elf block caching (when loading) was not merged in earlier pull request.
- In this PR, using CUTOFF_RATIO_CACHE_BLOCKS macro, we set number to blocks to use in elf caching inside elf_cache_init.
Signed-off-by: Nishtha97 <n.maloo@samsung.com>
=> os/binfmt/libelf: Set cut-off ratio for no. of blocks for elf block caching

framework/src/araui/core/ui_core.c, framework/src/araui/widgets/ui_widget.c
- In order to prevent unpredicted operations, add return value check procedures.
- When return value of the queue is NULL, it means error case (i.e, memory violations). Therefore it considered as an error case.
=> framework/araui: Add return check procdures

external/include/protocols/libcoap/config.h
TLS in coap used easy tls module that isn't supported anymore.
so TizenRT disable it until easy tls is replaced.
=> coap: fix coap build on Artik053

build/configs/imxrt1020-evk/SAM/defconfig, build/configs/imxrt1020-evk/loadable_elf_apps/defconfig, build/configs/imxrt1050-evk/loadable_elf_apps/defconfig, build/configs/imxrt1050-evk/wifi_loadable/defconfig, lib/libc/Kconfig, lib/libc/symtab/Make.defs, os/binfmt/Kconfig
symtab APIs are used only when loader tries to load.
So add symtab config to enable/disable.
=> libc/symtab : Add config for symtab APIs

apps/examples/testcase/ta_tc/messaging/utc/utc_messaging_multicast.c, apps/examples/testcase/ta_tc/messaging/utc/utc_messaging_recv.c, framework/src/messaging/messaging_cleanup.c
1.  framework/messaging : Change empty check logic for cleanup
If port_info reaches the end of the g_port_info_list, it also returns OK.
For distinguishing the empty of g_port_info_list and no matched case, make boolean variable.
2. apps/testcase/messaging : Modify cleanup tc of recv and multicast
messaginig_cleanup only works with port owner who registered the port.
so calling cleanup in each receivers.
=> framework/messaging : Modify cleanup

framework/src/wifi_manager/wifi_manager.c
- When disconnect is done quickly before starting softap mode,
state might be changed to DISCONNECTED (not DISCONNECTING),
so add a logic to handle this exceptional case.
=> framework/wifi_manager: Calling SoftAP mode transition after disconn

framework/src/messaging/messaging_common.c
There are same error return statements. They can be unified as goto.
=> framework/messaging : Unify the error return case as goto

framework/src/araui/core/ui_core.c, framework/src/araui/widgets/ui_widget.c
- As ui_render_widget() is added and used for update global_rect of each widget, ui_widget_update_position_info() is no longer used for updating the global_rect of widget.
Therefore the operation of ui_widget_update_positio_info() is chaged to set the update_flag of widget.
- The prototype of unused api (_ui_widget_destroy_recur()) is removed.
- Unncessary operation in _ui_update_redraw_list() is removed.
=> framework/araui: Modify operation of ui_widget_update_position_info()

framework/src/araui/widgets/ui_text_widget.c
- Modify #ifdefine location.
- add static to global variable.
=> framework/araui: Fix text widget issue

apps/examples/testcase/le_tc/kernel/tc_libc_timer.c, lib/libc/time/lib_strftime.c
1.
In certain cases strftime function returns a different value.
For example, "%a" case can return "Day" or a three letter abbreviation for the day of the week depending on whether the particular CONFIG value is on off or not.
So I added #if line to handle this.
2.
libc_strftime.c have no explanation of %a and %A cases.
so I added explanation of this two cases.
=> Add strftime testcase and add missing explanation of strftime

apps/examples/testcase/le_tc/drivers/drivers_tc_main.c, apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/kernel/kernel_tc_main.c, apps/examples/testcase/le_tc/network/network_tc_main.c, apps/examples/testcase/le_tc/tcp_tls/tcp_tls_stress.c, apps/examples/testcase/le_tc/ttrace/ttrace_tc_main.c, apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c, apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c, apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c, apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c, apps/examples/testcase/ta_tc/device_management/itc/itc_dm_main.c, apps/examples/testcase/ta_tc/device_management/utc/utc_dm_main.c, apps/examples/testcase/ta_tc/eventloop/utc/utc_eventloop_main.c, apps/examples/testcase/ta_tc/media/itc/itc_media_main.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp, apps/examples/testcase/ta_tc/messaging/utc/utc_messaging_main.c, apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c, apps/examples/testcase/ta_tc/mqtt/utc/utc_mqtt_main.c, apps/examples/testcase/ta_tc/security/utc/utc_security_main.c, apps/examples/testcase/ta_tc/systemio/itc/itc_sysio_main.c, apps/examples/testcase/ta_tc/systemio/utc/utc_sysio_main.c, apps/examples/testcase/ta_tc/task_manager/itc/itc_taskmanager_main.c, apps/examples/testcase/ta_tc/task_manager/utc/utc_taskmanager_main.c, apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifimanager_main.c, apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifimanager_main.c, apps/examples/testcase/tc_common.h, apps/examples/testcase/tc_main.c, external/libcxx-test/utc_libcxx.c
It is difficult to know what it is from the function name and
is not a testcase function to test something.
So, this commit renames it as testcase_state_handler.
=> testcase: rename tc_handler to testcase_state_handler

apps/examples/testcase/ta_tc/task_manager/utc/utc_taskmanager_main.c, framework/src/task_manager/task_manager_broadcast.c, framework/src/task_manager/task_manager_register.c, framework/src/task_manager/task_manager_set_callback.c, framework/src/task_manager/task_manager_unicast.c
1.     framework/task_manager : Modify wrong cmd in set callback and Merge duplicated errout case
. taskmgr_set_cb_common should set the cmd based on passed param
. Freeing some data is duplicated for error case. Merged them.
2.     apps/testcase/task_manager : Expand utc for pthread to start and stop with group permission
There was a utc for pthread, but only testing register and unregister.
Expand to test task_manager_start and task_manager_stop with group permission.
=> framework/task_manager : coverage enhancement

os/board/imxrt1050-evk/src/imxrt_boot.c
Current peripheral initialization is not working well. It blocks
seeing serial logs. Let's block them temporarily.
=> board/imxrt1050-evk: block peripheral initialization to support serial

os/board/artik05x/src/Makefile, os/board/imxrt1020-evk/src/Makefile, os/board/imxrt1050-evk/src/Makefile
crashdump.c and DEPPATH,VPATH for board/common do not need to bounded to CONFIG_FLASH_PARTITON config.
=> board : Move crashdump build condition and build path of board/common

framework/src/messaging/messaging_common.c
Commit e7f8067 unified the error return case using goto.
If there is no error, it has to finish without freeing memory allocated.
So, return should be located before goto.
This commit fixes the wrong location of return.
=> fixup! framework/messaging : Unify the error return case as goto

os/binfmt/binfmt_execmodule.c, os/kernel/task/task_init.c
1. When execution of task_init() is failed, it should free
the stack allocated before. But it doesn't.
This commit adds the "errout_with_stack" tab to do it.
2. kumm_free(stack) and mm_free(binp->uheap, stack) are the same.
Let's remove duplicated code with CONFIG_APP_BINARY_SEPARATION.
3. Making "tcb->cmn.stack_alloc_ptr" null is done by sched_realeasetcb().
Let's remove duplication.
=> binfmt: fix missing of freeing stack allocated and tidyup

framework/src/media/audio/audio_manager.c
The reset_audio_stream_in function should be called
but the reset_audio_stream_out function is called.
=> framework/media: fix invalid function call

os/drivers/task_manager/task_manager_drv.c, os/include/tinyara/binary_manager.h, os/kernel/binary_manager/binary_manager_getinfo.c, os/kernel/binary_manager/binary_manager_load.c
sched_gettcb can return NULL when cannot find the tcb.
In this case, we should not use the tcb in the below.
=> drivers/task_manager : Add NULL checking after sched_gettcb

framework/src/media/audio/audio_manager.c, framework/src/media/audio/resample/samplerate.c, framework/src/media/audio/resample/samplerate.h
- Separate code of src_simple()  into several sub functions, to improve readability.
- Merge most resampling methods into one common method.
- Remove unused and  APIs: src_StereoToMono/src_MonoToStereo.
- Improve resampling quality.
=> framework/media/audio: Refactor audio resampling code

os/drivers/usbhost/Kconfig, os/drivers/usbhost/rtl8723d.c
- rtl wifi destory API is not used, because rtl is embedded in NXP board.
=> wifi/rtl8723d: disable unused rtl APIs

apps/examples/testcase/le_tc/kernel/Kconfig, apps/examples/testcase/le_tc/kernel/kernel_tc_main.c, apps/examples/testcase/le_tc/kernel/tc_libc_misc.c
- Remove select option of DEBUG and DEBUG_ERROR/VERVOSE in Kconfig
- Add ifdef depending on configuration of DEBUG and DEBUG_ERROR/VERVOSE
=> testcase/kernel: Remove dependency on DEBUG of kernel_tc

os/binfmt/binfmt_loadbinary.c
The name of a main task is set as binary name when loading binary.
=> os/binfmt: Set name of main task as binary name

framework/src/media/audio/audio_manager.c
Capture should resample data based on user input.(Contrary case for playback)
=> media/audiomanager: Fix resampler bug

framework/src/wifi_manager/wifi_manager.c, framework/src/wifi_manager/wifi_utils_lwnl80211.c
- g_lwnl_hnd and g_lwnl_signal in wifi_utils_lwnl80211.c
- g_handler in wifi_manager.c
=> framework/wifi_manager: Static declaration of global variables

framework/src/wifi_manager/wifi_manager.c
- Add a logic to check whether socket open is failed or not
Because socket open fail at this stage is very critical to the entire wifi manager's operation, it is better to use DEBUGASSERT.
=> framework/wifi_manager: socket open fail check

os/binfmt/binfmt_loadbinary.c, os/include/tinyara/binfmt/binfmt.h, os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_load.c
- Retry binary loading in a failure
- Remove unnessasary locking scheduling when binary loading
=> kernel/binary_manager: Support to retry loading in a failure and Remove unnessasary sched_lock/unlock

os/binfmt/libelf/libelf_cache.c
-Assign no. of blocks for caching based on correctly updated number of blocks in file
Signed-off-by: Nishtha97 <n.maloo@samsung.com>
=> os/binfmt/libelf: Correctly assign number of blocks for caching

os/drivers/testcase/kernel_testcase_drv.c
There is a typo, change tg_gpid to tg_pgid
=> drivers/testcase : Fix typo for tg_pgid

apps/examples/testcase/le_tc/kernel/tc_task.c, os/drivers/testcase/kernel_test_proto.h, os/drivers/testcase/kernel_testcase_drv.c, os/drivers/testcase/test_task_init.c
User entry function should be located in userspace because user can't access kernel region.
=> testcase/kernel: Move user entry function for task_init to userspace

apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
Fixed issues:
- The handle 'fp' was created at utc_media_mediaplayer.cpp:86 by calling function 'fopen' and lost at utc_media_mediaplayer.cpp:90.
- Return value of a function 'fopen' is dereferenced at utc_media_fileinputdatasource.cpp:154 without checking, but it is usually checked for this function.
=> examples/media/utc: fix handle leak and check issues in utc functions

framework/src/araui/widgets/ui_widget.c
When a widget needs update transform matrix (when it is scaled or set pivot point), add set the update flag procedures to be updated its transform matrix by core thread.
=> framework/araui: Add set the update flag procedures

framework/src/araui/Kconfig, framework/src/araui/core/ui_core.c, framework/src/araui/core/ui_window.c, framework/src/araui/include/ui_window_internal.h, framework/src/araui/widgets/ui_widget.c
Previously, AraUI framework provided partial display update feature as default.
From now on, user can select the option for the partial display update or full display update.
=> framework/araui: Add partial display update config

os/compression/compress_read.c
- Keep entire compression header, including block offsets, in memory when loading compressed binary.
- Overhead of time taken to get block's offset from file using seek is eliminated.
This significantly reduces time taken for compressed binary loading.
=> os/compression/compress_read.c : Reduce loading time for compressed binary

os/binfmt/libelf/libelf.h, os/binfmt/libelf/libelf_bind.c, os/binfmt/libelf/libelf_symbols.c, os/include/tinyara/binfmt/elf.h
Allocate memory from kernel heap for symbol table and reloc table.
Read complete symbol table and relocation table into RAM before
starting the relocation process. All accesses to the symbol and
relocation table will be done using the RAM instead of Flash. This
will reduce the relocation time.
=> os/binfmt: Read symbol table and relocation table into RAM

os/arch/arm/src/armv7-m/up_doirq.c, os/arch/arm/src/armv7-m/up_lazyexception.S
This patch adds support of nested interrupt in flat binary
as well as move logic of incrementing g_nestlevel and storing
current_regs value in critical area under exception_common function
Signed-off-by: Drashti Parikh <p.drashti@partner.samsung.com>
=> arch/arm/src/armv7-m: Add support of nested interrupt in flat binary

os/wqueue/work_process.c, os/wqueue/work_queue.c
Build failed for "stm32" boards with below error 
configs:
stm32f429i-disco/hello
stm32f407-disc1/hello
CC:  work_queue.c
work_queue.c: In function 'work_qqueue':
work_queue.c:137:2: error: 'next_work' undeclared (first use in this function)
next_work = NULL;
^~~~~~~~~
CC: work_process.c
work_process.c: In function 'work_process':
work_process.c:277:28: error: 'set' undeclared (first use in this function)
DEBUGVERIFY(sigwaitinfo(&set, NULL));
CC: work_process.c: In function 'work_process':
work_process.c:257:4: error: 'remaining' undeclared (first use in this function)
remaining = work->delay - elapsed;
^~~~~~~~~
Signed-off-by: Satheesh Kumar <satheesh.ks@samsung.com>
=> wqueue: Fix build error in HP/LP worker thread's

apps/examples/testcase/ta_tc/media/utc/utc_media_focusmanager.cpp, framework/include/media/FocusManager.h, framework/src/media/FocusManager.cpp
FocusManager::requestFocus considers stream policy.
So if the requiring FocusRequest has lower priority, it will not gain focus.
=> framework/media: Manage focus with stream policy

lib/libc/unistd/lib_usleep.c
Since usleep operates in tick, It always works by counting in tick.
=> libc/unistd : Add a comment about usleep operates in tick

apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifimanager_main.c, apps/examples/wifi_manager_sample/wm_test.c, framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/slsi_wifi_utils.c, framework/src/wifi_manager/wifi_manager.c, framework/src/wifi_manager/wifi_utils_lwnl80211.c, os/drivers/lwnl/lwnl80211.c, os/drivers/lwnl/slsi_drv.c, os/drivers/wireless/realtek/wifi_util_interface/rtk_drv_lwnl80211.c, os/drivers/wireless/realtek/wifi_util_interface/rtk_drv_lwnl80211.h, os/include/tinyara/lwnl/lwnl80211.h, os/include/tinyara/lwnl/slsi_drv.h
Add an API of wifi_manager_scan_specific_ap for targetted scanning
- Modify the input type of internal scanning APIs
- Applied to slsi and rtk lwnl80211 drv
- Add UTC for newly added API
=> framework/wifi_manager: Add an API for scanning specific AP

os/arch/arm/src/armv7-m/up_assert.c, tools/ramdump/HowToUseRamdump.md, tools/ramdump/ramdump.sh, tools/ramdump/ramdump_tool.c
This patch adds support for the user to enter choice of the
device port connected to the linux machine. It will help to
take ramdumps for all kind of boards rather than only ttyUSB1.
Interface looks like:
********************************************************************
sh ramdump.sh
Please enter serial port adapter:
For example: /dev/ttyUSB0 or /dev/ttyACM0
Enter:
/dev/ttyUSB0
/dev/ttyUSB0 open failed!!
Please enter correct device port
Enter:
/dev/ttyUSB1
Target Handshake successful do_handshake
Target entered to ramdump mode
.
.
.
Ramdump received successfully..!
********************************************************************
=> tools/ramdump: Enabled user input for different device ports.

framework/include/media/MediaUtils.h, framework/src/media/utils/MediaUtils.cpp
Implement simple MPEG2-TS demux inside media utils.
It's light-weighted, and has below limitations:
- Do not support multi sections in neither PAT nor PMT.
- Do not support one section packaged in multi TS packets.
- Do not support PSI table version detecting.
But it meets the requirement to abstract audio informations
from MPEG2-TS data stream.
=> framework/media/utils: Remove dependence on mpeg2ts demux module

os/arch/arm/src/common/up_initialize.c, os/arch/arm/src/stm32/stm32_eth.c, os/arch/arm/src/tiva/tm4c_ethernet.c, os/arch/xtensa/src/esp32/esp32_spi.c, os/drivers/net/phy_notify.c, os/drivers/net/telnet.c, os/drivers/pipes/pipe.c, os/drivers/syslog/ramlog.c, os/fs/driver/Make.defs, os/fs/driver/block/driver.h, os/fs/driver/block/fs_blockproxy.c, os/fs/fs_initialize.c, os/include/semaphore.h, os/include/tinyara/fs/fs.h, os/include/tinyara/net/phy.h, os/kernel/init/os_bringup.c, os/kernel/messaging/message_ctrl.h, os/kernel/messaging/messaging.c, os/net/bluetooth/bluetooth.c, os/net/bluetooth/bt_conn.c, os/net/bluetooth/bt_conn.h
All kernel semaphores should be intialized by sem_init for recovery.
In App separation, they are registered to a list in sem_init and recovered when fault occurs.
=> kernel/semaphore: Initialize kernel semaphores with sem_init instead of SEM_INITIALIZER

framework/src/araui/widgets/ui_text_widget.c
1. fix memory overwrite issue when text size is too big, and also
the memset is unnecessary here.
2. fix building issue of ui_render_quad_uv function call
@gcjjyy
=> framework/araui: fix text widget issues

framework/src/dm/conn/wifi/slsi_dm_connectivity.c, os/drivers/wireless/scsc/slsi_drv.c, os/drivers/wireless/scsc/slsi_utils.c, os/drivers/wireless/scsc/slsi_wifi_api.c, os/include/tinyara/wifi/slsi/slsi_wifi_api.h
- Wildcard SSID in probe request forces for the surrounding APs to send probe response,
which is not efficient and makes it possible to miss the target AP's probe response when there are many near by AP with high traffic ratio.
This implementation inserts a specific SSID into probe requenst not wildcard SSID,
which reduces the scanning duration by an average value of 250 ms.
=> os/drivers/scsc: Implement probe request to send target SSID

framework/src/media/audio/audio_manager.c
audio manager does not need to care rechanneling logic, which has been implemented in src_simple().
=> framework/media: Refine rechanneling logic in audio manager

apps/examples/nanopb_simple/Makefile
NanoPb submodule could not be updated.
In this case, Makefile of nanopb_simple can't include
nanopb/extra/nanopb.mk
=> examples/nanopb_simple: Modify Makefile

apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
- To increase procfs code coverages, dup() is added to a procfs TC.
=> app/examples: Add a dup function to a procfs test case.

os/include/tinyara/wqueue.h, os/wqueue/kwqueue/kwork_queue.c, os/wqueue/uwqueue/uwork_queue.c, os/wqueue/work_queue.c, os/wqueue/wqueue.h
os/wqueue : Check underflow in remaining time
If 'elapsed' is greater than 'cur_work->delay', there is an underflow.
So It must check.
os/wqueue : Modify the 'delay' type
Since the value of 'delay' uses clock, I changed the data type to clock_t.
=> os/wqueue : Refactor work queue

os/arch/arm/src/imxrt/imxrt_norflash.c
- By adding dcache invalidation when erasing flash, MTD_ERASE failures
which occur rarely disappear.
=> arch/arm: Add dcache invalidation to imxrt1020 flash driver.

apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
- To increase the code coverage of procfs which uses mtd,
a dup() is added to mtd procfs TCs.
=> app/examples: Add a dup function to mtd procfs test cases.

framework/src/wifi_manager/Kconfig
add netlib dependency to wifi manager configuration to prevent build
errors
=> wifi_manager: add dependency in wifi manager config

os/arch/arm/src/common/up_allocateheap.c, os/arch/xtensa/src/esp32/esp32_allocateheap.c, os/kernel/init/os_start.c
We can check that heap is initialized or not with heap size. Because, if it is initialized, the size of its heap will not be zero.
So we don't need to use heapx_is_init array anymore.
=> kernel/allocateheap : Remove unnecessary heap initialization checking

framework/src/wifi_manager/wifi_manager.c, framework/src/wifi_manager/wifi_manager_dhcp_internal.c, framework/src/wifi_manager/wifi_manager_dhcp_internal.h
- Rename dhcps_start/stop to solve conflict with lwip dhcp function names
- Remove static predef in header
=> framework/wifi_manager: DHCP bug fix

build/configs/esp32_DevKitC/.buildSpec.xml, build/configs/esp32_DevKitC/.flashSpec.xml, build/configs/esp_wrover_kit/.buildSpec.xml, build/configs/esp_wrover_kit/.flashSpec.xml
To support build and flash project with Tizen Studio RT IDE on esp32 boards.
(co-work with PR #4023)
=> build/configs: Add meta files to support esp32 boards on RT IDE

framework/src/security/security_ss.c, os/Directories.mk
ctx was not used in secure storage API so it caused build error when
log option is turned off.
=> security: remove unused variable

os/kernel/semaphore/sem_post.c
Call directly without assigning rtcb variable because it is used when enabling some configurations only.
=> kernel/semaphore: Remove unnecessary variable

os/fs/smartfs/smartfs_utils.c, os/include/errno.h
Remove EINVAL_SECTOR from errno which is not defined in linux
=> fs/recovery : remove unnecessary errno

os/dbuild.sh
In previous version, build error occured because the board name passed as an argument is changed to lowercase.
for example esp32_DevKitC is changed to esp32_devkitc.
=> os/dbuild.sh : fix build error

os/arch/xtensa/src/Makefile
1. esp32/spi_flash dir is missed in makefile for making depend
2. remove useless code for nonexist dir 'common'
=> os/arch/xtensa: add missing dep-path for xtensa

apps/examples/camera/Kconfig, apps/examples/camera/camera_main.c
When ENTRY_CAMERATEST is enabled, USER_ENTRYPOINT must be 'camera_main'.
=> apps/camera : Add USER_ENTRYPOINT when Enable ENTRY_CAMERATEST

README.md
Blockquote in README.md misses a ` character. This commit fixes it.
=> [README.md] Fix blockquote in README.md

framework/src/wifi_manager/wifi_manager.c
- Return WIFI_MANAGER_BUSY intead of WIFI_MANAGER_FAIL for connecting/disconnecting state,
which are waiting for callbacks from the driver
=> framework/wifi_manager: Fix return type when waiting callback

external/stdk/tizenrt-wrapper/bsp/iot_bsp_wifi_common.c
1. remove unnecessary check condition to _obtain_time after set STA mode
(some board may have future time as default system time)
2. refine the hard code of 2016-1900 year check condition
=> external/stdk: refine obtain time check condition

build/configs/qemu/tc_16m/Make.defs, build/configs/qemu/tc_16m_grpc/Make.defs, build/configs/qemu/tc_1m/Make.defs, build/configs/qemu/tc_64k/Make.defs
Without this commit, CXX can't include framework headers.
=> configs/qemu: Add framework dir at ARCHXXINCLUDES

os/arch/arm/src/stm32l4/Make.defs, os/arch/arm/src/stm32l4/hal/stm32l4xx_hal_interface.c, os/arch/arm/src/stm32l4/stm32l4_serial.c, os/arch/arm/src/stm32l4/stm32l4_start.c, os/board/stm32l4r9ai-disco/src/Makefile
This patch enables ramdump support using TizenRT ramdump tool for stm32l4 board.
Please enter serial port adapter:
For example: /dev/ttyUSB1 or /dev/ttyACM0
Enter:
/dev/ttyACM0
[sudo] password for vidisha:
Target Handshake successful do_handshake
Target entered to ramdump mode
=========================================================================
Ramdump Region Options:
1. ALL
2. Region 0:    ( Address: 0x20000000, Size: 196608 )    [Heap index = 0]
3. Region 1:    ( Address: 0x20030000, Size: 65536 )     [Heap index = 0]
4. Region 2:    ( Address: 0x20040000, Size: 393216 )    [Heap index = 0]
=========================================================================
Please enter desired ramdump option as below:
1 for ALL
2 for Region 0
25 for Region 0 & 3 ...
Please enter your input: …
=> Add ramdump support for stm32l4

os/arch/arm/src/imxrt/Make.defs, os/arch/arm/src/imxrt/imxrt_lowputc.c, os/arch/arm/src/imxrt/imxrt_lowputc.h
This patch add interface for TizenRT ramdump tool.
Find the below test logs :
Please enter serial port adapter:
For example: /dev/ttyUSB1 or /dev/ttyACM0
Enter:
/dev/ttyACM0
Target Handshake successful do_handshake
Target entered to ramdump mode
=========================================================================
Ramdump Region Options:
1. ALL  ( Address: 80000000, Size: 33554432 )
=========================================================================
Please enter desired ramdump option as below:
1 for ALL
Please enter your input: 1
No. of Regions to be dumped received: ramdump_recv
Receiving ramdump......
=========================================================================
Dumping data, Address: 0x80000000, Size: 33554432bytes …
=> arch/arm/src/imxrt: Support ramdump via uart support in imxrt board.

tools/symbolview/README.md, tools/symbolview/symbolviewer.py
It will support developer to follow call stack to improve aborted application.
1. Enable Debug Options.
Debug Options
-> [*] Enable backtracking using Frame pointer register
2. Run logassist.
[TizenRT]/tools$ python symbolviewer.py /dev/ttyUSB1
example:
print_callstack: *******************************************************************************
unwind_backtrace_with_fp: Task: [appmain], Pid: [6], TaskAddr: [0x206b7d0] and [Current : appmain]
unwind_backtrace_with_fp: stack size 0x27ec
unwind_backtrace_with_fp: Registers are Valid, We may be either Interrupt context/exception context
unwind_backtrace_with_fp: fp:0x2070bbc , sp:0x2070b90 , pc:0x412ba30
unwind_backtrace_with_fp: [<0x412ba30>]
: /root/tizenrt/framework/src/st_things/things_stack/framework/things_security_manager.c:702 …
=> tools/symbolviewer: Support printing call stack information.

os/binfmt/libelf/libelf_cache.c, os/binfmt/libelf/libelf_read.c, os/compression/compress_read.c
This PR contains below changes:
- Removes caching of large readsize requests.
- Removes an unnecessary file seek from compressed elf loading
- Removes needless caching of one additional block for compressed elf loading
- Adds check for minimum number of blocks needed for caching.
Together, they significantly reduce loading time for uncompressed/compressed elfs.
=> os: Refine caching logic for improved loading time

os/drivers/video/video.c, os/include/video/video.h
This patch involves 
- support for colorspace, formats like MJPEG/YUY2
- Modify set_buff api to pass args value, which is used in transfer complete callback
=> drivers/video: Support for colorspace and formats(MJPEG/YUY2)

os/compression/Kconfig
Miniz has lower compression ratio, but has big advantage of decompressing compared with LZMA.
So select the default compression algorithm as Miniz.
=> compression : Change default compression algorithm to Miniz

os/board/sidk_s5jt200/src/slip_if.c, os/fs/aio/aioc_contain.c, os/fs/inode/fs_files.c, os/fs/vfs/fs_dupfd.c, os/fs/vfs/fs_dupfd2.c, os/fs/vfs/fs_fcntl.c, os/fs/vfs/fs_fdopen.c, os/fs/vfs/fs_fstat.c, os/fs/vfs/fs_fstatfs.c, os/fs/vfs/fs_fsync.c, os/fs/vfs/fs_getfilep.c, os/fs/vfs/fs_ioctl.c, os/fs/vfs/fs_lseek.c, os/fs/vfs/fs_open.c, os/fs/vfs/fs_poll.c, os/fs/vfs/fs_pread.c, os/fs/vfs/fs_pwrite.c, os/fs/vfs/fs_read.c, os/fs/vfs/fs_write.c, os/include/tinyara/fs/fs.h
It no longer sets the errno variable but, rather, returns errors in the same manner as other internal OS functions.
This commit is taken from Nuttx.
=> fs/vfs:  Change the return value of fs_getfilep()

os/board/imxrt1020-evk/src/Makefile, os/board/imxrt1050-evk/src/Makefile
Add proper include path for board compilation.
=> board/imxrt1020,imxrt1050: Set proper include in imxrt.

framework/src/araui/core/ui_core.c
Previously, when a FPS of certain frame belows a maximum FPS which was set through menuconfig, the compensation occurs in the next frame.
(i.e., if the maximum FPS is set as 30 and certain frame's FPS is 29, then the next frame's FPS compensated with 31 (if possible).)
Therefore, the compensated frame's FPS exceeds the maximum FPS value.
In this pull request, above problem is solved.
=> framework/araui: Change the FPS calculate procedure.

os/dbuild.sh
dbuild.sh doesn't work out on centos linux with permission problem.
Add --privileged option to fix it
=> os: Modify dbuild.sh to work around on centos linux

os/fs/vfs/fs_open.c
'va_start' is used in function with fixed args.
'va_start'/'va_end' should not be used in vopen function,
because it has fixed arguments.
=> fs/vfs/fs_open.c:  Fix error in vopen() function

os/kernel/task_monitor/task_monitor.c
Overflow can occur at line 64 and line 174.
It has to search for node from head to next. (line 163)
=> kernel/task_monitor : Fix wrong logic

os/fs/driver/mtd/smart.c
The logical sector size cannot be smaller than the MTD device's block/page size (256B)
The logical sector size cannot be larger than the MTD devices's reported erase block size (1024B)
The number of logical sectors per MTD device erase block cannot be greater than 256, and 4 - 128 is the best choice (2 with bs = 512B, 1 with bs = 1024B)
=> os/fs/driver/mtd: Fix for smartfs.bin mount failure and improper CRC comparison

docs/HowToPortTizenRTOnWiFiChipset.md
It has some `<br>` tags. and it is not allowed as a markdown syntax.
So, The doc. has shown a wrong outputs.
=> docs: remove HTML tags on Markdown doc. for HowToPortTizenRTOnWiFiChipset.md

external/error_report/error_report.c
The `prv_fetch_taskaddr` internal function in error report does not require the `pid` argument, and can be deleted.
=> [external/error_report]: Fix redundant parameter in error report

apps/shell/tash_command.c, apps/shell/tash_internal.h, apps/shell/tash_main.c
If CONFIG_TASH_MAX_STORE_COMMANDS is not config,
'#if CONFIG_TASH_MAX_STORE_COMMANDS > 0 'is build warning.
So modified from '#if CONFIG_TASH_MAX_STORE_COMMANDS > 0' to
'#if TASH_MAX_STORE > 0'.
=> apps/shell : Fix build warning

build/configs/artik05x/scripts/memory_layout.ld
memory_layout.ld is not needed in artik.
So it deleted.
=> conifgs/artik05x : Delete unnecessary file

os/net/socket/net_sockets.c
lwip doesn't use group->tg_socketlist.
It will be used for UDS.
=> net/socket: Remove lwip code at net_sockets.c

os/include/sys/sock_internal.h, os/include/sys/socket.h, os/include/tinyara/lwnl/lwnl.h
After including LWIP, socket.h define address families and protocol
families which are not defined.
=> socket: Define PF and AF after including LWIP

os/net/lwip/src/api/api_lib.c, os/net/lwip/src/api/api_msg.c, os/net/lwip/src/api/tcpip.c, os/net/lwip/src/include/lwip/api.h
Synchronize access to mbox using a `op-sync` sempahore. In effect, this commit reinstates an earlier [patch](https://github.com/Samsung/TizenRT/commit/19d2dc6e33df7fece97ac5d6df8ca66dccd60ac2#diff-a9481755452c015da55b0766857a43dc) that was removed over time.
=> net/lwip: Synchronize access to mbox between sending tasks

os/net/netmgr/netstack.h
struct netmon_sock is defined at net/if.h
=> net/netmgr: Add missed header

os/arch/arm/src/stm32/stm32_eth.c
[SPC_M_OPR] spaces prohibited around that ':' (ctx:VxW)
=> stm32: Fix coding rule violation

external/include/libcxx/cstddef
max_align_t will be needed for tflite framework.
test result -
============ Test ofstream ==============================
printf: Starting test_ostream
printf: Successfully opened /dev/console
cout: Successfully opened /dev/console
Writing this to /dev/console
============ Test iostream ==============================
Hello, this is only a test
Print an int: 190
Print a char: d
============ Test STL(Array) ============================
1 2 3 4
10 11 12 13
=> external/include/libcxx: Backport max_align_t type from LLVM. 

os/net/lwip/src/api/api_lib.c, os/net/lwip/src/api/api_msg.c, os/net/lwip/src/api/tcpip.c, os/net/lwip/src/include/lwip/api.h
Reverts Samsung/TizenRT#4137 in light of crashes seen when running ST things application.
=> Revert "net/lwip: Synchronize access to mbox between sending tasks"

os/include/sys/un.h
sockaddr_un must be cast compatible with sockaddr.
=> sys/un.h: Make sockaddr_un compatible with lwip

os/include/sys/un.h
This commit is taken from Nuttx.
=> include/sys/un.h: Remove an incorrect comment

os/binfmt/libelf/libelf_load.c, os/include/tinyara/mm/mm.h, os/mm/mm_heap/mm_heapinfo.c
The current user heap allocation logic is as follows:
1. allocate partition for app using kumm_memalign API
2. place the elf sections directly in this partition
3. initialize the uheap (which is the application's heap) at the end of the data section
So we don't need to exclude elf_sections_size anymore.
=> mm/mm_heapinfo : Remove unnecessary elf_sections_size exclusion

os/arch/xtensa/include/.gitignore
The build system makes the chip and board folders link at build time using
selected chip and board configuration. So it should not be shown at Git.
This commit adds .gitignore to blind them from git.
===================================================================
TizenRT$ git status
On branch master
Your branch is ahead of 'origin/master' by 44 commits.
(use "git push" to publish your local commits)
Untracked files:
(use "git add <file>..." to include in what will be committed)
os/arch/xtensa/include/board
os/arch/xtensa/include/chip
==================================================================
=> arch/xtensa/include: add .gitignore to blind the chip and board folders

build/configs/imxrt1050-evk/imxrt1050-evk_download.sh
… script
-Added provision in download script to flash
userfs (smartfs.bin) image to imxrt1050-evk board.
-Do a "sudo make download userfs" after
"sudo make downlaod ALL" to flash smartfs.bin image.
=> build/configs/imxrt1050-evk: Add userfs flash provision in download.sh script for Imxrt1050-evk.

loadable_apps/loadable_sample/Kconfig
Each test has a dependency on some configurations, messaging IPC or binary manager recovery.
=> loadable_apps: Add missing dependencies for each test

os/net/bluetooth/bt_conn.c, os/net/bluetooth/bt_hcicore.c, os/net/bluetooth/bt_ioctl.c, os/net/bluetooth/iob/iob_alloc.c, os/net/bluetooth/iob/iob_alloc_qentry.c
sem_wait return values are not handled properly.
Fix the return value handling.
=> net/bluetooth: Fix error handling in Bluetooth subsystem

tools/cmdautotest/README_CMDAutoTest.md, tools/cmdautotest/cmdautotest.py
Support for Python version 2 is coming to an end. Therefore, the syntax is modified to version 3.
=> tools/cmdautotest: Fix Syntax Python 2to3

os/include/mqueue.h, os/include/tinyara/mqueue.h, os/kernel/mqueue/mq_getattr.c, os/kernel/mqueue/mq_msgqalloc.c, os/kernel/mqueue/mq_rcvinternal.c, os/kernel/mqueue/mq_sndinternal.c, os/kernel/mqueue/mqueue.h
- Type of variables about message length, 'size_t'
. maxmsgsize in mqueue_inode_s
. msglen in mqueue_msg_s
. msglen parameters of MQ functions.
- Type of variables about message count, 'size_t'
. maxmsgs, nmsgs in mqueue_inode_s
. mq_maxmsg, mq_msgsize in mq_attr.
=> kernel/mqueue: Match types of variable between structures.

os/arch/Kconfig
CONFIG_KREGINOx_XXX configs are meaningful only when protected build.
=> arch/Kconfig : Add dependency for KREGIONx configs

os/arch/arm/src/armv7-m/up_svcall.c, os/binfmt/binfmt_execmodule.c, os/binfmt/binfmt_exit.c, os/binfmt/binfmt_unloadmodule.c, os/binfmt/elf.c, os/binfmt/libelf/libelf_addrenv.c, os/binfmt/libelf/libelf_load.c, os/tools/mkbinheader.py
If CONFIG_OPTIMIZE_APP_RELOAD_TIME is enabled, then we define 3 MPU regions
for loadable apps. The existing implementation for this is to allocate one large
memory region to cover text, ro, data and heap requirements of the applications.
This large memory region is configured as RW memory in the MPU. Additionally, we
define two MPU regions for text and ro areas which will overlap the large RW region.
Allocating memory regions in this way can sometimes result in wastage of memory
due to the address alignment and region size requirements of the MPU. Specifically,
memory wastage occurs due to resizing the large RW memory region according to the
MPU requirements.
In order to overcome this problem, we modify the memory regions as follows:
- Allocate 2 separate regions for text and ro
- …
=> os/binfmt: Modify loadable app memory regions to reduce memory wastage

os/fs/driver/mtd/smart.c, os/fs/smartfs/smartfs_utils.c, os/include/debug.h
- A sector size is fixed at the beginning of smart_scan since
existing sectors are deleted when the sector size is changed.
- Dangling entry chains are cleaned when accessed.
- The existence of the sector to save wear status of all sectors
is checked before it is accessed.
=> os/fs: Prevent and handle powercut failures

os/fs/driver/mtd/smart.c
- The freecount value of an erasable block mismatches with
actual block status when MTD_ERASE fails.
As a result, no physical sector is allocated and file system errors
occur at various moments.
Error handling code is added to avoid this situation.
- Useful debug messages are added also.
=> os/fs: Add error handling code when finding a free physical sector.

framework/src/araui/widgets/ui_text_widget.c
Except RGB888 mode, there was a build error
It is fixed
=> framework/araui: Fix build error (unused variable)

os/arch/arm/src/imxrt/imxrt_wdog.c, os/board/common/crashdump.c
This dependency causes build break in imxrt when ramdump is enabled.
This patch updates that dependency
It also updates crashdump file to send no Kernel MM heap notification to the ramdump tool in case only USer MM regions are present.
=> Update up_disable_watchdog() dependency on CONFIG_WATCHDOG_FOR_IRQ in imxrt

apps/examples/testcase/le_tc/filesystem/fs_main.c
The "lib and environment" testcases in the "testcase/le_tc/" path are considered to require itc for proper validation.
Therefore, it revert itc separation
=> testcase/filesystem: Revert itc separation of PR #4168

build/configs/esp_wrover_kit/README.md
I have faced an error when tried to setup env. to build.
the 'xvjf' means that the compressed file is bzip2.
but actually the file is not bzip file. so It can show some error messages.
=> build/configs/esp_wrover_kit: modify readme.md

apps/examples/camera/camera_main.c, os/arch/arm/src/common/up_initialize.c, os/board/imxrt1050-evk/src/imxrt_bringup.c, os/drivers/video/video_null_driver.c, os/drivers/video/video_null_driver.h
- Support for basic video null driver.
- currently the driver will return a empty buffer
- Provisions are there to read from a file and return the frame of the type requested by user.
- Initialize video_null code in "up_initialize"
=> os/drivers/video: Video null driver implementation

apps/examples/testcase/ta_tc/systemio/utc/Kconfig, apps/examples/testcase/ta_tc/systemio/utc/utc_adc.c
Following are appearing as undefined symbols in the libapps.a and are not getting resolved during final linking stage :
iotbus_adc_get_channel
iotbus_adc_get_state
iotbus_adc_set_channel
iotbus_adc_start
iotbus_adc_stop
TC_ASSERT_EQ
TC_ASSERT_GT
TC_ASSERT_LT
TC_ASSERT_NEQ
TC_SUCCESS_RESULT
utc_systemio_iotbus_adc_deinit_n
utc_systemio_iotbus_adc_deinit_p
utc_systemio_iotbus_adc_init_n
utc_systemio_iotbus_adc_init_p
=> apps/examples/testcase: Fix undefined symbols due to utc_adc testcase

lib/libc/stdio/lib_vdprintf.c
If the 1st param(fd) is not valid, dprint should be return negative value.
(https://pubs.opengroup.org/onlinepubs/9699919799/functions/dprintf.html)
=> libc/stdio : Add fd validation checking in vdprintf

apps/examples/testcase/le_tc/filesystem/fs_main.c
Add errno verification and fix expect value of the "tc_libc_stdio_dprintf_invalid_fd_n()" function.
#This PR works properly when PR #4211 is merge
=> testcase/filesystem: Add errno verification and fix expect value of dprintf negative case function

tools/ramdump/dumpParser.py
In some cases, the read() function read Bytes type data instead of String type.
So, in this cases we need to change bytes type to string type.
This problem can be solved by decode() function.
The decode() function can change bytes type to string type.
So, I added .decode() function to fix build errors.
=> ramdump/dumpParser.py : Add .decode() function to fix build error

apps/examples/nettest/nettest_stress.c
callback functions in nettest program should be static function.
=> network: modify redefinition in nettest stress

os/include/sys/syscall.h, os/include/tinyara/irq.h, os/include/tinyara/sched.h, os/kernel/binary_manager/binary_manager_recovery.c, os/kernel/init/os_start.c, os/kernel/irq/Make.defs, os/kernel/irq/fin_notify.c, os/kernel/irq/fin_wait.c, os/kernel/task/task_setup.c, os/syscall/syscall.csv, os/syscall/syscall_lookup.h, os/syscall/syscall_stublookup.c
Fast Interrupt Notification(FIN) is for event from kernel to user.
It has advantages of speed and RAM usage.
There is 1 public API which anyone can use, and 1 internal API which kernel only can use.
[public] fin_wait : wait to receive kernel irq event
[internal] fin_notify : send event to specific pid
=> kernel/task : Add Fast Interrupt Notification APIs

lib/libc/zoneinfo/Makefile
LIBC_DELETE_ZONEINFO_RULES was renamed to LIBC_OPTIMIZE_ZONEINFO_RULES with commit b2cb34d.
This commit applies that change in Makefile of libc/zoneinfo.
=> libc/zoneinfo : Apply the config renamed to LIBC_OPTIMIZE_ZONEINFO_RULES 

os/drivers/video/Kconfig, os/drivers/video/Make.defs, os/drivers/video/video.c, os/drivers/video/video_null_driver.c, os/include/video/video_halif.h
- Error handling for change video state, set buffer and type
and transfer failure cases.
- Merged function set_buf and set_buftype as single function.
=> drivers/video: Add proper error handling in failures

os/include/sys/syscall.h
- Remove a dependency of prctl, 'CONFIG_TASK_NAME_SIZE' because prctl has many other functionalities.
- SYS_maxsyscall should be greater than used numbers for syscall.
=> syscall: Fix definition of syscall numbers

os/arch/arm/Kconfig, os/arch/arm/src/amebad/Kconfig
1. arch/arm/Kconfig : There is no Kconfig in os/board/rtl8721csm/src/component/soc/realtek/amebad/cmsis,
so remove sourcing from arch/arm/Kconfig
2. fix "depends" to "depends on"
=> arch/arm/amebad : Fix invalid Kconfig grammar and source

os/fs/vfs/fs_poll.c, os/include/tinyara/net/net.h, os/net/netmgr/net_vfs.c, os/net/netmgr/netstack_lwip.c, os/net/socket/Make.defs, os/net/socket/net_poll.c
poll() called lwip_poll directly before.
net_poll is added to hide lwip interface from TizenRT VFS.
=> network: add net_poll interface

external/esp_idf_port/esp32/esp32_wifi_os_adapter.c, lib/libc/semaphore/sem_init.c, os/arch/xtensa/src/esp32/esp32_i2c.c
Replace `seamahpore` with `semaphore`
=> Fix typo about semaphore

os/binfmt/libelf/libelf_bind.c, os/binfmt/libelf/libelf_symbols.c
- Instead of using memcpy to fetch relocation and symbol entries
from Symbol and Relocation Tables allocated in RAM, simply use
the addresses of these entries in the tables to access them.
Co-authored-by: Kishore SN <kishore.sn@samsung.com>
=> Optimize ELF loading time

os/tools/configure.sh
When we use the docker through the dbuild script, we don't need to
install some tools to use some functionalities like romfs, iotivity,
and so on. But regardless of using docker, it says need to install
them.
This commit adds the sentence about this.
=> os/tools/configure: Notice no need to install the tools with docker

os/arch/arm/Kconfig
It had the Kconfig syntax error. defaut --> default
Github user @Boooooots raises the issue for this,
https://github.com/Samsung/TizenRT/issues/4243.
=> fixup! arch/arm: make CONFIG_ARM_MPU invisible for user

os/arch/arm/src/tiva/tiva_allocateheap.c, os/board/stm32l4r9ai-disco/src/stm32_spi.c
I added ')' to tiva_allocateheap.c at line 138 and '{' to stm32_spi.c
=> os/arch: fix typo

os/arch/arm/src/armv7-m/up_svcall.c, os/arch/arm/src/armv8-m/up_svcall.c
Unused tcb variable resulting into build failure with CONFIG_ARMV7M_MPU.
Fix build by removing tcb declaration.
=> arch/arm/src/armv7-m, armv8-m: Fix build error with unused variable

os/arch/arm/Kconfig, os/arch/arm/src/armv7-m/mpu.h, os/arch/arm/src/armv7-m/up_blocktask.c, os/arch/arm/src/armv7-m/up_mpu.c, os/arch/arm/src/armv7-m/up_releasepending.c, os/arch/arm/src/armv7-m/up_reprioritizertr.c, os/arch/arm/src/armv7-m/up_svcall.c, os/arch/arm/src/armv7-m/up_unblocktask.c, os/arch/arm/src/armv8-m/mpu.h, os/arch/arm/src/armv8-m/up_blocktask.c, os/arch/arm/src/armv8-m/up_mpu.c, os/arch/arm/src/armv8-m/up_releasepending.c, os/arch/arm/src/armv8-m/up_reprioritizertr.c, os/arch/arm/src/armv8-m/up_svcall.c, os/arch/arm/src/armv8-m/up_unblocktask.c, os/arch/arm/src/common/up_createstack.c, os/binfmt/binfmt_execmodule.c, os/include/tinyara/mpu.h, os/include/tinyara/sched.h, os/tools/mkconfig.c
Implement task's stack overflow protection with MPU support.
Stack guard memory(min of 32 bytes) will be reserved at the end of
each task's stack memory. The Stack guard memory will be marked as RO,
so that stack access above the permissible limit will result into
memory fault with MPU.
=> Support MPU Stack Overflow Protection

os/drivers/video/Kconfig
- Include supported options list in menuconfig
for NULL driver.
- Options are only for display help, not for
final selection.
- Options supported by the actual camera
hardware may vary.
=> os/drivers/video: Add NULL Driver help for supported options

tools/nxfuse/mksmartfsimg.sh
Remove unwanted modproble command from tools/nxfuse/mksmartfsimg.sh.
=> tools/nxfuse: Remove unwanted modprobe command

framework/src/st_things/things_stack/framework/things_data_manager.c, framework/src/st_things/things_stack/framework/things_req_handler.c, lib/libc/misc/lib_hashmap.c, os/arch/arm/src/armv7-m/up_assert.c, os/arch/arm/src/armv7-m/up_mpu.c, os/arch/arm/src/armv8-m/up_assert.c, os/arch/arm/src/armv8-m/up_mpu.c, os/binfmt/binfmt_exec.c, os/binfmt/binfmt_execmodule.c, os/binfmt/binfmt_loadbinary.c, os/binfmt/libelf/libelf.h, os/binfmt/libelf/libelf_addrenv.c, os/binfmt/libelf/libelf_bind.c, os/binfmt/libelf/libelf_load.c, os/binfmt/libelf/libelf_symbols.c, os/include/debug.h, os/include/hashmap.h, os/include/tinyara/hashmap.h, os/include/tinyara/mpu.h, tools/nxfuse/src/nxfuse.h, tools/nxfuse/src/tinyara_services.c
1. include/debug.h: fix typo in media debug definition 
2. tools/nxfuse: fix build warnings
3. binfmt: fix build warnings
4. arch/arm: fix build warnings
5. include/mpu.h: add the prototype of mpu_get_register_value …
6. arch/mpu: remove unnecessary conditionals of mpu_get_register_value …
7. arch/armv7-m/up_mpu.c: fix violations of coding rules
8. hashmap: fix violations of coding rules
9. hashmap: move the location of header into os/include/tinyara
=> fix build warnings

tools/fs/contents-smartfs/.gitignore
The tools/fs/contents-smartfs folder could include some files
but they are not contents for remote repository.
This commit adds .gitignore to blind the change of this folder for git.
Untracked files:
(use "git add <file>..." to include in what will be committed)
/tools/fs/contents-smartfs/
=> tools/fs/contents-smartfs: add .gitignore to blind the change

os/drivers/video/Kconfig
There are syntax errors on Kconfig of video.
This commit fixes errors as shown below:
drivers/video/Kconfig:73:warning: leading whitespace ignored
drivers/video/Kconfig:44:warning: defaults for choice values not supported
drivers/video/Kconfig:49:warning: defaults for choice values not supported
drivers/video/Kconfig:58:warning: defaults for choice values not supported
drivers/video/Kconfig:62:warning: defaults for choice values not supported
drivers/video/Kconfig:66:warning: defaults for choice values not supported
drivers/video/Kconfig:70:warning: defaults for choice values not supported
drivers/video/Kconfig:77:warning: defaults for choice values not supported
drivers/video/Kconfig:81:warning: defaults for choice values not supported
drivers/video/Kconfig:85:warning: defaults for …
=> drivers/video: fix errors on menuconfig

docs/LoadableAppsConfigurationUserGuide.md
Xalloc is not easy to understand, so add/expand the description related to memory allocation APIs.
=> docs/loadable : Add detailed API list for user and kernel side usage

apps/examples/timer/timer_main.c, os/arch/arm/src/imxrt/imxrt_timer_lowerhalf.c, os/include/tinyara/timer.h
1. define the Timer mode as ALARAM and FRT(free run timer)
2. change SETFREERUN to SETMODE
: The definition is different for each hal part,
so it can be used for common use
3. add SETTIMEUNIT ioctl
: this option to operate depending on whether the users
sets the time unit to ms or us.
=> timer: change and add ioctl commands, TCIOC_SETMODE, TCIOC_SETRESOLUTION

os/binfmt/binfmt_loadbinary.c
Place a pointer to the app's heap object into the heap table.
=> binfmt: fix wrong type casting

os/arch/arm/src/armv7-m/up_assert.c, os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_load.c, os/kernel/binary_manager/binary_manager_recovery.c
No needs to do something if fault thread is NRT thread.
That is because binary manager deactivates it before it is unblocked.
So fault handler deactivates it if faulty thread is RT thread only.
=> kernel/binary_manager: Deactivate faulty thread if it is RT thread

.travis.yml
There is no protection branch anymore, and there is fs_journal branch now.
Let's do travis-ci for fs_journal branch.
=> travis: modify the branch name, protection -> fs_journal

os/binfmt/libelf/libelf.h, os/binfmt/libelf/libelf_sections.c
If CONFIG_OPTIMIZE_RELOAD_TIME is enabled, elf will be loaded with one block. So there is no each section's place.
=> binfmt/libelf : Add #ifdef for OPTIMIZE_RELOAD_TIME in libelf_section.c

loadable_apps/loadable.mk
The loadable.mk is an util script to build loadable user binary so that
it should be called from each binary.
Each binary should include Make.defs of TOPDIR and should define each
CFLAGS in each Makefile.
With above, loadable.mk should not include Make.defs of TOPDIR.
This commit makes each Makefile take own CFLAGS.
=> loadable_apps: remove including Make.defs of TOPDIR from loadable.mk

apps/examples/testcase/le_tc/filesystem/fs_main.c
CONFIG_NFILE_DESCRIPTOS is not always invalid fd.
A fd value can be 0 to (CONFIG_NFILE_DESCRIPTORS + CONFIG_NSOCKET_DESCRIPTORS) when network is enabled.
So define negative value for invalid fd test.
=> testcase/filesystem: Use negative value for invalid fd test

os/board/common/userspace/up_userspace.c
Some userspace object values like textstart, etc., are missing due to
wrong placement of preprocessor directive.
=> os/board/common/userspace: Fix issue of missing USERSPACE values

apps/examples/security_test/security_api/Makefile, apps/examples/security_test/security_api/security_api_crypto_test.c, apps/examples/security_test/security_api/security_api_ss_test.c, apps/examples/security_test/security_api/security_api_test.c, external/mbedtls/alt/ecdh_alt.c, external/mbedtls/alt/pk_wrap_alt.c, os/drivers/seclink/seclink_drv.c, os/drivers/seclink/seclink_drv_key.c, os/drivers/seclink/seclink_drv_utils.h, os/include/tinyara/seclink_drv.h, os/se/sss/security_hal_wrapper.c
Add key allocation logic in mbedTLS alternative layer. if the key slot
is used and there are available slots then mbedTLS will allocate next
slot.
=> external/mbedtls: Add key allocation logic in mbedTLS alt layer

docs/ProtectedBuildGuide.md
There are APIs which can be used on Protected build.
This commit adds the tab in the documentation of protected build guide
to say the API lists.
=> docs/ProtectedBuildGuide: add the Available APIs tab

os/binfmt/binfmt_execmodule.c, os/binfmt/binfmt_exit.c
A node of app heap is created and added to a list of app heap when loading binary.
This node should be removed from the list and freed when unloading binary.
=> binfmt: Free app heap node when unloading binary

os/binfmt/libelf/libelf_bind.c, os/mm/kmm_heap/kmm_free.c
The memory should be freed when it is allocated.
=> binfmt/libelf: Free memory if it is allocated memory

os/binfmt/elf.c, os/binfmt/libelf/Kconfig, os/binfmt/libelf/libelf_bind.c, os/binfmt/libelf/libelf_init.c, os/include/debug.h
Add missing debug macros for CONFIG_ELF_DUMPBUFFER
=> os/binfmt: Add missing macros for elf_dumpbuffer

tools/nxfuse/src/tinyara_services.c
The vdbg function is matched with CONFIG_DEBUG_VERBOSE, not
CONFIG_DEBUG.
This commit fixs above and resolves build break as below:
In file included from src/tinyara_services.c:68:0:
include/debug.h:1052:21: error: expected identifier or '(' before 'void'
#define vdbg       (void)
^
src/tinyara_services.c:294:5: note: in expansion of macro 'vdbg'
int vdbg(const char *fmt, ...)
^
make[3]: *** [obj/tinyara_services.o] Error 1
=> tools/nxfuse: fix wrong conditional of vdbg

build/configs/artik053/README.md, build/configs/artik053s/README.md, build/configs/artik055s/README.md, build/configs/imxrt1020-evk/README.md, build/configs/imxrt1020-evk/imxrt1020-evk_download.sh, build/configs/imxrt1050-evk/README.md, build/configs/imxrt1050-evk/imxrt1050-evk_download.sh
Adding the USB rule file is not related with image programming
in the flash so that it does not need to check others like
partition table, serial port and so on.
This commit moves the location of checking that command at
very first.
=> configs/imxrt10x0-evk: check adding USB rule command at start

os/fs/smartfs/Kconfig
- 'endmenu' statement mistakenly removed earlier
causes make menuconfig to fail.
- Re-add statement.
=> os/fs/smartfs: Add missing 'endmenu' in Kconfig

os/fs/smartfs/smartfs_utils.c
1. If crc is enabled, it doesn't write data on flash after allocation
2. But smartfs_createentry try to read from flash, so crc value is 0xffff
3. Because of unmatched crc, it returns error all the time
4. So after alloc sector, do not read it anymore.
5. This will be cleaned when new journal added.
=> os/fs/smartfs : Fix error when create entry

apps/examples/timer/timer_main.c, docs/HowToUseTimer.md, os/drivers/timer.c, os/include/tinyara/timer.h
For notifying the timer interrupt, FIN(Fast Interrupt Notification) can be used, even it is faster than Signal.
=> drivers/timer : Modify timer interrupt notification method

os/arch/arm/src/common/up_exit.c, os/kernel/mqueue/mq_receive.c, os/kernel/mqueue/mq_send.c, os/kernel/mqueue/mq_timedreceive.c, os/kernel/semaphore/sem_timedwait.c, os/kernel/signal/sig_timedwait.c
mqueue : only protect with sched_lock about accessing and modifying the mqdes
semaphore : don't need to protect time calculation before start the watchdog
signal : remove not-necessary sched_lock
=> kernel : Optimize non-preemption-lock range

os/arch/arm/include/arch.h, os/arch/arm/src/armv8-m/up_blocktask.c, os/arch/arm/src/armv8-m/up_releasepending.c, os/arch/arm/src/armv8-m/up_reprioritizertr.c, os/arch/arm/src/armv8-m/up_schedulesigaction.c, os/arch/arm/src/armv8-m/up_svcall.c, os/arch/arm/src/armv8-m/up_unblocktask.c, os/arch/arm/src/common/up_schedyield.c, os/include/tinyara/tz_context.h
This patch adds secure context handling when non-secure context switches without involving SVC
i.e when context switch/restore is done via up_savestate/up_restorestate
Signed-off-by: Nitish Ambastha <nitish.a@samsung.com>
=> Handle secure context switch whenever context switches without SVC

lib/libc/netdb/Make.defs, lib/libc/netdb/lib_getifaddr.c, os/include/ifaddrs.h, os/include/netdb.h, os/include/tinyara/net/ioctl.h, os/net/netdev/Make.defs, os/net/netdev/netdev_ifname.c, os/net/netdev/netdev_ioctl.c, os/net/netmgr/net_vfs.c, os/net/netmgr/netdev_mgr_internal.c, os/net/netmgr/netmgr_ioctl_lwip.c, os/net/netmgr/netmgr_ioctl_netdev.c
getifaddrs is tempolary implementation to run Iotivity. it doesn't run
on TizenRT 3.0 loadable environment because it accesses to
g_netdevices which is defined in kernel layer to get a running NIC
name. So this commit adds new ioctl command(SIOCGIFNAME) to access interface name
from app layer. however this operation is not same to linux. so you'd
better to use it carefully.
=> network/library: fix getifaddrs for Iotivity

os/kernel/semaphore/sem_timedwait.c
In PR#4333, irqsave is moved from line 225 to line 270.
Between line 225 and line 270, there is irqrestore for error case. But we don't need this anymore.
=> kernel/semaphore : Remove unnecessary irqrestore

os/binfmt/binfmt_execmodule.c, os/binfmt/binfmt_loadbinary.c, os/kernel/debug/Make.defs, os/kernel/debug/memdbg.c, os/kernel/debug/memdbg.h, os/kernel/init/os_start.c
This patch adds the following logs:
1) ram address /size
2) idle stack address / size
3) each section address / size per binary
4) heap address / size per binary
=> Update boot logs to get RAM configuration for debug purpose

os/kernel/binary_manager/binary_manager_load.c, os/kernel/semaphore/sem_holder.c, os/kernel/semaphore/sem_post.c, os/kernel/semaphore/semaphore.h
If a task which occupied the kernel sem in fault binary, we should remove the sem holder from holder list.
So before calling the releaseholder, set the holder counts as 1.
And after releasing the kernel sem, there can be a task which waits that sem.
So call the sem_post instead of just calling sem_releaseholder.
=> kernel/binary_manager_load : Modify sem restore logic for fault case

os/arch/arm/src/amebad/Kconfig
CONFIG_AMEBAD_RDP_KEY has prompt definition with hex type
so that separated prompt definition is unnecessary.
This commit fixes the mennuconfig warning as shown below:
arch/arm/src/amebad/Kconfig:83:warning: prompt redefined
=> arch/amebad: remove duplicated definition of type in Kconfig

apps/examples/testcase/le_tc/kernel/tc_libc_stdio.c
The length modifier of sscanf was added with commit 356610d.
This commit adds checking the length modifier, ll, l, hh and h with
several types of buffers to confirm.
=> examples/testcase: add the test case of length modifier on sscanf tc

os/kernel/binary_manager/binary_manager_load.c
It is good to show always about binary loading failure log.
So change bmdbg to lldbg.
=> kernel/binary_manager : Change binary load-failure log to lldbg

os/arch/arm/src/amebad/Make.defs, os/arch/arm/src/amebad/amebad_timer_lowerhalf.c, os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/timer_api.c, os/board/rtl8721csm/src/rtl8721csm_boot.c
1) The timer peripheral is now supported.
2) It is tested by the timer example (timer_main.c).
3) Currently, the 'getstatus' and 'ioctl' functions are not supported.
=> [Realtek][RTL8721CSM]Add General Purpose Timer Peripheral

os/fs/driver/mtd/smart.c
When wrtie 1 sector & erase by file operation, fs uses only 1sector
But journal need 3 journal data.
=> os/fs/smartfs : Adjust formula to calculate number of journal block

os/arch/arm/include/arch.h, os/arch/arm/src/amebad/Make.defs, os/arch/arm/src/armv7-m/up_schedyield.c, os/arch/arm/src/armv7-r/arm_schedyield.c, os/arch/arm/src/armv8-m/up_schedyield.c, os/arch/arm/src/imxrt/Make.defs, os/arch/arm/src/s5j/Make.defs, os/arch/arm/src/stm32l4/Make.defs, os/arch/arm/src/tiva/Make.defs, os/include/tinyara/arch.h, os/include/tinyara/tz_context.h, os/kernel/sched/sched_yield.c
1. arch/arm: move up_schedyield to each architecture
2. arch/arm: add missing codes in schedyield.c 
3. kernel/sched: optimize sched_yield with CONFIG_SCHED_YIELD_OPTIMIZATION 
4. arch/arm, kernel/sched: move yield functionality into arch for optimization
=> tidyup of sched_yield

apps/examples/testcase/le_tc/drivers/tc_watchdog.c
remove that tc, because
In some drivers, -1 may or may not be used.
=> tc/tc_watchdog: remove unncessary tc

os/arch/arm/src/amebad/Make.defs, os/arch/arm/src/amebad/amebad_watchdog_lowerhalf.c, os/board/rtl8721csm/src/rtl8721csm_boot.c
1. The watchdog peripheral is now supported.
2. It is tested by the watchdog testcase (tc_watchdog.c).
3. Systimer is used to get timeleft.
4. Both reset mode and interrupt mode are supported.
5. Both WDIOC_PAUSE and WDIOC_RESUME ioctl commands are supported.
6. Fixed the logic of changing timeout mode when watchdog is paused.
7. Fixed the timeout and timeleft calculation issue after watchdog is resumed.
=> [Realtek][RTL8721CSM]Add Watchdog Timer Peripheral

os/arch/arm/src/stm32l4/stm32l4_flash.c, os/arch/xtensa/src/esp32/spi_flash/include/esp_partition.h, os/arch/xtensa/src/esp32/spi_flash/partition.c, os/board/esp32_devkit/src/esp32_boot.c, os/board/stm32l4r9ai-disco/include/stm32l4r9i_discovery.h, os/board/stm32l4r9ai-disco/src/stm32_boot.c, os/net/netmgr/netdev_mgr_internal.c, os/pm/pm_initialize.c
All kernel semaphores are registered to a list of kernel semaphores, g_sem_list for fault recovery.
So they should call sem_register by calling sem_init instead of SEM_INITIALIZER.
=> kernel/semaphore: Initialize semaphore with sem_init instead of SEM_INITIALIZER

os/arch/xtensa/src/esp32/esp32_spi.c
Fix build warning.
chip/esp32_spi.c: In function 'up_spiinitialize':
chip/esp32_spi.c:1590:12: warning: passing argument 1 of 'sem_init' discards 'volatile' qualifier from pointer target type [-Wdiscarded-qualifiers]
sem_init(&g_spi_dma.dma_lock, 0, 1);
^
In file included from /root/tizenrt/os/include/sys/types.h:66:0,
from /root/tizenrt/os/include/stdio.h:76,
from chip/esp32_spi.c:24:
/root/tizenrt/os/include/semaphore.h:198:5: note: expected 'sem_t * {aka struct sem_s *}' but argument is of type 'volatile sem_t * {aka volatile struct sem_s *}'
int sem_init(FAR sem_t *sem, int pshared, unsigned int value);
=> arch/esp32: Type casting to sem_t * when passing an argument to sem_init

os/fs/smartfs/smartfs_smart.c, os/fs/smartfs/smartfs_utils.c
When currennt entry sector is full, smartfs alloc new entry sector and chaining with
current sector. In this time there's no chain header in new entry sector, so error happened
when some of file operation called(c.f rmdir)
=> os/fs/smartfs : [BugFix] Add chainheader to new entry sector

os/fs/driver/mtd/smart.c
After recover journal, some of date(c.f freecount) is not updated,
so next GC will be happned during write data
=> os/fs/smartfs : Do not GC after recover journal

os/drivers/wireless/scsc/netif.c, os/drivers/wireless/scsc/slsi_drv_netmgr.c, os/include/tinyara/netmgr/netdev_mgr.h, os/net/netmgr/Kconfig, os/net/netmgr/netdev_lwip.c, os/net/netmgr/netdev_mgr.c, os/net/netmgr/netdev_mgr_internal.h
To increase the performance, zerocopy feature is implemented.
it'll pass pbuf from lwIP to wi-Fi driver while it's sending data. so
the number of memory copy is reduced. On the contrary, the network manager
pass pbuf to lwIP directly when it receive data from Wi-Fi
driver. this feature is dependent to Wi-Fi driver. So it have to be
handled carefully
=> network: Add zerocopy feature in Network Manager.

os/kernel/binary_manager/binary_manager.h, os/kernel/binary_manager/binary_manager_binfile.c, os/kernel/binary_manager/binary_manager_load.c
Binary manager validates header values of binary file without checking crc when system boot.
That's because it takes a long time to read whole file for checking crc value.
And then it validates header values and crc value when loading binary.
=> kernel/binary_manager: Skip crc checking of binary files when system booting

os/kernel/binary_manager/binary_manager_load.c, os/kernel/semaphore/sem_holder.c, os/kernel/semaphore/sem_post.c, os/kernel/semaphore/sem_setprotocol.c, os/kernel/semaphore/semaphore.h
All semphoare holders should be freed by binary_manager_release_binary_sem.
If priority inheritance is disabled, a holder is freed directly.
If not, it is freed after restoring priorities of threads holding semaphore in sem_restorebaseprio.
=> kernel/binary_manager: Free a semaphore holder directly when priority inheritance is disabled

os/fs/driver/mtd/smart.c, os/fs/smartfs/smartfs.h, os/fs/smartfs/smartfs_smart.c, os/fs/smartfs/smartfs_utils.c
- Separate functions to find available entries,
create new entries and write new entries.
- Handle renaming of files at the same location
separately for optimization.
- Pre-allocation of firstsector for new file/dir
entries.
- Separate function to invalidate old entry
wherever required.
=> os/fs/smartfs: Refactoring of code for Smartfs file operations

os/fs/smartfs/smartfs_smart.c
st_blksize represents blocksize of FileSystem I/O.
So user can use it size of buffer to use entire of sector.
But it include size of chainheader in sector, so reduce size of chainheader
=> os/fs/smartfs : Adjust stat's st_blksize

os/fs/smartfs/smartfs_utils.c
If fs->entry_seq is same as timestamp, it doesn't increase number, so fix it
=> os/fs/smartfs : [BugFix] fs->entry_seq does not incease

os/fs/smartfs/smartfs_utils.c
- Exit the loop for counting entries when count>1.
- If count>1, we know that sector can't be released.
=> os/fs/smartfs: Optimize number of loop iterations in smartfs_deleteentry()

os/drivers/usbdev/cdcacm.c, os/drivers/usbhost/usbhost_cdcacm.c
both of host and dev of cdcacm use priv structure in ioctl.
Fix to use priv properly
=> os/driver/usb Fix ioctl of cdcacm

os/fs/smartfs/smartfs.h, os/fs/smartfs/smartfs_smart.c, os/fs/smartfs/smartfs_utils.c
- smartfs_find_availableentry returns the final entry
for writing to, not just an available entry.
- smartfs_createentry will be called internally from
find_availableentry wihtout passing control back to
upper fs layer API.
- Basically now, find_availableentry first looks for an
availableentry and otherwise allocates space for a
new one via createentry.
=> os/fs/smartfs: Modify flow for assigning new file/dir entry

os/board/esp32_devkit/src/spiram.c, os/board/esp32_devkit/src/spiram_psram.c
1. use #if defined instead of #if because it checks definition, not value
CC:  spiram_psram.c
spiram_psram.c: In function 'psram_enable':
spiram_psram.c:625:5: warning: "CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V" is not defined [-Wundef]
#if CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V
^
CC:  spiram.c
spiram.c:63:5: warning: "CONFIG_SPIRAM_SPEED_40M" is not defined [-Wundef]
#if CONFIG_SPIRAM_SPEED_40M && CONFIG_ESPTOOLPY_FLASHFREQ_40M
^
spiram.c:65:7: warning: "CONFIG_SPIRAM_SPEED_40M" is not defined [-Wundef]
#elif CONFIG_SPIRAM_SPEED_40M && CONFIG_ESPTOOLPY_FLASHFREQ_80M
^
2. use kregionx_size instead of regionx_size because it was renamed previous commit
spiram.c: In function 'esp_spiram_test':
spiram.c:75:28: error: 'regionx_size' undeclared (first use in this function)
#define CONFIG_SPIRAM_SIZE …
=> board/esp32_devkit: fix build errors and warnings

os/fs/smartfs/smartfs.h, os/fs/smartfs/smartfs_smart.c, os/fs/smartfs/smartfs_utils.c
- write entry to new sector first, then write chainheader->nestsector
for old parent sector.
- If a power off occurs before the last step, smartfs recovery will
handle the new isolated sector.
- remove unnecessary sector read from smartfs_createentry().
=> os/fs/smartfs: Write nextsector to parent after writing new entry

os/fs/smartfs/smartfs_utils.c
If next entry or sector is not exist, it clean entry but it doesn't increase count
=> os/fs/smartfs : Modify number of cleaned entry properly

os/fs/driver/mtd/smart.c, tools/nxfuse/Makefile, tools/nxfuse/mknxfuse.sh, tools/nxfuse/mksmartfsimg.sh, tools/nxfuse/src/filemtd.c
New journaling initialized before smart_scan, so if write journal data failed, fusing also failed
1. Fix unnecessary reset of journal state when checkout
2. Set 0xFF when fuse make image
3. Improve logic of filemtd_write
=> fs/smartfs/nxfuse : Fix error nxfuse with new journaling

os/binfmt/binfmt_loadbinary.c, os/binfmt/libelf/libelf_sections.c
RO section should be from ALLOC_RO, not from ALLOC_DATA.
There are two wrong settings, so fix them.
=> os/binfmt : Fix wrong RO section address

os/fs/driver/mtd/smart.c
It is not error case but uses fdbg, change it to fvdbg
=> fs/smartfs : Change debug level regarding allocblock

os/arch/arm/Kconfig
ARCH_HAVE_MPU should be selected because amebad hw supports the mpu.
But ARMV8M_MPU is an optional config which can be enabled if needed.
=> os/arch/arm/Kconfig : Remove unnecessary MPU select option

os/include/tinyara/wqueue.h
The priority of hpwork-queue should be less than binary manager.
So it was decreased to 201, but the description was not.
Fix the description.
=> os/include/tinyara/wqueue.h : Modify hpwork default priority description

os/include/semaphore.h, os/kernel/semaphore/Make.defs
Semaphore holders should be saved to be released when binary recovery or binary update.
=> kernel/semaphore : Save semaphore holders when binary manager is enabled

apps/system/utils/utils_proc.h
We don't need to enclose with ENABLE_PROC_UTILS for using proc utils.
Even it is not good to add every configs.
So remove unnecessary condition.
=> apps/system/utils/utils_proc.h : Remove unnecessary #ifdef condition for proc utils

apps/examples/testcase/le_tc/filesystem/fs_main.c, os/fs/smartfs/smartfs_smart.c
1. If user open with flag O_TRUNCATE but do not close, then it never update flash
if sector buffer is enabled.
2. If O_TRUNCATE is set when open, do not read whole of sector because it already
read by smartfs_truncatefile
=> os/fs/smartfs : Fix truncate issues

os/fs/smartfs/smartfs_utils.c
If error happened during scan entries, it free all remained sector.
Modify code to avoid this behavior
=> fs/smartfs : Fix sector recovery logic

loadable_apps/loadable_sample/wifiapp/recovery.c
Unused variable makes build warning. So remove it.
=> loadable_sample/wifiapp : Remove unused variable

os/mm/mm_heap/mm_getheap.c
mm_get_app_heap_node returns app_heap structure, but its return type was mm_heap_s.
For avoiding build error, change the return type to app_heap_s.
=> mm/mm_heap/mm_getheap : Modify return type of mm_get_app_heap_node

os/binfmt/libelf/libelf_addrenv.c, os/drivers/testcase/testcase_drv.c, os/kernel/binary_manager/binary_manager_binfile.c
Fix build warnings because of wrong type definition or type casting.
=> os: Fix build warnings

os/fs/smartfs/smartfs.h, os/fs/smartfs/smartfs_smart.c, os/fs/smartfs/smartfs_utils.c
- When CRC is enabled
- Sync file data with MTD first.
- Then write the new file entry ot MTD.
- If the entry was written to a new sector on the parent directory,
Chain the new sector to the parent directory now.
=> os/fs/smartfs: Modify sequence for writing new file entry/data with CRC enabled

os/fs/smartfs/smartfs.h, os/fs/smartfs/smartfs_smart.c, os/fs/smartfs/smartfs_utils.c
- Can work smartfs_finddirentry() without extra filename parameter.
- fix:smartfs_finddirentry returns filename NULL.
- Allocate entry name space minimum times.
- Use kmm_zalloc instead of kmm_malloc + memset(0).
=> os/fs/smartfs: Optimize parameters for finddirentry()

os/arch/arm/src/s5j/Kconfig, os/board/Kconfig, os/board/common/Kconfig, os/board/imxrt1020-evk/Kconfig, os/board/imxrt1050-evk/Kconfig
1. remove the prompt to hide from user
They show the board has the flash, they are not the way to enable flash.
CONFIG_FLASH_PARTITION and CONFIG_SECOND_FLASH_PARTITION are for that.
So, user should not control them.
2. make a dependency with board config, not with chip config
Ususally flash has a dependency with board, not with chip.
Let's move the selection them under board config in Kconfig.
3. rename it to CONFIG_ARCH_BOARD_HAVE_FLASH
By 2nd modification, it had better have BOARD prefix.
And by 1st, it had better have HAVE prefix instead of USE.
=> os/board: tidyup CONFIG_ARCH_USE_FLASH, CONFIG_ARCH_USE_SECOND_FLASH

apps/system/utils/fscmd.c
If user type just 'echo' memfault happened because args[1] is null so fix it.
=> fs/fscmd : Fix memfault of echo

framework/src/tinyalsa/tinyalsa.c
'frames' can not be 0 in pcm_mmap_transfer, so remove break condition
=> audio/tinyalsa : Remove unrechable code

apps/system/utils/fscmd.c
If there are more than one same fs type of mountpoint, df show only first one.
=> fs/fscmd : Fix df doesn't show 2nd mount point of file system

apps/system/utils/fscmd.c
Check buffer size when memcpy to fscmd_buffer
=> fs/fscmd : Prevent overflow of fscmd_buffer

apps/examples/mpu/mpu_test.c, apps/system/utils/fscmd.c, apps/system/utils/utils_ps.c, loadable_apps/loadable_sample/wifiapp/recovery.c
1. apps/system/utils: fix typo in utils_ps.c 
2. apps/system/utils/fscmd: tidyup tash_cat
1. remove duplicated fscmd_free for src/dest_fullpath at end of function
2. In redirection case, written size could be less than requested size.
add while loop to write entire read data to destination
=> apps/system/utils: tidyup

apps/examples/testcase/le_tc/filesystem/fs_main.c
In fact, file will be synced when close called.
It uses file without close, so fix it
=> fs/utc : Fix utc uses open-close wrongly

os/include/debug.h
can't find dbg_noarg when nxfusing, because config is different
=> debug/fs : fix build error when nxfusing run

os/include/tinyara/seclink_drv.h
This patch resolves build break for rtl8721csm/security_hal_test configuration.
=> include/tinyara: Resolve build break for rtl8721csm/security_hal_test config

apps/system/utils/fscmd.c
some logic is missed, so there was infinite write in redirection case
=> tash/cat : Prevent infinite write

os/board/common/crashdump.c, tools/ramdump/ramdump_tool.c
This PR removes the user space memory dependencies of ramdump
tool(CONFIG_RAM_REGIONx_xx) since protected build feature has
been removed TizenRT. Instead of supporting kernel & user heap dumps,
this tool now simply supports memory dump, the memory cofnigurations
for which are extracted using the following configs:
CONFIG_RAM_KREGIONx_xx
=> Update ramdump as per latest TizenRT code

build/configs/rtl8721csm/rtl8721csm_download.sh
TizenRT provide the docker build by default, and docker runs all commands with sudo permission by default.
So we don't need to run the command with sudo permission.
=> build/configs/rtl8721csm: Remove sudo for running commands

docs/HowToPortTizenRTOnWiFiChipset.md
typos:
an driver -> a driver
BRAODCAST -> BROADCAST
EHTERNET -> ETHERNET
netev -> netdev
nconfie -> nconfig
PRPPIETARY -> PROPRIETARY
DRVER -> DRV
CSCRS -> CSRCS
links:
light-weight-netlink-802-11-driver -> light-weight-netlink-80211-driver
network-manager-configuration -> 2-network-manager-configuration
../framework/include/wifi_manager/ -> ../framework/include/wifi_manager/wifi_manager.h
wifi_utils_lwnl80211.c -> wifi_manager_lwnl.c
=> docs/HowToPortTizenRTOnWiFiChipset: fix typos and wrong links

build/configs/rtl8721csm/rtl8721csm_download.sh, build/tools/amebad/image_tool/.gitignore
This patch resolves smartfs download issue using make download smartfs
for realtek hello & tc configurations.
=> build/configs/rtl8721csm: Modify smartfs binary download conditional

os/fs/smartfs/smartfs_smart.c
- Pass buffer with 0 offset to smartfs_append_data().
- 'byteswritten' parameter takes care of offset internally.
=> os/fs/smartfs: Fix improper start address of buffer passed to append_data

os/arch/arm/src/armv7-m/up_mpu.c, os/binfmt/binfmt_execmodule.c, os/binfmt/binfmt_loadbinary.c, os/binfmt/elf.c, os/include/tinyara/binfmt/binfmt.h
Commit 1:
When reload optimization is disabled, a single chunk of memory is
allocated for holding all elf sections in RAM. In this case, the
alloc[] array in binary_s structure will contain a single entry for
the whole binary and any access to bin->alloc[DATA] will be invalid.
So, we change all such access to bin->datastart which will hold the
start address of data section.
Commit 2:
arch/armv7-m: Set MPU permission to RO-RO for read only region
Armv7m allows setting of different permissions for previleged and
user modes. So, previously we were setting RW(P)-RO(U) permission for
read only region. But armv8-m does not allow setting different permissions
based on the mode. So, we are forced to set RO-RO permission for all
read only regions. This commit changes the permission for armv7m read …
=> os/binfmt: Fix crash issue when reload optimization is disabled

os/mm/kmm_heap/kmm_sem.c, os/mm/mm_heap/mm_sem.c, os/mm/umm_heap/umm_sem.c
In mm APIs, heap pointer can be dereferencing sometimes.
To avoid dereferencing, add null checking.
=> mm/mm_sem : Add NULL check of heap for avoiding dereferencing

os/arch/arm/src/armv7-m/up_mpu.c, os/arch/arm/src/armv8-m/up_mpu.c, os/arch/arm/src/common/up_releasestack.c, os/include/tinyara/mpu.h
- **up_mpu_disable_region(..)** is provided in up_mpu.c files for **armv7-m/armv8-m**
- A tcb's mpu registers for a mpu region can be passed to disable the region's ENABLE bit in these registers.
- This feature is needed to fix crash during binary recovery when kernel is freeing stack resources for a stopped task. It is required (for armv8-m) to disable MPU region for stack protection so that kernel has full access to these resources before freeing them.
- While for armv7-m mpu, it is possible to give privileged code full RW permission for a mpu region while maintaining RO permission for unprivileged code, this is not possible for armv8-m mpu (inherent limitation). So, for armv8-m, if it is required for privileged code to have full RW access to a RO mpu region, we should disable the MPU …
=> os/arch/arm: Provide function for disabling MPU region for armv7-m/armv8-m

os/fs/driver/mtd/smart.c, os/fs/smartfs/smartfs_utils.c
Currently we can request FIBMAP with EMTPY SECTOR(0xFFFF) in this case it is greater than
sMap, so error happened. Max size should be smaller than number of sectors in dev
=> fs/smartfs : Add boundary check logic FIBMAP

os/fs/smartfs/smartfs_utils.c
1. Because of free node in queue logic, index of queue has changed, so some of node
skipped from checking. It will free at the last time of recovery.
2. If any of entry already checked, it's chained sectors should be skipped next time
=> fs/smartfs : Fix recovery if power failed before write new path's entry

os/fs/smartfs/smartfs_utils.c
CRC Enabled - Currently, chainheader type is written as SMARTFS_DIRENT_TYPE_FILE
It should be SMARTFS_SECTOR_TYPE_FILE instead.
CRC Disabled - Chainheader type not written to MTD, write it along with data for new sectors.
=> os/fs/smartfs: Fix improper type value for subsequent file sectors

os/binfmt/binfmt_execmodule.c, os/binfmt/binfmt_exit.c, os/include/tinyara/mm/mm.h, os/kernel/init/os_start.c, os/mm/mm_heap/mm_getheap.c
We maintain a list of app heap objects in app_heap_list. When an
application is loaded for the first time, a new node is created and
added to this list. However, since the is_active variable in the node
is not set, it leads to a failure when searching the app_heap_list
for a heap corresponding to an address. In such case, the mm_free
operation fails to free the address, resulting in memory leak. The
issue is fixed by setting is_active to true when the app heap is being
added to the list.
=> os/mm: Fix memory leak issue due to mm_get_heap

os/fs/smartfs/smartfs_utils.c
- Fix improper used bytes in header so that retrieved file size is correct.
=> os/fs/smartfs: Fix - Incorrect file size after shrinkfile()
