apps/examples/kernel_sample/cancel.c
Extend the pthread cancellation test in kernel_sample cancel.c referenced by NuttX 7.18(committed 8586535)
=> Update the cancel.c in kernel_sample

os/include/pthread.h, os/kernel/pthread/pthread_condtimedwait.c, os/kernel/pthread/pthread_condwait.c, os/kernel/pthread/pthread_mutexdestroy.c
Update Nuttx commit d16053c33cdf3f570d347b29f809cd69a6d916c0
=> sched/pthread: Use -1 instead of 0 as PID for unclaimed mutexes

os/kernel/Kconfig
latency and debug are not supported so that configurations are needed.
=> remove unsupported configuration

os/include/sys/types.h
It is at line 298 and 322 and it should be in __ASSEMBLY__.
=> remove duplicated type definition for uint

os/include/debug.h
Fix build warning regarding define syntax in debug.h
=> Fix build warning regarding define syntax in debug.h

os/fs/procfs/fs_procfs.c
Some variables are only used when CONFIG_FS_PROCFS_EXCLUDE_PROCESS is disabled.
procfs/fs_procfs.c: In function 'procfs_opendir':
procfs/fs_procfs.c:439:13: error: unused variable 'flags' [-Werror=unused-variable]
irqstate_t flags;
^
procfs/fs_procfs.c: In function 'procfs_readdir':
procfs/fs_procfs.c:590:8: error: unused variable 'pid' [-Werror=unused-variable]
pid_t pid;
^
procfs/fs_procfs.c:589:13: error: unused variable 'flags' [-Werror=unused-variable]
irqstate_t flags;
^
procfs/fs_procfs.c:586:20: error: unused variable 'tcb' [-Werror=unused-variable]
FAR struct tcb_s *tcb;
=> fix build error on procfs

apps/platform/Makefile, os/fs/Makefile, os/logm/Makefile, os/pm/Makefile
If distclean is excuted before configuring,
we can meet errors on pm, fs, logm and apps/platform like belows.
make[1]: Entering directory `/home/sunghan/Work/TinyAra/TizenRT/os/logm'
Makefile:19: /home/sunghan/Work/TinyAra/TizenRT/os/Make.defs: No such file or directory
make[1]: *** No rule to make target `/home/sunghan/Work/TinyAra/TizenRT/os/Make.defs'.  Stop.
=> fix errors on distclean

os/fs/smartfs/smartfs_smart.c
lseek should set the file offset to the size of the file plus offset
=> Fix  lseek's bug in smartfs

os/fs/smartfs/smartfs_smart.c
There are potential memory leakage in rmdir & unlink in smartfs
=> Fix potential memory leakage

os/tools/version.sh
If Tizen RT is tried to build without .git, below error is shown.
We should make Tizen RT can be built regardless of existing of .git.
No .version file found, creating one
GIT version information is not available
chmod: cannot access ‘.version’: No such file or directory
make: *** [/os/.version] Error 1
=> modify version.sh

os/fs/fs_utils.c
if smart_clean failed, inode never released
=> Fix memory leak in fs_clean

apps/examples/hello_tash/Kconfig, apps/examples/hello_tash/hello_tash_main.c, apps/examples/proc_test/Kconfig, apps/examples/proc_test/proc_test_main.c
TASH for hello_tash and DISABLE_MOUNTPOINT, FS_PROCFS for proc_test are needed.
There is no meaningful operation without those configs.
=> modify dependancies of examples, proc_test and hello_tash

apps/examples/testcase/ta_tc/device_management/utc/Kconfig, external/Kconfig
[Description] WiFi settings for Device Management were defined under apps/examples folder. They are now moved to external folder where they should belong.
=> [Title] Modified Kconfig in external to add DM WiFi settings

os/include/tinyara/pm/pm.h
it was written as a conditional statement,
and the ifndef was used incorrectly
change ifndef to if
Signed-off-by: Jaesik <jaesick.shin@samsung.com>
=> bug fix about power manager in pm.h

apps/include/builtin.h, apps/system/init/init.c
TizenRT/os/../build/output/libraries/libapps.a(init.o): In function `tash_register_cmds':
TizenRT/apps/system/init/init.c:72: undefined reference to `register_examples_cmds'
make[1]: *** [../build/output/bin/tinyara] Error 1
=> fix compilation error

framework/src/arastorage/index_manager.c, framework/src/arastorage/storage_interface.c
src/arastorage/index_manager.c:506:5: warning: 'row' may be used uninitialized in this function [-Wmaybe-uninitialized]
if (row != NULL) {
src/arastorage/storage_interface.c:579:4: warning: 'fd' may be used uninitialized in this function [-Wmaybe-uninitialized]
r = storage_write(fd, g_storage_write_buffer.buffer, g_storage_write_buffer.data_size);
=> fix compilation warning at arastorage

os/fs/smartfs/smartfs_utils.c
If buffer size is bigger than remained area + next area, calculating failed
=> Fix journaling issue

apps/examples/telnetd/Makefile
There is a white space in APPNAME, and there is a problem in creating
BuiltinApps. This patch fixes such a bug.
=> examples/telnetd: fix compile error

os/drivers/usbdev/Make.defs, os/drivers/usbdev/cdcacm.c, os/drivers/usbdev/cdcacm.h, os/drivers/usbdev/cdcacm_desc.c, os/drivers/usbdev/composite.c, os/drivers/usbdev/composite.h, os/drivers/usbdev/composite_desc.c, os/drivers/usbdev/pl2303.c, os/drivers/usbdev/usbdev_strings.c, os/drivers/usbdev/usbdev_trace.c, os/drivers/usbdev/usbdev_trprintf.c, os/drivers/usbdev/usbmsc.c, os/drivers/usbdev/usbmsc.h, os/drivers/usbdev/usbmsc_desc.c, os/drivers/usbdev/usbmsc_scsi.c, os/drivers/wireless/scsc/Make.defs
The e-mail address of the author of the file is incorrect. I think it is
a bug that occurred when changing nuttx to tinyara in batch.
=> drivers: modify author's email address

os/kernel/wdog/wd_delete.c
Interrupts has been restored only under 2 conditions
1) pre-allocated wdog free list
2) Allocated from heap memory
If the wdog has been statically allocated from wd_static API,and
wd_delete API is invoked, interrupts have not been restored. Since
wd_delete is global API, system can't guarantee that it will not
be called for statically created wdog timers
=> Restore the interrupts if wdog is created statically

os/include/tinyara/irq.h
irq_detach API expects irq as argument but naming it as isr
is confusing. Change it to appropriate name as irq
=> Change the irq_detach argument from isr to irq

os/arch/Kconfig, os/arch/arm/src/armv7-r/arm_assert.c, os/arch/arm/src/armv7-r/arm_vectors.S, os/arch/arm/src/common/up_internal.h
This patch adds a seperate stack for data abort handling.
Reason for adding a seperate stack for data abort handling is as below.
When a task's execution consumes all of its stack, example if its stack size
is 2K and stack is almost used (2K - 8) bytes. During this time if any data
abort happened, data abort handling code uses task's stack for storing context
and as well as for its execution. In that case data abort handling code might
corrupt adjacent stack area.
If an application's intention is to corrupt the other application's stack,
it would do it by overflowing its stack and hence corrupting the adjacent stack.
This scenario of adjacent stack corruption by stack overflow can be avoided
using this patch with MPU_STACKGAURD feature.
Change-Id: I61f80da6b6bbdd0d8d7375438a1bc5f44edd5b32 …
=> arch : prevention of adjacent stack access during data abort

os/arch/Kconfig, os/arch/arm/Kconfig
seperate dataabort stack is implemented only for armv7-r.
This patch moves dataabort stack config to arm/Kconfig and enables
only for armv7-r processors
Change-Id: Icf703dac4904a595a8420e4039527b8795614573
=> arch : move dataabort stack config to arm/Kconfig

os/kernel/irq/irq.h, os/kernel/irq/irq_initialize.c
NR_IRQS value is already incremented by last irq + 1
hence, there is no need to initialize g_irqvector as
NR_IRQS + 1. Save memory by limiting the g_irqvector
size to NR_IRQS
=> Limit the g_irqvector size to NR_IRQS

os/kernel/semaphore/sem_tickwait.c
Since wdog_timer has been started before waiting for semaphore and
if Sem_wait fails, wdog timer should be canceled before attempting
for delete operation. Though wdog_delete API takes care of canceling
an active timer, One must consider canceling the timer as soon as
possible to avoid calling wdog timeout handler and overwrite the
sem_wait error value as ETIMEOUT.
=> Stop the watchdog timer even when sem_wait() fails

apps/examples/testcase/le_tc/kernel/tc_libc_timer.c, apps/examples/testcase/le_tc/network/tc_net_inet.c
I have tested the tc examples of the kernel and network symbols. This patch includes examples that fix build errors and correspond to modified kernels.
=> Fix testcase

os/kernel/sched/sched_gettcb.c
valid pid range is from 0 to g_lastpid. anything beyond
this range is invalid pid. Hence add proper validation
=> Add missing boundary validation for pid

os/arch/arm/include/armv7-r/irq.h
Currently wrong configuration CONFIG_ARMV7A_DECODEFIQ is used in armv7-r
This patch changes it to use the appropriate config CONFIG_ARMV7R_DECODEFIQ.
=> armv7-r : use appropriate DECODEFIQ config in armv7-r

apps/system/utils/kdbg_env.c
Modify message of usages for setenv, getenv and unsetenv.
Change a syntax of getenv to display all environment variables that 'all' argument is removed.
=> Modify message of kdbgs for env variables and the syntax of getenv to print all env variables

os/fs/procfs/fs_procfsuptime.c
It brings build error that uptime_operations is not found when CONFIG_FS_PROCFS_EXCLUDE_PROCESS is enabled
=> fix incorrect config dependency in fs_procfsuptime.c

os/kernel/sched/sched.h
Max number of tasks should be power of 2
=> Make a build error when CONFIG_MAX_TASKS is not power of 2

os/kernel/wdog/wd_delete.c
Positions of 'else' and parentheses near the else are fixed following coding rules.
=> fix violations of coding style in wdog

apps/examples/ttrace/Make.defs, lib/libc/ttrace/lib_ttrace.c
Make.defs is missing at "Support T-Trace" commit
=> modify ttrace

lib/libc/pthread/pthread_attrgetstacksize.c
Without this condition, null dereference assert will occur
=> pthread : Add null check at pthread_getstacksize

os/kernel/pthread/pthread_create.c, os/kernel/task/task_create.c, os/kernel/task/task_init.c, os/kernel/task/task_setup.c, os/kernel/task/task_vfork.c
Both task_schedsetup() and pthread_schedsetup() sets wrong
error number incase of failure. error no set during invalid
priority check is not considered. And proper error no was not
set if system fails to assign unique new pid to task/thread.
This patch fixes the wrong error no set and sets the correct
error no.
=> Set correct errno in task_schedsetup and pthread_schedsetup

apps/system/utils/kdbg_kill.c
pthread_cancel() shouldn't be used to kill kernel threads, it raises
assert if tcb type is other than TCB_FLAG_TTYPE_PTHREAD. refer line no
125 in pthread_cancel.c
task_delete() API takes care of deleting tasks and kernel threads.
refer lineno 151 in task_delete.c
we can verify it using following commands from TASH
killall -9 <kernel thread name> or
kill -9 <pid of kernel thread>
=> Fix: use task_delete() to kill kernel threads and tasks

apps/examples/testcase/le_tc/kernel/tc_pthread.c, os/kernel/pthread/pthread.h, os/kernel/pthread/pthread_completejoin.c, os/kernel/pthread/pthread_condbroadcast.c, os/kernel/pthread/pthread_condsignal.c, os/kernel/pthread/pthread_condwait.c, os/kernel/pthread/pthread_create.c, os/kernel/pthread/pthread_detach.c, os/kernel/pthread/pthread_initialize.c, os/kernel/pthread/pthread_join.c, os/kernel/pthread/pthread_mutex.c, os/kernel/pthread/pthread_mutexinconsistent.c
When CONFIG_PTHREAD_MUTEX_UNSAFE=y, the special return value
EAGAIN was not being detected due to differences in reporting of returned values.
=> Fix a problem in pthread_trylock()

apps/netutils/mdns/mdnsd.c
services, member of struct mdnsd was added in CONFIG_NETUTILS_MDNS_RESPONDER_SUPPORT.
But codes calling this were added without CONFIG.
It makes compilation error like below when extra defconfig is used.
mdnsd.c:1357:30: error: 'struct mdnsd' has no member named 'services'
struct rr_list *svc_le = svr->services;
^
make[2]: *** [mdnsd.o] Error 1
=> fixup! netutils/mdns: add support for exposing services

os/kernel/semaphore/sem_recover.c, os/kernel/semaphore/sem_tickwait.c, os/kernel/semaphore/sem_timedwait.c
sem_recover() => sem_post has been changed to sem_wait
sem_tickwait() => sem_timeout() return value is also considered
sem_timedwait() => hidden call to sem_trywait() is mentioned
=> Correct the comment description for better understanding

apps/system/utils/kdbg_stackmonitor.c
pthread_cancel kills the thread and stkmon logging will be stopped immediately.
hence set the variable stkmon_started to FALSE so that user can re-attempt
command "stkmon" from tash
=> Set stkmon_started=FALSE in error case

lib/libc/spawn/lib_psa_init.c
If attr is invalid, posix_spawnattr_init return EINVAL
=> posix_spawnattr_init:Return EIVNAL when attr is NULL

os/arch/arm/src/sidk_s5jt200/src/s5jt200_led.c
fix not appropriate string to s5jt200
Change-Id: Ic11084af6a1e6ca73d0d45a20b443f5dae6ba66c
Signed-off-by: Jihoon Park <jh6186.park@samsung.com>
=> s5jt200: remove wrong string in error output

os/arch/Kconfig.board
The binary to upload with OpenOCD is tinyara_head.bin.
That binary is created when (and only when) SAMSUNG_NS2 is selected in the config.
=> Force tinyara_head.bin creation for Artik05x boards

os/include/tinyara/mm/mm.h
When CONFIG_MM_SMALL is defined, SIZEOF_MM_ALLOCNODE is not set properly
and thus set it properly and remove the hard coded values to real time values
=> Correct the SIZEOF_MM_ALLOCNODE incase of CONFIG_MM_SMALL is defined

os/include/tinyara/mm/mm.h, os/mm/mm_heap/mm_heapinfo.c
Inside struct mm_allocnode_s in mm.h file, the size and preceding are declared as mmsize_t.
heapinfo_add_size is getting called from mm_malloc.c by referencing to it's own structures
as below. heapinfo_add_size(((struct mm_allocnode_s *)node)->pid, node->size);
This was the concern to change the data type to mmsize_t to keep the same reference across
src files to keep the code robust.
=> Correct the datatype mismatch

apps/examples/hello_tash/hello_tash_main.c
Selecting CONFIG_EXAMPLES_HELLO_TASH makes the hello_tash application to be built.
The app does not build due to invalid types of two functions.
This patch fixes this build break.
=> Example build fix: invalid types of functions.

os/kernel/pthread/pthread_mutexunlock.c
where pthread_mutex_unlock() is called when the mutex is not locked.
In this case, it would increment the underlying semaphore above 1.
Change-Id: Iafb29eea5d81e25ca1fa52e1f698c7da62adbbd8
=> pthread_mutex_unlock(): Missing check for the case

os/kernel/pthread/pthread_mutexunlock.c
when fail because the mutex is not locked, but try to unlock,
it should return the proper errno, EPERM
=> Modify the initial return type for pthread_mutex_unlock

os/Kconfig
This comment makes defconfig ugly.
When we disable DEBUG_WLAN, it shows unncessary title at defconfig.
DEBUG_WLAN should be under subsystem debug options and
there are enough titles at wlan's subsystem like FW, driver and wpa_supplicant.
=> remove unnecessary wlan comment (title) on Kconfig

lib/libc/pthread/pthread_mutexattr_getprotocol.c, lib/libc/pthread/pthread_mutexattr_setprotocol.c
linfo is not defined, but want to show the info for debugging
Change-Id: I8802e9cfbc0147f39795c38b1c3a8f5482ce1584
=> Fix the wrong dbg in pthread_mutexattr_set/getprotocol

lib/libc/signal/sig_hold.c, lib/libc/signal/sig_relse.c, os/include/signal.h
signo -> sig, kill(pid_t pid, int sig), (_sa_handler_t) type
Change-Id: I0cf026fe99731134ff0a9fcda5c0bda2fae4b51e
=> Fix the param name mismatch and defines based on POSIX

apps/netutils/wifi/slsi_wifi_api.c
This pull request fixes a problem found in the wifi api function slsi_hexstr_2_bytearray. It did not convert the hex string correctly in all cases and this corrupts the IE data.
=> Fix for problem with conversion of WiFi IE data (hexstr_2_bytearray) 

os/drivers/audio/Make.defs
commit 50f18d7 uses wrong usage of c coding style comment inside Make.defs. This caused build break.
use # instead of /* in Make.defs
=> Fix build error in audio driver

apps/examples/kernel_sample/posixtimer.c, apps/examples/kernel_sample/sighand.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c
SIG_DFL is of sa_handler type and it should not be assigned to sa_sigaction type.
This fixes this issue
=> Fix : Assignment from incompatible pointer type

os/tools/README.txt, os/tools/mkdefconfig.sh
When new .config file is made and it will be used frequently or
will be shared to others, it should become a defconfig.
This script supports making defconfig set from .config and Make.defs.
=> add mkdefconfig.sh script at os/tools to make defconfig

os/include/stdlib.h
itoa returns a pointer to the resulting null-terminated string,
same as parameter str.
Change-Id: I583262751a36239f70e736bbb765490f72f6c7df
=> Fix the wrong explanation for itoa return

os/arch/arm/src/artik053/src/artik053_tash.c
With this fix ROM partition will be handled.
To test it:
1. In os/.config add line:
`CONFIG_FS_ROMFS=y`
2. Adjust partitions, eg:
```
CONFIG_ARTIK053_FLASH_PART_LIST="16,48,192,32,512,2400,1536,1536,1000,400,8,512,"
CONFIG_ARTIK053_FLASH_PART_TYPE="none,ftl,none,none,none,none,none,ftl,smartfs,romfs,config,none,"
CONFIG_ARTIK053_FLASH_PART_NAME="bl1,sssro,bl2,sssfw,wlanfw,os,factory,ota,user,rom,nvram,sssrw,"
```
above lines change size of main user partition from 1400 * 1KB to 1000 * 1KB
and add new 400 * 1KB partition. Type is romfs.
3. call make to build image
4. prepare ROM image using genromfs
`genromfs -f bin/rom.img -d /path/to/rom_fs/folder -V "NuttXBootVol"`
5. in openocd/partition_map.cfg add line corresponding with point 2
```
user	{ "USER R/W"		0x04620000	0x000FA000  0 }
rom …
```
=> Fix missing ROM partition type

lib/libc/pthread/Make.defs, lib/libc/pthread/pthread_rwlock.c, lib/libc/pthread/pthread_rwlock_rdlock.c, lib/libc/pthread/pthread_rwlock_wrlock.c, os/include/pthread.h
This patch adds pthread read write locks.
This implementation is ported by referring os test in latest nuttx.
Change-Id: I7f01845f36eb931405ca27f3b3b54cd9599a2e93
=> pthread : add rwlock implementation

apps/examples/testcase/le_tc/kernel/tc_libc_misc.c
some debug tc needs some condition, so bind with appropriate #ifdef~#endif
Change-Id: I8d98bf6f4f12cb32bcfb2aa713ec3a56a993af1c
=> Bind the debug tc function with appropriate #ifdef CONFIG_XX ~ #endif

os/kernel/init/os_start.c, os/kernel/sched/sched.h, os/kernel/sched/sched_releasetcb.c, os/kernel/task/task_create.c, os/kernel/task/task_setup.c
Existing overhead:
-----------------
Currently following steps involved before returning error.
1) Allocates the kernel memory for tcb struct
2) Allocates the user/kernel stack memory
3) Allocates the memory for group using group_allocate()
4) Associates file descriptors with the new task
5) Try to assign the pid for the new task
6) task_assignpid() does a check and returns error if already CONFIG_MAX_TASKS are alive in the system.
7) Once the error is returned, OS calles sched_release_tcb to deallocate/freeup the tcb, stack and group memory.
This feature address above concern as follows.
1) Tracks the number of tasks alive in the system at any point of time
2) Makes the early check, whether CONFIG_MAX_TASKS are already alive in the system, before proceeding further
3) If already …
=> Move CONFIG_MAX_TASKS check at earlier stage of task/thread creation

lib/libc/pthread/pthread_rwlock.c, os/include/pthread.h
This patch adds check for invalid rwlock initialization parameters.
Change-Id: Ifaf2654a72b0f67b354c742a8bfc230e23e4ad57
=> pthread :checking for invalid rwlock parameters

apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/kernel/tc_environ.c, apps/examples/testcase/le_tc/kernel/tc_group.c, apps/examples/testcase/le_tc/kernel/tc_libc_mqueue.c, apps/examples/testcase/le_tc/kernel/tc_libc_signal.c, apps/examples/testcase/le_tc/kernel/tc_libc_stdio.c, apps/examples/testcase/le_tc/kernel/tc_libc_string.c, apps/examples/testcase/le_tc/kernel/tc_libc_unistd.c, apps/examples/testcase/le_tc/kernel/tc_mqueue.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c, apps/examples/testcase/le_tc/kernel/tc_sched.c, apps/examples/testcase/le_tc/kernel/tc_semaphore.c, apps/examples/testcase/le_tc/kernel/tc_signal.c, apps/examples/testcase/le_tc/kernel/tc_task.c, apps/examples/testcase/le_tc/kernel/tc_timer.c, apps/examples/testcase/le_tc/kernel/tc_umm_heap.c, apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c, apps/examples/testcase/ta_tc/device_management/itc/itc_dm_conn.c, apps/examples/testcase/ta_tc/device_management/itc/itc_dm_lwm2m.c, apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c, apps/examples/testcase/ta_tc/systemio/itc/itc_i2c.c, apps/examples/testcase/ta_tc/systemio/itc/itc_pwm.c, apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c, apps/examples/testcase/ta_tc/systemio/itc/itc_uart.c, apps/examples/testcase/tc_common.h
Remove error parameter of clean up functions in tc macros because this is not useful
Leave a function which checks whether values are equal and rename it to TC_ASSERT_EQ_ERROR_CLEANUP to show error type
=> Changes format of function for clean up in tc macros and add new tc macro

os/include/net/lwip/sockets.h
There is macro with the same name but different content
within two basic OS headers - sockets.h and ioctl.h.
It is necessary to fix this by extending macro name with prefix
so it will be clear, which header's macros is use where.
=> FIONREAD macro namespace clash resolved for IOCTL and SOCKETS

lib/libc/stdlib/lib_mkstemp.c
1.Fix an error in mkstemp() the could result in an infinite loop.
2.Fix for wrong output in some cases.
For Example:
input: "FILEXX"
output: "FILE00" and repeating same output for further invocations of mkstemp().
But, the ouput has to be FILE01, FILE02, ...., FILEZZ.
=> libc/stdlib: Error Fixes

apps/system/utils/Kconfig
Stack monitoring feature is enabled from TASH with "stkmon" command. however
this file is getting built even though TASH shell is disabled and it's been
referenced from sched_releasetcb() API in sched_releasetcb.c file. Thus it's
symbols have been included in final image.
Without having the TASH shell prompt, there is no purpose of building this file and
having it's symbols in the final binary. This patch saves 2048 bytes in the
final tinyara binary. Also this feature shouldn't be available for protected build.
Thus adding both TASH and !BUILD_PROTECTED dependency to Kconfig
without patch : -rwxrwxr-x 1 pradeep pradeep  175104 Jul 13 23:10 tinyara.bin
with patch    : -rwxrwxr-x 1 pradeep pradeep  173056 Jul 13 23:44 tinyara.bin
=> Add !BUILD_PROTECTED && !BUILD_KERNEL dependency for ENABLE_STACKMONITOR flag

build/configs/sidk_s5jt200/sidk_s5jt200_download.sh, build/configs/sidk_s5jt200/tools/openocd/partition_gen.sh, build/configs/sidk_s5jt200/tools/openocd/s5jt200_silicon_evt0_fusing_flash_all.cfg, os/arch/arm/src/sidk_s5jt200/Kconfig, os/arch/arm/src/sidk_s5jt200/src/s5jt200_tash.c
This series of patches for supporting romfs  in sidk_s5jt200 board.
To test it,
1. configure for sidk_s5jt200/hello_with_tash
2. make menuconfig
- Enable CONFIG_FS_ROMFS
- Split last partition size to (256,256) in CONFIG_SIDK_S5JT200_FLASH_PART_LIST
- Append "smartfs" at the end to CONFIG_SIDK_S5JT200_FLASH_PART_TYPE
- Append "romfs" at the end to CONFIG_SIDK_S5JT200_FLASH_PART_NAME
(Above 3 steps created romfs partition with size 256K at the end,
where romfs device is a smart device and romfs filesystem will be
mounted on smartdevice "/dev/smart0p15" )
- Enable CONFIG_SIDK_S5JT200_AUTOMOUNT_ROMFS
3. make
4. Put "contents" into "external/contents" directory
4. make download ALL
=> Sidk s5jt200 romfs dev

os/arch/arm/src/artik053/src/artik053_tash.c, os/arch/arm/src/sidk_s5jt200/src/s5jt200_tash.c, os/drivers/pipes/pipe.c, os/drivers/usbdev/cdcacm.c, os/drivers/usbdev/pl2303.c, os/include/tls/configs/ssl_client1.c, os/include/tls/configs/ssl_server.c, os/kernel/environ/env_setenv.c, os/pm/pm_procfs.c
Usage of sprintf can help hackers to cause buffer overflows and even
developers may unnotice the size of the destination buffer before
passing the formatted string and thus cause buffer overflow scenarios.
It's wise to use snprintf to avoid any such scenarios.
This patch takes care of sprintf usage inside OS folder only.
=> Replace sprintf with secure API snprintf for security reasons

lib/libc/math/lib_ceil.c, lib/libc/math/lib_ceilf.c, lib/libc/math/lib_ceill.c
_Ex_:for input **x = 1.0**, the ouput should be **1.0**, but the ouput was **2.0**.
This wrong ouput is fixed.
=> libc/math: Fix for wrong ouput in ceil() API

apps/examples/testcase/le_tc/filesystem/fs_main.c
Add ommitted assignment for fd in dup2 tc
Although negative tc is failed below, fd1 can be positive value because of tc success before
So fd should be assigned as negative value
=> Fix bugs in fs dup2 tc

apps/examples/testcase/le_tc/kernel/tc_libc_math.c
This patch covers test cases for left out API's in libc/math
The API's are namely:	acos,acosf,acosl,acosh,acoshf,acoshl,
asin,asinf,asinl,asinh,asinhf,asinhl,
atan,atanf,atanl,atanh,atanhf,atanhl,
atan2,atan2f,atan2l,ceil,ceilf,ceill,
copysign,copysignf,copysignl,cos,cosf,
cosl,cosh,coshf,coshl,erf,erff,erfl,
frexp,frexpf,frexpl,ldexp,ldexpf,ldexpl,
log2,log2f,log2l,sin,sinf,sinl,sinh,
sinhf,sinhl,trunc,truncf.
=> Code Coverage: libc/math: Add test cases for various math API's

os/kernel/signal/sig_timedwait.c
Pending signal structure '**sigpend**' is used after it has been released by **sig_releasependingsignal**().
=> Fix: sigtimedwait: Pending signal structure used after it has been released

apps/examples/testcase/le_tc/kernel/tc_libc_math.c
Adds test cases for following libc/math API's,
cbrtf, cbrtl, exp2, expl, exp2f, exp2l, fabsf, fabsl, fdimf, fdimfl,
floorf, floorl, fmaxf, fmaxl, fminf, fminl, hypotf, hypotl, j0f, j1f, jnf,
nextafterf, nextafterl, nexttowardf, nexttowardl, remainderf, remainderl,
remquof, remquol, rint, rintf, rintl, round, roundf, roundl, scalbnf, scalbnl,
sqrt, sqrtf, sqrl, y0f, y1f, ynf.
=> TC: Add test cases for Libc Math

apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/kernel/tc_clock.c, apps/examples/testcase/le_tc/kernel/tc_environ.c, apps/examples/testcase/le_tc/kernel/tc_libc_libgen.c, apps/examples/testcase/le_tc/kernel/tc_libc_semaphore.c, apps/examples/testcase/le_tc/kernel/tc_libc_stdlib.c, apps/examples/testcase/le_tc/kernel/tc_libc_string.c, apps/examples/testcase/le_tc/kernel/tc_libc_timer.c, apps/examples/testcase/le_tc/kernel/tc_libc_unistd.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c, apps/examples/testcase/le_tc/kernel/tc_semaphore.c, apps/examples/testcase/le_tc/kernel/tc_termios.c, apps/examples/testcase/le_tc/network/tc_net_inet.c
Expands/Adds test cases for following API's,
**fs**: opendir(), closedir()
**net_inet**: ntop() and pton()
**kernel/pthread**: pthread_sigmask() 
**kernel/clock**: clock_getres() and gettimeofday()
**kernel/environ**: setenv() and putenv()
**libc/libgen**: dirname()
**libc/termios**: isatty(), cfgetspeed() and tcsetattr()
**libc/timer**: strftime()
**libc/string**: memmove(), strstr() and strcasestr()
**libc/unistd**: getcwd(), chdir(), access(), getopt() getoptargp(), getoptindp() and getoptoptp()
**libc/stdlib**: itoa(), qsort(), abort(), strtod(), strtol(), strtoll(), strtoul()
**libc/semaphore**: sem_getprotocol()
=> Add Test Cases for fs, net_inet, kernel, libc modules

apps/examples/testcase/le_tc/kernel/tc_libc_math.c
This patch covers test cases for left out API's in libc/math
The API's are namely:	tan, tanf, tanh, tanhf, tanhl, tanl
=> libc/math: Add test cases for few math API's

apps/examples/testcase/le_tc/kernel/tc_libc_math.c
libc/math: Cover full test cases for atan2(),atan2f(),atan2l() API's
Earlier all test cases were not covered in the TC for atan2.
This patch covers the left out TC's.
=> [Code coverage] libc/math: cover left over test cases for existing TC's

apps/system/utils/Kconfig, apps/system/utils/Makefile, apps/system/utils/kdbg_commands.h, apps/system/utils/kdbg_irqinfo.c, apps/system/utils/kernelcmd.c, os/Kconfig, os/include/tinyara/irq.h, os/kernel/irq/Make.defs, os/kernel/irq/irq.h, os/kernel/irq/irq_attach.c, os/kernel/irq/irq_dispatch.c, os/kernel/irq/irq_info.c, os/kernel/irq/irq_initialize.c
If CONFIG_ENABLE_IRQINFO is enabled, This patch would display the number of registerd interrupts, it's occurances in the system and it's isr information. This feature works only for flat build ie BUILD_PROTECTED = n
=> Display Interrupts information to user

os/Kconfig, os/arch/Kconfig
Corrected the Kconfig help description as follows
BUILD_PROTECTED => Adjusted the length of the description to readable format
BUILD_KERNEL => Changed from MPU -> MMU
ARCH_USE_MMU => removed duplicate word
ARCH_USE_MPU => removed duplicate word
=> Correct the Kconfig help description

apps/system/netdb/netdb_main.c
Fixed a build error when using netdb interface
netdb_main.c:144:6: error: unused variable 'ret' [-Werror=unused-variable]
int ret;
^
=> Fixed a build error when using netdb interface

os/arch/arm/src/s5j/s5j_boot.c
Previous code assumed that registers during function call
are r0 and r1, but compiler can allocate any register at
any time to inlined function.
=> s5j_boot.c: fix incorrect assembly code

lib/libc/fixedmath/lib_fixedmath.c
Fix in **ub16mulub16()** of fixedmath,
It's "**uint32_t m2i = ((uint32_t)m1 >> 16)**"
where, It should be "**uint32_t m2i = ((uint32_t)m2 >> 16)**"
=> Fix: Minor change in Libc FixedMath "ub16mulub16" function

apps/Makefile, apps/tools/create_appspec.sh
1. modify calling method on Makefile
The applist should be called at everywhere of apps, not only example
2. add removing an old appspec meta file before making a new meta
3. modify a variable name from EXAMPLEDIR to TARGET_DIR_LIST
4. modify a method to get whether configuration is enabled or not
If some config is not in defconfig (It means config is not enabled),
this script recognize config is enabled. This is wrong.
Let's get "CONFIG_XX=y" instead of "# CONFIG_XX is not set"
5. add output sentence to notice finishing
=> refactoring create_appspec

os/kernel/task/task_create.c, os/kernel/task/task_restart.c, os/kernel/task/task_vfork.c
By design, task_activate API always returns OK.
There is no need to check error condition and
add the un-necessary code. Keep the code clean
=> Remove unnecessary logic while handling return of task_activate

apps/examples/testcase/le_tc/kernel/tc_libc_pthread.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c, lib/libc/pthread/pthread_mutexattr_getprotocol.c
Modified return value and test cases for:
pthread_mutexattr_getprotocol()
pthread_mutexattr_setprotocol()
pthread_setcancelstate()
pthread_setcanceltype()
pthread_testcancel()
=> Libc pthread Modify return value as per POSIX standard

lib/libc/string/lib_vikmemcpy.c
Fix compile-time warning about type conversion
=> libc: fix 'casting pointer to integer of different size' compiler warnings

os/drivers/rwbuffer.c
=> drivers/rwbuffer: fix 'unused variable'

apps/system/readline/readline_common.c
* We should check whether CONFIG_EOL_IS_EITHER_CRLF is defined,
instead of checking it's value.
=> apps/readline: check whether CONFIG_EOL_IS_EITHER_CRLF is defined

os/drivers/rwbuffer.c
=> drivers/rwbuffer: fix wrong arguments order during 'rwb->rhreload' call

os/fs/procfs/Kconfig
=> fs/procfs: make FS_PROCFS option visible only with mountpoints enabled

apps/system/utils/fscmd.c
* 'df' utilities task is to show filesystem info, but it
is meaningless when mountpoints are disabled and hence
no user filesystems are supported.
=> apps/fscmd: hide util 'df' if mountpoints are disabled

os/fs/smartfs/smartfs_procfs.c
Smartfs info can be excluded from procfs by enabling
FS_PROCFS_EXCLUDE_SMARTFS config, but in smartfs_procfs
there was syntax error with wrong config name.
=> fs: fix config name for smartfs exclusion from procfs

os/arch/arm/src/artik053/Kconfig
* MTD_PARTITION option is supported only when MTD support is enabled.
=> arch/artik053/Kconfig: selecting MTD_PARTITION without MTD is an error

os/pm/pm_metrics.h
The pm_get_domainmetrics and pm_prune_history functions are called
only when CONFIG_PM_METRICS is enabled. So definitions for them is
not needed when config is disabled.
=> remove unused definitions for pm

apps/examples/testcase/le_tc/kernel/tc_termios.c, lib/libc/Kconfig
1) Changes wrong typo '_memcpy_' to '_memset_' in `config MEMSET_OPTSPEED `"`--help--`" section. 
2) Add Missing TC_SUCCESS_RESULT Macro in libc termios.
=> Typo Fix in Libc Kconfig and Add Missing TC_SUCCESS_RESULT Macro in libc termios.

os/arch/arm/src/artik053/Kconfig
* Since ARTIK053_FLASH_PART selects MTD layer specific options, which
are available only with mountpoints being enabled, ARTIK053_FLASH_PART
option must be invisible for user when DISABLE_MOUNTPOINT is enabled.
=> arch/artik053: make ARTIK053_FLASH_PART dependent on !DISABLE_MOUNTPOINT

os/include/stdio.h
Declaration of statfs should belong to sys/statfs.h
=> include/stdio: removed duplicate prototype of statfs

os/arch/arm/src/s5j/Make.defs
* When option CONFIG_SCHED_YIELD_OPTIMIZATION is enabled, scheduler's
code enable yield feature which requires up_schedyield to be
implemented. But there was missing logic in arch Makefile for
compiling up_schedyield.c file.
=> arch/arm/common: add directives to compile up_schedyield logic

lib/libc/Kconfig
Enabling ARCH_ROMGETC assumes that for the target architecture
there exists implementation of up_romgetc() function. But even when
implementation is missing ARCH_ROMGETC option is still visible
to the user, so the option being selected cause build failure.
The solution is to add upper-level option, which can be selected
in specific architecture configs and make option ARCH_ROMGETC visible.
Otherwise ARCH_ROMGETC will be unvisible to the user.
=> libc: add arch-dependent option for ARCH_ROMGETC visibility control

os/arch/arm/src/armv7-r/arm_memcpy.S
This patch adds support for architecture optimized `memcpy` for **armv7-r** architecture.
To use architecture optimized memcpy enable `CONFIG_ARCH_OPTIMIZED_FUNCTIONS` and `CONFIG_ARCH_MEMCPY`.
This patch is back ported form Nuttx.
=> armv7-r: memcpy: support architecture optimized memcpy

README.md
Current kconfig-frontends is not supporting byacc anymore.
Observed issue using byacc (20140715-1):
kconfig-frontends/kconfig-frontends/libs/parser/yconf.y", syntax error
%destructor {
Problem has been solved using bison-2:3.0.4.dfsg-1 instead.
Change-Id: I25d53f3d01c1f260b6fa9523ca9442b719862139
=> doc: Install bison to support kconfig

build/configs/sidk_s5jt200/README.md, build/configs/sidk_s5jt200/tools/openocd/s5jt200_attach_gdb.cfg
This patch adds a openocd cfg which can be used to attach
gdb to s5jt200 chip.
Steps:
1. Build tinyara for sidk_s5j200 board (tested with hello_with_tash config)
2. make download ALL
3. cp build/output/bin/tinyara os/
4. [In Terminal 1] :
- cd build/configs/sidk_s5jt200/tools/openocd/
- ./linux64/openocd -f s5jt200_attach_gdb.cfg
5. [In Terminal 2] :
- cd os/
- arm-none-eabi-gdb -ex "target remote :3333" tinyara
- To run tinyara from beginning, set entrypoint to pc register in gdb
- Ex : (gdb) set $pc = entry_addr
- entry_addr can be obtained by "arm-none-eabi-readelf -h tinyara"
=> s5jt200 : add openocd configuration to attach gdb

apps/examples/testcase/le_tc/kernel/tc_libc_math.c
=> Fix Coding Rule Violation on testcase example

os/pm/Kconfig
* The power managment system depends on workqueue support, which
checks at compile time and cause build failure, if workqueues
disabled. However, it seems necessary to make PM
option dependent on SCHED_WORKQUEUE itself.
=> pm/Kconfig: make power management settings dependent on SCHED_WORKQUEUE

apps/examples/kernel_sample/kernel_sample_main.c
aio.c compiles only when CONFIG_EXAMPLES_KERNEL_SAMPLE_AIO is enable,
so in order to use it's functions we need to check whether
CONFIG_EXAMPLES_KERNEL_SAMPLE_AIO is enabled.
=> apps/kernel_sample: fix async io test

os/include/tinyara/net/netdev.h
* If CONFIG_NET_MULTIBUFFER is not defined, then static buffer
for holding packets allocated and it's size depends on MAX_NET_DEV_MTU
constant. Included header with it's definition.
=> include/netdev: include missing header

lib/libc/stdio/lib_dtoa.c
=> lib/libc: fix 'unsuned variable' compilation error

apps/examples/testcase/le_tc/kernel/kernel_tc_main.c, apps/examples/testcase/le_tc/kernel/tc_libc_unistd.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c, os/include/pthread.h
1) Fix for tc libc sleep fail.
2) Fix for tc build error when CONFIG_PTHREAD_MUTEX_TYPES disabled.
=> Fix: libc tc issues

os/arch/arm/src/artik053/Kconfig
Implementation of userfs partition automount ('artik053_tash.c',
'board_app_initialize()') requires smartfs filesystem support.
=> artik053/Kconfig: made ARTIK053_AUTOMOUNT_USERFS dependent on FS_SMARTFS

apps/system/utils/kdbg_date.c, lib/libc/time/lib_gmtimer.c
Added Localtime support:
Date command works fine with CONFIG_LIBC_LOCALTIME enabled.
=> Added LIBC_LOCALTIME support for date command

os/kernel/pthread/pthread_setschedparam.c
Setting the error no at the beginning of logic is not a good practice as it causes
confusion during successful execution of the API.
When API executes successfully, it does not revert the wrong error code set during
beginning of the logic. Thus we should always make a practice to set the error no
only when logic enters the error case.
=> Remove failsafe error setting in pthread_setschedparam.c

build/configs/artik053/README.md, build/configs/sidk_s5jt200/README.md
ARTIK053 and SIDK_S5JT200 boards are connected through USB.
To use USB, permission is needed. So, contents which shows how to do it
are added.
=> Add contents how to set usb environment

build/configs/sidk_s5jt200/tools/openocd/.gitignore
The partition_map.cfg is built for specific configs, we don't need to add
that at repository.
=> add .gitignore to block adding built file for specific configs

lib/libc/math/lib_j0.c, lib/libc/math/lib_j1.c
When compiling with Linux toolchain, there are build errors like:
```
math/lib_j1.c: In function ‘pone’:
math/lib_j1.c:363:2: error: unknown type name ‘double_t’; did you mean
‘double’?
double_t z;
^~~~~~~~
```
This patch solves compilation using modern v7.2.0 toolchain.
This PR fixes issue:
https://github.com/Samsung/TizenRT/issues/463
=> Fix compilation of arm-linux-gnueabi-gcc-

lib/libc/math/lib_exp2.c, lib/libc/math/libm.h
lib_exp2.c : spaces required around that '='
libm.h : space required after that close brace '}'
=> Fix coding rule error in lib

build/configs/artik053/audio/Make.defs, build/configs/artik053/extra/Make.defs, build/configs/artik053/hello/Make.defs, build/configs/artik053/iotivity/Make.defs, build/configs/artik053/kernel_sample/Make.defs, build/configs/artik053/minimal/Make.defs, build/configs/artik053/nettest/Make.defs, build/configs/artik053/tash/Make.defs, build/configs/artik053/tc/Make.defs, build/configs/artik053/typical/Make.defs, build/configs/artik053/wifi_test/Make.defs, build/configs/sidk_s5jt200/hello/Make.defs, build/configs/sidk_s5jt200/hello_with_tash/Make.defs, build/configs/sidk_s5jt200/kernel_sample/Make.defs, build/configs/sidk_s5jt200/sidk_tash_aws/Make.defs, build/configs/sidk_s5jt200/sidk_tash_wlan/Make.defs, build/configs/sidk_s5jt200/tc/Make.defs
to include external APIs easily.
In source codes, we can include them like below.
#include <xxx.h>
=> Add an include path for external

lib/libc/stdio/lib_rawinstream.c, lib/libc/stdio/lib_rawoutstream.c, lib/libc/stdio/lib_rawsistream.c, lib/libc/stdio/lib_rawsostream.c
This patch fixes wrong file names of the files:
lib_rawinstream.c
lib_rawoutstream.c
lib_rawsistream.c
lib_rawsostream.c
=> Fix wrong filenames

apps/system/utils/kdbg_date.c
This symbol is used only in day_of_week() function
Fixes following error:
kdbg_date.c:76:30: error: ‘g_dayofweek’ defined but not used
[-Werror=unused-const-variable=]
static FAR const char *const g_dayofweek[] = {
=> kdbg_date.c: Fix compilation error on GCC 7

os/fs/driver/mtd/smart.c
Definition of variables depends on CONFIG_MTD_SMART_WEAR_LEVEL
Fixes following build error:
driver/mtd/smart.c:209:22: error: ‘gWearBitToLevelMap4’ defined but not
used [-Werror=unused-const-variable=]
static const uint8_t gWearBitToLevelMap4[] = {
^~~~~~~~~~~~~~~~~~~
driver/mtd/smart.c:198:22: error: ‘gWearLevelToBitMap4’ defined but not
used [-Werror=unused-const-variable=]
static const uint8_t gWearLevelToBitMap4[] = {
^~~~~~~~~~~~~~~~~~~
=> smart.c: Fix compilation error with GCC 7

os/logm/logm.c, os/logm/logm.h, os/logm/logm_tashcmds.c
- Add missing include header
- Delete logm_tash definition from logm.h because it is used in a file only
=> Fix build warnings in logm

os/arch/arm/src/artik053/Kconfig, os/arch/arm/src/sidk_s5jt200/Kconfig
For flash_part config, mtd should be enabled but disable_mountpoint
is not needed. But for automount config, disable_mountpoint should
be checked.
=> modify a dependancy of flash configuration on artik053 and sidk_s5jt200

os/arch/arm/src/s5j/s5j_i2c.c
Before the bus could only be taken once, otherwise it didn't work.
Even worse, second uninit triggered a DEBUGASSERT failure.
Fixes https://github.com/Samsung/TizenRT/issues/476
Tested (in relevant regard) on Artik053
=> S5J I2C: fix bus initialization.

apps/system/init/Make.defs
When CONFIG_SYSTEM_PREAPP_INIT is disabled, init should not be compiled.
So, bind it at Make.defs of init folder
=> apps/init: bind a conditional

apps/examples/fs_helper/Kconfig
For fs helper example, we don't need to make a title.
It cause a wrong block for example.
```
#
#
#
#
```
=> examples/fs_helper: remove unnecessary menu in Kconfig

os/fs/smartfs/smartfs_smart.c
During error case in smartfs_open() , sf->buffer is not freed.
CONFIG_SMARTFS_USE_SECTOR_BUFFER is dependent on CONFIG_MTD_SMART_ENABLE_CRC
When CONFIG_MTD_SMART_ENABLE_CRC is enabled through make menuconfig,  *_SECTOR_BUFFER gets defined and thus , in below logic, there is a chance of potential memory leak incase of failure case in smartfs_open file.
#ifdef CONFIG_MTD_SMART_ENABLE_CRC
#define CONFIG_SMARTFS_USE_SECTOR_BUFFER
#endif
=> Fix memory leak when CONFIG_SMARTFS_USE_SECTOR_BUFFER is enabled

os/arch/arm/src/tiva/tiva_gpio.c
amselclr, amselset can be unused-but-set-variable depends on config.
Wrap them in ifdef statements
=> Fix build warning in tiva_gpio.c

os/arch/arm/src/tiva/chip/lm3s_memorymap.h, os/arch/arm/src/tiva/tiva_gpioirq.c
Replace TIVA_ADC_BASE with TIVA_ADC0_BASE
Remove unused variable 'index'
=> Fix typo and remove unused variable in tiva

lib/libc/string/lib_strncmp.c
that line is not operation, so space is not needed
=> Fix the coding rule : libc/string/strncmp

apps/system/utils/kdbg_date.c, apps/system/utils/kdbg_env.c, apps/system/utils/kdbg_heapinfo.c, apps/system/utils/kdbg_kill.c, apps/system/utils/kdbg_stackmonitor.c, apps/system/utils/kdbg_stackopt.c, apps/system/utils/kdbg_ttrace.c
if only strlen, security issue can occur. so we should check strlen + 1 size.
=> Modify strncmp 3rd param in kdbg

framework/include/arastorage/arastorage.h
The group name, ARASTORAGE is used in ingroup before being defined by defgroup.
Defgroup which means definition of group should be in front of ingroup.
=> Fix doxygen comment for arastorage in framework/include/arastorage/arastorage.h

os/kernel/Kconfig, os/kernel/init/os_bringup.c, os/tools/cfgdefine.c
CONFIG_INIT_FILEPATH, CONFIG_INIT_SYMTAB and CONFIG_INIT_NEXPORTS are not
needed anymore. They are not needed and
config already removed so that we can't enable them.
=> kernel, tools: remove unused codes related CONFIG_INIT_FILEPATH

apps/system/utils/netcmd_dhcpd.c, external/dhcpd/dhcpd.c, external/include/protocols/dhcpd.h, framework/Makefile, framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/Kconfig, framework/src/wifi_manager/Make.defs, framework/src/wifi_manager/wifi_common.h, framework/src/wifi_manager/wifi_manager.c, framework/src/wifi_manager/wifi_mutex.c, framework/src/wifi_manager/wifi_mutex.h, framework/src/wifi_manager/wifi_net.c, framework/src/wifi_manager/wifi_net.h, framework/src/wifi_manager/wifi_semaphore.c, framework/src/wifi_manager/wifi_semaphore.h, framework/src/wifi_manager/wifi_utils.c, framework/src/wifi_manager/wifi_utils.h, os/net/Kconfig
Wi-Fi Manager is introduced to provide easy APIs for applications to easily manipulate Wi-Fi features
=> Add the initial version of Wi-Fi Manager

apps/system/i2c/Makefile, apps/system/vi/Makefile
These tools come from apps/system.
=> Integrate vi and i2ctool into builtin apps for tash

external/Kconfig
To handle variable arguments in iotivity, you need the stdarg.h file.
This patch allows you to include this file.
Change-Id: I3c6afee312542764c94ced931e9563ed70090875
=> external: add header files that require iotivity

external/Makefile
The Make.dep is an output of built so that it should be clean when
we execute "make distclean".
=> external: delete output of built, Make.dep at distclean

os/arch/arm/src/artik053/src/artik053_alc5658.c, os/audio/Kconfig
alc5658 audio device can be registered as two seperate devices.
The device naming format is "/dev/audio/pcmC%dD%d%c",card,device,(playback or capture flag).
Changed the device opening format in tinyalsa to open the device registered as a single device for both playback and capture.
=>  Added support for separate device registeration for play and capture.

lib/libc/math/lib_logf.c, lib/libc/math/lib_modff.c, lib/libc/math/lib_modfl.c
Use correct type of 'fabs' API in modff, modfl and logf implementations.
=> Fix: Use correct type of 'fabs' API

apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c, apps/examples/testcase/le_tc/kernel/tc_sched.c, apps/examples/testcase/le_tc/kernel/tc_signal.c, apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
TC_ASSERT and TC_ASSERT_EQ/NEQ can check whether some value is true or false.
But it is more clear to use TC_ASSERT_EQ/NEQ for readability.
=> Change TC_ASSERT to TC_ASSERT_EQ for readability in TCs of fs, arstorage and kernel

apps/system/utils/kdbg_stackopt.c
Buffer '&stkmon_arr' of size 64 accessed at kdbg_stackopt.c:124 can overflow, since its index 'stkmon_idx' can have value 64
that is out of range, as indicated by preceding conditional expression at kdbg_stackopt.c:114.
=> Fix svace issue : kdbg_stackopt array index error

apps/examples/testcase/le_tc/kernel/tc_libc_pthread.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c
This patch fixes the value for old cancellability variable used in the TC for testing.
=> Codecoverage: (libc/pthread) Fix TC for pthread_setcanceltype() & pthread_setcancelstate() API

apps/examples/testcase/le_tc/filesystem/fs_main.c
This patch adds test cases for stream initialization API's namely:
memoutstream, meminstream, memsistream, memsostream,
rawinstream, rawoutstream, rawsistream, rawsostream,
stdinstream, stdoutstream, stdsistream, stdsostream
nullinstream, nulloutstream, zeroinstream
=> Codecoverage(libc/stdio): Add TC's for few API's in stdio

apps/examples/wifi_test/wifi_test.c
1. use strncat instead of strcat.
2. use snprintf instead of sprintf
3. close socket fd when send() fails.
=> Fix Svace issues in wifi_test.c

os/arch/arm/src/artik053/Kconfig
Automount functionality of ROMFS for ARTIK053 should be executed
only when FS_ROMFS is enabled.
=> arch/artik053: make a dependancy with ROMFS for ROMFS automount

os/logm/logm.c
g_logm_overflow_offset is a variable for saving buffer offset where overflow happened.
So when overflow happens only, It has a value of which the range is from 0 to (buffer size-1).
If not, it should be invalid value like -1.
Initially, logm buffer is empty but logm can decide that overflow happened because this value is 0.
So It is needed to be initialized as invalid value.
=> Initialize g_logm_overflow_offset value as -1 in logm.c

external/iotivity/iotivity_1.2-rel/resource/csdk/connectivity/src/adapter_util/ca_adapter_net_ssl.c
- 2619e21 : This commit changed 'pthread_mutex_unlock' process  when the mutex is already unlocked.
- In 'oc_mutex_unlock()', if we do unlock with unlocked mutex, 'pthread_mutex_unlock()' retruns FAIL.
- 'exit()' kill the essential thread which is running,  then every process is stopped.
```c
void oc_mutex_unlock(oc_mutex mutex)
{
oc_mutex_internal *mutexInfo = (oc_mutex_internal*) mutex;
if (mutexInfo)
{
int ret = pthread_mutex_unlock(&mutexInfo->mutex);
if(ret != 0)
{
OIC_LOG_V(ERROR, TAG, "Pthread Mutex unlock failed: %d", ret);
exit(ret);
}
(void)ret;
}
else
{
OIC_LOG_V(ERROR, TAG, "%s: Invalid mutex !", __func__);
}
}
```
=> Fix iotivity bug in usage of mutex

external/iotivity/iotivity_1.2-rel/resource/csdk/connectivity/src/ip_adapter/tizenrt/caipnwmonitor.c
- 'Interface down' is a burden process in iotivity for TizenRT
- We need to keep tcp setting while device is on.
=> Remove call statement which is called when network interface down

external/include/mbedtls/see_api.h
- 'mbedtls' is moved to '/external/' from '/os/net/' relative paths are changed too.
- This is just for workaround to build, we need to change this to the generic architecture for several boards.
=> fix include path in mbedtls

os/arch/arm/include/setjmp.h, os/arch/arm/src/common/setjmp.S, os/arch/arm/src/s5j/Make.defs, os/arch/arm/src/tiva/Make.defs, os/include/setjmp.h
This patch adds ARM-R and ARM-M implementation of setjmp and
longjmp POSIX functions. FPU context saving and restoring is
supported when enabled.
=> Include implementation of setjmp/longjmp

apps/examples/webclient/webclient_main.c, apps/examples/webserver/webserver_main.c, apps/examples/websocket/websocket_main.c
1. Use strncmp instead of strcmp
2. Delete duplicated usage print webclient example
3. Free malloced variables before a function returns
=> Fix Svace issues in webclient/webserver/websocket examples.

os/arch/arm/src/tiva/Make.defs
It makes build error.
Assembler messages: common/setjmp.S:155: Error: r13 not allowed here
=> Remove setjmp.S in tiva/Make.defs

apps/examples/testcase/le_tc/filesystem/fs_main.c
We don't need many testcases for various mode flags here.
Internally, lib_mode2flags function checks whether it is valid or not.
It is already covered in libc_stdio_fopen_tc.
=> Remove unnessasary testcase in libc_stdio_freopen_tc

lib/libc/stdio/lib_freopen.c
freopen should return NULL when oflags is less than 0, not equal to 0.
Because negative value is returned on failure of lib_mode2offlags which converts the mode string into file open mode flag.
=> Fix wrong condition for checking invalid mode in freopen function.

external/iotjs/test/run_pass/test_net_connect.js
This fix closes the server in the test more clearly. The test purpose is to test 'net.connect'.
=> fix iotjs net connection test

apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c, apps/examples/wifi_test/wifi_test.c
1. Use snprintf instead of sprintf with maximum length - 1
2. Tackle the overflow when string concatenating
=> Fix missing null termination at strncat() in wifi_test.c

apps/tools/update_config.sh
When user entry point is changed through make applist/appupdate,
CONFIG_ENTRY_XX is not updated, only CONFIG_USER_ENTRYPOINT is.
So, it looks not changed on menuconfig.
Let's change it to manaul when entry is changed.
=> apps/tools: fix update_config.sh for issue on update entry point

build/configs/artik053/.flashSpec.xml, build/configs/artik053/artik053_download.sh
Sometimes, we should erase user fs at first flashing on new board.
So, ERASE_USERFS option is added.
=> artik053: add flashing script to erase user fs

os/arch/arm/src/s5j/Make.defs
Fix "Makefile:174: target `s5j_clock.o' given more than once in the same rule"
Removed the duplicate entry 'CHIP_CSRCS += s5j_clock.c' in 'os/arch/arm/src/s5j/Make.defs'
=> Fix: Remove duplicate entry in 'os/arch/arm/src/s5j/Make.defs'

apps/system/netdb/netdb_main.c
1. if netdb calls exit() then tash will be destroyed. so I call 'return ' instead of calling exit()
2. usage is not correct. even though I turn off gethostbyaddr it shows address options
=> fix netdb bug

apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
After pcm_close, set the g_pcm variable to null
=> set null for audio_utc

apps/examples/websocket/websocket_main.c
1) websocket_main() allocates memory for input
2) calls websocket_client() api and passes input as argument
3) websocket_client returns without freeing the input due to error cases
4) websocket_main does not handle this case due to merge commit id #667
Fixed the same in websocket_client to release the memory for input
=> Fix the memory leak caused due to merge#667 in websocket_main

lib/libc/Kconfig
* LIBC_FLOATINGPOINT option enables printing float point in printf,
and the implementation of it depends on libm functions.
=> lib/libc/Kconfig: make FLOATINGPOINT dependent on LIBM support

build/configs/sidk_s5jt200/README.md, build/configs/sidk_s5jt200/tools/openocd/partition_gen.sh, build/configs/sidk_s5jt200/tools/openocd/s5jt200_silicon_evt0_fusing_flash_all.cfg, os/arch/arm/src/sidk_s5jt200/Kconfig, os/arch/arm/src/sidk_s5jt200/src/s5jt200_tash.c
Changes:
1. Create rom device using ftl mtd instead of smart mtd
2. Removed SIDK_S5JT200_AUTOMOUNT_ROMFS_DEVNAME config,
and devname is dynamically composed.
3. Modified partition and openocd script accordingly
=> sidk_s5t200 : create rom device using ftl mtd

apps/examples/nettest/nettest.c, external/netutils/netlib_getipv4addr.c
1) Add an interface name in command line to get an allocated ip address from system
2) Modify an usage because old version is difficult to understand
3) Bug fix in netlib_getipv4addr: NET_LWIP should not be used in netlib
=> apps:nettest modify multicast test in nettest

apps/examples/testcase/le_tc/network/Kconfig, apps/examples/testcase/le_tc/network/Make.defs, apps/examples/testcase/le_tc/network/network_tc_main.c, os/net/netdev/Make.defs, os/net/utils/Make.defs
This commit is for increasing code coverage.
1) add UTC to test dup() which duplicate a socket descriptor
2) modify make.defs because netdev_* files are not currently used.
=> code coverage: add utc to network tc and change make.defs not to build unused network files now.

apps/examples/testcase/le_tc/kernel/tc_libc_spawn.c
This patch adds TC's for code coverage of the following API's:
posix_spawn_file_actions_adddup2()
It also covers left over cases in the following test API's:
tc_libc_spawn_posix_spawn_file_actions_dump()
tc_libc_spawn_posix_spawnattr_dump()
=> libc/spawn: Add test case for spawn API's

apps/examples/testcase/le_tc/network/Kconfig, apps/examples/testcase/le_tc/network/Make.defs, apps/examples/testcase/le_tc/network/network_tc_main.c
This reverts commit 43f0771693275fe3ea141a5c0869c6da111e21a2.
Missed a main file for this commit. This will be merged including that file later.
=> Revert "net:tc add dup testcases"

build/configs/artik053/audio/Make.defs, build/configs/artik053/extra/Make.defs, build/configs/artik053/hello/Make.defs, build/configs/artik053/iotivity/Make.defs, build/configs/artik053/iotjs/Make.defs, build/configs/artik053/kernel_sample/Make.defs, build/configs/artik053/minimal/Make.defs, build/configs/artik053/nettest/Make.defs, build/configs/artik053/tash/Make.defs, build/configs/artik053/tc/Make.defs, build/configs/artik053/typical/Make.defs, build/configs/artik053/wifi_test/Make.defs, build/configs/sidk_s5jt200/hello/Make.defs, build/configs/sidk_s5jt200/hello_with_tash/Make.defs, build/configs/sidk_s5jt200/kernel_sample/Make.defs, build/configs/sidk_s5jt200/sidk_tash_aws/Make.defs, build/configs/sidk_s5jt200/sidk_tash_wlan/Make.defs, build/configs/sidk_s5jt200/tc/Make.defs
When Tizen RT is building in windows, different ARCH(XX)INCLUDESs are used.
But including framework and external folders are missing. Those for Linux
were added already.
=> configs/artik053,sidk_s5jt200: modify ARCH(XX)INCLUDES for windows

build/configs/qemu/tash_16m/Make.defs, build/configs/qemu/tash_64k/Make.defs, build/configs/qemu/tc_16m/Make.defs, build/configs/qemu/tc_64k/Make.defs
That should be added to use external's APIs for network protocols.
=> qemu/configs: add external/include folder path at ARCH(XX)INCLUDES

framework/src/arastorage/index_bplustree.c, framework/src/arastorage/index_manager.c
Two svace warnings have been fixed in index_manager.c and index_bplustree.c
=> [Arastorage] Handling svace warnings 

lib/libc/netdb/lib_dnscache.c
Uninitialized data is read from local variable 'inlen' at lib_dnscache.c:295.
The variable is uninitialized at lib_dnscache.c:295.
=> Initialize inlen to 0 in lib_dnscache.c

lib/libc/stdio/lib_dtoa.c
Pointer 'rv' returned from function 'malloc' at lib_dtoa.c:162 may be null,
and it is dereferenced at lib_dtoa.c:163.
=> Add NULL check in Balloc

os/arch/arm/src/s5j/s5j_i2c.c
Assign I/O error when i2c fails to read bytes, and jump to fail laber with -EIO return value.
Signed-off-by: Jihoon Park <jh6186.park@samsung.com>
=> Fix i2c return value when it fails to read

framework/src/arastorage/index_manager.c
Corrected num of bytes being passed to memset in index_manager.c at line 480
Earlier size of pointer struct was being passed, now the value to which row is malloc'd is sent to memset.
=> [Arastorage] Svace warning fix

os/net/lwip/src/api/api_msg.c
Pointer 'conn' which was dereferenced at api_msg.c:330 is compared to NULL value at api_msg.c:336.
If conn is NULL, ERR_ARG will be returned.
=> Add NULL check in send_tcp function

external/iotjs/deps/libtuv/include/uv-tizenrt.h, os/include/uio.h
There are same structure definition, so integrated.
=> Integrate iovec structure between uv-tizenrt.h and uio.h

apps/system/iperf/iperf_api.c, framework/src/iotbus/iotbus_gpio.c, framework/src/iotbus/iotbus_i2c.c, framework/src/iotbus/iotbus_spi.c, framework/src/iotbus/iotbus_uart.c, os/net/lwip/src/core/pbuf.c
1. Checked return value of malloc and exited function gracefully if malloc failed
2. used LWIP_ASSERT for null pointer check
3. check for negative values before copying to unsigned variable.
=> Fixed SVACE warnings for IotBus, Lwip and iperf_api

framework/src/st_things/things_stack/src/common/framework/things_req_handler.c, framework/src/st_things/things_stack/src/stack/things_stack.c
- Add things_free() of thread arguments to things_abort() to avoid memory leak
- Delete useless comments in trigger_abort_request()
=> fix memory leak in things_abort()

framework/src/st_things/st_things_request_handler.c, framework/src/st_things/things_stack/src/common/cloud/cloud_connector.c, framework/src/st_things/things_stack/src/common/easy-setup/easysetup_manager.c, framework/src/st_things/things_stack/src/common/easy-setup/resource_handler.c, framework/src/st_things/things_stack/src/common/framework/things_req_handler.c, framework/src/st_things/things_stack/src/common/framework/things_security_manager.c, framework/src/st_things/things_stack/src/common/utils/things_string_util.c
st_things_request_handler.c
- In error statement, make the func to return false
cloud_connector.c
- 'registerPayload' & 'loginoutPayload' are released in 'OCDoResource'
- So, add 'OCRepPayloadDestroy' to release in error state.
easysetup_manager.c
- Add check statement before close file descriptor
resource_handler.c
- change 'strncmp' which is using just for empty checking to 'strlen'
things_req_handler.c
- initialize variable before using
things_security_manager.c
- Add fclose after usage of fds.
things_string_utils.c
- Add '+1' when check string length for null character.
=> Fix svace errors

framework/src/st_things/st_things_request_handler.c, framework/src/st_things/things_stack/src/common/easy-setup/easysetup_manager.c, framework/src/st_things/things_stack/src/common/framework/things_security_manager.c
st_things_request_handler.c
- fix misspell in null check
easysetup_manager.c
- remove unreachable expression
- check negative value before close fd
things_security_manager.c
- move 'fclose(fp)' to general location
=> Fix svace error.

apps/examples/testcase/le_tc/kernel/tc_libc_math.c, os/arch/arm/src/s5j/s5j_boot.c, os/drivers/wireless/scsc/misc/utils_misc.h, os/fs/smartfs/smartfs_utils.c
./os/fs/smartfs/smartfs_utils.c:3429: ERROR: [SPC_M_OPR] space prohibited before that ':' (ctx:WxE)
./os/fs/smartfs/smartfs_utils.c:3433: ERROR: [SPC_M_OPR] space prohibited before that ':' (ctx:WxE)
./os/arch/arm/src/s5j/s5j_boot.c:113: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:ExV)
./apps/examples/testcase/le_tc/kernel/tc_libc_math.c:1931: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
./os/drivers/wireless/scsc/misc/utils_misc.h:255: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
=> Fix coding rule error

os/include/sys/types.h
IoT.js uses this type, so remove iotivity ifdef condition
=> Move typedef unsigned long __kernel_size_t out of ifdef condition

external/iotjs/src/platform/tizenrt/iotjs_main.c
SVACE error fix (160314)
IoT.js-DCO-1.0-Signed-off-by: Haesik, Jun haesik.jun@samsung.com
=> SVACE error fix (160314) - missing initial values on iotjs_main.c 

external/iotjs/src/modules/iotjs_module_dns.c
Use of vulnerable function 'strcpy' at iotjs_module_dns.c
It's changed to 'strncpy'
IoT.js-DCO-1.0-Signed-off-by: Haesik, Jun haesik.jun@samsung.com
=> Fix svace error (160318) - use of vulnerable function

external/iotjs/deps/libtuv/src/unix/fs.c
=> Fix SVACE defect in IoT.js (fs.scandir)

framework/src/st_things/things_stack/src/common/cloud/cloud_manager.c, framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
- cloud_manager.c
. Expression 'ES_STATE_INIT <= es_state' is always true , which may be caused by a logical error
- things_data_manager.c
. Return value of a function 'cJSON_GetObjectItem' is dereferenced at things_data_manager.c:991 without checking, but it is usually checked for this function (79/83).
=> Fix svace issue in st_things

external/iotjs/deps/libtuv/src/unix/fs.c
Incorrectly located error handling code (introduced by #744) is fixed.
(The allocation error check should be after the allocation.)
=> Fix IoT.js fs.scandir

apps/shell/tash_main.c
* usleep() is not available if signals are disabled.
=> apps/shell: hide usleep call if signals are disabled

build/configs/artik053/artik053_download.sh, build/configs/artik053/tools/openocd/partition_map.cfg
partition_map.cfg did source romfs_flashing.cfg
But romfs_flashing.cfg is removed after "make download"
Sometimes cfg file are used without "make download"
So set romfs_partition_enable using openocd command
And romfs_partition_enable will be 0 if romfs_partition_enable doesn't exist
=> Set romfs_partition_enable using command instead of romfs_flashing.cfg

framework/src/iotbus/iotbus_pwm.c, os/include/tinyara/pwm.h
- the range of pulse width should be 0 - 65535
- The max value should be b16ONE - 1 and the half value should be b16HALF.
- The rounding conversion satisfies above 2 condtions.
=> pwm: fix issues on range and decimal point

apps/examples/testcase/ta_tc/device_management/itc/itc_dm_main.c, apps/examples/testcase/ta_tc/device_management/utc/utc_dm_main.c
Callback functions for linkupEvent had multiple definitions for utc and itc.
These functions were renamed.
=> Fixed errors when building for both DM utc and itc

os/fs/smartfs/Kconfig
* Implementation of sector recovery functionality requires mtd/smart.c
routines, which compilation controlled by MTD_SMART.
=> fs/smartfs/Kconfig: make SMARTFS_SECTOR_RECOVERY dependent on MTD_SMART

os/logm/Kconfig
* logm_task uses usleep() call, which implementation
relies on signals. So when they are disabled, usleep()
routine is not compiled.
=> logm/Kconfig: make LOGM dependent on !DISABLE_SIGNALS

build/configs/artik053/artik053_download.sh, build/configs/sidk_s5jt200/sidk_s5jt200_download.sh
If openocd return non-zero exit code, download script exits with exit code 1
=> Return exit code when openocd command failed in download script

os/arch/arm/src/sidk_s5jt200/src/s5jt200_led.c, os/logm/logm_start.c, os/net/lwip/sys/arch/sys_arch.c
1. use kernel_thread instead of task_create in kernel side, logm, arch and net
2. refactoring of s5jt200 led
=> use kernel_thread for kernel thread and refactor s5jt200 led

framework/src/iotbus/iotbus_uart.c
A break statement was missing inside switch case. no break statement,
hence stopbits 2 always failed.
Change-Id: Ib2b53ef73e752821f1b077700606fcb45d403597
=> iotbus/uart: add missing break

os/arch/arm/src/s5j/s5j_adc.c
An unnecessary warning log was output. The debug level was modified to
prevent output by default.
Change-Id: If5a70358171450338699997de5a2b070c92566d5
=> s5j/adc: change interrupt debug level

external/libcoap/Makefile
mbedtls and libcoap cause a conflict because there are object files which are same name
To fix it I added prefix at object files
=> protocol:libcoap Fix build error

build/configs/artik053/README.md
If you have an ARTIK 0 Starter Kit board, you can refer to PinOut with
this document.
Change-Id: Iaee1b9ebfab25c8def33e215285847d2716bfa62
=> build: add starter kit pinout figure

os/arch/arm/src/s5j/s5j_clock.c
An SPI contains an internal 1/2 clock divider. Configure the SCLK_SPI
value to the double of an SPI operating clock frequency.
Change-Id: I8efd88dec2166ae5241f13a08d2c18438d26bb9b
=> s5j/clk: modify SPI clk rate

framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/wifi_manager.c
- Hung up during linkdown because the linkdown handler did not consider WIFI_MODE_CHANGING state.
- Add wifi manager modes for linkup&down handlers to know previous and next modes.
- Edit functions of wifi init, deinit and set mode which trigger linkup&down handlers.
- Re-fix for the previous quick fix(commit 111d0b10430601ea4653b2be3530b94dc9848ffd)
=> Fix the WiFi linkdown hang up issue

framework/src/st_things/things_stack/src/common/framework/inc/things_data_manager.h, framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
Unused functions are deleted to increase code coverage for RC3.
- update_and_save_device_info()
- dm_register_user_define_device_id()
- dm_get_num_of_children()
- dm_get_resource_uri()
- dm_update_device_iInfo_list()
=> Delete dead code related to things_data_manager

apps/examples/testcase/le_tc/filesystem/fs_main.c
The name of all testcases in le_tc has naming rule, tc_[module]_[function]
So I need to change all testcases for fs, stdio in fs_main.c to apply it
=> testcase/fs : change the name of all filesystem TCs to tc_[module]_[function]

external/ftpc/ftpc_utils.c
Function ftpc_stripcrlf removes newline characters from string can go before data buffer if the buffer is completely filled with newline characters(\r or \n).
This can lead to memory corruption but is not easily exploitable, so the risk is reduced.
=> Memory corruption security issue fixed for FTP client

external/ftpc/ftpc_transfer.c
Function ftp_pasvmode that parses FTP server response to PASV command goes outside data buffer - ptr is increased and checked only using !isdigit function.
This can lead to memory disclosure / corruption but is not easily exploitable, so the risk is reduced. In FTP client code input from server is written correctly to staticaly allocated buffer and only reading after end of buffer is possible.
=> Fixed stack based memory disclosure in FTP client

apps/examples/testcase/le_tc/filesystem/fs_main.c
[IDT_M_TAB] please, no space before tabs
=> testcase/filesystem : fix coding rule error - remove unnecessary space

apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
cleanup function cleans all comopents like relations used in these TCs.
Some files used before in arastorage operations and so on may be removed.
So we call cleanup function before running arastorage TCs to verify cleaning all existent things.
=> testcase/arastorage: call cleanup function at the beginning arastorage TCs to verify cleaning all undeleted resources

apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
cleanup function is called before and after arastorage TCs run to verify cleaning related resources
We don't need to check whether result value of function used here is valid or not.
Because this function is not tc and is used internally.
=> testcase/arastorage: delete checking result value in cleanup function.

framework/src/st_things/things_stack/src/common/utils/things_network.c, framework/src/st_things/things_stack/src/common/utils/things_ping.c, framework/src/st_things/things_stack/src/stack/things_stack.c
- Assert often occur during the reset process as the TCP receive thread is trying to use resources of the ping thread already terminated.
- The TCP receive thread does not need to call the session state callback to terminate the ping thread during reset because the reset loop thread will unregister that callback.
=> Fix assert during things reset

apps/examples/testcase/le_tc/ttrace/Kconfig
Add select config in Kconfig for testcase of T-trace.
Enable CONFIG_TTRACE when CONFIG_EXAMPLES_TESTCASE_TTRACE is turned on.
=> testcase/ttrace: add select condition for using ttrace in Kconfig

framework/src/wifi_manager/wifi_manager.c
Send network events to Iotivity only when the IP address is changed on the device.
Wifi manager sends network event even though sta leaves on SoftAP mode.
In above case, The IP address on the device is still ok, so it doesn't need to send.
=> net:wifimanager fix sending net events to iotivity from wifi manager

apps/examples/testcase/le_tc/filesystem/fs_main.c
This patch fixes wrong initialization in setvbuf and remove API testcases.
=> (libc/stdio): Fix wrong initialization in FS TC.

apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c
Fix systemio itc_gpio.c file, change gpio pin 12 to 41
As discussed with developer (Mr. Sangwon An), GPIO pin number is 12. but need to use 41 in sw code. it related to HW board(artik053).
For more information "https://developer.artik.io/documentation/artik-05x/getting-started/board-ref.html"
=> Fix systemio itc_gpio.c file, change gpio pin 12 to 41

apps/examples/testcase/ta_tc/systemio/itc/itc_i2c.c
apps/examples/testcase/ta_tc/systemio/itc : 
filename : itc_i2c.c
testcase : fix itc_iotbus_i2c_write_read_p
Fix return condition of API "iotbus_i2c_read" as "greater than" IOTBUS_ERROR_NONE from earlier condition of "equal" to IOTBUS_ERROR_NONE, referred UTC
=> apps/examples/testcase/ta_tc/systemio/itc : fix itc_iotbus_i2c_write_read_p

apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c, apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
In audio utc/itc, readi positive tc gave an assert failure. The failure was due to the last pcm_readi call returning a negative value. The negative value was passed to write function which led to assert failure.
Now an if block has been added which checks the return value of pcm_readi before passing it to the write function.
=> ta_tc/audio/{utc,itc} : Removing assert failure in audio TCs

apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c, apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c, framework/include/tinyalsa/tinyalsa.h, framework/src/tinyalsa/tinyalsa.c
pcm_set_config has been removed from tinyalsa include file. The tcs in utc and itc which tested pcm_set_config have been removed. Calls to pcm_set_config outside of tinyalsa have also been removed .pcm_set_config has been made a static function so that it can it is called only from tinyalsa.c file.
=> framework/tinyalsa : Removing pcm_set_config as public API

framework/src/iotbus/iotbus_pwm.c
- change type of divisor to get the result as float value.
=> iotbus: bug fix in pwm

apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c
[SPC_M_OPR] spaces required around that '=' (ctx:VxW)
=> testcase/mqtt_itc : fix coding rule error - space is needed before '='

external/netutils/netlib_parsehttpurl.c
netlib_parsehttpurl() should be returned when error is detected
=> net:netlib fix vulerability while parsing malicious URLs

framework/include/dm/dm_connectivity.h, framework/include/dm/dm_lwm2m.h, framework/include/network/mqtt/mqtt_api.h
1. Add include path for each api 
- if not, we cannot know which header we should include for using that api
2. Add missing param name for each api 
- argument name is needed after param[in] or param[out]
=> doxygen : Add include path and missing param name in framework

external/wakaama/core/data.c, external/wakaama/core/internals.h, external/wakaama/core/liblwm2m.c, external/wakaama/core/objects.c, external/wakaama/core/observe.c, external/wakaama/core/utils.c, external/wakaama/examples/server/lwm2mserver.c
Wakaama in the version currently used by TizenRT (seems to be from around March/April) is vulnerable to several security issues, which were since fixed in the upstream version at https://github.com/eclipse/wakaama.
Reference to the original fixes are given below:
1. eclipse/wakaama#319 (fix unknown, but likely eclipse/wakaama@8037174)
2. eclipse/wakaama#320
3. eclipse/wakaama#268
4. eclipse/wakaama#301
=> Merge security-related fixes from eclipse wakaama Github to TizenRT

external/wpa_supplicant/src/utils/common.c, external/wpa_supplicant/src/utils/common.h, external/wpa_supplicant/src/wps/wps_attr_process.c, external/wpa_supplicant/wpa_supplicant/config.c
Title : psk configuration parameter update allowing arbitrary data to be written
To prevent written arbitrary data on wpa_supplicant configuration file, requesting review.
Test Results
- Hardware : ARTIK-053
- Access Point : iptime  
1) Wi-Fi Join Test : OK
- wpa-tkip, wpa-aes, wpa-mixed, wpa2-tkip, wpa2-aes, wpa2-mixed, wep, open
2) Wi-Fi Join / leave test : OK
=> wpa_supplicant : security vulnerability patch (http://w1.fi/security/2016-1/)

external/ftpc/ftpc_utils.c
Function ftpc_dequote that converts quoted hexadecimal constants to binary values goes outside input data buffer -str pointer is checked, while str[1] and str[2] are read.
while parsing the server response end of string should be checked
=> Fix buffer overflow in FTP client

external/webserver/http_string_util.c
- Remove the code for checking the length of the http header. The whole unseparated http header can be longer than the max key length.
- Re-fix of commit eda61d6f7b0b1ed4a17a62206ddf94d6fc8069d1
=> Fix a http header parsing function in webserver

os/include/stdio.h
if not, we cannot know which header we should include for using 'puts' api
=> doxygen : Add include path in stdio.h

apps/examples/testcase/ta_tc/device_management/itc/Make.defs, apps/examples/testcase/ta_tc/device_management/itc/itc_dm_lwm2m.c, apps/examples/testcase/ta_tc/device_management/utc/Make.defs, apps/examples/testcase/ta_tc/device_management/utc/utc_dm_lwm2m.c, framework/Makefile, framework/src/dm/dm_lwm2m.c
- Edit the compile option not to find the header file directory and use the original one as other framework modules do.
=> Edit makefiles of framework and tc for the path inclusion of DM API header

os/net/lwip/src/core/tcp_in.c
Ignore TCP_RST if lwIP stack recevie it with invalid seqnum
You can check the detailed at https://www.cvedetails.com/cve/CVE-2004-0230/
=> net:lwip fix tcp spoofing attack at lwIP

os/net/lwip/src/core/snmp/mib_structs.c, os/net/lwip/src/core/snmp/msg_in.c
1) build error fix 
- Add <net/lwip/debug.h> in snmp to prevent a build error
2) assert due to config
- fix SNMP assert when config value is not match to the received.
=> net:lwip fix snmp issues

os/include/sys/mount.h, os/include/sys/select.h
. Add include path
- If not, user can't know which header file should be included to use these APIs
. Add parameter name
- each parameter name is needed for param[in/out] to follow doxygen rule
. Add missing brief to POSIX APIs and return
=> doxygen : add include path, missing brief, parameters and return for fs APIs in include/sys

os/tools/csvparser.c
The g_parm variable which it is a buffer to treat system call parameters
has a maximum value, 16 as a parameter field. But in parse_csvline function,
a maximum value is not checking so that it can cause memory corruption.
Because of above reason, it should have a checking code for maximum.
But, parser can't make a decision whether it is a valid or not. Let's exit
with error.
=> tools/csvparser: add a limitation of parsing parameters from syscall csv

external/webclient/webclient.c, external/webserver/http_client.c
- http_parse_message function doesn't check an returned value of an error, it can causes proceed with unproper values.
- Initialization of buffers is needed for every loop not to be filled with the previous data.
=> Add an error handling code and an initialization function in webserver&client

framework/include/st_things/st_things.h
Remove two st_things APIs in doxygen. It may be necessary to implement in a future, I only removed in doxygen list.
1. st_things_register_pin_handling_cb : Among the boards supported by TizenRT, there is no board providing pin based comfirmation. So TizenRT does not support this API.
2. st_things_deinitialize : It has not been implemented.
=> Revise doxygen comment to remove unused st_things APIs

external/wakaama/core/er-coap-13/er-coap-13.c
Coap parsing needs to check for buffer boundary violation, especially when parsing option bytes. This commit enforces a strong check in the coap_parse_message and coap_merge_multi_option functions to mitigate such potential DoS attacks.
=> Fix coap parsing for wakaama in coap_parse_message and coap_merge_multi_option functions

external/xmlrpc/xmlparser.c
if member in parsebuf_s has negative value then xmlrpc refers buf with index -1
so I add compare logic in xmlrpc_getelement()
=> external:xmlrpc fix xmlrpc refer invalid memory area

external/mdns/mdns.c
it is more safe to check p is within valid memory before access to memory
=> net/mdns: fix that mdns refers invalid memory

lib/libc/netdb/lib_getaddrinfo.c
This file includes some codes got from open source under the terms of BSD license.
So copyright and license in original file should be kept to fulfill BSD license oligations.
=> libc/netdb: add missing original copyright and license in lib_getaddrinfo.c

external/wpa_supplicant/src/ap/ap_drv_ops.c, external/wpa_supplicant/src/ap/ap_drv_ops.h, external/wpa_supplicant/src/ap/ieee802_11.c, external/wpa_supplicant/src/ap/sta_info.c, external/wpa_supplicant/src/ap/sta_info.h, external/wpa_supplicant/src/ap/wpa_auth.c, external/wpa_supplicant/src/ap/wpa_auth.h, external/wpa_supplicant/src/ap/wpa_auth_ft.c, external/wpa_supplicant/src/ap/wpa_auth_i.h, external/wpa_supplicant/src/common/qca-vendor.h, external/wpa_supplicant/src/common/wpa_common.h, external/wpa_supplicant/src/drivers/driver.h, external/wpa_supplicant/src/drivers/driver_nl80211.c, external/wpa_supplicant/src/drivers/driver_nl80211_capa.c, external/wpa_supplicant/src/rsn_supp/tdls.c, external/wpa_supplicant/src/rsn_supp/wpa.c, external/wpa_supplicant/src/rsn_supp/wpa.h, external/wpa_supplicant/src/rsn_supp/wpa_ft.c, external/wpa_supplicant/src/rsn_supp/wpa_i.h, external/wpa_supplicant/wpa_supplicant/config.c, external/wpa_supplicant/wpa_supplicant/config.h, external/wpa_supplicant/wpa_supplicant/config_file.c, external/wpa_supplicant/wpa_supplicant/ctrl_iface.c, external/wpa_supplicant/wpa_supplicant/events.c, external/wpa_supplicant/wpa_supplicant/wnm_sta.c, external/wpa_supplicant/wpa_supplicant/wpa_supplicant_i.h, external/wpa_supplicant/wpa_supplicant/wpas_glue.c
It applies KRACK patch set from Tizen patch.
It contains KRACK patch and 2.6 version up patch for adapting a KRACK patch
=> wifi/wpa_suuplicant: patch for wpa_supplicant security issue called KRACK

os/tools/csvparser.c
Fix build error caused by wrong typo of variable `nparms` from the commit https://github.com/Samsung/TizenRT/commit/819fa0bdfb525199d7f587fade7f5af1311d2827
=> tools/csvparser.c: Fix build error

external/wpa_supplicant/src/utils/os_tinyara.c
Comparison should be performed on return value of call to chdir.
=> external/wpa_supplicant/src/utils/os_tinyara.c: fix misplaced parentheses

os/arch/arm/src/sidk_s5jt200/src/s5jt200_led.c
the build target sidk_s5jt200 failed to build due to changes in kernel_thread() signature.
This patch corrects the build error.
=> sidk build fix

framework/include/arastorage/arastorage.h
Add missing filepath and description in doxygen for arastorage.h to show this in File List of API page
=> arastorage : add missing filepath and description to doxygen for arastorage.h

os/arch/arm/src/artik053/include/artik053_alc5658_i2c.h, os/arch/arm/src/artik053/src/artik053_alc5658_i2c.c
1. Add a conditional on alc5658 header
For every header file, checking a conditional is needed to prevent
duplicated including header file. That is missed in artik053_alc5658_i2c.h.
2. refactor alc5658 files
for coding rule and readability
=> arch/artik053: tidy up on alc5658

framework/include/tinyalsa/tinyalsa.h
the "@brief" in pcm config and pcm mask is missing
and is not displayed of doxygen.
=> add description for audio framework doxygen

framework/include/network/mqtt/mqtt_api.h
add a brief section in mqtt for doxygen.
=> framework/mqtt: add a missed description of doxygen in mqtt

apps/examples/testcase/le_tc/filesystem/fs_main.c
This patch covers left over use cases for API's namely:
memoutstream, meminstream, memsistream, memsostream,
rawinstream, rawoutstream, rawsistream, rawsostream,
stdinstream, stdoutstream, stdsistream, stdsostream
nullinstream, nulloutstream, zeroinstream
=> Codecoverage(libc/stdio): Modify TC's for few API's in stdio

framework/include/dm/dm_connectivity.h, framework/include/dm/dm_lwm2m.h
Add description in the DM LWM2M and connectivity header files, to describe data structures.
=> Add description for DM data structures

os/kernel/task/task_exithook.c
task_exithook.c fails to link if signals are disabled because was unconditionally trying to send the SIGCHLD signal to the parent in certain configurations.
commit from Nuttx - 3cd41b0
=> kernel/task : Add ifndef condition for task_sigchild

docs/Porting_Guide.md
Porting Guide for kernel, file system and network. It shows what is our policy
and how to confirm porting.
=> Docs: Add Porting Guide

os/fs/inode/inode.h, os/fs/procfs/fs_procfs.c, os/fs/romfs/fs_romfs.c, os/fs/romfs/fs_romfs.h, os/fs/smartfs/smartfs_smart.c, os/fs/vfs/Make.defs, os/fs/vfs/fs_fstat.c, os/fs/vfs/fs_fstatfs.c, os/fs/vfs/fs_stat.c, os/include/tinyara/fs/fs.h
Somewhat tested on Artik053.
Note: only romfs and smartfs filesystems are covered.
=> fstat & fstatfs for ROMFS and SMARTFS backported from nuttx

apps/examples/fs_helper/ramfs_test.c, os/logm/logm_process.c
In this scenario,  if realloc fails, then the original memory allocation exists, but is leaked as it is no longer referred. So you need to keep a handle on the original allocation until you have verified that the new allocation is valid.
=> Fix Memory Issues and Optimizations in Code Usage 

os/fs/vfs/fs_stat.c
Previous PR contains a bug - the buffer pointer is cleared (along some adjacent memory), and later on some value is written into location pointed by resulting NULL.
Reproduction:
> TASH>>ls /dev
Crashes
Tested on artik053.
=> Bug fix: inode_stat mishandled the buffer, resulting in NULL dereference

os/fs/smartfs/smartfs_smart.c
These values also should be assigned when entry is root.
=> fs/smartfs: assign stat values for root in smartfs_stat_common

os/arch/arm/src/s5j/s5j_i2s.c
i2s receive and transmit buffer protection semaphore is inited with
incorrect value which is modified to 0.
=> Init i2s buffer protection semaphore with 0.

os/drivers/rwbuffer.c
* In 'rwb_read' function there are two ways of execution flow:
(1) either we read data from readahead cache,
(2) or we read data directly from device. The (1) way takes place
when option CONFIG_DRVR_READAHEAD is enabled and when the readahead
buffer was configured to store non-zero amount of blocks. Otherwise
the (2) way executes.
=> drivers/rwbuffer: fix rwb_read and rwb_write logic

os/Kconfig.debug, os/mm/mm_heap/mm_free.c
When CONFIG_DEBUG flag is enabled, This patch address to detect following 4
different bugs present in sw logic
1) Attempt to free a NULL pointer
2) Attempt to free an Unallocated pointer
3) Attempt to free an abruptly initialized pointer (Security exploitation)
without actually allocating it
4) Attempt to free an already released pointer ( double free detection )
Reference test code for each of the above case is as below
1)	int *ptr = NULL; free(ptr);
2)	int *ptr; free(ptr);
3)	int *ptr = (int*)0x20102020; free(ptr);
4)	int *ptr;
ptr = malloc(100);
free(ptr);
/* Since ptr is not set to NULL after free, following code executes */
if (ptr) {
printf("Freeing the released pointer\n");
free(ptr);
}
=> Add debug code to detect double freeing the pointer

apps/examples/testcase/ta_tc/systemio/utc/utc_internal.h, apps/examples/testcase/ta_tc/systemio/utc/utc_sysio_main.c
Remove unnecessary codes like duplicated definitions, commented codes,
unused function and codes.
=> testcase/systemio: clean up systemio utc

framework/src/dm/Kconfig
- Add dependency on LIBC_NETDB because LIBC_NETDB have to be on when LWM2M_WAKAAMA is selected.
=> framework/dm: fix Kconfig warning

docs/Porting_Guide.md
Add link to "Policy & Caution" in Porting_Guide.md
=> Fix missing link to "Policy & Caution" in Porting_Guide.md

framework/include/tinyalsa/tinyalsa.h, framework/src/tinyalsa/tinyalsa.c
I have added the pcm_drain and pcm_drop API's and fixed few issues with readi API.
Details of all changes done in this PR:
- Added pcm_drop() API
- Added pcm_drain() API
- Modified pcm_readi() API logic to accept any value of frame_count (to allow user to read less data than buffer size)
- Fixed incorrect logic in pcm_start and pcm_stop API's
- Fixed coding rule errors in source file (like comments, variable names, etc..)
=> <Tinyalsa> Add pcm_drain and pcm_drop API and fix other issues

build/configs/artik053/tools/openocd/partition_gen.sh
If CONFIG_ARTIK053_FLASH_PART_LIST or CONFIG_ARTIK053_FLASH_PART_NAME are unset, they will be set as default value
=> Set default partition info in partition_gen.sh

docs/Porting_Guide.md
Setting multi-heap is a part of porting guide. Let's add it.
=> docs: add a link on porting guide for how to use multiple memory as a heap

lib/libc/stdio/lib_tempnam.c
This patch modifies tempnam() API to check for NULL case which was not handled.
=> (libc/stdio): Handle NULL case input in tempnam() API

apps/examples/testcase/le_tc/filesystem/fs_main.c
This patch covers stdio API's namely:
tempnam()
tmpnam()
=> Codecoverage(libc/stdio): Add TC for API's tempnam() & tmpnam()

README.md, docs/HowtoInstallKconfigFrontend.md
That is not a mandatory always. Someone who is not a developer will not
use menuconfig.
=> docs: add a new documentation for how to install kconfig frontend

os/drivers/audio/alc5658.c, os/drivers/audio/alc5658reg.h, os/drivers/audio/alc5658scripts.h
This is a patch that adds the information in the ALC5658 codec register.
And I reset the naming with the keywords presented in the datasheet.
Similar to other driver register settings, I changed from 'enum' to
'define'.
=> alc5658: modify alc5658 codec register

apps/examples/sensorbd_demo/examples/gpio_ledonoff.c, apps/examples/sensorbd_demo/examples/gpio_loopback.c, apps/examples/sensorbd_demo/examples/gpio_starterled.c, apps/examples/sensorbd_demo/examples/pwm_led.c
examples/gpio_starterled.c:66: (error) Resource leak: fd
examples/gpio_starterled.c:83: (error) Resource leak: fd
examples/gpio_loopback.c:77: (error) Resource leak: fd
examples/gpio_loopback.c:98: (error) Resource leak: fd
examples/pwm_led.c:73: (error) Resource leak: fd1
examples/pwm_led.c:78: (error) Resource leak: fd2
examples/pwm_led.c:83: (error) Resource leak: fd3
examples/gpio_ledonoff.c:70: (error) Resource leak: fd
=> Fixed resource leak in examples/sensorbd_demo

tools/ramdump/ramdump_tool.c
Incase of Receiving ramdump failure or Writing ramdump failure, bin_fp is not closed.
This commit closes bin_fp before returning -1.
=> tools/ramdump: fix resource leak bin_fp

apps/examples/artik_demo/artik_demo.c
Hi,
While returning from the function -
1. Socket was not closed in few scenarios
2. client_tls was not freed
Made changes to address above issues.
=> Socket close before returning in examples/artik_demo

apps/builtin/registry/Makefile
Builtin makes tdat file to save TASH task informations, priority and stacksize.
But it doesn't delete them after using by missing codes in Makefile.
When user calls update or clean, they will be deleted.
=> apps/builtin: Modify Makefile to delete tdat file

apps/system/utils/fscmd.c, os/arch/arm/src/artik053/src/artik053_tash.c, os/arch/arm/src/sidk_s5jt200/src/s5jt200_tash.c
mksmartfs has 2 or 3 parameters depending on support for multiple root dir/mount points
If CONFIG_SMARTFS_MULTI_ROOT_DIRS is enabled, a nrootdirs parameter, the number of root dir entries is needed additionally.
And user can use mksmartfs TASH command with this value.
=> fs/smartfs: add missing dependency on support for multiple root dir/mount points to mksmartfs

external/webclient/webclient.c
urldecode.h, base64.h are located in codecs dir
=> Modify codecs header path in external/webclient

os/arch/arm/include/armv7-r/irq.h
I would like to build `IoT.js` on `artik053` with enabled `jerry-debugger`. The `CMakeLists.txt` of `JerryScript` (a dependency of IoT.js)  sets the conversion compile warning as an error with `-Werror=conversion` flag. This PR resolves the following issue:
`error: conversion to 'irqstate_t' from 'unsigned int' may alter its value [-Werror=conversion]`
=> Fix conversion warnings in `os/arch/arm/include/armv7-r/irq.h`

os/mm/mm_heap/mm_malloc.c
if input size is greater than MM_ALIGN_DOWN(MMMAX_SIZE) - SIZEOF_MM_ALLOCNODE, it can be overflow by MM_ALIGN_UP.
=> mm_heap/mm_malloc : Add bad size checking logic which checks overflow

external/dhcpc/dhcpc.c
dhcp client returns -1 when it fails to send Discover packet once. If the errno is EAGAIN, we should allow it to retry.
=> Add retry for dhcpc sendDiscover

external/include/codecs/base64.h, external/include/codecs/md5.h, external/include/codecs/urldecode.h, external/include/json/cJSON.h, external/include/netutils/ipmsfilter.h, external/include/netutils/netlib.h, external/include/protocols/dhcpc.h, external/include/protocols/dhcpd.h, external/include/protocols/discover.h, external/include/protocols/ftpc.h, external/include/protocols/ftpd.h, external/include/protocols/ntpclient.h, external/include/protocols/smtp.h, external/include/protocols/telnetd.h, external/include/protocols/tftp.h, external/include/protocols/webclient.h, external/include/protocols/websocket.h, external/include/protocols/xmlrpc.h
Those were moved from apps but they have previous path and conditionals.
Let's modify them with right path information.
=> external: Modify paths and conditionals on headers of include folder

README.md
Sub-title was changed to "Supported Board / Emulator" but link is not.
Because of that, link is not working. Fix it to current name.
=> README: Fix not working a link to "supported board and emulator"

os/include/sched.h, os/kernel/Kconfig, os/kernel/sched/sched_addreadytorun.c, os/kernel/sched/sched_mergepending.c, os/kernel/sched/sched_removereadytorun.c, os/kernel/sched/sched_yield.c, os/kernel/task/task_activate.c, os/kernel/task/task_terminate.c
sched_note_XXX are functions for monitoring system performance.
Implementations of these functions don't exist and we don't need to use it because ttrace has similar functionality in TizenRT.
So remove all remained things related to these functions.
=> sched_note: remove remained codes related to non-existent functions for monitoring system

os/arch/arm/src/s5j/s5j_pwm.c
In 's5j_pwminitialize' function, if timer value is invalid or pwm value is NULL,
then it calls 's5j_pwm_reset' with NULL as a pwm dev parameter.
This case leads to NULL pointer dereference in 's5j_pwm_reset' function.
So NULL check is added in 's5j_pwminitialize' before calling 's5j_pwm_reset'.
=> s5j/s5j_pwm.c: Fix NULL pointer dereference

apps/examples/testcase/ta_tc/device_management/itc/Kconfig
DM_WIFI, DM_AP_SSID, DM_AP_PASS and DM_AP_SECURITY should be set
in DM of framework, not testcase. Due to this, these are listed in
in-correct locations.
```
CONFIG_DM_AP_SSID="TizenRT1"
CONFIG_DM_AP_PASS="tizenrt_tdc2017"
CONFIG_DM_AP_SECURITY="wpa2_aes"
#
#
CONFIG_DM=y
CONFIG_DM_WIFI=y
```
=> testcase/dm/itc: remove duplicated configs for wifi

build/configs/artik05x/artik05x_download.sh
Correcting Tizenrt binary which is passed to codesigner signing script during flashing image to secure versions of artik05x series boards
=> build/configs/artik05x: Correcting tizenrt image path in artik05x_download.sh 

os/Kconfig.debug, os/kernel/Kconfig, os/logm/Kconfig
1. PTHREAD_STACK_MIN and PTHREAD_STACK_DEFAULT
They should not be shown when DISABLE_PTHREAD is enabled.
Let's make a dependancy as "depends on !DISABLE_PTHREAD".
2. SCHED_WORKQUEUE and SCHED_WORKQUEUE_SORTING
SORTING config is meaningful when one of kernel workqueues is enabled.
Let's make a dependancy as "depends on SCHED_WORKQUEUE"
Remove unncessary comments and duplicated a dependancy, !DISABLE_SIGNAL.
3. LOGM
When DISABLE_SIGNAL is enabled, we can't enable LOGM. But it shows only
menu without config. Let's move a dependancy from config to menu.
When DISABLE_SIGNAL is enabled, it will not show meanless title.
=> kernel, logm: modify dependancies of configs

os/arch/arm/src/armv7-m/up_assert.c, os/arch/arm/src/armv7-r/arm_assert.c
If CONFIG_ARCH_STACKDUMP is defined, CONFIG_DEBUG will be defined.
So " || defined(CONFIG_ARCH_STACKDUMP)" is not needed.
And if CONFIG_DEBUG is off, lldbg will be replaced with an empty line.
In conclusion, CONFIG_TASK_NAME_SIZE > 0 is enough.
=> Remove unnessary CONFIG_PRINT_TASKNAME

os/kernel/Kconfig
1. SCHED_WORKQUEUE will be enabled when HPWORK or LPWORK is enabled.
So, it should have 'n' as a default value.
2. When any workqueue is not enabled, we don't need to remain title.
And When DISABLE_SIGNALS is enabled, wqueue should be disabled.
Let's move a dependancy with DISABLE_SIGNALS to menu.
=> kernel/wqueue: modify a default value and dependancy on Kconfig

apps/examples/wifi_manager_sample/wm_test.c, framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/wifi_manager.c
currently, sta_connected user callback in wifi_manager does not distinguish between success and fail event for station join. By parameterizing the callback, we make it possible to distinguish.
=> parameterize the sta_connected user callback in wifi_manager

os/arch/arm/src/armv7-m/up_assert.c, os/arch/arm/src/armv7-r/arm_assert.c
While removing CONFIG_PRINT_TASKNAME, some conditional statement is missed.
This commit takes into account the situation where CONFIG_TASK_NAME > 0 and CONFIG_DEBUG_ERROR is not defined
Please refer this commit : 907e0ca60d78503611e2fb063a16f9f4b8e2215f
=> Fix build warning at up_assert

tools/ramdump/dumpParser.py
It's initial drop to parse the ramdump file and display the backtracing
It supports two options as of now and it will be further enhanced in future to
support multiple debugging features
For more info on usage of script, run
python callTrace.py -h
1) user can execute the script by passing complete ramdump as argument like below
python callTrace.py -r ramdump_0x02023800_0x02110000.bin -e tinyara
o/p  for simulating crash inside ps utility :
ramdump_file      : ramdump_0x02023800_0x02110000.bin
log_file          : None
Tinyara_elf_file  : tinyara
self.ram_base_addr 2023800
self.ram_end_addr 2110000
current_regs is not NULL …
=> Python script to display backtracing

apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
There are some rules about TC log in TizenRT.
TC function naming rule is {TC Category}_{Module}_{Function name}_{Positive/Negative} by default
So I change UTC names and test log at the start/end point to follow TC log rules.
=> testcase/arastorage: change UTC names and start/end log to follow TC log rules

framework/src/tinyalsa/tinyalsa.c
Modify the readi and writei API to run in a loop and transfer "frame_count"
size of data as requested by user. This will remove the limitation of the API
to transfer only period_size bytes of data at a time. However, this change will
make both the API's block for a long time, depending on the size of data transfer
requested by the user.
=> Tinyalsa : Fix readi and writei API's

external/wakaama/core/er-coap-13/er-coap-13.c
er-coap parsing in wakaama does not handle option processing correctly, and generates false positives in parsing errors. This commit fixes the problem.
=> fix coap parsing to process option boundary

os/mm/mm_heap/mm_heapinfo.c
If supporting multi-heap, printed msg in heapinfo is not good for legibility.
So change some words to capital, remove unnecessary words or sentences.
=> mm/mm_heapinfo: Modify printing msg format for distinguishing heap region

external/include/protocols/libcoap/debug.h
fix coap_show_pdu2 signature in libcoap. Currently when CONFIG_NETUTILS_LIBCOAP_DEBUG is disabled, coap_show_pdu2 shows wrong signature. This commit fixes the problem.
=> fix coap_show_pdu2 signature in libcoap

os/include/tinyara/spi/spi.h, os/include/tinyara/spi/spi_bitbang.h
This patch fix's the header guard in spi header files.
=> includes : Fix spi header guard

docs/HowToUsePeripheral.md
This patch updates SPI driver section in How to Use Peripheral
document.
It describes the low-level SPI device driver implementation
details with examples.
=> docs : add SPI device driver usage

os/arch/arm/src/armv7-r/arm_assert.c, os/include/assert.h, os/kernel/semaphore/sem_wait.c, tools/fs/mkromfsimg.sh
This feature is dependent on CONFIG_FS_ROMFS and CONFIG_FRAME_POINTER
It Copies the System.map file from output/bin/System.map to tools/fs/contents/System.map
It Parses the System.map file and searches for the symbol name corresponding to address
It displays the callStack along with symbol name
Advantage of this feature:
1. One can use these utilities [ dump_stack and dump_all_stack ] to display the callStack
anywhere in the source code for the src code browsing and learning
2. During System crash, along with stackdump, it helps to print the call stack with
symbol names. which will help the developer to debug the issue
Foreseen issue for point 2:
Since the file operations (fopen, fseek, rewind) are done when system is crashed,
there can be a recursive crash if there is a abort inside file …
=> Support for symbol name display inside callStack

apps/examples/testcase/ta_tc/device_management/itc/itc_dm_conn.c, apps/examples/testcase/ta_tc/device_management/itc/itc_dm_lwm2m.c
apps/examples/testcase/ta_tc/device_management/itc : DM ITC rename
Rename of scenario ITCs of DM
TC Naming rule is <TC_Category>_<Module>_<FunctionName>_<Positive/Negative>_<AdditionalInformation>
Current TC name do not have above naming convention
=> apps/testcase/DM : DM ITC rename

apps/examples/testcase/ta_tc/systemio/itc/itc_i2c.c
Rename of scenario ITCs of SystemIO i2c
TC Naming rule is <TC_Category>_<Module>_<SubModule>_<FunctionName>_<Positive/Negative>_<AdditionalInformation>
Current TC name donot have above naming convention
=> apps/testcase/i2c : i2c ITC rename

apps/examples/testcase/ta_tc/systemio/itc/itc_pwm.c
Rename of scenario ITCs of SystemIO pwm
TC Naming rule is <TC_Category>_<Module>_<SubModule>_<FunctionName>_<Positive/Negative>_<AdditionalInformation>
Current TC names do not have above naming convention
=> apps/testcase/pwm : pwm ITC rename

apps/examples/testcase/le_tc/kernel/tc_sched.c
The TC's under this flag may fail as they use kernel API this_taski() directly from application.
=> kernel/sched: add missing PROTECTED build flag for sched TC's

apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c
Refactor of ITCs of SystemIO spi
add static keyword for local function and variable.
TC Naming rule is <TC_Category>_<Module>_<SubModule>_<FunctionName>_<Positive/Negative>_<AdditionalInformation>
Current TC names do not have above naming convention
Remove not required header files and correct file name comment
=> apps/testcase/spi : spi ITC refactor

apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c, apps/examples/testcase/ta_tc/systemio/itc/itc_uart.c
Refactor of ITCs of SystemIO : uart and gpio
TC Naming rule is <TC_Category>_<Module>_<SubModule>_<FunctionName>_<Positive/Negative>_<AdditionalInformation>
Current TC names do not have above naming convention
Remove not required header files and correct file name comment
Restructure TCs and declare variable in seperate line.
Current TC do not have this conventtion
=> apps/testcase/systemio : uart, gpio ITC refactor

framework/src/tinyalsa/tinyalsa.c
Freeing pcm struct in pcm_close when pcm structure passed is a bad pcm.
This is necessary because even in case of bad pcm, the pcm structure is allocated
by pcm_open.
=> framework/tinyalsa: Fixing memory leak in tinyalsa

apps/examples/testcase/le_tc/filesystem/Kconfig, apps/examples/testcase/le_tc/filesystem/Make.defs, apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/filesystem/itc_fs.c
Scenario ITCs perform below tests
itc_fs_vfs_umount_n_twice : Unmount Mounted directory twice
itc_fs_vfs_mount_p_read_mode : Mount file system in read mode, and try to create directory
itc_fs_vfs_mount_n_twice : Mount file system twice
itc_fs_vfs_open_n : Open file with empty string, directory, file with parent directory does not exists
itc_fs_vfs_close_n : Close file twice, read after close
itc_fs_vfs_read_p_empty_file : Read an empty file
itc_fs_vfs_write_read_p : Write text to the file, and read it
itc_fs_vfs_fsync_p : Open same file with two file descriptors in read and write mode, and checks fsync
itc_fs_vfs_lseek_n : Move file position with invalid file descriptor, invalid whence
itc_fs_vfs_lseek_n_closed_fd : Move file position with file descriptor that is closed
itc_fs_vfs_lseek_p …
=> testcase/le_tc/filesystem : add ITCs for Filesystem APIs

apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c
itc_audio_pcm_open_p_with_different_flag : open pcm with different flag and check its validation
itc_audio_pcm_open_n_reopen : reopen pcm_open after opening
itc_audio_pcm_open_n : pcm_open with invalid argument
itc_audio_pcm_close_n : pcm_close with invalid argument
itc_audio_pcm_is_ready_n_after_close : check pcm_is_ready after pcm_close
itc_audio_pcm_is_ready_n : check pcm_is_ready with invalid argument
itc_audio_pcm_prepare_n_after_close : pcm_prepare after pcm_close
itc_audio_pcm_open_by_name_n : pcm_open_by_name with invalid argument
itc_audio_pcm_get_config_n_after_close : pcm_get_config afetr pcm_close
itc_audio_pcm_get_config_n : pcm_get_config after pcm_close
itc_audio_pcm_get_channels_n_after_close : pcm_get_channels after pcm_close …
=> testcase/ta_tc/Audio : add ITCs for Audio APIs

apps/examples/testcase/le_tc/network/Kconfig
currently, network testcase does not have CONFIG_NET_LWIP_ERROR  automatically enabled, which causes problems in it's execution. The solution is to enforce a dependency of CONFIG_NET_LWIP_ERROR on the testcase example. This ensures that testcase can compile only if CONFIG_NET_LWIP_ERROR is enabled.
=> Add LWIP error dependency to network testcase

apps/examples/testcase/le_tc/kernel/tc_libc_math.c
This patch covers corner TC's for:
j0f()
j1f()
nextafter()
nextafterf()
=> le_tc/math: Cover corner TC' for few math API's

framework/src/st_things/st_things_request_handler.c
When a request message is sent, the properties of the register resource will need to be check for existence.
=> framework/st_things: Add Request message payload property check logic

apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c, apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c, apps/examples/testcase/ta_tc/systemio/itc/itc_uart.c
Scenarios ITCs of gpio, spi and uart modules of systemio perform below tests:
itc_systemio_gpio_set_direction_read_write_p_all_directions : gpio read wirte for all direction
itc_systemio_gpio_set_edge_read_write_p_all_edges : gpio read wirte for all edges
itc_systemio_gpio_set_drive_read_write_p_all_drive_mode : gpio read wirte for all drive modes
itc_systemio_gpio_set_get_direction_edge_drive_mode_p : gpio set get direction edge and drive mode combined
itc_systemio_gpio_open_close_p_different_pin : gpio open close different pins
itc_systemio_gpio_open_close_p_multi_handle : gpio open close formultiple handle
itc_systemio_gpio_open_close_p_reclose : gpio reclose after gpio close
itc_systemio_gpio_open_n : gpio open with invalid argument
itc_systemio_gpio_close_n : gpio close with invalid …
=> testcase/ta_tc/SystemIO : add ITCs for SystemIO APIs

apps/examples/st_things/contents/sampleDevice.json, framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
1. Fix get filepath logic
Flexible logic to get file path for user authentication from json in Data Manager
The path to the file for user authentication may change during development, so change it flexibly to work even if it changes.
2. Fix coding rule
Modification of coding rule violation
3. Modify Json file
Modify the json file by agreement
=> framework/st_things: Fix get filepath logic

os/drivers/audio/alc5658.c
Shutdown logic for alc5658 has to clean up any pending buffers
in the pend queue.
=> ALC5658 codec to support shutdown properly

os/Kconfig.debug
DEBUG_TTRACE is valid when TTRACE is enabled.
=> ttrace: make a dependancy between DEBUG_TTRACE and TTRACE

framework/src/tinyalsa/tinyalsa.c
In tinyalsa, variable 'nbytes' be not frame unit but byte unit.
'nbytes' must be as byte unit.
=> Audio: Fix buffering delay issue

framework/src/media/media_recorder.c
Fix the issue which halt on recording.
Reason: Buffer size unit was different. One is byte, one is frame.
=> frameworks/media: Fix buffer size issue on recording

framework/src/media/media_recorder.c
Did not specify the period_size and period_count values of rec_config,
and an error caused by the garbage value occured.
=> fix invalid value of rec_config

apps/examples/testcase/le_tc/kernel/tc_environ.c
For TizenRT coding rule, trailing blank should not allowed
=> Remove unnessary tab in environ tc

apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c
change in ITC itc_systemio_gpio_register_unregister_callback_p
earlier callback was not properly invoked which lead to TC FAIL
callback is now properly invoked
=> testcase/itc_gpio.c : update ITC register_unregister_cb

os/arch/arm/src/tiva/Kconfig
1. When we use menuconfig, we can meet a warning as shown below:
warning: (TIVA_ETHERNET) selects NETDEVICES which has unmet direct dependencies (NET)
NETDEVICES is under NET so that if we want to enable NETDEVICES,
NET should be enabled first. To resolve this, let's add "if NET" at end of
NETDEVICE selection.
2. TIVA_ETHERNET can be enabled when hw has that periperal.
TIVA_HAVE_EHTERNET shows that so that TIVA_ETHERNET should have
a dependancy with TIVA_HAVE_ETHERNET.
=> arch/tiva: modify TIVA_ETHERNET dependancies

apps/examples/media_test/server/server_example_linux.c, framework/src/media/media_recorder.c
When stop recording, server program would be caught in a infinite loop.
Reason: Sent wrong instruction number.
=> examples/media: Fix recording stop issue

apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
Iterative init and deinit db operation
After db_deinit check APIs : print header, print tuple, print value, cursor_get_count, cursor_get_row API
Recreate same relation which is already created, reremove relation which is already removed
Create multiple relation and then remove
Create and remove same relation multiple time
get_result_message for all DB_ERRORS, get_result_message for specific ERROR
print header, print tuple, print value with invalid argument
Verify APIs with invalid scenario : get cursor count, cursor_move_first, _move_next, _move_prev, _move_last, _move_to, _is_first_row, _is_last_row
Check APIs : get_attr_type, _attr_name, _attr_index, _int_value, _long_value with invalid argument
cursor_get_row from current db cursor, cursor_get_row …
=> testcase/Arastorage : add ITCs for Arastorage APIs

apps/examples/testcase/le_tc/network/Kconfig, apps/examples/testcase/le_tc/network/Make.defs, apps/examples/testcase/le_tc/network/itc_net_close.c, apps/examples/testcase/le_tc/network/itc_net_dup.c, apps/examples/testcase/le_tc/network/itc_net_fcntl.c, apps/examples/testcase/le_tc/network/itc_net_listen.c, apps/examples/testcase/le_tc/network/network_tc_main.c, apps/examples/testcase/le_tc/network/tc_internal.h
open and close socket file descriptor multiple times,
reclose close file descriptor
clone a file descriptor multiple times
clone a file descriptor to specific descriptor multiple times
call fcntl with flag F_DUPFD
call fcntl with flag O_NONBLOCK and F_DUPFD
bind socket and then listen and repeat multiple times
bind different socket and then listen
listen afetr close socket
=> testcase/le_tc/network : add ITCs for network APIs

apps/examples/testcase/ta_tc/mqtt/itc/Kconfig, apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c
itc_mqtt_init_deinit_client_p :If used api returns not NULL and 0
itc_mqtt_init_deinit_client_n :If used api returns NULL and not 0
itc_mqtt_connect_disconnect_p :If used api returns not 0
itc_mqtt_connect_disconnect_n :If mqtt_connect returns not 0 and
mqtt_disconnect return 0
itc_mqtt_publish_p : If used api returns 0
itc_mqtt_publish_n : If used api returns not 0
itc_mqtt_subscribe_unsubscribe_p : call mqtt_subscribe, mqtt_unsubscribe
return 0
itc_mqtt_subscribe_p_resubscribe : already subscribe from a broker
itc_mqtt_unsubscribe_p_reunsubscribe : already un-subscribing from a
broker
itc_mqtt_publish_p_performance : average performance for mqtt_publish
itc_mqtt_api_success_ratio_p : success ratio for all mqtt api
itc_mqtt_subscribe_p_performance : …
=> testcase/ta_tc/mqtt : add new ITC for MQTT

apps/examples/testcase/le_tc/kernel/tc_clock.c, apps/examples/testcase/le_tc/kernel/tc_environ.c, apps/examples/testcase/le_tc/kernel/tc_mqueue.c
This patch ads missing TC's for following:
1) kernel/mqueue: message queue API's:
mq_timedsend()
mq_notify()
2) kernel/clock: closck API's:
clock_initialize()
clock_gettime()
clock_settime()
3) kernel/environ API's:
get_environ_ptr()
getenv()
=> Kernel code coverage: Cover missing cases from existing TC's

build/configs/artik053/.flashSpec.xml, build/configs/artik053/audio/Make.defs, build/configs/artik053/extra/Make.defs, build/configs/artik053/hello/Make.defs, build/configs/artik053/iotivity/Make.defs, build/configs/artik053/iotjs/Make.defs, build/configs/artik053/kernel_sample/Make.defs, build/configs/artik053/minimal/Make.defs, build/configs/artik053/nettest/Make.defs, build/configs/artik053/st_things/Make.defs, build/configs/artik053/tc/Make.defs, build/configs/artik053s/.flashSpec.xml, build/configs/artik053s/nettest/Make.defs, build/configs/artik055s/.flashSpec.xml, build/configs/artik055s/audio/Make.defs, build/configs/artik055s/nettest/Make.defs, build/configs/artik05x/artik05x_download.sh
Only "ALL" option is providing to flash all of partitions on "make download" command.
This patch makes user can select which partition should be flashed.
i.e.
make download OS BL2 ROMFS
make download SSSFW WLANFW
=> configs/artik05x: modify download script to download each partition

os/arch/arm/src/armv7-r/arm_assert.c
When get_symbol fails to get the symbol name, return the appropriate
value. return value 0 for success and -1 for failure.
If return value is -1, it does not display the symbol name infront of address
If return value is 0, display the symbol name infront of address
=> Handle the get_symbol return value

os/Makefile.unix, os/arch/Kconfig.chip, os/arch/arm/src/armv7-r/arm_assert.c, os/kernel/semaphore/sem_wait.c, tools/fs/mkromfsimg.sh
callstack dump with symbol feature stores symbol data in romfs.
user should be able to turn this feature on and off.
=> Make user choose dump callstack with symbol feature

apps/shell/tash_command.c, apps/system/init/init.c
Since basic TASH commands are registered at the end, there is a
chance that help command would not get install itself in some
corner cases and thus it causes inconvenience to see all
the registered commands
This patch fixes this issue by always registering basic commands first
and then prints the error message. This will help developer to increase
the CONFIG_TASH_MAX_COMMANDS value
For ex:
1. cd os/tools
2. ./configure.sh artik053/iotivity
3. cd ..
4. make menuconfig
5. go to Application Configuration --> TASH
6. It shows MAX commands allowed as 132
7. Disable the tash option and save the config and exit
8. again run "make menuconfig" and enable the tash
9. It updates the default registered commands as 32 only.
10. Save the config and exit
11. build and download the binary
12. help …
=> Register the basic TASH commands first

framework/src/media/media_player.c, framework/src/media/media_recorder.c
a problem by unlocking the lock after pthread_join,
and I fixed that part.
=> fix deadlock for media_framework.

apps/shell/tash_main.c
tash_start() api prints pid as error code, tash_start calls task_create()
to start tash, Incase of task_create fails to start a task, it sets the
error code in "errno" and returns either valid pid or ERROR(-1)
Also, there is is no need to print the error message inside tash_start as it
causes duplication inside preapp_start() api of apps/system/init/init.c
This commit does following things
1. Sets the valid error code inside tash_start
2. Removes duplicated printf message inside tash_start as it's already
printed in preapp_start()
=> Fix : tash_start() prints incorrect error code

lib/libc/pthread/pthread_attrdestroy.c, lib/libc/pthread/pthread_attrgetinheritsched.c, lib/libc/pthread/pthread_attrgetschedparam.c, lib/libc/pthread/pthread_attrgetschedpolicy.c, lib/libc/pthread/pthread_attrgetstacksize.c, lib/libc/pthread/pthread_attrinit.c, lib/libc/pthread/pthread_attrsetinheritsched.c, lib/libc/pthread/pthread_attrsetschedparam.c, lib/libc/pthread/pthread_attrsetschedpolicy.c, lib/libc/pthread/pthread_attrsetstacksize.c, lib/libc/pthread/pthread_condattrdestroy.c, lib/libc/pthread/pthread_condattrinit.c, lib/libc/pthread/pthread_mutexattrdestroy.c, lib/libc/pthread/pthread_mutexattrgetpshared.c, lib/libc/pthread/pthread_mutexattrinit.c, lib/libc/pthread/pthread_mutexattrsetpshared.c, lib/libc/time/lib_gmtimer.c, lib/libc/time/lib_mktime.c, os/kernel/pthread/pthread_join.c
Some sdbg has just information message, not error message so that
debug message level is changed to verbose instead of error.
=> pthread, time: change sdbg to svdbg

apps/system/init/init.c
mount operation sets the error number and returns either 0 or ERROR.
To get the actual error no, use get_errno()
=> Fix incorrect error code display in preapp_start()

apps/system/sysdbg/sysdbgapp_init.c, os/kernel/debug/sysdbg.c
Reference PR#1141
When CONFIG_DEBUG_SYSTEM & CONFIG_DEBUG_SYSTEM_APP is enabled,
in qemu/tc_64k or qemu/tc_1m configuration, build error occurs due to implicit
declaration of strlen, strncmp, sscanf and printf
This commit includes missing header files for below operations
Strlen => string.h (sysdbgapp_init.c)
printf => stdio.h  (sysdbgapp_init.c)
strncmp => string.h (sysdbg.c)
sscanf => stdio.h (sysdbg.c)
=> Fix build error on sysdbg for qemu/tc_64k

os/audio/pcm_decode.c
=> Fix miswritten address of author in pcm_decode.c

apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
The value of fd can be 0.
Comparison of pointers should only use =, !=
=> Fix minor errata in audio utc

os/audio/audio.c
Concider mkdir fail case.
If it happens, audio_register failed
=> Check mkdir return value in audio_register

apps/system/utils/fscmd.c
INVALID_ARGS, MISSING_ARGS use only one arg
=> Fix FSCMD_OUTPUT usage mistake

apps/system/utils/fscmd.c
=> Fix FSCMD_OUTPUT usage mistake(INVALID_ARGS)

framework/src/tinyalsa/tinyalsa.c
Argument e of oops(struct pcm *pcm, int e, const char *fmt, ...)
must be >= 0
=> Fix oops parameter in tinyalsa.c

external/iotjs/Kconfig.runtime
Observed issue was:
iotjs_module_spi-tizenrt.c:23:2: \
error: #error "\n\nTizenRT CONFIG_SPI_EXCHANGE flag required for SPI module\n\n"
Change-Id: I8ec289c680973f7949d48b64a459524dab2083e0
=> iotjs: Select SPI in KConfig

os/drivers/wireless/scsc/misc/mx_mmap.c, os/drivers/wireless/scsc/t20_ops.c
Deleted code is never executed.
=> Move unreachable code properly in drivers/wireless

os/arch/arm/src/armv7-m/up_blocktask.c, os/arch/arm/src/armv7-m/up_releasepending.c, os/arch/arm/src/armv7-m/up_reprioritizertr.c, os/arch/arm/src/armv7-m/up_sigdeliver.c, os/arch/arm/src/armv7-m/up_unblocktask.c
Further enhancement of Reference PR#1141
This commits adds support for logging the task scheduling information
for armv7-m architecture and it's verified using qemu as it uses armv7-m
=> Logging task scheduling info for armv7-m based board

os/include/pthread.h
PTHREAD_COND_INITIALIZER will initialize the pthread_cond_s,and pthread_cond_s is made from semaphore
Referenced by Nuttx(35a6ef7)
=> include/pthread.h: fix PTHREAD_COND_INITIALIZER macro and explanation comment for tinyara/semaphore.h

external/wpa_supplicant/src/common/wpa_ctrl.c
In cases where a large amount of data is to be transferred over a non-UDP socket, the offset would not be updated correctly.
This patch makes sure that the offset is always updated according to the amount read.
=> Fix problem with offset in wpa_receive_from not being updated correctly

apps/examples/testcase/le_tc/network/Kconfig, apps/examples/testcase/le_tc/network/Make.defs, apps/examples/testcase/le_tc/network/itc_net_connect.c, apps/examples/testcase/le_tc/network/itc_net_inet.c, apps/examples/testcase/le_tc/network/itc_net_netdb.c, apps/examples/testcase/le_tc/network/itc_net_send.c, apps/examples/testcase/le_tc/network/itc_net_setsockopt.c, apps/examples/testcase/le_tc/network/network_tc_main.c, apps/examples/testcase/le_tc/network/tc_internal.h
itc_net_inet_addr_n : passing invalid address
itc_net_inet_aton_n : passing invalid args
itc_net_inet_ntop_p : passing hex value in inet_ntop
itc_net_inet_ntop_n : passing invalid args to inet_ntop
itc_net_inet_pton_p : passing IPv4 addr in dot format and IPv6 in colon
format
itc_net_inet_pton_n : passing invalid args to inet_pton
itc_net_ntohl_p : passing uint32_t hostlong and comparing value
itc_net_ntohs_p : passing uint16_t hostshort and reconvering to uint16_t
netshort comparing their values
itc_net_netdb_getaddrinfo_n : passing invalid node and service
itc_net_send_n_fd : sending invalid file descriptor
itc_net_send_n_msg : sending NULL msg
itc_net_setsockopt_p_invalid_opt_name : sending invalid opt name
itc_net_setsockopt_p_rcvbuf : setsockopt …
=> testcase/le_tc/network : add ITC for network

apps/system/utils/kdbg_irqinfo.c
Build error happens when CONFIG_ENABLE_IRQINFO is enabled for
qemu/tc_1m configuration as OK and ERROR are undefined
=> utils/kdbg_irqinfo : Fix build error for qemu/tc_1m configuration

os/arch/arm/src/armv7-m/up_assert.c
MPU regions info should be displayed in asserts only when `CONFIG_ARMV7M_MPU` is enabled.
=> armv7-m/up_assert: wrap CONFIG_ARMV7M_MPU to 'mpu_show_regioninfo'

apps/examples/testcase/le_tc/network/itc_net_connect.c
For artik053/tc coonfigurtion , when we run make menuconfig and save it
it results in build error as follows
le_tc/network/itc_net_connect.c:181:16: error: passing argument 1 of 'pthread_exit' makes pointer from integer without a cast [-Werror]
pthread_exit(ret);
=> network/itc_net_connect.c : fix build error

build/configs/artik053/README.md, build/configs/artik053s/README.md, build/configs/artik055s/README.md
For a safer factory reset, it's safer to erase OTA partition.
I came to the case, where there was junk in partition,
instead of actual "Over the Air" image
And do_checkupdate failed on crc32 which caused a reset of uboot.
So to reduce unexpected cases, the partition is just erased,
then comparaison test on ${otapart} header will be skipped (==0xffffffff).
For more insights check file:
artik-05x/include/configs/artik05x.h
URL: https://developer.artik.io/forums/t/solved-how-to-factory-reset-artik055s/5254
Change-Id: I19de266fdfe134fe3cc9574f5cc2482215d9877a
=> artik: Explain to erase OTA part for factory reset

os/audio/audio.c
usermq should not be initialize after first audio_open,
because previous thread may using that usermq
=> Initialize usermq only when first audio_open

apps/examples/media_test/media_test_main.c
"media_test" command overlaps with builtin command of media_test_main.
So remove media_test command registration, and let media_test app start directly.
If user want to use media_test via tash, just enable media_test and builtin feature.
=> Remove media_test command registration

framework/src/iotbus/iotbus_gpio.c
When gpio is closed, even though dev resource is freed, dev value
is not set to NULL. It causes getting wrong response from gpio function
after calling close function.
=> framework/iotbus/gpio: set a dev to NULL on close

os/kernel/debug/sysdbg.c
This patch fixes build error, which occurs
when any one or two of below three configs are disabled
1. CONFIG_TASK_SCHED_HISTORY
2. CONFIG_IRQ_SCHED_HISTORY
3. CONFIG_SEMAPHORE_HISTORY
=> kernel/debug: Fix build error in sysdbg module

tools/fs/mkromfsimg.sh
This is a divergence from NuttX,
problem has been introduced when removed file:
os/tools/mkromfsimg.sh (dropped NSHInitVol support)
https://github.com/Samsung/TizenRT/pull/1204
While this tools/fs/mkromfsimg.sh script was testing that removed file,
this is not relevent, so we adapt to check if pwd is in os dir
Observed regression is:
The "bl1 bl2 sssfw wlanfw os rom" partition(s) will be flashed
../tools/fs/mkromfsimg.sh: 59: ../tools/fs/mkromfsimg.sh: error: not found
ROMFS image is not present
make[1]: *** [download] Error 1
URL: https://github.com/Samsung/TizenRT/pull/1204
Change-Id: I830dd31d95ff2b2342c3f0301a8ba83e5e3b75bf
=> tools: Ensure mkromfsimg.sh run from os dir

os/arch/arm/src/armv7-m/up_assert.c, os/arch/arm/src/armv7-r/arm_assert.c
It is not relavant to print log header without actual log content.
So it is better to move log header of up_showtasks inside it's function definition.
=> armv7: Move log header of up_showtasks inside it's function definition

docs/HowtoInstallKconfigFrontend.md
In some environment, byacc should be installed to use Kconfig-frontend.
We wrote that on description, "(or byacc if supported)".
But someone doesn't see it and just copy commands from bash window and execute.
To prevent an error, let's defaultly add that in bash window.
=> docs: add the byacc package in bash command window

apps/examples/iotbus_test/iotbus_test_main.c, apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c, apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c, external/iotjs/src/platform/tizenrt/iotjs_module_gpio-tizenrt.c, framework/include/iotbus/iotbus_gpio.h, framework/src/iotbus/iotbus_gpio.c
iotbus_gpio_close closes the gpio context and frees all resources pointed by dev.
We need to pass the address of dev to set dev as NULL.
=> iotbus/gpio: change a prameter type of iotbus_gpio_close to pointer of iotbus_gpio_context_h

docs/HowToPortTizenRTOnWiFiChipset.md, framework/src/wifi_manager/Kconfig, os/drivers/wireless/Kconfig
Edit the Kconfig for wifi manager, and carry out the following changes:
create choice config for supplicant library, and move the WPA_SUPPLICANT config creation to wifi_manager
create choice config for wifi driver, and move the SCSC_WLAN config creation to wifi_manager.
Additionally, document these changes to the docs file for WiFi.
=> Edit wifi manager build and wifi porting guide

apps/examples/testcase/le_tc/network/tc_net_getsockname.c, apps/examples/testcase/le_tc/network/tc_net_listen.c, apps/examples/testcase/le_tc/network/tc_net_netdb.c, apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c
fixed to close handle or free allocated resource before exit
tc_net_getsockname.c:
- The handle 'sock' was created at tc_net_getsockname.c:50 by calling function 'socket' and lost at tc_net_getsockname.c:54.
- The handle 'sock' was created at tc_net_getsockname.c:74 by calling function 'socket' and lost at tc_net_getsockname.c:77.
- The handle 'sock' was created at tc_net_getsockname.c:143 by calling function 'socket' and lost at tc_net_getsockname.c:146.
- The handle 'sock' was created at tc_net_getsockname.c:166 by calling function 'socket' and lost at tc_net_getsockname.c:169.
tc_net_listen.c:
- The handle 'SocketFD' was created at tc_net_listen.c:130 by calling function 'socket' and lost at tc_net_listen.c:141.
tc_net_netdb.c:
- The handle 'res' was created at tc_net_netdb.c:59 by …
=> testcase: fix some defects in testcase for network, gpio

build/configs/qemu/HowToRunNetworkStackOnQemu.md, build/configs/qemu/README.md
Create new net_up and net_down shell script files to bring up and bring down the tap interface on QEMU.
Run net_up shell script file to bring up tap interface.
Run the qemu command.
Run ping application on QEMU to test Network Module.
Run net_down shell script file to bring down tap interface.
Signed-off-by: vinay kadam <vinay1.kadam@samsung.com>
=> Procedure to verify Network Module on QEMU.

framework/src/wifi_manager/wifi_manager.c
if mac address is "fe:00:..." then it will lose data after ":00:.."
because strncpy will stop copy when character is null.
so using memcpy() instead of strncpy() will fix the issue.
=> network/wifi_manager: fix copying mac address bug

apps/system/iperf/iperf_api.c, external/netutils/netlib_getipv4addr.c, framework/src/st_things/things_stack/framework/things_data_manager.c, os/drivers/wireless/scsc/mib_text_convert.c
- NULL check after memory allocation
- Add '\0' at the end of string
- Add type casting when change to bigger type
=> Fix logical errors

apps/examples/iotbus_test/iotbus_test_main.c, apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c, apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c, external/iotjs/src/platform/tizenrt/iotjs_module_gpio-tizenrt.c, framework/include/iotbus/iotbus_gpio.h, framework/src/iotbus/iotbus_gpio.c
This reverts commit 042e1dcfd2b2eda074491debf2824cb887ce92ca.
This API should be kept and deprecated because it is public API.
New API for this functionality will be added.
=> Revert "iotbus/gpio: change a prameter type of iotbus_gpio_close to pointer of iotbus_gpio_context_h"

apps/examples/testcase/le_tc/network/tc_net_getpeername.c
I closed a socket that was not closed in the function.
=> testcase/network : Fix handle_leak

external/ntpclient/ntpclient.c
A build error occurs when the CONFIG option is not set.
=> NTPC Daemon : build error fix when CONFIG option was not set

external/wpa_supplicant/Kconfig, external/wpa_supplicant/src/eap_peer/eap_pwd.c, external/wpa_supplicant/src/eap_server/eap_server_pwd.c
Fix CVE issues in wpa_supplicant (ref: issue #942). 
1. The fix disables building of the affected files eap_server_pwd.c and eap_pwd.c, by using a CONFIG_DISABLE_EAP_SUPPLICANT
2. CONFIG_DISABLE_EAP_SUPPLICANT is defined in the Kconfig for supplicant, and is set to true by default.
=> fix CVE issues in wpa_supplicant

apps/platform/Kconfig
This patch adds support to source missing gnu/Kconfig
It is required to include CONFIG_HAVE_CXXINITIALIZE in the
build configuration
=> apps : include platform/gnu Kconfig

build/configs/artik053/audio/Make.defs, build/configs/artik053/extra/Make.defs, build/configs/artik053/hello/Make.defs, build/configs/artik053/iotivity/Make.defs, build/configs/artik053/iotjs/Make.defs, build/configs/artik053/kernel_sample/Make.defs, build/configs/artik053/minimal/Make.defs, build/configs/artik053/nettest/Make.defs, build/configs/artik053/st_things/Make.defs, build/configs/artik053/tc/Make.defs, build/configs/artik053s/nettest/Make.defs, build/configs/artik053s/st_things/Make.defs, build/configs/artik055s/audio/Make.defs, build/configs/artik055s/minimal/Make.defs, build/configs/artik055s/nettest/Make.defs, build/configs/artik055s/st_things/Make.defs, build/configs/qemu/tc_16m/Make.defs, build/configs/qemu/tc_1m/Make.defs, build/configs/qemu/tc_64k/Make.defs, build/configs/sidk_s5jt200/hello/Make.defs, build/configs/sidk_s5jt200/hello_with_tash/Make.defs, build/configs/sidk_s5jt200/kernel_sample/Make.defs, build/configs/sidk_s5jt200/sidk_tash_aws/Make.defs, build/configs/sidk_s5jt200/sidk_tash_wlan/Make.defs, build/configs/sidk_s5jt200/tc/Make.defs, external/iotjs/config/tizenrt/artik05x/configs/Make.defs, external/iotjs/deps/jerry/targets/tizenrt-artik053/configs/jerryscript/Make.defs, external/iotjs/deps/libtuv/cmake/option/option_arm-tizenrt.cmake
include/cxx && include/uClibc++ directories are not present.
hence this patch updates all board configuration Make.defs to remove
these directory path from the include
=> configs : update all board Make.defs to remove cxx include path

framework/src/st_things/things_stack/things_stack.c
- ip4_address itself is string, no conversion needed
=> framework/st_things : Fix IPv4 address error in station mode

framework/src/st_things/things_stack/things_stack.c
- In Station Mode, if the connection to the Home AP fails, return an error
=> framework/st_things : Error return when wifi connection fails

framework/Makefile, framework/src/arastorage/Make.defs, framework/src/dm/Make.defs, framework/src/iotbus/Make.defs, framework/src/media/Make.defs, framework/src/network/Make.defs, framework/src/st_things/Make.defs, framework/src/tinyalsa/Make.defs
Using wildcard, all Make.defs are included
=> Remove hardcoded directories in framework/Makefile

build/configs/artik053/.flashSpec.xml, build/configs/artik053s/.flashSpec.xml, build/configs/artik055s/.flashSpec.xml, build/configs/artik05x/artik05x_download.sh
Erasing ota partition is needed to support FOTA. This commit add
ERASE_OTA option on make command to do it.
=> build/artik05x: support erasing ota partition through make command

apps/examples/cxxtest/cxxtest_main.cxx, build/configs/artik053/audio/Make.defs, build/configs/artik053/extra/Make.defs, build/configs/artik053/hello/Make.defs, build/configs/artik053/iotivity/Make.defs, build/configs/artik053/iotjs/Make.defs, build/configs/artik053/kernel_sample/Make.defs, build/configs/artik053/minimal/Make.defs, build/configs/artik053/nettest/Make.defs, build/configs/artik053/st_things/Make.defs, build/configs/artik053/tc/Make.defs, build/configs/artik053s/nettest/Make.defs, build/configs/artik053s/st_things/Make.defs, build/configs/artik055s/audio/Make.defs, build/configs/artik055s/minimal/Make.defs, build/configs/artik055s/nettest/Make.defs, build/configs/artik055s/st_things/Make.defs, build/configs/sidk_s5jt200/hello/Make.defs, build/configs/sidk_s5jt200/hello_with_tash/Make.defs, build/configs/sidk_s5jt200/kernel_sample/Make.defs, build/configs/sidk_s5jt200/sidk_tash_aws/Make.defs, build/configs/sidk_s5jt200/sidk_tash_wlan/Make.defs, build/configs/sidk_s5jt200/tc/Make.defs, external/iotjs/config/tizenrt/artik05x/configs/Make.defs, external/iotjs/deps/jerry/targets/tizenrt-artik053/configs/jerryscript/Make.defs, lib/libxx/.gitignore, lib/libxx/Kconfig, lib/libxx/Makefile, os/include/.gitignore
uClibc++ configurations no longer required.
This patch removes these configurations from Kconfig
and Makefiles
This also updates all Make.defs to remove definitions/code under
uClibc++ configs.
=> libxx : remove uClibc++ configurations

apps/examples/testcase/le_tc/kernel/tc_task.c
This patch adds corner cases for following API's
task_create()
task_reparent()
task_restart()
=> le_tc/task: Add corner cases for task TC's

external/wpa_supplicant/Kconfig, external/wpa_supplicant/src/eap_peer/eap_pwd.c, external/wpa_supplicant/src/eap_server/eap_server_pwd.c
Edit a fix for CVE issues (commit id: 23fa1c75c26aa0fb400c7e2df6345e63a4cc2825). In this pull request, we perform the following edits to the above fix.
1. Rename the Kconfig parameter, allowing a default value of n.
2. Fix correct usage of the parameter to disable build of the affected files.
3. Document the CVE issues at affected code, and suggest the developer to fix the CVE issues before using the code.
=> Edit fix for CVE issues in wpa_supplicant

lib/libc/spawn/lib_psa_getflags.c, lib/libc/spawn/lib_psa_getschedparam.c, lib/libc/spawn/lib_psa_getschedpolicy.c, lib/libc/spawn/lib_psa_getsigmask.c, lib/libc/spawn/lib_psa_getstacksize.c, lib/libc/spawn/lib_psa_init.c, lib/libc/spawn/lib_psa_setflags.c, lib/libc/spawn/lib_psa_setschedparam.c, lib/libc/spawn/lib_psa_setschedpolicy.c, lib/libc/spawn/lib_psa_setsigmask.c, lib/libc/spawn/lib_psa_setstacksize.c, lib/libc/spawn/lib_psfa_addclose.c, lib/libc/spawn/lib_psfa_adddup2.c, lib/libc/spawn/lib_psfa_addopen.c, lib/libc/spawn/lib_psfa_destroy.c, os/include/spawn.h
Nuttx checks them with DEBUGASSERT. But that is different with POSIX
standard and we don't want to make a crash even if it has invalid arguments.
This commit changes them returning errno values without crash.
=>  libc/spwan: modify checking logic of function arguments

README.md
Our recommanded toolchain is fully working on 32bits OS.
64bits OS needs to install additional ubuntu package.
This commit describes above.
=> README: add caution of toolchain usages for 64bit OS

os/arch/arm/src/s5j/s5j_i2s.c, os/include/tinyara/audio/i2s.h
Add i2s_pause and i2s_resume methods for s5j_i2s driver.
These methods will be used to pause and resume i2s transfer
while trying to recover from xrun error during audio play / record.
=> Add new methods, pause and resume, in I2S driver

framework/src/st_things/things_stack/things_stack.c
The device had tried to connect when it is cut off from WiFi
and It occurred timed-out.
So Now, It doesn't try to connect to sign-up/in when disconnected the Network
and It will try to Sign-Up/In when WiFi are turned up.
=> framework/st_things: Add canceling logic for trying reconnect the cloud.

os/kernel/timer/timer.h, os/kernel/timer/timer_create.c, os/kernel/timer/timer_gettime.c, os/kernel/timer/timer_release.c, os/kernel/timer/timer_settime.c
When timer is created or released, they update pt_flags
inside posix_timer_s struct. And set and get timer functions check
that flag and return appropriatary value.
=> kernel/timer: add a logic to check timer is valid or not

apps/examples/testcase/Makefile
Using wildcard, all Make.defs are included
=> Remove hardcoded directories in testcase/Makefile

apps/shell/Kconfig, apps/shell/Makefile, apps/shell/tash_command.c, apps/shell/tash_internal.h, apps/system/cle/Kconfig, apps/system/poweroff/Kconfig, apps/system/utils/Kconfig, apps/system/vi/Kconfig, framework/src/dm/Make.defs, framework/src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c, os/arch/arm/src/artik05x/Kconfig, os/arch/arm/src/artik05x/src/artik05x_tash.c, os/arch/arm/src/sidk_s5jt200/Kconfig, os/arch/arm/src/sidk_s5jt200/src/s5jt200_tash.c, os/drivers/Kconfig, os/include/stdio.h
1. Some module which uses file operation APIs like open, read, write and so on make a dependancy with NFILE_DESCRIPTORS to prevent compilation and linking errors.
2. TASH adds new config, TASH_SCRIPT to disable script functionality.
=> code refactoring

apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c, framework/src/wifi_manager/wifi_manager.c
As definition of wifi-manager's callback is changed, utc need to be changed in UTC.
=> testcase/wifi-manager: fix callback function definition

os/arch/arm/src/common/up_createstack.c
Currently stack base is aligned to the stack size requested which causes more
fragmentation.
stack base is not required to be aligned, only stack top needs to be
aligned to max 8 bytes in case of armv7 which is already done.
Hence this patch removes aligning stack base during stack allocation from heap
=> arm : fix stack memory base alignment

external/Makefile
When we try to build IoTjs, we should set --target-arch and --target-board
options on Makefile. They are fixed to arm and artik05x but they cause
difficult to find and wrong operation on IoTjs.
When TizenRT is built, CONFIG_ARCH and CONFIG_ARCH_BOARD are set and
they shows the information of selected board. User doesn't need to
set them in iotjs again.
This commit makes iotjs using those configurations.
=> external/iotjs: get build options, target-arch and board from Kconfig

lib/libc/semaphore/sem_getprotocol.c, lib/libc/semaphore/sem_getvalue.c, lib/libc/semaphore/sem_init.c, lib/libc/semaphore/sem_setprotocol.c, os/include/semaphore.h, os/kernel/semaphore/sem_destroy.c, os/kernel/semaphore/sem_post.c, os/kernel/semaphore/sem_reset.c, os/kernel/semaphore/sem_setprotocol.c, os/kernel/semaphore/sem_trywait.c, os/kernel/semaphore/sem_wait.c
1. POSIX standard describes return value as shown below:
Upon successful completion, a value of zero shall be returned.
Otherwise, a value of -1 shall be returned and errno set to indicate the error.
But our sem APIs do not check sem initialization and do not return ERROR.
2. Without sem_init, almost sem APIs work. But it can cause abnormal
operation.
The sem_s structure already has the flag element inside
and first bit is an inheritance flag. Let's use second bit as
initialization flag and check it at first operation of sem APIs.
=> sem: add a flag to show initialization and check it on sem APIs

framework/Makefile
CXXOBJS needed both .cxx and .cpp, and it is a bug
Divide CXXOBJS by CXXOBJS and CPPOBJS according to suffix
=> Fix bug in framework/Makefile

build/configs/artik053/grpc/Make.defs
- Modify C++ warning options of grpc which issue a lot of build warnings as grpc doesn't check them strictly
1. removed :  -Wshadow, -Wundef, -pedantic
2. added : -Wno-sign-compare
=> Modify build warning options in artik053/grpc

os/kernel/init/os_start.c
clock_initialize uses the semahpore for inode, g_inode_sem before initialization.
A semaphore shouldn't be used without initialization.
So we need to call fs_initilize function which initializes inode semaphore before that.
=> kernel/init: call fs_initialize before clock_initialize to initialize semaphore for inode

external/protobuf/Makefile
- There are two common.cc files in Makefile, one should be removed.
=> Modify protobuf makefile not to build two same files

docs/Porting_Guide.md
Audio is a part of porting so that link is necessary on porting guide.
=> docs: make a link to audio document on Porting guide

build/configs/qemu/tc_16m_grpc/Make.defs
- Modify C++ warning options of grpc which issue a lot of build warnings as grpc doesn't check them strictly
1. removed :  -Wshadow, -Wundef, -pedantic
2. added : -Wno-sign-compare
=> Modify build warning options in qemu/tc_16m_grpc

os/include/sys/sock_internal.h, os/net/socket/Make.defs, os/net/socket/recvmsg.c, os/net/socket/sendmsg.c
socket apis(recvmsg, sendmsg) have a dependency to iotivity.
recvmsg and sendmsg will be built with other socket apis
but those apis are not fully supported. so it should be used carefully.
=> network/socket_api: remove dependency between iotivity and socket apis

os/include/semaphore.h
The sem_s structure has the flags element always by commit 9d4e238.
But SEM_INITIALIZER misses adding that element.
This commit fixs commit 9d4e238 and 3b7eaca.
=> os/sem: fix missing value of SEM_INITIALIZER on commit 9d4e238

external/grpc/README.md
Add README to external/grpc folder. This document covers details from how to build gRPC module on TizenRT, as well as develop, build and execute TizenRT applications that use gRPC.
=> Add README.md to grpc folder

apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
Original code tries to remove the relation after deinitializing database. I observed kernel panic due to illegal memory access occasionally during the execution of `arastorage_itc` tests on ARTIK053 board. After this fix, I did not observe the kernel panic.
=> Should deinitialize database after removing relations (db_cleanup).

apps/system/utils/Kconfig, apps/system/utils/Makefile, apps/system/utils/kdbg_kill.c
The kill and killall functions can always run task termination, SIGKILL
even if signal and pthread are disabled.
So, remove a signal conditional on Kconfig and Makefile of kill and
make conditionals on source code for signal and pthread.
Kill and Killall is controled by only CONFIG_ENABLE_KILL(ALL).
=> apps/utils/kill(all): enable task termination with any configs

docs/HowToUseAudio.md
PCM decoder has been removed from kernel audio framework.
Modify the audio HowTo documentation accordingly to reflect this change.
=> [Audio] Fix mistake in audio HowTo documentation

apps/examples/testcase/tc_main.c
Fixes wrong typo "#if CONFIG_TASH" introduced in the commit [fff960](https://github.com/Samsung/TizenRT/commit/fff960a48b956ae6f0e4775818455a0eddc55f23#diff-5a3373019e1c1e2913a474432bdc9943).
Due to which error occurs in kernel tc_main when CONFIG_TASH is disabled.
The correct typo is "#ifdef CONFIG_TASH".
=> examples/testcase: Fix wrong typo in kernel tc main

framework/src/st_things/things_stack/framework/things_server_builder.c, framework/src/st_things/things_stack/things_api.h, framework/src/st_things/things_stack/things_stack.c
1. 639c408 : Bug fix, 'create_resource' function used assign(=) operation when it copied type(string). At this time the string can be constant string.
2. e1244e1 : This function will trig stack deinitialization functions such as 'es_cloud_terminate', 'esm_terminate_easysetup'.
=> framework/st_things : Add 'things_stop' which internal function.

apps/shell/Kconfig, apps/shell/tash_internal.h
TASH has debug APIs, shdbg and shvdbg. They are splitted by debug level.
But it has only one config so that there is no difference between them.
This commit makes them working as original purpose of debug level.
=> apps/shell: add new configs, DEBUG_TASH_ERROR and DEBUB_TASH_VERBOSE

apps/examples/grpc_greeter_client/Kconfig, apps/examples/grpc_route_client/Kconfig, apps/examples/protobuf/Kconfig, external/grpc/Kconfig.protocol, external/protobuf/Kconfig
These examples can be executed with enabling related modules.
And protobuf should be enabled for gRPC usage.
So these have some dependency on each module.
=> add dependency between configurations about grpc and protobuf

external/protobuf/README.md
The guide contains the version of a ported protobuf, how to build and
hot to run it on TizenRT.
=> external/protobuf: Add a guide to build and run protobuf on TizenRT

apps/builtin/builtin_taskinfo.c, apps/shell/tash_command.c, apps/system/utils/kdbg_stackopt.c
tash_taskinfo_list[] is declared when build time, so it cannot be changed.
so set to const.
=> apps/builtin : Add omitted const identifier

build/configs/qemu/README.md
Issue: Hardfault while running iperf application with huge TCP throughput [>20MB]
Fix: Use latest qemu sw : 2.12.0-rc1
Qemu sw has been recently updated with several enhancements to
cortex m profile emulation as well as to network component.
More details about change log is here: https://wiki.qemu.org/ChangeLog/2.12
procedure to download and build are updated in this readme
=> Qemu/readme : Update about using latest qemu sw 2.12.0-rc1

apps/system/utils/Kconfig, apps/system/utils/README.md, apps/system/utils/kdbg_heapinfo.c, os/include/tinyara/mm/.gitignore, os/include/tinyara/mm/mm.h, os/kernel/sched/sched_releasetcb.c, os/kernel/task/task_create.c, os/kernel/task/task_prctl.c, os/mm/Makefile, os/mm/mm_heap/mm_free.c, os/mm/mm_heap/mm_heapinfo.c, os/mm/mm_heap/mm_initialize.c, os/mm/mm_heap/mm_malloc.c, os/mm/mm_heap/mm_memalign.c, os/mm/mm_heap/mm_realloc.c
"heapinfo -g" shows the information about user defined group heap memory usage
example)
```
****************************************************************
Heap Allocation Information per User defined Group
****************************************************************
PEAK | HEAP_ON_PEAK | STACK_ON_PEAK | THREADS_IN_GROUP
----------------------------------------------------------------
4572 |         3568 |          1004 | jckim,jckim2
5772 |         4768 |          1004 | jckim3
2940 |          896 |          2044 | asdf
```
=> kdbg/heapinfo : Implement to showing User Defined Group Heap Usage

os/include/pthread.h, os/include/tinyara/sched.h, os/kernel/Kconfig, os/kernel/pthread/Make.defs, os/kernel/pthread/pthread.h, os/kernel/pthread/pthread_exit.c, os/kernel/pthread/pthread_getspecific.c, os/kernel/pthread/pthread_keycreate.c, os/kernel/pthread/pthread_keydelete.c, os/kernel/pthread/pthread_setspecific.c
kernel/pthread: modify operation of pthread key
Currently pthread key supports only create, not delete.
It causes limitation of pthread key usages, only first CONFIG_NPTHREAD_KEYS
number keys are working.
This commit supports deleting key so that this fixs above issue.
Here is results of simple exmaple using pthread key on this commit:
key1 create!! ret = 0, key = 0
key2 create!! ret = 0, key = 1
key3 create!! ret = 0, key = 2
key4 create!! ret = 0, key = 3
key5 create!! ret = 11, key = 33945344
key2 set!! ret = 0
key1 get!! ret = -369098745
key2 get!! ret = 123
key3 get!! ret = -369098745
key2 delete!! ret = 0
key2 get!! ret = -369098745
key6 create!! ret = 0, key = 1
key6 get!! ret = -369098745
key6 set!! ret = 0
key6 get!! ret = 123
=> kernel/pthread: modify operation of pthread key

framework/src/st_things/st_things_request_handler.c, framework/src/st_things/things_stack/framework/things_data_manager.c, framework/src/st_things/things_stack/framework/things_data_manager.h
To generate the response of resource,
the function created double pointer and allocate some memories.
But these memory had not freed.
=> framework/st_things : Fix memory leak.

framework/src/st_things/st_things_logger.c, framework/src/st_things/st_things_logger.h
- To measure memory usage by module, change malloc to util_malloc (st_things_util)
- Remove Tizen Define
=> framework/st_things : change "malloc" to "util_malloc"

os/drivers/audio/alc5658.c, os/drivers/audio/alc5658.h
ALC5658 thru 3.5mm jack at present works with fixed volume settings.
This commit allows to change the volume of alc5658 for 3.5mm jack ONLY.
=> Audio: add support for changing volume settings for ALC5658 codec

os/include/net/lwip/mem.h
If lwip is set to use system malloc() then it doesn't succeed,
because it fails to find free() definition.
It will find free definition by including stdlib.h
=> network/lwip: fix the build error in lwip configuration.

build/configs/qemu/qemu-2.12.0-rc1_16m_ram_size.patch, build/configs/qemu/qemu-2.12.0-rc1_1m_ram_size.patch
1) Check for SUPPORT_SDRAM flag was not done properly.
Same has been fixed and publishing the correct patches.
2) Prepared the patch with latest qemu [ 2.12.0-rc1 ] source code clone
=> Qemu: Fix SUPPORT_SDRAM flag usage error

framework/src/st_things/things_stack/framework/things_data_manager.c, framework/src/st_things/things_stack/framework/things_data_manager.h
- it does not need to set it by user
The Iotivity version must use the embedded version.
=> framework/st_things : remove spec_ver & data_model_ver parsing logic

framework/src/st_things/st_things_request_handler.c, framework/src/st_things/st_things_request_handler_collection.c
OCRepSet/Add*AsOwner function doesn't allocated memory when build the response payload.
So, user should allocate the memory for payload but user can't free.
In order to ignore this issue , We can use OCRep* instead of OCRepSet/Add*AsOwner. Therefore we should care of the pointers to avoid memory leak.
=> framework/st_things : Changes OCRepSet/Add*AsOwner to OCRep*.

os/mm/mm_heap/mm_heapinfo.c
for strncmp() and strlen, #include <string.h> is needed, but omitted
=> mm/heapinfo : Add omitted header include

external/grpc/Kconfig.protocol, external/grpc/src/core/tsi/ssl_transport_security.cc
- Change process of handshake.
- Integrate server-side hs and client-side hs.
- Extract SSL context initialize function.
- Remove in_ssl_buffer (saved 16KB heap memory)
=> external/grpc: refactoring transport security interface

external/include/libcxx/cstddef, external/include/libcxx/cstdio, external/include/libcxx/ctime
This patch updates C Standard Library headers(cstdio, etc ...) in libcxx
to add missing functions.
=> include/libcxx : support ptrdifft_t, time*, remove functions

os/tools/configure.sh
- Execute build configuration tool from top directory.
- If build configuration is already done, then report the same to user.
- Add informational echo statements.
This patch is back-ported from Nuttx.
=> tools: Add new features to build configuration tool

apps/examples/wifi_manager_sample/wm_test.c
when scan is executed, if scan result is  NULL, the crash has occurred. 
BR,  HJ Lee.
=> fixed crash when scan done

os/kernel/group/group_join.c, os/kernel/pthread/pthread_create.c
Hard coded return values have been assigned instead of actual return value.
This patch address it by assigning the correct return values.
=> kernel/pthread : Assign correct return values

external/webclient/webclient.c
- webclient.c:1064:19: error: comparison of constant '-1' with boolean expression is always false [-Werror=bool-compare]
if (read_finish == HTTP_ERROR) {
^~
cc1: all warnings being treated as errors
- This patch is to change the data type of 'read_finish' as conditions compare boolean and '-1'
=> Fix a build error in webclient

external/iotivity/iotivity_1.2-rel/resource/c_common/SConscript
strings.h is not supported, hence removing it.
=> iotivity : remove unsupported strings.h for tizenrt

external/gmock/gtest/include/gtest/internal/gtest-internal.h, external/gmock/gtest/include/gtest/internal/gtest-port.h, external/gmock/gtest/src/gtest.cc, external/gmock/src/gmock-spec-builders.cc
- Apply GTEST_OS_TIZENRT in gtest
=> external/gmock : Add macros indicating the current platform

build/configs/artik055s/scripts/flash.ld
Without 'KEEP' expression,
C++ features don't work out.
=> modify flash_ld for c++

apps/examples/testcase/le_tc/kernel/Kconfig, apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
To run clock tc, CONFIG_SYSTEM_TIME64 is not mandatory.
This dependancy makes wrong selection on config and causes
compilation error when that config is disabled.
le_tc/kernel/kernel_tc_main.c: In function 'tc_kernel_main':
le_tc/kernel/kernel_tc_main.c:48:2: error: #error CONFIG_SYSTEM_TIME64 is needed for testing CLOCK TC
#error CONFIG_SYSTEM_TIME64 is needed for testing CLOCK TC
^~~~~
Makefile:121: recipe for target 'kernel_tc_main.o' failed
=> testcase/kernel: remove unncessary clock dependancy

external/mbedtls/debug.c
- Remove '#if' statement for general debugging function
=> external/mbedtls : enable debugging function call in mbedtls

framework/src/wifi_manager/wifi_manager.c
- Add logic to ensure callback for scannig (scan_ap_done) is declared
- Handling ENT_DEINIT in RECONNECTED state
- Add logic to ensure wifi_manager_info_s is not null when it is called
=> framework/wifi_manager: wifi_manager bug fix

apps/examples/testcase/le_tc/network/itc_net_connect.c, apps/examples/testcase/le_tc/network/itc_net_inet.c, apps/examples/testcase/le_tc/network/itc_net_setsockopt.c, apps/examples/testcase/le_tc/network/tc_net_getpeername.c, apps/examples/testcase/le_tc/network/tc_net_getsockopt.c, apps/examples/testcase/le_tc/network/tc_net_inet.c, apps/examples/testcase/le_tc/network/tc_net_recv.c, apps/examples/testcase/le_tc/network/tc_net_recvfrom.c, apps/examples/testcase/le_tc/network/tc_net_setsockopt.c, os/net/socket/bsd_socket_api.c
server_connect()
itc_net_inet_ntop_p()
tc_net_getsockopt_multicast_ttl_loop_p()
tc_net_getsockopt_multicast_ttl_loop_own_p()
tc_net_getsockopt_multicast_ttl_p()
tc_net_inet_ntop()
: bugs fixed that cause wrong results.
itc_net_setsockopt_p_reuseport()
tc_net_setsockopt_reuseport_p()
: commented out as SO_REUSEPORT option is unimplemented.
It will be added by the next release.
tc_net_getpeername_p1()
tc_net_getpeername_udp_p()
: wrong tcs removed. getpeername() returns error after close().
tc_net_recv_shutdown_n()
tc_net_recvfrom_tcp_conn_n()
: expected returns changed.
*** How to Test**
verified using artik053/tc config
menuconfig
Networking Support > LwIP options
> select "IPv6 support"
Networking Support > LwIP options > IPv6 support > Socket support
> select "Enable send timeout socket …
=> Modify network tc according to lwip-2.0.2

framework/src/media/MediaPlayerImpl.cpp
InputDataSource.open() returns InputDataSource.isPrepare()
Remove unnecessary line
=> MediaPlayerImpl: Remove duplicated function call

external/dhcpc/dhcpc.c
As lwip is upgrade to 2.0, the way dns server is set is changed.
The commit apply the way lwip 2.0 provided to set dns server properly.
=> external/dhcpc: fix dns setting issue

apps/examples/testcase/Kconfig, apps/examples/testcase/Makefile, apps/examples/testcase/ta_tc/media/utc/Kconfig, apps/examples/testcase/ta_tc/media/utc/Make.defs, apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp, apps/examples/testcase/tc_common.h, apps/examples/testcase/tc_main.c
modified the environment files to use gtest,
and inserted the skeleton code for media utc development.
=> testcase : add TC for media framework

README.md, docs/TroubleShooting.md
- GCC version has been updated from 4.9.3 to 6.3.1.
- refer to https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads/6-2017-q1-update for download and information.
=> Apply the toolchain version update

apps/examples/st_things/st_things_sample_main.c
- st things framework supports real time sync through NTP.
Therefore, this logic is not necessary.
=> app/st_things : remove time setting logic

external/dhcpd/dhcpd.c
dhcpd_stop & dhcpd_start bug fix
- reset g_dhcpd_running variable when dhcp server is destroyed
- set g_dhcpd_running variable after dhcp server is actually running
- change blocking range of dhcpd_stop & dhcpd_start
=> network/dhcpd: dhcpd bug fix 

os/include/tinyara/pm/pm.h, os/pm/Makefile, os/pm/pm.h, os/pm/pm_test.c, os/pm/pm_unregister.c
add pm_unregister support for pm framework (Backport from Nuttx).
This function is called by a device driver in order to unregister
previously registered power management event callbacks.
Signed-off-by: Shadakshari KP <shari.kps@samsung.com>
=> pm: add pm_unregister

os/kernel/sched/sched_processtimer.c
wd_timer()'s callback function can change current running task and hence it must be called after the time slice check.
The time slice check will decrement the currently running task's time slice count.
When context switch occurs before decrementing the slice count, then the newly started task will lost one slice count before it even has a chance to run.
This is patch is back ported from Nuttx.
=> kernel/sched: Change ordering of round-robin time slice check and processing of wdog timers

apps/examples/testcase/le_tc/drivers/tc_loop.c, apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c, apps/examples/testcase/le_tc/kernel/tc_libc_timer.c, apps/examples/testcase/le_tc/kernel/tc_pthread.c
testcase/drivers : Add check logic for fd when open
testcase/fs : Remove unnecessary close() and  Add cleanup for fd, buf
testcase/libc_timer : Remove unnecessary return check logic
testcase/pthread : Add return check logic for pthread_mutexattr_init
=> Fix Svace issue : drivers, fs, libc_timer, pthread

framework/src/media/MediaRecorderImpl.cpp, framework/src/media/RecorderObserverWorker.cpp, framework/src/media/RecorderWorker.cpp
1. fix wrong reference count for recorder observerworker
2. add missing function call for observer
=> media : bug fix for MediaRecorder

os/arch/arm/src/artik05x/src/Makefile
File name was changed to artik05x_crashdump.c, but Makefile is not applied.
=> artik05x/Makefile : Fix typo from artik053 to artik05x for ramdump

framework/src/st_things/st_things_request_handler.c, framework/src/st_things/st_things_request_handler_collection.c
In add_common_props func., We have used 'OCRepPayloadAddResourceType' and 'OCRepPayloadAddInterface'.
These function has copied memory to use internally.
So, the caller function has to free the parameters.
=> framework/st_things: Fix memory leak.

apps/examples/testcase/le_tc/kernel/tc_pthread.c, apps/examples/testcase/le_tc/kernel/tc_timer.c, os/kernel/signal/sig_allocatependingsigaction.c, os/kernel/signal/sig_dispatch.c, os/kernel/timer/timer_release.c, os/mm/mm_heap/mm_heapinfo.c
1. kernel/timer: move a location of marking not in use
2. mm/mm_heap: check NULL dereferencing on sched_gettcb
3. kernel/signal: remove duplicated checking conditional
4. testcase/kernel/pthread: check return value of function
5. estcase/kernel/timer: check return value of function
=> fix SVACE issue on kernel side

apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/system/utils/fscmd.c
- UGID 160578 add return check when write
- UGID 160979 use strlen instead of sizeof for write
=> apps/fs: Fix svace issue

framework/src/st_things/things_stack/things_stack.c
- If easysetup is not complete and there is no svrdb (initial) initialize fail
=> framework/st_things : Resolves issues when svr db is missing

apps/examples/testcase/le_tc/network/Kconfig
removed tests : dup() api, ITC dup() api, ITC fcntl()
=> Exclude network testcases that are not supported

framework/src/media/MediaRecorder.cpp
only a function definition, and no implementation added
=> media : add missing function for getstate

apps/examples/testcase/le_tc/filesystem/fs_main.c
free(buf) caues filesystem testcase stuck after printing
"[tc_libc_stdio_stdsostream] PASS" always.
But missing free causes memory leak, we should fix it later.
=> testcase/filesystem: not free allocated memory on tc_driver_mtd_ftl_ops

external/curl/curl_config.h
@juitem , @sunghan-chang, @pillip8282 @bhargava-cs 
Please review the PR. This is to resolve following build error.
"In file included from curl_setup.h:638:0,
from sendf.c:23:
sendf.c: In function 'Curl_send_plain':
curl_setup_once.h:123:22: error: 'MSG_NOSIGNAL' undeclared (first use in this function)
#define SEND_4TH_ARG MSG_NOSIGNAL
"
=> Disable MSG_NOSIGNAL in curl

.clang-format, framework/include/media/MediaPlayer.h, framework/include/media/MediaRecorder.h
[M16] Open braces for enum, union and struct go on the same line
=> tools: Apply M16 rule at clang-format file

os/tools/README.txt, tools/HowToUseFormatter.md, tools/cformatter.sh, tools/cxxformatter.sh
1. Move existing c formatter from os/tools to tools.
Formatter is not only for os. Tools folder is approprietary location.
2. Add new script to run c++ formatter which use clang-format
To give same usages with c, make a new script which has same usages.
3. Add new README to give information of formatter
4. Check existance of necessary package on ubuntu before excuting
=> tools: move a location of formatter, make a script of c++, add README

external/grpc/README.md
Add documentation explaining how to install grpc-cpp-plugin, which is essential for generating C++ Class implementation for protobuf.
=> Add documentation on grpc essential plugins

external/curl/curl_config.h
TizenRT does not have sys/param.h header so that we should
not define HAVE_SYS_PARAM_H.
This commit fixs compilation error.
CC:  http.c
In file included from /gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/machine/endian.h:5:0,
from /gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/sys/param.h:7,
from http.c:45:
/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/sys/_types.h:168:5: error: unknown type name 'wint_t'
wint_t __wch;
^~~~~~
Makefile:64: recipe for target 'curl_http.o' failed
=> external/curl: disable HAVE_SYS_PARAM_H definition

apps/examples/cy4390x_demo/Kconfig
cy4390x_demo app is valid when cy4390x board is selected.
Let's make a dependancy between EXAMPLES_CY4390x_DEMO and ARCH_BOARD_CY4390x.
It prevents compilation error and removes unnecessary menu on menuconfig.
=> examples/cy4390x_demo: add a dependancy with ARCH_BOARD_CY4390x

apps/examples/testcase/ta_tc/media/utc/utc_media_common.h, apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_recorder.cpp
1. add tc, which is a separate recorder and datasource
2. add tc for datasource constructor
3. add tc for get and set functions.
=> media: add tc for media datasource

framework/src/media/MediaRecorderImpl.h, framework/src/media/PlayerObserverWorker.h
Open braces for enum go on the same line
=> media: Fix coding rule violation in media

framework/include/iotbus/iotbus_gpio.h, framework/include/tinyalsa/tinyalsa.h, framework/include/wifi_manager/wifi_manager.h
Current TizenRT API version is "TizenRT v2.0 PRE", not "PRE PRE".
This commit fixs above wrong version.
=> framework/iotbus,tinyalsa,wifi_manager: fix wrong version of API

docs/TroubleShooting.md
It is easy to meet build breaks on proto buffers.
This commit shows error and how to resolve it.
=> docs/troubleshooting: add an issue on building Proto buffers

framework/src/media/audio/audio_manager.c
- The maximum volume of the target hardware is stored soundly.
- The current volume is scaled by changing the maximum volume locally.
=> Adjust a volume scaling logic in audio manager

framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaRecorderImpl.cpp
observer stopWorker should be executed if observer is not nullptr
=> media: Do observer stopWorker if observer is set

framework/src/media/MediaRecorderImpl.cpp
On the user side, use mCurstate,
On the operator side, use getState and setState
so, synchronized using lock_guard for state
=> media : add missing lock_guard for state

apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c, apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
Apply manual flag for manual testcase of audio framework 
List of Manual Testcase :
itc_audio_pcm_readi_p
itc_audio_pcm_readi_n
itc_audio_pcm_writei_p
itc_audio_pcm_writei_n
utc_audio_pcm_readi_p
utc_audio_pcm_readi_n
utc_audio_pcm_writei_p
utc_audio_pcm_drain_p
utc_audio_pcm_writei_n
utc_audio_pcm_drain_n
utc_audio_pcm_drop_p
utc_audio_pcm_drop_n
utc_audio_pcm_avail_update_n
utc_audio_pcm_wait_n
utc_audio_pcm_begin_n
utc_audio_pcm_commit_n
utc_audio_pcm_mmap_read_n
utc_audio_pcm_mmap_write_n
utc_audio_pcm_avail_update_p
utc_audio_pcm_wait_p
utc_audio_pcm_begin_p
utc_audio_pcm_commit_p
utc_audio_pcm_mmap_read_p
utc_audio_pcm_mmap_write_p
Signed-off-by: sri <sri@s.sa.corp.samsungelectronics.net>
=> examples/testcase/audio: Apply manual flag for testcase of audio

build/configs/artik053/README.md, build/configs/artik053s/README.md, build/configs/artik055s/README.md
There is no description about how to use GDB on ARTIK05x.
This commit helps user how to do it.
=> configs/artik053, 3s, 55s: add how to use GDB tab on README

framework/src/st_things/st_things_request_handler.c
Each variable shall be declared in a new line.
=> st_things: Fix coding rule violation in st_things

framework/src/media/RecorderWorker.cpp, framework/src/media/RecorderWorker.h
=> media: Remove unused var in RecorderWorker

apps/examples/mediaplayer/mediaplayer_main.cpp, apps/examples/mediarecorder/mediarecorder_main.cpp, framework/src/media/FileOutputDataSource.cpp, framework/src/media/InputDataSource.cpp, framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaPlayerImpl.h, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/MediaRecorderImpl.h, framework/src/media/PlayerObserverWorker.cpp, framework/src/media/PlayerWorker.cpp, framework/src/media/RecorderObserverWorker.cpp, framework/src/media/RecorderWorker.cpp
fix svace issuse for media
fix WGID numbers
218000	do not initialize class member variables
217922	do not checking the file open status
217938	do not initialize class members
217932	different return type
217933	different return type
217939	do not initialize class member variables
218001	do not initialize class member variables
218002	do not initialize class member variables
218004	do not initialize class member variables
218005	do not initialize class member variables
218006	do not initialize class member variables
218007	do not initialize class member variables
218008	do not initialize class member variables
218009	do not initialize class member variables
218010	do not initialize class member variables
=> media: fix svace issues

framework/src/media/MediaRecorderImpl.cpp
used a variable with the wrong name
=> media: bug fix for log in media recorder

os/kernel/init/os_bringup.c
WID:5130364 Return value of a function 'task_create' called at os_bringup.c:255 is not checked, but it is usually checked for this function (6/7).
=> init/os_bringup: Add return value check when creating app init task

framework/src/media/audio/audio_manager.c
- WGID 217988 and 217989 are fixed by deleting useless comparison operators for uint8_t variables.
=> media: Delete useless comparisions with unsigned int variables in audio manager

external/curl/Makefile, external/curl/formdata.c
@juitem , @sunghan-chang, @pillip8282, @bhargava-cs
Please review patch to fix curl warning
external/curl: Fix variadic function warning
Enums are promoted to 'int' when passed through '...'
va_arg function does not take enums as arguments.
Also this being the only warning, "CFLAGS += -Wno-error" has been
removed from MakeFile, in this commit.
Logs:
formdata.c: In function 'FormAdd':
formdata.c:306:31: warning: 'CURLformoption {aka enum <anonymous>}' is promoted to 'int' when passed through '...'
option = va_arg(params, CURLformoption);
^
formdata.c:306:31: note: (so you should pass 'int' not 'CURLformoption {aka enum <anonymous>}' to 'va_arg')
formdata.c:306:31: note: if this code is reached, the program will abort
=> external/curl: Fix variadic function warning

os/drivers/audio/alc5658.c
- Svace major issues (WGID 217986, 217987) are fixed.
=> media: Fix useless variable comparisons of volume settings in alc5658.c

framework/src/wifi_manager/wifi_utils.h, framework/src/wifi_manager/wpa_wifi_utils.c
framework/wifi_manager: change length of bssid in wifi_utils_ap_scan_info_s (fix svace issues)
- cleanup the length of ssid/bssid/MACaddress/passphrase 
- change bssid length, because wifi_utils_ap_scan_info_s structure should store bssid of scanned neighboring APs in the form of 'xx:xx:xx:xx:xx:xx', not MAC address of 6 bytes characters
- type casting for ssid_length (int8_t to unsigned int)
=> framework/wifi_manager: change length of bssid in wifi_utils_ap_scan_info_s

framework/src/media/audio/audio_manager.c
Before : Hard-coded sampling rate array for only ARTIK055s
After : Getting supported sampling data information from the device.
=> media: Getting supported sampling data from the device

os/audio/audio.c
- strcpy and strcat are changed into strncpy and strncat, respectively.
- Major svace issues (WGID 217990, 217991) are fixed.
=> media: Change unsafe string functions

os/fs/vfs/fs_open.c
Fixes setting of negative errno in fs_open.
This patch is back ported from Nuttx.
=> fs/vfs: Fix negative errno set

os/Kconfig.debug
DEBUG output message is valid only when core module is enabled.
As of now, it shows debug always even though core is disabled.
=> os/Kconfig.debug: make a dependancy between DEBUG and core module

apps/examples/testcase/ta_tc/media/utc/utc_media_player.cpp
Most audio card doesn't support 20000hz. So if we deliver the sample rate as 20000hz,
device would open as 22050hz, and resampling logic is working to convert to 22050 from 20000.
=> media: Modify samplerate value for resampler code coverage

external/curl/curl_threads.c, external/curl/curl_threads.h
@juitem , @sunghan-chang, @pillip8282, @bhargava-cs
Please review Curl-assert fix patch
Pthread created by curl for address resolution, needed a minimum stack
size of 4000 bytes. But only 2000 bytes were allocated, leading to assert.
Updated pthread stacksize to 4096 bytes in this commit.
=> external/curl: Increase stack size to 8K

.clang-format
The asterisk can be placed adjacent to either the variable name
=> .clang-format: Modify pointer alignment

external/slsi_wifi/slsi_wifi_api.c
framework/wifi_manager: change return value to avoid unreachable code
- Make a return variable to prevent scan callback function in slsi interface always returning SLSI_STATUS_SUCCESS, which causes unreachable code problem.
=> framework/wifi_manager: change return value to avoid unreachable code

framework/src/st_things/st_things_request_handler.c
Post handler can not when value is NULL and not writable.
=> framework/st_things : updates post request handling logic without mandatory attribute of resource.

framework/src/st_things/things_stack/framework/things_req_handler.c, framework/src/st_things/things_stack/things_stack.c
This is not common feature.
It is needed commercialization feature
when device easy setup can be abort by user.
=> framework/st_things : separates things abort functions as commercialization feature.

framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager.c
WID:5144327 After having been compared to NULL value at task_manager.c:412, pointer 'request_msg.data' is dereferenced at task_manager.c:264 by calling function 'strlen'.
WID:5144550 'return value of malloc(20)' may be null, and it is dereferenced at task_manager.c:279.
=> framework/task_manager: Fix dereferencing pointer

os/tools/configure.sh
To build some configuration set like grpc, st_things and so on,
some packages are needed to build or download.
When we configure configuration set, we can know what is needed.
TizenRT/os/tools$ ./configure.sh artik053/grpc
Copy build environment files
CAUTION!! To build artik053/grpc, protoc should be installed
Find details at https://github.com/Samsung/TizenRT/blob/master/external/protobuf/README.md
Configuartion is Done!
=> os/tools/configure.sh: check existence of necessary package to build

apps/examples/st_things/Kconfig, apps/examples/st_things/blink/blink.h
…nd EXAMPLES_IOTBUS_TEST.
Both features depends on EXAMPLES_IOTBUS_TEST_RED_LED_GPIO_NUM.
To solve this, EXAMPLES_IOTBUS_TEST_RED_LED_GPIO_NUM is changed to EXAMPLES_ST_THINGS_RED_LED_GPIO_NUM.
=> apps/st_things : rename GPIO config from iotbus to st_things

apps/examples/kernel_sample/workqueue.c, apps/examples/testcase/le_tc/kernel/tc_clock.c, apps/examples/testcase/le_tc/kernel/tc_semaphore.c, apps/examples/testcase/le_tc/kernel/tc_wqueue.c, apps/system/utils/kdbg_stackmonitor.c, apps/system/utils/kdbg_uptime.c, apps/system/utils/kdbg_utils.h, lib/libc/wqueue/work_queue.c, lib/libc/wqueue/work_usrthread.c
As clock_systimer() is removed from syscall, all apps and lib's should use clock() API.
So clock_systimer() is replaced with clock() And tc for clock_systimer() is removed.
=> Replace clock_systimer() with clock() API

apps/shell/tash_command.c
shell: modify cmdtask debug message
Unnecessary TASH debugging information continued to be output by
default. This patch changes the output level of that information.
=> shell: modify cmdtask debug message

framework/include/media/MediaPlayer.h, framework/src/media/MediaPlayer.cpp, framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaPlayerImpl.h
If setObserver called before PlayerWorker creation, setObserver returns
PLAYER_ERROR
=> media: Returns result of setObserver

os/net/lwip/src/netif/ppp/ppp.c, os/net/lwip/src/netif/slipif.c
NETIF_FLAG_POINTTOPOINT is deprecated from lwip 2.0.0 so removed it.
- It can cause compilation error during build so, fix it.
=> lwip: removed unused netif flag for point to point connections

external/audiocodec/streaming/internal_defs.h, external/audiocodec/streaming/player.c, external/audiocodec/streaming/rb.c, external/audiocodec/streaming/rbs.c, external/include/audiocodec/streaming/player.h, external/include/audiocodec/streaming/rb.h, external/include/audiocodec/streaming/rbs.h
@Taejun-Kwon @sunghan-chang 
1. Correct codeing rule, and clean code.
format code with os/tools/formatter.sh,
remove unused code,
define macros to replace constant values,
delete unnecessary fucntion params,
update descriptions of structure and interfaces.
2. Use media framework debug methods to print log.
3. Add below new interfaces of audiocodec/streaming/player:
// new added ...
int pv_player_get_audio_type(pv_player_p player);
int pv_player_init_decoder(pv_player_p player, int audio_type);
bool pv_player_get_frame(pv_player_p player);
int pv_player_frame_decode(pv_player_p player, pcm_data_p pcm);
// to replace ...
int _get_audio_type(rbstream_p rbsp);
bool _get_frame(pv_player_p player);
int _init_decoder(pv_player_p player);
int _frame_decoder(pv_player_p player, pcm_data_p pcm);
=> audiocodec/streaming/*: Clean code and add new interfaces

lib/libc/pthread/pthread_mutexattrinit.c
if CONFIG_PTHREAD_MUTEX_UNSAFE is not enabled, pthread_mutexattrinit doesn't initialize the robust member.
So make initialization for robust to PTHREAD_MUTEX_ROBUST
=> libc/mutex: Modify the initialization for mutex attr robust

apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
Fix Svace issue: 218040, 218041
'offset' is unsigned int. So, always equal or greater than zero.
=> media: Remove no effect macro

apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
Below utc are included:
utc_media_FileInputDataSource_getChannels_p(),
utc_media_FileInputDataSource_getSampleRate_p(),
utc_media_FileInputDataSource_getPcmFormat_p(),
utc_media_FileInputDataSource_setChannels_p(),
utc_media_FileInputDataSource_setSampleRate_p(),
utc_media_FileInputDataSource_setPcmFormat_p(),
utc_media_FileInputDataSource_open_p(),
utc_media_FileInputDataSource_close_p(),
utc_media_FileInputDataSource_isPrepare_p(),
utc_media_FileInputDataSource_read_p(),
utc_media_FileInputDataSource_readAt_p(),
=> ta_tc/media: Add FileInputDataSource positive utc

framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaRecorderImpl.cpp
Modified to call stopWorker according to
the result of destroyRecorder function.
=> media: bug fix for media destroy api

os/fs/driver/mtd/mtd_config.c
When kmm_malloc() fails, it returns OK instead of -ENOMEM.
=> driver/mtd: Fix wrong return value in mtdconfig_register

apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
1. modify tc for mediarecoder apis.
2. modify tc for fileoutputdatasource apis.
modified it with tc which does not use gmock and gtest
=> media: modify tc for media recorder

apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c
updated testcase's :
itc_audio_pcm_get_subdevice_p : updated compared value 0 -> 1
itc_audio_pcm_is_ready_n_after_close : add "g_pcm = NULL;" after close api to deallocated memory
itc_audio_pcm_get_config_n_after_close : add "g_pcm = NULL;" after close api to deallocated memory
itc_audio_pcm_get_channels_n_after_close : add "g_pcm = NULL;" after close api to deallocated memory
itc_audio_pcm_get_rate_n_after_close : add "g_pcm = NULL;" after close api to deallocated memory
itc_audio_pcm_get_format_n_after_close : add "g_pcm = NULL;" after close api to deallocated memory
itc_audio_pcm_get_file_descriptor_n_after_close : add "g_pcm = NULL;" after close api to deallocated memory
itc_audio_pcm_get_buffer_size_n_after_close : add "g_pcm = NULL;" after close api to deallocated memory …
=> testcase/audio/itc: update ITC testcase of audio framework

apps/examples/testcase/le_tc/kernel/tc_sched.c
Line 399 in tc_sched.c is for checking wrong pid, so change to -1 which is not valid for pid
=> le_tc/sched: Modify wrong param for pid in waitpid

os/kernel/group/group_create.c
if defined CONFIG_SCHED_WAITPID and not defined CONFIG_SCHED_HAVE_PARENT,
tg_exitsem in task_group_s is used for waitpid, but not initialized when creating task.
=> kernel/group: Add sem_init for tg_exitsem

lib/libc/Kconfig
Turn this feature on by default.
Instead, it will be enabled only in limited configurations
=> libc: Enable LIBC_SCANSET by default in Kconfig

apps/examples/wifi_manager_sample/wm_test.c
it make crash when ssid or password is more than 32 or 64 at wm_softap_start()
=> example/wifi_maanger: fix an overflow issue of an input parameter

apps/examples/testcase/le_tc/kernel/tc_sched.c
If pid is equal to (pid_t)-1, status is requested for any child process in waitpid.
So -1 cannot be a invalid pid in waitpid
=> testcase/tc_sched: Redefine INVALID_PID to -2 and modify waitpid tc

os/include/sys/wait.h, os/kernel/sched/sched_waitpid.c
for waitpid, pid which is less than -1, equal to 0 is Not Supported yet
=> sched/waitpid : Add description for not supported param

framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaRecorderImpl.cpp
add missing logic for nullptr case in setObserver
1. first, mRecorderObserver is not null case
2. second, observer is not null case
=> media : add logic for nullptr case in setObserver

apps/examples/testcase/le_tc/filesystem/fs_main.c, lib/libc/stdio/lib_fopen.c, os/fs/dirent/fs_closedir.c, os/fs/dirent/fs_opendir.c, os/fs/smartfs/smartfs_smart.c, os/fs/vfs/fs_lseek.c, os/fs/vfs/fs_mkdir.c
fs_main.c
1. tc_fs_vfs_lseek
- fd is not closed when open is called below.
2. tc_fs_vfs_mkdir
- readdir returns a pointer to a direct structre and closedir release it.
so returned dirent is not valid after calling closedir.
lib_fopen.c
- If mode value is an empty string, it should return ERROR with errno, EINVAL.
fs_closedir.c
- Before free memories, initialzation is needed because free function doesn't delete somethings in that region.
fs_opendir.c
- If name is an empty string, it should return ERROR with errno, ENOENT.
- Refer to Posix API in http://pubs.opengroup.org/onlinepubs/9699919799/
smartfs_smart.c
1. smartfs_seek_internal
- If whence is not one of SEEK_SET, SEEK_CUR, SEEK_END, it should return ERROR with errno, EINVAL.
- Refer to Posix API in …
=> Fix filesystem issues

apps/examples/testcase/le_tc/filesystem/itc_fs.c
change testcase "itc_fs_vfs_mount_p_read_mode" :
1. change TC_ASSERT_NEQ_CLEANUP to TC_ASSERT_EQ_CLEANUP
2. add rmdir(VFS_FOLDER_PATH) before umount
Signed-off-by: Sameer Gautam <sameer.g1@samsung.com>
=> apps/testcase/filesystem: change conditional check of ITC of filesystem

os/kernel/pthread/pthread_keycreate.c, os/kernel/pthread/pthread_keydelete.c
pthread_key_create and delete APIs are only for pthread type tcb
=> os/pthread: Add DEBUGASSERT for checking tcb type

os/kernel/pthread/pthread_keycreate.c, os/kernel/pthread/pthread_keydelete.c
In present implementation, pthread_key_delete and destructor for key deletion are supported.
=> kernel/pthread: Modify comment for pthread_key create and delete APIs

apps/examples/testcase/le_tc/network/itc_net_connect.c, apps/examples/testcase/le_tc/network/itc_net_setsockopt.c, apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
Changes are as below:
itc_net_connect.c     -> 1. Memory allocation of *pret was not checked for proper memory allocation
2. return value of setsockopt() API not checked
3. wrong parameter in memset API
itc_net_setsockopt.c  -> 1. return value of socket() API not checked
itc_arastorage_main.c  ->1. return value of db_exec() API not checked
2. used sprintf instead of snprintf
3. return value of cursor_get_count() API not checked
=> apps/exaple/testcase/ : fix svace issue for network and arastorage ITC

apps/examples/testcase/le_tc/network/itc_net_connect.c
Changes are as below:
itc_net_connect.c     -> 1. removed unsupported macro "SO_REUSEPORT"for setcockopt API
=> apps/example/testcase/ : removed unsupported Macro SO_REUSEPORT

external/libcxx-test/std/thread/tc_thread.cpp
Try lock may not always get succeeded.
Hence, few try lock tc's might fail sometimes.
So, few tc's are not required.
=> external/libcxx-test: Update Thread Testcases

external/webserver/http_client.c
Fix an abort Issue in WGET
with this patch, data abort at the end of file transmission is resolved.
=> external/webserver: Fix data length miscalculation issue

docs/HowToUseAudio.md
- Naming rules for alc5658 chip are added to 'HowToUseAudio.md'.
=> media: Add descriptions for naming audio drivers

external/iotivity/iotivity_1.2-rel/build_common/tizenrt/SConscript, external/iotivity/iotivity_1.2-rel/resource/c_common/SConscript
fix that iotivity refers /usr/lib/include/
Iotivity on TizenRT should not refer compiler's header files
And iotivity refered header files that TizenRT doesn't support.
because thoes are in system include path.
=> external/iotivity: fix build configurations

framework/src/st_things/Kconfig, os/arch/arm/src/armv7-r/mpu.h
1. arch/armv7-r: fix wrong config name, CONFIG_ARMV7R_HAVE_ICACHE 
2. framework/st_things: use presentative config for ARTIK board
=> arch/armv7-r, framework/st_things: use appropriate config

docs/HowToUseMultiHeap.md, os/arch/Kconfig.chip, os/arch/arm/src/common/up_allocateheap.c, os/mm/Kconfig
By user decision or hw limitation, heap regions can be separated.
As of now, HEAPx_BASE and HEAPx_SIZE supports that.
But, config of first heap region is RAM_START and RAM_SIZE.
Because they have different naming rules and are at different locations,
it is difficult to know.
Let's move additional heap configurations to arch and rename them.
Because usually architecture determines heap regions.
=> arch: move and rename configs to support additional heap regions

framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager.c, os/drivers/task_manager/task_manager_drv.c, os/kernel/signal/Make.defs, os/kernel/signal/sig_is_handler_registered.c
If handler is not registered, unicast cannot work properly.
=> framework/task_manager: Add checking handler logic for unicast

framework/src/media/MediaWorker.cpp, framework/src/media/MediaWorker.h
increaseRefCnt, decreaseRefCnt can be replace with simple code.
And these methods are only used once.
=> media: Remove redundant method in MediaWorker

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/Kconfig, framework/src/task_manager/taskmgr_interface.c
When request to terminate or restart, resource collection is needed.
So if user registered the resource collection handler, task_manager will call that handler.
=> framework/task_manager: Add resource collection logic

apps/system/sysdbg/sysdbgapp_init.c
Sometimes, when args[2] is not passed in TASH
ex:  TASH>>sysdbg help
length of args[0] is 6
length of args[1] is 4 and
length of args[2] is 32 , even when args[2] is not passed at all
This causes program to enter wrong logic and always returns error.
This patch address this issue by checking the args length based on
number of arguments passed.
=> apps/sysdbg: Fix the logic of handling the args lg

apps/examples/wifi_manager_sample/Kconfig, apps/examples/wifi_manager_sample/rt_perf.c, apps/examples/wifi_manager_sample/wm_test_stress.c
- Add a configuration parameter of test trial number
- Modify output print messages
- Initialize min/max of execution time
=> example/wifi_manager: Revision of wifi_manager stress test

build/configs/artik053/README.md, build/configs/artik053s/README.md, build/configs/artik055s/README.md, build/configs/sidk_s5jt200/README.md, tools/fs/README_ROMFS.md
1. There is no [using download script] tab. It should be
[How to download a binary].
2. To run menuconfig, os folder is right, not on $TIZENRT_BASEDIR.
=> configs, tools: fix incorrect information on README

external/webclient/webclient.c
There is an intermittent case where recv is called one more time after receiving all files.
In this case, returning 0 from the recv function is not an error.
If all data is received, the return value is changed to WGET_OK.
=> external/webclient: Modify WGET return value

apps/examples/testcase/le_tc/filesystem/fs_main.c
it didn't follow tc naming policy, add 'tc' as a prefix
=> testcase/fs : fix fuction name of readdir_r & telldir in utc

build/configs/artik05x/artik05x_download.sh, build/configs/sidk_s5jt200/sidk_s5jt200_download.sh
This patch supports auto reset after flashing all the built images on to the target.
It is better than pressing hardware reset button every time after flashing.
=> build/configs: support auto reset after download

apps/Make.defs
When builtin feature is enabled and priority and stacksize is not
configured in each application, let's use default values of
priority and stacksize which is defined in shell Kconfig instead
of hard-coded in apps/Make.defs.
=> apps/builtin: Use shell default values of priority and stacksize

apps/system/iperf/Makefile
- Since Iperf uses more stack size than that of a typical example,
an ASSERT can occur, when the builtin default is changed.
=> apps/example/iperf: Set priority and stacksize

apps/examples/mdns_test/mdns_main.c, apps/examples/testcase/ta_tc/device_management/itc/itc_dm_main.c, apps/examples/testcase/ta_tc/device_management/utc/utc_dm_main.c, apps/examples/wakaama_client/wakaama_client.c, external/include/slsi_wifi/slsi_wifi_api.h, external/wakaama/examples/client/connectivity_interface.c, framework/src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c
- Change the way to specify the interface name according to the configuration set by wifi manager, not forced to set 'wl1'
=> framework/wifi_manager: Unify control interface name

framework/src/media/audio/audio_manager.c
- Toss the buffer of each audio card to the resampler to reduce memcpy.
- Add logics to prevent xrun when the resampler is not used.
=> media: refactor resampler usages in audio manager

os/fs/fs_initialize.c
Fix wrong typo "/procfs", which should be "/proc" in fs_auto_mount().
=> fs: Fix wrong typo in fs_auto_mount

os/kernel/signal/sig_sethandler.c
sig_sethandler should set signal through argument
=> kernel/signal: Modify wrong signal assign in sig_sethandler

apps/platform/gnu/gnu_cxxinitialize.c, os/kernel/init/os_bringup.c
up_cxxinitialize is to perform initialization of the
static C++ class instances. All the static initializers
are put in init section(sinit <--> _einit) during build time
and before application start all these initializers must be
invoked by parsing init section.
But in case of Flat address space, all application's initializers are
put into init section of a single blob.
Hence up_cxxinitialize need not to be performed in each application start,
instead it can invoked during application init in os bringup.
This patch makes up_cxxinitialize to perfrom initialization only once and
any subsequent invokations, are ingored.
=> init : do up_cxxinitialize during application init

framework/src/media/audio/audio_manager.c, framework/src/media/audio/audio_manager.h
- The basic descriptions for get functions to calculate a byte size from a frame value and vice versa for both input and output streams are added.
=> media: add API descriptions for audio manager

lib/libc/stdio/lib_fclose.c
If flush failed during fclose, it doesn't return close's result.
But if disk is full, there's no way write contents anymore, so
File should be closed
=> fs/stdio : change return value as same as close if flush returns -ENOSPC

apps/examples/wifi_manager_sample/wm_test.c, framework/include/wifi_manager/wifi_manager.h
- Add WIFIMGR's string length definition.
- AP configuration structure should have a SSID with a length of WIFIMGR_SSID_LEN.
Some of them have a length of 33, which causes SVACE criticals.
=> framework/wifi_manager: Unification of SSID length 

apps/examples/task_manager_sample/action_manager.c, apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/Make.defs, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_set_unicast_cb.c, framework/src/task_manager/task_manager_start.c, framework/src/task_manager/task_manager_terminate.c, framework/src/task_manager/task_manager_unregister.c
1. modify task_manager_set_handler to task_manager_set_unicast_cb
2. modify unicast cb prototype to "void func(void *)"
3. apply api and cb prototype in tc and sample
=> framework/task_manager: Modify unicast callback API prototype and callback func type

os/kernel/Kconfig
SIGTM is used for specific functionality in task manager
=> kernel/Kconfig: Modify SIGTM explanation for pause, resume, unicast

apps/examples/task_manager_sample/action_manager.c
As task_manager_set_broadcast_handler() was changed into task_manager_set_broadcast_cb(), task_manager_sample is modified.
=> examples/task_manager_sample: Apply changed set broadcast call back API

apps/examples/testcase/le_tc/network/network_tc_main.c, apps/examples/testcase/le_tc/network/tc_net_bind.c, apps/examples/testcase/le_tc/network/tc_net_getpeername.c, apps/examples/testcase/le_tc/network/tc_net_getsockname.c, apps/examples/testcase/le_tc/network/tc_net_socket.c, os/include/net/lwip/sockets.h, os/net/socket/bsd_socket_api.c
- Remove socket protocols (and tc) not supported by lwip
- Provide a proper socket_argument_validation function to match
domain, type, and protocol correctly
- Modify tc contents (positive/negative) according to the socket protocol
=> network/tc: Domain, type, and protocol matching for socket API

framework/src/media/audio/audio_manager.c, framework/src/media/audio/audio_manager.h
- Static functions are grouped and moved to the upper position of public functions.
- Public functions are reordered following actual execution orders for readability.
=> media: rearrange API orders

lib/libc/Kconfig, lib/libc/stdio/lib_libvsprintf.c
As per standard, if precsion is not provided in printf, it should print
float values with default precision. This patch adds support for default
floating point precsion in printf
=> libc/stdio: Add support for floating point precision in printf

framework/include/task_manager/task_manager.h
In order to prevent a memory leakage problem when using task_manager_getinfo_with_name(), task_manager_getinfo_with_handle(), and task_manager_getinfo_with_group(), additional information were added on the header file.
Use task_manager_clean_inforlist() API after using the task_manager_getinfo_with_name() and task_manager_getinfo_with_group.
Use task_manager_clean_info() API after using the task_manager_getinfo_with_handle().
=> framework/include/task_manager: Add free method of getinfo features on their descriptions

apps/examples/task_manager_sample/user.c
In order to solve memory leakage problem, memory free procedure is added to the task manager sample.
(When task_manager_getinfo_with_name() API is used, use task_manager_clean_infolist() API to free allocated memory to solve memory leakage problem)
=> examples/task_manager_sample: Add calling clean_infolist after getinfo

os/drivers/testcase/testcase_drv.c
Add read/write APIs to testcase driver so that UTC apps can
open /dev/testcase to pass ioctls
=> Add read/write APIs to testcase driver

framework/include/media/FileInputDataSource.h, framework/include/media/FileOutputDataSource.h, framework/include/media/InputDataSource.h, framework/include/media/OutputDataSource.h, framework/include/media/SocketOutputDataSource.h, framework/src/media/Decoder.cpp, framework/src/media/FileInputDataSource.cpp, framework/src/media/FileOutputDataSource.cpp, framework/src/media/MediaPlayerImpl.cpp, framework/src/media/SocketOutputDataSource.cpp, framework/src/media/streaming/player.c, framework/src/media/streaming/player.h
@Taejun-Kwon @jarvisjang 
Decode multiple audio frames to fill read buffer fully.
Previously, Decoder just decode one frame once, and more than half of the audio buffer is free. 
If apply this modification, decoder will return data of required size.
In addition,  we change to use latest pv_player APIs from deprecated ones.
Add a new pv_player API: *size_t pv_player_get_frames(...)*
=> framework/media: Refine decoder buffer usage

apps/examples/testcase/le_tc/filesystem/fs_main.c, os/fs/vfs/fs_mkdir.c
When configured with `qemu/tc_64k` defconfig, following build errors occur,
```
vfs/fs_mkdir.c: In function 'mkdir':
vfs/fs_mkdir.c:164:4: error: implicit declaration of function 'memset'; did you mean 'sigset'? [-Werror=implicit-function-declaration]
vfs/fs_mkdir.c:165:4: error: implicit declaration of function 'strncpy' [-Werror=implicit-function-declaration]
le_tc/filesystem/fs_main.c: In function 'tc_fs_vfs_ioctl':
le_tc/filesystem/fs_main.c:1598:29: error: passing argument 3 of 'ioctl' makes integer from pointer without a cast [-Werror=int-conversion]
le_tc/filesystem/fs_main.c: In function 'tc_fs_vfs_ioctl':
le_tc/filesystem/fs_main.c:1596:8: error: implicit declaration of function 'ioctl'; did you mean 'prctl'? [-Werror=implicit-function-declaration]
le_tc/filesystem/fs_main.c: In …
```
=> Fix build errors

os/kernel/task/task.h, os/kernel/task/task_exithook.c, os/kernel/task/task_restart.c
If atexit and onexit are in task restart, we can hook function when restart the task, such as resource deallocation callback
=> kernel/task: Add calling atexit and onexit in task_restart

framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/audio/audio_manager.c, framework/src/media/audio/audio_manager.h
- A card mutex is added into each audio card struct.
- init_audio_stream_in/out() are added and the card mutex is initialized in those init functions.
- The card mutex is locked at the beginning and unlocked at the end in all functions.
=> media/audio: Add mutex logics to audio manager functions

apps/examples/testcase/le_tc/kernel/tc_mqueue.c
1.if no unlink, the allocated message queue is not freed.
2.for testing mq_unlink, mq_close should be called first.
=> testcase/kernel/mqueue: Add omitted mq_unlink and move mq_close before unlink

apps/examples/testcase/le_tc/kernel/tc_libc_timer.c, lib/libc/time/Make.defs, lib/libc/time/lib_strptime.c, os/include/time.h
- Prototypes of strptime() and difftime() are wrapped with CONFIG_ENABLE_IOTIVITY conditional. This conditional is removed as there is no such dependency exists.
- libc/time: Fix compilation error in strptime
- testcase/kernel: Add test case for difftime()
- testcase/kernel: Add test case for strptime() 
libc time tc result:
=> Remove wrong conditional config in libc time

apps/examples/testcase/le_tc/filesystem/fs_main.c, apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
- Fix blocking of fs testcase
- Fix failure of tc_fs_vfs_stat()
- Move procfs tc's from fs_main to tc_procfs_main
- Fix wrong usage of configs wrapper
- Modify mounting un-mounting of procfs
- Fix fs readdir() tc failure
=> Fix filesystem testcase issues

os/kernel/init/os_bringup.c
Previous commit which did cxxinitialize during os_do_appstart()
would cause crash in few scenarios.
If a task does cxxinitialize and creates a new c++ application task
and exits immediately then in newly created C++ task if iostream are used,
the task would crash.
It is because during cxxinitialize iostreams are initialized (ios_base::Init)
and during iostream initialization they refer console streams
(Ex: stdout, which are defined per task group: group->tg_streamlist)
and set those pointers in iostreams internal file pointers members.
Once the task which did cxxinitialize exits, it would destroy the streams as well
Hence if the newly created c++ task uses any iostreams(Ex: cout) would crash.
os_do_appstart can run as init kthread and would exit after application launch
and the above …
=> init : call cxxinit initializers from idle thread

apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp, framework/include/media/DataSource.h, framework/include/media/FileOutputDataSource.h, framework/include/media/OutputDataSource.h, framework/include/media/SocketOutputDataSource.h, framework/src/media/DataSource.cpp, framework/src/media/FileInputDataSource.cpp, framework/src/media/FileOutputDataSource.cpp, framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/OutputDataSource.cpp, framework/src/media/SocketOutputDataSource.cpp, framework/src/media/audio/audio_manager.c, framework/src/media/audio/audio_manager.h, os/drivers/audio/alc5658.c
1. Sync up parameter type in audio manager same as tinyalsa & audio driver
2. fix bug of read in FileInputDataSource, to return read size properly for pcm type
3. Add semaphore in configure logic in alc5658
4. remove unneccessary state checking routine in mediaplayer
=> media : sync parameter type refer to tinyalsa & audio driver

framework/src/st_things/things_stack/cloud/cloud_connector.c, framework/src/st_things/things_stack/framework/things_data_manager.c, framework/src/st_things/things_stack/framework/things_data_manager.h, framework/src/st_things/things_stack/things_def.h
… a hash map
- Logic changes to support only a single device because there are currently no multiple device requirements
- Define internal resource (easysetup, fota, etc.) as const str and change it to include in existing logic: Improvement of development convenience / readability
=> framework/st_things : Removing hash based device managing Logic

framework/src/media/FileInputDataSource.cpp, framework/src/media/FileOutputDataSource.cpp, framework/src/media/MediaQueue.h, framework/src/media/SocketOutputDataSource.cpp
MediaFramework should be built on TizenRT and Linux both.
Linux build is more strict than TizenRT.
=> media: Fix build error on linux

apps/examples/mediarecorder/mediarecorder_main.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp, framework/include/media/MediaPlayer.h, framework/include/media/MediaRecorder.h, framework/src/media/FileInputDataSource.cpp, framework/src/media/FileOutputDataSource.cpp, framework/src/media/MediaRecorder.cpp, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/MediaRecorderImpl.h
1. Apply setDuration API to make limitation of duration
2. Clean each api's reference
3. return EOF if buffer is null when write or read in datasource
=> media/recorder : add setDuration API

os/arch/arm/src/artik05x/Kconfig, os/arch/arm/src/sidk_s5jt200/Kconfig
This patch modifies Kconfig help to mention that AUTOMOUNT_USERFS_DEVNAME
will be changed when SMARTFS_MULTI_ROOT_DIRS is enabled.
Signed-off-by: Kavya <kavya.nunna@partner.samsung.com>
=> Modify Kconfig help for AUTOMOUNT_USERFS_DEVNAME

external/iotivity/Kconfig
- NET_SECURITY_TLS is needed to use tls in iotivity.
=> iotivity/Kconfig: Add the dependency of iotivity security

os/arch/arm/src/s5j/s5j_i2s.c, os/drivers/audio/alc5658.c
There is no logic where unset pause state of i2s
=> audio/i2s : unset pause state when shutdown

framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_state.c
1. Include <stdlib.h> to use malloc() and free()
2. Include <sys/ioctl.h> to use ioctl()
CC:  src/task_manager/task_manager_register.c
In file included from src/task_manager/task_manager_register.c:26:0:
src/task_manager/task_manager_register.c: In function 'task_manager_register':
src/task_manager/task_manager_internal.h:47:22: warning: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
#define TM_ALLOC(a)  malloc(a)
^
src/task_manager/task_manager_register.c:45:29: note: in expansion of macro 'TM_ALLOC'
request_msg.data = (void *)TM_ALLOC(strlen(name) + 1);
^~~~~~~~
src/task_manager/task_manager_internal.h:48:22: warning: implicit declaration of function 'free' [-Wimplicit-function-declaration]
#define TM_FREE(a)   free(a)
^ …
=> framework/task_manager: fix compilation warnings of missing header

apps/examples/testcase/le_tc/kernel/tc_libc_misc.c
The lib_dumpbuffer() uses lowsyslog so that serial logs can be
a mess. Let's add usleep() before testing it.
[tc_libc_misc_crc16part] PASS
_c_tl_liic_misb_crcc_miscSS
ltcilibc__iscdcru32mpbt]uffer (401_lb2c5mc8):
g: 000mple0
[t: lib53mis4_d14] d5SS3554e472d54697a656e5254                                    SAMSUNG-TizenRT
tc_libc_misc_lib_dumpbuffer (401b2640):
0000: 0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a 0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a ................ ................
=> testcase/kernel/misc: add usleep() before testing lib_dumpbuffer()

apps/system/utils/README.md
Printing messages of "heapinfo" was changed by commit fe27b22.
This commit changes an example of heapinfo result.
=> apps/utils/README: update "heapinfo" content for fe27b22

apps/examples/st_things/blink/contents/device_def.json, apps/examples/st_things/light/contents/device_def.json, framework/src/st_things/things_stack/cloud/cloud_connector.c, framework/src/st_things/things_stack/framework/things_data_manager.c, framework/src/st_things/things_stack/framework/things_data_manager.h
- The current manufacturerName is used as the MNID of the Samsung Account
VenderID is used as a VID.
Dev.Workspace has inconsistencies with the terms used in development.
Therefore, the manufactureName is MNID and the VenderID is VID.
=> framework/st_things : Change manufacturerID to MNID and venderID to VID

framework/src/st_things/things_stack/framework/things_data_manager.c
This patch fix mnid and vid setting bugs. When loading device
information from device_def.json, the mnid and vid are not stored to
variables due to invalid NULL check logic.
For example, if mnid is not NULL, copy mnid->valuestring to
g_device->mnid is not work. The vid also same.
Signed-off-by: Inho Oh <webispy@gmail.com>
=> framework/st_things: Fix bug for mnid, vid value

lib/libxx/libxx_cxa_atexit.cxx, lib/libxx/libxx_cxa_guard.cxx, lib/libxx/libxx_cxa_guard.hxx, os/include/tinyara/sched.h, os/include/unistd.h, os/kernel/Kconfig, os/kernel/group/group_create.c, os/kernel/task/task.h, os/kernel/task/task_atexit.c, os/kernel/task/task_exithook.c, os/kernel/task/task_onexit.c
1. Reset static object after destruction, to allow object construnction again.
2. There is a limitations in the current implementation that
only a single atexit/onexit function can be registered unless
CONFIG_SCHED_ATEXIT_MAX/CONFIG_SCHED_ONEXIT_MAX/ defines a
larger number. To overcome this limitation this patch removes the support of static
array of callbacks and keeps the callbacks in the dynamically allocated
space at runtime using dqueue.
=> Static object reset & handle atexit/onexit registration dynamically

framework/src/wifi_manager/wifi_profile.c
- Change sscanf to strncpy when the WiFi profile information is saved
- Change an order of the saved information to read SSID length
=> framework/wifi_manager: Chaning sscanf to strncpy for WiFi profile saving

external/webserver/http_client.c
strncat was being used without calculating the remaining length of the destination string buffer.
Prevent buffer overflow by calculating the remaining length of the destination string buffer.
=> external/webserver: Fix strncat() with calculating the remaining length

os/include/sys/types.h, os/include/wchar.h
Observed issue while building iotivity-constrained:
arm-none-eabi-gcc -c -o obj/cborencoder.o (...)
In file included from
.../gcc-arm-none-eabi-6-2017-q1-update/.../reent.h:15:0,
from
.../arm-none-eabi/include/math.h:5,
from ../../deps/tinycbor/src/compilersupport_p.h:40,
.../sys/_types.h:168:5: error: unknown type name 'wint_t'
wint_t __wch;
Bug: https://jira.iotivity.org/projects/LITE/issues/LITE-4
Change-Id: I328e902ad4320f4772af3b802e1fbea8239f5c61
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> os: Define wint_t in types.h

os/include/tinyara/sched.h, os/kernel/group/group_create.c, os/kernel/task/task_atexit.c, os/kernel/task/task_exithook.c, os/kernel/task/task_onexit.c
Changes:
1. Use single-linked queue insted of dqueue
2. Remove unnecessary condition checks
2. Minor coding style fixes
=> kernel : use single-linked queue in atexit & onexit

external/ntpclient/ntpclient.c
- #ifndef CONFIG_DISABLE_SIGNALS is a condition only for the ntpc_stop function.
=> ntpclient : Change location #endif of CONFIG_DISABLE_SIGNALS

external/websocket/websocket.c
This results in stack based buffer overflow of accept key variable which is declared as char[24]buffer.
This can lead to remote code execution using various techniques.
So I added logic that when copying data from HTTP headers check that the result will fit in the buffer.
=> external/websocket: Fix stack based buffer overflow in websocket

external/wakaama/core/er-coap-13/er-coap-13.h
Implementation of CoAP protocol used by Wakaama library is vulnerable to stack based buffer overflow attacks leading to remote code execution (RCE) triggered by single malformed CoAP packet.
The SET_OPTION macro should limit the number of CoAP option to the size of the options bitmap (COAP_OPTION_PROXY_URI/ OPTION_MAP_SIZE).
=> external/wakaama: Fix stack based buffer overflow in Wakaama

apps/examples/mediastreamer/mediastreamer_main.cpp, apps/examples/testcase/le_tc/tcp_tls/tcp_tls_stress.c, apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c, apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c, apps/examples/wifi_manager_sample/wm_test.c, apps/examples/wifi_manager_sample/wm_test_stress.c, framework/include/wifi_manager/wifi_manager.h, framework/src/st_things/things_stack/utils/things_network.c, framework/src/wifi_manager/wifi_manager.c
- Pass an additional parameter, wifi_manager_disconnect_to, to disconnect callback
in order for the callback function to distinguish
whether Wi-Fi Manager goes into RE(AUTO)CONNECT or not
- Add enum, wifi_manager_disconnect_to,  to distinguish RECONNECT and DISCONNECT
when calling disconnect callback
- Modify the location of link up/down messages passed to iotivity
- Modify all of the sta_disconnected callback functions used in the applications
=> framework/wifi_manager: Distinguish RECONNECT and DISCONNECT when callback

lib/libc/net/Make.defs
Observed issue while building master branch of IoT.js:
arm-none-eabi-ld (...) \
-o ".../tinyara" arm_vectortab.o  (...) \
.../TizenRT/os/../build/output/bin/tinyara.map
/build/output/libraries/libtuv.a(udp.c.obj): \
In function `uv__udp_maybe_deferred_bind':
.../libtuv/src/unix/udp.c:445: undefined reference to `in6addr_any'
Change-Id: I37d5a3a16d412682e1308dc8952faac54bd40a18
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> net: Add in6addr_any constant only if IPv6 enabled

framework/src/wifi_manager/wpa_wifi_utils.c
- Register scan callback for every scanning trial, because slsi driver deregisters scan callback after finishing scanning
=> framework/wifi_utils: Registration of scan callback for each scanning

framework/src/media/Make.defs
Reason: audio_decoder.h and audio_encoder.h has a dependency to media, but the files were added without the media feature.
=> media: Fix audio build error on extra configuration

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_set_callback.c, os/drivers/task_manager/task_manager_drv.c, os/include/tinyara/task_manager_internal.h, os/kernel/init/os_bringup.c, os/kernel/task/task_exithook.c
User can set stop and exit callback with Task Manager.
task_manager_set_termination_cb is changed to task_manager_set_exit_cb.
=> framework/task_manager: Support stop and exit callback

README.md, build/configs/artik05x/artik05x_cmn.sh, tools/fs/README_ROMFS.md
1. Update README.md  to provide TizenRT developement on Mac OS X HOST
2. Update romfs README to install genromfs from source which would work on both linux and Mac OS X
3. select HOST OS specific openocd and codesigner in artik05x
=> Mac OSX support

apps/system/utils/kdbg_date.c
The date command allows year within [1970,2106] and month, the day
of week allows 3 abbreviation characters.
It it difficult to know these limitations without messages.
=> apps/utils/date: add messages to show limitation of year, month and week

lib/libc/math/lib_gamma.c, lib/libc/math/libm.h
This patch removes duplicate definition of FORCE_EVAL in lib_gamma.c.
Also it updates the FORCE_EVAL to use UNUSED macro to fix 'unused variable' warning from compiler.
=> libc/math: Remove duplicate definition of FORCE_EVAL

os/fs/inode/fs_inodereserve.c
1. Fixed a problem where the generated file name was truncated if the generated file name was longer than the maximum length of the file name.
2. Fixed an issue where inode filename did not have a length limit even if file name length was limited.
=> filesystem/inode: Fix filename length check logic

apps/examples/testcase/Makefile, apps/examples/testcase/tc_main.c
The builtin supports a functionality to set priority and stacksize
to each ASYNC command. But tash does not do it on API side.
To allow setting each different value, register all of testcase
at Makefile when builtin is enabled.
=> testcase: register all of testcase at Makefile when builtin enabled

os/fs/tmpfs/fs_tmpfs.c
Fixes the logic in tmpfs_ioctl() that extracts the priv state structure from the file system structures.
It was not getting the right value and causing mmap() to fail.
This patch is back-ported from Nuttx.
=> fs/tmpfs: Fix tmpfs_ioctl() logic

apps/examples/testcase/le_tc/kernel/tc_libc_stdlib.c, lib/libc/stdlib/lib_rand.c, os/include/stdlib.h
Adds implementation of posix api's random() and srandom().
This patch is back-ported from Nuttx.
=> libc/stdlib: Add implementation of random() and srandom()

build/configs/artik053/.buildSpec.xml, build/configs/artik053s/.buildSpec.xml, build/configs/artik055s/.buildSpec.xml, build/configs/qemu/.buildSpec.xml, build/configs/sidk_s5jt200/.buildSpec.xml
V=1 means enabling echo of commands. But it is not needed at
normal build so that let's set it 3 to disable verbose logs.
FYI, 2 means enabling bug/verbose options in tools and scripts.
=> configs: change a build log level, V to 3

docs/HowToDevelopThingsUsingSTThings.md
- Fix link error through https://smartthings.developer.samsung.com internal reorganization
- Add device definition guide link
=> framework/st_things : Fix url link error in guide

os/net/lwip/src/api/sockets.c
- Since LWIP_IPV6 is always defined to differenciate IP version, ifdef is not allowed.
- Fix a problem of missing #if LWIP_IPV6 before using IPADDR6_INIT macro.
=> net/lwip: Fix bug of handling LWIP_IPV6

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_getinfo.c, framework/src/task_manager/task_manager_internal.h
1. framework/task_manager: Implement task_manager_getinfo_with_pid API
User can get task information by pid which is managed by task manager
2. Add positive and negative TCs for task_manager_getinfo_with_pid()
=> framework/task_manager: Implement task_manager_getinfo_with_pid API

apps/examples/testcase/le_tc/tcp_tls/tcp_tls_stress.c, apps/examples/wifi_manager_sample/wm_test.c, apps/examples/wifi_manager_sample/wm_test_stress.c, framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/wifi_manager.c, framework/src/wifi_manager/wifi_utils.h, framework/src/wifi_manager/wpa_wifi_utils.c
- Set the SSID and Passphrase string length to 33 and 65 bytes, respectively
- Insert null after strncpy, only when the string is not initialized (to null)
- In case WiFi Manager recieves callback msg (such as scanning result), check the SSID length not to be larger than 32
- Change SSID and Passphrase length condition in wm_test, wm_test_stress, and tcp_tls_stress (commit 
7a8937e)
=> framework/wifi_manager: Arrange SSID and Passphrase length

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_set_callback.c
Modify the termination cb type, corresponding APIs, and its TC.
1. Modify the termination cb type to deliver a data when it becomes set.
2. As the termination cb type is changed, corresponding APIs (task_manager_set_exit_cb and task_manager_set_stop_cb) are changed.
3. As the APIs are changed, corresponding TC is changed.
=> framework/task_manager: Modify the termination cb type

docs/TroubleShooting.md
Add trouble shooting case when user is using gperf3.1 and
kconfig-frontend-4.11.0.1
=> docs: Add a case when installing Kconfig-frontend

os/drivers/audio/alc5658.c
audio drivers require high priority for audio performance.
=> drivers/audio: change alc5658 driver to use high priority workqueue

os/net/lwip/src/core/tcp.c
- Initialize global union variable used in tcp of lwip
- Cypress board currently does not initialize variables during the flashing, this variable should be initialized in order to prevent false references
=> net/lwip: Add initialization of union variable in tcp

apps/system/utils/Kconfig, apps/system/utils/Makefile, apps/system/utils/kdbg_commands.h, apps/system/utils/kdbg_cpuload.c, apps/system/utils/kernelcmd.c, os/fs/procfs/fs_procfscpuload.c, os/fs/procfs/fs_procfsproc.c, os/include/tinyara/clock.h, os/kernel/Kconfig, os/kernel/sched/sched.h, os/kernel/sched/sched_cpuload.c, os/kernel/sched/sched_releasetcb.c, os/kernel/task/task_setup.c
- kernel/cpuload: support multiple time constant for CPU load measurement
: It supports to measure CPU load with 3 types of interval : short-term, mid-term, long-term
- kdbg/cpuload : add 'cpuload' command
: User can know current CPU load of all live tasks, and run CPU load monitor daemon which periodically show them.
=>  kernel/cpuload: support multiple CPU load measurement and cpuload command

os/include/net/lwip/sockets.h, os/include/net/lwip/sys.h, os/net/lwip/src/core/raw.c
lwIP generates build errors with options -Wimplicit-function-declaration, -Wunused-but-set-variable.
=> net/lwIP: fix build error on lwIP

framework/src/task_manager/task_manager_alloc_broadcast_msg.c, framework/src/task_manager/task_manager_dealloc_broadcast_msg.c, framework/src/task_manager/task_manager_getinfo.c, framework/src/task_manager/task_manager_internal.h, framework/src/task_manager/task_manager_pause.c, framework/src/task_manager/task_manager_register.c, framework/src/task_manager/task_manager_restart.c, framework/src/task_manager/task_manager_resume.c, framework/src/task_manager/task_manager_set_callback.c, framework/src/task_manager/task_manager_start.c, framework/src/task_manager/task_manager_stop.c, framework/src/task_manager/task_manager_unicast.c, framework/src/task_manager/task_manager_unregister.c, framework/src/task_manager/task_manager_unset_broadcast_cb.c
asprintf uses malloc. for checking TM memory usage, TM_ASPRINTF macro is needed.
=> framework/task_manager: Apply TM_ASPRINTF macro

framework/src/media/MediaPlayerImpl.cpp
MediaPlayer should call stop_audio_stream_out when it stops
=> media: Call stop_audio_stream_out in stopPlayer

apps/examples/mediarecorder/mediarecorder_main.cpp
called the stop function incorrectly
when the onPlaybackFinished callback function was called.
=> media: modify recorder app for invalid call

apps/examples/mediarecorder/mediarecorder_main.cpp
- Modify to check whether the return value is error
- Modify the 'isPlaying' update logic that it is updated in started or finished callback
=> app/mediarecorder : change logic of mediarecorder error handling

framework/src/st_things/st_things_request_handler.c
framework/src/st_things : Change the check management for readonly exist
Change the "if statement" logic to check whether a read only attribute is present or not in the request.
signed off by: uvasistha-samsung  utkarsh.m@samsung.com
=> framework/st_things   :  Change the check management for readonly exist

framework/src/media/MediaWorker.cpp
Even though a worker thread creation fails, the flag of 'mIsRunning' is set to true.
Fix this logical error by moving the 'mIsRunning' update logic right after the thread creation successfully.
=> framework/media : fix a logical error at MediaWorker::startWorker()

external/audiocodec/Makefile
sub directory objects are not cleaned after make clean
Steps:
./configure.sh /artik055s/audio
make
make clean
find . -name "*.o"
=> external/audiocodec: fix make clean

os/kernel/sched/sched_cpuload.c
=> kernel/sched: fix wrong indentation on sched_cpuload.c

build/configs/artik05x/artik05x_download.sh, build/configs/sidk_s5jt200/sidk_s5jt200_download.sh, os/Makefile.unix
Currently, romfs.img is made when download script is executed.
But it is not a step of downloading, it is a kind of binary
building.
It is better executing on Makefile, not download script.
"make", "make all" and "make romfs" makes romfs.img when CONFIG_FS_ROMFS
is enabled.
=> make: make a romfs.img on Makefile, not download script

apps/system/init/init.c, apps/system/sysinfo/sysinfo.c
1. mount procfs
CONFIG_FS_AUTOMOUNT_PROCFS does it on fs_auto_mount() so that
mounting it on preapp_start() should be removed.
2. read version info from procfs
Even if CONFIG_BUILD_PROTECTED is enabled, version.h can be
read from anywhere. That is not a value of kernel context.
=> system: remove mounting procfs and reading it for sysinfo

apps/system/init/init.c
Commit 8427254 removes mounting procfs from preapp_start().
But headers which are used to do above are not removed.
This commit removes redundant headers.
=> system/init: remove redundant headers

apps/appgen/README.md, apps/appgen/appgen.sh, apps/appgen/template_Kconfig, apps/appgen/template_Kconfig_ENTRY, apps/appgen/template_Make.defs, apps/appgen/template_Makefile, apps/appgen/template_main.c_source, os/tools/appgen.sh
- Latest bash
- Generally, Ubuntu linux has the latest bash
In any directory, run the appgen shell script and just enter the application name that you would make.
Your application would be generated at the apps/examples/
```sh
TizenRT/os$ tools/appgen.sh
TizenRT Application Generator
======================= v 1.0
Enter application name: test application
[Summary]
-------------------------------
* Application Name: test application
* Configuration Key: CONFIG_APP_TEST_APPLICATION
* Entry Function: test_application_main
* Location: /home/gcjjyy/workspace/github.com/gcjjyy/TizenRT/apps/examples/test_application
* This year: 2018
-------------------------------
Continue? (y/N): y
Generating...
* How to setup your application
Run) TizenRT/os/tools$ ./configure.sh <BOARD>/<CONFIG>
Run) …
```
=> tools: Add TizenRT Application Generator

os/tools/download.bat, os/tools/download.sh, os/tools/zipdownload.sh
Someone wants flash TizenRT binary without any enviorments like
cloning source codes, setting up build env and so on.
This script zips necessary files to download.
After installing USB driver, "make download" on os folder allows
flashing binary.
=> os/tools: add zipdownload script

framework/src/media/MediaPlayerImpl.cpp
- fix warning error when building time.
"warning: label 'errout' defined but not used"
In the function, it does not need to goto logic for return.
=> framework/media : Remove unused errout logic

external/wpa_supplicant/src/ap/hw_features.c, external/wpa_supplicant/src/utils/wpa_debug.h
When CONFIG_NO_STDOUT_DEBUG is enabled, serveral errors come out, which are resolved as follows.
- Change macros to inline function due to the errors from the defined but not used variable using wpa_dbg and wpa_printf
- Modify location of #ifndef CONFIG_NO_STDOUT_DEBUG not to build dfs_info
(requested by chan45.lee@samsung.com)
=> external/wpa_supplicant: Remove build error for CONFIG_NO_STDOUT_DEBUG

apps/examples/wifi_manager_sample/wm_test.c, framework/include/wifi_manager/wifi_manager.h, framework/src/wifi_manager/wifi_manager.c
- Add a new API to extract WiFi Manager run-time statistics
- Test the new API using wm_test
- Modify some spacing to remove code rule errors
=> framework/wifi_manager: Add a new API to extract WiFi Manager stats

framework/src/media/FileInputDataSource.cpp, framework/src/media/FileOutputDataSource.cpp
At destruction time, check if stream is alive and close it
=> media: Automatically close only if stream is alive

build/configs/qemu/qemu-2.12.0-rc1_16m_ram_size.patch, build/configs/qemu/qemu-2.12.0-rc1_1m_ram_size.patch
smartfs changes are reverted by mistake in the commit https://github.com/Samsung/TizenRT/commit/93e92b2dbb4b44cb31333d5ae6ecd4f1926f1b35
This patch adds back the required changes.
=> configs/qemu: Fix reverted smartfs changes in qemu patches

os/arch/Kconfig.chip
1. add a dependancy with ARCH_STACKDUMP
The assert shows call stack when ARCH_STACKDUMP is enabled.
Without above config, assert shows simple information like
below:
up_assert: Assertion failed at file:hello_main.c line: 70 ....
So, because DEBUG_DISPLAY_SYMBOL is meaningful with
ARCH_STACKDUMP, let's add "depends on ARCH_STACKDUMP"
2. change a type of dependancy
To use DEBUG_DISPLAY_SYMBOL, DEBUG_SYMBOLS, FRAME_POINTER
and FS_ROMFS are needed so that it made dependancies
through "depends on".
But because first two configs (DEBUG_SYMBOLS and FRAME_POINTER)
do not have any dependancy themself, we can use "select" instead
of "depends on". "select" is easiler to use, gives more convenient
to user.
=> arch/debug: modify DEBUG_DISPLAY_SYMBOL dependancies

external/grpc/Makefile, external/grpc/extlib/zlib/crc32.c, external/grpc/extlib/zlib/deflate.c, external/grpc/extlib/zlib/inflate.c, external/grpc/extlib/zlib/zlib.h
- Change the name of crc32 defined in grpc/extlib to grpc_crc32 because crc32 is defined in lib/libc/misc/ and os/include/
=> external/grpc: remove a duplicate function link of crc32

apps/Make.defs, apps/examples/grpc_greeter_client/Makefile, apps/examples/grpc_route_client/Makefile
Clean C++ files auto-generated by the `protoc` compiler, upon typing `make clean`. This will prevent possible errorneous mismatches between successive builds by different `protobuf` versions.
=> Clean Protobuf-generated C++ sources in Makefile

apps/examples/mediarecorder/mediarecorder_main.cpp, apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp, framework/include/media/MediaRecorder.h, framework/include/media/MediaRecorderObserverInterface.h, framework/include/media/MediaTypes.h, framework/src/media/MediaRecorder.cpp, framework/src/media/MediaRecorderImpl.cpp, framework/src/media/MediaRecorderImpl.h
1. remove instance id(not required)
: Use the mediarecorder object instead of instance id
2. add define error types for recorder result
: An error type is added to define each error in detail
=> media: modify observer for recorder

lib/libc/math/libm.h
Fixes below warning,
TizenRT/os/include/tinyara/compiler.h:79:20: warning: '__x' may be used
uninitialized in this function [-Wmaybe-uninitialized]
#define UNUSED(a) ((void)(a))
^
In file included from math/lib_exp2f.c:74:0:
math/libm.h:97:19: note: '__x' was declared here
volatile float __x;                   \
^
math/lib_exp2f.c:166:5: note: in expansion of macro 'FORCE_EVAL'
FORCE_EVAL(-0x1p-149f / x);
^~~~~~~~~~
=> libc/math : fix warning

framework/src/media/MediaRecorderImpl.cpp
Check whether vol is nullptr before enqueuing command
=> media: Check invalid param early in MediaRecorder

apps/examples/grpc_greeter_client/.gitignore, apps/examples/grpc_route_client/.gitignore
Add Protobuf-generated files to .gitignore, as they should not be versioned, and are deleted upon `make clean`.
=> examples/grpc: Add protobuf generated stubs to gitignore

framework/src/st_things/things_stack/easy-setup/es_common.h
Aligns the value of definitions using space(' ') instead of tab('\t')
=> framework/st_things: fixes indentation of definitions.

external/grpc/README.md
update `gRPC README.md` with an additional `ldconfig` installation step that was previously missed.
=> Update gRPC README.md

framework/src/task_manager/task_manager_core.c
if user_data is NULL, size var should be set to zero.
=> framework/task_manager: Fix bug for broadcast when user data is NULL

framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_set_callback.c
If not allocate the broadcast msg, only the last data is broadcasted.
Because the local variable is over-written by the last data.
=> framework/task_manager: Modify broadcast logic about sending msg

framework/src/wifi_manager/Kconfig, framework/src/wifi_manager/wifi_manager.c
- Add WIFIMGR_DISABLE_AUTO_GET_IP to enable/disable automatic IP after association/authentication
- DHCP for IPv4 and nothing to do for IPv6 yet
=> framework/wifi_manager: Add configuration to disable getting IP 

external/protobuf/README.md
Update Protobuf README.md to refer to gRPC's README.md for instructions how to install Protobuf.
=> update Protobuf README

os/tools/appgen.sh
^^ uppercase ,, lowercase functions are supported only bash 4.x or above.
To support lower version of bash, the script has modified.
=> tools: Fix appgen.sh for support bash 3.x

apps/system/utils/netcmd_netmon.c
Just initializing struct netmon_netdev_stats by {0} gives rise to a build warning.
It needs to be initialized by {{0,}, 0, 0, 0, 0}.
=> utils/netcmd_netmon : remove a build warning cause

framework/include/media/MediaRecorder.h, framework/src/media/MediaRecorder.cpp
The media framework supports multiple instances
applications are trying to handle multiple instances,
and we need to compare the objects. So we added operator and id.
=> add operator== and id for media recorder

framework/include/media/MediaRecorderObserverInterface.h
remove instance id(not required) - #2038 
: Use the mediarecorder object instead of instance id
=> media: remove unused id for recorderobserverinterface

os/tools/download.bat, os/tools/zipdownload.sh
1. Add signing step to supprt ARTIK secure models
2. Add making board.bat to enhance usability on Windows
Just double click of download.bat will program binaries
without "-b <BOARD_NAME"
=> os/tools/download: support ARTIK secure model and enhance usability 

README.md
1. Mark menuconfig and clean/distclean as optional steps
with sub-title because they are not essential steps.
essential steps : install docker -> clone source code -> configure -> build -> program
optionals : menuconfig and clean
2. Add the program step.
This step introduces a programming.
3. Modify content of clone and clean tabs.
=> README: modify Quick Start for docker build

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/include/task_manager/task_manager.h, framework/src/task_manager/task_manager_core.c, framework/src/task_manager/task_manager_set_callback.c
When user sends unicast msg, user should free the user data.
With this change, user don't need to free the user data. It will be freed automatically.
=> framework/task_manager: Change unicast about freeing user data

framework/include/media/InputDataSource.h, framework/src/media/FileInputDataSource.cpp, framework/src/media/InputDataSource.cpp, framework/src/media/MediaPlayerImpl.cpp
Only InputDataSource can handle Decoder.
Derived datasource call register and unresgister decoder.
=> media:Make Decoder visible only to InputDataSource

external/include/libtuv/queue.h, external/libtuv/source/uv_async.c
These source codes are got from libtuv github, https://github.com/Samsung/libtuv
1. Add QUEUE_MOVE() API at queue.h
2. Modify uv__async_event() API
In some cases, QUEUE_FOREACH() casues an infinite loop.
Therefore, QUEUE_FOREACH() is changed into while (!QUEUE_EMPTY())
=> external/libtuv: Add QUEUE_MOVE() API and modify uv__async_event() API

os/fs/vfs/fs_poll.c, os/net/lwip/src/api/sockets.c
Fix issue with concurrent socket select and socket close.
Scenario: 2 threads 1 and 2.
Thread 1 select-waits on a socket fd, while Thread 2 closes the same socket fd. 
At present: TizenRT does not de-allocate the said socket fd.
Fix: Exit the select wait, and also de-allocate the socket fd.
=> Fix issue with concurrent socket select and socket close

framework/src/media/MediaPlayerImpl.cpp, framework/src/media/MediaPlayerImpl.h
added STATE_CONFIGURED to
unconditionally set datasource before prepare
=> media: add configured state for media player

apps/examples/testcase/ta_tc/systemio/itc/Make.defs, apps/examples/testcase/ta_tc/systemio/utc/Make.defs
make systemio subtests: uart, i2c, spi, gpio, and pwm test independent.
Signed-off-by: tianfu.huang <tianfu.huang@samsung.com>
@sunghan-chang
=> testcase/systemio: make systemio sub-tests independent

framework/src/media/audio/audio_manager.c
It makes double closing the pcm because reset_audio_stream close the pcm
=> framework/media: Remove pcm_close line from stop_audio_stream_out()

external/iotjs/config/tizenrt/Makefile
There is a build error if a custom IoT.js is used by environment variables (`IOTJS_ROOT_DIR`).
**Commands:**
```sh
$ cd <path-to-tizenrt>/os
$ tools/configure.sh artik053/iotjs
$
$ export IOTJS_ROOT_DIR=/home/.../path/to/iotjs
$ export IOTJS_BUILD_OPTION='--profile=test/profiles/tizenrt.profile'
$
$ make
```
**Output:**
```sh
make[1]: Leaving directory '/home/.../TizenRT/framework'
make: *** No rule to make target '../external/iotjs/libhttpparser.a', needed by '../build/output/libraries/libhttpparser.a'.  Stop.
```
**Reason:**   
The Makefile of IoT.js (in external/iotjs/config/tizenrt/) copies all the created iotjs static libraries from the `${IOTJS_ROOT_DIR}/build/arm-tizenrt/libs` folder to the `${IOTJS_ROOT_DIR}`. After that, [LibTargets.mk (line …
=> iotjs: copy the IoT.js static libraries to the external iotjs folder

README.md, os/dbuild.sh
1. Support "menu" option
"./dbuild.sh menu" shows menu. User can choose an option
after seeing list of available option.
======================================================
"Select Board"
======================================================
"1. artik053"
"2. artik053s"
"3. artik055s"
"4. cy4390x"
"5. qemu"
"6. sidk_s5jt200"
"x. EXIT"
======================================================
2. Support exection list
User can put the list of execution as arguments like below:
"./dbuild.sh configure artik053 hello"
"./dbuild.sh distclean configure cy4390 tc build download all"
=> dbuild: support menu and execution list

framework/src/media/Decoder.h, framework/src/media/Encoder.h
Include guard is needed to void double inclusion
=> media: Add include guard at Decoder.h, Encoder.h

framework/src/media/Decoder.cpp, framework/src/media/streaming/audio_decoder.cpp, framework/src/media/streaming/audio_decoder.h
@Taejun-Kwon
Issue: In decoder, api name is hard to understand, audio_decoder_init_decoder & audio_decoder_init
Solution: modify audio_decoder_init_decoder to audio_decoder_cofig_decoder.
=> framework/media: Modify audio_decoder_init_decoder function name.

apps/examples/testcase/le_tc/kernel/Kconfig, apps/examples/testcase/le_tc/kernel/tc_sched.c
1. fix compilation warings 
2. remove a KERNEL_TEST_DRV dependancy
=> testcase/kernel: fix compilation warnings and remove a dependancy

external/grpc/src/core/lib/gpr/thd_posix.cc
external/grpc: Name grpc pthreads for debugging purposes, and understandability
=> external/grpc: Name grpc threads for debugging purposes, and understandability

framework/src/tinyalsa/tinyalsa.c
During audio playback, the media player tries to call pcm_drain API
at the end of playback to flush the data and close the device. However,
since we have stopped enqueuing new buffers to the codec and waiting
for dequeue msg, the codec generates underrun errors in the meantime.
Since we are in the phase of closing the audio device, we can ignore
any underrun related errors. Hence, modify tinyasla to ignore underrun
during pcm_drain.
=> Fix Error in Tinyalsa during audio playback

framework/include/media/InputDataSource.h, framework/src/media/Decoder.cpp, framework/src/media/Decoder.h, framework/src/media/FileInputDataSource.cpp, framework/src/media/InputDataSource.cpp, framework/src/media/streaming/audio_decoder.cpp
@Taejun-Kwon 
1. Fix the mp3 audio type  mConfig return false issue: Becasue mp3 need to find the sync header. If find the sync header  in the mConfig(), it will return false.  
Now, we move the find sync header flow to mp3_get_frame() function, and it works ok.
2. Add Decoder::create()interface, and call it in data source registerDecoder() fucntion.
=> framework/media: Init the audio decoder in data source open()

apps/examples/mediarecorder/mediarecorder_main.cpp, framework/include/media/MediaRecorderObserverInterface.h, framework/src/media/BufferOutputDataSource.cpp, framework/src/media/MediaRecorderImpl.cpp
Previous direct call to observer may cause unknown scheduling issue.
Use shared_ptr<> manage buffer and auto delete it after application read data.
@Taejun-Kwon @junmin-kim @gcjjyy @jsdosa
=> framework/media: Send buffer data via RecorderObserverWorker

apps/examples/mediarecorder/mediarecorder_main.cpp
onRecordBufferDataReached method prototype has changed.
But the example app didn't apply it.
=> media: Fix build error because of invalid type casting

apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
Allocated array should be removed by delete[]
=> media/utc: Use delete[] instead of delete

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/src/task_manager/task_manager_broadcast.c, framework/src/task_manager/task_manager_register.c, framework/src/task_manager/task_manager_set_callback.c
when fail to alloc, allocated memory should be released before return.
=> framework/task_manager: Fix memory leak possibility when fail case

apps/examples/mediaplayer/mediaplayer_main.cpp, apps/examples/mediarecorder/mediarecorder_main.cpp
Constructor inits all primitive data
=> examples/media: Init all members at construction

.clang-format
Break constructor initializers after the colon and commas.
ex)
Constructor() :
initializer1(),
initializer2()
=> .clang-format: Add BreakConstructorInitializers

apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c, framework/src/task_manager/task_manager_core.c
Before restarting the task, STOP_CB information and EXIT_CB information should be freed.
=> framework/task_manager: Fix memory deallocation after task_manager_restart

framework/src/st_things/things_stack/cloud/cloud_manager.c
In cloud_manager, log_in_out_to_cloud makes a call to make_cloud_address
with ci_addr as NULL. Hence, we can free ipport.
=> framework/st_things: fix memory leak

framework/src/st_things/things_stack/framework/things_data_manager.c
1. Updated delete_device() to de-allocate single and collection resources' info in st_device_s structure.
2. Updated delete_resource_type() to de-allocate the properties.
3. If there is an error in parse_device_json(), then delete the device information
before returning to caller.
=> framework/st_things: Fix memory leaks in Things Data Manager.

os/dbuild.sh
Download command supports all argument and it is executed
with make. But make has the all command always. Low character
all gives make confused.
This commit delivers capital characters for download arguments.
=> dbuild: Use capital characters for download arguments

framework/src/task_manager/task_manager_core.c, os/drivers/task_manager/task_manager_drv.c
task_restart calls sig_cleanup, and sig_cleanup sets tcb->sigprocmask to ALL.
if tcb->sigprocmask sets to ALL, it will be added to pendingsignal, but task_manager doesn't want to pend the signal.
=> framework/task_manager: Set tcb->sigprocmask to NULL after restart

framework/src/wifi_manager/wifi_profile.c
if CONFIG_WIFI_PROFILE_SECURESTORAGE is disabled then it can't refer readlen
which is used only above config so it causes a build error.
=> network/wifi_manager: fix build issue on wifi_profile

framework/src/media/utils/MediaUtils.cpp
Change from int to unsigned int.
=> framework/media: Fix a bulid warning in MediaUtils
