os/include/tinyara/bluetooth/bluetooth.h
os/include/tinyara/bluetooth/bt_core.h
os/include/tinyara/bluetooth/bt_hci.h
os/net/bluetooth/bluetooth.c
os/net/bluetooth/bt_hcicore.c
os/net/bluetooth/bt_hcicore.h

Add advertising and scan functions in net/bluetooth

net/bluetooth: Add bluetooth functions

---

os/drivers/wireless/Kconfig
os/drivers/wireless/bluetooth/Kconfig
os/drivers/wireless/bluetooth/Make.defs
os/drivers/wireless/bluetooth/bt_null.c
os/include/tinyara/bluetooth/bt_driver.h
os/include/tinyara/bluetooth/bt_hci.h
os/net/bluetooth/bluetooth.c
os/net/bluetooth/bt_hcicore.h
os/net/bluetooth/bt_netdev.c

driver/bluetooth: Implement the null driver for bluetooth

---

os/include/tinyara/bluetooth/bluetooth.h
os/include/tinyara/bluetooth/bt_hci.h
os/net/bluetooth/bluetooth.c
os/net/bluetooth/bt_hcicore.c
os/net/bluetooth/bt_hcicore.h

net/bluetooth: Implement the start stop advertising

---

build/configs/imxrt1020-evk/imxrt1020-evk_download.sh

Download script changes to fix long boot delay
imxrt1020-evk_download.sh: Read the configured partitions and input passed on to
download script and perform action ONLY on the input partition.

IMXRT1020-EVK:

---

build/configs/imxrt1020-evk/SAM/Make.defs

SAM/Make.defs: Add arguments to download script in Make.defs

IMXRT1020-EVK: Pass download arguments for SAM application

---

apps/examples/testcase/ta_tc/task_manager/utc/utc_taskmanager_main.c

Add new testcase for empty user data

testcase/task_manager : add new testcase for empty user data

---

external/dhcpd/Kconfig.protocol
external/dhcpd/dhcpd.c
external/dhcpd/dhcpd_lwip.c
external/include/protocols/dhcpd.h
framework/src/wifi_manager/wifi_manager.c
os/include/net/lwip/dhcp.h
os/include/net/lwip/lwipopts.h
os/net/lwip/configs/debug/Kconfig
os/net/lwip/src/core/ipv4/dhcps.c
os/net/lwip/src/core/ipv4/etharp.c
os/net/lwip/src/netif/ethernet.c
os/net/netdev/netdev_ioctl.c

Dhcp unicast

---

external/dhcpc/Kconfig.protocol
external/dhcpd/Kconfig.protocol
os/net/lwip/src/core/ipv4/dhcps.c
os/net/netdev/Make.defs
os/net/netdev/netdev_ioctl.c

- Modify Kconfig of LwIP's DHCP
- Fix build error when ipv6 is enabled

net/DHCP: Clean up DHCP server and client configurations

---

framework/src/media/codec/wav/wav_decoder_api.cpp

- comparison between signed and unsigned integer expressions [-Werror=sign-compare]
- ISO C++ forbids variable length array 'fmtChunk' [-Werror=vla]

framework/media: Fix build warning in codec

---

apps/examples/bluetooth/bt_unit_test.c
os/net/bluetooth/bluetooth.c

net/bluetooth: Test bluetooth enable feature using bt_enable

---

framework/include/media/OutputDataSource.h
framework/src/media/FileOutputDataSource.cpp
framework/src/media/OutputDataSource.cpp

DataSource doesn't use StreamBuffer

framework/media: Remove unused headers

---

apps/examples/mediaplayer/Makefile
apps/examples/mediaplayer/WiFiConnector.cpp
apps/examples/mediaplayer/WiFiConnector.h
apps/examples/mediaplayer/mediaplayer_main.cpp

Extract wifi component from mediaplayer_main

examples/mediaplayer: Add WiFiConnector

---

apps/examples/bluetooth/bt_unit_test.c
os/include/tinyara/bluetooth/bt_driver.h
os/include/tinyara/bluetooth/bt_hci.h
os/net/bluetooth/Kconfig
os/net/bluetooth/bluetooth.c
os/net/bluetooth/bt_conn.c
os/net/bluetooth/bt_hcicore.c
os/net/bluetooth/bt_hcicore.h
os/net/bluetooth/bt_netdev.c
os/net/bluetooth/bt_smp.c

net/bluetooth: Add iob buffer count and hci receive

---

os/Kconfig.debug
os/board/stm32f429i-disco/src/stm32_boot.c
os/board/stm32f429i-disco/src/stm32_lcd.c
os/drivers/Kconfig
os/drivers/Makefile
os/drivers/lcd/Kconfig
os/drivers/lcd/Make.defs
os/drivers/lcd/ili9341.c
os/drivers/lcd/lcd_framebuffer.c
os/drivers/video/Kconfig
os/drivers/video/Make.defs
os/drivers/video/fb.c
os/include/debug.h
os/include/tinyara/fs/ioctl.h
os/include/tinyara/input/touchscreen.h
os/include/tinyara/lcd/ili9341.h
os/include/tinyara/lcd/lcd.h
os/include/tinyara/video/fb.h

1. porting the fb/lcd driver structure from nuttx
2. porting the ili9341 common driver
@gcjjyy

os/drivers: apply fb/lcd drivers structure

---

os/fs/mqueue/mq_close.c

If mqdes is not in one's group, we should not desclose the mq and release the mq_inode.

mqueue/mq_close : Close the mq when mqdes is in one's group

---

os/drivers/lcd/lcd_framebuffer.c

putdma interface of lcd driver was added for fast data transmit.
refinement in this PR include:
1. support bpp < 8 device
2. use uint32 instead of uint64 to optimize mem copy
@gcjjyy

os/drivers: refine dma update code of lcd driver

---

os/arch/xtensa/src/esp32/Kconfig
os/arch/xtensa/src/esp32/esp32_spi.c
os/board/esp32_devkit/include/esp32_lcd.h
os/board/esp32_devkit/src/Makefile
os/board/esp32_devkit/src/esp32_lcd.c

add lcd driver of esp32 wrover kit, base on the
fb/lcd driver structure.
@gcjjyy

os/board: add esp32 lcd driver

---

os/arch/arm/src/imxrt/imxrt_gpio.c
os/arch/arm/src/imxrt/imxrt_gpio.h

- update irq vector table for all gpio set.

arch/imxrt/gpio: update gpio irqvector table

---

apps/examples/mediaplayer/CmdView.cpp
apps/examples/mediaplayer/CmdView.h
apps/examples/mediaplayer/Makefile
apps/examples/mediaplayer/mediaplayer_main.cpp

Extract UI component from mediaplayer_main

examples/mediaplayer: Add CmdView

---

build/configs/imxrt1020-evk/imxrt1020-evk_download.sh

Add ability to erase partition through commands for imxrt1020 board.

imxrt1020-evk_download.sh: Add support to erase individual partition

---

os/net/bluetooth/bluetooth.c
os/net/bluetooth/bt_conn.c
os/net/bluetooth/bt_conn.h
os/net/bluetooth/bt_hcicore.h
os/net/bluetooth/conn_internal.h

net/bluetooth: Add LE create connection

---

docs/HowToUseSmartFS.md

- Some sample code are updated with reference to partition code changes.
- NXP porting examples are added.

docs/fs: Update the SMARTFS porting guide.

---

docs/HowToUsePeripheral.md

docs/HowToUsePeripheral: update GPIO porting guide.

---

os/include/tinyara/bluetooth/bt_hci.h
os/include/tinyara/bluetooth/conn.h
os/net/bluetooth/bluetooth.c
os/net/bluetooth/bt_conn.c
os/net/bluetooth/bt_conn.h
os/net/bluetooth/bt_hcicore.c
os/net/bluetooth/bt_hcicore.h
os/net/bluetooth/bt_l2cap.c
os/net/bluetooth/bt_l2cap.h
os/net/bluetooth/bt_util.h

LE Connection and disconnection complete event

net/bluetooth: LE Connection and disconnection complete event

---

framework/src/media/InputHandler.cpp
framework/src/media/InputHandler.h
framework/src/media/Make.defs
framework/src/media/MediaPlayerImpl.cpp
framework/src/media/MediaRecorderImpl.cpp
framework/src/media/OutputHandler.cpp
framework/src/media/OutputHandler.h
framework/src/media/StreamHandler.cpp
framework/src/media/StreamHandler.h

StreamHandler is base class of InputHandler and OutputHandler

framework/media: Add StreamHandler

---

apps/examples/binary_update/binary_update_main.c
os/include/tinyara/binary_manager.h
os/kernel/binary_manager/binary_manager_getinfo.c

Support a path of active partition in getinfo API for delta update.

kernel/binary_manager: Support a path of active partition in getinfo API

---

os/fs/smartfs/smartfs_utils.c

os/fs: Fix Function Description

---

framework/src/wifi_manager/wifi_profile.c
lib/libc/net/lib_etherntoa.c
lib/libc/net/lib_inetntoa.c
lib/libc/net/lib_inetntop.c

change sprintf which is unsafe to snprintf

network: modify unsafe libc function

---

apps/examples/binary_update/binary_update_main.c
framework/include/binary_manager/binary_manager.h
framework/src/binary_manager/binary_manager_update.c
os/include/tinyara/binary_manager.h
os/kernel/binary_manager/binary_manager_getinfo.c

Change the structure name of binary update information

kernel/binary_manager: Change the structure name of binary update information

---

build/configs/qemu/README.md

Add guide to resolve install failure.

qemu/README: Add Trouble Shooting

---

os/tools/README_download.md

This document shows what it is and how to use.

os/tools/download: add README for download functionlity

---

framework/src/araui/assets/ui_font_asset.c
framework/src/araui/core/ui_core.c
framework/src/araui/widgets/ui_text_widget.c
tools/araui/sim/template/src/sim_main.c

- 'View' term is changed to the 'Window'
- Text draw logic is uncommented for testing

framework/araui: Revise simulator template, fix function name issue.

---

external/iotivity/iotivity_1.2-rel/resource/csdk/stack/src/oicgroup.c

- Replace sprintf to snprintf for safety

external/iotivity: use snprintf instaed of sprintf

---

os/dbuild.sh
os/tools/mksmartfsimg.sh

Docker version modify for docker update. And add command.

dbuild : Add smartfs command support

---

external/iotivity/iotivity_1.2-rel/resource/csdk/stack/src/oicgroup.c

- Change the size to the proper value of 1024

external/iotivity: Modify invalid snprintf usage

---

framework/include/araui/ui_animation.h
framework/include/araui/ui_widget.h
framework/src/araui/animation/ui_animation.c
framework/src/araui/core/ui_core.c
framework/src/araui/include/ui_animation_internal.h
framework/src/araui/include/ui_widget_internal.h
framework/src/araui/widgets/ui_widget.c

framework/araui: Add animation skeleton

---

os/board/common/partitions.c

There are many if statements in one function, which reduces the if.

board/common : Refactoring for visibility

---

os/board/common/partitions.c

Change : struct mtd_dev_s *mtd_initialize(FAR struct mtd_geometry_s geo) to struct mtd_dev_s *mtd_initialize(FAR struct mtd_geometry_s *geo)

board/common/partitions.c : Change mtd_initialize param type

---

os/tools/configure.bat
os/tools/configure.c

fixed issues found while building on windows

fixed issues found while building on windows

---

apps/system/utils/netcmd.c

- Refactor ifconfig command operations; Remove redundant logics and clean up sub-commands
- Add a proper DNS operation

apps/system/utils: Refactor netcmd ifconfig

---

apps/system/utils/fscmd.c

apps/system/utils: Fix fscmd memory leak

---

framework/src/media/HttpInputDataSource.cpp
framework/src/media/audio/audio_manager.c
framework/src/media/utils/MediaUtils.cpp

- Initialize member of HttpInputDataSource

Framework/Media: Fix Svace issue

---

os/fs/vfs/fs_select.c

- Define internal functions to make it easy to read

os/fs/vfs: Readability enhancement of select()

---

apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
framework/src/tinyalsa/tinyalsa.c

total_frames is no longer used

audio/utc: Remove an unused variable

---

build/configs/imxrt1020-evk/scripts/kernel-space-dtcm.ld
build/configs/imxrt1020-evk/scripts/kernel-space.ld
build/configs/imxrt1020-evk/scripts/user-space-dtcm.ld
build/configs/imxrt1050-evk/scripts/kernel-space-dtcm.ld
build/configs/imxrt1050-evk/scripts/kernel-space.ld
build/configs/imxrt1050-evk/scripts/user-space-dtcm.ld

Change comments section with proper file name

configs/imxrt1050x-evk,imxrt1020-evk/scripts: Fix comments section

---

build/configs/imxrt1020-evk/loadable_elf_apps/defconfig
os/board/common/partitions.c

have defined a partition type for using app partitions.

os/board/common/partitions: Fix partition type

---

framework/include/binary_manager/binary_manager.h
framework/include/messaging/messaging.h

PRE means that it is not released officially, it could be changed.

framework/binary_manager, messaging: change an API version to v3.0 PRE

---

build/configs/imxrt1020-evk/loadable_elf_apps/defconfig
os/board/common/partitions.c

Revert PR #3753

---

framework/include/media/MediaUtils.h

framework/media: Modify MediaUtils doxygen

---

framework/src/media/audio/audio_manager.c
framework/src/media/audio/audio_manager.h
framework/src/media/audio/resample/samplerate.c

In case of down resampling,
an error occurred and the logic was corrected

framework/media: modify down resampling(revert commit a5f266b)

---

os/board/common/partitions.c

Refactoring for improved readability and SAM CC entries

board/common/partitions : Refactoring

---

tools/ramdump/HowToUseRamdump.md
tools/ramdump/Ramdump_windows.ps1

tools/ramdump: This patch adds Ramdump tool for windows

Windows Ramdump tool

---

apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp

media/utc: Cleanup after epd

---

framework/src/araui/animation/ui_animation.c
framework/src/araui/assets/ui_font_asset.c
framework/src/araui/assets/ui_image_asset.c
framework/src/araui/core/ui_commons.c
framework/src/araui/core/ui_core.c
framework/src/araui/core/ui_quick_panel.c
framework/src/araui/core/ui_window.c
framework/src/araui/include/ui_debug.h
framework/src/araui/include/ui_renderer.h
framework/src/araui/include/ui_widget_internal.h
framework/src/araui/include/ui_window_internal.h
framework/src/araui/renderer/ui_renderer.c
framework/src/araui/widgets/ui_button_widget.c
framework/src/araui/widgets/ui_image_widget.c
framework/src/araui/widgets/ui_paginator_widget.c
framework/src/araui/widgets/ui_scroll_widget.c
framework/src/araui/widgets/ui_text_widget.c
framework/src/araui/widgets/ui_widget.c
tools/araui/sim/template/src/dal/dal_sdl.c

- framework/araui: Rendering image with texture uv coordinates
- tools/araui: Fix wrong simulator display area

framework/araui: Rendering image with texture uv mapping

---

apps/examples/testcase/le_tc/filesystem/fs_main.c

Add MTD path depend on imxrt1020

apps/examples/testcase/le_tc/filesystem: Add MTD path depending on specific board

---

apps/examples/testcase/le_tc/kernel/tc_sched.c

restore the task priority as the previous after testing

testcase/kernel/tc_sched.c : Restore the task priority as the previous after testing

---

framework/src/araui/animation/ui_animation.c
framework/src/araui/include/ui_animation_internal.h

- Add spawn animation
- Refactoring initialization of local variables
- Gap conditions of `_ui_anim_move_func` are temporary, those will be removed later.

framework/araui: Add spawn

---

framework/src/iotbus/iotapi_dev_handler.c
framework/src/iotbus/iotbus_pwm.c
framework/src/iotbus/iotbus_spi.c
os/drivers/iotdev/iotdev.c

framework/iotbus: fix svace issues

---

framework/include/araui/ui_animation.h
framework/src/araui/animation/ui_animation.c
framework/src/araui/include/ui_animation_internal.h

- Add delay animation
- Use `ui_widget_set_position` instead of changing position value directly in `_ui_anim_move_func`

framework/araui: Add delay animation

---

framework/include/araui/ui_commons.h
framework/src/araui/core/ui_core.c
framework/src/araui/include/ui_renderer.h
framework/src/araui/renderer/ui_renderer.c
framework/src/araui/widgets/ui_image_widget.c

Before, uv mapping is based on the basic algorithm.
Enhanced algorithm is applied.

framework/araui: Enhancement of UV mapping quality

---

framework/src/araui/renderer/ui_renderer.c

Didn't support RGB888 format. Added.

framework/araui: Fix renderer pixel format problem

---

framework/include/araui/ui_animation.h
framework/src/araui/animation/ui_animation.c
framework/src/araui/include/ui_animation_internal.h

- implemented rotate and scale animation
- add interpolation type to rotate, opacity, scale animation
- remove unused local variable of `_ui_anim_delay_func`
- rename some local variables for clarity of purpose of those

framework/araui: Implement animations

---

framework/src/araui/core/ui_core.c
framework/src/araui/renderer/ui_renderer.c

framework/araui: Change matrix order to TRS from SRT

---

apps/examples/testcase/le_tc/network/tc_net_accept.c
apps/examples/testcase/le_tc/network/tc_net_connect.c
external/dhcpd/dhcpd.c
framework/src/iotbus/iotapi_evt_handler.c
framework/src/wifi_manager/wifi_manager.c
framework/src/wifi_manager/wifi_utils_lwnl80211.c
os/drivers/iotdev/iotdev.c
os/net/socket/net_dupsd.c

fix coverity issues on network, iotapi_event handler

coverity: fix coverity issues on network, iotapi_event handler

---

framework/src/iotbus/iotapi_evt_handler.c
framework/src/iotbus/iotapi_sig_handler.c

- fix return values.
- modify fd open permission.

framework/iotbus: fix minor bugs

---

apps/examples/testcase/le_tc/kernel/tc_mqueue.c
apps/examples/testcase/le_tc/kernel/tc_roundrobin.c
apps/examples/testcase/le_tc/kernel/tc_timer.c
apps/examples/testcase/ta_tc/task_manager/utc/utc_taskmanager_main.c
framework/src/messaging/messaging_common.c
framework/src/task_manager/task_manager_core.c

taskmgr_get_handle_by_pid can return negative value(-4, TM_UNREGISTERED_APP), but it is used for index of array.

framework/task_manager : Add invalid return check for handle

---

apps/examples/testcase/Makefile
apps/examples/testcase/ta_tc/task_manager/itc/itc_taskmanager_main.c

For avoiding stack overflow, increase the stack size for TCs in task manager itc.

apps/testcase/task_manager_itc : Increase the stack size of TCs

---

os/drivers/wireless/realtek/os/tizenrt/tizenrt_service.c
os/drivers/wireless/realtek/wifi_util_interface/wifi_interactive_mode.c

- Modify return type of several functions
- Remove unnecessary code

os/drivers/wireless: Bug fix Relatek Wi-Fi driver

---

framework/src/araui/core/ui_core.c
framework/src/araui/widgets/ui_widget.c

As the internal operation is not recursive, _recur in the name of APIs were removed.

framework/araui: Modify the name of internal APIs.

---

apps/examples/testcase/le_tc/kernel/tc_libc_inttypes.c
apps/examples/testcase/le_tc/kernel/tc_libc_pthread.c
apps/examples/testcase/le_tc/kernel/tc_pthread.c
apps/examples/testcase/le_tc/kernel/tc_sched.c
apps/examples/testcase/le_tc/kernel/tc_semaphore.c

Add two negative cases, invalid base and overflow

testcase/kernel: add negative testcase of strtoumax and tidyup

---

build/configs/imxrt1050-evk/imxrt1050-evk_download.sh

imxrt1050-evk_download.sh misses logic to convert kB to bytes

IMXRT1050-EVK: Hello world application fails to be downloaded

---

apps/examples/testcase/ta_tc/media/utc/utc_media_focusmanager.cpp
framework/include/media/FocusManager.h
framework/src/media/FocusManager.cpp

media/utc: Improve FocusManager utc

---

apps/examples/testcase/ta_tc/media/utc/utc_media_bufferoutputdatasource.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp

add utc for
bufferoutputdatasource,
fileinputdatasource,
fileoutputdatasource,
and mediaplayer

framework/media: add utc for media

---

framework/src/media/MediaPlayerImpl.cpp

Fixed a timing issue between threads.

framework/media: fix bug for prepareasync

---

apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp

- Add MediaRecorder operator== test
- Add MediaPlayer operator== test

utc/media: Improve media utc

---

framework/include/iotbus/iotbus_pwm.h
framework/src/iotbus/iotbus_pwm.c
os/drivers/pwm.c
os/include/tinyara/pwm.h

iotbus/pwm: remove unused API

---

apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp

- check setDataSource after configuration
- check setObserver twice

media/utc: Improve MediaPlayer utc

---

apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp

- Check with mono channel datasource
- Check with various samplerate datasources

media/utc: Improve MediaPlayer::start utc

---

apps/examples/testcase/le_tc/kernel/tc_libc_string.c

Change strlen("string") + 1 to sizeof("string") and change "Bad address" to EFAULT_STR

testcase/kernel/tc_libc_string : Refactoring tc_libc_string

---

os/arch/arm/src/imxrt/imxrt_ehci.c

Fixed build error with macro usage.

arch/arm/src/imxrt: Fixing build error on enabling usb debug

---

framework/src/media/audio/audio_manager.c
framework/src/media/audio/audio_manager.h
framework/src/media/audio/resample/samplerate.c

Remove rechannel code in samplerate.c
Remove definition regarding stereo extender

media/common: Remove unusing code

---

apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp

- Test mono, stereo channel
- Test 41000, 32000, 20000, 16000, 14000, 8000, 6000 samp rate

utc/media: Test with various channel, samprate

---

os/drivers/usbhost/usbhost_enumerate.c

Most of the USB Configuration descriptors are with in 128bytes, but in
case of UVC class this size would be in range of 1000bytes to 2000bytes
Current driver would assumes bigger configuration size as a failure and
returns with no memory error.Due to this the UVC device fails to enumerate.
This patch would reallocate new buffer with actual configuration size
and read the complete configuration descriptor

drivers/usbhost: Reallocate buffer to read USB configuration descriptor

---

apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp

Add utc of detectEndPoint, waitEndPoint

media/utc: Add SpeechDectector API utc

---

apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp

Check mp3, aac, wav, ts header parsing with empty file

media/utc: Improve FileInputDataSource open utc

---

framework/src/media/OutputHandler.cpp
framework/src/media/SocketOutputDataSource.cpp
framework/src/media/audio/audio_manager.c
framework/src/media/utils/MediaUtils.cpp
framework/src/tinyalsa/tinyalsa.c

framework/media: fix coverity issues

---

apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp

testcase/media: modify utc regarding setDuration

---

apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
framework/include/media/MediaPlayer.h
framework/src/media/MediaPlayer.cpp
framework/src/media/MediaPlayerImpl.cpp
framework/src/media/MediaPlayerImpl.h

framework/media: Remove unused api

---

framework/src/messaging/messaging_cleanup.c
framework/src/messaging/messaging_internal.h
framework/src/messaging/messaging_rcvinternal.c
os/kernel/messaging/messaging.c

Change g_port_info_list to static and add get function for using in another file.
port_list_sem is already used in only that file. just change to static.

framework/messaging : Change global variable to static

---

framework/include/media/MediaUtils.h
framework/src/media/utils/MediaUtils.cpp

- Make `ts_parsing` to be static method
- Add AUDIO_TYPE_MP2T case to `buffer_header_parsing`

framework/media: Put ts_parsing inside buffer/file_header_parsing

---

apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp

Add resume test(pause->start)
Fix bug regarding resampled data because of too small data

media/utc: Improve code coverage

---

framework/src/iotbus/iotapi_evt_handler.c
framework/src/iotbus/iotbus_uart.c

- modify global variables to static variables.

framework/iotbus: modify global variables to static var

---

framework/src/media/Decoder.cpp
framework/src/media/demux/mpeg2ts/PATParser.cpp
framework/src/media/demux/mpeg2ts/PATParser.h
framework/src/media/demux/mpeg2ts/PMTInstance.cpp
framework/src/media/demux/mpeg2ts/PMTInstance.h
framework/src/media/demux/mpeg2ts/ParseManager.cpp
framework/src/media/demux/mpeg2ts/ParseManager.h
framework/src/media/demux/mpeg2ts/SectionParser.h
framework/src/media/demux/mpeg2ts/TSDemuxer.cpp
framework/src/media/demux/mpeg2ts/TSDemuxer.h

Remove unused code in below files:
- framework/src/media/Decoder.cpp
- framework/src/media/demux/mpeg2ts/*

framework/media: Remove unused functions and codes

---

framework/src/bluetooth/src/bluetooth-adapter.c

bluetooth:Fix memory leak while validating the pointer

---

loadable_apps/loadable_sample/micomapp/messaging.c

There is duplicated code about setting to receive SIGMSG_MESSAGING and SIGUSR1.

loadable_apps/micom/messaging : Merge duplicated signal setting code

---

framework/src/messaging/messaging_unicast_send.c

checking port name and send data is duplicated in messaging_send and messaging_send_async.

framework/messaging : Merge duplicated send param validation check

---

apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c
apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c
framework/src/iotbus/iotbus_gpio.c

- add GPIO interrupt type TCs
- add SPI transfer TCs

iotbus/utc: add GPIO/SPI utc

---

framework/src/media/audio/audio_manager.c

- Extract pause_audio_stream method

audio/audio_manager: Refactor duplicated code

---

apps/examples/testcase/ta_tc/media/utc/utc_media_focusmanager.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp

- Check invalid param
- Call virtual function

media/utc: Improve media utc coverage

---

framework/src/media/audio/audio_manager.c
framework/src/media/audio/audio_manager.h

- remove get_card_input_bytes_to_frame
- remove get_card_output_bytes_to_frame

audio/audio_manager: Remove unused function

---

framework/src/media/audio/audio_manager.c

- Extract ioctl_with_path function

audio/manager: Refactor audio_manager.c

---

framework/src/binary_manager/binary_manager_update.c
os/include/tinyara/binary_manager.h
os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_load.c

When updating, reload will not work if it is the latest version.

kernel/binary_manager : Do not reload if it is already latest version

---

framework/src/media/audio/audio_manager.c

pause_audio_stream should get audio_io_direction_t

audio/audio_manager: Fix bug in pause_audio_stream

---

framework/src/media/codec/audio_decoder.cpp
framework/src/media/codec/audio_decoder.h
framework/src/media/codec/audio_encoder.cpp
framework/src/media/codec/audio_encoder.h
framework/src/media/utils/rbs.c
framework/src/media/utils/rbs.h

pulling data callback is not used, and wont be used in future.

framework/media: Remove unused logic code in rbs and codec

---

apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp

testcase/media: add utc for opus and wave

---

apps/system/utils/fscmd.c
os/fs/driver/mtd/mtd_partition.c
os/fs/driver/mtd/smart.c
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c
os/fs/tmpfs/fs_tmpfs.c

- Cyclomatic Complexities of file system functions are reduced
by defining parts of the functions as indivisual functions.
- cat and ls functions, some smartfs functions, and some mtd functions
are divided into two or four functions.

os/fs: Fix SAM issues in SmartFS

---

framework/src/messaging/messaging_unicast_send.c
loadable_apps/loadable_sample/micomapp/messaging.c

There is a missing return statement in int type function

framework/messaging : Add missing return statement

---

os/mm/mm_heap/mm_free.c
os/mm/mm_heap/mm_malloc.c
os/mm/mm_heap/mm_node.h
os/mm/mm_heap/mm_realloc.c
os/mm/mm_heap/mm_shrinkchunk.c

There are many duplicated code.
It can be merged into defines for avoiding redundancy.

os/mm : Merge duplicated code about remove node

---

framework/src/media/Decoder.cpp
framework/src/media/Demuxer.cpp
framework/src/media/InputHandler.cpp
framework/src/media/audio/audio_manager.c

Remove useless log & optimize log case

media/common: Clean media log

---

apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp

media/utc: Improve FileOutputDataSource utc

---

apps/system/utils/fscmd.c
os/fs/driver/mtd/mtd_partition.c
os/fs/driver/mtd/smart.c
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c
os/fs/tmpfs/fs_tmpfs.c

- Refactored functions of file systems are reverted.

os/fs: Revert file system modification for SAM issues.

---

framework/include/araui/ui_animation.h
framework/include/araui/ui_widget.h
framework/src/araui/animation/ui_animation.c
framework/src/araui/core/ui_core.c
framework/src/araui/core/ui_quick_panel.c
framework/src/araui/include/ui_animation_internal.h
framework/src/araui/include/ui_widget_internal.h
framework/src/araui/widgets/ui_paginator_widget.c
framework/src/araui/widgets/ui_widget.c

- Replace tweening with animation
- Remove tweening code
- Remove unused variables
- Correct typos

framework/araui: Replace tweening widget with animation

---

framework/include/araui/ui_widget.h
framework/src/araui/animation/ui_animation.c
framework/src/araui/core/ui_quick_panel.c
framework/src/araui/widgets/ui_paginator_widget.c
framework/src/araui/widgets/ui_widget.c
tools/araui/sim/template/araui.mk

- add animation path to simulator
- fix `ui_paginator_tween_finish`
- remove build warning

framework/araui: add animation path to simulator

---

framework/src/araui/core/ui_core.c
framework/src/araui/widgets/ui_text_widget.c
tools/araui/sim/template/araui.mk

In order to solve build error, add initialziation procedure of values is added.

framework/araui: Add initialization procedure

---

os/drivers/testcase/Make.defs
os/drivers/testcase/kernel_test_proto.h
os/drivers/testcase/kernel_testcase_drv.c
os/drivers/testcase/test_clock.c
os/drivers/testcase/test_group.c
os/drivers/testcase/test_sched.c
os/drivers/testcase/test_sem.c
os/drivers/testcase/test_signal.c
os/drivers/testcase/test_task.c
os/drivers/testcase/test_timer.c

I split kernel_testcase_drv.c into other source files by test group to refactor it.

drivers/testcase : Split files by test group

---

apps/examples/testcase/Kconfig
apps/examples/testcase/Makefile
apps/examples/testcase/le_tc/compression/Kconfig
apps/examples/testcase/le_tc/compression/Make.defs
apps/examples/testcase/le_tc/compression/compression_tc_main.c
apps/examples/testcase/le_tc/compression/tc_internal.h
apps/examples/testcase/le_tc/compression/tc_lzma.c
apps/examples/testcase/tc_main.c

- Checking if the data is correctly retrieved after performing compression and
decompression on a buffer.
Signed-off-by: Nishtha97 <n.maloo@samsung.com>

apps/examples/testcase: Testcase for compression using LZMA algorithm

---

framework/src/binary_manager/binary_manager_interface.c
framework/src/binary_manager/binary_manager_internal.h
framework/src/binary_manager/binary_manager_notify.c
framework/src/binary_manager/binary_manager_register_callback.c
framework/src/binary_manager/binary_manager_update.c

…inary manager
There are many duplicated code.
It can be merged into defines for avoiding redundancy.

framework/binary_manager : Split the function of setting request message

---

apps/examples/testcase/ta_tc/media/utc/utc_media_focusmanager.cpp
framework/src/task_manager/task_manager_core.c
os/include/time.h
os/tools/cfgdefine.c

fix violations of coding rules

---

os/Makefile.unix
os/Makefile.win

Makefile: version up as 3.0

---

framework/include/araui/ui_animation.h
framework/include/araui/ui_widget.h
framework/src/araui/Make.defs
framework/src/araui/animation/ui_animation.c
framework/src/araui/core/ui_core.c
framework/src/araui/include/ui_widget_internal.h
framework/src/araui/widgets/ui_paginator_widget.c
framework/src/araui/widgets/ui_widget.c

- Add some sync function for animation
- Add path to araui framework Make.defs
- Add temporary variable for delta time of `_ui_process_widget`
- Add another callback function for paginator to remove animation
- Add `ui_widget_play_anim` brief and animation functions

framework/araui: Fix paginator swipe shaking

---

docs/HowToUseTimer.md

It describes the usages and purpose of sw, hw timers,
sleep, workqueue, POSIX timer and HW timer.

docs: add the document about how to use timer

---

apps/examples/camera/Kconfig
apps/examples/camera/Kconfig_ENTRY
apps/examples/camera/Make.defs
apps/examples/camera/Makefile
apps/examples/camera/camera_main.c
os/Kconfig.debug
os/drivers/video/Kconfig
os/drivers/video/Make.defs
os/drivers/video/video.c
os/drivers/video/video_framebuff.c
os/drivers/video/video_framebuff.h
os/include/debug.h
os/include/video/video.h
os/include/video/video_controls.h
os/include/video/video_halif.h

- Added support for Video source, this driver will define
standard interface for camera application and drivers.

driver/video: Add video source frame buffer

---

tools/ramdump/dumpParser.py

Details of Heap Usages (Size in Bytes)
******************************************************************
MemAddr |   Size   | Status |  Pid  |           Owner
----------|----------|--------|-------|---------------------------
0x2025ba0 |    528   |  Alloc |   0   | os/kernel/signal/sig_initialize.c:170
0x2025db0 |    272   |  Alloc |   0   | os/kernel/signal/sig_initialize.c:175
0x2025ec0 |    336   |  Alloc |   0   | os/kernel/signal/sig_initialize.c:260
0x2026010 |    400   |  Alloc |   0   | os/kernel/signal/sig_initialize.c:203
0x20261a0 |    208   |  Alloc |   0   | os/kernel/signal/sig_initialize.c:203
0x2026270 |   2448   |  Alloc |   0   | os/kernel/mqueue/mq_initialize.c:149
0x2026c00 |   4880   |  Alloc |   0   | os/kernel/mqueue/mq_initialize.c:149
0x2027f10 |    320   | …

tools/ramdump : Show heap usage in ramdump

---

framework/src/media/FileOutputDataSource.cpp

Adjust indent using clang-format

framework/media: Fix coding rule violation

---

framework/src/wifi_manager/wifi_manager_dhcp_internal.c
framework/src/wifi_manager/wifi_manager_dhcp_internal.h

- Add a supplement logic for handling a number of associated stations
- Clean up the linked headers

framework/wifi_manager: Arrange DHCPS in WiFi Manager

---

external/include/json/cJSON.h
external/json/cJSON.c
os/arch/xtensa/src/xtensa/xtensa_initialize.c
os/include/net/lwip/lwipopts.h
os/net/lwip/configs/Kconfig

os/arch/xtensa: init pipe during booting for xtensa
os/net: Add LWIP_NETIF_TX_SINGLE_PBUF in lwipopts for stdk
external/mbedtls: Enable some mbedtls config for stdk
external/json: Add GetStringValue API for cJSON

os/net: some modifications in common for stdk

---

.gitmodules
external/libsodium/Kconfig
external/libsodium/Make.defs
external/libsodium/Makefile
external/libsodium/port/crypto_hash_mbedtls/crypto_hash_sha256_mbedtls.c
external/libsodium/port/crypto_hash_mbedtls/crypto_hash_sha512_mbedtls.c
external/libsodium/port/randombytes_default.h
external/libsodium/port/randombytes_esp32.c
external/libsodium/port/randombytes_soft.c
external/libsodium/port/sodium/version.h

Add libsodium for st-device-sdk on tizenrt

external/libsodium: add sodium lib

---

external/openssl/Kconfig
external/openssl/Make.defs
external/openssl/Makefile
external/openssl/OpenSSL-APIs.rst
external/openssl/include/internal/ssl3.h
external/openssl/include/internal/ssl_cert.h
external/openssl/include/internal/ssl_code.h
external/openssl/include/internal/ssl_dbg.h
external/openssl/include/internal/ssl_lib.h
external/openssl/include/internal/ssl_methods.h
external/openssl/include/internal/ssl_pkey.h
external/openssl/include/internal/ssl_stack.h
external/openssl/include/internal/ssl_types.h
external/openssl/include/internal/ssl_x509.h
external/openssl/include/internal/tls1.h
external/openssl/include/internal/x509_vfy.h
external/openssl/include/openssl/ssl.h
external/openssl/include/platform/ssl_opt.h
external/openssl/include/platform/ssl_pm.h
external/openssl/include/platform/ssl_port.h
external/openssl/library/ssl_cert.c
external/openssl/library/ssl_lib.c
external/openssl/library/ssl_methods.c
external/openssl/library/ssl_pkey.c
external/openssl/library/ssl_stack.c
external/openssl/library/ssl_x509.c
external/openssl/platform/ssl_pm.c

Add openssl library for stdk porting on tizenrt

external/openssl: add openssl library

---

os/kernel/init/os_start.c

Change to initialize the main(first) heap and add another region if needed.

kernel/init/os_start : Change heap initialization for multi-region

---

framework/src/wifi_manager/wifi_manager_dhcp_internal.c

- Default SoftAP IP addr setting in WiFi Manager API

framework/wifi_manager: Set SoftAP IP address

---

external/codecs/base64.c
external/codecs/md5.c
external/include/codecs/base64.h
external/include/codecs/md5.h

- Update base64, md5 from nuttx.
- Fix typo.

external/codecs: Update codecs from nuttx

---

external/include/libtuv/uv_platform.h
external/iotjs/deps/libtuv/include/uv-tizenrt.h
external/wpa_supplicant/src/utils/includes.h
os/include/errno.h

ENOKEY, EKEYEXPIRED, EKEYREVOKED, EKEYREJECTED are added

errno: Add key error number

---

build/tools/esp32/esptool_py/Makefile

1. Add esptool_py submodule checking.
2. Change some downloading peremeters to capital letter form.

build/tools: Update the Makefile of esptool.

---

framework/src/araui/animation/ui_animation.c
framework/src/araui/widgets/ui_widget.c

framework/araui: add missing statement

---

framework/src/preference/private_preference.c
framework/src/preference/shared_preference.c
os/include/tinyara/preference.h
os/kernel/preference/preference_read.c
os/kernel/preference/preference_write.c

Caculate and Write CRC of them when setting preference data.
And then check it when getting preference data.

framework/preference: Support CRC to verify preference data

---

external/stdk/README.md

external/stdk: add readme

---

docs/HowToUseSmartFSDumpVisualizer.md

- Explanations for Java tool installation and smartfs dumping are added.

docs: Update how-to-use of SDV.

---

tools/cmdautotest/README_CMDAutoTest.md
tools/cmdautotest/cmdautotest.py

This tool is a tool that automatically executes TASH commands.
[Install]
$ apt install python2.7
$ pip install pyserial
[How to Use]
$ python cmdautotest.py serial_port
ex)
$ python cmdautotest.py /dev/ttyUSB1

tools: Add TASH CMD auto test tool

---

framework/src/araui/renderer/ui_renderer.c
framework/src/araui/widgets/ui_text_widget.c

- Fix typo to build successfully
- Remove unused variables

framework/araui: Fix typo and remove unused variables

---

tools/ramdump/dumpParser.py
tools/ramdump/gui_dumpParser.py

By showing the heap usage through the GUI, visibility is increased.
And you can see where it is ALLOC and where STACK is located. So
click each button to check Mem address, size, pid, etc.

tools/ramdump : Show heap usage through the GUI

---

os/drivers/wireless/realtek/wifi_util_interface/rtk_drv.c

Fix build error in non protected build environments.

os/drivers/wireless/realtek: Build fix in non protected configs.

---

loadable_apps/loadable_sample/micomapp/messaging.c

Fix errors in code which cause failure of messaging test
in the loadable applications.

loadable_apps: Fix issue in messaging test

---

external/esp_idf_port/include/event_groups.h
external/stdk/tizenrt-wrapper/os/event_groups.h
external/stdk/tizenrt-wrapper/os/iot_os_net_tizenrt.c

external/stdk: Add missing original license

---

docs/HowToUseSmartFS.md

There is the documentation to say the way of making SmartFS image already.
This commit adds the sub-content in how to use SmartFS doc to know it easily.

docs/HowToUseSmartFS: add the content of making SmartFS image

---

framework/src/araui/renderer/ui_renderer.c
framework/src/araui/widgets/ui_text_widget.c

There was a text color issue because of the bit operations.

framework/araui: Fix text color issue

---

build/configs/artik053/.flashSpec.xml
build/configs/artik055s/.flashSpec.xml
build/configs/artik05x/artik05x_download.sh
build/configs/esp32_DevKitC/.flashSpec.xml
build/configs/esp_wrover_kit/.flashSpec.xml
build/configs/imxrt1020-evk/.flashSpec.xml
build/configs/imxrt1020-evk/imxrt1020-evk_download.sh
build/configs/imxrt1050-evk/.flashSpec.xml
build/configs/imxrt1050-evk/imxrt1050-evk_download.sh
build/configs/stm32f407-disc1/.flashSpec.xml
build/configs/stm32f429i-disco/.flashSpec.xml
build/configs/stm32f4xx/stm32f4xx_download.sh
build/configs/stm32l4r9ai-disco/.flashSpec.xml
build/configs/usbrule.sh
build/tools/esp32/esptool_py/Makefile
os/dbuild.sh

I added usbrule menu for user convenient
If user selectes usbrule menu, then it will automatically creates a target board-specific .rule file in /etc/udev/rule.d directory.

os/dbuild.sh : Add usbrule menu in download option

---

framework/src/araui/widgets/ui_text_widget.c

Text position was calculated twice.

framework/araui: Fix text position issue

---

external/stdk/README.md

- Modify the link of patch file

external/stdk: Update git patch path

---

framework/src/tinyalsa/Make.defs

Remove useless space at framework/src/tinyalsa/Make.defs

framework/tinyalsa: Remove useless blank

---

apps/shell/tash_command.c
apps/shell/tash_internal.h
apps/shell/tash_main.c

Press tab while typing commands to auto complete.
Pressing tab twice while typing a command will show
you the commands you can use.
TASH>>hel
help             hello

apps/shell/tash : Add command autocompletion support

---

build/configs/artik053/.flashSpec.xml
build/configs/artik053s/.flashSpec.xml
build/configs/artik055s/.flashSpec.xml
build/configs/artik05x/artik05x_download.sh
build/configs/imxrt1020-evk/.flashSpec.xml
build/configs/imxrt1020-evk/imxrt1020-evk_download.sh
build/configs/imxrt1050-evk/.flashSpec.xml
build/configs/imxrt1050-evk/imxrt1050-evk_download.sh
build/configs/stm32f4xx/stm32f4xx_download.sh
build/configs/usbrule.sh
build/tools/esp32/esptool_py/Makefile
os/dbuild.sh

I changed the hardcoded part of the build script to read board-specific predefined options.
In addition, I added board-specific options to provide the user with a menu
I also refactored download scripts

os/dbuild.sh : Refactoring of build and download script

---

tools/fs/FS_Dump_Parser/SmartFS_Dump_Parser.product

Add plug-in for developing Eclipse RCP-based SDV.

tools/fs: Add dependency plugn for SDV development

---

apps/examples/camera/camera_main.c

- Options to set various camera controls
- Options to set various format and frames
- Options to set various frame intervals
- Code cleanup
- Fix invalid index ranges for all formats, frames & frame intervals
- Help string alignment
- Print a valid error string's for invalid option

apps/examples/camera: Support for Camera control & format

---

os/fs/vfs/fs_open.c
os/include/tinyara/fs/fs.h

vopen() is an internal TizenRT interface

fs/vfs: Add vopen

---

framework/src/araui/widgets/ui_widget.c

- unify two if statement to one.
- simplify some statements.

framework/araui: Make the code simple

---

os/fs/inode/Make.defs
os/fs/inode/fs_fileclose.c
os/fs/inode/fs_filedetach.c
os/fs/inode/fs_fileopen.c
os/fs/vfs/fs_poll.c
os/include/tinyara/fs/fs.h

These function returns 'struct file'

fs: Add file functions 

---

apps/examples/nettest/Makefile
apps/examples/nettest/linux_server/build.sh
apps/examples/nettest/linux_server/server_sample.c
apps/examples/nettest/nettest.c
apps/examples/nettest/nettest_stress.c

- Add client application in nettest
- Add a reference linux server code in linux_server directory
- The server and client send and receive 10 packets by default, and then shutdown() is called randomly.

apps/example/nettest: Add stress test for TCP connection

---

docs/HowToPortTizenRTOnWiFiChipset.md
docs/HowToUseLWIP.md

- Update a way to port the new Wi-Fi chipset and how to use LwIP, reflecting the newly developed Network Manager

docs: Network porting guide update

---

build/tools/esp32/esptool_py/Makefile

this command is used to readback flash contents
in esp32 boards.

build/tools/esp32: Add erase read functionality

---

build/tools/esp32/esptool_py/Makefile
build/tools/esp32/esptool_py/partition_offset.py

Add erase specific flash region functionality in esp32 boards.
the start address and size muse be a multiple of 4096.

build/tools/esp32: Add erase flash functionality

---

os/include/tinyara/miniz/miniz.h

no spaces at the start of line
Signed-off-by: sunghan-chang <sh924.chang@samusng.com>

miniz: fix violations of coding rules

---

framework/src/media/utils/MediaUtils.cpp

framework/media: fix build error for compare logic

---

os/include/tinyara/net/net.h
os/net/netmgr/Make.defs
os/net/netmgr/bsd_socket_api.c
os/net/netmgr/uds.c
os/net/netmgr/uds.h

add user domain socket entry in bsd socket.
you can check whether it is user domain socket by the number of file descriptor

network: add user domain socket entry in bsd socket

---

apps/system/utils/netcmd_netmon.c
os/include/net/if.h
os/net/lwip/src/api/sockets.c
os/net/netdev/netdev_ioctl.c
os/net/netmgr/netdev_lwip.c
os/net/netmgr/netdev_mgr_internal.h
os/net/netmgr/netmgr_ioctl_lwip.c
os/net/netmgr/netmgr_ioctl_netmon.c
os/net/netmgr/netstack.c
os/net/netmgr/netstack.h
os/net/netmgr/netstack_lwip.c
os/net/socket/net_dupsd.c
os/net/socket/net_dupsd2.c

previous network monitoring uses lwIP api directly. So it can not be
used on loadable configuration.

network: refactoring network monitoring

---

docs/HowToUseTaskMonitor.md

Added TaskMonitor Readme file that contains descriptions and examples for the API

TizenRT/docs : Add HowToUseTaskMonitor

---

os/net/netmgr/bsd_socket_api.c
os/net/netmgr/netmgr_ioctl_netmon.c

net/netmgr: Fix typo

---

os/include/tinyara/net/net.h
os/net/Kconfig
os/net/local/Kconfig
os/net/local/Make.defs
os/net/local/local.h
os/net/local/local_accept.c
os/net/local/local_bind.c
os/net/local/local_conn.c
os/net/local/local_connect.c
os/net/local/local_fifo.c
os/net/local/local_listen.c
os/net/local/local_netpoll.c
os/net/local/local_recvfrom.c
os/net/local/local_recvutils.c
os/net/local/local_release.c
os/net/local/local_send.c
os/net/local/local_sendpacket.c
os/net/local/local_sendto.c
os/net/local/local_sockif.c

net/local: Add Unix domain (local) sockets

---

os/fs/vfs/fs_pwrite.c

fs/vfs: Update fs_pwrite

---

os/tools/memstats.py
os/tools/memstats_gnueabil.py
os/tools/memstats_xtensa.py

Python 2.7 will not be maintained past 2020.
So update python code to be able to run under python3.

tools/memstats: Make memstats run under python3

---

apps/examples/testcase/le_tc/filesystem/fs_main.c

1. Remove dependency of vfs tc
2. Separation Positive Case and Negative Case
3. Some TC bug fix

testcase/filesystem: Improve filesystem vfs testcase

---

external/include/libcxx/csignal
external/include/libcxx/cstdio
external/include/libcxx/cstdlib

Update C++ header files due to changes to C header files.
Backport changes from Nuttx.

external/include/libcxx: Update Some C++ header files

---

apps/system/utils/utils_ps.c
os/arch/arm/src/armv7-m/up_assert.c
os/binfmt/binfmt_exec.c
os/binfmt/binfmt_execmodule.c
os/binfmt/binfmt_loadbinary.c
os/binfmt/binfmt_loadmodule.c
os/fs/procfs/fs_procfsproc.c
os/include/tinyara/binfmt/binfmt.h
os/include/tinyara/sched.h
os/kernel/binary_manager/Make.defs
os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_callback.c
os/kernel/binary_manager/binary_manager_data.c
os/kernel/binary_manager/binary_manager_getinfo.c
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_recovery.c
os/kernel/group/group_leave.c
os/kernel/init/os_start.c
os/kernel/preference/preference_common.c
os/kernel/preference/preference_remove.c
os/kernel/preference/preference_write.c
os/kernel/pthread/pthread_create.c
os/kernel/sched/sched_releasetcb.c
os/kernel/task/Make.defs
os/kernel/task/task_create.c
os/kernel/task/task_exithook.c
os/kernel/task/task_terminate_unloaded.c

- kernel/binary_manager : Support real-time type of binary
- kernel/binary_manager: Refactor binary manager

kernel/binary_manager: Refactor binary manager

---

apps/examples/testcase/le_tc/filesystem/fs_main.c

Reverts Samsung/TizenRT#4128
- This PR updates half of all TCs, therefore remaining TCs fail due to the updates.
- So currently this PR is reverted and merged later after all TCs are updated.

Revert "testcase/filesystem: Improve filesystem vfs testcase"

---

external/dhcpd/dhcpd.c
os/arch/arm/src/imxrt/imxrt_enet.c
os/arch/arm/src/stm32/stm32_eth.c
os/arch/arm/src/tiva/tm4c_ethernet.c
os/drivers/net/enc28j60.c
os/include/tinyara/net/net.h
os/include/tinyara/net/net_lock.h
os/net/Makefile
os/net/local/local_conn.c
os/net/local/local_connect.c
os/net/local/local_listen.c
os/net/local/local_netpoll.c
os/net/local/local_release.c
os/net/net_initialize.c
os/net/net_initialize_netmgr.c
os/net/netmgr/net_vfs.c
os/net/utils/net_lock.c

net_lock returns 0 on success else returns a negated errno.
net_unlock doesn't need parameters.

net/utils: Add net_lock

---

os/net/local/Make.defs
os/net/local/uds_checksd.c
os/net/local/uds_net.h
os/net/local/uds_socket.h
os/net/local/uds_sockets.c
os/net/netmgr/bsd_socket_api.c
os/net/netmgr/net_vfs.c

Add uds_checksd function and connect with netmgr

net/local: Add uds_checksd

---

os/net/local/Make.defs
os/net/local/uds_net.h
os/net/local/uds_socket.c
os/net/local/uds_socket.h
os/net/local/uds_sockets.c
os/net/local/uds_sockif.c

Add uds_socket function and functions for using uds_socket

net/local: Add uds_socket

---

os/net/local/Make.defs
os/net/local/uds_accept.c
os/net/local/uds_bind.c
os/net/local/uds_close.c
os/net/local/uds_connect.c
os/net/local/uds_getpeername.c
os/net/local/uds_getsockname.c
os/net/local/uds_listen.c
os/net/local/uds_net.h
os/net/local/uds_recv.c
os/net/local/uds_recvfrom.c
os/net/local/uds_send.c
os/net/local/uds_sendto.c
os/net/netmgr/Make.defs
os/net/netmgr/netstack_uds.c

Add uds_xxx and connect to netmgr

net/local: Add uds code

---

framework/include/araui/ui_asset.h
framework/include/araui/ui_commons.h
framework/include/araui/ui_core.h
framework/src/araui/include/ui_math.h

- Revise typos
- Add SAMSUNG license
- Revise unchaged descriptions for API

framework/araui: Revise typos in the headers of AraUI.

---

build/tools/esp32/esptool_py/partition_offset.py
build/tools/esp32/partiton_table/gen_esp32part.py
build/tools/esp32/partiton_table/parttool.py
os/tools/discover.py
os/tools/mkbinheader.py
os/tools/mkchecksum.py
os/tools/s5jchksum.py
os/tools/xmlrpc_test.py
tools/ramdump/dumpParser.py
tools/ramdump/gui_dumpParser.py
tools/ttrace_parser/scripts/ttrace.py
tools/ttrace_parser/scripts/ttrace_tinyaraDump.py
tools/ttrace_parser/ttrace_tinyara.py

Python 2.7 will not be maintained past 2020.
So update python code to be able to run under python3.

os/tools : Make binary header run under python3

---

os/arch/arm/src/s5j/s5j_serial.c
os/arch/arm/src/stm32/stm32_serial.c
os/board/stm32f407-disc1/src/stm32_userleds.c
os/board/stm32f429i-disco/src/stm32_userleds.c
os/pm/pm_changestate.c
os/pm/pm_procfs.c

os/pm : provide proper typecast and const char arguments for write
os/arch/arm/src/ : update pm_register() call on some boards
os/board/ : update pm_register() call on some boards

Resolves PM related build errors on some boards

---

framework/include/araui/ui_animation.h

framework/araui: Fix typo

---

docs/HowToSupportTizenRtProtectedBuild.md
docs/Porting_Guide.md
docs/ProtectedBuildGuide.md

Signed-off-by: Nishtha97 <n.maloo@samsung.com>

Protected build Porting document

---

apps/examples/testcase/le_tc/filesystem/fs_main.c
apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
apps/examples/testcase/le_tc/filesystem/tc_internal.h

1. UTC/ITC isolate - Currently utc itc is run together in "filesystem_tc" cmd
2. Remove dependency of fs utc - Remove dependencies between test cases
3. Separation Positive Case and Negative Case
3. Some TC bug fix

testcase/filesystem: Improve filesystem testcase

---

external/stdk/README.md

- update README following th 'STDK v1.0.10'

external/stdk: update README.md

---

os/fs/driver/mtd/smart.c

-Separated CRC check modifications for host build
from on-device functioning usinf NXFUSE_HOST_BUILD flag.
-Avoids unneccessary erase of eraseblocks due to CRC
invalidation of completely erased logical sectors during
host build.

os/fs/driver/mtd: Fix for CRC check during smartfs-image host build

---

os/arch/arm/src/imxrt/imxrt_lowputc.c
os/board/common/crashdump.c
tools/ramdump/ramdump_tool.c

This patch adds external ramdump to existing ramdump tool for imxrt1050 board

Add external ramdump support for imxrt1050 board

---

apps/examples/testcase/le_tc/filesystem/fs_main.c

1. Add some functions description
2. Some functions have been rename to their correct meanings

testcase/filesystem: Add functions description and Fix functions name

---

lib/libc/time/lib_localtime.c

It needs the zoneinfo rule that was previously registered as the
system time base (1970/01/01). Because it needs to find out which
rules to apply based on the current time.
For example In Japan, the last rule registered was 1951.
So the rule was not applied properly.

libc/time : Modify the logic to save the zoneinfo rule

---

external/stdk/tizenrt-wrapper/os/iot_os_util_tizenrt.c

- update STDK verssion to 1.1.0
- modify stdk-tizenrt-wrapper

external/stdk: update STDK version to 1.1.0

---

framework/src/arastorage/aql_exec.c

arastorage: Remove unused specifier

---

os/net/netmgr/net_vfs.c
os/net/netmgr/netstack.h

netstack_ops has initlist, releaselist operation

net/netmgr: Add initlist, releaselist ops

---

apps/examples/camera/camera_main.c

- FPS was bad when reading from driver and writing to file-system
was in same thread, moved write to a separate thread so that
FS write delay will not impact the frame read time.

apps/examples/camera: Improve frame rate by separating rw threads

---

os/wqueue/work_queue.c

os/wqueue: fix typo

---

apps/system/utils/utils_stackmonitor.c

terminated_infos can be affected with another configs, like CONFIG_MAX_TASKS.
So that it can also affect the stack size of stack monitor.
Changing that array to be allocated can avoid the problem.

apps/system/utils : Change to allocate array which saved terminated info

---

framework/include/media/BufferOutputDataSource.h

framework/media: remove unnecessary comments

---

docs/HowToConfirmNetworkPorting.md
docs/HowToSupportTizenRtProtectedBuild.md
docs/HowToUseSmartFSDumpVisualizer.md
docs/InstallAdReq.md
docs/ProtectedBuildGuide.md
os/arch/arm/src/tiva/tiva_allocateheap.c
os/board/stm32l4r9ai-disco/src/stm32_spi.c

I fixed some typos in docs directory.

docs: fix typo

---

apps/examples/testcase/le_tc/filesystem/fs_main.c
apps/shell/tash_main.c

apps/example/testcase/fs_main : Add #ifdef for local variable in vfs unlink tc
apps/shell/tash_main : Add #ifdef for tash_clear_line function

Add #ifdef condition for avoiding build error.

---

apps/examples/camera/camera_main.c
os/drivers/video/video.c
os/drivers/video/video_null_driver.c

os/drivers/video - NULL driver
- Fix NULL Driver file read problems.
- Add delay setting function for worker in NULL Video Driver.
apps/examples/camera - camera main
- Change Camera app frame saving directory.
os/drivers/video - video.c
- Change checking point for return value from set_buf() in change_video_state()

Update Video Driver, NULL Driver for video and Camera app features.

---

.travis.yml

Add privileged permission for running external script

travis.yml : Add privileged option in travis script

---

docs/LoadableAppsConfigurationUserGuide.md

This patch adds a reference document to support loadable apps
configuration for a new chipset.

Loadable Apps Reference Document

---

os/arch/arm/Kconfig
os/arch/arm/src/armv7-m/Kconfig
os/arch/arm/src/armv8-m/Kconfig

1. arch/arm: add new configs for arm architecture family 
2. arch/arm/Kconfig: tidy up mpu config
3. arch/arm/armv7-m, armv8-m: remove unnecessary condition

arch/arm: tidy up Kconfig in arm

---

os/kernel/binary_manager/binary_manager_load.c

kernel/binary_manager: Fix typo

---

os/arch/arm/src/common/up_createstack.c
os/arch/arm/src/imxrt/imxrt_mpuinit.c
os/binfmt/binfmt_execmodule.c
os/binfmt/binfmt_loadbinary.c
os/include/tinyara/mpu.h

- MPU region numbers are defined in enum MPU_REG_NUM

Set proper structure for MPU regions

---

os/fs/driver/Make.defs
os/fs/driver/mtd/Kconfig
os/fs/driver/mtd/mtd_jedec.c
os/include/tinyara/fs/mtd.h

1. Add mtd driver for jedec
2. Add routines for new mtd driver

fs/mtd : Add common mtd driver which uses jedec interface

---

os/arch/arm/src/amebad/amebad_serial.c

This PR contains the following changes:
1. Changes to fix certain UART test cases.
All commits have been labelled with respective changes.

os/arch/arm/src/amebad fix for UART test case issue

---

os/binfmt/elf.c
os/include/tinyara/binfmt/binfmt.h
os/kernel/binary_manager/binary_manager_binfile.c
os/kernel/binary_manager/binary_manager_load.c

binfmt : Change ifdef conditions for textsize in binary_s
binary_manager : Remove unused local variables

binfmt : Change ifdef conditions for textsize in binary_s

---

apps/examples/testcase/le_tc/filesystem/fs_main.c

It is covered by bch testcases in drivers testcase.

testcase/filesystem: Remove ftl testcase

---

framework/src/wifi_manager/wifi_manager_message.c
framework/src/wifi_manager/wifi_manager_msghandler.c
os/drivers/lwnl/lwnl_evt_queue.c

- fix wifi manager init for binary recovery

framework/wifi_manager: fix wifi initialize logic.

---

.travis.yml

- add branch for building test

travisCI: update check branch on travisCI

---

os/fs/driver/mtd/smart.c

- Function name smart_validate_erase_block() is
misleading. Rename to smart_validate_sector.
- Add logicalsector number validity check
before adding to sector sequence log.

os/fs/driver/mtd: Fix CRC check function name and logicalsector check

---

os/arch/arm/src/imxrt/imxrt_serial.c
os/arch/arm/src/s5j/s5j_serial.c
os/arch/arm/src/stm32l4/stm32l4_serial.c
os/arch/arm/src/tiva/tiva_serial.c
os/arch/xtensa/src/esp32/esp32_serial.c
os/drivers/serial/serial.c
os/drivers/serial/serialirq.c
os/drivers/serial/uart_16550.c
os/drivers/usbdev/cdcacm.c
os/drivers/usbdev/pl2303.c
os/drivers/usbhost/usbhost_cdcacm.c
os/include/signal.h
os/include/tinyara/serial/serial.h
os/include/tinyara/serial/tioctl.h

1. Expand dev structure to use signal
2. Modify Lower driver use uart_dev_s, instead of file pointer, upper can call ioctl everywhere.
3. Modify Interrupt Logic to fix unwanted disabling.
4. Add tioctl to get information of lower level driver.

Modifiy serial logic

---

loadable_apps/loadable_sample/wifiapp/binary_update.c

loadable_apps/loadable_sample/wifiapp: Remove unused variables

---

os/binfmt/binfmt_exit.c
os/binfmt/binfmt_unloadmodule.c
os/binfmt/libelf/libelf_addrenv.c
os/mm/mm_heap/mm_memalign.c

This PR contains following commits:
- Modify memalign to reduce memory requirement for alginment
- Modify loader to avoid multiple memalign request for each elf section

Reduce app loading memory requierment

---

os/drivers/serial/serialirq.c

This reverts commit 66286dffd944783f4061fecde4f1c753e6ebace5.
This works well with another board but artik053 hanged during booting time.
So revert it for now

Revert "driver/serial : Fixed unwanted disabling of TX Interrupt"

---

apps/examples/wifi_manager_sample/wm_test.c

Modify Wifi manager tash command to check softap cmd argc, and sta connection arg copy.

examples/wifi_manager_sample: Modify WIFI Manager cmd on input checking

---

os/fs/driver/mtd/Kconfig
os/fs/driver/mtd/smart.c
os/fs/smartfs/Kconfig

Add Kconfig & Basic Structure of Journal
Remove unuseful Log

os/fs/smartfs : Apply basic structure & Config of Journaling

---

external/dhcpc/dhcpc.c

Add support for multiple DNS configuration
Signed-off-by: Deepak sharma <deepak.sh@samsung.com>

external/dhcpc : support multiple DNS configuration

---

lib/libc/stdio/lib_sscanf.c

Currenlty it does not support. When the type of getting result
is less than int, sscanf removes outsid of result buffer.
for example,
char ret[10] = "efghi";
char buf[10] = "1:2:3";
sscanf(buf, "%hhx:%hhx:%hhx", &ret[0], &ret[1], &ret[2]);
Then, ret should be "123hi", but because of not support hh modifier
it becomes "123".
This is partially back-ported from nuttx commit 350295d.

libc/stdio: support hh, h, int, long, long long modifier in sscanf

---

apps/examples/wifi_manager_sample/wm_test.c

Add a command to wm_test to get connected AP info.

network/wifi_manager: get connected AP info

---

os/fs/driver/mtd/Kconfig
os/fs/driver/mtd/smart.c

1. Add journal area feature
2. Add init routine of journal
3. Add logic to Allocate physical sectors for journal.
4. Reduce dev->erasesize if journal sector is necessary.
5. Clean code where use geo->eraseblock

os/fs/smartfs : Apply journal area feature

---

apps/examples/testcase/le_tc/kernel/tc_pthread.c

1. Pthread_join in line 641 tries to wait/join the already terminated pthread.
In this case, pthread_join returns ESRCH.
2. Add EINVAL case TC. EINVAL will be returned when passing the task's pid in pthread_join.

apps/examples/tc_pthread : Modify wrong return check in pthread join tc

---

framework/src/binary_manager/binary_manager_interface.c
os/arch/arm/src/armv7-m/up_blocktask.c
os/arch/arm/src/armv7-m/up_releasepending.c
os/arch/arm/src/armv7-m/up_reprioritizertr.c
os/arch/arm/src/armv7-m/up_svcall.c
os/arch/arm/src/armv7-m/up_unblocktask.c
os/arch/arm/src/armv7-m/up_unblocktask_withoutsavereg.c
os/arch/arm/src/armv8-m/up_blocktask.c
os/arch/arm/src/armv8-m/up_releasepending.c
os/arch/arm/src/armv8-m/up_reprioritizertr.c
os/arch/arm/src/armv8-m/up_svcall.c
os/arch/arm/src/armv8-m/up_unblocktask.c
os/binfmt/libelf/libelf_bind.c
os/drivers/i2c/i2c_uio.c
os/include/tinyara/debug/sysdbg.h
os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_binfile.c
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_recovery.c
os/kernel/debug/sysdbg.c
os/kernel/pthread/pthread_create.c
os/kernel/semaphore/sem_post.c
os/kernel/semaphore/sem_trywait.c
os/kernel/semaphore/sem_wait.c
os/kernel/semaphore/sem_waitirq.c
os/kernel/task/task_execv.c
os/kernel/task/task_terminate_unloaded.c
os/mm/kmm_heap/kmm_initialize.c

1. AQUIRE -> ACQUIRE
2. warnings at binary_manager, binfmt, mm and etc

fix typo and fix warnings

---

os/fs/driver/mtd/smart.c

1. Apply Logic regarding journal block
2. Apply checkout / checkin logic
3. Optimize Bit-operation of journal type and state
4. Apply basic logic of init and recovery

os/fs/smartfs : Apply Basic Step of Journal

---

os/fs/driver/mtd/smart.c

1. add smart_validate_journal_crc
2. remove useless definitions

os/fs/smartfs : Add smart_validate_journal_crc to verify crc of journal

---

os/fs/driver/mtd/smart.c

1. Add logic to handle MTD_WRITE, smartfs_bytewrite, MTD_ERASE
2. Add logic to logging above operation.
3. Add basic routine to handle recovery.
4. Add some more comments to understand logic

os/fs/smartfs: Apply journal logic for all MTD operation

---

os/fs/driver/mtd/smart.c

1. Remove unncessary log regarding verify block.
2. Fix typo
3. Remove code which restrict allocation for sector 0

os/fs/smartfs: Clean unnecessary code

---

os/fs/driver/mtd/smart.c

1. Add basic recovery logic, it release again if journal data is exist.

os/fs/smartfs : Apply basic recovery logic of SMART_JOURNAL_TYPE_RELEASE

---

os/fs/smartfs/smartfs_utils.c

1. To guarantee integrity of entry or chaining, we have to reorder flow.
2. For delete, update entry or chaining should be done at the first time.
3. If power off after change entry or chaining, there should be isolated sector
4. We will reuse fs_recover in master branch to handle this.

os/fs/smartfs: Change flow of smartfs_deleteentry

---

os/kernel/binary_manager/binary_manager_load.c

If g_sem_list is empty, it means there is no kernel semaphore which used by threads.
For checking this, added the debug message.

kernel/binary_manager_load : Add Debug message for checking g_sem_list

---

os/fs/driver/mtd/smart.c

1. Add logic to check crc of written data on data sector
2. Clean checkout logic
3. Modify comment more clearly.

os/fs/smartfs : Apply Recovery logic for commit type

---

os/fs/driver/mtd/smart.c

Release flag doesn't set, so fix it.

os/fs/smartfs : Fix bug it never release sector

---

os/fs/driver/mtd/smart.c

After journal we should update some counts in smartfs_dev, for example dev->releasecount
To calculate this, we have to finish smart_scan. So modify to initialize journal
before smart_scan execute.
So we don't need extra Map structure for loser anymore.

Adjust init time of journal

---

os/fs/driver/mtd/smart.c

Remove unnecessary code & add missing return

os/fs/smartfs : Delete unusing code

---

os/arch/arm/src/stm32l4/stm32l4_flash.c

Fix unsages of undefined function, sem_wait/post and ferr/info.

arch/stm32l4: Fix usages of undefined function.

---

os/include/tinyara/netmgr/netdev_mgr.h

include/tinyara/netmgr: fix typo

---

os/fs/smartfs/Kconfig
os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_utils.c
tools/nxfuse/mknxfuse.sh

1. Recover unchained(isolated) sector due to sudden power
2. This can be used stand alone but with journal is much better.
3. Use timestamp instead of UTC if config is not set

os/fs/smartfs: apply sector recovery

---

os/fs/smartfs/smartfs_smart.c

If CRC is enabled, it uses sector buffer. This buffer always include
information of its header, otherwise data corruption happened

os/fs/smartfs : Read sector data when it open

---

os/kernel/binary_manager/binary_manager_data.c

When adding tcb to binary list, it is added to a head of list.
So a blink of old head should pointed to new head.

kernel/binary_manager: Link blink of old head to new head when adding tcb to binary list

---

os/board/rtl8721csm/src/component/os/os_dep/include/osdep_service.h
os/board/rtl8721csm/src/component/os/os_dep/osdep_service.c
os/board/rtl8721csm/src/component/os/tizenrt/tizenrt_service.c

1. Replace all Application API on rtl8721csm OS related API with Kernel API

board/rtl8721csm/src/component/os: Replace Application API on Kernel level

---

os/fs/driver/mtd/smart.c

- change struct smart_journal_logging_data_s ->
smart_journal_entry_s.
- change njournaldata -> njournalentries in struct
smart_struct_s

os/fs/driver/mtd : Modify journaling object structures

---

lib/libc/unistd/Make.defs
lib/libc/unistd/lib_truncate.c
os/fs/procfs/fs_procfs.c
os/fs/romfs/fs_romfs.c
os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c
os/fs/tmpfs/fs_tmpfs.c
os/fs/vfs/Make.defs
os/fs/vfs/fs_truncate.c
os/include/tinyara/fs/fs.h
os/include/unistd.h

Apply ftruncate to vfs & each of file system

os/fs : Add ftruncate

---

os/fs/smartfs/smartfs_utils.c

- No need to read sector data again as fs->fs_rwbuffer
already holds sector data.
- No need for label for general return statement.

os/fs/smartfs: Do away with unecessary BIOC_READSECT request in smartfs_deleteentry()

---

build/configs/imxrt1020-evk/imxrt1020-evk_download.sh
build/configs/imxrt1050-evk/imxrt1050-evk_download.sh
build/configs/usbrule.sh

1. build/configs: tidyup of usbrule script 
2. config/imxrt10x0-evk: use different idVendor and idProduct values

configs/imxrt: tidyup usbrule.sh and fix USB rule values of imxrt

---

os/fs/driver/mtd/smart.c

os/fs/driver/mtd: Do away with unnecessary ERROR condition labels

---

apps/shell/tash_command.c

there was no clear command. Added.

apps/shell: Add clear command on TASH

---

os/fs/driver/mtd/smart.c

if dump option is enabled, it print all journal, it will print checkin only if dump is disabled

fs/smartfs : Print only checkin journal if dump option is disabled

---

build/configs/imxrt1020-evk/SAM/Make.defs
build/configs/imxrt1020-evk/helloxx/Make.defs
build/configs/imxrt1020-evk/loadable_elf_apps/Make.defs
build/configs/imxrt1020-evk/reliability_test/Make.defs
build/configs/imxrt1020-evk/tc/Make.defs
build/configs/imxrt1050-evk/helloxx/Make.defs
build/configs/imxrt1050-evk/loadable_elf_apps/Make.defs

Set proper LD files for build in windows environment.

build/configs/imxrt1020, imxrt1050: Set proper LD scripts for build 

---

apps/examples/smartfs_powercut/Kconfig
apps/examples/smartfs_powercut/Kconfig_ENTRY
apps/examples/smartfs_powercut/Make.defs
apps/examples/smartfs_powercut/Makefile
apps/examples/smartfs_powercut/smartfs_powercut_main.c
loadable_apps/loadable_sample/wifiapp/wifiapp.c

Add application for auto testing.
It use all apis which handle  entry of smartfs.
Also to check integrity of journal, use 2 size of buffer, one is small(st_blksize) one is large

apps/smartfs_powercut : Add auto powercut test app

---

os/fs/smartfs/smartfs_smart.c

If file modified but appending is needed due to remained buffer,
smartfs will change current sector to next sector of current sector
But if current sector was last sector, next sector in header is empty, so chain breaks.

fs/smartfs : Fix to avoid set next sector as empty

---

build/tools/amebad/gnu_utility/AP2_KM4.JLinkScript
build/tools/amebad/gnu_utility/README.md
build/tools/amebad/gnu_utility/jlink_debug.sh
build/tools/amebad/gnu_utility/rtl_gdb_debug.txt

Please read the 'README.md' for the use of the Jlink debug function.

build/tools/amebad: Add Jlink Debug Function

---

os/board/common/Kconfig
os/board/common/common.h
os/board/common/partitions.c

User can configure partitions of external flash.

board: Support partition configuration of external flash

---

os/fs/driver/mtd/smart.c

Journal follows checkin -> data write -> header write -> checkout.
If power cut happened after data write, it should checkout process but it didn't
Also if transaction failed in the middle of journal process, release working sector & checkout current journal

fs/smartfs : Update journal recovery logic

---

os/fs/driver/mtd/smart.c

Journal operation using MTD Operation, so return should be checked carefully.
So clean code to improve readability

fs/smartfs : Clean return of journal operations

---

os/fs/driver/mtd/smart.c

If sector data & header written properly but checkout wasan't, checkout only should be done.
But it checked data & journal data again, and do something more, so fix logic to avoid
unnecessary process.

fs/smartfs : Fix power cut issue

---

framework/include/binary_manager/binary_manager.h
framework/src/binary_manager/binary_manager_update.c
loadable_apps/loadable_sample/wifiapp/binary_update.c
os/include/tinyara/binary_manager.h
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_data.c
os/kernel/binary_manager/binary_manager_getinfo.c
os/kernel/binary_manager/binary_manager_load.c
os/tools/mkbinheader.py

Binary manager manages kernel version as float type.

kernel/binary_manager: Change a type of kernel version to float

---

os/fs/smartfs/smartfs_utils.c

Bit operation is always faster than divide operation, so change divide by 8 to shift 3bits.

fs/smartfs : Change divide operation to bit operation.

---

os/drivers/seclink/seclink_drv_key.c
os/drivers/serial/serial.c

1. drivers/seclink: remove unreachable statement 
2. drivers/serial: remove unreachable statement

remove unreachable statement

---

os/fs/vfs/fs_unlink.c

The inode->u.i_ops, line 157, is confirmed at previous line, line 152, as it's not null
so that line 157, if conditaional checking and line 210, else statement is unnecessary.

fs/vfs: remove unreachable statement

---

lib/libc/misc/lib_sendfile.c

The sendfile has return value with ssize_t. But the count argument which
gives the size user requests is size_t type. So, the ntransferred variable
which shows transferred size could be overflowed.
Before sending the read data, let's check the transferred size and new
requested sending data size and adjust the size not to overflow.

libc/misc: add size limitation of sendfile

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c

Fix wifi connection issue in hello config.
RTK mpu settings are enabled.

os/board/rtl8721csm: Fix wifi connection issue.

---

os/fs/driver/mtd/smart.c

If CONFIG_MTD_SMART_SECTOR_ERASE_DEBUG set, it will show erase count of journal block

fs/smartfs : Add erase info of journal block

---

apps/system/utils/fscmd.c

there's no mv, so we can't test rename in tash, so add it

fs/fscmd : Add mv

---

os/fs/smartfs/smartfs_smart.c

- Current code supports only rename/move operations on files.
- We should support directory renaming also.
- Moving directories will not be supported.

os/fs/smartfs: Support renaming of directories in smartfs

---

os/fs/smartfs/smartfs_smart.c

- Instead of calling smartfs_writeentry, use FS_IOCTL to overwrite only
the entry name avoiding other unnecessary steps.

os/fs/smartfs: Write only new entry name in case of renaming an entry in the same sector.

---

os/include/debug.h

fsdbg deleted before by mistake, so restore it

debug/fs : Restore fsdbg

---

os/fs/driver/mtd/smart.c
os/fs/smartfs/Kconfig

fs/smartfs : Fix coding rule violation

---

os/fs/driver/mtd/smart.c

Apply log level for smart_journal_print_log, also add more info if write_sector failed

fs/smartfs : Update log infor of journal & mtd operation

---

apps/examples/smartfs_powercut/smartfs_powercut_main.c
os/fs/driver/mtd/smart.c
os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_utils.c

fs/smartfs : Fix typo

---

os/fs/driver/mtd/smart.c
os/include/debug.h

Display sector scan log if DEBUG_INFO is enabled, and clean code regarding fsdbg in debug.h

fs/smartfs : Modify debug message

---

os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c

- Add error code to all error debug logs in smartfs fs layer.

os/fs/smartfs: Update debug logs with error codes

---

os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c

- Change variable name for file data length in entry structure
from 'datlen' to 'datalen'.

os/fs/smartfs: Update variable name in entry structure

---

os/include/sys/syscall.h
os/syscall/syscall.csv
os/syscall/syscall_lookup.h
os/syscall/syscall_stublookup.c

register ftruncate as a syscall

fs/truncate : add ftruncate to syscall

---

os/fs/driver/mtd/smart.c

If level of crc is same but journal state is different, guide it to lower level format

fs/smartfs : Add journal format to signature sector, logical 0

---

os/fs/driver/mtd/smart.c
os/fs/smartfs/smartfs_procfs.c
os/include/tinyara/fs/smart_procfs.h

Add dump for smartfs function to procfs
usuage :
For dump all : cat /proc/fs/smartfs/smart0p3/dump_all
For dump specific sector : echo # > /proc/fs/smartfs/smart0p3/dump

procfs/smart : Add sector dump of smartfs to procfs

---

os/arch/arm/src/amebad/amebad_serial.c
os/board/common/crashdump.c
os/board/rtl8721csm/src/Makefile
tools/ramdump/ramdump_tool.c

This patch adds ramdump support fo rrealtek board.

Ramdump support for Realtek Board

---

apps/system/utils/fscmd.c

truncate & append doesn't work properly so fix it

tash/cat : redirection doesn't work properly

---

os/fs/smartfs/smartfs_smart.c

If user modify current contents to the end of contents, it will update
wrong value for last sector's nextsector

fs/smartfs : Fix last sector chain to wrong sector when modify contents

---

build/configs/rtl8721csm/rtl8721csm_download.sh

This update is to fix the "Specified filename ttyUSB1 does not exist" bug.

build/configs/rtl8721csm: Bug fix for download_tool

---

os/fs/vfs/fs_truncate.c

It is Same as posix, change to set EINVAL as a errno

fs/ftruncate : set errno as EINVAL if length is negative

---

os/arch/arm/src/common/up_createstack.c

Cleanup stack overflow protection by adding guard region to kernel
tasks as well

os/arch/arm: Stack protection code cleanup.

---

apps/examples/testcase/le_tc/filesystem/fs_main.c

Add 1 positive & 3 negative utc for ftruncate.
change tc_fs_vfs_write_invalid_len_n to tc_fs_vfs_write_invalid_flags_n, it is related to flag of open()

fs/utc : Add utc for ftruncate, and fix wrong name of function

---

apps/examples/smartfs_powercut/smartfs_powercut_main.c

Added ftruncate function, so modify app to use it.
Now we can test below.
1. Create entry(mkdir, open)
2. Move Entry(rename)
3. Update Contents
4. Append Contents
5. ftruncate(shrink, extend)
6. Delete entry(rmdir, unlink)

app/smartfs_powercut : Modify powercut test app

---

os/arch/arm/src/common/up_allocateheap.c

Kheap is created based on ram regions defined in the configuration.
The configuration provides the physical start address and size of each
region. It is possible that some ram region might contain data and stack
of the kernel. In such case, the kheap is created after the stack. But,
if the ram region is defined such that the data and stack regions extend
outside of the ram region, then it is an error. This commit checks for
such error condition and causes the device to assert on errors.

os/arch/common: Add error check for kheap allocate api

---

.travis.yml

- Remove artik053/grpc
- Add rtl8721csm/loadable_apps

travis: Remove artik053/grpc and Add rtl8721csm/loadable_apps

---

apps/examples/smartfs_powercut/smartfs_powercut_main.c

- Add functions to create, verify and recover text files.

apps/smartfs_powercut: Modify to add test functions for text files

---

build/configs/rtl8721csm/hello/Make.defs
build/configs/rtl8721csm/loadable_apps/Make.defs
build/configs/rtl8721csm/rdp/Make.defs
build/configs/rtl8721csm/security_hal_test/Make.defs
build/configs/rtl8721csm/tc/Make.defs
os/arch/arm/src/amebad/Make.defs

- add TrustZone configuration into all exmaple Make.defs
- Remove unused define

build/configs/rtl8721csm: add TrustZone configuration into all example Make.defs

---

os/fs/driver/mtd/smart.c

Actually it is very less chance that happen it failed, but add it to for powercut test.

fs/smartfs : Add verify code for release type

---

os/fs/driver/mtd/smart.c

Before calculate journal crc, check validation of its contents first.

fs/smartfs : Add logic to check journal contents before recovery

---

os/fs/smartfs/smartfs_utils.c

- Clean code for smartfs_shrinkfile and assign proper number
for bytes used in last active data sector of file.

os/fs/smartfs: Fix improper used bytes assignment to last sector and clean shrinkfile()

---

os/board/artik05x/src/artik05x_tash.c
os/board/imxrt1020-evk/src/imxrt_bringup.c
os/board/imxrt1050-evk/src/imxrt_bringup.c
os/board/sidk_s5jt200/src/s5jt200_tash.c

os/board codes are in kernel side, so memory allocation should be changed to kmm_Xalloc APIs

board : Modify malloc to kmm_malloc from os/board folder

---

os/fs/smartfs/smartfs_utils.c
os/fs/vfs/fs_pread.c

1. Fix unrechable code
2. Fix derefence wihtout validation check

fs : Fix svace issue

---

apps/system/utils/README.md

Add description of mv, and remove description regarding mkrd, mksmartfs which removed before

fscmd/mv : Add description to readme.md

---

loadable_apps/loadable_sample/wifiapp/binary_update.c

Close file descriptors opened by function 'open' but not closed.

loadable_apps/binary_update: Close opened file descriptors

---

os/arch/arm/src/armv7-m/up_blocktask.c
os/arch/arm/src/armv7-m/up_releasepending.c
os/arch/arm/src/armv7-m/up_reprioritizertr.c
os/arch/arm/src/armv7-m/up_schedyield.c
os/arch/arm/src/armv7-m/up_svcall.c
os/arch/arm/src/armv7-m/up_unblocktask.c
os/arch/arm/src/armv7-m/up_unblocktask_withoutsavereg.c
os/arch/arm/src/armv8-m/up_blocktask.c
os/arch/arm/src/armv8-m/up_releasepending.c
os/arch/arm/src/armv8-m/up_reprioritizertr.c
os/arch/arm/src/armv8-m/up_schedyield.c
os/arch/arm/src/armv8-m/up_svcall.c
os/arch/arm/src/armv8-m/up_unblocktask.c
os/arch/arm/src/armv8-m/up_unblocktask_withoutsavereg.c
os/arch/arm/src/common/up_createstack.c
os/arch/arm/src/common/up_releasestack.c
os/include/tinyara/mpu.h

- Add Stack Overflow protection support for kernel threads in
addition to existing support for user threads.

os/arch/arm/src: Support Stack Overflow Protection for Kernel threads

---

os/arch/arm/src/imxrt/Kconfig
os/arch/arm/src/imxrt/Make.defs
os/arch/arm/src/imxrt/imxrt_ehci.c
os/arch/arm/src/imxrt/imxrt_ehci.h
os/arch/arm/src/imxrt/imxrt_usbhost.c
os/arch/arm/src/imxrt/imxrt_usbhost.h
os/arch/arm/src/imxrt/usb/host/usb_host.h
os/arch/arm/src/imxrt/usb/host/usb_host_devices.c
os/arch/arm/src/imxrt/usb/host/usb_host_devices.h
os/arch/arm/src/imxrt/usb/host/usb_host_ehci.c
os/arch/arm/src/imxrt/usb/host/usb_host_ehci.h
os/arch/arm/src/imxrt/usb/host/usb_host_hci.c
os/arch/arm/src/imxrt/usb/host/usb_host_hci.h
os/arch/arm/src/imxrt/usb/host/usb_porting.c
os/arch/arm/src/imxrt/usb/include/usb.h
os/arch/arm/src/imxrt/usb/include/usb_host_config.h
os/arch/arm/src/imxrt/usb/include/usb_misc.h
os/arch/arm/src/imxrt/usb/include/usb_porting.h
os/arch/arm/src/imxrt/usb/include/usb_spec.h
os/arch/arm/src/imxrt/usb/phy/usb_phy.c
os/arch/arm/src/imxrt/usb/phy/usb_phy.h
os/board/imxrt1020-evk/src/Makefile
os/board/imxrt1020-evk/src/imxrt_bringup.c
os/board/imxrt1050-evk/src/Makefile
os/board/imxrt1050-evk/src/imxrt_bringup.c

-Add support for USB host driver, initial driver to support TizenRT
host driver stack. This commit is currently been tested only with
camera driver(uvc).

arch/arm/src/imxrt: NXP USB Host driver

---

os/arch/arm/src/imxrt/usb/host/usb_host.h
os/arch/arm/src/imxrt/usb/host/usb_host_ehci.c
os/arch/arm/src/imxrt/usb/host/usb_host_ehci.h
os/arch/arm/src/imxrt/usb/host/usb_host_hci.c
os/arch/arm/src/imxrt/usb/include/usb_host_config.h

disbale -> disable
destory -> destroy
addresss -> address
informations -> information
transfering -> transferring
sleeped -> slept

arch/imxrt/usb: fix typos

---

apps/examples/wifi_manager_sample/wm_test.c
framework/include/wifi_manager/wifi_manager.h
framework/src/wifi_manager/wifi_manager_msghandler.c
os/include/tinyara/wifi/wifi_common.h

Add WPA3 parameters to wm_test, wifi_manager, and wifi_utils layer.

network/wifi_manager: Add WPA3 type

---

os/net/lwip/src/core/ipv6/ip6.c
os/net/lwip/src/core/ipv6/nd6.c
os/net/netdev/netdev_ioctl.c

WGID
185441
164736
185295
185442

network: fix svace issue

---

build/tools/amebad/gnu_utility/README.md

1) Modify J-link and AmebaD connections
2) Add the path for clarification

build/tools/amebad : Update J-link README.md

---

apps/examples/simple_file_transfer/.gitignore
apps/examples/simple_file_transfer/Kconfig
apps/examples/simple_file_transfer/Kconfig_ENTRY
apps/examples/simple_file_transfer/Make.defs
apps/examples/simple_file_transfer/Makefile
apps/examples/simple_file_transfer/README.txt
apps/examples/simple_file_transfer/sft_main.c
tools/net/simple_file_transfer.py

add simple file transfer
host: tools/net/simple_file_transfer.py
target: sft

apps/example: add simple file transfer

---

os/drivers/usbhost/Kconfig
os/drivers/usbhost/uvc/Kconfig
os/drivers/usbhost/uvc/Make.defs
os/drivers/usbhost/uvc/usbhost_uvc.h
os/drivers/usbhost/uvc/usbhost_uvc_ctrl.c
os/drivers/usbhost/uvc/usbhost_uvc_driver.c
os/drivers/usbhost/uvc/usbhost_uvc_v4l2.c
os/drivers/usbhost/uvc/usbhost_uvc_video.c

-Add support for USB video class driver for camera support.

drivers/usbhost: Add USB UVC class driver

---

os/arch/arm/src/imxrt/imxrt_i2s.c
os/arch/arm/src/imxrt/imxrt_i2s_edma.c
os/arch/arm/src/s5j/s5j_dma.c
os/arch/arm/src/s5j/s5j_dma_m2m_sb_4B_x256.c
os/arch/arm/src/s5j/s5j_dma_m2p_sb_4B_x256.c
os/arch/arm/src/s5j/s5j_dma_p2m_sb_4B_x256.c
os/arch/xtensa/src/esp32/esp32_i2s.c
os/arch/xtensa/src/esp32/esp32_spi.c
os/audio/audio.c
os/drivers/spi/spi_bitbang.c
os/fs/smartfs/smartfs_utils.c
os/pm/pm_metrics.c

In kernel, we should use kmm_zalloc and kmm_free for using kernel heap.
So changed them.

os : Change zalloc and free to kmm_zalloc and kmm_free

---

os/drivers/lwnl/lwnl_evt_queue.c
os/drivers/net/telnet.c
os/net/lwip/src/netif/ppp/auth.c
os/net/lwip/sys/arch/sys_arch.c
os/net/netmgr/netdev_lwip.c
os/net/netmgr/netdev_mgr_internal.c
os/net/netmgr/netstack_lwip.c

modify calling malloc in network stack in kernel space

network: fix calling malloc in network kernel space

---

os/kernel/Kconfig

Fix typo : application, will
Add close parenthesis

os/kernel/Kconfig : Fix typo and Add missed parenthesis

---

os/include/tinyara/binary_manager.h
os/kernel/binary_manager/binary_manager.c

kernel/binary_manager: change NAME_MAX to BIN_NAME_MAX for binary name

kernel/binary_manager: change NAME_MAX to BIN_NAME_MAX for binary name

---

os/arch/arm/include/armv8-m/irq_cmnvector.h
os/arch/arm/include/armv8-m/irq_lazyfpu.h
os/arch/arm/src/armv8-m/up_blocktask.c
os/arch/arm/src/armv8-m/up_exception.S
os/arch/arm/src/armv8-m/up_initialstate.c
os/arch/arm/src/armv8-m/up_lazyexception.S
os/arch/arm/src/armv8-m/up_releasepending.c
os/arch/arm/src/armv8-m/up_reprioritizertr.c
os/arch/arm/src/armv8-m/up_schedyield.c
os/arch/arm/src/armv8-m/up_svcall.c
os/arch/arm/src/armv8-m/up_unblocktask.c
os/arch/arm/src/armv8-m/up_unblocktask_withoutsavereg.c

This patch >
1) Removes existing register based stack protection.
2) Adds NuttX based stack protection.

Backport NuttX register based stack overflow protection 

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c

MPU region 0 usage depends on some conditions in code. Sometimes it is not used,
but the region number is allocated for it. So region 0 goes waste. So, we move
the region number allocation into the if condition.
Also, we were using a hardcoded value of 1 for mpu_set_nregion_board_specific().
If rtk uses more than 1 region, then this will result in overwriting the board
specific region by the app region. So, we modify the hardcoded value and instead
use the current region number setting from the rtk board for reserving the board
mpu regions.

os/board/rtl8721csm :  Fix MPU setting error in rtk board

---

apps/examples/wifi_manager_sample/wm_test_on_off.c

examples/wifi_manager_sample: fix typo

---

docs/MPURegionsUsageGuide.md

This patch updates the MPU guide to accomodate the steps to add a
new MPU region and reserve MPU regions for board specific purpose.

docs: Update MPU Region Usage guide

---

os/drivers/otp/otpnull.c
os/include/tinyara/otp.h

- use int value instead of the pointer of int.

drivers/otp: modify otr_read interface

---

os/net/lwip/configs/netdb/Kconfig

network/lwIP: add DNS configurations

---

tools/nxfuse/src/tinyara_services.c

- Fix - conversion of signed integer to bigger unsigned integer.

tools/nxfuse/src: Fix svace issues - conversion of signed integer to bigger unsigned integer.

---

os/include/tinyara/net/if/wifi.h

Add WP3 missing enmum
Signed-off-by: fengyunlai <1063072208@qq.com>

include/tinyara/net/if: add missing WPA3 type enum member for PR4597

---

build/configs/rtl8721csm/rtl8721csm_download.sh

- Remove duplicated write operation for kernel partitions
- Unify download functions for specific partition
- Remove hard-coded and clean codes

rtl8721csm: Improve download script

---

os/fs/smartfs/smartfs_utils.c

Change log level to verbose about freeing node, and change to error regarding invalidate entry

fs/smartfs : adjust log level regarding sector recovery

---

os/arch/Kconfig

Fix typo : accomodate -> accommodate

arch/Kconfig : Fix typo

---

os/arch/arm/src/amebad/amebad_enet.c
os/arch/arm/src/amebad/amebad_flash.c
os/arch/arm/src/amebad/amebad_irq.c
os/arch/arm/src/amebad/amebad_lowerhalf.c
os/arch/arm/src/amebad/amebad_timerisr.c
os/board/rtl8721csm/src/component/os/os_dep/include/osdep_service.h
os/board/rtl8721csm/src/component/os/tizenrt/ethernetif_tizenrt.c
os/board/rtl8721csm/src/component/os/tizenrt/lwip_intf_tizenrt.c
os/board/rtl8721csm/src/component/os/tizenrt/lwip_intf_tizenrt.h
os/board/rtl8721csm/src/component/os/tizenrt/tizenrt_service.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_common/rtl8721d_ipc_api.c

Fix more warnings like incompatible type, unused variable, unintialized variable.

arch/arm/src/amebad/: Fix more warnings.

---

apps/shell/tash_command.c

1) If the last character in buff is '!', it will be handled as character, not history command.
2) If there is no number after '!' and '!' is not the last, returns ERROR.

shell/tash_command : Handle '!' cases in tash

---

os/kernel/debug/memdbg.c

Add debug message for heap settings to verify all heaps and regions are set well.

kernel/debug: Add debug message for heap settings

---

loadable_apps/loadable_sample/wifiapp/binary_update.c

Run update aging test with Micom or Wifi binary randomly.

loadable_apps/binary_update: Run update aging test with random binary

---

os/arch/arm/src/amebad/amebad_serial.c

Add function LOGUART_PutChar_RAM

arch/arm/src/amebad: Fix the 'extra CR after LF' issue

---

apps/examples/wifi_manager_sample/wm_test_stress_test1.c
apps/examples/wifi_manager_sample/wm_test_stress_test2.c

network/app: fix wifi stress test

---

build/configs/rtl8721csm/loadable_apps/defconfig
os/board/common/partitions.c
os/include/tinyara/binary_manager.h
os/kernel/binary_manager/Kconfig
os/kernel/binary_manager/Make.defs
os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_binfile.c
os/kernel/binary_manager/binary_manager_data.c
os/kernel/binary_manager/binary_manager_getinfo.c
os/kernel/pthread/pthread_create.c
os/kernel/task/task_create.c
os/kernel/task/task_exithook.c

- Manage kernel data for kernel binary update
. version, index in use, partition size, num, count
- Support getinfo functions to get kernel data
. partitions_get_kcount
. partitions_get_kversion
. partitions_get_download_kinfo

board/common: Manage kernel data for kernel binary update

---

apps/examples/security_test/seclink/sl_test_utils.c

Fix build failure on seclink test case.

apps/examples: Fix build failure with tc configuration

---

os/mm/mm_heap/mm_mallinfo.c

Heap corruption can occur when data of one node overflows to the next node.
In order to detect heap corruption, we added some debug logic in mallinfo api.
We check the current node "preceding" size with previous node size. If it is
not a match, then previous node is corrupted. We print debug information about
the corrupted node and trigger an assert failure.

os/mm: Add debug logic to find out heap corruption

---

apps/examples/testcase/le_tc/network/Kconfig
os/drivers/kernel_test/Make.defs

- this commit fix the build error of commit 057dec00ab9911dbcbf43379e11fc923ab31d056
Signed-off-by: Deepak sharma <deepak.sh@samsung.com>

fix build error

---

external/include/mbedtls/alt/common.h
external/mbedtls/alt/ecdh_alt.c
external/mbedtls/alt/pk_wrap_alt.c

- apply SECLINK changes in mbedtls alt

external/mbedtls: apply SECLINK changes in mbedtls alt

---

os/mm/mm_heap/mm_check_heap_corruption.c

Assertion failure occurs when we try to aquire heap semaphore
in mm_check_heap_corruption. So, we add a check for whether we
are in irq mode, and try to aquire semaphore only when we are
not in irq mode.

os/mm/mm_heap: Fix assertion fail during mm_check_heap_corruption

---

os/drivers/wireless/Make.defs
os/drivers/wireless/bluetooth/Make.defs
os/drivers/wireless/scsc/Make.defs

Modify make.defs to remove dependency

drivers/wireless: modify make.defs

---

os/mm/mm_heap/mm_check_heap_corruption.c

When we check for heap corruption, we are printing pid of the owner
task for the corrupted node. Additionally, we will now print the
name of the owner task. If the task has already exited, then we
print "Exited Task" as the name.

os/mm: Add task name in heap corruption details

---

apps/shell/Kconfig
apps/shell/Makefile
apps/shell/tash_internal.h
apps/shell/tash_main.c
apps/shell/tash_security.c

Secured tash can be accessed through password.

apps/shell/tash : Add secured tash

---

build/configs/rtl8721csm/rtl8721csm_download.sh

"make download OTA" or "make download ota" can download the kernel ota image to the kernel second partition.

build/configs/rtl8721csm_download.sh : Add Kernel OTA region download

---

.gitignore
os/board/rtl8721csm/src/Makefile

change include path for ble rtl8721 : `da_include/ble`, `da_include/da_core`

[Changed] change ble include rtl8721

---

os/fs/driver/mtd/smart.c

Currently, journaling uses bytewrite operation.
But not all architecture support bytewrite, so add this.

fs/smartfs : Add block write function for journaling

---

build/configs/rtl8721csm/.flashSpec.xml

Add options to .flashspec.xml to flash a binary to specific partition in dbuild

configs/rtl8721csm : Support flash a binary to specific partition in dbuild

---

os/board/common/Kconfig

os/board/common/Kconfig : Fix typo

---

apps/examples/testcase/le_tc/filesystem/Kconfig
apps/examples/testcase/le_tc/filesystem/fs_main.c
apps/examples/testcase/le_tc/filesystem/itc_fs.c
apps/examples/testcase/le_tc/filesystem/tc_fs_mops.c
apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
os/board/common/common.h
os/board/common/partitions.c
os/drivers/os_api_test/filesystem/Make.defs
os/drivers/os_api_test/filesystem/test_filesystem.c
os/drivers/os_api_test/os_api_test_drv.c
os/drivers/os_api_test/os_api_test_proto.h
os/include/tinyara/os_api_test_drv.h

In commit bca7c3826e60e, mountpoint is calculcated automatically. So we don't need to define every board's mountpoint.

apps/testcase/filesystem : Add auto calculation of mount devname

---

apps/system/flash_test/flash_test.c

Add description of read address to usage to avoid user confusion.

apps/system/flash_test : Add description to usage

---

os/net/lwip/src/api/sockets.c

WID:10916217 Return value of a function 'get_socket' is dereferenced at sockets.c:585 without checking, but it is usually checked for this function (23/24).

net/lwip/sockets.c : Add Null checking for get_socket

---

os/arch/arm/src/amebad/Kconfig
os/board/rtl8721csm/src/Makefile
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_central/ble_tizenrt_da_client.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_app_task.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_da_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_service.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/Make.defs
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_da_combo.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app_flags.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app_main.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app_task.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app_task.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_link_mgr.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_link_mgr.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/user_cmd.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/user_cmd.h

- Add support for ble scatternent
- Change Makefile include path for submodule
- Modify details of parse_service_table() api
- Add rtw_ble_server_set_adv_interval() api

board/rtl8721csm/bluetooth: Add support for BLE scatternent

---

os/fs/driver/mtd/smart.c

- Update comments and function descriptions in Journaling code part
for better understandability and readability.

os/fs/driver/mtd: Update comments and descriptions for Journaling

---

os/fs/driver/mtd/smart.c

fs/mtd: fix typo, succesfully -> successfully

---

apps/shell/tash_security.c

1. add CONFIG_TASH_PASSWORD_SHA256 length check
It should be 32 bytes.
2. covert CONFIG_TASH_PASSWORD_SHA256 char to hex once
It should be converted to SHA256 hex value to compare input password.
But it's fixed value so that we can convert it one time.
And this commit removes unnecessary string copy.
2 times (sprintf, strncpy) -> 1 time (strncpy)
3. use some definitions for readability
SHA256_HASH_nCHAR : number of SHA256 hash character to verify the config
SHA256_HASH_nBYTE : size of SHA256 data to set array
CONVERT_nCHAR : number of character to convert char to hex at once
4. reduce local variables size
212 bytes -> 98 bytes

shell: tidyup secured TASH

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/board/common/os/tizenrt/osif_tizenrt.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/board/common/src/hci_adapter.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/board/common/src/hci_process.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_da_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app_main.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app_task.c

Fix abort when CONFIG_DEBUG & CONFIG_DEBUG_ERROR on

board/rtl8721csm/bluetooth: Fix abort when CONFIG_DEBUG & CONFIG_DEBUG_ERROR on

---

tools/dump_tool/ramdumpParser.py

Based on #4876, update _stext & _etext to _stext_flash & _etext_flash
Also add _stext_ram & _etext_ram checks to existing code.

tools/dump_tool/ramdumpParser.py: Update _stext and _etext variables and related code

---

apps/examples/testcase/le_tc/compression/compression_tc_main.c

- fix build error for artik053/tc

testcase/compression: fix build error

---

build/configs/rtl8721csm/hello/Make.defs
build/configs/rtl8721csm/hello/defconfig
build/configs/rtl8721csm/loadable_apps/Make.defs
build/configs/rtl8721csm/loadable_apps/defconfig
build/configs/rtl8721csm/nettest/Make.defs
build/configs/rtl8721csm/nettest/defconfig
build/configs/rtl8721csm/rdp/Make.defs
build/configs/rtl8721csm/rdp/defconfig
build/configs/rtl8721csm/rtl8721csm_download.sh
build/configs/rtl8721csm/security_hal_test_tz/Make.defs
build/configs/rtl8721csm/security_hal_test_tz/defconfig
build/configs/rtl8721csm/tc/Make.defs
build/configs/rtl8721csm/tc/defconfig
build/configs/rtl8721csm/tls_test/Make.defs
build/configs/rtl8721csm/tls_test/defconfig
os/Makefile.unix
os/tools/mkbootparam.py

- os/tools: Support boot parameters for kernel
- build/configs/rtl8721csm: Set partition for boot parameters and Define MAKE_BOOTPARAM

Support boot parameters for kernel

---

os/drivers/lwnl/lwnl.c
os/fs/vfs/fs_select.c

drivers/lwnl: fix lwnl return type

---

build/configs/rtl8721csm/rtl8721csm_download.sh
os/tools/mkbootparam.py

Add checksum and size of boot parameters to verify data integrity.

tools/mkbootparam : Add checksum and size to boot param

---

os/dbuild.sh
os/tools/version.sh

1. dbuild.sh: sync host time for build time 
2. os/tools/version: add %Z format at date command

dbuild: sync build time to host machine time

---

framework/src/wifi_manager/wifi_manager_msghandler.c
os/drivers/wireless/virtual/vdev.c
os/net/net_initialize_netmgr.c

vwifi was initialized a user space. So it caused build fail if
loadable configuration was set. Therefore change the location of
initialization of vwifi device.

network/wi-fi: move vwifi initialization

---

apps/examples/testcase/le_tc/kernel/tc_pthread.c

- add new TC to test pthread_mutex_consistent()

testcase/kernel/pthread: add pthread_mutex_consistent TC

---

build/configs/common_download.sh

./dbuild.sh ERASE ALL will erase whole partitions even userfs

build/configs/common_download.sh : Change ERASE ALL to erase userfs also

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_da_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_da_combo.c

board/rtl8721csm/bluetooth:Fix server flag not set exactly

board/rtl8721csm/bluetooth:Fix server flag not set exactly

---

.travis.yml

- add temporary travis account for pull limits

travis: add temporary travis account

---

os/fs/driver/mtd/mtd_jedec.c

Add new jedec Common Flash Interface to support XMC

mtd/jedec : Add new flash interface of XMC

---

os/kernel/binary_manager/binary_manager.c

It is difficult for user to debug it with an assert when kernel or user binary is not found.
So print error messages instead of assert to let the user know why.
- Logs on failure:
binary_manager: =============== !!ERROR!! ==============
binary_manager: ERROR!! Not found valid user binaries.
binary_manager: Please check user binary and smartfs configurations.
binary_manager: ERROR!! Not found kernel partitions.
binary_manager: Please check kernel partition configurations.
binary_manager: Enable CONFIG_DEBUG_BINMGR_ERROR if you want to see the logs for failures.

kernel/binary_manager: print error messages instead of assert when kernel or user binary is not found

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c

Added API to set maximum connection to one in Soft AP mode

os/board/rtl8721csm : Limit maximum connection to 1 in Soft AP mode

---

os/tools/check_output_size.py

For finding kernel binary name, using board_metadata.txt.
Because each board has a different kernel binary name.

tools/check_output_size.py : Modify to use board_metadata.txt

---

os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c

add return value in cmd_wifi_off

wifi/driver: add return value in cmd_wifi_off

---

README.md

Remove white-space in README.md

Remove white-space in README.md

---

os/dbuild.sh
os/tools/build_test.sh

Support build test with dbuild to allow users to check build errors before pushing commits

dbuild: Support build test with dbuild

---

apps/examples/wifi_manager_sample/wm_test.c
external/dhcpd/dhcpd.c
external/netutils/netlib_getifaddrs.c
framework/include/wifi_manager/wifi_manager.h
framework/src/wifi_manager/wifi_manager_api.c
framework/src/wifi_manager/wifi_manager_event.c
framework/src/wifi_manager/wifi_manager_event.h
framework/src/wifi_manager/wifi_manager_lwnl.c
framework/src/wifi_manager/wifi_manager_message.c
framework/src/wifi_manager/wifi_manager_state.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c
os/drivers/wireless/realtek/wifi_util_interface/rtk_drv.c
os/drivers/wireless/scsc/slsi_drv_netmgr.c
os/drivers/wireless/virtual/vdev.c
os/drivers/wireless/virtual/vdev_handler.c
os/drivers/wireless/virtual/vdev_handler.h
os/drivers/wireless/virtual/vdev_handler_auto.c
os/drivers/wireless/virtual/vdev_handler_onoff.c
os/drivers/wireless/virtual/vdev_packet.c
os/drivers/wireless/virtual/vdev_scan_info.c
os/include/tinyara/lwnl/lwnl.h
os/include/tinyara/net/if/wifi.h
os/include/tinyara/wifi/wifi_common.h
os/include/tinyara/wifi/wifi_utils.h
os/net/netmgr/netdev_lwnl.c
os/net/netmgr/netdev_mgr_internal.c
os/net/netmgr/netdev_wifi.c

get wi-fi driver statistics information by wifi_manager_get_stats()

network/wifi: add getting statistics info from a wi-fi driver

---

external/dhcpd/dhcpd_lwip.c

refactoring dhcps message queue

external/dhcps: refactoring dhcps message queue

---

external/dhcpd/dhcpd_lwip.c

add log to dhcps event handler

external/dhcps: add log to dhcps event handler

---

apps/system/utils/utils_date.c
apps/system/utils/utils_tzselect.c
lib/libc/time/lib_strftime.c

Add timezone information in date command like below.
Dec 06 00:00:01 2011 Tue UTC

apps/system/utils_date.c : Add timezone information in date command.

---

lib/libc/time/lib_strftime.c

- Add #include <string.h> for strlen
- Add #include <stdlib.h> for getenv

lib/libc: Add missing header include for localtime

---

os/arch/arm/src/armv7-m/up_reprioritizertr.c
os/arch/arm/src/armv8-m/up_reprioritizertr.c

Fix minor typo in up_reprioriwtizertr.c
Signed-off-by: sangamanatha <sangam.swami@samsung.com>

arch/arm/src: fix typo

---

apps/examples/testcase/le_tc/kernel/tc_task.c

[Code Coverage] This patch adds few more TC's to task test cases.

apps/examples/testcase/le_tc/kernel: Add more task test cases 

---

apps/examples/testcase/le_tc/kernel/Kconfig
apps/examples/testcase/le_tc/kernel/Make.defs
apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
apps/examples/testcase/le_tc/kernel/tc_internal.h
apps/examples/testcase/le_tc/kernel/tc_irq.c

- add new IRQ TC to test fin_wait().

apps/testcase/kernel: add new IRQ TC

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_central/ble_tizenrt_central_client_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_central/ble_tizenrt_da_client.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_peripheral/ble_tizenrt_da_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_da_combo.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/da_ble_scatternet/ble_tizenrt_scatternet_app.h

Fix some memory leak problems in ble example.

board/rtl8721csm/bluetooth: Fix ble example memory leak

---

apps/examples/rtc/.gitignore
apps/examples/rtc/Kconfig
apps/examples/rtc/Kconfig_ENTRY
apps/examples/rtc/Make.defs
apps/examples/rtc/Makefile
apps/examples/rtc/rtc_main.c

This example runs forever with printing the log on every 5mins.
With this log, we can check the time difference which rtc runs well or not.

apps/examples/rtc : Add rtc accuracy test example

---

external/netutils/netlib_getifaddrs.c
os/drivers/lwnl/lwnl.c
os/drivers/wireless/virtual/vdev_ops_handler.c
os/include/tinyara/lwnl/lwnl.h
os/net/netmgr/netdev_lwnl.c

network/lwnl: modify lwnl handler

---

os/arch/boardctl.c

Board Reboot is important event, so it is better to remain the log.
Signed-off-by: jeongchanKim <initialkjc@gmail.com>

arch/boardctl.c : Add reboot debug message

---

os/drivers/wireless/realtek/wifi_util_interface/rtk_drv.c

os/driver/wireless/realtek: fix imxrt1020 build error

---

os/drivers/wireless/scsc/slsi_drv_netmgr.c

driver/wireless/scsc: fix mis typo

---

os/arch/arm/src/amebad/amebad_serial.c
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/serial_api.c

This commit updates serial_init process and removes the redundant code.

arch/arm/src/amebad: Update serial_api

---

lib/libc/queue/dq_addfirst.c

lib/libc/queue/dq_addfirst : Fix typo

---

apps/examples/lwnl_sample/lwnl_sample.c
framework/src/wifi_manager/wifi_manager_lwnl_listener.c

- remove unused data in lwnl socket.
- fix lwnl_sample bug

framework/wifi_manager: remove unused data in lwnl socket

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c

Do not start adv after set adv parameters

board/rtl8721csm/bluetooth: Do not start adv after set adv parameters

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

Fix wrong callback when connect fail

board/rtl8721csm/bluetooth: Fix wrong callback when connect fail

---

framework/src/ble_manager/ble_manager_lwnl_listener.c
framework/src/ble_manager/ble_manager_message.c
framework/src/wifi_manager/wifi_manager_lwnl_listener.c
framework/src/wifi_manager/wifi_manager_message.c
os/drivers/lwnl/lwnl.c

os/driver/lwnl: fix lwnl build error

---

framework/include/ble_manager/ble_client.h
framework/include/ble_manager/ble_manager.h

framework/ble_manager: fix typo

---

apps/system/init/init.c
external/include/stress_tool/st_perf.h
os/net/net_initialize.c
os/net/net_initialize_netmgr.c

move wi-fi initialization to net_initialize

network/wifi: move wi-fi initialization

---

apps/system/init/init.c
os/net/net_initialize.c
os/net/net_initialize_netmgr.c

network: fix build error

---

.circleci/config.yml

Separate build jobs to show each build result in PR check list

CircleCI: Separate build jobs for readability

---

os/arch/arm/src/amebad/amebad_enet.c

- fix build error in BLE dev register

os/amebad_ent: fix build error

---

os/include/tinyara/reboot_reason.h

[Reboot Reason Code]
System : 0 ~ 29,
Network : 30 ~ 59,
Common Service : 60 ~ 89,
App : 90 ~ 254

include/tinyara/reboot_reason : Rearrange the reboot reason codes

---

os/arch/arm/src/amebad/amebad_reboot_reason.c
os/include/tinyara/reboot_reason.h

os/arch/arm/src/amebad: Add all RTK reboot reason

---

os/arch/arm/src/amebad/amebad_reboot_reason.c
os/arch/arm/src/amebad/amebad_reboot_reason.h
os/include/tinyara/reboot_reason.h

/* [Reboot Reason Code]
* System : 50 ~ 79,
* Network : 80 ~ 109,
* Common Service : 110 ~ 139,
* App : 140 ~ 254
*/

include/tinyara/reboot_reason.h : Adjust reboot reason start code

---

apps/examples/lwnl_sample/lwnl_sample.c
external/iotivity/iotivity_1.2-rel/resource/csdk/connectivity/src/ip_adapter/caipserver.c
framework/src/ble_manager/ble_manager_message.c
framework/src/wifi_manager/wifi_manager_lwnl_listener.c
framework/src/wifi_manager/wifi_manager_message.c
os/drivers/lwnl/lwnl.c
os/drivers/lwnl/lwnl_evt_queue.c
os/drivers/lwnl/lwnl_evt_queue.h
os/drivers/lwnl/lwnl_log.h
os/include/tinyara/lwnl/lwnl.h
os/net/netmgr/netstack_lwnl.c

network/lwnl: fix lwnl event

---

framework/src/ble_manager/ble_manager_lwnl_listener.c
framework/src/wifi_manager/wifi_manager_lwnl_listener.c

- apply lwnl BLE & WiFi addr binding feature.

drivers/lwnl: apply lwnl bind feature.

---

apps/examples/wifi_manager_sample/wm_test_stress_test4.c
framework/src/wifi_manager/wifi_manager_cb.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c
os/drivers/wireless/scsc/slsi_drv_netmgr.c
os/drivers/wireless/virtual/vdev_ops_handler.c
os/net/net_initialize_netmgr.c
os/net/netmgr/netdev_wifi.c

add event handler task not to driver create new thread if wi-fi event occurs.

network/netmgr: add event handler task

---

apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifimanager_main.c
apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifimanager_main.c
apps/examples/wifi_manager_sample/wm_test.c
apps/examples/wifi_manager_sample/wm_test.h
apps/examples/wifi_manager_sample/wm_test_stress_test1.c
apps/examples/wifi_manager_sample/wm_test_stress_test2.c
apps/examples/wifi_manager_sample/wm_test_stress_test3.c
apps/examples/wifi_manager_sample/wm_test_stress_test4.c
apps/examples/wifi_manager_sample/wm_test_usage.h
framework/include/wifi_manager/wifi_manager.h
framework/src/st_things/things_stack/utils/things_network.c
framework/src/wifi_manager/wifi_manager_api.c
framework/src/wifi_manager/wifi_manager_state.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c
os/drivers/lwnl/lwnl.c
os/drivers/lwnl/lwnl_ioctl.c
os/drivers/wireless/realtek/wifi_util_interface/rtk_drv.c
os/drivers/wireless/scsc/slsi_drv_lwnl.c
os/drivers/wireless/scsc/slsi_drv_netmgr.c
os/drivers/wireless/virtual/vdev.c
os/drivers/wireless/virtual/vdev_ops_handler.c
os/include/tinyara/net/if/wifi.h
os/net/netmgr/netdev_wifi.c

network/wifi: add single scan channel

---

apps/system/utils/fscmd.c
os/fs/driver/mtd/smart.c
os/include/tinyara/fs/ioctl.h

Add format feature and tash command
Format works only with blockdriver which is registered for smartfs

file : Add format functionality for both of internal & external

---

apps/examples/wifi_manager_sample/wm_test.c
apps/examples/wifi_manager_sample/wm_test_table.h

add scan and join performance tool

apps/wm_test: add scan and join performance tool

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_client.c

Check active conn before read/write/notify

board/rtl8721csm/bluetooth: Check active conn before read/write/notify

---

os/fs/smartfs/smartfs_smart.c

[Improve SmartFs Overwrite Method] These changes reduce the overhead in overwriting consecutive chunks of data of a file.
The case of appending data to the file is not affected as it is handled by a separate part of code, the modified code only deals with overwriting to the files.
- Hold the buffer from being committed to flash if the buffer is not completely full.
- The buffer will get synced when the file is closed or if another write request is
issued which fills up the left over space in the buffer.
Signed-off-by: Taejun Kwon <tj80.kwon@samsung.com>, Amogh Hassija <a.hassija@samsung.com>

[Under Powercut Testing] os/fs/smartfs : Add buffering of data to be written to smartfs file

---

os/tools/version.sh

Commit hash is very long, so cut it as 7 strings.

tools/version.sh : Cut the commit hash as 7 strings

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

Fix send callback msg no return value

board/rtl8721csm/bluetooth: Fix send callback msg no return value

---

apps/include/system/utils.h
apps/system/utils/Kconfig
apps/system/utils/Makefile
apps/system/utils/systemcmd.c
apps/system/utils/utils_prodconfig.c
os/board/rtl8721csm/src/rtl8721csm_boot.c
os/drivers/Kconfig
os/drivers/Makefile
os/drivers/prodconfig/Make.defs
os/drivers/prodconfig/prodconfig.c
os/include/tinyara/prodconfig.h
os/kernel/init/os_bringup.c

TASH>>prodconfig
HW Debug : On
Download : Downloader & Hotfix Available

Support prodconfig

---

os/board/artik05x/src/artik05x_boot.c
os/board/esp32_devkit/src/esp32_boot.c
os/board/imxrt1020-evk/src/imxrt_boot.c
os/board/imxrt1050-evk/src/imxrt_boot.c
os/board/lm3s6965-ek/src/up_boot.c
os/board/stm32f407-disc1/src/stm32_boot.c
os/board/stm32f429i-disco/src/stm32_boot.c
os/board/stm32l4r9ai-disco/src/stm32_boot.c

Applied boards : artik05x, esp32_devkit, imxrt1020/1050, lm3s6965, stm32f407/429/l4r9ai

board : Apply prodconfig to every boards

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

Remove delete bond when disconnected

board/rtl8721csm/bluetooth: Remove delete bond when disconnected

---

framework/include/ble_manager/ble_client.h
os/include/tinyara/net/if/ble.h

- add BLE connect timeout param

framework/ble_manager: add BLE connect timeout param

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_app_main.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app_main.c

board/rtl8721csm/bluetooth: Add set adv type api

---

apps/examples/testcase/ta_tc/systemio/itc/itc_uart.c
framework/include/iotbus/iotbus_uart.h
framework/src/iotbus/iotbus_uart.c
os/arch/arm/src/amebad/amebad_serial.c
os/board/rtl8721csm/src/component/common/mbed/hal/serial_api.h
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/serial_api.c
os/include/tinyara/serial/tioctl.h

commit 1: changes in iotbus to add loopback mode in UART.
commit 2: add loopback mode in UART.
commit 3: refactor the ITC UART TCs

app/examples/testcase/systemio/itc: fix the UART Read/write TCs

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_link_mgr.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_client.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_combo.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_link_mgr.h

Fix 'rtw_ble_client_connect' becomes invalid after failing 3 times issue

board/rtl8721csm/src/component/common/bluetooth/realtek/: Fix 'rtw_ble_client_connect' becomes invalid after failing 3 times issue

---

os/dbuild.sh

modify .bininfo path to absolute path

os: modify .bininfo path to absolute path

---

os/fs/smartfs/smartfs_smart.c

- Do not truncate an already existing file to 0 if O_CREAT flag is included for opening.
- Truncate the file if O_TRUNC flag is included and O_APPEND is not.

os/fs/smartfs: Fix truncate discrepancy during file opening in SmartFs

---

framework/include/ble_manager/ble_client.h
os/include/tinyara/net/if/ble.h

framework/ble_manager: add ble mac filter param

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_ble_utils.h
os/board/rtl8721csm/src/component/os/tizenrt/rtk_blemgr.c

framework/ble_manager: add set_adv_type API in BLE

---

framework/include/ble_manager/ble_client.h
os/board/rtl8721csm/src/component/os/tizenrt/rtk_blemgr.c
os/include/tinyara/net/if/ble.h

- add ble_addr param in scan filter struct

framework/ble_manager: add ble_addr param in scan filter struct

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_client.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

Take in Scan Timeout as parameter and use it during BLE connect

os/board/rtl8721csm: Added Scan Timeout as BLE connect parameter

---

build/configs/rtl8721csm/rtl8721csm_download.sh

Add conditions for loadable apps about checking each binary exists

build/configs/rtl8721csm_download.sh : Add condition for loadable apps

---

framework/src/ble_manager/ble_manager_lwnl.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app_task.c

- fix ble_manager bug
- fix build error

framework/ble_manager: fix ble_manager bug

---

framework/include/ble_manager/ble_common.h
framework/src/ble_manager/ble_manager_state.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_client.c

- add default connect timeout value

framework/ble_manager: add default connect timeout value.

---

os/fs/driver/mtd/smart.c

Sync last 2 commits related to Filesystem improvements from RS6_Tp1x branch
Refer: [https://github.sec.samsung.net/RS6-RTOS/TizenRT_TP1x/pull/811](url) [https://github.sec.samsung.net/RS6-RTOS/TizenRT_TP1x/pull/752](url)

Sync FS changes from Tp1x branch

---

os/net/netmgr/Kconfig
os/net/netmgr/netstack_lwip.c

net/netmgr: add socket trace log

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.h
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_client.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app_task.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_ble_utils.h

- Added BT Whitelist modify feature.
- Added Scan Whitelist filter feature.

os/board/rtl8721csm: Add BT Whitelist Feature

---

external/iotivity/iotivity_1.2-rel/resource/csdk/connectivity/src/ip_adapter/tizenrt/caipnwmonitor.c

external/iotivity: sync iotivity code

---

docs/HowToDebugACrash.md

Update debug guidelines for all fault scenarios in the HowToDebugACrash.md file.

docs: Update debug guidelines for Fault scenarios

---

apps/examples/ble_rmc/ble_rmc_main.c
framework/include/ble_manager/ble_client.h
framework/src/ble_manager/ble_manager_autoconnect.c
framework/src/ble_manager/ble_manager_autoconnect.h
framework/src/ble_manager/ble_manager_common.h
framework/src/ble_manager/ble_manager_state.c

apps/ble_rmc: add ble multi pairing test

---

os/kernel/binary_manager/binary_manager_load.c

kernel/binary_manager_load.c : Print loaded binary path

---

os/include/tinyara/binfmt/compression/compression.h
os/tools/compression/src/compress.c
os/tools/mkbinheader.py

tools/compression/src: terminate build when compression fails

---

loadable_apps/loadable_sample/wifiapp/Kconfig

loadable_apps/wifiapp/Kconfig : Fix app1 to app2

---

os/include/tinyara/seclink_drv.h
os/include/tinyara/security_hal.h

security: fix seclink header

---

framework/src/ble_manager/ble_manager_lwnl.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c

framework/ble_manager: adjust BLE build warnings

---

external/include/protocols/webserver/http_server.h
external/webclient/webclient.c
external/webserver/http_client.c
external/webserver/http_client.h

Support of  Handling persitent connections in webserver, Supporting chunk transfer file in webserver,  Adding a new api for sending response message,  Fix null pointer exception for webserver,  Fix print format correctly

external/webserver Support of Webserver Handling persitent connections, chunk transfer

---

os/Kconfig.debug
os/include/debug.h

ble_manager/debug: add BLE debug config

---

external/include/stress_tool/st_perf.h
external/stress_tool/Makefile
external/stress_tool/st_perf.c
external/stress_tool/st_perf_print.c
external/stress_tool/st_perf_print.h

external/stress_tool: refactoring stress tool

---

framework/src/ble_manager/ble_manager_lwnl.c
framework/src/ble_manager/ble_manager_state.c

- fix BLE minor bug
- fix BLE build warnings

framework/ble_manager: fix BLE minor bug

---

framework/src/ble_manager/ble_manager_autoconnect.c

- check mq_receive return value

framework/ble_manager: fix minor bug in BLE manager

---

external/stress_tool/st_perf.c

external/stress_tool: remove unused variable

---

os/net/netmgr/netmgr_ioctl_lwip.c

fix logging value in lwip func ioctl

net/netmgr: fix logging value in lwip func ioctl

---

apps/examples/nettest/netlog_test.c
external/netutils/netlib_netlog.c
os/include/tinyara/net/netlog.h
os/net/net_initialize_netmgr.c
os/net/netmgr/net_vfs.c
os/net/netmgr/netdev_lwip.c
os/net/netmgr/netdev_lwnl.c
os/net/netmgr/netdev_mgr.c
os/net/netmgr/netdev_mgr_internal.c
os/net/netmgr/netdev_stats.c
os/net/netmgr/netdev_wifi.c
os/net/netmgr/netmgr_ioctl_igmp.c
os/net/netmgr/netmgr_ioctl_lwip.c
os/net/netmgr/netmgr_ioctl_netdev.c
os/net/netmgr/netstack.c
os/net/netmgr/netstack_lwip.c
os/net/netmgr/netstack_lwnl.c

add network log for user space.
-  test cases for user space log are added
-  implement netlog for user space
- seperate network to user space(eg. NET_LOG) and kernel space(NET_LOGK)

add network log for user space

---

external/dhcpd/Kconfig.protocol
os/net/lwip/src/core/ipv4/dhcps.c

add dns option 8.8.8.8 to dhcps

network/dns: add dns option to dhcps

---

apps/examples/security_test/seclink/sl_mbed_test.c

change ST_EXPECT_ASSERT to ST_ASSERT_EQ

security_test: change unchanged stress test macro

---

os/binfmt/binfmt_loadbinary.c
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_recovery.c

kernel/binary_manager: Support reloading optimization for common binary

kernel/binary_manager: Support reloading optimization for common binary

---

os/wqueue/wqueue.h

os/wqueue/wqueue.h : Delete duplicated prototype of get_usrwork

---

os/arch/arm/src/armv7-m/up_usagefault.c
os/arch/arm/src/armv8-m/up_usagefault.c

Fix typo : occured -> occurred

arch/armv7-m, v8-m/up_usagefault.c : Fix typo

---

os/net/netmgr/netdev_wifi.c

add wifi deinit in kernel space for binary manager to deinit wifi

net/netmgr: add wifi deinit in kernel space

---

tools/debug/debugsymbolviewer.py
tools/trap/HowToUseTrap.md
tools/trap/gui_ramdumpParser.py
tools/trap/ramdumpParser.py

Remove kernel symbols added twice.
Remove elf file argument to ramdumpParser.py
Add elf file extension parsing to ramdumpParser.py
Rectify HowToUseTrap.md log formatting.

tools: Refactor trap tool

---

external/webserver/http.c
external/webserver/http_client.c

This resolves the crash due to tcb and initialize the buffer

external/webserver: resolves the crash and init buf 

---

apps/examples/ble_rmc/ble_rmc_main.c
framework/src/ble_manager/ble_manager_state.c
os/drivers/bluetooth/Kconfig

- fix build warnings in BLE example
- fix BLE manager bug
- add default value in BT Kconfig

framework/ble_manager: fix BLE build warnings

---

os/net/lwip/sys/arch/sys_arch.c

sem_tickwait API was changed however lwIP didn't apply changed API.

net/lwip: fix sem_tickwait error handleing

---

external/dhcpc/dhcpc_lwip.c

external/dhcpc: remove unused code in dhcpc

---

apps/examples/ble_rmc/ble_rmc_main.c
framework/include/ble_manager/ble_client.h
framework/include/ble_manager/ble_scan.h
framework/src/ble_manager/Make.defs
framework/src/ble_manager/ble_manager_lwnl.c
framework/src/ble_manager/ble_manager_msghandler.h
framework/src/ble_manager/ble_manager_state.c
framework/src/ble_manager/ble_queue.c
framework/src/ble_manager/ble_queue.h
os/include/tinyara/ble/ble_manager.h
os/include/tinyara/net/if/ble.h
os/net/blemgr/bledev.c

- implement BLE priority queue.
- add ble_evt_handler

framework/ble_manager: implement BLE priority queue.

---

external/webserver/http_client.c

Support of Trailer header on webserver

external/webserver: Support of Trailer header on webserver

---

os/net/lwip/configs/tcp/Kconfig
os/net/lwip/src/include/lwip/lwipopts.h

net/lwip: support window scale option

---

external/mbedtls/alt/pk_wrap_alt.c

mbedtls: remove unused code

---

os/fs/smartfs/smartfs_smart.c

- The last sector chained to the file may be overwritten during sync at close time.
- In some cases, the proper sector header may not be present in sf->buffer for sync.
- Hence, read the next sector always after filling up current sector to maintain
proper contents in buffer.

os/fs/smartfs: Fix chaining issue in jSmartFs overwrite

---

os/drivers/memory/mminfo.c

It should search all kmmheaps if CONFIG_KMM_NHEAPS > 1 to show all heaps information in heapinfo.

driver/memory: Search all kmmheaps in heapinfo if CONFIG_KMM_NHEAPS > 1

---

external/include/stress_tool/st_perf.h

external/stress_tool: add assert_neq

---

os/fs/driver/mtd/smart.c
os/include/tinyara/fs/ioctl.h

It decided that apply this code to only product branch, but to prevent confusion
, Merge from product branch.

fs/smartfs : apply corruption feature

---

apps/examples/smartfs/fs_performance/Kconfig
apps/examples/smartfs/fs_performance/Kconfig_ENTRY
apps/examples/smartfs/fs_performance/Make.defs
apps/examples/smartfs/fs_performance/Makefile
apps/examples/smartfs/fs_performance/fs_performance_main.c

Filesystem Performance Test :
1. File Creation Test - Performance of creating a file in one go.
2. Overwrite Test - Performance of overwriting to a file from start of file.
3. Append Test - Performance of adding additional 64 kb data to existing file size
4. Read Test - Read Performance on different combination of file size and buffer size
5. GC effect - Performance of filesystem due to Garbage Collection
Usage:
Tash >> fs_performance [Timer dev. no] [Tc] [Filesize (bytes)] [Buffersize (bytes)]
e.g, Tash >> fs_performance 0 4 65536 1024
Read Test for max file size 64kb and buffer size as 1kb
Signed-off-by: dinesh.das <dinesh.das@samsung.com>

apps/examples/smartfs/fs_performance : Add Filesystem Performance Test

---

tools/debug/debugsymbolviewer.py

- Convert spaces to tabs
- Trim trailing spaces
- Remove unused variable

tools/TRAP: Fix debugsymbolviewer formatting

---

tools/trap/HowToUseTrap.md

This patch updates the md file as per the latest TRAP tool functioning
for kenel, app & common binary crashes.

tools/trap: Update the md file as per latest TRAP tool

---

os/tools/check_package.py

If there is a validation failure, return exit(1).

os/tools/check_package.py : Add sys.exit(1) for validation failure

---

os/drivers/seclink/seclink_drv.c
os/drivers/seclink/seclink_drv_utils.h

seclink: change log

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

Peer MAC address reported in trwifi_post_event()

os/board/rtl8721csm : Connected AP MAC address in connect_ap callback

---

os/mm/mm_heap/mm_check_heap_corruption.c

For stack allocation, the pid which is in mm_allocnode_s is pid * (-1) for distinguishing it is stack allocation or normal allocation.
If we print the pid with unsigned format, then the pid of stack allocated node looks very big number because of negative value.
So it is better to print the pid with signed format.

mm/mm_check_heap_corruption.c : Show pid with signed format

---

os/include/sched.h

os/include/sched.h : Fix typo

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_ota_ram.c

OTA_Image2SignatureCheck() is the Image2 (Kernel Image) signature verify API
Please pass in the Flash address of Image to verify, return 1 as Success.
Example of Flash address of Image 0x08082000, 0x08242000.

os/board/rtl8721csm: Add Image2 verify API

---

build/configs/rtl8721csm/loadable_apps/Make.defs
build/configs/rtl8721csm/rtl8721csm_make_bin.sh
build/configs/rtl8721csm/rtl8721csm_signing.sh
os/Kconfig
os/Makefile.unix
os/arch/arm/src/amebad/Make.defs
os/arch/arm/src/amebad/amebad_signature.c
os/board/common/partitions.c
os/include/tinyara/binary_manager.h
os/include/tinyara/signature.h
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_data.c
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_verify.c

- Support Loadable Image Verify API

kernel/binary_manager: Support binary signing

---

os/include/tinyara/security_hal.h

security: add ed25519 key type

---

tools/trap/ramdumpParser.py

Replace duplicated code with loop

tools/trap: Refactor TRAP tool

---

os/net/lwip/src/core/tcp.c

line 1817 : Calcluates -> Calculates
line 1818 : determin -> determine

Tcp.c : correct typo

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

Modified the scan implementation to support,  Full scan/Scan with SSID/Scan with channel/Scan SSID with specific channel

os/board/rtl8721csm : Support Single channel scan

---

apps/examples/testcase/le_tc/filesystem/fs_main.c
apps/examples/testcase/le_tc/filesystem/itc_fs.c
external/iotivity/iotivity_1.2-rel/resource/csdk/security/provisioning/unittest/pmutilitytest.cpp
external/protobuf/java/core/src/test/java/com/google/protobuf/LiteEqualsAndHashTest.java
external/protobuf/java/core/src/test/java/com/google/protobuf/LiteTest.java
external/protobuf/javanano/src/main/java/com/google/protobuf/nano/FieldData.java

corrected the typo about `different`.

catch correct typo

---

framework/src/wifi_manager/wifi_manager_api.c

framework/wifimanager: remove log related security

---

os/kernel/binary_manager/binary_manager_load.c

- Add a flag for BP recovery
- Set updated BP data in g_bp_info when BP data is updated
- Update version after header verification is done

kernel/binary_manager: Add missing BP recovery update and version update

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c

Some members have dependency of configs. So added the ifdef conditions.

arch/armv7,8-m, 7-r/*_assert.c : Add condition for tcb members

---

os/tools/build_test.sh

Add "rtl8721csm/hello" build test on build_test script
to verify modification in build

os/tools/build_test.sh: add rtl8721csm/hello in build test

---

os/wqueue/Makefile

This is a Makefile for workqueue, not memory manager.

os/wqueue/Makefile : Fix wrong description

---

apps/examples/smartfs/smartfs_powercut/smartfs_powercut_main.c

- The application recovers the primary file with the help of the backup file.
However, there is no method for recovery of the backup file.
- Completeness of the backup file is not checked during initialization which
can cause failure while recovering the primary file.
- Add a check for the size of the backup file during init and if found
incomplete, it should be re-created.

apps/examples/smartfs: Fix bug in smartfs_powercut app

---

apps/examples/webserver_test/Kconfig
apps/examples/webserver_test/Kconfig_ENTRY
apps/examples/webserver_test/Make.defs
apps/examples/webserver_test/Makefile
apps/examples/webserver_test/readme.md
apps/examples/webserver_test/results.md
apps/examples/webserver_test/webserver_test_main.c
apps/examples/webserver_test/webserver_test_tls.c
apps/examples/webserver_test/webserver_test_tls.h
apps/examples/webserver_test/webserver_test_util.c
apps/examples/webserver_test/webserver_test_util.h

1.  Added test app to test webserver
2.  Added testing guide
3.  Added results

apps/examples/webserver_test: Add webserver test application

---

os/mm/mm_heap/mm_heapinfo_parse_heap.c

mm/mm_heap: Fix typo

---

apps/examples/smartfs/buffer_optimization/buffer_optimization_main.c

- Append File Operation improvements are not guaranteed/indicated with the optimized buffer size.
- We keep read file operation improvement which is significant as a suggestion to the programmer.
- Modularity is retained considering the possible addition of any future improvement suggestions.

apps/examples/smartfs: Revert changes related to append file operation

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/board/common/os/tizenrt/osif_tizenrt.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_app_task.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app_task.c

Change msg receiver priority to be same as sender to prevent msg send fail in high load condition
Add prevention check for timer overflow

os/board/rtl8721csm: Fix BLE msg send fail issue

---

os/tools/mkbinheader.py

1. Fix wrong indentation at line 280 in mkbinheader.py
2. Fix wrong value of common binary version
It should be converted to integer value before value verification.
3. Modify debug messages to know what problem is Exactly

fixup! os/tools/*.py: Integrate common util functions

---

apps/examples/connect_test/Kconfig
apps/examples/connect_test/Kconfig_ENTRY
apps/examples/connect_test/Make.defs
apps/examples/connect_test/Makefile
apps/examples/connect_test/README.txt
apps/examples/connect_test/connect_test.c
apps/examples/connect_test/connect_test.h
apps/examples/connect_test/connect_test_auth_table.h
apps/examples/connect_test/connect_test_client.c
apps/examples/connect_test/connect_test_client_dtls.c
apps/examples/connect_test/connect_test_client_tls.c
apps/examples/connect_test/connect_test_crypto_table.h
apps/examples/connect_test/connect_test_data.h
apps/examples/connect_test/connect_test_guide.md
apps/examples/connect_test/connect_test_hostnames.c
apps/examples/connect_test/connect_test_log.h
apps/examples/connect_test/connect_test_server.c
apps/examples/connect_test/connect_test_server.h
apps/examples/connect_test/connect_test_server_dtls.c
apps/examples/connect_test/connect_test_server_tls.c
apps/examples/connect_test/connect_test_table.h
apps/examples/connect_test/connect_test_tcp.c
apps/examples/connect_test/connect_test_udp.c
apps/examples/connect_test/connect_test_usage.h
apps/examples/connect_test/connect_test_utils.c
apps/examples/connect_test/connect_test_utils.h

This TC simulates steps of Connect and Data Transfer Test which will help wi-fi vendor to find driver issues easily.
connect_test server - Simulating connect and data transfer process on Samsung DA device
connect_test client - Simulating connect and data transfer process on mobile SmartThings Application
Signed-off-by: Snehanshu Vivek <s1.vivek@samsung.com>

apps/examples/wifi_manager/wm_test: Implementation of stress test for Connect and Data Transfer Test

---

build/configs/rtl8721csm/rtl8721csm_make_bin.sh
os/Kconfig
os/include/tinyara/signature.h
os/kernel/binary_manager/Kconfig
os/kernel/binary_manager/binary_manager_data.c

Modify condition of version checking to allow same version binary update.

kernel/binary_manager: Allow same version binary update

---

docs/TroubleShooting.md

This commit adds how to resolve "arm-none-eabi-gcc: Command not found" error.

docs: add toolchain issue

---

external/webserver/http_client.c

This adds support for webserver to send the response body
larger than HTTP_CONF_MAX_REQUEST_LENGTH bytes

external/webserver: Add support of large body in response

---

os/arch/arm/src/amebad/amebad_enet.c
os/drivers/Makefile
os/drivers/bluetooth/virtual_ble/Kconfig
os/drivers/bluetooth/virtual_ble/Make.defs
os/drivers/bluetooth/virtual_ble/ble_vdev.c
os/drivers/bluetooth/virtual_ble/readme.md
os/drivers/bluetooth/virtual_ble/vble_handler.c
os/drivers/bluetooth/virtual_ble/vble_handler.h
os/net/net_initialize_netmgr.c

Signed-off-by: Hrishikesh Kashyap h1.kashyap@samsung.com
Features
1) Supports all the interfaces for BLE manager
2) Can trigger callbacks through IOCTL calls

os/drivers/bluetooth/virtual_ble: Add BLE mock driver

---

os/fs/driver/mtd/smart.c

- We do not need a CRC check for verification at read time if read back and verify happens at write time.
- In our focus area of jSmartFs (Journaling enabled), read back and verify always happens at write time,
which gives us the option to avoid this unnecessarily time taking overhead.

[UNDER POWERCUT TESTING] os/fs/driver/mtd: Remove additional CRC check of data read from flash

---

apps/examples/webserver/webserver_main.c
apps/examples/webserver_test/webserver_test_main.c
apps/examples/webserver_test/webserver_test_util.c
apps/examples/webserver_test/webserver_test_util.h

Add support to receive multiple body packet

app/webserver_test: Add support to receive multiple body packet

---

apps/examples/ble_perfs/Kconfig
apps/examples/ble_perfs/Make.defs
apps/examples/ble_perfs/Makefile
apps/examples/ble_perfs/README.txt
apps/examples/ble_perfs/ble_perfs_main.c

apps/ble_perfs: Implement BLE Server to measure the ble bandwidth

---

os/board/rtl8720e/src/component/wifi/wifi_interactive_mode.c

In loadable_apps config, cmd_wifi_on() cannot access netlib_setmacaddr(), so put a static _netlib_setmacaddr() inside wifi_interactive_mode.c to fix the compile error.

os/board/rtl8720e: fix setmacaddr compile error in loadable_apps config

---

external/webserver/http_client.c

external/webserver: Fix svace WGID 230304 webserver memory leak

---

external/webserver/http_client.c

external/webserver: Fix svace issues: WGID 230303 and 230308

---

build/configs/rtl8720e/rtl8720e_download.sh

configs/rtl8720e: fix download for loadable config

---

os/arch/arm/src/amebalite/Make.defs

Add wifi build rules for rtl8720e.

arch/arm/amebalite: Add wifi build rules

---

apps/examples/ble_rmc/ble_rmc_main.c
apps/examples/testcase/Kconfig
apps/examples/testcase/Makefile
apps/examples/testcase/ta_tc/ble_manager/itc/Kconfig
apps/examples/testcase/ta_tc/ble_manager/itc/Make.defs
apps/examples/testcase/ta_tc/ble_manager/itc/itc_blemanager_main.c
apps/examples/testcase/ta_tc/ble_manager/itc/readme.md
apps/examples/testcase/tc_main.c

Integration Test Cases (positive & negative) for the APIs of BLE manager
Signed-off-by: Hrishikesh Kashyap <h1.kashyap@samsung.com>

apps/examples/testcase/ta_tc: Add BLE manager ITC application

---

os/dbuild.sh

```
"9. ERASE SS"
"10. ERASE USERFS"
"11. ERASE ALL"
"u. USBrule"
"x. Exit"
==================================================
9
Warning, this will erase important data (Secure storage). Press 'y' or 'n' to continue : n
```
```
"10. ERASE USERFS"
"11. ERASE ALL"
"u. USBrule"
"x. Exit"
==================================================
10
Warning, this will erase important data (User data). Press 'y' or 'n' to continue : y
Port ttyUSB1 is selected
############################################
```

os: add conformation to erase userfs and secure storage

---

os/arch/arm/src/amebalite/amebalite_serial.c

Warns the user to use UART0/3 when flowcontrol is used.

os/arch/arm/src/amebalite: Add serial flowcontrol warnings

---

os/fs/driver/mtd/smart.c
os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c

- Fix spelling mistakes at a few places.
- Update comment indentation for better grammatical understanding.

os/fs: Fix spelling/grammatical mistakes

---

os/board/rtl8720e/src/component/wifi/api/wifi_conf_inic_ipc.c

Add association and disassociation handler event for SoftAP

board/rtl8720e/wifi : Add assoc and disassoc handler when starting SoftAP

---

apps/examples/uart_hw_test/Kconfig
apps/examples/uart_hw_test/Make.defs
apps/examples/uart_hw_test/Makefile
apps/examples/uart_hw_test/uart_hw_test.c
tools/uart_hw_test/README.md
tools/uart_hw_test/uart_test.c
tools/uart_hw_test/uart_test.sh

This tool can be used to perform the uart HW test.
The tool performs the following tests.
UART Tx byte gap time test
1. The target prints log on the console continuously
2. The target sends data on the selected uart
3. The ubuntu app checks tx packet gap using time api
UART Rx loss check test
1. The target prints log on the console continuously
2. The ubuntu app sends data on the selected uart
3. The target verify rx data for data loss
The above tests are performed for the following baud rates.
115200, 38400, 19200, 9600, 4800
Sample test result:
```
Enter UART port number : 1
Opened UART port : /dev/ttyUSB1
######################## UART Test Start #############################
######################################################################
Test Scenario 0: UART test only …
```

UART HW test tool

---

os/board/rtl8720e/src/component/bluetooth/os/tizenrt/osif_tizenrt.c
os/board/rtl8720e/src/component/bluetooth/rtk_stack/example/ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8720e/src/component/os/tizenrt/rtk_blemgr.c
os/board/rtl8720e/src/component/soc/amebalite/fwlib/ram_common/ameba_ipc_ram.c
os/board/rtl8720e/src/component/soc/amebalite/fwlib/ram_km4/ameba_ota_ram.c
os/board/rtl8720e/src/component/wifi/inic/inic_ipc_host_api.c
os/board/rtl8720e/src/component/wifi/inic/inic_ipc_host_trx.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/board/common/os/tizenrt/osif_tizenrt.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

Check whether returned value of sched_gettcb is NULL or not to avoid dereference.

os/board/rtl872X: Fix svace issues

---

external/webserver/http_client.c

external/webserver: Fix svace issues (45b7f5e, a7a4c8e)

Sync from master, 220725

---

os/board/rtl8720e/src/component/bluetooth/driver/hci/hci_transport/hci_h4.c
os/board/rtl8720e/src/component/bluetooth/rtk_stack/example/ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8720e/src/component/wifi/inic/inic_ipc_host_trx.c
os/board/rtl8720e/src/component/wifi/promisc/wifi_promisc_inic_ipc.c

Add NULL checking for memory dereference.

os/board/rtl8720e: Fix svace issues

---

apps/examples/webserver/webserver_main.c
external/include/protocols/webserver/http_server.h
external/webserver/http_client.c

http_send_response_chunk and http_send_response_helper are
refactored for body len

external/webserver Refactor send response and send chunk response

---

external/webserver/http_client.c

external/webserver: Change Error log to Debug log

---

os/dbuild.sh

- After chosing to Erase a partition, the user may wish to download/erase another one.
- After downloading a particular partition, the user may wish to download yet another one.
- This gives the user the option to continue working with docker after any download command completes.
- Also, changes the STATUS option from "DOWNLOAD" to "DOWNLOAD READY" to differentiate between the status and a script function.

os: Keep Docker script in the menu loop even after downloading

---

apps/examples/board_specific_demo/ameba_secure_world_demo/.gitignore
apps/examples/board_specific_demo/ameba_secure_world_demo/Kconfig
apps/examples/board_specific_demo/ameba_secure_world_demo/Kconfig_ENTRY
apps/examples/board_specific_demo/ameba_secure_world_demo/Make.defs
apps/examples/board_specific_demo/ameba_secure_world_demo/Makefile
apps/examples/board_specific_demo/ameba_secure_world_demo/README.txt
apps/examples/board_specific_demo/ameba_secure_world_demo/secure_world.c
os/board/rtl8720e/Kconfig

Signed-off-by: Tirtha Biswas <biswas.t@samsung.com>

board_specific_demo/ameba_secure_world_demo: Add secure_world example

---

os/board/rtl8720e/src/component/filesystem/ftl/ftl.c

- Added ftl write protection disable/enable to flash erase and write when flash is protected.

os/board/rtl/8720e: add FTL write protection disable/enable

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

- BLE server now disconnects based on the connection id

os/board/rtl8721csm: BLE server disconnection fix

---

os/dbuild.sh

1) Rename current docker options to:
======================================================
"1. Build with Current Configuration"
"2. Re-configure"
"3. Modify Current Configuration"
"4. Clean Build"
"5. Clean Build and Re-Configure"
"6. Build SmartFS Image"
"d. Download"
"t. Build Test"
"x. Exit"
======================================================
2) Fix typo in the script excute > execute
3) Fix typo in the script treate > treat

dbuild.sh: Refactor docker script

---

os/dutils.sh

os/dutils.sh: Implement method to run toolchain commands in docker
When user has not installed toolchain, but only using the docker container,
then there needs to be a method to run toolchain commands like nm, readelf,
addr2line for debugging purpose.
This commit adds a method to run these commands. The user can call dutils.sh
with new "tool" command, followed by the actual toolchain command to be run.
./dutils.sh tool nm build/output/bin/tinyara.axf
./dutils.sh tool addr2line -e build/output/bin/tinyara.axf 0x0123abcd
The toolchaing commands can also be run from the dutils menu as below:
./dutils.sh menu
======================================================
"Select Option"
======================================================
"1. Run Toolchain Command"
"x. Exit" …

Implement method to run toolchain commands in docker

---

README.md

README.md: Update build options as per latest dbuild script

---

os/include/tinyara/mm/mm.h
os/mm/Kconfig
os/mm/mm_heap/mm_check_heap_corruption.c
os/mm/mm_heap/mm_initialize.c

Some changes to improve the heap corruption check and provide better debug information.

Improved Heap corruption check 

---

apps/shell/tash_command.c

Considering ! as a character when it is inside quotation mark

apps/shell/tash_command.c: fix ! command issue

---

apps/shell/tash_main.c

```
TASH>>wm_test softap '@!123' '123123132' 1
TASH>>[WT][T18] wifi manager test!!     wm_test_main:947
[WT][T18] wait func signal      wm_test_main:958
[WT][T19] -->   _wt_softap_start:312
====================================
AP INFO
------------------------------------
SSID: @!123
channel: 1
====================================
[WM][INFO] --> wifi_manager_set_mode 136
[WM][INFO] handle request state(UNINITIALIZED) evt(CMD_SET_SOFTAP)
[WT][ERR][T19] Run SoftAP Fail  _wt_softap_start:331
[WT][T19] <--   _wt_softap_start:333
[WT][T19] send func signal      _wt_process:938
TASH>>
```

apps/shell/tash_main.c: fix single quotes problem in ! command issue

---

os/arch/arm/src/amebalite/amebalite_timerisr.c
os/board/rtl8720e/src/component/bluetooth/os/tizenrt/osif_tizenrt.c
os/board/rtl8720e/src/component/soc/amebalite/misc/ameba_wlan_init.c
os/board/rtl8720e/src/component/wifi/api/wifi_conf_inic_ipc.c

Other issues:
amebalite_timerisr.c - Revert define to extern variable due to incorrect value
osif_tizenrt.c - Fix missing variable

board/rtl8720e/src/component/: Fix_wifi_disconnect_hang_issue

---

os/arch/arm/src/amebad/amebad_reboot_reason.h

Add timer to check REG_TCR BIT_CRC(bit 8) every 1 min, if the value is wrong, set reboot reason code and do system reset

os/board/rtl8721csm: Add timer to check REG_TCR BIT_CRC(bit 8) every 1 min, if the value is wrong, set reboot reason code and do system reset

---

os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

Reinit channel set before start softap

os/board/rtl8721csm: fix softap start fail issue

---

apps/examples/lw_aifw_sine_test_app/lwaifw_sine_test_main.cpp

examples/lw_aifw_sine_test_app: Includes stdlib.h for free API

examples/lw_aifw_sine_test_app: Includes stdlib.h for free API

---

build/configs/rtl8720e/rtl8720e_download.sh

build/configs/rtl8720e/rtl8720e_download.sh: Changes from hard-coded pathname to generic name

---

framework/src/lw_aifw/AICSVArrayReader.cpp
framework/src/lw_aifw/AICSVDataSource.cpp
framework/src/lw_aifw/AICSVFileReader.cpp
framework/src/lw_aifw/AIServiceCore.cpp
framework/src/lw_aifw/include/AICSVArrayReader.h
framework/src/lw_aifw/include/AICSVFileReader.h
framework/src/lw_aifw/include/AICSVReader.h

framework/src/lw_aifw: Add files missed in previous commit: https://github.com/Samsung/TizenRT/commit/c340cfed5ef189f0114ee75291e841ea985d0479

src/lw_aifw: Add missing AIFW source files

---

framework/include/ble_manager/ble_manager.h

add a omitted api declaration to header file

[ble manager] add a omitted api declaration to header file

---

os/dbuild.sh
os/dutils.sh

docker image checking is done only build command.
so It adds CHECK_DOCKER_IMAGE function that check docker image and pull docker image. 
And apply in all command.
On the other hand, This commit is for support other docker repository. 
In CHECK_DOCKER_IMAGE function, It can add logic that for use other docker reposiotry image.

dbuild.sh, dutils.sh: add GET_SPECIFIC_DOCKER_IMAGE functiuon

---

os/mm/mm_heap/mm_manage_allocfail.c

There are printing many logs in heapinfo_parse_heap() 
So during print log, Its reboots from the watchdog used by wifi, etc.
Therefore, This commit add to disable watchdog in mm_manage_alloc_fail()
that only when CONFIG_DEBUG_MM_HEAPINFO is enabled.

mm/mm_heap: disable watchdog in mm_manage_alloc_fail function

---

os/fs/smartfs/README.txt

- Addition of a few lines of content
- Minor grammatical corrections

os/fs/smartfs: Update jSmartFS README with minor changes

---

os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

* Refree error is because the driver handles the first amsdu packet wrongly

os/board/rtl8721csm: fix amsdu packets refree error

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c
os/board/rtl8721csm/src/component/os/tizenrt/tizenrt_service.c
os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

add lock to prevent from accessing 0 address
add data length check to avoid hardfault
fix hardfault caused by timer task preempt wifi driver task

os/board/rtl8721csm : add fault prevention check

---

os/arch/arm/src/amebad/amebad_serial.c
os/board/rtl8721csm/src/component/common/mbed/hal/serial_api.h
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/serial_api.c

This commit changes time of serial pin initialize.

arch/amebad, board/rtl8721csm: set-up uart pins in up_serialinit

---

.circleci/config.yml

add rtl8730e/hello ci build test configuration

.circleci: add rtl8730e ci build test

---

apps/examples/testcase/ta_tc/preference/utc/utc_preference_main.c
framework/include/preference/preference.h
framework/src/preference/private_preference.c
framework/src/preference/shared_preference.c
os/include/tinyara/preference.h

########## Preference UTC End [PASS : 58, FAIL : 0] ##########
Added 8 new testcases for (shared/private, get/set preference)

Add support and test cases for binary data type preference

---

os/arch/arm/src/amebalite/amebalite_serial.c
os/arch/arm/src/amebasmart/amebasmart_serial.c
os/board/rtl8720e/src/component/mbed/hal/serial_api.h
os/board/rtl8720e/src/component/mbed/targets/hal/rtl8720e/serial_api.c
os/board/rtl8730e/src/component/mbed/hal/serial_api.h
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/serial_api.c

Uart setup initialise pins has been added similar to AmebaD
#5852

Set-up uart pins in up_serialinit for amebaSmart & amebaLite

---

os/board/rtl8730e/src/component/os/tizenrt/rtk_netmgr.c
os/board/rtl8730e/src/component/wifi/wifi_interactive_mode.c

- Add checks in rtk_netmgr to check if channel is a valid 2.4ghz/5ghz channel when scanning specific channel or starting softap

os/board/rtl8730e: Add checks for validity of specified wifi channels

---

tools/trap/ramdumpParser.py

This patch formats heap corruption logs as follows,
(Note : Must have following to run the code successfully
1. It is assumed that heap information prints parameters by comma seperation (as in this repo)
2. Binary start address and size are are print in crash log (as in this repo) )
eg: 
1. Heap corruption
```
dump_file                   : None
log_file                    : ../../temp
Number of binaries          : 3 [kernel + apps]
"kernel" elf_file           : ../../build/output/bin/tinyara.axf
"app1" elf_file             : ../../build/output/bin/app1_dbg
"app2" elf_file             : ../../build/output/bin/app2_dbg …
```

tools/trap/ramdumpParser.py : Formatted heap region information in trap tool

---

os/arch/arm/src/amebasmart/Make.defs
os/arch/arm/src/armv7-a/arm_blocktask.c
os/arch/arm/src/armv7-a/arm_releasepending.c
os/arch/arm/src/armv7-a/arm_reprioritizertr.c
os/arch/arm/src/armv7-a/arm_syscall.c
os/arch/arm/src/armv7-a/arm_unblocktask.c
os/arch/arm/src/common/up_restoretask.c
os/board/rtl8730e/src/rtl8730e_boot.c
os/include/tinyara/mpu.h

- Fix issues with common binary working
- Fix build issues with build for rtl8730e/loadable_apps

Update support for loadable_apps on RTL8730E

---

os/se/ameba/rtl_se_crypto_function.h
os/syscall/syscall_names.c
tools/uart_hw_test/README.md

- os/se/ameba/rtl_se_crypto_function.h : extention -> extension
- os/syscall/syscall_names.c : defintions -> definitions
- tools/uart_hw_test/README.md : appropiate -> appropriate

os, tools: Fix typo

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c
os/se/ameba/security_ameba_wrapper_tz.c

Add PANIC() to print non-secure register into Secure fault prehandler
Add Security level slot info into Secure during init

os/board/rtl8721csm: Add non-secure print into Secure fault prehandler

---

external/dhcpd/dhcpd.c
external/include/protocols/libcoap/net.h
external/libcoap/net.c
os/arch/arm/src/armv7-m/nvic.h
os/arch/arm/src/armv8-m/nvic.h
os/arch/arm/src/stm32/stm32_sdio.c
os/board/rtl8721csm/src/component/common/mbed/hal/serial_api.h
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/serial_api.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_usi_uart.c
os/drivers/usbdev/usbmsc.c
os/drivers/usbdev/usbmsc.h
os/include/tinyara/can.h
os/include/tinyara/sdio.h

- contol -> control
- reponse -> response

external, os: Fix typo

---

apps/system/utils/security_level_cmd.c
os/include/tinyara/security_level.h
os/se/security_level/security_level.c

Add null check at malloc to prevent memory leakage

os/se/security_level : Add null check at malloc

---

os/Kconfig.debug
os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-m/up_busfault.c
os/arch/arm/src/armv7-m/up_doirq.c
os/arch/arm/src/armv7-m/up_hardfault.c
os/arch/arm/src/armv7-m/up_memfault.c
os/arch/arm/src/armv7-m/up_usagefault.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv7-r/arm_dataabort.c
os/arch/arm/src/armv7-r/arm_prefetchabort.c
os/arch/arm/src/armv7-r/arm_undefinedinsn.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/armv8-m/up_busfault.c
os/arch/arm/src/armv8-m/up_doirq.c
os/arch/arm/src/armv8-m/up_hardfault.c
os/arch/arm/src/armv8-m/up_memfault.c
os/arch/arm/src/armv8-m/up_usagefault.c
os/arch/xtensa/src/xtensa/xtensa_assert.c
os/include/debug.h
os/include/tinyara/security_level.h
os/kernel/debug/Make.defs
os/kernel/debug/debug.c
os/mm/mm_heap/mm_heap_dbg.c

The assert log and alloc fail logs are have dynamic address and system infomation. 
This can cause security issues.
So, for beffer system security, this commit adds to check the security level about system logs

arch, mm: Add to check security level for system log output

---

.circleci/config.yml

updates the rtl8730e configuration from hello to hello_8M and added loadable_apps_8M in .circleci/config.yml

fixup! .circleci: Update rtl8730e configurations

---

os/board/rtl8730e/src/component/usrcfg/rtl8730e/ameba_wificfg.c

- disable tx power limit for wifi

os/board/rtl8730e: update wificfg for tx power limit

---

tools/trap/HowToUseTrap.md
tools/trap/ramdumpParser.py

This patch updates the parser as per latest assert logs in arch files.
vidisha@vidisha:~/rt/tools/trap(master)$ python3 ramdumpParser.py -t log
dump_file                   : None
log_file                    : log
Number of binary            : 1 [kernel]
"kernel" elf_file           : ../../build/output/bin/tinyara.axf
DEBUG_MM_HEAPINFO is not enable. Enable DEBUG_MM_HEAPINFO to see heap usage -----------------------------------------------------------------------------------------
1. Crash Binary             : kernel
2. Crash type               : code assertion by code ASSERT or PANIC
3. Crash point
-  print_assert_detail: Assertion failed at file:hello_main.c line: …

tools/trap: Update TRAP tool as per latest assert logs

---

os/arch/arm/src/amebasmart/Kconfig
os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2c_api.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/include/ameba_pinmux.h
os/board/rtl8730e/src/component/soc/amebad2/fwlib/include/ameba_rom_patch.h
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/Make.defs
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_rom_patch.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/rom_common/ameba_pinmux_rom.c
os/board/rtl8730e/src/rtl8730e_boot.c

- Added multi I2C support
- Fixed GPIO and Audio shared pin configuration

os/board/rtl8730e: Added multi I2C support

---

os/arch/arm/src/armv8-m/up_schedulesigaction.c
os/compression/compress_read.c

- os/compression/compress_read.c: Fixes memfault issues during booting
- armv8-m/up_schedulesigaction: Fix mem_fault caused by not setting REG_EXC_RETURN

fix loading issue by compress and fix memfault by up_schedulesigaction

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c
os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.h
os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c
os/board/rtl8721csm/src/component/common/drivers/wlan/realtek/include/wifi_constants.h
os/board/rtl8721csm/src/component/common/drivers/wlan/realtek/src/osdep/wlan_intf.h
os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

- Add feature to select the wpa mode to use to connect to APs in mixed security mode based on security type indicated by user

os/board/rtl8721csm: add feature for selecting wpa mode

---

os/kernel/log_dump/log_dump.c

Context switch is possible when between after check kerenl heap locked and before send mq for wake up log_dump thread. If in this time, context switch and other thread get kernel heap sem, log_demp thread wake up with kerenl heap locked. This can occur device hang.
Therefore, Fix to do not context swiching during kernel heap locked checking and mq sending to log_dump thread. And, Change meaningless spin-locking in the while statement to sleep every 10ms.
Additional, detail of possible device hang as belog.
- Thread 1: take uart sem and wait for complate compress from log_dump thread.
- Thread 2: take kerenl heap sem and wait for take uart sem
- Thread log_dump: wait kernel heap sem. 
- -> Circular wait, dead lock.

os/kernel/log_dump: fix device hang by kernel heap locked

---

os/arch/arm/src/amebasmart/Kconfig
os/arch/arm/src/amebasmart/amebasmart_spi.c
os/board/rtl8730e/src/rtl8730e_boot.c

Add menuconfig selection for multiple SPI
Change pins and roles

os/arch/src/amebasmart: Add multiple SPI support

---

os/kernel/init/os_bringup.c

preapp_main should run before user_main
increase priority of preapp_main to default + 1

os_bringup.c: Increase the priority of preapp_main

---

os/kernel/task/task_terminate.c

make chages to add critial section only when needed. Also, move the
task cleanup logic to be executed after removing the task from the
task_list.

kernel/task: refactor task_terminate function

---

os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_trx.c

- Fix ipc SVACE warnings for unreachable code

os/board/rtl8730e: fix ipc SVACE warnings

---

build/configs/rtl8730e/Make.defs

- Remove unnecessary comments during post-compilation

build/configs/rtl8730e: Remove unnecessary comments

---

external/gmock/scripts/generator/fixedpoint/fixedpoint_neon.h

Add fixedpoint_neon as GEMMLOWP_NEON(dependent on __ARM_NEON or __ARM_NEON__)

tfmicro/third_party/gemmlowp : Add fixedpoint_neon.

---

os/board/rtl8721csm/src/component/common/file_system/ftl/ftl.c

-simplify all mutex call, remove redundant call
-remove no needed action

os/board/rtl8721csm: Simplify all mutex call in FTL

---

os/kernel/task/task_dumptasks.c
tools/trap/ramdumpParser.py

This patch adds the task state of each task at the task list of the assert log and TRAP.
Assert log result:
```
===========================================================
List of all tasks in the system
===========================================================
NAME |   PID |  PRI |    USED / TOTAL STACK | STACK ALLOC ADDR | TCB ADDR | TASK STATE
-------------------------------------------------------------------------------------------------------------------
Idle Task |     0 |    0 |     676 /    1024 |       0x10004bfc | 0x100294f0 |          2
hpwork |     1 |  201 |     264 /    2028 |       0x1005ecb0 | 0x1005e530 |          7
lpwork |     2 |   50 |     264 /    2028 |       0x1005fc40 | 0x1005f4c0 |          7
LWIP_TCP/IP |     3 |  105 |     356 /    4068 |       0x1006c1f0 | …
```

os/kernel/task: add task state of each task shown in assert log

---

apps/examples/lcd_test/Kconfig
apps/examples/lcd_test/Kconfig_entry
apps/examples/lcd_test/Make.defs
apps/examples/lcd_test/Makefile
apps/examples/lcd_test/example_lcd.c
os/board/rtl8730e/src/Make.defs
os/board/rtl8730e/src/rtl8730e_boot.c
os/board/rtl8730e/src/rtl8730e_st7789.c
os/drivers/lcd/Kconfig
os/drivers/lcd/Make.defs
os/drivers/lcd/lcd_dev.c
os/drivers/lcd/st7789.c
os/include/tinyara/fs/ioctl.h
os/include/tinyara/lcd/lcd.h
os/include/tinyara/lcd/lcd_dev.h
os/include/tinyara/lcd/st7789.h

st7789 lcd driver
rtl8730e changes for st7789 support
lcd demo app

lcd st7789 with spi

---

os/fs/smartfs/smartfs_smart.c

Free name of entry when mkdir finished

fs/smartfs : fix memory leak

---

os/drivers/lcd/lcd_framebuffer.c
os/drivers/lcd/st7789.c
os/include/tinyara/lcd/lcd.h

1. Fix build break
2. Clean orientation logic

driver/lcd/st7789 : Clean code

---

os/arch/arm/src/amebad/Kconfig
os/arch/arm/src/amebad/amebad_spi.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_ssi.c

os/arch/arm/src/amebad, os/board/rtl8721csm: SPI DMA implementation

---

os/arch/arm/src/amebasmart/Kconfig
os/arch/arm/src/amebasmart/amebasmart_spi.c

Do note that the SPI0 cs1 pin is currently set as PB31, SPI1 set as PB29*
* Just randomly selected pin

 os/board/rtl8730e: SPI multi-slave implementation

---

apps/examples/testcase/ta_tc/security/utc/utc_crypto.c

To detect crypto hang issue of security API, add repeat testcases.

apps/examples/testcase: Add testcase for security API

---

os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/dma_api.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2c_api.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/spi_api.c

- Remove redundant codes
- Create API for commonly used codes

os/board/rtl8730e/src: Refine BSP code

---

os/arch/arm/src/amebasmart/Kconfig
os/arch/arm/src/amebasmart/amebasmart_spi.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_gdma_ram.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_spi.c

1. support SPI DMA mode for both 8 bits and 16 bits

os/arch/arm/src/amebasmart: Implement SPI DMA

---

apps/examples/hello_tfmicro/Makefile
build/configs/rtl8721csm/Make.defs
build/configs/rtl8730e/Make.defs
external/tfmicro/Makefile
external/tfmicro/tensorflow/lite/kernels/op_macros.h
framework/include/aifw/AIModel.h
framework/include/aifw/AIProcessHandler.h
framework/include/aifw/aifw_log.h
framework/src/aifw/AIDataBuffer.cpp
framework/src/aifw/AIModel.cpp
framework/src/aifw/AIModelService.cpp
framework/src/aifw/Kconfig
framework/src/aifw/Make.defs
framework/src/aifw/TFLM.cpp
framework/src/aifw/include/AIEngine.h
framework/src/aifw/include/TFLM.h

Update AI Framework:
1.  support models with multi input and output.
2. Improve debug information
3. Modify AIDataBuffer Logs
4. Add inference time Log
5. add AIFW_LOGD in aifw_log.h
6. Memset AIDataBuffer node data to 0 while clearing it.
7. change model size datatype from long to int.
external/tfmicro: Add RTL8730e support

framework/aifw, external/tfmicro: sync from ecode.

---

os/board/artik05x/src/artik05x_tash.c
os/board/common/common.h
os/board/common/partitions.c
os/board/esp32_devkit/src/esp32_boot.c
os/board/imxrt1020-evk/src/imxrt_bringup.c
os/board/imxrt1050-evk/src/imxrt_bringup.c
os/board/rtl8720e/src/rtl8720e_boot.c
os/board/rtl8721csm/src/rtl8721csm_boot.c
os/board/rtl8730e/src/rtl8730e_boot.c
os/board/stm32h745zi-nucleo/src/stm32_boot.c
os/board/stm32l4r9ai-disco/src/stm32_exflash.c
os/fs/driver/mtd/Kconfig
os/fs/driver/mtd/mtd_partition.c
os/fs/driver/mtd/smart.c
os/fs/driver/mtd/w25.c

1. Update Logic regarding automount
2. Expand w25 driver to support w25q256 series
3. Fix smart.c to support big size of flash

board/common : Support 2nd 32mb of flash

---

os/arch/arm/src/amebasmart/amebasmart_spi.c

1. remove delay in spi_dmatxwait
2. replace spi_master_write_stream_dma with spi_master_write_read_stream_dma
3. implement data slicing

os/arch/arm/src/amebasmart: optimize SPI DMA

---

os/arch/arm/src/amebad/amebad_spi.c
os/board/rtl8721csm/src/component/os/os_dep/include/osdep_service.h
os/board/rtl8721csm/src/component/os/os_dep/osdep_service.c
os/board/rtl8721csm/src/component/os/tizenrt/tizenrt_service.c

1. zmalloc 32 byte alignment
2. spi dma data slicing

os/arch/arm/src/amebad: SPI DMA data slicing

---

os/arch/arm/src/amebasmart/amebasmart_flash.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/flash_api.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_flash_ram.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_ipc_api.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/rom_common/Make.defs
os/board/rtl8730e/src/component/soc/amebad2/fwlib/rom_common/ameba_flash_rom.c

- Added check spic busy condition before entering user mode for spic
- Remove rom code from build
- Remove write lock/unlock for flash read
- Revise ipc semaphore type instead of void

os/board/rtl8730e/src, os/arch/arm/src/amebasmart: Fix Flash operation hang issue

---

os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c
os/drivers/Makefile
os/drivers/pm/Make.defs
os/drivers/pm/pm.c
os/include/tinyara/fs/ioctl.h
os/include/tinyara/pm/pm.h
os/kernel/init/os_bringup.c

this commit adds pm driver for locking and unlocking of specific PM state.

os/driver/pm: Add pm driver for lock and unlock

---

os/board/rtl8730e/src/rtl8730e_st7789.c
os/drivers/lcd/st7789.c

pwm duty cycle is being changed to change brightness of lcd. It can go from 0 to 100 percent.

os/board/rtl8730e: dimming support for lcd st7789 using pwm

---

apps/shell/tash_command.c

We check the information or status of the program by using the TASH SYNC command. TASH is only used for debugging and testing, so it does not affect power consumption in actual operation. Therefore, for proper debugging and testing, we apply pm suspend to the TASH SYNC command to ensure operation.

apps/shell/tash_command: Add pm suspend while executing SYNC cmd

---

os/arch/arm/src/amebasmart/amebasmart_i2c.c

-Modify pins for i2c0 and i2c1 according to board revision 5th

os/arch/arn/src/amebasmart: Modify i2c pins for board revision 5th

---

os/binfmt/libxipelf/xipelf.c
os/tools/mkldscript.py

support xipelf binary loading with binary signing

os/binfmt, os/tools: support binary signing with xipelf

---

os/drivers/lcd/st7789.c

Update spi frequency to 50MHz from 48MHz. Removed unnecessary code which was using slowed down api after DMA support

os/drivers/lcd : update spi frequency to maximum 50 MHz

---

build/configs/rtl8730e/scripts/rlx8730e_img2.ld
os/arch/arm/Kconfig
os/arch/arm/src/amebasmart/Make.defs
os/arch/arm/src/amebasmart/amebasmart_idle.c
os/arch/arm/src/amebasmart/amebasmart_pmc.c
os/arch/arm/src/amebasmart/amebasmart_smp.c
os/arch/arm/src/amebasmart/psci.c
os/arch/arm/src/amebasmart/psci.h
os/arch/arm/src/armv7-a/arm_cpugating.c
os/arch/arm/src/armv7-a/arm_cpuhotplug.c
os/arch/arm/src/armv7-a/arm_cpustart.c
os/arch/arm/src/armv7-a/arm_gicv2.c
os/arch/arm/src/armv7-a/gic.h
os/arch/arm/src/armv7-a/smp.h
os/board/rtl8730e/src/component/soc/amebad2/misc/ameba_tizenrt_pmu.c
os/board/rtl8730e/src/component/soc/amebad2/misc/ameba_tizenrt_pmu.h
os/kernel/Kconfig
os/kernel/init/os_smpstart.c

- This PR introduces cpu hotplug mode, which is a necessary feature to integrate PM and SMP.

os: CPU hotplug mode implementation

---

os/board/rtl8730e/src/component/bluetooth/driver/hci/hci_process/hci_process.c
os/board/rtl8730e/src/component/bluetooth/driver/platform/amebad2/hci/hci_platform.c

- Revise data retrieve flow from external flash
- Revise the condition checking for data binary

os/board/rtl8730e: Revise data retrieve flow from external flash

---

os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_hp/ameba_mipi.c
os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/lcd/mipi_lcd.c

- Add cache clean invalidate operation
- Add LCD frame trigger interrupt
- Revise LCD initialization flow

os/board/rtl8730e: Revise LCDC logic flow

---

os/arch/arm/src/amebad/amebad_idle.c
os/arch/arm/src/amebalite/amebalite_idle.c
os/arch/arm/src/amebasmart/amebasmart_idle.c
os/arch/arm/src/imxrt/imxrt_idle.c
os/arch/arm/src/s5j/s5j_idle.c
os/arch/arm/src/stm32/stm32_idle.c
os/arch/arm/src/stm32h745/stm32h745_idle.c
os/arch/arm/src/stm32l4/stm32l4_idle.c
os/include/tinyara/arch.h
os/include/tinyara/pm/pm.h
os/kernel/init/os_start.c
os/pm/Makefile
os/pm/pm.h
os/pm/pm_changestate.c
os/pm/pm_idle.c
os/pm/pm_wakehandler.c

Move PM Specific Code from BSP to PM Module. Create new pm_idle API  to check board ready to go sleep state. This PR also give functionality to do all the pre processing related to PM inside PM module only.

os: Refactor PM & BSP Code

---

os/arch/arm/src/amebasmart/amebasmart_mipi.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_hp/ameba_mipi.c
os/board/rtl8730e/src/component/soc/amebad2/misc/ameba_tizenrt_pmu.h
os/board/rtl8730e/src/rtl8730e_boot.c
os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/lcd/lcd_dev.c
os/drivers/lcd/mipi_lcd.c
os/drivers/mipidsi/mipi_dsi_device.c
os/include/tinyara/lcd/mipi_lcd.h
os/include/tinyara/lcd/st7701.h

- Implement logic for LCD operation under different PM states
- Reinit both MIPI and LCDC when wakeup from power saving
- Remove redundant code and cleanup
- Fix some code misalignment

os/board/rtl8730e: Integrate LCD with PM

---

os/pm/pm_sleep.c

This commit resolve memory leak issue with pm_sleep API. pm_sleep allocating timer from heap and releasing memory after timer expiration. In event of thread termination, the timer will remain active forever and cause memory leak. To prevent this issue now we are using tcb->waitdog. During the event of thread termination the task_recover API will call and it delete the timer to prevent memory leak.

os/pm: fix pm_sleep memory leak

---

os/include/tinyara/audio/audio.h

SPD will always work with EPD, hence add values only related to callback & msg And add reserved value for local command too

driver/audio : Add constant value to handle SPD

---

os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2s_api.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/include/ameba_rcc.h

*Wordlength correction has been added

os/arch/arm/src/amebasmart: I2S driver sampling fix

---

apps/examples/smp/smp_main.c
os/kernel/Kconfig
os/kernel/init/os_start.c

Add support for Asymmetric Multi Processing (AMP) in kernel
Modify SMP test app for AMP
Test result:
With AMP:
```
TASH>>  Main[0]: Running on CPU0
Main[0]: Initializing barrier
Running SMP test with AMP configuration
Main[0]: Thread 1 created
Thread[1]: Started
Thread[1]: Running on CPU1
Main[0]: Thread 2 created
Thread[2]: Started
Thread[2]: Running on CPU1
Thread[3]: Started
Main[0]: Thread 3 created
Thread[3]: Running on CPU1
Thread[4]: Started
Main[0]: Thread 4 created
Thread[4]: Running on CPU1
Thread[5]: Started
Main[0]: Thread 5 created
Thread[5]: Running on CPU0
Thread[6]: Started
Thread[6]: Running on CPU0
Main[0]: Thread 6 created
Thread[7]: Started
Thread[7]: Running on CPU0
Main[0]: Thread 7 created
Thread[8]: Started
Thread[8]: Running on CPU0
Main[0]: Thread 8 created …
```

Enable AMP on rtl8730e

---

apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp
framework/src/media/voice/EPDInferenceHandler.cpp
framework/src/media/voice/EPDInferenceHandler.h
framework/src/media/voice/EPDProcessHandler.cpp
framework/src/media/voice/EPDProcessHandler.h
framework/src/media/voice/SpeechDetector.cpp

This PR sync Media Framework to the latest changes.

Media : Sync Media Framework to latest code.

---

framework/include/aifw/AIInferenceHandler.h
framework/include/aifw/AIModel.h
framework/src/aifw/AIInferenceHandler.cpp
framework/src/aifw/AIModel.cpp
framework/src/aifw/TFLM.cpp
framework/src/aifw/include/AIEngine.h
framework/src/aifw/include/TFLM.h

This PR sync AIFW Framework to the latest changes.

AIFW : Sync AIFW Framework to latest code.

---

apps/examples/rtc/rtc_main.c
apps/examples/testcase/le_tc/drivers/drivers_tc_main.c
apps/examples/testcase/le_tc/drivers/tc_internal.h
apps/examples/testcase/le_tc/drivers/tc_rtc.c

- This patch adds sample app to test the rtc alarm. This app set the alarm and alarm signal handler gets called when alarm gets expired. we can also cancel the alarm before it expires.

Add sample app and UTC to test rtc alarm 

---

os/kernel/sched/sched_setpriority.c

There is an issue where a deadlock occurs when using pthread_cond_wait().
If the priority of the thread calling pthread_cond_signal is higher than that of the thread
calling pthread_cond_wait, a deadlock is occuring.
The cause is that even though sched_lock was called within the pthread_cond_wait function,
during the PRIORITY INHERITANCE operation in the sem_post operation.
So, It should have take sem of cond after give mutex in pthread_cond_wait, It can't take sem
because it give up cpu in this time, resulting in a leak of cond signals.
In the sched_setpriority() function, it changes its own priority while giving up the CPU.
Therefore, in the case of sched_lock, so as not to give up the CPU, threads with priorities
higher than the changed priority of the running thread are changed to …

sched/sched_setpriority: fix cond wait deadlock issue

---

framework/include/media/MediaTypes.h
framework/src/media/utils/MediaUtils.cpp

media/utils: Add check for ID3v2 tag in mp3 file format

media/utils: Add check for ID3v2 tag in mp3 file format

---

apps/examples/SoundPlayer/soundplayer_main.cpp
framework/src/media/FocusManager.cpp

Unprepare & destroy properly when focus lost.

apps/soundPlayer : Fix to use audio focus properly.

---

framework/include/aifw/AIModel.h
framework/include/aifw/AIProcessHandler.h
framework/src/aifw/include/AIEngine.h
framework/src/aifw/include/TFLM.h

Adding tinyara config header file for preprocessor directives

framework/aifw: Add tinyara/config.h in f/w header files

---

os/board/rtl8730e/src/component/bluetooth/example/ble_central/ble_tizenrt_client.c
os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c

- change BLE scan type from passive to active

os/board/rtl8730e: change BLE scan type

---

apps/examples/wakerec/wakerec.cxx
framework/include/media/voice/SpeechDetector.h
framework/src/media/audio/audio_manager.c
framework/src/media/audio/audio_manager.h
framework/src/media/voice/HardwareKeywordDetector.cpp
framework/src/media/voice/HardwareKeywordDetector.h
framework/src/media/voice/KeywordDetector.h
framework/src/media/voice/SoftwareKeywordDetector.cpp
framework/src/media/voice/SoftwareKeywordDetector.h
framework/src/media/voice/SpeechDetector.cpp

Implementation to get keyword data as per new flow
2 new APIs added to get keyword size and data

Implementation to get keyword data as per new flow

---

apps/examples/SoundPlayer/soundplayer_main.cpp
framework/src/media/FocusManager.cpp
framework/src/media/MediaPlayerImpl.cpp
framework/src/media/audio/audio_manager.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/drivers/audio/alc1019.c
os/drivers/audio/syu645b.c

Focus manager doesn't work between 2 more application

framework/media : Fix focus manager

---

os/arch/arm/src/armv7-a/arm_assert.c

If an assert happens when SMP is handled, we need to do the following:
- Enter critical section
- If crash is in kernel, then stop all other cores
- Perform assert handling
- Leave critical section

os/arch/arm/src/armv7-a: Modify assert handler for SMP case

---

apps/examples/led_test/Kconfig
apps/examples/led_test/Kconfig_entry
apps/examples/led_test/Make.defs
apps/examples/led_test/Makefile
apps/examples/led_test/example_led.c
os/board/rtl8730e/src/rtl8730e_boot.c

This commit adds led pin (PB_20) to gpio driver.

rtl8730e_boot.c: Add led pin to gpio driver

---

os/drivers/serial/serial.c

This commit make use of pm_suspend and pm_resume APIs to avoid board sleep during uart_write operation. It register PM_UART_DOMAIN during uart_open to access PM APIs. The prevention of board sleep is required to avoid data loss during uart_write operation.

os/drivers/serial: Avoid Board Sleep in UART Tx

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

- change of log printing api from dbg to debug_print, to reduce default log printing when starting and stopping BLE adv

os/board/rtl8721csm: change of BLE adv log API

---

os/board/rtl8730e/src/component/bluetooth/api/rtk_stack/rtk_stack_gatts.c
os/board/rtl8730e/src/component/bluetooth/rtk_stack/inc/profile_server.h

- fixed issue of unable to set an attribute as notify and indicate at the same time

os/board/rtl8730e: fix BLE GATT attribute notify & indicate

---

os/kernel/wdog/wd_start.c
os/pm/pm_wakehandler.c

There is an issue where after waking up from UART RX, even if pm_timedsuspend is called, it immediately enters enter_board_sleep again.
since, The missed ticks while the board is asleep will be compensated for after waking up. At this time, the wd timer is corrected in the first tick ISR that comes after wakeup.
but UART RX ISR is comming first than tick ISR.
So even if call pm_timedsuspend whick is using wd timer, it will expired in first tick ISR after wakeup.
The issue flow likes below:
WAKE HANDLER -> UART RX ISR -> UART READ THREAD -> call pm_timedsuspend -> TICK ISR (Collect missing tick and expire)
Therefore, Move correcting wd missing tick to pm_wakehandler. but The wd timer is corrected in pm_wakehandler and the timer expiration is performed in the first ISR after wakeup. This is …

wdog/wd_timer_nohz: Move correcting wd missing tick to pm_wakehandler

---

os/arch/arm/src/amebasmart/amebasmart_serial.c

1. there is no domain control for loguart tx irq previously, causing it to enter PG before all logs are printed correctly
2. add domain control similar to UART1, both LOGUART and UART1 shared the same domain.

os/arch/arm/src/amebasmart: fix pm sleep before loguart flush all data

---

os/drivers/ai-soc/ndp120/src/syntiant_ndp120.c

This PR attempts to work around an issue of mbwait timeout during FW load.

During init, wait for mbout msg, and retry if it does not show

---

os/arch/arm/src/amebasmart/amebasmart_serial.c

Change Notes:
1. Improved LOGUART Tx Empty check:
- Simplified the check in rtl8730e_log_up_txempty() to determine if the Tx FIFO is empty by directly checking the LOGUART_BIT_TP4F_EMPTY status.
2. Updated Tx FIFO Empty and NOT_FULL logic:
- The txempty_en check to be exactly 0x4, and repaced the & operator to be && operator.
3. Removed duplicate check for Rx FIFO:
- set the LOGUART_GetChar(_FALSE) uart_recvchars -> uart_rxavailable -> *LOGUART_Readable() -> uart_receive -> rtl8730e_log_up_receive -> *LOGUART_GetChar()
4. Workaround for Tx FIFO full case:
- Added else case to handle the Tx FIFO full condition by enabling the LOGUART_TX_EMPTY_PATH_4_INT Tx Empty IRQ.
- Further investigation required to identify where Tx Empty FIFO IRQ was disabled.

os/arch/arm: Workaround to fix LOGUART Tx IRQ handling for Tx FIFO full case

---

os/drivers/ai-soc/ndp120/src/syntiant_portability.c

Added implementation of `syntiant_get_ms*()` functions.

ai-soc/ndp120: add implementation of syntiant_get_ms*() functions

---

apps/examples/SoundPlayer/soundplayer_main.cpp
apps/examples/wakerec/wakerec.cxx
framework/src/media/MediaPlayerImpl.cpp
framework/src/media/audio/audio_manager.c
os/drivers/audio/syu645b.c
os/drivers/audio/syu645b.h
os/drivers/audio/syu645bscripts.h

1. New volume logic based on stream policy added.
2. Refactor wakerec to work based on latest code

Media : Add new volume logic & update wakerec

---

os/arch/arm/src/amebasmart/amebasmart_i2s.c

1. domain control should be added at start i2s DMA tx and end of i2s DMA tx.
2. original place is the end of CPU filling up DMA page, but not the end of DMA transfer, resulting in enter sleep before I2S tx done.
3. add i2s_lock_state flag to keep track current domain status, since i2s_send will be called multiple times by application, it should only lock for the first time, and release the lock only when i2s_stop is called.
4. verified that it will only enter sleep after I2S tx done, and after wakeup it can start I2S tx again.

os/arch/arm/src/amebasmart: update I2S PM domain control

---

os/drivers/audio/syu645b.c

reset config before setting default Equalizer Set and then set volume again
this pr depends on https://github.com/Samsung/TizenRT/pull/6524.
please merge after that.

os/drivers/audio: reset config before setting default Equalizer Set

---

apps/examples/wakerec/wakerec.cxx
framework/include/audio/SoundManager.h
framework/src/audio/Make.defs
framework/src/audio/SoundManager.cpp
framework/src/media/MediaPlayerImpl.cpp
framework/src/media/audio/audio_manager.c
framework/src/media/audio/audio_manager.h
framework/src/media/utils/MediaUtils.cpp

This Commit Sync commits from Media Repo to Samsung/TizenRT opensource repo.

framework/media : Sync Media changes.

---

os/pm/pm_idle.c

This commit resolves the board hang issue, which is occuring with AMP & PM.
The CPU1 hotplug code is not taking care of EXIT case in PM TIMEDWAKEUP
code. When PM decides to make board sleep and the wakeup time is less than
CONFIG_PM_SLEEP_ENTRY_WAIT_MS, then it simply exit from pm_idle without
making board sleep, but in this case CPU1 was already in HOTPLUG state.
Later when application thread in CPU0 tries to gate CPU1, then CPU0 gets
stuck in while loop waiting for CPU1 to gate but since CPU1 is
in HOTPLUG state, it won't able to change its state, which leads to hang
issue. This commit moves the hotplug code after PM TIMEDWAKEUP code
which ensure the hotplug lead to board sleep without any failure.

os/pm: Fix board hang issue

---

os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_i2c.c

This commit addresses issue where i2c driver may get stuck in infinite loop while checking for status bit due to unstable voltage on SDA/SCL line caused by hardware
Added a counter-based timeout as watchdog cannot be used as interrupts are disabled before I2C operation happens
The workaround message for ist415 driver is replaced to indicate the root cause due to LDO soft startup voltage unstable

os/board/rtl8730e: add timeout for i2c writebrk api

---

os/board/rtl8730e/src/component/bluetooth/driver/platform/amebad2/hci/hci_uart.c

- Changed HCI_ERR and HCI_INFO to DGB_8195A, which does not use printf

os/board/rtl8730e: change BLE HCI debug print function

---

os/arch/arm/src/amebad/amebad_i2c.c
os/arch/arm/src/amebad/amebad_i2s.c
os/arch/arm/src/amebad/amebad_rtc_lowerhalf.c
os/arch/arm/src/amebad/amebad_spi.c
os/arch/arm/src/amebalite/amebalite_i2c.c
os/arch/arm/src/amebalite/amebalite_i2s.c
os/arch/arm/src/amebalite/amebalite_rtc_lowerhalf.c
os/arch/arm/src/amebalite/amebalite_spi.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/arch/arm/src/amebasmart/amebasmart_rtc_lowerhalf.c
os/arch/arm/src/amebasmart/amebasmart_spi.c
os/arch/arm/src/amebasmart/amebasmart_usb.c
os/board/rtl8720e/src/component/os_dep/osdep_service_critical.c
os/board/rtl8720e/src/component/os_dep/osdep_service_mutex.c
os/board/rtl8721csm/src/component/os/tizenrt/tizenrt_service.c
os/board/rtl8730e/src/component/os_dep/osdep_service_critical.c
os/board/rtl8730e/src/component/os_dep/osdep_service_mutex.c

- Correct sem_wait while loop check condition
- Standardize sem_wait return value check

os/arch/arm/src: Fix Ameba incorrect sem_wait condition

---

apps/examples/power/power_main.c
apps/examples/uart_loopback/uart_loopback.c

Build warnings fix for power, uart examples

Build warnings fix for power, uart examples

---

apps/platform/gnu/Make.defs
apps/platform/gnu/gnu_unwind_find_exidx.c
os/binfmt/binfmt_execmodule.c
os/binfmt/libxipelf/xipelf.c
os/include/tinyara/binfmt/binfmt.h
os/include/tinyara/userspace.h
os/userspace/up_userspace.c

tested all possible cases, test commit (https://github.com/abhishek-samsung/TizenRT/commit/9fae1ce32418ed54899547fa19d9fb756dec9dae)
```
caught 5 in common
caught 5 thrown in app caught in common
caught 5 thrown in common and caught in app
caught 5 in app
```

Add custom find_exidx to support exceptions accross differnt binaries

---

os/drivers/input/Kconfig
os/drivers/input/ist415.c
os/drivers/input/ist415.h
os/drivers/input/ist415_misc.c

Touch sampling rate based on number of interrupts in a second
Its coming ~ 100-120 SPS

os/drivers/input : add touch sampling rate

---

os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c

-Add application disconnect API trigger for connection fail case
-Add application disconnect API trigger for pairing fail case

os/board/rtl8730e: Add BLE disconnect call back API trigger

---

os/board/rtl8730e/src/component/bluetooth/profile/client/rtk_gcs_client.c

- changed printf to debug_print in rtk_gcs_client.c

os/board/rtl8730e: Change printf to debug_print in BLE client

---

os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/lcd/mipi_lcd.c

Backlight on/off sequence updated as per correct order
It is verified with power off/on test

os/drivers/lcd, os/board/rtl8730e: modify power on/off sequence

---

apps/shell/Kconfig
apps/shell/tash_main.c

We need to change TASH task priority sometime.
Therefore, Add CONFIG_TASH_TASK_PRIORITY

apps/shell: Add CONFIG_TASH_TASK_PRIORITY configure

---

framework/src/ble_manager/ble_manager_api.c
framework/src/ble_manager/ble_manager_lwnl.c
framework/src/ble_manager/ble_manager_state.c
os/board/rtl8730e/src/component/bluetooth/api/Make.defs
os/board/rtl8730e/src/component/bluetooth/api/rtk_bt_vendor.c
os/board/rtl8730e/src/component/bluetooth/api/rtk_stack/rtk_stack_api.c
os/board/rtl8730e/src/component/bluetooth/driver/platform/amebad2/hci/hci_platform.c
os/board/rtl8730e/src/component/bluetooth/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8730e/src/component/bluetooth/inc/bt_api_config.h
os/board/rtl8730e/src/component/os/tizenrt/rtk_blemgr.c

- added ble_server_set_adv_tx_power to set TX power for multi adv

os/board/rtl8730e: Add BLE TX power setting API

---

os/board/rtl8730e/src/component/file_system/ftl/ftl.c

-Remove Status Bits read and backup
-Check if key is injected, else do not set or clear write protection

os/board/rtl8730e: Optimize FTL Write Protection Process

---

os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/ble_tizenrt_combo.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_ble_utils.h
os/board/rtl8730e/src/component/os/tizenrt/rtk_blemgr.c

-Rename add_profile API to set_server_config API
-Remove not used variable

os/board/rtl8730e: Rename BLE Set Server Config API

---

os/arch/arm/src/armv7-a/arm_assert.c

Fix wrong logs when a crash occurs in irq context:
1. The intial logs print the task name and pid instead of irq num
2. The irq stack caclulation is wrong and hence the logs indicate that stack pointer if out of allocated stack
3. Even though the SP is actually valid, the proper stack data is not printed. So, it is not possible to get the correct stack trace.

os/arch/arm/src/armv7-a: Fix assert logs for irq crash

---

apps/system/utils/fscmd.c
os/fs/driver/mtd/little.c
os/fs/driver/mtd/w25n.c
os/fs/littlefs/lfs_vfs.c
os/fs/littlefs/littlefs/lfs.c
os/fs/littlefs/littlefs/lfs.h
os/fs/littlefs/littlefs/lfs_util.c
os/fs/littlefs/littlefs/lfs_util.h
os/kernel/silent_reboot/silent_reboot.c

https://github.com/littlefs-project/littlefs(8ed63b27be79ab59ee1cd15a950ddd64e7a602f7)

fs/littlefs : Update version of littlefs

---

os/drivers/input/touchscreen.c

Fix wrong indentation in drivers/input/touchscreen.c

drivers/input: Fix wrong indentation

---

os/drivers/lcd/mipi_lcd.c

os/drivers/lcd/mipi_lcd: Add log when switch mipi mode

---

os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/board/rtl8730e/src/component/mbed/hal/i2c_api.h
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2c_api.c

Revert "os/arch/arm/src/amebasmart: refactor peripheral suspend flow memory management"

---

os/kernel/task/task_terminate.c

When a task is terminated we do below things in a sequence
1. Remove the task from the corresponding tasklist (in current issue, the task is on the mq wait tasklist)
2. Reset the values in the tcb in task_restore API (One of the values being reset is used to indicate if the task is on the mq wait tasklist)
However, sine the above points are not performed as a single atomic step, the state of the tcb becomes inconsistent with the tasklist. Due to this, the mq send api is resulting in ASSERT failure.
To fix this issue, we call task_recover before remove the task from the tasklist.

Reverse sync ecode to public  (3dba1dc)

---

os/drivers/input/ist415.c
os/drivers/input/ist415.h
os/drivers/input/ist415_misc.c

- Added the condition of sem_wait() in process event.

*driver/input: Patch auto calibration timeout issue.

---

os/arch/arm/src/armv7-a/arm_cpupause.c

If we gate the CPU and then if we try to pause the same CPU, we faced the hang issue. This patch resolves the hang issue by adding the CPU gating check while proccessing the CPU pause request.

arch/armv7-a: Fix hang issue while gating and then pausing the CPU

---

os/fs/procfs/fs_procfsproc.c

This patch shows the tash as waiting for semaphore and next ready to run tcb as running for that cpu.
Test result:
PID | PRIO | FLAG |  TYPE   | NP |  STATUS  | CPU | NAME
------|------|------|---------|----|----------|-----|----
0 |    0 | FIFO | KTHREAD | N  | RUNNING  |   0 | CPU0 IDLE
1 |    0 | FIFO | KTHREAD | N  | RUNNING  |   1 | CPU1 IDLE
2 |  201 | RR   | KTHREAD |    | WAITSIG  |   0 | hpwork
3 |   50 | RR   | KTHREAD |    | WAITSIG  |   0 | lpwork
5 |  200 | RR   | KTHREAD |    | MQNEMPTY |   0 | km4_log_task
6 |  107 | RR   | KTHREAD |    | WAITSEM  |   0 | inic_msg_q_task
7 |  104 | RR   | KTHREAD |    | WAITSEM  |   0 | inic_host_rx_tasklet
8 |  103 | RR   | KTHREAD |    | WAITSEM  |   0 | inic_ipc_api_host_task
10 |  105 | RR   | KTHREAD |    | WAITSEM  |   0 | LWIP_TCP/IP …

os/fs/procfs: make ps cmd to show next task as running instead of tash

---

build/configs/rtl8730e/rtl8730e_make_bin.sh

-Add BLE debug file (APP.trace) generation script command -APP.trace is used to decode BLE debug log

build/configs/rtl8730e: Add BLE debug file generation script command

---

apps/examples/lcd_test/example_lcd.c

apps/examples/lcd_test/: Add light and dark shade to bitmap and power off and power on feature via terminal in lcd_test

apps/examples/lcd_test/: Add bimap shade and lcdtest power on off feature

---

apps/system/utils/fscmd.c
os/fs/driver/mtd/little.c
os/fs/littlefs/lfs_vfs.c
os/fs/littlefs/littlefs/lfs.c
os/fs/littlefs/littlefs/lfs.h

This commit adds lfs_reserve_corrupt to give file system to corruption. if you want recover it to normal, you should enter format and reboot.

fs/littlefs : Add littlefs corrupt

---

apps/examples/testcase/ta_tc/security/utc/utc_crypto.c

Add GCM testcases of AAD and TAG validation.
1. Check AAD mismatch
2. Check TAG mismatch
3. Encrypt/decrypt success if AAD is null

apps/examples/testcase/ta_tc/security/utc: Add GCM testcases

---

os/arch/arm/src/amebasmart/amebasmart_mipi.c
os/drivers/lcd/mipi_lcd.c

1. add mipi receive cmd decode for rx isr
2. add error handling if mipi entered invalid state

os/arch/arm/src/amebasmart: support mipi read

---

os/drivers/audio/Make.defs
os/drivers/audio/cJSON.c
os/drivers/audio/syu645b.c
os/include/cJSON.h

syu645b.c requires cJSON
cJSON is currently part of external. external is not linked to kernel This give undefined reference errors.

Adding json to kernel binary

---

os/arch/arm/src/amebasmart/amebasmart_mipi.c

-reset LPRX and LPTX without LPRX or LPTX timeout caused error code remain after clear
-Error code check after clear cause command mode disable
-Do not reset LRRX and LPTX after LPRX or LPTX timeout

os/arch/arm/src/amebasmart: Fix MIPI command mode disable issue

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c
os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.h
os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_netmgr.c
os/board/rtl8730e/src/component/wifi/api/wifi_intf_drv_to_app_basic.h
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api_basic.c

Add support for obtaining BSSID info in rtk_netmgr of rtl8721csm and rtl8730e

Support obtaining BSSID info in rtk_netmgr

---

os/board/rtl8721csm/src/component/common/file_system/ftl/ftl.c

- previously the secure will call ftl_non_secure_save_to_storage to write encrypted data to flash, this causes fault
- to fix the fault, now non-secure will call ftl_write_to_storage to write encrypted data to flash

os/board/rtl8721csm: modify ftl write flow

---

os/fs/littlefs/lfs_vfs.c
os/fs/littlefs/littlefs/lfs.c
os/fs/littlefs/littlefs/lfs.h

fs/littlefs : Apply thread-safe logic for littlefs

---

os/drivers/lcd/lcd_dev.c
os/drivers/lcd/mipi_lcd.c
os/drivers/lcd/st7701.c
os/drivers/lcd/st7701sn.c
os/drivers/lcd/st7785.c
os/include/tinyara/lcd/lcd.h
os/include/tinyara/lcd/lcd_dev.h
os/include/tinyara/lcd/st7701sn.h
os/include/tinyara/lcd/st7785.h

Implemented a new ioctl command to fetch LCD parameters including screen active area height in mm, width in mm, screen size in inch and DPI.

os/: Add IOCTL support to retrieve display info (height, width, size, dpi)

---

apps/examples/lcd_test/example_lcd.c

Add test for LCD_GETINFO ioctl for LCD width mm, height mm, DPI
TASH>>lcd_test lcdinfo
TASH>>=== LCD demo ===
LCD HEIGHT MM: 58
LCD WIDTH MM: 43
LCD SIZE INCH: 2.842563
LCD DPI: 140.718063

apps/examples/lcd_test: Add lcd get info test

---

apps/examples/lcd_test/example_lcd.c

Implemented a stress test inside the LCD test application to check the stability of the LCD during continuous operations.
-Thread1 : Continuously switches the frame colour between red and blue to simulate rapid screen updates. -Thread2 : Continuously turns the lcd on and off to simulate frequent power cycling.
Usage:
tash>> lcd_test stress_test start <mode>                                     ----Start stress test
tash>> lcd_test stress_test stop                                                     --- Stop stress test
<mode>
0 : Run only power cycle stress test
1 : Run only frame change stress test
2 : Run both tests simultaneously

apps/examples/lcd_test/example_lcd.c: Add lcd stress test

---

os/board/rtl8730e/src/component/bluetooth/profile/client/rtk_gcs_client.c

- fixed assert in loadable config caused by malloc

os/board/rtl8730e: modify malloc to kmm_malloc

---

apps/system/utils/utils_heapinfo.c

Modify heapinfo behavior to print heap information for all binaries when executed without specifying a binary.
If the user uses the -k, -b, or -d options, it is assumed that binary is specified.

apps/system/utils/heapinfo: Default to printing heapinfo for all binaries

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8730e/src/component/bluetooth/example/ble_peripheral/ble_tizenrt_server.c

- added check for BLE server connection status before indication and notification

os/board/rtl8721csm: add BLE server connection status check

---

framework/src/eventloop/eventloop_async.c

Replace static callback list array with pointer array to enable on-demand dynamic allocation of callback list structures.
This change improves memory efficiency by allocating actual callback list data only when needed,
rather than pre-allocating for all possible tasks.
Memory Usage Breakdown:
- thread_safe_cb_list_t structure: 24 bytes total
- `sq_queue_t cb_list`: 8 bytes (double linked list head)
- `el_async_t *async_handle`: 4 bytes (pointer)
- `sem_t list_sem`: 12 bytes (semaphore with CONFIG_PRIORITY_INHERITANCE)
Memory Usage:
- Previous: 24 bytes * CONFIG_MAX_TASKS (static allocation for all tasks)
- Current: 4 bytes * CONFIG_MAX_TASKS (pointer array) + 24 bytes * tasks_using_eventloop (dynamic allocation)
Examples (tasks_using_eventloop = 10):
Case 1: CONFIG_MAX_TASKS = 128
- …

framework/src/eventloop: Optimize callback list management with dynamic allocation

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

-Remove not needed APIs calling
-Clear Adv sub state when Adv started
-Add assert check to halt the program if the BLE state is stuck

os/board/rtl8721csm: Fix BLE Adv corner case

---

os/pm/pm_procfs.c

This commit completely refactors the pm_procfs.c implementation to improve readability, maintainability, and extensibility.
The previous implementation relied on a complex, procedural function (power_find_dirref) to parse relative paths. This involved manual string manipulation, nested if-else statements, and state management using level indicators, making the code difficult to understand and prone to errors when extending.
This has been replaced with a data-driven, declarative design centered around a static "template tree" (power_path_template_s).
1. Declarative Template Tree The entire /proc/power filesystem layout, including full path patterns, file/directory types, and associated handlers, is now defined in a single, static data structure. This makes the overall structure …

os/pm: Rearchitect pm_procfs with a declarative template tree

---

os/net/lwip/src/core/ipv4/ip_nat/lwip_ip4nat.c

This causes conflicts during code rebase.

Use system mutex APIs instead of `rtw` APIs
