Samsung/TizenRT

os/fs/driver/mtd/smart.c

We didn't move journal pointer when error happened, this will overwrite last journal

fs/smartfs : Checkout & move journal pointer even if operation is failed

---

apps/shell/tash_command.c
apps/shell/tash_internal.h
apps/shell/tash_main.c
apps/system/utils/README.md

1. refactoring the tash_get_cmd_from_history 
1. Return the address of command according to history index given on success, return null on failure
2. Rename the variables for readability
3. Add code comments to explain the operation
4. Add user feedback messages on failure case
5. Fix the bug on checking index validation
2. tidyup treatement of semicolon 
1. Add error feedback message on single semicolon
When only semicolon is input without any command, Linux returns
syntax error. Let's do the same.
2. Rename the local variable, has_nextcmd
It shows there is a next continouse command. When it is set,
Main loop should check continousely. For this usages, 'has' is
better to understand the meaning. Let's rename 'is_nextcmd' to 'has_nextcmd'.
3. add combination command with exclamation …

shell: tidyup semicolon and exclamation commands

---

os/board/Kconfig
os/board/rtl8721csm/src/rtl8721csm_boot.c

There are two comments for partition in os/board and os/board/common.
"Board-Partition Options"
Let's remove one.

board: remove duplicated comment for partition

---

lib/libc/time/lib_localtime.c

A libc is used by kernel and user spaces.
So it should use lib_malloc for memory allocation instead of malloc.

libc/time: Change malloc to lib_malloc for memory allocation

---

framework/include/binary_manager/binary_manager.h
framework/src/binary_manager/Make.defs
framework/src/binary_manager/binary_manager_get_state.c
framework/src/binary_manager/binary_manager_interface.c
framework/src/binary_manager/binary_manager_internal.h
framework/src/binary_manager/binary_manager_notify.c
framework/src/binary_manager/binary_manager_update.c
loadable_apps/loadable_sample/wifiapp/binary_update.c
os/binfmt/binfmt_execmodule.c
os/include/tinyara/binary_manager.h
os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_binfile.c
os/kernel/binary_manager/binary_manager_getinfo.c
os/kernel/binary_manager/binary_manager_load.c

User can get a path download binary instead of opened fd from binary_manager_open_new_entry.
And then user can perform file operations like open, read, write.

kernel/binary_manager: Get path to download binary from binary_manager_open_new_entry

---

os/drivers/wireless/realtek/wifi_util_interface/wifi_util.c
os/drivers/wireless/scsc/mib.c
os/drivers/wireless/scsc/slsi_drv.c
os/drivers/wireless/scsc/slsi_drv_lwnl.c
os/drivers/wireless/scsc/slsi_drv_netmgr.c
os/drivers/wireless/scsc/slsi_utils.c
os/drivers/wireless/scsc/slsi_wifi_api.c
os/se/konai/konai.c
os/se/sss/security_hal_wrapper.c
os/se/virtual/hal_virtual.c

Because se and drivers/wireless folders are parts of kernel binary, they should use kmm APIs like
kmm_malloc, kmm_free, kmm_calloc and etc instead of malloc, free and calloc.
This commits fix them.

drivers/wireless, se: use kmm APIs

---

lib/libc/lib_internal.h
lib/libc/misc/lib_hashmap.c
lib/libc/time/lib_localtime.c

In PR#4551, malloc is changed to lib_malloc, then we should change free to lib_free also.
Because lib can be used from kernel and user spaces.

libc/time/lib_localtime : Change free to lib_free

---

os/drivers/wireless/realtek/wifi_util_interface/wifi_util.c
os/drivers/wireless/scsc/mib.c
os/drivers/wireless/scsc/slsi_utils.c
os/se/konai/konai.c
os/se/sss/security_hal_wrapper.c
os/se/virtual/hal_virtual.c

To use kmm APIs like kmm_malloc, kmm_free, <tinyara/kmalloc.h> should be
included.
This commit includes it on some files under os/wireless and os/se folders.

drivers/wireless, se: include kmalloc.h for kmm APIs

---

os/arch/arm/src/s5j/sss/sss_driver_io.c
os/arch/arm/src/s5j/sss/sssro_verify.c
os/arch/xtensa/src/esp32/esp32_ledc.c
os/arch/xtensa/src/esp32/esp32_rtc_module.c
os/arch/xtensa/src/esp32/spi_flash/flash_mmap.c
os/arch/xtensa/src/esp32/spi_flash/partition.c
os/board/esp32_devkit/src/esp32_lcd.c
os/board/esp32_devkit/src/heap_caps.c
os/crypto/blake2s.c
os/drivers/lcd/lcd_framebuffer.c
os/drivers/testcase/test_compress_decompress.c
os/logm/logm_process.c

Kernel modules should allocate the memory in kernel space for internal usages.
Let's use kmm APIs instead of memory allocation APIs for user.
This commit includes the change in arch, board, crypto, drivers and logm.

os: use kmm APIs

---

os/mm/mm_heap/mm_free.c

Before double free checking, we took semaphore for that heap. So before returning, we should give the semaphore.

mm/mm_heap/mm_free : Add givesemaphore before returning failure case

---

os/arch/arm/src/armv8-m/up_unblocktask_withoutsavereg.c

Fix typo from CONFIG_ARMV8_MPU to CONFIG_ARMV8M_MPU.

arch/armv8-m: Fix typo from CONFIG_ARMV8_MPU to CONFIG_ARMV8M_MPU

---

os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager_binfile.c
os/kernel/binary_manager/binary_manager_callback.c

Fix typo in binary_manager.c, binary_manager_binfile.c and binary_manager_callback.c

kernel/binary_manager : Fix typo

---

os/arch/arm/src/amebad/amebad_flash.c
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/flash_api.c

In amebad_flash.c:
1) Remove time consuming instructions like malloc and memcpy
2) Remove irqsave and alignment check as they are done in flash_api
In flash_api.c:
1) Using 256B programming unit instead of 12B to write large size data

arch/amebad: Flash performance improvement

---

apps/examples/stack_protection/stack_protection_main.c

This patch resolves unused variable warnings in stack protection test code.

apps/examples/stack_protection: Resolve warnings

---

os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c

os/fs/smartfs: Modify name of recovery info structure attribute
- Current name 'cleanentries' misguides the reader to believe
that it is the count of clean entries.
- Change the bame to 'cleanedentries' which identifies as the
count of entries cleaned during the recovery process.

os/fs/smartfs: Update variable names and add macros for frequently used long strings

---

lib/libc/netdb/lib_freeaddrinfo.c

It's dangerous to call assert(). furthermore linux doens't make
crash when freeaddrinfo() receive null. so libc prints error log
instead of calling assert()

libc/network: remove assert in freeaddrinfo()

---

lib/libc/stdio/lib_vasprintf.c
lib/libc/unistd/lib_execl.c

libc can be used from kernel and user, so it should use lib_Xalloc instead of Xalloc.

lib/libc : Modify malloc to lib_malloc in stdio and unistd

---

os/kernel/clock/clock_settime.c

Currently clock_settime calls up_rtc_settime with g_rtc_enabled conditional.
It means when we set the time, both system time and rtc time are set.
But there is no way to adjust system time alone. In our usage,
we get the time from server and then set the RTC time. Every few seconds,
we adjust system time using rtc time. But adjusting system time causes
rtc time re-setting. At that time, because of some additional code, rtc time
gets small time difference. It causes big time difference after few hours.
Let's make clock_settime to set system time only. When we want to set
RTC time, let's use RTC driver.

kernel/clock: remove up_rtc_settime in clock_settime

---

framework/src/preference/preference_init.c
os/include/tinyara/preference.h
os/include/tinyara/sched.h
os/kernel/group/group_create.c
os/kernel/preference/preference_common.c
os/kernel/preference/preference_remove.c
os/kernel/preference/preference_write.c

The values of private preference are managed by task group.
Each 'value' is saved in a file named 'key' and they are located in a directory /mnt/private/<tg_name>.

kernel/preference: Support private preference by task group

---

os/binfmt/libelf/libelf_read.c

- Add fix for below build warning:
-------------------------------------------------------
```
libelf/libelf_read.c: In function 'elf_read':
libelf/libelf_read.c:204:13: warning: 'nbytes' may be used uninitialized in this function [-Wmaybe-uninitialized]
readsize -= nbytes;
```
-------------------------------------------------------

os/binfmt/libelf/libelf_read.c: Fix build warning

---

os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_recovery.c

Set OK value on success in binary_manager_execute_loader and fix condition for checking result returned from it.

kernel/binary_manager: Set OK value on success in binary_manager_execute_loader

---

os/arch/arm/src/amebad/Kconfig

RDP key value is not set properly resulting in below build error.
Set proper HEX value for RDP KEY.
========== Image manipulating start ==========
========== RDP Encryption ==========
*** Error in `./EncTool': munmap_chunk(): invalid pointer: 0x00007ffffa43eb30 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffa421057e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7ffa42112698]
./EncTool(+0x1483f)[0x5619b7cd183f]
./EncTool(+0x14956)[0x5619b7cd1956]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ffa420ae830]
./EncTool(+0xd8a)[0x5619b7cbdd8a]

arch/arm/src/amebad: Fix build error for RDP config

---

os/arch/arm/src/armv7-m/arch_clean_dcache_by_range_to_poc.c
os/arch/arm/src/armv7-m/arch_clean_invalidate_dcache_by_range_to_poc.c
os/arch/arm/src/armv7-m/cache.h

-IMXRT USB Host driver requires to flush and invalid the dcache specific region, added
two api to handle this requirement as currently this is not supported.
This requirement is from NXP to support USB Host driver, and is part of the release from NXP

arch/arm/src/armv7-m: Add support for clean & invalidate api for a specific region of dcache

---

os/arch/arm/src/common/up_checkspace.c
os/include/tinyara/arch.h
os/include/tinyara/binfmt/binfmt.h
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_recovery.c

If a fault happens in common library, All user binaries and library are reloaded.
So all RT threads of all binaries should be deactivated in fault handler.

kernel/binary_manager: Deactivate RT threads of all binaries in fault handler

---

os/se/ameba/rtl_security_api_wrapper.c
os/se/ameba/security_ameba_wrapper.c

1. Resolve compile error by adding include semaphore.h
2. Fix key index convert, array index start from 0, key index start from 1
3. Added rtl_write_factory_cert_wrapper() API for future reference

se/ameba: Resolve compile error, and index problem for SE non-secure

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c

- Removed 3 mpu setting "close 216K irom_ns cache", "close 80K drom_ns cache" and "set 1KB retention ram no-cache"
- Added PSRAM mpu setting "set PSRAM Memory Write-Back", to prevent data confusion issue in PSRAM

os/board/rtl8721csm: Remove unneeded RTL mpu setting

---

os/arch/arm/src/armv8-m/up_svcall.c

The tz_context type is TZ_ModuleId_t which is the same as uint32_t.
So, null is not proper. This causes build warning as below:
CC:  armv8-m/up_svcall.c
armv8-m/up_svcall.c: In function 'up_svcall':
armv8-m/up_svcall.c:571:20: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
rtcb->tz_context = NULL;
^
Let's change the value to 0 to resolve above.

arch/armv8-m: modify tz_context initialization value to 0 in up_svcall.c

---

os/kernel/group/group_leave.c

A group_leave function is called when a task or thread exits.
It decrements the reference count of the group and frees all resources of group if the reference count is zero.
Then a group is detached from the tcb regardless of reference count to avoid doing this again.

kernel/group: Always detach the group from the tcb if the tcb has a group

---

loadable_apps/loadable_sample/micomapp/micomapp.c
loadable_apps/loadable_sample/wifiapp/wifiapp.c
os/kernel/binary_manager/binary_manager_recovery.c

1. Every 10 sec, micom and wifi binaries prints the alive message.
It's not good to use TASH.
Let's adjust the period from 10 secs to 5 mins.
2. The binary_manager_reset_board() resets the board when CONFIG_BOARDCTL_RESET
is enabled, but it just waits after printing the message every 10 sec with
CONFIG_BOARDCTL_RESET disabled.
Message at every 10 sec disturbs checking the debug messages.
Let's increase the period from 10 secs to 5 mins.

binary_manager, micomapp and wifiapp: adjust the period of alert message

---

os/arch/arm/Kconfig

Even a board supports FPU, it's not mandatory feature.
It might cause performance degradation so that it should be
defaultly disabled. When it needs, we can enable.

arch/arm: set the default value of FPU config as n

---

.travis.yml

remove env for travis
remove list,
- env: BUILD_CONFIG=artik053/iotjs	
- env: BUILD_CONFIG=artik053/minimal	
- env: BUILD_CONFIG=qemu/tc_64k

remove env for travis

---

os/arch/arm/src/amebad/amebad_enet.c
os/arch/arm/src/amebad/amebad_serial.c
os/arch/arm/src/amebad/amebad_start.c
os/board/rtl8721csm/src/component/common/api/network/src/wlan_network.c
os/board/rtl8721csm/src/component/common/api/wifi/rtw_wpa_supplicant/wpa_supplicant/wifi_wps_config.c
os/board/rtl8721csm/src/component/common/api/wifi/wifi_util.c
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/sys_api.c
os/net/netmgr/netdev_lwip.c

RTL8721CSM configs loopback disable. 1st commit for the modification of all defconfigs, fix netdev_lwip.c Macros, _netif_loop_output_ipv4 and _netif_loop_output_ipv6 are not defined if LWIP_HAVE_LOOPIF is 0.

[Realtek][RTL8721CSM] net/netmgr/ : RTL8721CSM loadable apps config bus fault fix

---

apps/examples/performance/syscall/syscall_performance_main.c

Each test can be interfered by another threads because of scheduling.
For precise performance measurement, lock the scheduling on every tests.

apps/performance/syscall : Add sched lock and unlock for every tests

---

os/arch/arm/src/armv8-m/up_mpu.c

The syscall performance is poor since we are using no cache setting
in MPU. Change this to write back cache setting to improve performance.
Below is the performance comparison for both cases:
Syscall performance
Syscall type	| No cache case	| With WB cache case
syscall 0	| 52 secs	| 2 secs
syscall 1	| 59 secs	| 2 secs
syscall 2	| 51 secs	| 2 secs
syscall 3	| 184 secs	| 37 secs
syscall 4	| 57 secs	| 8 secs
syscall 5	| 66 secs	| 8 secs
syscall 6	| 282 secs	| 23 secs
Average context switch time
No cache : 138 usecs
WB cache : 19 usecs

arch/arm/armv8-m : Fix performance issue due to cache setting

---

os/arch/arm/src/armv8-m/up_unblocktask.c
os/arch/arm/src/armv8-m/up_unblocktask_withoutsavereg.c

During context switch, the secure context store is not happening sometimes.
Load secure context is getting called repeatedly without corresponding calls
to score secure context. This is resulting in corruption of secure area PSP.
The issue is fixed by making sure that secure context is stored for each
task which is switched OUT during a context switch.

arch/armv8-m : Fix Security test hang issue

---

apps/examples/stack_protection/Kconfig
apps/examples/stack_protection/stack_protection_main.c
os/drivers/kernel_test/Make.defs
os/drivers/kernel_test/kernel_test_drv.c
os/drivers/kernel_test/kernel_test_proto.h
os/drivers/kernel_test/test_kthread_stack_protection.c
os/include/tinyara/kernel_test_drv.h

- This PR adds testcase for verifying if Stack Overflow Protection feature works for Kernel thread as well.
- From Application, user is provided option for which feature of Stack Protection to test for Kernel thread.
- Application side code at -> apps/examples/stack_protection
- Testcase driver side code at -> os/drivers/testcase/
Result looks like below:
----------------------------------------------------
```
TASH>>stack_prot
Stack Overflow Protection testcase!!
Press U - Test Stack Protection for User Thread
Press K - Test Stack Protection for Kernel Thread
Press E - Exit the Test ..
Testing for Kernel Thread !!
Press M - Test Stack protection with MPU
Press E - Exit the Test ..
Press N - Test Stack access within range
Press O - Test Stack access in overflow
Press E - Exit the Test .. …
```

Kernel Thread Stack Overflow Protection Testcase

---

os/arch/arm/src/common/up_createstack.c

kernel_thread() API only uses kernel heap regardless of calling from where.
so add type checking for where to allocate stack memory.

arch/arm/common/up_createstack : Add condition for checking kernel heap

---

os/arch/arm/src/common/up_createstack.c
os/arch/arm/src/common/up_mpuinit.c
os/binfmt/binfmt_execmodule.c
os/binfmt/binfmt_loadbinary.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c
os/include/tinyara/mpu.h

This PR adds support to reserve MPU regions by the vendor. (CONFIG_MPU_RESERVED)
In such a scenario, the TizenRT MPU configurations will be done past the reserved MPU regions.
It adds the following API's to mpuinit.c
mpu_get_region_info(), mpu_set_region_info(), mpu_regs_initialize()

Reserve MPU regions

---

os/arch/arm/src/armv7-m/up_blocktask.c
os/arch/arm/src/armv7-m/up_mpu.c
os/arch/arm/src/armv7-m/up_releasepending.c
os/arch/arm/src/armv7-m/up_reprioritizertr.c
os/arch/arm/src/armv7-m/up_schedyield.c
os/arch/arm/src/armv7-m/up_svcall.c
os/arch/arm/src/armv7-m/up_unblocktask.c
os/arch/arm/src/armv7-m/up_unblocktask_withoutsavereg.c
os/arch/arm/src/armv8-m/up_mpu.c
os/arch/arm/src/armv8-m/up_releasepending.c
os/arch/arm/src/armv8-m/up_reprioritizertr.c
os/arch/arm/src/armv8-m/up_schedyield.c
os/arch/arm/src/armv8-m/up_svcall.c
os/arch/arm/src/armv8-m/up_unblocktask.c
os/arch/arm/src/armv8-m/up_unblocktask_withoutsavereg.c
os/arch/arm/src/common/up_mpuinit.c
os/binfmt/binfmt_loadbinary.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c
os/include/tinyara/mpu.h
os/include/tinyara/sched.h
os/kernel/task/task_setup.c
os/kernel/task/task_terminate.c
os/kernel/task/task_terminate_unloaded.c

1. Rename the definitions
REG_XXX -> MPU_REG_XXX
2. Use the definition instead of hard-coded value
3 -> MPU_REG_NUMBER
3. Add and fix the comments

mpu: tidy-up naming and comment

---

os/kernel/binary_manager/binary_manager_load.c

For reloading, CONFIG_BINMGR_RECOVERY is needed.
If not, LOADCMD_RELOAD makes build error.

kernel/binary_manager_load : Add ifdef for reload case

---

build/configs/rtl8721csm/rtl8721csm_download.sh

When enabling trustzone, km4_boot_all_tz.bin should be downloaded instead of km4_boot_all.bin.

build/rtl8721csm/download.sh : Add km4_boot_all_tz.bin download option

---

os/mm/mm_heap/mm_initialize.c
os/mm/mm_heap/mm_realloc.c

MM_ALIGN_UP do an unsafe calculation that can cause integer wrap-around.
For avoiding integer wrap-around, check the size whether it is smaller than possible allocation size.

mm/mm_heap/mm_realloc : Add logic for checking overflow of size

---

os/arch/arm/src/amebad/amebad_flash.c

RTL8721x didn't implement bytewrite, so add it to increase performance

arch/amebad/flash : Apply bytewrite function

---

os/net/netmgr/netmgr_ioctl_lwip.c

netdev_ioctl() converts lwIP data type to socket data type to pass the
result of getaddrinfo(). but it doesn't free lwip data type moreover doesn't free it's member data.

network/libc: fix getaddrinfo memory leak.

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c

With PSRAM MPU setting, binary manager cannot load the user binary.
So temporarily disable PSRAM MPU setting.

board/rtl8721csm/app_start.c : Disable PSRAM MPU setting

---

os/drivers/gpio/gpio.c
os/drivers/lwnl/lwnl.c

Check if this file is registered in a list of waiters for polling.
It it is, the used slot should be cleared.
Otherwise, a invalid pollfd remains in a list and this slot is not available forever.

drivers: Clear the registered waiters for polling when closing filep

---

os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c

Change key_id from 1 to 0 for WEP shared key auth method connection according to RTK default SDK setting, also to fix connection issue found in compatibility test.

board/rtl8721csm: Change key_id used for WEP shared key auth method to 0

---

os/binfmt/binfmt_execmodule.c
os/binfmt/binfmt_unloadmodule.c

- Fix bugs about variable definition
- Build error/warning logs
binfmt_unloadmodule.c: In function 'unload_module':
binfmt_unloadmodule.c:156:6: warning: unused variable 'section_idx' [-Wunused-variable]
int section_idx;
^~~~~~~~~~~
CC:  binfmt_execmodule.c
binfmt_execmodule.c: In function 'exec_module':
binfmt_execmodule.c:201:52: error: 'nregion' undeclared (first use in this function)
mpu_get_register_config_value(&rtcb->mpu_regs[0], nregion - 1, (uintptr_t)binp->ramstart, binp->ramsize, false, true);

binfmt: Fix bugs about location of variable definition

---

os/binfmt/binfmt_execmodule.c
os/include/tinyara/sched.h
os/kernel/task/task_setup.c

ram_start in tcb is not needed anymore, because we allocate the loading app with its own way.

kernel : Remove unnecessary variable in tcb - ram_start

---

os/binfmt/libelf/libelf_addrenv.c
os/include/tinyara/mpu.h

1) MPU_ALIGNMENT_BYTES and MPU_ALIGN_UP are used only with armv8m mpu.
2) Calculation of each section size has dependency with architecture, but the allocation for those section has dependency with CONFIG_BINFMT_SECTION_UNIFIED_MEMORY.

os/binfmt/libelf : Fix wrong condition for MPU-related defines and codes

---

os/drivers/gpio/gpio.c
os/drivers/lwnl/lwnl.c

Store filep when file is registered in a list of waiters for polling and check it when closing filep.

drivers: Store filep to distinguish fds of poll waiter slots

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c

Fix compile error when TrustZone not enable, do not call mpu_s_no_cache_init() when TrustZone is not enable.
mpu_s_no_cache_init() only exist in TrustZone

os/board/rtl8721csm: Fix compile error when TrustZone not enable

---

os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_load.c

A size of buffer affects loading time because the number of read operations varies depending on it.
So Set a buffer size according to each binary to enough large value instead of fixed size.

kernel/binary_manager: Optimize a buffer size for checking crc value

---

os/arch/arm/src/armv8-m/up_svcall.c

This patch fixes the following build break:
armv8-m/up_svcall.c: In function 'up_svcall':
armv8-m/up_svcall.c:277:23: error: 'tcb' undeclared (first use in this function)
up_mpu_set_register(tcb->stack_mpu_regs);
^~~

arch/arm/src/armv8-m: Fix build break with MPU Stack protection enabled.

---

loadable_apps/loadable_sample/wifiapp/wifiapp.c

WID:10253106 Integer value received from 'fgetc' can't be safely converted to a character at wifiapp.c:89 without a test for EOF.

loadable_apps/wifiapp : Change user input variable type from char to int

---

os/fs/driver/mtd/smart.c
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c
tools/nxfuse/src/filemtd.c
tools/nxfuse/src/main.c
tools/nxfuse/src/nxfuse.h
tools/nxfuse/src/tinyara_services.c

- Fix - possibly uninitialized variable 'nxfuse_data' passed to fuse_main()
- Fix - check possible NULL return value of recall before deferencing pointer
- Fix - file opened but not closed before returning in error case
- Fix - use 'strncpy' instead of 'strcpy' for safety
- Fix - possibly unreachable code
- Fix - result of mathematical operation subject to overflow
- Fix - Possible underflow of integer during unsigned subtraction
- Fix - Assignment of signed int to bigger unsigned int without proper casting (added explicit type casting)

Fix Svace errors - FS

---

os/fs/driver/mtd/smart.c

Sometimes there is invalid journal which has checkin state but not checkout in the middle of journal list.
In this case last_recovery_seq is changed to sequence of invalid journal, then corrupt happend due to overwrite exist journals.
Hence fix it

smartfs/journaling : Do not update last_recovery_seq if recovery failed

---

loadable_apps/loadable_sample/wifiapp/binary_update.c

Change update aging test to make micom update instead of wifi.

loadable_apps/binary_update: Change a scenario of update aging test

---

external/mbedtls/alt/pk_wrap_alt.c

there're two location to set key index in ecp_keypair. this should be
fixed later.

network/tls: fix ecdsa HW acceleration

---

build/configs/rtl8721csm/rtl8721csm_download.sh

In build-time, the name of km4 image is set to km0_boot_all.bin regardless of trustzone in rtl8721csm_make_bin.sh.
Remove checking filename according to trustzone in download script.

configs/rtl8721csm: Remove checking filename according to trustzone in download script

---

os/board/rtl8721csm/src/component/os/tizenrt/tizenrt_service.c

Modification for easy setup example performance, revert the changes made for tizenrt os delay API usage in previous PR, change back to up_mdelay and up_udelay.
Signed-off-by: fengyunlai <1063072208@qq.com>

board/rtl8721csm/src/component/os/tizenrt: Modification for easy setup example performance.

---

os/fs/driver/mtd/smart.c

If there are duplicated sector due to sudden power off, smart_scan checks
sequence value to determine winner and loser.
Based on crc, it checks 16bits or 8bits value.
This is came from nuttx's fixing

fs/smartfs : Fix logic of smart_scan regarding selecting winner

---

os/arch/Kconfig
os/arch/arm/src/common/up_allocateheap.c
os/binfmt/libelf/libelf_addrenv.c
os/include/tinyara/mm/mm.h

Load apps into single RAM region to make sure that all app sections are within 32MB address range.
Modify defconfig to use 2 heaps to allow the above change

Load apps into single RAM region

---

os/fs/driver/mtd/smart.c

To split the arguments, comma should be used.
fdbg(".." - ret, ..); => fdbg("..", ret, ..);

fs/mtd/smart: fix typo, - => ,

---

os/kernel/debug/memdbg.c

1) If kmm_region is greater than 1, there was no information for every region.
2) Change mllvdbg to mllwdbg

kernel/debug/memdbg : Add debug message for every regions

---

os/fs/tmpfs/fs_tmpfs.h

kmm_malloc can be matched with kmm_malloc_at, instead of malloc_at for allocating the memory into the kernel.

fs/tmpfs : Change wrong memory allocation usage

---

os/mm/umm_heap/umm_mallinfo.c

When CONFIG_APP_BINARY_SEPARATION, user heap only can be single heap.

mm/umm_mallinfo : Use First heap only when binary separation

---

os/arch/arm/src/amebad/amebad_flash.c
os/board/rtl8721csm/src/component/common/mbed/hal_ext/flash_api.h
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/flash_api.c

If sudden power off happened during erase, sometimes target pages are not erased properly.
In product level, level of voltage can be increase for a while, then fs could treat it is correct.
To prevent this situation, verify logic must be added

arch/amebad/flash : Add function to verify erased page

---

build/configs/rtl8721csm/hello/Make.defs
build/configs/rtl8721csm/loadable_apps/Make.defs
build/configs/rtl8721csm/rdp/Make.defs
build/configs/rtl8721csm/security_hal_test_tz/Make.defs
build/configs/rtl8721csm/tc/Make.defs
os/tools/mkconfig.c
tools/dump_tool/HowToUseDumpTool.md
tools/dump_tool/dump_tool.c

- ARM Cortex M devices do not support register for frame pointer backtracking.
Hence, build fails when CONFIG_FRAME_POINTER is selected.
Add flag to omit frame pointer while building for rtl8721csm.
- For such cases, it is not possible to obtain exact call stack for the crash.
- Modify flash base address of rtl8721csm to proper value.
- Add NOTE to "How-To" file for dumps to declare limitation for ARM Cortex M devices.
- Modify formatting of filesystem start address print output to console.

Update Dump Tool (Realtek - rtl8721csm)

---

tools/memory/g_var_profiler.sh

Current g_var_profiler.sh should get arguments at fixed order.
For example, to give elf path, user should give size first.
There is no way to give ELF alone.
New way is giving argument with '-' option like
-s 1024 for the size
-e ../bin/tinyara for the elf
-o variable_list.txt for the output file
It allows single argument without the sequence.

tool/memory: change usages of g_var_profiler.sh to '-' option

---

tools/memory/HowToUseGlobalVariableProfiler.md
tools/memory/g_var_profiler.sh

1. tools/memory: check existence of default ELF 
When ELF option is not specified by user to g_var_profiler.sh, default ELF binary is used.
But in some board default ELF binary is not built resulting into empty output file by the script.
To avoid above scenario, we will check pre-existence of ELF binary.
2. tools/memory: add README for g_var_profiler.sh

tools/memory: add README and add file existence check

---

os/include/tinyara/mm/mm.h
os/mm/mm_heap/mm_heapinfo_parse_heap.c
os/mm/mm_heap/mm_heapinfo_utils.c

total_info indicates the whole heap information. But it is duplicated info with free commands, and it can be calculated from each heap info.
So removed it.

mm/mm_heap/mm_heapinfo : Remove total_info

---

os/kernel/init/os_bringup.c

Changed heapinfo_drv.h to mminfo.h for mminfo_register.

kernel/init: Fix wrong include header file for mminfo

---

os/kernel/debug/Make.defs
os/kernel/debug/memdbg.c
os/kernel/init/os_start.c

1) memdbg is only meaningful when CONFIG_DEBUG_MM_WARN is enabled.
2) Modify comment about heap configuration

os/kernel/debug/memdbg : Add build condition when CONFIG_DEBUG_MM_WARN is enabled

---

docs/APIListToBePorted.md
docs/Porting_Guide.md

Our porting guide does not provide entire api list to be ported
This document provides the api list, references, file location
and header file which has the API prototypes.
A link to the document has also been added to the TizenRT PortingGuide.

docs: Add API list to be ported.

---

os/mm/kmm_heap/kmm_mallinfo.c
os/mm/umm_heap/umm_mallinfo.c

If passed 'info' is NULL, mallinfo cannot work properly.
But it is checked only when the build type is not binary separation.
So moved up for checking every cases.

os/mm/umm_mallinfo : Move param null checking

---

os/board/rtl8721csm/src/component/os/tizenrt/tizenrt_service.c
os/drivers/memory/mminfo.c

1) tizenrt_service.c : Delete wrong comment
2) mminfo.c : ioctl is for mminfo, not heapinfo

os : Delete/Fix wrong comment

---

os/include/tinyara/mminfo.h

BIN_NAME_MAX is declared in binary_manager.h, but there is no header include when DEBUG_MM_HEAPINFO and APP_BINARY_SEPARATION are enabled.

include/tinyara/mminfo.h : Add conditions for BIN_NAME_MAX

---

build/configs/rtl8721csm/rtl8721csm_download.sh

There are SE partitions which have the type as none.
We don't need to download the none type, so skip them.

build/configs/rtl8721csm_download.sh : Skip to try download for SE

---

build/configs/rtl8721csm/hello/defconfig
build/configs/rtl8721csm/loadable_apps/defconfig
build/configs/rtl8721csm/rdp/defconfig
build/configs/rtl8721csm/rtl8721csm_download.sh
build/configs/rtl8721csm/security_hal_test_tz/defconfig
build/configs/rtl8721csm/tc/defconfig

1. config/rtl8721csm/download.sh: skip non-binary partition 
2. configs/rtl8721csm/*: set partition name for secure storage

configs/rtl8721csm: set secure storage partition name and skip that at download

---

os/board/common/crashdump.c
tools/dump_tool/HowToUseDumpTool.md
tools/dump_tool/dump_tool.c
tools/dump_tool/dump_tool.h
tools/dump_tool/dump_tool.sh
tools/dump_tool/dumping_protocol.txt

- Add smart MTD ioctl to retrieve all smartfs sectors for
corresponding partition identifier.
- Add option to dump tool interface to dump external
userfs partition.

Add functionality to dump Userfs partition from External Flash

---

os/drivers/kernel_test/kernel_test_drv.c

Get an address of uheap from tcb structure instead of BIN_LOADINFO.
That's because a BIN_LOADINFO() is defined when CONFIG_OPTIMIZE_APP_RELOAD_TIME is enabled only.

drivers/kernel_test: Get an address of uheap from tcb structure instead of BIN_LOADINFO

---

apps/system/utils/utils_heapinfo.c
apps/system/utils/utils_kill.c
os/kernel/messaging/messaging.c

Fix string copy size and add '\0' to the end of string array for security issue.

heapinfo, messaging : Fix copy size and add '\0' to the end of string array

---

os/arch/arm/src/amebad/amebad_irq.c
os/arch/arm/src/armv8-m/up_hardfault.c
os/arch/arm/src/armv8-m/up_memfault.c

In every fault cases, write the reboot reason as prefetch abort before calling PANIC.

arch/arm/amebad_irq : Add reboot reason write for every fault cases

---

apps/examples/telnetd/telnetd.c
apps/shell/Kconfig
apps/shell/tash_command.c

Currently TASH uses global array variable to save the command.
It sets the size from the config to get the maximum number of command.
But it's not good due to belows.
1. User should consider the maximum number of shell commands.
When user enables more application or utils, then user should check it.
It's much uncomfortable.
2. When user does not use it fully, it wastes memory.
3. Usually global variables are located in internal RAM which has fastest performance.
But shell command itself does not require performance.
And this takes memory even TASH is exited.
This commit changes that TASH dynamically allocates memory for the commands instead of
using global array variable.

apps/shell, telnetd: dynamically allocate shell command buffer

---

build/configs/rtl8721csm/hello/defconfig
build/configs/rtl8721csm/loadable_apps/defconfig

Enable CONFIG_DEBUG and CONFIG_DEBUG_ERROR for rtk defconfigs.
If this is not enabled, all the faults such as memfault, busfault,
etc are treated as unexpected irq and we dont get debug information
for them. These configs were previously disabled for wifi perf
issue, and since we found that wifi perf is not related to these
configs, we are re-enabling them.

configs/rtl8721csm: Enable debug configs for rtk

---

os/kernel/binary_manager/binary_manager_data.c

This commit is for crash issue in network_tc pthread. It is observed that
there is a busfault while running net_sendto_main(). This API creates some
pthreads. If we add some print statements in the pthread, then crash is not
reproduced. It is found from analysis that the crash is happening due to
NULL pointer access in binary_manager_add_binlist. This is because, the pthread
seems to have exited before the binary_manager_add_binlist() is called, and
hence the tcb->group member is NULL.
In order to fix this issue, we perform NULL check in binary_manager_add_binlist
and if group member in tcb is null, then we do not need to add the tcb to the
app's thread list.

os/kernel/binary_manager: Add NULL check in binary_manager_add_binlist

---

apps/examples/reboot_reason_test/.gitignore
apps/examples/reboot_reason_test/Kconfig
apps/examples/reboot_reason_test/Kconfig_ENTRY
apps/examples/reboot_reason_test/Make.defs
apps/examples/reboot_reason_test/Makefile
apps/examples/reboot_reason_test/reboot_reason_main.c
os/arch/arm/src/amebad/amebad_reboot_reason.c
os/include/tinyara/reboot_reason.h

There are 5 options for testing reboot reason functionality.
1) hw reset
2) memory allocation fail
3) watchdog reset
4) temporary value write
5) clear the reboot reason

apps/examples/reboot_reason_test : Add reboot reason sample

---

os/tools/build_test.sh

Current build script tries to build many configurations automatically.
But when there is a fail, build is not stopped and continue to the next.
So when there is a fail, stop the build and show where the build error is come from.

os/tools/build_test.sh : Add error check when build fail

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-m/up_hardfault.c
os/arch/arm/src/armv7-m/up_svcall.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/armv8-m/up_hardfault.c
os/arch/arm/src/armv8-m/up_svcall.c
os/include/tinyara/mm/mm.h
os/mm/mm_heap/Make.defs
os/mm/mm_heap/mm_check_heap_corruption.c
os/mm/mm_heap/mm_heapinfo_parse_heap.c
os/mm/mm_heap/mm_mallinfo.c

Heap corruption can happen when a node overflows into next node
in the heap list. However, even when heap is corrupted, the system
can run properly for some time. So, we provide heap corruption check
in following ways:
- Add heap corruption check api as part of heapinfo
- If heapinfo is not enabled, then we dont have any information about
the owner process of the heap node which caused the corruption.
- When user calls heapinfo for any app or kernel, the corresponding
heap is checked for corruption. All details about corruption are printed.
- When mallinfo api is called, heap corruption is checked and printed.
- In both cases, we will not ASSERT because, even with heap corruption,
the system can continue to operate unless the corrupted node is accessed.
- However, if the system gets …

New method to debug heap corruption

---

apps/examples/wifi_manager_sample/wm_test.c
os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c

Fix 2 parts: 1. wep_shared key not only support ASCII password, but also HEX password, while checking password length, add conditions.
2. In wifi_interactive_mode.c, cmd_wifi_connect() checked AES and auth type match. It is okay to skip, delete it to keep it same as RTK default wifi_interactive_mode.c, if keep this check, need to add for wpa, wpa12, wps for all cases.

apps/examples/wifi_manager_sample/wm_test.c: Fix auth type specified wm_test join issues.

---

os/se/ameba/rtl_security_api_wrapper_tz.c

- Add SE Secure Storage Write Protect for Flash first 512K bytes
- Flash Write protect will be enable when DA AES key is written in efuse

/se/ameba: Add RTL SE Secure Storage Write Protect

---

os/arch/arm/src/amebad/Make.defs
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/common/up_reboot_reason.c

1) reboot_reason_trywrite checks that there is already written reboot reason. If no, write REBOOT_SYSTEM_USER_INTENDED.
2) In up_assert, if there is user intended assert, not data abort or prefetch abort, calls reboot_reason_trywrite().

arch/arm : Add reboot_reason_trywrite in up_assert

---

apps/examples/reboot_reason_test/reboot_reason_main.c

For testing prefetch abort reboot reason, make usagefault intentionally.

apps/examples/reboot_reason_test : Add Prefetch Abort Test

---

os/arch/arm/src/stm32l4/stm32l4_irq.c

This patch updates the stm32l4 board interrupt conditional with
appropriate arm cortex flag for unification across different chipsets.

arch/arm/src/stm32l4: Update arm conditional flag for stm32l4 board.

---

docs/HowToPortTizenRTBinaryHeader.md
docs/Porting_Guide.md

This patch adds Binary Header guide to the document.
It also explains the various partitions in the flash.

docs: Add Binary Header guide to the porting guide.

---

os/arch/arm/src/amebad/amebad_irq.c
os/arch/arm/src/imxrt/imxrt_irq.c
os/arch/arm/src/imxrt/imxrt_lowputc.c
os/arch/arm/src/imxrt/imxrt_lowputc.h
os/arch/arm/src/stm32/stm32_irq.c
os/arch/arm/src/stm32l4/stm32l4_irq.c
os/arch/arm/src/tiva/tiva_irq.c

1. Enable lldbg logs during crash in imxrt without CONFIG_DEBUG
2. Move memfault, busfault and usagefault handlers out of CONFIG_DEBUG

os/arch/arm/src : Move memfault, busfault and usagefault handlers out of CONFIG_DEBUG

---

os/tools/mkbinheader.py

Hard coded path "/root/..." is valid only in some environment. We should not
use it. And there are many duplicated getting config path.
This commit removes duplicated and get the path of .config file from TOPDIR env.

os/tools: modify a way to get the path of .config

---

os/net/lwip/configs/Kconfig
os/net/lwip/configs/icmp6/Kconfig
os/net/lwip/configs/nd/Kconfig

ICMPv6 and neighbor discovery don't have type. so it was removed after
menuconfig.

network/lwip: fix ipv6 kconfig

---

os/net/lwip/src/core/ipv6/nd6.c

This commit fixes violation of coding rule. The else conditional has no statement.
Let's remove it.
os/net/lwip/src/core/ipv6/nd6.c:2245: ERROR: [BRC_M_SMT] else should follow close brace '}'

net/lwip/ipv6: fix coding rule violation

---

apps/examples/wifi_manager_sample/wm_test.c

- wm_test doesn't suuport enterprise auth.

examples/wifi_manager_sample: apply wifi auth policy

---

apps/examples/wifi_manager_sample/wm_test.c

1) WID:10637402 Use of vulnerable function 'strcat' at wm_test.c:366. This function is unsafe, use strncat instead.
2) Revert partial of 143ea06 about unreachable code

apps/wifi_manager_sample/wm_test : Change strcat to strncat

---

external/netutils/netlib_getifaddrs.c

The function exits without closing opened fd when write is failed.
It causes memory leak. This commit closes opened fd at every exit.

external/netutils: close opened fd before exit

---

apps/system/sysinfo/sysinfo.c

Recently CONFIG_BINARY_VERSION was added. Let's print it in system information.

apps/sysinfo: add Binary version in system information

---

os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/flash_api.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_common/rtl8721d_flash_ram.c

1. Add flow control mechanism on 256BWrite function 
2. Move the new 256BWrite function to RAM 
3. Use the updated function instead of FLASH_TxData256B in flash_stream_write

board/rtl8721csm/flash: Add flow control mechanism for 256BWrite

---

build/configs/rtl8721csm/rtl8721csm_download.sh

The logs of flash partition information was not aligned for each like below.
```
===================================================================================
PARTITION NAMES: 	km0_bl		km4_bl		reserved		ss		system_data		kernel		kernel		userfs
PARTITION SIZES: 	16		8		16		472		8		1792		1792		1048
PARTITION OFFSETS:  0x8000000  0x8004000  0x8006000  0x800A000  0x8080000  0x8082000  0x8242000  0x8402000
===================================================================================
```
This commit aligns the logs of each partition like below.
```
================================ < Flash Partition Information > ================================
NAME       :        km0_bl        km4_bl      reserved            ss   system_data        kernel        kernel        userfs
SIZE(in KB): …
```

configs/rtl8721csm/download.sh: align partition information logs

---

os/fs/smartfs/smartfs_utils.c

Code related to sector recovery was under CONFIG_FS_PROCFS condition,
adjust it.

fs/smartfs : Fix wrong CONFIG condition

---

os/board/artik05x/src/artik05x_tash.c
os/board/common/common.h
os/board/common/partitions.c
os/board/imxrt1020-evk/Kconfig
os/board/imxrt1020-evk/src/imxrt_bringup.c
os/board/imxrt1050-evk/src/imxrt_bringup.c

Timezone uses romfs, so romfs should be mounted before using.
There is automount_fs_partition(), so merge the timezone automount into that.

board/common : Merge timezone automount

---

apps/examples/testcase/le_tc/drivers/tc_rtc.c

The struct rtc_time has tm_mday, tm_min and tm_sec also.
So initialize their value before setting the rtc.

apps/examples/testcase/tc_rtc : Add missed rtc time value

---

apps/system/utils/Kconfig
os/net/lwip/configs/Kconfig

1. net/lwip/config: remove typo in Kconfig
2. apps/system/utils: tidyup ENABLE_IRQINFO dependencies

lwip, utils: fix Kconfig warnings

---

apps/examples/testcase/le_tc/kernel/tc_libc_misc.c

llvdbg is valid when CONFIG_DEBUG_VERBOSE is enabled.
But that tc is not under proper conditional.
Let's move it under proper conditional to resolve the build break.
CC:  le_tc/kernel/tc_libc_misc.c
le_tc/kernel/tc_libc_misc.c: In function 'tc_libc_misc_llvdbg':
le_tc/kernel/tc_libc_misc.c:363:30: error: expected expression before ';' token
ret_chk = llvdbg("Examples");
^
make[2]: *** [tc_libc_misc.o] Error 1

examples/testcase/kernel: fix build error on tc_libc_misc.c

---

os/kernel/Kconfig
os/kernel/clock/clock_initialize.c

When boot up, set the system init time based on CONFIG_VERSION_BUILD_TIME.

kernel/clock : Update the system init time based on build time

---

apps/examples/testcase/le_tc/drivers/tc_rtc.c
lib/libc/time/lib_calendar2utc.c

tc_rtc fails for settime and rdtime ioctl. This is because, we set
year value as 3. According to unix standard, this value is considered
as year 1903, which is in turn less than EPOCH year of 1970. In such
case, we need to follow unix standard and add 100 to the year value.
So, all year values from 1900 to 1969 will be converted to 2000 to
2069. We update the tc_rtc accordingly.

lib/libc: Fix testcase failure in tc_rtc

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/mm/mm_heap/mm_check_heap_corruption.c

Recursive abort issue happened since the first assertion was caused
due to invalid heap semaphore, and in assert handler we again try
to check heap corruption which will try to aquire the invalid heap
semaphore. Modify heap corruption check to NOT use semaphore during
abort_mode. Also, we would like heap check to run always in case of
assert, irrespective of whether somebody else is holding the sem.

os/arch/arm: Prevent recursive abort due to heap check

---

os/board/common/partitions.c

1) mount() is used not only AUTOMOUNT_ROMFS but also LIBC_ZONEINFO_ROMFS.
So change ifdef condition for including sys/mount.h
2) For mksmartfs(), include mksmartfs.h

board/common/partitions.c : Include header for mount() and mksmartfs()

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

Fix the issue: Cannot type the password in Easy setup due to the incorrect AP scan result.
Add the missing security types in scan result handler.

Sdaiot 98 fix scan type missing issue

---

os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c

- When multiple files are opened at once without writing anything,
temporary buffer entry gets overwritten.
- Hence, only the last of new file entries is synced to MTD.
- Change method so that new file entries are written instantly to
MTD without holding for smartfs_sync_internal().

os/fs/smartfs: Fix inconsistency while opening multiple files at once

---

lib/libc/string/lib_strlen.c

If passed param 's' is NULL, it cannot be calculated.
So add null checking.

libc/lib_strlen : Add NULL check for string

---

apps/examples/testcase/le_tc/drivers/tc_rtc.c

1) After running rtc tc, it unlinks the rtc driver.
In this case, we cannot use rtc anymore.
So remove unlink when finishing rtc tc.
2) The 3rd param of ioctl is unsigned long type, so add typecasting for build warning.

apps/testcase/tc_rtc.c : Remove unnecessary rtc unlink

---

os/se/ameba/security_ameba_wrapper_tz.c

The type of factory key which is injected in slot 1 is AES 128.
So this slot key type should be HAL_KEY_AES_128.

se/ameba : Change factory key type of slot 1 to HAL_KEY_AES_128

---

os/kernel/clock/clock_initialize.c

tm_isdst in init_time variable is used from mktime when CONFIG_LIBC_LOCALTIME is enabled.
Without initialization, it can have trash variable, so it can make wrong calculation in mktime.

kernel/clock_initialize : Add initialization of init_time

---

os/mm/mm_heap/mm_calloc.c

The size which is n * elem_size can be integer wrap-around.
In this case, mm_calloc tries to allocate wrong, small memory and user can access invalid memory.

mm/mm_heap/mm_calloc : Check integer wrap-around

---

os/arch/arm/src/common/up_allocateheap.c
os/arch/xtensa/src/esp32/esp32_allocateheap.c
os/binfmt/binfmt_execmodule.c
os/include/tinyara/mm/mm.h
os/kernel/init/os_start.c
os/mm/kmm_heap/kmm_addregion.c
os/mm/kmm_heap/kmm_initialize.c
os/mm/mm_heap/mm_initialize.c
os/mm/umm_heap/umm_addregion.c
os/mm/umm_heap/umm_initialize.c

If there is a failure on mm_initialize when os boot up, system should not be started, because heap cannot be used properly.

mm : Add error return in mm_initialize

---

os/mm/mm_heap/mm_extend.c

There are many cases which cannot run properly, if there is NULL or something not aligned.
In those cases, it can problem system error, so check with ASSERT instead of DEBUGASSERT.

mm/mm_heap/mm_extend : Change DEBUGASSERT to ASSERT

---

build/configs/rtl8721csm/.flashSpec.xml
build/configs/rtl8721csm/rtl8721csm_download.sh

The secure storage and userfs partitions should be kept when erasing all partitions.
That's why some data not to be erased could be written in these partition.
So except for userfs and ss and add command 'download erase ss' for erasing ss.

rtl8721csm/download : Erase partitions except for userfs and ss in ERASE ALL command

---

external/stress_tool/st_perf.c
os/arch/arm/src/armv7-m/up_schedulesigaction.c
os/arch/arm/src/armv8-m/up_schedulesigaction.c

Two crash issues are found during wifi stress test and fixed in this PR. 
1. Usage fault (INVPC) while running any stress test
2. Usage fault (INVSTATE) or busfault while running "stress 1" command multiple times.

Fix Wifi stress test crash issues

---

apps/shell/tash_security.c

If it writes passwd_prompt properly, it can be equal to sizeof(passwd_prompt).
So the return of write is equal to sizeof(passwd_prompt) for successful case.

apps/shell/tash_security : Modify wrong comparison of write size

---

apps/shell/Kconfig
os/Kconfig

The password which is given in the config is hashed by SHA256
so that it should be 32 bytes. This commit describes it in the
help tab.

shell/Kconfig: add description in TASH_PASSWORD_SHA256

---

os/fs/smartfs/smartfs_utils.c

If all exist data in user buffer copied to sf->buffer, sometimes it writes wrong value.
In this case, #of written bytes was empty but calculates #of written bytes based on
sf->byteswritten, but it writes wrongly.

fs/smartfs : Fix logic of writing #of bytes in chainheader

---

apps/examples/dnsclient_test/dnsclient_main.c
apps/system/utils/netcmd.c
external/dhcpc/dhcpc.c
external/netutils/Makefile
external/netutils/netlib_setdnsserver.c
os/include/netdb.h
os/net/netdev/netdev_ioctl.c
os/net/netmgr/netmgr_ioctl_lwip.c

The structure req_lwip_data contains lwip data structure. Therefore
application have to access lwip data type. It'll cause build error
if loadable option is enabled. So replace lwip data type to struct
sockaddr which is in socket api.

network/dns: fix req_lwip_data

---

os/Makefile.unix

For managing one functionality, divide pass2 as post.
In post build option, it makes board specific bin and samsung header and so on.

Makefile.unix : Divide pass2 build options

---

apps/examples/wifi_manager_sample/wm_test.c
apps/examples/wifi_manager_sample/wm_test_stress_test1.c
framework/src/wifi_manager/wifi_manager_cb.c

stress test 1 doesn't define scan callback. so it caused crash while
scan stress test.
And add callback function checking in wi-fi manager callback function
for safety.

wifi_manager: fix scan callback in stress test

---

apps/examples/lwnl_sample/.gitignore
apps/examples/lwnl_sample/Kconfig
apps/examples/lwnl_sample/Kconfig_ENTRY
apps/examples/lwnl_sample/Make.defs
apps/examples/lwnl_sample/Makefile
apps/examples/lwnl_sample/lwnl_sample.c

add lwnl sample. it creates 3 wi-fi event listener threads by lwnl and
it prints the type of event immediately.
1) run lwnl sample
TASH> lwnl_sample
2) generate wi-fi manager event by wm_test
TASH> wm_test start
TASH> wm_test join ...
3) check that lwnl sample receive events
[0] status (5) len(3268)␍␊
[1] status (5) len(3268)␍␊
[2] status (5) len(3268)

apps/examples: add lwnl sample

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

Fix wifi_netmgr_utils_init() on gmode set value.

board/rtl8721csm/src/component/os/tizenrt: Fix wifi_netmgr_utils_init(), gmode should not be set to RTK_WIFI_NONE at the start of this function.

---

os/binfmt/binfmt_unloadmodule.c
os/binfmt/libelf/libelf.h

Fix following build warning in binfmt.
binfmt_unloadmodule.c: In function 'unload_module':
binfmt_unloadmodule.c:203:23: warning: initialization of 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
203 |    void *start_addr = elf_find_start_section_addr(binp);
|

os/binfmt: Fix build warning in binfmt

---

loadable_apps/loadable.mk
os/Makefile.unix

This patch removes all user libraries like framework, external etc from app
binary and includes it in the common library when
CONFIG_SUPPORT_COMMON_BINARY is enabled.

os/Makefile.unix: Moving all USERLIBS from app binary to common binary..

---

os/include/sys/boardctl.h

To reset the board through sw, we should call boardctl(BOARDIOC_RESET, EXIT_SUCCESS/FAILURE).
For easy use, add macro as board_sw_reset()

include/sys/boardctl.h : Add macro of boardctl

---

os/drivers/wireless/realtek/wifi_util_interface/rtk_drv.c

- to fix the build error, include netdev_mgr.h header file to provide the reference of netdev.

drivers/rtk_drv.c: fix build error for imxrt1020-evk/tc

---

apps/system/utils/Makefile

A killall command uses proc data with utils in utils_proc.c
So build utils_proc.c if a killall command is enabled.

apps/system/utils: Fix build error of killall command about functions in utils_proc.c

---

os/crypto/Makefile
os/drivers/Makefile
os/fs/Makefile
os/logm/Makefile
os/net/Makefile
os/pm/Makefile

Add .PHONY definitions to prevent 'clean up to date' message weirdness when 'make clean' is done with no .config or
Make.defs file.

os: Add missing .PHONY definitions

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

fix wifi scan memory leak in app_scan_result_handler()

os/board/rtl8721csm: fix wifi scan memory leak issue

---

os/Makefile.unix

check_output_size.py only works when CONFIG_FLASH_PARTITION is enabled, because it uses FLASH_PART_NAME and FLASH_PART_SIZE.

Makefile.unix : call check_output_size.py when CONFIG_FLASH_PARTITION is enabled

---

os/fs/driver/mtd/mtd_jedec.c

When sudden power off happened, voltage level goes to down but
it can be grow up suddenly in product level.
In this case some of bits are still '0' but erase ops returns OK
To prevent this situation, verification is needed

mtd/jedec : Add logic to verify erase

---

build/configs/rtl8721csm/tc/Make.defs

- Correct the path to common_download.sh in rtl8721csm/tc/Make.defs.

configs/rtl8721csm/tc : Correct the path to common_download.sh.

---

os/arch/arm/src/amebad/Kconfig
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/inc/bt_board.h

- Disable flash bit check to disable all BLE debug function

os/board/rtl8721csm: Disable all rtl8721csm BLE debug function by default

---

build/configs/rtl8721csm/rtl8721csm_download.sh

There are duplicated line for copying boot param binary. So remove one of them.

build/config/rtl8721csm_download.sh : Remove duplicated bootparam copy

---

os/board/common/partitions.c

minor information of partition should be set for all cases, not only ftl_init

board/common/partitions.c : Fix fs minor setting

---

os/dbuild.sh

A username of github is used for hostname.
Trim white-space from hostname for a case with spaces in the username.

dbuild: Trim white-space from hostname

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

Wep scan result is scan_list->ap_info.ap_auth_type = WIFI_UTILS_AUTH_WPA_PSK.
Fix it to scan_list->ap_info.ap_auth_type = WIFI_UTILS_AUTH_WEP_SHARED.

rtl8721csm/rtk_netmgr.c: Fix wep AP scan result correctly

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c

Modify error flag in wifi_disconn_hdl for AP mac filter case from RTW_UNKNOWN to RTW_CONNECT_FAIL

os/board/rtl8721csm: modify error flag for AP mac filter case

---

os/net/netmgr/netdev_lwip.c

if it's not zero then some module(ex. dhcpc) can access invalid
address of netif which is not initialized.

network/netmgr: initialize allocated netif memory to 0

---

framework/src/wifi_manager/wifi_manager_state.c

dhcpc is not closed if STA receive disconnect command on connected
state. So call dhcpc_close_ipaddr() if STA in connected state get
a disconnect command.

wifimanager: terminate dhcpc on disconnected state in STA

---

os/board/common/partitions.c

- "timezone," string of length 9 should be matched with incoming
partition type string but strncmp checks for string of length 10.
- Hence, the partition types never match and timzeone romfs mounting
never takes place.
- Change comparison length in strncmp for "timezone," from 10 to 9

board/common: Fix string comparison length for flash partition

---

apps/system/utils/utils_tzselect.c

- in utils_tzselect.c, change the overwrite value as 1 in setenv() to select the TZ multiple times because if overwrite value is 0 then we can select the TZ only once, again overwriting is not allowed.

apps/system/utils/tzselect: change the overwrite value in setenv

---

os/arch/arm/src/amebad/amebad_serial.c

This modification is made to fix the uart data loss under the heavy load.

os/arch/arm/src/amebad: Modify rtl8721d_up_txready function

---

external/dhcpd/dhcpd_lwip.c

Fix pthread_create return check in dhcps and add detach

external/dhcpd_lwip: Fix pthread_create return check in dhcps

---

os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/rtc_api.c

Build warning : component/common/mbed/targets/hal/rtl8721d/rtc_api.c:128:6: warning: unused variable 'value' [-Wunused-variable]
u32 value;

board/rtl8721csm/rtc_api.c : Remove unused local variable

---

os/include/tinyara/reboot_reason.h

To write reboot reason, user should call prctl(PR_REBOOT_REASON_WRITE, code) and include both sys/prctl.h and tinyara/reboot_reason.h
For easy use, add macro.

include/tinyara/reboot_reason.h : Add macro for reboot reason

---

os/include/tinyara/reboot_reason.h

Remove wrong '\' at the end of macro definition.
Build error:
In file included from /TizenRT_washer/os/include/arch/reboot_reason.h:22:0,
from task/task_prctl.c:86:
/TizenRT_washer/os/include/tinyara/reboot_reason.h:49:30: error: '#' is not followed by a macro parameter
#define WRITE_REBOOT_REASON(x) do {                                       \
^
Makefile:97: recipe for target 'task_prctl.o' failed

reboot_reason: Remove wrong '\' at the end of macro definition

---

apps/examples/testcase/le_tc/kernel/tc_mqueue.c

In tc_mqueue_mq_timedsend_timedreceive_failurechecks, return statement is missed.
So duplicated mq_close prints the below ERRORs.
mq_close_group: ERROR: mqdes(xxxxx) is not in this thread's group.

apps/examples/le_tc/kernel/tc_mqueue.c : Add missing return statement

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c
os/net/netmgr/netdev_wifi.c

Modified code to parse the result of scan with SSID API and to pass the list to upper layer
Modified LWNL_REQ_WIFI_SCANAP case of netdev_wifi.c to pass user input to scan with SSID API

os/board/rtl8721csm : Implementation of Wi-Fi scan with SSID

---

os/tools/build_test.sh

- Print a summary of build test results like travis CI
- All build test works without break although some builds are failed
- Support result file for failed test to help users find problems
[Print Logs]
1. All success
==========================================
=========== Build Test Result ===========
==========================================
artik055s/audio ------ SUCCESS
artik053/st_things ------ SUCCESS
artik053/tc ------ SUCCESS
qemu/build_test ------ SUCCESS
esp_wrover_kit/hello_with_tash ------ SUCCESS
imxrt1020-evk/loadable_elf_apps ------ SUCCESS
rtl8721csm/loadable_apps ------ SUCCESS
==========================================
2. Some failures
==========================================
=========== Build Test Result ===========
========================================== …

tools/build_test: Print a summary of build test results

---

os/arch/arm/src/amebad/amebad_serial.c

This PR fixes the 'mixed uart log' issue which happens when multiple functions use log_uart at the same time.

os/arch/arm/src/amebad: Fix the 'mixed uart log' issue

---

os/board/rtl8721csm/src/component/common/file_system/ftl/ftl.c

- Implement Secure FTL
- Due to image3 is not update, so Secure FTL is default set to off.
- To turn on Secure FTL please define FTL_SECURE as 1. (#define FTL_SECURE 1)

os/board/rtl8721csm: Implement Secure FTL

---

os/include/tinyara/reboot_reason.h

For board specific reboot reason, change to start them from 250.

os/include/tinyara/reboot_reason.h : Change board specific reboot reason from 250

---

apps/examples/testcase/ta_tc/systemio/itc/itc_internal.h
apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c
apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c

#Patch 1
apps/examples/testcase/ta_tc/systemio: Fix build breaks when SPI driver TC's are enabled
This patch adds fix for:
1) Missing declarations of SPI driver itc:
int itc_spi_main(void);
2) Config dependency for unused API's when CONFIG_SPI_EXCHANGE is disabled.
3) SPI bus for UTC to 0.
#Patch 2
apps/examples/testcase/ta_tc/systemio/itc: Rename API in SPI ITC
Fix typo SPI test case ITc and rename to itc_systemio_spi_write_recv_transfer_p

Add SPI driver build break fixes

---

apps/examples/timer/timer_main.c

It should close fd before pthread_exit to release used resource.
If timer example runs continuously, an error occurs in 4 times.
TASH>>timer -n 10
Open /dev/timer0
Attach timer handler
Set timer interval to 1000000, repeat 10
Start the timer
FRT Open /dev/timer1
ERROR: Failed to open Free Run Timer: 24
Finished

apps/examples/timer: Close fd before pthread exit to release used resources

---

apps/examples/testcase/le_tc/network/tc_net_pbuf.c

Fix following build errors:
CC:  le_tc/network/tc_net_pbuf.c
le_tc/network/tc_net_pbuf.c: In function 'tc_net_pbuf_layer_link_p':
le_tc/network/tc_net_pbuf.c:98:36: warning: passing argument 3 of 'ioctl' makes integer from pointer without a cast [-Wint-conversion]
98 |  ret = ioctl(fd, TESTIOC_NET_PBUF, &args);
|                                    ^~~~~
|                                    |
|                                    struct pbuf_test_args *
In file included from le_tc/network/tc_net_pbuf.c:32:
/home/kishore/tinyara/TizenRT_srib_gerrit/os/include/sys/ioctl.h:140:42: note: expected 'long unsigned int' but argument is of type 'struct pbuf_test_args *'
140 | int ioctl(int fd, int req, unsigned long arg);
|                            ~~~~~~~~~~~~~~^~~
Signed-off-by: Kishore S N …

testcase/le_tc: Fix build errors

---

os/kernel/debug/sysdbg.c

Remove wrong function description.
Signed-off-by: sangamanatha <sangam.swami@samsung.com>

os/kernel/debug: Remove wrong description of sysdbg_read function

---

os/kernel/debug/sysdbg.c

Change sysdbg_read function misnomer to sysdbg_print.
Signed-off-by: sangamanatha <sangam.swami@samsung.com>

os/kernel/debug: Change sysdbg_read function misnomer.

---

os/kernel/mqueue/mq_timedreceive.c
os/kernel/mqueue/mq_timedsend.c
os/kernel/pthread/pthread_condtimedwait.c

wd_create fails when it cannot allocate the wd.
So the errno of wd creation failure can be ENOMEM.

kernel : Change errno for wd_create fail case

---

os/arch/arm/src/amebad/amebad_timer_lowerhalf.c

1)   The return type of amebad_gpt_handler() is void, so it cannot return -ENODEV.
2)  'ret' is initialized as -EINVAL, so it is not need to be reassigned for some cases.

arch/arm/amebad_timer_lowerhalf.c : Remove wrong return of amebad_gpt_handler

---

os/arch/arm/src/armv7-r/arm_syscall.c

Task monitor is kernel thread which monitor the tasks/pthreads.
It checks if registered tasks/pthreads are alive.
It was implemented in v7m and v8m, so implement to v7-r also.

arch/arm/src/armv7-r : Add task monitor functionality

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/board/common/os/tizenrt/osif_tizenrt.c
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/i2c_api.c

WID:12571040 Uninitialized data is read from local variable 'i2cen' at i2c_api.c:704.

board/rtl8721csm/i2c_api.c : Initialize local variable

---

framework/include/wifi_manager/wifi_manager.h
framework/src/wifi_manager/wifi_manager_api.c

Both channel and ssid_length are unsigned int. So they're never less
than zero.

framework/wifi_manager: fix parameter validation in scan api

---

os/arch/arm/src/amebad/Make.defs
os/arch/arm/src/armv7-m/up_blocktask.c
os/arch/arm/src/armv7-m/up_releasepending.c
os/arch/arm/src/armv7-m/up_reprioritizertr.c
os/arch/arm/src/armv7-m/up_schedyield.c
os/arch/arm/src/armv7-m/up_svcall.c
os/arch/arm/src/armv7-m/up_unblocktask.c
os/arch/arm/src/armv7-m/up_unblocktask_withoutsavereg.c
os/arch/arm/src/armv7-r/arm_blocktask.c
os/arch/arm/src/armv7-r/arm_releasepending.c
os/arch/arm/src/armv7-r/arm_reprioritizertr.c
os/arch/arm/src/armv7-r/arm_schedyield.c
os/arch/arm/src/armv7-r/arm_unblocktask.c
os/arch/arm/src/armv8-m/up_blocktask.c
os/arch/arm/src/armv8-m/up_releasepending.c
os/arch/arm/src/armv8-m/up_reprioritizertr.c
os/arch/arm/src/armv8-m/up_schedyield.c
os/arch/arm/src/armv8-m/up_svcall.c
os/arch/arm/src/armv8-m/up_unblocktask.c
os/arch/arm/src/armv8-m/up_unblocktask_withoutsavereg.c
os/arch/arm/src/bcm4390x/Make.defs
os/arch/arm/src/common/up_restoretask.c
os/arch/arm/src/imxrt/Make.defs
os/arch/arm/src/s5j/Make.defs
os/arch/arm/src/stm32/Make.defs
os/arch/arm/src/stm32l4/Make.defs
os/arch/arm/src/tiva/Make.defs
os/include/tinyara/arch.h

- Unify same operations for context switching in each functions.
- It can help to avoid missing and you don't need to modify all files when some operations or values are changed.

arch/arm/common: Unify a function to restore context of tcb for context switching

---

apps/system/utils/Kconfig

StackMonitor only works when FS_PROCFS is enabled.

apps/system/utils/Kconfig : Add dependency of PROCFS in StackMonitor

---

os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c

- add WPA_PSK auth type in rtl wifi connection

os/board/rtl8721csm: add wifi auth type in connection

---

os/board/common/partitions.c
os/include/tinyara/binary_manager.h
os/kernel/binary_manager/Make.defs
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_bootparam.c
os/kernel/binary_manager/binary_manager_data.c

Update booted kernel binary information from boot parameter data without scanning all kernel binaries.
This PR will be updated with commits about boot parameter recovery, #5008 soon.

kernel/binary_manager: Update booted kernel information from bootparam

---

os/arch/arm/src/armv7-m/up_doirq.c
os/arch/arm/src/armv8-m/up_doirq.c

Fix the following build warnings:
CC: armv8-m/up_doirq.c
armv8-m/up_doirq.c: In function 'up_doirq':
armv8-m/up_doirq.c:95:11: warning: unused variable 'stack_remain' [-Wunused-variable]
uint32_t stack_remain;
^~~~~~~~~~~~
CC: armv7-m/up_doirq.c
armv7-m/up_doirq.c: In function 'up_doirq':
armv7-m/up_doirq.c:95:11: warning: unused variable 'stack_remain' [-Wunused-variable]
uint32_t stack_remain;
^~~~~~~~~~~~

arm/src/up_doirq.c: move local variable definition into proper conditional

---

os/net/lwip/src/core/pbuf.c

initialize pbuf->flags. other member of pbuf are initialized in
pbuf_alloc except flags. So it cause unexpected behavior when lwip
fails to make pbuf chain and free the pbuf.
The scenario is like this
1) pbuf_alloc
2) head of pbuf(p) chain is allocated.
3) fail to allocate chain pbuf.
4) lwip tries to deallocated pbuf p.
5) p->flags contains trash value. it can perform
pc->custom_free_function() in pbuf_free().

net/lwip: fix lwip pbuf initialization

---

os/kernel/semaphore/sem_timedwait.c

sem_timedwait returns 0 on success.

kernel/semaphore/sem_timedwait.c : Fix description of successful return

---

os/binfmt/libelf/libelf_sections.c

/root/tizenrt/os/include/tinyara/binfmt/elf.h: In function 'elf_find_text_section_addr':
libelf/libelf_sections.c:218:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^

binfmt/libelf/libelf_sections.c : Fix build warning for return

---

os/drivers/lwnl/lwnl.c
os/drivers/lwnl/lwnl_evt_queue.c
os/drivers/lwnl/lwnl_evt_queue.h
os/include/tinyara/lwnl/lwnl.h
os/include/tinyara/net/if/ble.h
os/net/blemgr/bledev.c
os/net/blemgr/bledev_mgr_client.c

- add data pointer mode in lwnl_postmsg
(if data_len is negative, a queue copies pointer of data.)

drivers/lwnl: add data pointer copy mode in lwnl_postmsg

---

os/Makefile.unix
os/binfmt/binfmt_loadbinary.c
os/binfmt/elf.c
os/binfmt/libelf/libelf.h
os/binfmt/libelf/libelf_cache.c
os/binfmt/libelf/libelf_init.c
os/binfmt/libelf/libelf_read.c
os/binfmt/libelf/libelf_uninit.c
os/include/tinyara/binary_manager.h
os/include/tinyara/binfmt/binfmt.h
os/include/tinyara/binfmt/elf.h
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_load.c
os/tools/mkbinheader.py

Common binary will be compressed with CONFIG_COMPRESSION_TYPE and
CONFIG_COMPRESSION_BLOCK_SIZE, if CONFIG_COMPRESSED_BINARY is enabled.

os/Makefile: Enable binary compression for common binary

---

os/tools/mkbootparam.py

========== Start to make boot parameters ==========
Traceback (most recent call last):
File "/root/tizenrt/os/../os/tools/mkbootparam.py", line 161, in <module>
make_bootparam()
File "/root/tizenrt/os/../os/tools/mkbootparam.py", line 122, in make_bootparam
user_file_list = os.listdir(user_file_dir)
OSError: [Errno 2] No such file or directory: '/root/tizenrt/os/../os/tools/../../build/output/bin/user'
make: *** [post] Error 1
Makefile.unix:494: recipe for target 'post' failed

os/tools: Fix "No such file or directory: 'build/output/bin/user'" error

---

os/Makefile.unix

When loadable build configuration is built, the user folder under output/bin is newly created and
it should be deleted with clean command. But DELFILE definition can do only files, can't do folders.
It causes the error as below:
rm: cannot remove '../build/output/bin/user': Is a directory
Makefile.unix:629: recipe for target 'clean' failed
make: *** [clean] Error 1
This commit changes the command to delete output bin folder from DELFILE to DELDIR to resolve above.

os/Makefile.unix: use -f option to delete output bin folder 

---

loadable_apps/loadable_sample/wifiapp/binary_update.c

binary_update.c:320:7: warning: unused variable 'path' [-Wunused-variable]
char path[BINARY_PATH_LEN];
^~~~

loadable_apps/binary_update.c : Remove unused local variable

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_client_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app_task.c

Handle three semaphores, give when disconnection happened, delete when task deinit.
Remove case BLE_TIZENRT_READ_RESULT_MSG which is not used anymore.
Use os_mutex_delete for ble_tizenrt_read_sem, since it is created using os_mutex_create.

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/exampe/: Fix BLE disconnection 30s delay

---

.circleci/config.yml

Because BLE on rtl8721csm is developing, this commit adds
rtl8721csm/hello build test by default.

circleci: add rtl8721csm/hello build test

---

os/kernel/binary_manager/binary_manager_load.c

To reload the all binaries, it iterates the all binary based on bin_count.
But bin_count is not set properly.
binary_manager/binary_manager_load.c:561:2: warning: 'bin_count' may be used uninitialized in this function [-Wmaybe-uninitialized]
for (bin_idx = 1; bin_idx <= bin_count; bin_idx++) {
^~~

kernel/binary_manager_load.c : Fix to get binary count

---

framework/src/wifi_manager/wifi_manager_state.c

wifi_manager manages it's internal information in
wifi_manager_info.c. However it doesn't update its state after
scanning is done. Because wifimgr_set_info wasn't called.

wifi_manager: modify state changing in scanning.

---

framework/include/ble_manager/ble_client.h
os/include/tinyara/net/if/ble.h
os/net/blemgr/bledev.c
os/net/blemgr/bledev_mgr_client.c

- Test 3 cases of memcpy
1. use 'memcpy'
2. copy 1 byte unit
3. copy 4 bytes unit
The size of source  : 84 bytes (trble_scanned_device)
The number of trial : 10000 times
- The results
Test#1 :  8.01 ms
Test#2 : 21.15 ms
Test#3 :  6.36 ms
The speed of memcpy increased 15% by using 4 bytes unit.

framework/ble_manager: improve memcpy speed

---

os/binfmt/libelf/libelf_sections.c

The binary name is in binary_s, not in bin_addr_info_t.
(It was removed from bin_addr_info_t in previous commit.)
libelf/libelf_sections.c: In function 'elf_save_bin_section_addr':
libelf/libelf_sections.c:229:42: error: 'bin_addr_info_t {aka struct bin_addr_info_s}' has no member named 'bin_name'; did you mean 'bin_idx'?
lldbg("[%s] text_addr : %x\n", bin_info->bin_name, bin_info->text_addr);

kernel/binfmt/libelf_sections.c : Fix to get binary name

---

os/wqueue/kwqueue/kwork_cancel.c
os/wqueue/kwqueue/kwork_hpthread.c
os/wqueue/kwqueue/kwork_inherit.c
os/wqueue/kwqueue/kwork_lpthread.c
os/wqueue/kwqueue/kwork_queue.c
os/wqueue/kwqueue/kwork_signal.c
os/wqueue/uwqueue/uwork_cancel.c
os/wqueue/uwqueue/uwork_lock.c
os/wqueue/uwqueue/uwork_queue.c
os/wqueue/uwqueue/uwork_signal.c
os/wqueue/uwqueue/uwork_thread.c
os/wqueue/wqueue.h

g_hpwork, g_lpwork, g_usrwork and g_usrsem/g_usrmutex are global variable, so it is not good to use directly.
So add getXXX APIs for each global variables.

wqueue : Modify to get hpwork, lpwork and usrwork from each getXXX APIs

---

os/binfmt/elf.c
os/binfmt/libelf/libelf.h
os/binfmt/libelf/libelf_sections.c
os/include/tinyara/binfmt/binfmt.h

To use the user binary's text region size for debugging, save the text region size and show it when asserted.

os/binfmt/libelf_sections.c : Save text region size

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv8-m/up_assert.c

Fix build error for comparison of different data type
armv8-m/up_assert.c: In function 'up_assert':
armv8-m/up_assert.c:140:52: warning: comparison between pointer and integer
#define IS_FAULT_IN_USER_THREAD  (fault_tcb->uheap != (void *)NULL)
^
armv8-m/up_assert.c:504:6: note: in expansion of macro 'IS_FAULT_IN_USER_THREAD'
if (IS_FAULT_IN_USER_THREAD) {
^~~~~~~~~~~~~~~~~~~~~~~

arch/arm/src/armv7,8-m/up_assert.c : Fix build warning

---

os/binfmt/libelf/libelf_read.c

Add preprocessor condition to fix build warning as shown below
CC:  libelf/libelf_read.c
libelf/libelf_read.c: In function 'elf_read':
libelf/libelf_read.c:134:8: warning: unused variable 'rpos' [-Wunused-variable]
off_t rpos;     /* Position returned by lseek */
^~~~

os/binfmt/libelf: fix build warning

---

os/tools/check_output_size.py

1. change the title to show which point is the target of verification
2. change the message format as below:
1) make a tab between the items
2) add comma at the number and make align
3) show binary size first
3. add done message
4. modify the message of failure
Success case
```
========== Size Verification of built Binaries ==========
KERNEL	Binary Size :    774,112 bytes	Partition Size :  1,835,008 bytes
APP1	Binary Size :      8,822 bytes	Partition Size :    524,288 bytes
APP2	Binary Size :    344,858 bytes	Partition Size :  1,040,384 bytes
Size verification is done.
```
Failure case
```
========== Size Verification of built Binaries ==========
KERNEL	Binary Size :    774,112 bytes	Partition Size :  1,835,008 bytes
APP1	Binary Size :      8,822 bytes	Partition Size :     16,384 bytes …
```

os/tools: reformatting output of check_output_size.py

---

os/fs/smartfs/smartfs_smart.c

- The check for the end of file sectors is done at the beginning of the
while loop, don't need to check again at the end.

os/fs/smartfs: Remove redundant check for end of file sectors

---

os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager_load.c

To show always to user, it is better to use printf instead of lldbg.
So change lldbg to printf in binary manager.

os/kernel/binary_manager : Change lldbg to printf

---

os/tools/set_bininfo.py

TizenRT adds its own header at front of the output so that it's not
proper to use previous extensions like bin, hex and so on.
This commit applies "trpk" for that.
"trpk" stands for TizenRT Package.

tools/set_bininfo.py: apply TizenRT Package extension - trpk on each output

---

framework/src/binary_manager/binary_manager_interface.c
framework/src/binary_manager/binary_manager_update.c

CC:  src/binary_manager/binary_manager_interface.c
src/binary_manager/binary_manager_interface.c: In function 'binary_manager_set_request':
src/binary_manager/binary_manager_interface.c:52:28: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
request_msg->data.type = (uint8_t)arg;
^
CC:  src/binary_manager/binary_manager_update.c
src/binary_manager/binary_manager_update.c: In function 'binary_manager_set_bootparam':
src/binary_manager/binary_manager_update.c:48:63: warning: passing argument 3 of 'binary_manager_set_request' makes pointer from integer without a cast [-Wint-conversion]
ret = binary_manager_set_request(&request_msg, BINMGR_SETBP, type);
^~~~
In file included from src/binary_manager/binary_manager_update.c:31:0: …

framework/binary_manager: Fix build warning about type casting

---

framework/include/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager.h

binary_manager_set_bootparam is user API which is in framework/binary_manager.
So to use this API, the prototype should be in framework/include/binary_manager.

framework/binary_manager.h : Move binary_manager_set_bootparam prototype

---

os/kernel/binary_manager/binary_manager_load.c

Binary manager allocates buffer with binary RAM size for binary crc checking.
But the space with this size can be not enough after some binaries are loaded.
So if this size is larger than the largest free size, set buffer size to (the largest free size / 2).

kernel/binary_manager: Optimize buffer size for crc checking

---

os/kernel/binary_manager/binary_manager_data.c
os/kernel/binary_manager/binary_manager_load.c

Binary manager loads binaries based on boot parameters.
But if the binary written in bootparam is invalid, it checks the binary in another partition.
If it is valid, binary manager loads the binary and updates bootparam.

kernel/binary_manager: Update bootparam when the binary not written in bootparam is loaded

---

os/binfmt/binfmt_loadbinary.c
os/binfmt/binfmt_unloadmodule.c
os/include/tinyara/binfmt/binfmt.h
os/include/tinyara/sched.h

During update test, we try to unload and reload all binaries. In case
of app binary, we disbale the MPU regions based on the MPU regs stored
in the tcb of apps. But, in case of Common binary, the MPU regions are
not stored anywhere. As a result, the MPU for common binary is not
disabled. So, at the time of reloading common binary, there is a memfault
while trying to copy code from binary to the read-only area of the code
section.
Issue is fixed by storing the common binary MPU registers in the binary
data structure and disabling the regions at the time of unload module.

os/binfmt: Fix memfault during Common binary Update test

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/common/up_checkspace.c
os/include/tinyara/arch.h
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_recovery.c

Binary manager should reload all binaries if a fault happens in common library or user binaries
That's because common binary is loaded in memory space of app binaries.

kernel/binary_manager: Reload all binaries when a fault happens in common or user binaries

---

os/binfmt/elf.c

Too many logs coming when berr logging type is enabled. So, change
unwanted information msgs from berr to binfo type.

os/binfmt: Change logging type for information msgs

---

os/mm/mm_heap/mm_manage_allocfail.c

In user level, use printf instead of lldbg for assertion on mem allocation fail.

mm/mm_manage_allocfail.c : Change to use printf for user level

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv8-m/up_assert.c
tools/debug/debugsymbolviewer.py
tools/dump_tool/HowToUseDumpTool.md
tools/dump_tool/ramdumpParser.py

This patch adds the functionality where the crash logs are scanned for
address in the range of application text address range in addition to the
kernel crashes. If yes, it displays the point of crash for the respective
apps.

tools/dump_tool: Update the tool to accomodate loadable_apps crash point detection

---

os/include/tinyara/mm/mm.h
os/mm/kmm_heap/kmm_calloc.c
os/mm/kmm_heap/kmm_malloc.c
os/mm/kmm_heap/kmm_memalign.c
os/mm/kmm_heap/kmm_realloc.c
os/mm/kmm_heap/kmm_zalloc.c
os/mm/umm_heap/umm_calloc.c
os/mm/umm_heap/umm_malloc.c
os/mm/umm_heap/umm_memalign.c
os/mm/umm_heap/umm_realloc.c
os/mm/umm_heap/umm_xalloc_user_at.c
os/mm/umm_heap/umm_zalloc.c

This macro should be placed at the first of the function.
If no, it is better to use "__builtin_return_address(0)" instead.

mm/*mm_heap : Move ARCH_GET_RET_ADDRESS at the first of the function

---

os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c

Fix the idle stack start address for coloration

board/rtl8721dhp_app_start.c : Fix to make coloration for idle stack

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv8-m/up_assert.c

When kernel heap corruption is detected in assert, we can't keep kernel alive.
Currently it keeps and tries to reload user binary. Finally it causes kernel assert again.
This commit resets the board with kernel heap corruption in assert.

arch/armv7-m, armv8-m: do board reset with kernel heap corruption

---

os/arch/arm/src/amebad/amebad_serial.c

Uart2 uses tx buffer for g_uart2txbuffer global variable and
its definition is
static char g_uart2txbuffer[CONFIG_UART2_TXBUFSIZE];.
So, g_uart2port structure should have CONFIG_UART2_TXBUFSIZE in the .xmit->.size,
not CONFIG_UART1_TXBUFSIZE.
This commit fixes above.

arch/amebad/amebad_serial.c: fix wrong size of tx buffer for uart2

---

os/kernel/binary_manager/binary_manager_load.c

Print loaded binary information : name, partition, version, compression
Ex)
1. Initial booting
- Load success! [Name: common] [Version: 200204] [Partition: A] [Compressed Binary]
- Load success! [Name: app1] [Version: 190412] [Partition: A] [Compressed Binary]
- Load success! [Name: app2] [Version: 190412] [Partition: A] [Compressed Binary]
2. After binary 'app1' update with 'u' command
- Load success! [Name: common] [Version: 200204] [Partition: A] [Compressed Binary]
- Load success! [Name: app1] [Version: 190413] [Partition: B] [Compressed Binary]
- Load success! [Name: app2] [Version: 190412] [Partition: A] [Compressed Binary]

kernel/binary_manager: Print loaded binary information on loading success

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-m/up_busfault.c
os/arch/arm/src/armv7-m/up_hardfault.c
os/arch/arm/src/armv7-m/up_memfault.c
os/arch/arm/src/armv7-m/up_svcall.c
os/arch/arm/src/armv7-m/up_usagefault.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/armv8-m/up_busfault.c
os/arch/arm/src/armv8-m/up_hardfault.c
os/arch/arm/src/armv8-m/up_memfault.c
os/arch/arm/src/armv8-m/up_svcall.c
os/arch/arm/src/armv8-m/up_usagefault.c
os/include/tinyara/mm/mm.h

During the faults and assert failure in app space, g_assert_location is set
to appropriate value to indicate the location of the crash and is used during
up_assert. In case of app SW assert, the crash location is obtained from
R14 of the interrupt context and in case of HW fault in app, it is obtained
from R15 of the interrupt context saved on the stack. In the case of kernel
asserts, we get the assert pc from the return address (current LR value) in
up_assert.
Moved ARCH_GET_RET_ADDRESS definition out of CONFIG_DEBUG_MM_HEAPINFO
as it is used in up_assert.

src/armv7-m,armv8-m: Modify to get the correct assert pc

---

os/include/tinyara/binary_manager.h
os/kernel/binary_manager/Make.defs
os/kernel/binary_manager/binary_manager_deinit.c
os/kernel/binary_manager/binary_manager_load.c

Add binary_manager_deinit_modules function to call deinit functions of modules which need to clear or reset used resources like device state before loading again after binary unloading (i.e. network modules like LWIP)

kernel/binary_manager: Add deinit functions for binary reloading

---

apps/examples/security_test/seclink/sl_auth_test.c
apps/examples/security_test/seclink/sl_crypto_test.c
apps/examples/security_test/seclink/sl_key_test.c
apps/examples/security_test/seclink/sl_mbed_test.c
apps/examples/security_test/seclink/sl_ss_test.c
external/include/stress_tool/st_perf.h

Issue: security_test/seclink files use ST_SET_PACK in global scope.
perf_add_global function call fails at that scope.
Change: Add an alternate ST_SET_PACK_GLOBAL and use in seclink files.

Resolve build issue in config: security_hal_test_tz

---

os/kernel/pthread/pthread_create.c

If a caller thread is blocked by pthread_sem_take, binary_manager_remove_binlist is called first by executing the new created thread before adding the tcb to a list by binary_manager_add_binlist.
So it should be added to a binary thread list after task_activate directly before pthread_sem_take.

kernel/binary_manager: Add tcb to a binary thread list after task activation in pthread_create

---

os/mm/kmm_heap/kmm_realloc.c
os/mm/umm_heap/umm_realloc.c

When realloc is executed with size 0, it should try to free previous
allocated memory. But commit fad7c48 returns NULL without freeing.
This commit fixes wrong modification of commit fad7c48.

fixup! mm/*mm_heap : Return NULL if requested size is 0

---

apps/examples/testcase/le_tc/kernel/itc_sched.c

This testcase is for checking setting/getting a scheduler and scheduling priority.
At this time, the scheduler and priority of thread which executes this TC are changed.
So restore original scheduler and scheduling priority after testcase execution.

app/examples/testcase: Restore original scheduler and priority after TC execution in itc_sched

---

apps/examples/testcase/le_tc/kernel/tc_sched.c

This testcase is for checking setting/getting a scheduler and scheduling priority.
At this time, the scheduler and priority of thread which executes this TC are changed.
So restore original scheduler and scheduling priority after testcase execution.

testcase/kernel: Restore original scheduler and priority after TC execution in tc_sched

---

apps/examples/testcase/le_tc/kernel/tc_umm_heap.c

1. Split heapinfo code
Heapinfo is not mandatory to test mm functions.
This commit splits the part of testing mm functions itself and
the part of checking memory by heapinfo.
2. Add some tests for realloc
Realloc has specific operation against others. When zero size is
given, others just return NULL. But realloc frees previous allocated
memory.
3. Remove random malloc test
Because it's the same as malloc test, let's remove.

examples/testcase/kernel: refactor tc_umm_heap

---

framework/include/binary_manager/binary_manager.h
framework/src/binary_manager/binary_manager_update.c
loadable_apps/loadable_sample/wifiapp/binary_update.c
os/include/tinyara/binary_manager.h
os/kernel/Kconfig
os/kernel/binary_manager/Make.defs
os/kernel/binary_manager/binary_manager.c
os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_bootparam.c
os/kernel/binary_manager/binary_manager_data.c
os/kernel/binary_manager/binary_manager_getinfo.c
os/kernel/binary_manager/binary_manager_load.c
os/kernel/binary_manager/binary_manager_recovery.c
os/kernel/binary_manager/binary_manager_verify.c
os/kernel/init/os_bringup.c

The binary_manager_set_bootparam is called with binary group.
If one of them has no update, binary manager doesn't update bootparam and returns error.
For this case, return all results for requested group's binaries to know the reason of failure of bootparam update.

kernel/binary_manager: Return all results for requested binaries from binary_manager_set_bootparam

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

rtl8721 calls wifi_scan_networks_with_ssid() when scan with ssid was
requested. wifi_scan_networks_with_ssid() calls result_handler even though
scan_cnt which is result of wifi_scan is 0. In result_handler it
convert scan_buf which has invalid data to trwifi_scan_result. So it
does unexpected behavior.

rtl8721csm: fix heap curruption when scan result is 0

---

os/kernel/mqueue/mq_send.c
os/kernel/mqueue/mq_sndinternal.c
os/kernel/mqueue/mq_timedsend.c

If fail to get the preallocated msg from interrupt handler, set errno as EBUSY.
If fail to allocat the msg from normal thread, set errno as ENOMEM.

kernel/mqueue : Set errno when fail to get/allocate the msg

---

apps/examples/testcase/le_tc/kernel/tc_umm_heap.c

Line 286 checks operation of line 285. Line 285 saves allocated memory
address in mem_ptr[0], but line 286 checks mem_ptr[1].
It's typo of previous commit ad391bf.
This commit fixes above.

fixup! examples/testcase/kernel: refactor tc_umm_heap

---

os/arch/arm/src/armv8-m/up_blocktask.c

To make context switching, current running tcb's secure context should be saved, not to be blocked one.
So change tcb to rtcb.

arch/armv8-m/up_blocktask.c : Fix wrong tcb for saving secure context

---

apps/examples/testcase/le_tc/filesystem/fs_main.c

Smartfs changed routine which checks flag of file(#5164), so old code faced errors
So Fix some flags.

fs/tc : Fix open flags to prevent error

---

apps/examples/fs_test/procfs_test.c
os/arch/arm/src/amebad/amebad_flash.c
os/arch/arm/src/imxrt/imxrt_mtd_flash.c
os/arch/arm/src/stm32l4/stm32l4_ospi.c
os/arch/xtensa/src/esp32/spi_flash/esp32_flash.c
os/board/common/partitions.c
os/fs/driver/mtd/m25px/m25px.c
os/fs/driver/mtd/mtd_partition.c
os/include/tinyara/fs/mtd.h

- Fix wrong entry function name to 'procfs_test_main'
- Set the name of mtd devices in when device initialization
- fs/driver/mtd: Fix wrong output from '/proc/partitions'
- Ex) cat /proc/partitions
Name             Start    Size   MTD
bl1       0       4    ameba_flash
bl2       4       2    ameba_flash
reserved       6       4    ameba_flash
ss      10     118    ameba_flash
system_data     128       2    ameba_flash
kernel     130     448    ameba_flash
kernel     578     448    ameba_flash
userfs    1026    1020    ameba_flash
bootparam    2046       2    ameba_flash

fs/driver/mtd: Fix wrong output from '/proc/partitions'

---

os/tools/mkbootparam.py

Change a range of CRC checking to the whole bootparam region with 4Kbytes to remove dependency of build type.

tools/mkbootparam: Change a range of CRC checking to the whole bootparam region with 4Kbytes

---

os/arch/arm/src/amebad/amebad_reboot_reason.h
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c

Override secure hardfault handler to 1. print PC/LR from NS 2. watchdog reset with reset reason
- Commit information
- https://github.com/Samsung/TizenRT/pull/5372

arch/arm/src/amebad/: Override secure hardfault handler to make it able to print PC/LR from NS

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv8-m/up_assert.c

Show loading binary addresses after checking app heap corruption for readability.

arrh/arm/armv7,8-m: Show loading binary addresses after checking app heap corruption

---

build/configs/rtl8721csm/scripts/rlx8721d_img2_is.ld
build/configs/rtl8721csm/scripts/rlx8721d_img2_ns.ld

To fix gnu_cxxinitialize.c build error, add _sinit, _einit to ld file.

configs/rtl8721csm/scripts: Add _sinit, _einit to support c++

---

external/mbedtls/alt/aes_alt.c

cfb128 only requires encryption key. So it doesn't need to use decrypt key.

mbedtls/alt: fix cfb128 test cases

---

external/include/protocols/webserver/http_server.h
external/webserver/http_client.c

Current timeout for read operation is 50 seconds.
Increase timeout to 300 seconds for keep-alive connection requests.

external/webserver: Increase timeout for keep-alive connections

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c
os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

Add release note in os/board/rtl8721csm/src/libs/ directory
Print wifi library version when wifi_netmgr_utils_init() is called
Log format:"wlan_version" + "lib_wlan_ver_SHA-1_YYYY/MM/DD-HH:MM:SS"
e.g."wlan_version lib_wlan_ver_1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50"
SHA-1 -> Realtek git version
YYYY/MM/DD -> compile date
HH:MM:SS -> compile time

os/board/rtl8721csm : print wifi library version

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c
tools/debug/debugsymbolviewer.py
tools/trap/ramdumpParser.py

This patch:
1) Adds debug display symbols for stack contents if sp is not within allocated
stack memory range. (PR #5339)
2) Adds symbol for addresses corresponding to (pc - 4) & (pc - 8).
3) Adds symbol location for all the displayed stack values.
4) Displays current stack values in ascending order.
5) Modifies the format of the display logs.

tools/trap: Refactor TRAP tool

---

os/include/tinyara/security_hal.h

if user request the key with wrong type then SE returns
HAL_BAD_KEY_TYPE.

security: add new result in security hal

---

apps/system/utils/README.md

Added the description of prodconfig like below.
prodconfig shows the status of hw configurations like swd enable/disable.

apps/system/utils/README.md : Add prodconfig guide

---

external/include/stress_tool/st_perf.h
external/stress_tool/st_perf.c

if st_pack is global then some members(st_performance, st_stability)
of st_smoke is defined to local variable of returned function.

stress_tool: fix st_pack is global

---

os/tools/check_package.py

This script parses the package header informations and show them.
And verify the package by calculating the crc and comparing it with the value of the header.
For example,
=== Kernel Package Header Information ===
< Cannot check the signing >
Header Size        : 12
Package Version    : 200204
File Size          : 994616
Secure Header Size : 32
* Checksum verification Done.
* Version Matched between filename and header.
=== App Package Header Information ===
< Signed App Package >
Header Size       : 41
Package Type      : ELF(1)
Main Priority     : 180
Loading Priority  : LOADING_MID(2)
File Size         : 44284
Package Name      : app
Package Version   : 190412
RAM Size          : 1213952
Stack Size        : 8192
Kernel Version    : 200204
* Checksum verification Done.
* Version Matched …

os/tools/check_package.py : Add script for checking package validation

---

os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c
os/board/rtl8721csm/src/component/os/tizenrt/rtk_wifi_utils.h

The full scan result is stored by default for 3 mins(SCAN_TIMER_DURATION) and timer is used to track it
The channel information is retrieved by comparing stored scan result with AP details from application
The partial scan is set up according to channel information which improves the join performance

os/board/rtl8721csm : Improve Wi-Fi join performance for Easy setup

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/board/common/os/tizenrt/osif_tizenrt.c

Osif timer functions are only used in RTK BLE code. LP work has a lower priority, it will be preempted by others and this will cause the timer to be inaccurate.

os/board/rtl8721csm: LPWORK to HPWORK in osif timer functions

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c

With stack alloc addr, we can get more information if there is an stack overflow.
For example, if there is a heap node corruption, but there is no overflowed prev node, then we can check the next heap node is stack or not.
If next heap node is stack node, then we can make suspicion about stack overflow.

arch/arm/v7,8-m,r/up_assert.c : Show stack alloc address when asserted

---

os/kernel/task/task_prctl.c

Fix typo : retruend to returned

kernel/task_prctl.c : Fix typo

---

os/net/lwip/configs/tcp/Kconfig

CONFIG_NET_WND_SCALE is a bool type so that it can't have a range syntax.
This causes menuconfig warnings as below:
net/lwip/configs/tcp/Kconfig:23:warning: range is only allowed for int or hex symbols
net/lwip/configs/tcp/Kconfig:23:warning: range is invalid
PR #5377 shows that range was for CONFIG_NET_TCP_RCV_SCALE. And description of that config
also says the same range.
This commit moves it to proper config to resolve the warning.

fixup! net/lwip: support window scale option

---

os/kernel/Kconfig
os/kernel/clock/clock_initialize.c

New config - CONFIG_INIT_SYSTEM_TIME_WITH_MIDNIGHT - sets system init time
to midnight. It's the same day regardless of this new config.
This is available with CONFIG_INIT_SYSTEM_TIME enabled.

kernel/clock: introduce CONFIG_INIT_SYSTEM_TIME_WITH_MIDNIGHT

---

os/mm/kmm_heap/kmm_realloc.c

To free the kheap, we should get the kheap first.

mm/kmm_realloc.c : Fix to get kheap before free

---

os/kernel/binary_manager/binary_manager_bootparam.c

Add releasing fd at failure case.
Signed-off-by: sangamanatha <sangam.swami@samsung.com>

os/kernel/binary_manager: Fix missing fd release

---

os/net/lwip/src/api/sockets.c

`recvevent` -> `receive events`
I don't think it's appropriate in context. 
Is it right to explain `receive event`"?

os/net/lwip/src/api/sockets.c : fixed comment

---

apps/examples/webserver/webserver_main.c

The certificates currently being used by the webserver have expired.
Hence, updated them with the ecdsa certificates from external.
Signed-off-by: hdotkashyap <h1.kashyap@samsung.com>

apps/examples/webserver:Update webserver certificates

---

os/kernel/binary_manager/binary_manager_bootparam.c
os/kernel/binary_manager/binary_manager_data.c
os/kernel/binary_manager/binary_manager_load.c

Change bmXdbg to printf in binary loading to make it easier to know the loading results

kernel/binary_manager: Change bmXdbg to printf in binary loading

---

tools/trap/HowToUseTrap.md
tools/trap/ramdumpParser.py

This patch:
1) Adds negative value check for (pc - 4) & (pc - 8) address values.
2) Fixes valid address checks for arm-none-eabi-addr2line command for
above addresses.
3) Removes the CONFIG_BOARD_CRASHDUMP dependency to run find_crash_point()
4) Formats log file to exclude unwanted lines.
5) Adds valid format check for log file. Looks like below
|19:27:38.36|  is not supported log format in TRAP

tools/trap: Add log formatting and some validation checks

---

apps/system/utils/netcmd_netmon.c
external/dhcpd/dhcpd_lwip.c
framework/src/ble_manager/ble_manager_state.c
framework/src/ble_manager/ble_queue.c
framework/src/wifi_manager/wifi_manager_lwnl_listener.c

To use mm APIs like malloc, free and so on, include stdlib.h

apps,external,framework : Include stdlib.h to use mm APIs

---

os/LibTargets.mk

Currently, the following mm, wqueue and lib are not being recompiled
when changes are made. Modified their respective calls to the Makefile
so that they are recompiled.

os/LibTargets.mk : modify call to Makefile for mm, wqueue and lib

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/include/tinyara/wqueue.h
os/wqueue/work_process.c

To build the work queue debug log from flat build, remove #ifdef __KERNEL__.

wqueue : Remove the condition of __KERNEL__

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c

1) Show asserted tcb info
: task state, flags, lockcount, timeslice, waitdog, waitsem, msgwaitq, sigdeliver, nsyscalls and syscall
2) Show tcb address when dump the tasks
For example,
up_show_asserted_tcb: *******************************************
up_show_asserted_tcb: Asserted TCB Info
up_show_asserted_tcb: *******************************************
up_show_asserted_tcb: State      : 3
up_show_asserted_tcb: Flags      : 33
up_show_asserted_tcb: Lock count : 0
up_show_asserted_tcb: Timeslice  : 10
up_show_asserted_tcb: Waitdog    : 0
up_show_asserted_tcb: WaitSem    : 0
up_show_asserted_tcb: MsgwaitQ   : 0
up_show_asserted_tcb: Sigdeliver : 0
up_show_asserted_tcb: Nsyscalls  : 0
up_show_asserted_tcb: Syscall    : 0x10073798
up_showtasks:                            NAME |   PID |  PRI | …

arch/armv7-m,r,v8-m/*_assert.c : Show assert tcb info and its address

---

os/arch/arm/src/amebad/amebad_flash.c
os/arch/arm/src/amebad/amebad_serial.c
os/board/rtl8721csm/src/component/common/mbed/hal/serial_api.h
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/flash_api.c
os/board/rtl8721csm/src/component/common/mbed/targets/hal/rtl8721d/serial_api.c

This PR contains modifications on uart api and flash api.
For the uart api update:
- **tx_level** is added to ensure 16 bytes of data is transmitted for each uart tx interrupt. In this way, the total number of interrupts can be reduced as well as the time used for the transmission.
For the flash api update:
- **FLASH_Write_Lock** is applied only before and after the flash write functions to reduce the overall period of FLASH_Write_Lock.

os/board/rtl8721csm: Fix uart data loss while flash write

---

os/tools/.gitignore

When build test script meets build error, it leaves build logs in build_test folder.
Because it should not be a modification in git, this commit adds build_test path
in .gitignore.
This will remove untracked files in git status like below.
Untracked files:
(use "git add <file>..." to include in what will be committed)
tools/build_test/

os/tools: add build_test path in .gitignore

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/kernel/task/Make.defs
os/kernel/task/task.h
os/kernel/task/task_dumptasks.c

There are duplicated up_showtasks and up_show_tcbinfo in each arm arch codes,
so merged into task.

kernel/task_dumptasks.c : Merge show_tasks and show_tcbinfo

---

tools/trap/ramdumpParser.py

This patch adds logs for current running worker thread.
```
vidisha@vidisha ~/tinyara/tools/trap (master) $python3 ramdumpParser.py -t wqlog
dump_file                   : None
log_file                    : wqlog
Number of binary            : 1 [kernel]
"kernel" elf_file           : ../../build/output/bin/tinyara.axf
-----------------------------------------------------------------------------------------
1. Crash Binary             : kernel
2. Crash point (PC or LR)
[ Current location (PC) of assert ]
- symbol addr        : 0x0e009ce1
- function name      : work_lpthread
- file               : /root/tizenrt/os/wqueue/kwqueue/kwork_lpthread.c:178
[ Exact crash point …
```

tools/trap: Add debug logs for work queues

---

apps/examples/smartfs/smartfs_powercut/smartfs_powercut_main.c

- Add size output of existing files during initialization of smartfs_powercut test app.

apps/examples/smartfs_powercut: Add existing file size to init logs

---

os/arch/Kconfig
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/common/up_checkstack.c
os/arch/arm/src/common/up_initialize.c

Nested irq stack is defined only in ARMv8. So, it causes build errors
for other chipsets when used in common code. Fix by adding check for
definition of nested irq stack config.

os/arch/arm: Fix build errors due to nested irq stack

---

apps/README.md
apps/examples/smartfs/buffer_optimization/Kconfig
apps/examples/smartfs/buffer_optimization/Make.defs
apps/examples/smartfs/buffer_optimization/Makefile
apps/examples/smartfs/buffer_optimization/buffer_optimization_main.c

- Using just any buffer size for reading from SmartFs files causes
repetitive reading of the same sector and degrades performance.
- We suggest the use of an optimal buffer size for reading from
SmartFs files when the content is to be read back-to-back in a loop.

[TEST PENDING] Optimization of buffer size for reading/appending SmartFs files

---

apps/examples/smartfs/buffer_optimization/buffer_optimization_main.c

- File size in Kb should be multiplied by 1024 to get correct throughput result
- Fix overflow in throughput calculation with float type variable

apps/examples/smartfs: Correct file size calculation in buffer optimization example

---

os/binfmt/Kconfig
os/binfmt/binfmt.h
os/binfmt/binfmt_copyargv.c
os/binfmt/binfmt_dumpmodule.c
os/binfmt/binfmt_exec.c
os/binfmt/binfmt_execmodule.c
os/binfmt/binfmt_exit.c
os/binfmt/binfmt_loadbinary.c
os/binfmt/binfmt_unloadmodule.c
os/binfmt/elf.c
os/binfmt/libelf/libelf.h
os/binfmt/libelf/libelf_addrenv.c
os/binfmt/libelf/libelf_bind.c
os/binfmt/libelf/libelf_ctors.c
os/binfmt/libelf/libelf_dtors.c
os/binfmt/libelf/libelf_load.c
os/binfmt/libelf/libelf_read.c
os/binfmt/libelf/libelf_sections.c
os/binfmt/libelf/libelf_unload.c
os/include/tinyara/binfmt/binfmt.h
os/include/tinyara/binfmt/elf.h
os/include/tinyara/mpu.h
os/kernel/binary_manager/binary_manager_load.c

- Remove unused and unnecessary variables
- Make changes to mpu and section allocations
- Remove addrenv since we dont use it
- Some more cleanup

os/binfmt: Refractoring binary loader

---

external/include/stress_tool/st_perf.h

If val is function then val will be called twice because val is
executed for log in printf. If function uses shared variables inside
then return value from it might be differed. So stored function value
to tmp_val and reuse it's value when print log.

st_perf: fix duplicate execution

---

apps/examples/nettest/netlog_test.c
external/netutils/netlib_netlog.c
external/stress_tool/st_perf.c
os/include/tinyara/net/netlog.h

TC pass was checked by returning value of NET_LOG API. However
previous API doesn't return correct value so TC couldn't check
validation of API. After modify APIs then change expected value of TC.

nettest/netlog: modify netlog TC

---

build/configs/artik05x/artik05x_make_bin.sh

build/configs/artik05x: Fix the build break with non standard python path
Env:
Python installed in path other than /usr/bin/python
Test Configution:
./tools/configure.sh  artik053/hello
make
Issue:
TizenRT/os/../build/configs/artik05x/artik05x_make_bin.sh:
TizenRT/build/configs/artik05x/../../../os/tools/s5jchksum.py:
/usr/bin/python: bad interpreter: No such file or directory
Makefile.unix:494: recipe for target 'post' failed
make: *** [post] Error 126
Cause:
artik05x_make_bin.sh requires python to be installed at /usr/bin/python
but it is possible to install python in other path and export system wide.
Measure:
Invoke the script with python which avoids looking for /usr/bin/python

build/configs/artik05x: Fix the build break with non standard python path

---

lib/libc/netdb/lib_freeaddrinfo.c
lib/libc/netdb/lib_getaddrinfo.c
lib/libc/netdb/lib_gethostbyname.c
lib/libc/netdb/lib_getnameinfo.c

Those APIs freeaddrinfo, getaddrinfo printed same error log if ioctl
was failed. To distinguish the log add function information.

lib/libc: add additional log information

---

os/se/ameba/rtl_security_api_wrapper_tz.c

Allow to print secure log using non-secure print to prevent mixed log

os/se/ameba: Link non-secure print to Secure

---

lib/libc/syslog/lib_lowsyslog.c
os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/drivers/memory/mminfo.c
os/include/debug.h
os/include/tinyara/fs/ioctl.h
os/include/tinyara/mm/mm.h
os/mm/Kconfig
os/mm/mm_heap/mm_check_heap_corruption.c
os/mm/mm_heap/mm_heapinfo_parse_heap.c
os/mm/mm_heap/mm_manage_allocfail.c

- Add ioctl call for mm_alloc_fail in app separation
- Change some logs from dbg to lldbg
- Disable irq during mm_alloc_fail
- Disable irq during assert handler
Disable irq during lldbg to avoid mixed logs. When irq is disabled,
then printf and dbg logs will not get printed.

Fix mm_alloc_fail mixed logs

---

apps/examples/webserver_test/webserver_test_main.c

Fixed keep-alive to process all keep-alive responses by resetting read_finish

apps/examples/webserver_test: Fix keep-alive

---

os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

Store the bssid that encrypted by password.
To verify password matched with pmkid during Pre-Authentication for pmk caching.

os/board/rtl8721csm: fix able to connect WPA3 ap with wrong pwd issue

---

os/binfmt/libelf/libelf_addrenv.c

Fix build error due to missing loadinfo variable in log

os/binfmt: Fix compile error in binfmt log

---

.circleci/config.yml

- Migrating CI from Ubuntu 14.04 to Ubuntu 20.04

CircleCI: Migrating CI from Ubuntu 14.04 to Ubuntu 20.04

---

os/kernel/task/task_prctl.c

Passed argument pid is used only when PR_GET/SET_NAME_BYPID.
For PR_GET/SET_NAME case, pid can be ignored, debug message can makes confusion if sched_gettcb() fails.

os/kernel/task_prctl.c : Fix to check passed pid only when get/set_BYPID

---

os/mm/mm_heap/mm_getsize.c

mm_heap/mm_getsize.c:82:30: error: extra tokens at end of #ifdef directive [-Werror]
#ifdef CONFIG_TASK_NAME_SIZE > 0

mm/mm_getsize.c : Fix build error about #if macro

---

os/kernel/log_dump/log_dump.c

1. Build Error
log_dump/log_dump.c: In function 'log_dump_save':
log_dump/log_dump.c:135:18: error: storage size of 'mem' isn't known
struct mallinfo mem;
2. Build Warning
log_dump/log_dump.c:63:1: warning: useless storage class specifier in empty declaration
};

kernel/log_dump.c : Fix build error and warning

---

apps/system/utils/utils_kill.c

utils_kill.c: In function 'utils_killall':
utils_kill.c:336:8: warning: implicit declaration of function 'mount' [-Wimplicit-function-declaration]
ret = mount(NULL, PROCFS_MOUNT_POINT, PROCFS_FSTYPE, 0, NULL);
^
utils_kill.c:358:9: warning: implicit declaration of function 'umount' [-Wimplicit-function-declaration]
(void)umount(PROCFS_MOUNT_POINT);

apps/system/utils_kill.c : Fix build warning

---

os/arch/arm/src/common/up_createstack.c
os/binfmt/binfmt.h
os/binfmt/binfmt_execmodule.c
os/binfmt/binfmt_unloadmodule.c
os/include/tinyara/binfmt/binfmt.h
os/kernel/pthread/pthread_create.c
os/kernel/task/task_create.c

If app separation is enabled, then only apps must be allowed to create
task and pthreads. Kernel can only create kthreads. If kernel side code
tries to create task or pthread, it will result in an ASSERT.

os/kernel: Prevent task and pthread creation from kernel threads

---

os/tools/check_output_size.py
os/tools/check_package.py
os/tools/config_util.py
os/tools/mkbinheader.py
os/tools/mkbootparam.py
os/tools/mksamsungheader.py
os/tools/set_bininfo.py

1. There are many duplicated util functions. So integrated.
1) get_value_from_file() checks that passed argument(target) is in the file or not, and returns the value if exist.
2) check_config_existence() checks that passed argument(config) is in the file and not starts with '#'.
3) get_binname_from_bininfo() returns the binary name read from .bininfo
2. Change indentation from tab to 4 spaces
It is recommended to use Python Coding rule based on PEP 8.
(PEP 8 : python.org/dev/peps/pep-0008)
So change the indentations from tab to 4 spaces.

os/tools/*.py : Integrate common util functions

---

apps/examples/log_dump/log_dump_main.c
os/drivers/serial/serial.c
os/fs/procfs/fs_procfslogsave.c
os/include/tinyara/log_dump/log_dump.h
os/include/tinyara/log_dump/log_dump_internal.h
os/kernel/init/os_start.c
os/kernel/log_dump/log_dump.c

To control the log saving, add start and stop functionality.
Log will be saved by default if log dump config is enabled.
Usage:
#include <tinyara/log_dump/log_dump.h>
START_LOGDUMP_SAVE(fd); //To start the log saving
STOP_LOGDUMP_SAVE(fd);  //To stop the log saving
Example:
TASH>>log_dump
TASH>>This Log Should NOT be saved!!!
log_dump_main: 
*********************   LOG DUMP START  *********************
This Log Should be saved!!!
System Information:
Version:
Platform: 3.1	Binary: 200204
Commit Hash: b008e5f
Build User: root@jeongchanKim
Build Time: 2022-03-28 09:50:21 KST
System Time: 06 Dec 2011, 00:00:00 [s] UTC 
TASH>>
TASH>>
TASH>>log_dump
TASH>>This Log Should be saved!!!
log_dump_main: 
*********************   LOG DUMP END  ***********************
Signed-off-by: …

os/kernel/log_dump.c : Add start and stop functionality

---

apps/examples/testcase/le_tc/kernel/tc_umm_heap.c

Covered APIs :
umm_get_heap_free_size(), umm_get_largest_freenode_size()
Scenarios :
Compare to return of each APIs and return of mallinfo
Test Result :
[umm_get_heap_free_size] PASS
[umm_get_largest_freenode_size] PASS

apps/examples/tc_umm_heap.c : Add get free/largest size TC

---

apps/examples/webserver/webserver_main.c
external/include/protocols/webserver/http_server.h
external/webserver/http_client.c

API http_send_response_chunk sends response to client in chunk
format

external/webserver: Implement API for chunk transfer from webserver

---

os/Makefile.unix
os/tools/check_output_size.py

Public and private repos use different number of apps. So, while
building the app binaries, check the corresponding config and
build only the required app binaries.

os/Makefile.unix: Make common changes for app build in all repos

---

build/configs/rtl8721csm/rtl8721csm_make_bin.sh

Binary signing is not supported on public repo.
So call the function to make binary without binary signing even if CONFIG_BINARY_SIGNING is enabled.

build/configs/rtl8721csm: No support binary signing when making binary

---

os/fs/smartfs/smartfs.h
os/fs/smartfs/smartfs_smart.c
os/fs/smartfs/smartfs_utils.c

1. Separate entry finding and length calculation functionalities of smartfs_finddirentry function into 2 separate functions
2. Invoke smartfs_get_datalen while opening the file only when length of the file is required to be known
3. Invoke smartfs_get_datalen if an operation requires the length of the file to be known but the length has not been calculated yet

[Under Powercut] Optimize Opening time of files in jSmartFs

---

os/arch/arm/src/armv7-m/mpu.h
os/arch/arm/src/armv7-m/up_busfault.c
os/arch/arm/src/armv7-m/up_memfault.c
os/arch/arm/src/armv7-m/up_usagefault.c
os/arch/arm/src/armv8-m/mpu.h
os/arch/arm/src/armv8-m/up_busfault.c
os/arch/arm/src/armv8-m/up_memfault.c
os/arch/arm/src/armv8-m/up_usagefault.c

Refactor debug messages in fault hanlders and mpu code to provide
clear and accurate information.
Sample output after refactoring
```
up_memfault: #########################################################################
up_memfault: PANIC!!! Memory Management Fault at instruction : 0x02200196
up_memfault: FAULT TYPE: DACCVIOL (Data access violation occurred. Check MPU RW permissions).
up_memfault: FAULT ADDRESS: 0x0e000020
up_memfault: FAULT REGS: CFAULTS: 0x00000082 MMFAR: 0x0e000020
up_memfault: #########################################################################
```
```
mpu_show_regioninfo: ********************************************************************************************
mpu_show_regioninfo: REGION_NO.         BASE_ADDRESS    SIZE            STATUS          ACCESS …
```

os/arch: Refactor debug messages

---

os/net/netmgr/netdev_wifi.c

-This PR fixes LWNL_EVT_SCAN_FAILED when there is no AP

netmgr/netdev_wifi.c: scan count is 0 with no AP

---

apps/examples/board_specific_demo/cy4390x_demo/Kconfig_ENTRY
apps/examples/board_specific_demo/esp32_wifi_demo/Kconfig_ENTRY
apps/examples/libcoap/client/Kconfig_ENTRY
apps/examples/libcoap/server/Kconfig_ENTRY
apps/examples/security_test/security_api/Kconfig_ENTRY
apps/examples/smartfs/buffer_optimization/Kconfig_ENTRY
apps/examples/smartfs/smart/Kconfig_ENTRY
apps/examples/smartfs/smart_test/Kconfig_ENTRY

- apps/examples: Add missing Kconfig_ENTRY files in sub-directories.

apps/examples: Add missing Kconfig_ENTRY files in sub-directories

---

os/drivers/serial/serial.c

Currently log_dump stores all the data that is sent via the serial driver
interface. Updated log_dump to only store the console logs.

drivers/serial: Update log_dump to only store console logs

---

tools/debug/debugsymbolviewer.py
tools/trap/ramdumpParser.py

This patch adds heap corruption logs to TRAP tool and displays
the appropriate file location for possible corrupted node allocation.
Logs look like below:
$sudo python3 ramdumpParser.py -t 31
dump_file                   : None
log_file                    : 31
Number of binary            : 1 [kernel]
"kernel" elf_file           : ../../build/output/bin/tinyara.axf
.
.
.
4. Miscellaneous information:
mm_check_heap_corruption: #######################################################################################
mm_check_heap_corruption: ERROR: Heap node corruption detected.
mm_check_heap_corruption: ====================================================================== …

tools: Add heap corruption log data to TRAP tool

---

apps/Directory.mk
apps/examples/board_specific_demo/Makefile
apps/examples/dtls/Makefile
apps/examples/grpc/Makefile
apps/examples/libcoap/Makefile
apps/examples/performance/Makefile
apps/examples/protobuf/Makefile
apps/examples/security_test/Makefile
apps/examples/smartfs/Makefile
apps/examples/tls/Makefile
apps/examples/wifi_manager/Makefile

- Multiple applications of the same domain will be presented in a separate sub-menu
under the "Application Configuration" menuconfig tab.
- Added MENUDESC option in Makefiles of subfolders to initiate presentation of
applications as a separate sub-menu
- Added preconfig options in Makefiles for subfolders to include dependant
applications in this separate sub-menu.

apps: Restructure menuconfig options into sub-menus

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/binfmt/binfmt_exit.c
os/binfmt/binfmt_initialize.c
os/binfmt/binfmt_loadbinary.c
os/binfmt/libelf/libelf.h
os/binfmt/libelf/libelf_sections.c
os/include/tinyara/binfmt/elf.h

save binary section address information, g_bin_addr_list in static memory for debugging when kernel heap corruption.

binfmt: save binary section addresses in static memory for debugging

---

tools/debug/debugsymbolviewer.py
tools/trap/HowToUseTrap.md
tools/trap/ramdumpParser.py

In previous commit id 24f18d12108e8260703f8ee8b035d80841d53fca, the API
name is changed from elf_show_all_bin_addr to elf_show_all_bin_section_addr.
So, we need to update in the script files to search the new name to find
the proper address of app text section.

tools: Update new API name while parsing logs

---

tools/debug/debugsymbolviewer.py
tools/trap/ramdumpParser.py

1. Add the Assertion failed at log
2. Add the running work function's corresponding symbol
3. Refactor comments
```
2. Crash type               : code assertion by code ASSERT or PANIC
Crash log                : up_assert: Assertion failed at file:mm_heap/mm_mallinfo.c line: 134 task: hpwork
3. Crash point (PC or LR)
PC & LR values not in any text range! No probable crash point detected.
4. Call stack of last run thread
- Current running work function is:	 0xe041e81
Current running work function		File_name
0xe041e81				/root/tizenrt/apps/da_module/da_common_event_pubsub/src/da_common_event_pubsub.c:162
- Current stack pointer:		 0x10064780
Stack_address	 Symbol_address	 Symbol location  Symbol_name		File_name
0x10064798	 0x10013014	 kernel  	  sem_unblock_task …
```

tools/trap: Add below requirements

---

external/json/cJSON.c

Without including stdbool.h, there can be build error from true and false.
error: ‘false’ undeclared (first use in this function); did you mean ‘pause’?
return false;
^~~~~
pause

external/json/cJSON.c : Include stdbool.h for true and false

---

external/include/miniz/miniz.h

Disable optional miniz APIs that are not being used
https://github.com/Samsung/TizenRT/blob/6c94db748e7e50a7d9a0e3e75df533ddf730f961/external/include/miniz/miniz.h#L24-L25

external/include/miniz: disable optional unused miniz APIs

---

os/se/ameba/rtl_security_api_wrapper_tz.c
os/se/ameba/security_ameba_wrapper_tz.c

Remove calling device lock from Secure
Protect SE Secure API with Flash operation with device lock

os/se/ameba: Fix hardfault caused by device lock calling from Secure

---

apps/examples/log_dump/log_dump_main.c

After the addition of log_dump start and stop, we no longer
need to use lldbg to avoid saving log_dump command output to
the compressed logs.

examples/log_dump: change lldbg to printf

---

os/arch/arm/src/amebad/Make.defs
os/arch/arm/src/imxrt/Make.defs

librtl.a is a library used for imxrt board which has an external
rtk wifi chip. This library is wrongly included in rtk board
Makefile. This commit moves it to the proper imxrt Makefile.

os/arch: Move wifi library from rtk to imxrt makefile

---

os/kernel/log_dump/log_dump.c

The variable writesize provides the output buffer size to the compression
algorithm. So before compression, reset the writesize variable.

kernel/log_dump: reset writesize to blocksize before compression

---

loadable_apps/loadable_sample/Kconfig

loadable_apps/loadable_sample: enable app info only in loadable config

---

os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.c

Some AP requires board to be disconnected first before trying to connect to same AP

os/board/rtl8721csm : Enable driver to send deauth before auth packet

---

apps/examples/wifi_manager/wm_test/wm_test.c

- Fix hardfault when it receives wrong command of wm_test

apps/wm_test: fix wrong cmd hardfault

---

os/mm/umm_heap/umm_calloc.c
os/mm/umm_heap/umm_malloc.c
os/mm/umm_heap/umm_memalign.c
os/mm/umm_heap/umm_realloc.c
os/mm/umm_heap/umm_zalloc.c

If app separated, user has single heap, not multi heap.
So when allocating the memory, we don't need to check the multi-region.
* User heap supports a single heap on app binary separation.

mm/umm_heap : Allocate memory into single heap user

---

os/kernel/task/task_dumptasks.c

```
task_show_alivetask_list:             NAME |   PID |  PRI | TOTAL STACK | STACK ALLOC ADDR | TCB ADDR
task_show_alivetask_list: ---------------------------------------------------------------------------
task_taskdump:        Idle Task |     0 |    0 |    1024 |       0x20003888 | 0x2000046c
task_taskdump:             tash |     2 |  125 |    4076 |       0x24002120 | 0x24001cb0
task_taskdump:          appmain |     3 |  100 |    1004 |       0x24001430 | 0x24001010
```

kernel/task : fix taskdump table header printing format

---

os/board/rtl8720e/src/component/soc/amebalite/fwlib/ram_common/ameba_clk.c

Workaround for 131k calibration issue in Acut, add more delay time to stable.

os/board/rtl8720e/src/component/soc/amebalite/fwlib/ram_common: Workaround for A cut 131K calibration.

---

os/Makefile.unix
os/tools/check_package_header.py
os/tools/check_package_size.py
os/tools/validate_output.py

Call script for checking package validation after build.
It parses the package header information and show them.
And verify the package by calculating the crc and comparing it with the value of the header.

os/tools: Validate packages after build

---

os/kernel/binary_manager/binary_manager.c

The size of bootparam should be 8Kbytes.

kernel/binary_manager: Fix typo of bootparam size, 8K

---

os/board/rtl8720e/src/component/mbed/targets/hal/rtl8720e/i2s_api.c
os/board/rtl8720e/src/component/soc/amebalite/fwlib/ram_common/ameba_sport.c

Resolve SVACE warnings with WGID from 244015~244019.

os/board/rtl8720e: Resolve SVACE warnings with WGID from 244015~244019.

---

os/board/rtl8720e/src/component/wifi/promisc/wifi_promisc_inic_ipc.c

Fix SVACE warnings: 244012, 244029, 244030, 244040

os/board/rtl8720e: fix SVACE defects in wifi_promisc_inic_ipc.c

---

os/board/rtl8720e/src/component/wifi/driver/include/wifi_constants.h
os/board/rtl8720e/src/component/wifi/wifi_interactive_mode.c

Resolve 244021 by initializing pscan_config to 0
Resolve 244060 by modifying rtw_security_t to long

os/board/rtl8720e: Resolve SVACE warnings with WGID 244021 and 244060

---

os/board/rtl8720e/src/component/wifi/wpa_supplicant/wpa_supplicant/wifi_eap_config.c

Resolve 244051 by removing retry_count part on wifi_eap_config.c

os/board/rtl8720e: Resolve SVACE warnings with WGID 244051

---

os/board/rtl8720e/src/component/bluetooth/rtk_stack/example/ble_peripheral/ble_tizenrt_service.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_service.c

Add NULL checking to avoid memory dereference

os/board/rtl872X: Add NULL checking to avoid memory dereference

---

os/board/rtl8720e/src/component/mbed/targets/hal/rtl8720e/i2c_api.c

Resolve SVACE i2c_api.c warnings with WGID from 191360~191361.

os/board/rtl8720e: Resolve SVACE i2c_api.c warnings with WGID from 191360~191361.

---

os/board/rtl8720e/src/component/soc/amebalite/fwlib/usrcfg/ameba_pinmapcfg.c

Change PA_19 from GPIO_PuPd_DOWN to GPIO_PuPd_UP, further changes might be made once the final defaul pulling table been settle done.

os/board/rtl8720e: Correct the internal pull up/pull down option for PA_19, LogUART RX, to pull up.

---

os/board/rtl8720e/src/component/wifi/wifi_interactive_mode.c

Resolve 244038 and 244039 by null terminating the string 
Resolve 244061 by using strncpy instead of strcpy and null terminating the string

os/board/rtl8720e: Resolve SVACE warnings with WGID 244038/244039/244061

---

os/binfmt/binfmt_loadbinary.c

Add NULL checking to avoid dereference

os/binfmt: Add NULL checking to avoid dereference

---

os/se/ameba/security_ameba_wrapper_tz.c

Added TP1E Samsung Key Address with condition checking for the board type

os/se/ameba: Added TP1E Samsung Key Address

---

os/board/rtl8720e/src/component/mbed/targets/hal/rtl8720e/us_ticker.c

The value of an arithmetic expression tick_cnt * (1000000 / 32768) is subject to overflow due to a failure to cast operands to a larger data type before perfoming arithmetic

os/board/rtl8720e: Result value typecasting for us ticks

---

apps/examples/board_specific_demo/ameba_secure_storage_demo/README.txt
apps/examples/board_specific_demo/ameba_secure_storage_demo/secure_storage.c

- Write user defined input to Secure Storage space at the given slot indices
- If no user input is given, use default values as before

apps/examples/board_specific_demos: Modify Ameba Secure Storage Demo

---

os/include/tinyara/math.h

Include type definition of float math.h doesn't include type definition of float_t, so add it.
It is required as per posix standard.

libc/math : Add float_t data type

---

os/drivers/memory/mminfo.c
os/include/debug.h
os/include/tinyara/mm/mm.h
os/mm/kmm_heap/kmm_calloc.c
os/mm/kmm_heap/kmm_malloc.c
os/mm/kmm_heap/kmm_memalign.c
os/mm/kmm_heap/kmm_realloc.c
os/mm/kmm_heap/kmm_zalloc.c
os/mm/mm_heap/mm_manage_allocfail.c
os/mm/umm_heap/umm_calloc.c
os/mm/umm_heap/umm_malloc.c
os/mm/umm_heap/umm_memalign.c
os/mm/umm_heap/umm_realloc.c
os/mm/umm_heap/umm_zalloc.c

When we print information about memory alloc failure, it is good to print the caller address so that during debugging we can immediately find out where the memory request was made. Add the caller address information to all memory failure cases.
Also, use lldbg instead of dbg to print mm fail logs in flat build.

os/mm: Add caller address to mm alloc fail API

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

The modification can handle the scenarios listed as below:
1. If there is no external operation over 100ms, adv start success.
nRF is able to scan the device.
2. If a master tries to connect TP1x within 100ms, connection built and new_state.gap_adv_state changed to idle. 
adv start success and build connection with other devices, so we think this adv_start operation success under such case. nRF will unable to see device after return success.
3. If a master tries to connect TP1x within 100ms, connection built but disconnect within 100ms as well. 
we think this adv_start operation success under such case. But nRF will unable to see TP1x in this case. Customers need to check log to debug.
Non-connectable cases:
1. start non-connectable adv as the first adv -> return success
2. start …

os/board/rtl8721csm: Modify do-while check in rtw_ble_server_start_adv(...) API

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-m/up_doirq.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/armv8-m/up_doirq.c
os/arch/arm/src/common/up_checkstack.c
os/include/tinyara/arch.h
tools/debug/debugsymbolviewer.py
tools/trap/ramdumpParser.py

This patch adds debug logs for IRQ during assert.
Sample logs are as follows:
up_hardfault: PANIC!!! Hard fault: 40000000
up_assert: Assertion failed at file:armv8-m/up_hardfault.c line: 204 task: tash
up_dumpstate: sp:     0218562c
up_dumpstate: Code asserted in nested IRQ state!
up_dumpstate: IRQ num: 4
up_dumpstate: IRQ handler: 0e008fd5
up_dumpstate: stack base: 02185878
up_dumpstate: stack size: 00000fec
up_dumpstate: stack used: 00000334
up_stackdump: 02185620: xxxxxxxx xxxxxxxx xxxxxxxx 000000cc 1007222c 00000001 00000330 00000018
up_stackdump: 02185640: 0e006a1b 00000003 0e00715d 0e00679d 0000002c 1002c1ec 1002c1ec 1002a9d0
up_stackdump: 02185660: 00000003 0218569c 0218570c 00000001 00000330 00000018 0e00940d 0e0093e5
up_stackdump: 02185680: 10012169 1002c1ec 1002a9d0 00000004 …

Add new IRQ and refactor debug logs during assertion and update TRAP tool accordingly 

---

os/tools/check_package_size.py
os/tools/validate_output.py

When the binary size exceeds the partition size, the build should terminate, but instead the build continues. Fixed this by exiting the parent process.
current version :
```
========== Size Verification of built Binaries ==========
KERNEL	Binary Size :    795,456 bytes	Partition Size :  1,835,008 bytes
APP1	Binary Size :        824 bytes	Partition Size :    524,288 bytes
APP2	Binary Size :      4,495 bytes	Partition Size :  1,040,384 bytes
COMMON	Binary Size :    359,336 bytes	Partition Size :     16,384 bytes
!!!!!!!! ERROR !!!!!!!
Built COMMON (359,336 bytes) is greater than its partition (16,384 bytes).
COMMON Binary will be deleted. Need to re-configure the partition using menuconfig and to re-build.
=> Size verification SUCCESS!! The size of all binaries are OK.
=== Kernel Package …
```

os/tools: terminate build when binary size exceeds partition size

---

apps/examples/board_specific_demo/ameba_secure_storage_demo/Kconfig_ENTRY
apps/examples/board_specific_demo/ameba_wifi_csi_demo/Kconfig_ENTRY

Kconfig_Entry should define a ENTRY_* config to provide entry point selection in menuconfig. But ameba_secure_storage_demo and ameba_wifi_csi_demo duplicate define EXAMPLES_* configs which are already defined in Kconfig.
This commit fixes the error on menuconfig as shown below.
/root/tizenrt/apps/examples/board_specific_demo/ameba_secure_storage_demo/Kconfig:7:warning: choice value used outside its choice group /root/tizenrt/apps/examples/board_specific_demo/ameba_secure_storage_demo/Kconfig:8:warning: defaults for choice values not supported /root/tizenrt/apps/examples/board_specific_demo/ameba_wifi_csi_demo/Kconfig:7:warning: choice value used outside its choice group /root/tizenrt/apps/examples/board_specific_demo/ameba_wifi_csi_demo/Kconfig:8:warning: defaults for choice values not …

examples/board_specific_demo/ameba_*: fix typo of entry config

---

os/drivers/bluetooth/virtual_ble/Kconfig

The Kconfig under os/drivers/bluetooth defines the config VIRTUAL_BLE already. But commit 3665952 duplicate defines it. That's why it makes the warning as below. This commit fixes it.
drivers/bluetooth/virtual_ble/Kconfig:2:warning: choice value used outside its choice group drivers/bluetooth/virtual_ble/Kconfig:3:warning: defaults for choice values not supported drivers/bluetooth/Kconfig:27:error: recursive dependency detected! For a resolution refer to Documentation/kbuild/kconfig-language.txt subsection "Kconfig recursive dependency limitations" drivers/bluetooth/Kconfig:27:	choice <choice> contains symbol VIRTUAL_BLE For a resolution refer to Documentation/kbuild/kconfig-language.txt subsection "Kconfig recursive dependency limitations" drivers/bluetooth/Kconfig:31:	symbol VIRTUAL_BLE …

drivers/bluetooth/virtual_ble: remove duplicated config, VIRTUAL_BLE

---

lib/libc/stdio/lib_sscanf.c
lib/libc/string/lib_strdup.c
os/drivers/bch/bchdev_unregister.c
os/drivers/bch/bchlib_read.c
os/drivers/bch/bchlib_write.c
os/mm/mm_heap/mm_check_heap_corruption.c

lib_strdup.c:73 - Use of vulnerable function 'strcpy' at lib_strdup.c:73. This function is unsafe, use strncpy instead. bchdev_unregister.c:124 - Uninitialized data is read from local variable 'bch' at bchdev_unregister.c:124. bchlib_write.c:139 - Division by zero
bchlib_read.c:152 - Division by zero
mm_check_heap_corruption.c:205 - After having been compared to NULL value at mm_check_heap_corruption.c:165, pointer 'prev' is passed as 1st parameter in call to function 'dump_node' at mm_check_heap_corruption.c:205, where it is dereferenced at mm_check_heap_corruption.c:104.

os, lib: Fix Svace issues

---

build/configs/rtl8720e/loadable_apps/Make.defs
os/arch/arm/src/amebalite/Make.defs

1. configs/rtl8720e/loadable_apps: fix typo, rtl8721csm -> rtl8720e
2. arch/arm/amebalite: add amebalite_signature.c in Make.defs

rtl8720e: fix typo

---

os/mm/mm_heap/mm_manage_allocfail.c

When memory alloc is failed, we must always print largest free node and total free space in the heap.

os/mm: Fix issue in mm_manage_allocfail

---

os/arch/xtensa/src/xtensa/xtensa_assert.c
os/include/debug.h
os/mm/mm_heap/mm_check_heap_corruption.c
os/mm/mm_heap/mm_manage_allocfail.c

This patch is for change in mfdbg to use lldbg instead of dbg in flat build
The logs get stuck for flat build, when there is heap corruption.
Change the mfdbg to use lldbg.
With the change the logs are getting displayed correctly.
LOGS BEFORE 
System Information:
Version:
Platform: 3.1 up_assert: Assertion failed at file:hello_main.c line: 83 task: appmn
up_dumpstate: Code asserted in normal thread!
up_dumpstate: Current SP is User Thread SP: 1006e6c8
........
TASH>>
mm_check_heap_corruption: ###########################################################################
mm_check_heap_corruption: ERROR: Heap n
LOGS AFTER CHANGE
up_assert: Assertion failed at file:hello_main.c line: 83 task: hello
.......
mm_check_heap_corruption: …

os/include/debug.h: Change the conditionals for mfdbg from dbg to lldbg

---

os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/xtensa/src/xtensa/xtensa_assert.c
os/include/assert.h
os/kernel/semaphore/sem_post.c

debugging
THis patch updates the up_assert() API with an extra argument to print information useful for debugging.
Sample assert logs are as below:
TASH>>binary_manager_load_binary: Load success! [Name: app2] [Version: 190412] [Partition: A] [Compressed Binary] Test will be finished
nup_assert: Assertion failed at file:wifiapp.c line: 128 task: app2 assertInfo = TESTSTRING
up_dumpstate: sp:     021837b4
up_dumpstate: Nested IRQ stack:
up_dumpstate:   base: 1002a9b0
up_dumpstate:   size: 00000200
up_dumpstate:   used: 00000000
up_dumpstate: stack base: 02183860
up_dumpstate: stack size: 00001fe4
up_dumpstate: stack used: 00000278
up_stackdump: 021837a0: xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx 00000080 100718ac 02257a88
up_stackdump: 021837c0: 02200343 022579cc 022579e4 02257a04 …

arch/arm/src: Update assert code to accomodate extra arguments for

---

docs/HowToDebug.md
os/dutils.sh
tools/trap/HowToUseTrap.md
tools/trap/ramdumpParser.py

Sample execution logs are as below:
For default build binary >
```
======================================================
"Select Option"
======================================================
"1. Run Toolchain Command"
"2. Run TRAP Debug tool"
"h. Help"
"x. Exit"
======================================================
2
======================================================
"Run TRAP tool for"
======================================================
"1. Default binary from previous build at build/output/bin location"
"2. Custom binary at any location"
"x. Exit"
======================================================
1
Enter the crash log file name: (ex: ../tools/trap/testlogs)
logs
Executing: ramdumpParser.py -t logs
dump_file …
```

Trap support on docker

---

apps/system/utils/fscmd.c

Currently it didn't check argc condition properly, hence add logic to prevent assert

fs/fscmd : Prevent assert when argc is smaller than 2 or greater than 3

---

os/fs/smartfs/smartfs_utils.c

- Entry timestamps of type uint32_t are mistakenly stored as type uint16_t for comparison checking
- They should be stored and compared as type uint32_t for effective functioning

os/fs/smartfs: Fix mismatched type of jSmartFs entry timestamps

---

os/include/tinyara/mm/mm.h
os/mm/mm_heap/mm_heapinfo_utils.c

Malloc API caller address is saved in alloc_call_addr of chunk(alloc node). If wrapping malloc API, The caller address becames warpped function address.
This commit adds macro(DEBUG_SET_CALLER_ADDR), that recives allocated memory address and sets caller address of current funtion to alloc_call_addr of chunk.
When warpping malloc API, have to update caller address with this macro.

mm/mm_heap: add DEBUG_SET_CALLER_ADDR() macro.

---

os/.gitignore
os/dutils.sh

This patch adds an option to store the output of the commands to a file with the name of command and timestamp as below:
>> Output is stored in dutils_output_addr2line_2023.01.12-18.21.24.txt
>> Output is stored in dutils_output_trap_2023.01.12-18.20.20.txt
>> Output is stored in dutils_output_nm_2023.01.12-18.22.39.txt

dutils.sh: Add option to store output to a file

---

os/board/rtl8721csm/src/Makefile

The below lines add duplicate CFLAG.
152:      CFLAGS += -I$(TOPDIR)/arch/$(CONFIG_ARCH)/src/armv8-m
194,204:  CFLAGS += -I$(ARCH_SRCDIR)/armv8-m
154:      CFLAGS += -I$(COMPONENT_DIR)/soc/realtek/amebad/cmsis
196,202:  CFLAGS += -I$(COMPONENT_DIR)/soc/realtek/amebad/cmsis
If there are more duplicate CFLAG, we can get warning message like below line. 
ERROR: Path+file is too long [4107/4096]
It might be became potential error, This commit removes duplicate CFLAG.

os/board/rtl8721csm/src/Makefile: Remove duplicate CFLAG

---

os/include/assert.h

- DEBUGASSERT_INFO gives out a descriptive output similar to ASSERT_INFO in case of DEBUGASSERTs
Sample output: -
```
up_assert: Assertion failed at file:hello_main.c line: 71 task: appmain
up_assert: This is DEBUGASSERT_INFO in hello
up_dumpstate: Code asserted in normal thread!
up_dumpstate: Current SP is User Thread SP: 20090758
```

os/include: Add DEBUGASSERT_INFO macro for descriptive debug output in case of DEBUGASSERT

---

apps/system/utils/utils_heapinfo.c
os/drivers/memory/mminfo.c
os/include/tinyara/mm/mm.h
os/mm/mm_heap/Make.defs
os/mm/mm_heap/mm_check_heap_corruption.c
os/mm/mm_heap/mm_heap_dbg.c
os/mm/mm_heap/mm_heapinfo_parse_heap.c
os/mm/mm_heap/mm_heapinfo_utils.c

Allow user to dump entire heap regions using heapinfo command. Add new option -d for dumping heap. The -d option may be followed by option "kernel" or the app name to indicate the heap to be dumped.

os/mm: Add heap dump option to heapinfo cmd

---

os/wqueue/kwqueue/kwork_hpthread.c
os/wqueue/kwqueue/kwork_lpthread.c

The lldbg have to used only when OS doesn't work normally, such as OS init or assert or other special cases. 
However, This case is OS normal operation. so This commit changes slldbg to sdbg.

os/wqueue/kwqueue: Change slldbg to sdbg in wqueue.

---

os/mm/mm_heap/mm_check_heap_corruption.c

Modify the heap region dump api to mm_dump_heap_region in the heap corruption code. This change was missed out in previous commit when the API was changed from heapinfo_dump_heap_region to mm_dump_heap_region.

mm: Modify heap region dump API

---

os/include/tinyara/mm/mm.h
os/kernel/Kconfig
os/kernel/init/os_bringup.c
os/kernel/log_dump/log_dump.c

If log dump is enabled, and we run heapinfo command, then there is a hang issue. This is because, the heapinfo command locks the kernel heap. But, at the same time heapinfo logs are sent to log dump module which tries to allocate buffer. Since, the heap is already locked by the heapinfo command, it results in a lock-up.
To overcome this issue, upon entering logdump api we will check if the kernel heap is locked before performing the log dump operations which require memory to be allocated or freed. The log dump operation will not be performed as long as the heap is locked. So, any logs printed during this time will not get included in the log dump.

log_dump.c: Fix hang issue in log dump module

---

os/tools/check_package_size.py

This PR adds build log about the ratio of flash memory used for each partition.
The usaed ratio means (Binary Size)/(Partition Size) and is divided into PASS, WARNING, FAIL according to used ratio.
- PASS: The used ratio is 95% or less.
- WARNING: The used ratio exceeds 95%.
- FAIL: Binary size is larger than partition size. It is build fail.
The printed build log examples are as below.
case1
```
========== Size Verification of built Binaries ==========
Type        Binary Size     Partition Size      used(%)
KERNEL   1,110,848 bytes    1,835,008 bytes     60.54%    PASS
=> Size verification SUCCESS!! The size of all binaries are OK.
```
case2
```
========== Size Verification of built Binaries ==========
Type        Binary Size     Partition Size      used(%)
KERNEL     795,456 bytes …
```

os/tools/check_package_size.py : add used ratio of flash memory

---

os/board/rtl8720e/src/component/os/tizenrt/rtk_netmgr.c

Fix the softap return for fail case
After modification, get info no longer returns incorrect value for fail case

os/board/rtl8720e : fix softap fail case

---

os/board/rtl8720e/src/component/os/tizenrt/ethernetif_tizenrt.c
os/board/rtl8720e/src/component/os/tizenrt/rtk_netmgr.c
os/board/rtl8720e/src/component/wifi/inic/inic_ipc_host_trx.c

Fix check for wlan idx by using flag, previous implementation affected throughput
In 10.1a SDK update, STA is wlan idx 0 and SOFTAP is wlan idx 1 in Wi-Fi driver
Because application layer is using wlan idx 0 regardless of STA or SOFTAP, it needs to know whether to send to STA (idx 0) or SOFTAP (idx 1) when application is sending data to Wi-Fi driver. This is done by checking whether application layer is in SOFTAP mode
Previously, this was done using wifi_is_running(), but it affected the Wi-Fi throughput and caused a bottleneck
This PR will resolve the bottleneck by using a flag "softap_flag" to check whether application is in SOFTAP mode and send data to the Wi-Fi driver with the correct idx

os/board/rtl8720e: Fix wlan idx selection

---

os/kernel/debug/mem_leak_checker.c

Modify print format to indicate byte which is unit of leak memory size.
And modify the spaces so that the lines are aligned.
1)Before
```
Type   |    Addr   |   Size   |  Owner  | PID
---------------------------------------------------
LEAK   |  0x1006fef0  |       16 | 0xe007899 | 9
LEAK   |  0x100756c0  |     4000 | 0xe0078a1 | 9
LEAK   |  0x2001fc0  |    40000 | 0xe0078a9 | 9
*** 3 LEAKS, 0 BROKENS.
```
2)After
```
Type   |    Addr    | Size(byte) |    Owner   | PID
---------------------------------------------------
LEAK   | 0x1006fef0 |        16  |  0xe007899 | 9
LEAK   | 0x100756c0 |      4000  |  0xe0078a1 | 9
LEAK   |  0x2001fc0 |     40000  |  0xe0078a9 | 9
```
*** 3 LEAKS, 0 BROKENS.

kernel/debug/mem_leak_checker.c: modify print format of mem_leak

---

external/webserver/http_client.c

NULL check for body param added in http_send_response & http_send_response_with_status_msg to avoid error in strlen function.

external/webserver/http_client.c: Add NULL validation

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_netmgr.c

Reset the  "rltk_wlan_enable_scan_with_ssid_by_extended_security" setting back to default 0 
Modified for both success and fail case of scan with ssid

os/board/rtl8721csm : reset scan with ssid setting to default

---

os/arch/arm/src/amebad/Kconfig
os/arch/arm/src/amebad/Make.defs
os/arch/arm/src/amebad/amebad_i2s.c

os/arch/arm/src/amebad: Fix I2S for RTL8721CSM
- Add I2S and I2C options into Kconfig
- Fix I2S Tx and add 16bit padding feature for I2S (Comment #define __16_BIT_PADDING__ to disable feature)
- Note: Pin configs are unchanged

os/arch/arm/src/amebad: Fix I2S for RTL8721CSM

---

os/kernel/task/task_terminate_unloaded.c

race condition during binary unloading & reloading scenarios.

kernel/task: Add sched_lock() to task_terminate_unloaded() API to avoid

---

os/kernel/semaphore/sem_post.c

ASSERT_INFO() and ASSERT() are checking same condition. (sem->semcount < SEM_VALUE_MAX)
So, This commit removes ASSERT().

kernel/semaphore: Remove duplicate ASSERT() in sem_post.c

---

os/arch/arm/src/common/up_createstack.c
os/arch/arm/src/common/up_vfork.c
os/binfmt/binfmt_execmodule.c
os/include/tinyara/mm/mm.h
os/kernel/pthread/pthread_create.c
os/kernel/task/task_create.c
os/mm/mm_heap/mm_heapinfo_utils.c

If stack node, pid is negative number in heapinfo.
So, when create stack, updated pid in stack node chunk.
But at this time, it directly accesses the heap node.
Therefore, this PR adds `heapinfo_set_stack_node()` that updates pid in stack node chunk to negative.
and applied the function.

change way to update pid of stack

---

os/Kconfig
os/Makefile.unix

Remove dependency on CONFIG_RAW_BINARY from defconfig and always generate .bin format. Move the .hex creation logic after the addition of samsung headers.

os/Makefile.unix: remove the CONFIG_RAW_BINARY dependency 

---

os/net/lwip/src/api/sockets.c

there was no NULL check in trycheck_selwait_socket fucntion.
It can make an error, so I added NULL check logic.

net/lwip: add null check

---

apps/shell/tash_command.c
apps/shell/tash_internal.h
apps/shell/tash_security.c

Modify the reboot to operate regardless of TASH authentication. 
(To improve the accuracy of Hotfix download)

apps/shell : Allow 'reboot' command before TASH authentication

---

build/configs/rtl8720e/rtl8720e_download.sh
build/configs/rtl8721csm/rtl8721csm_download.sh

when download without bootparam, we can have below error. because It is not check, during file copy and try download.
so, This commit adds to check for bootparam.bin file before try copy or download.
Error log:
cp: cannot stat '/root/tizenrt/build/configs/../../build/output/bin/bootparam.bin': No such file or directory
...
Makefile.unix:630: recipe for target 'download' failed
make: *** [download] Error 1
Also This commit removes unnecessary checking.

rtl8721csm_download, rtl8720e_download: fix to download fail

---

build/configs/rtl8720e/Make.defs
build/configs/rtl8721csm/Make.defs

The -fexceptions compiler flag must be added only if CONFIG_LIBCXX_EXCEPTION is enabled.

rtl8721csm/Make.defs: Fix cxx excteptions flag issue

---

apps/system/mem_leak_checker/mem_leak_checker_main.c
os/include/tinyara/mm/mm.h
os/kernel/debug/mem_leak_checker.c
os/kernel/task/task_prctl.c

Consolidate app and kernel leak check under mem_leak
```
TASH>>mem_leak
Kernel :
*** NO MEMORY LEAK.
Below are text addresses of loadable apps (and common binary if enabled) :
The pc value of the allocation can be obtained by subtracting the text start address of the appropriate binary
[app1] Text Addr : 0x217d040, Text Size : 8064
[app2] Text Addr : 0x21fe700, Text Size : 366624
app1 :
*** NO MEMORY LEAK.
app2 :
*** NO MEMORY LEAK.
TASH>>
```

apps/mem_leak_checker, kernel/debug: change usage for mem leak checker

---

os/binfmt/libelf/libelf_addrenv.c

CC:  libelf/libelf_addrenv.c
libelf/libelf_addrenv.c: In function 'elf_addrenv_free': libelf/libelf_addrenv.c:290:12: warning: passing argument 1 of 'kmm_free' makes pointer from integer without a cast [-Wint-conversion]
kmm_free(loadinfo->binp->sections[BIN_TEXT]);
^~~~~~~~
In file included from /root/tizenrt/os/include/tinyara/kmalloc.h:65:0,
from libelf/libelf_addrenv.c:63:
/root/tizenrt/os/include/tinyara/mm/mm.h:538:6: note: expected 'void *' but argument is of type 'uint32_t {aka unsigned int}'
void kmm_free(FAR void *mem);
^~~~~~~~
libelf/libelf_addrenv.c:291:38: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
loadinfo->binp->sections[BIN_TEXT] = NULL;
^
libelf/libelf_addrenv.c:294:12: warning: passing argument 1 of 'kmm_free' makes pointer from …

binfmt: Fix build warnings.

---

os/mm/mm_heap/mm_initialize.c

total_alloc_size is being initialized to zero and is being updated only during mm related calls (malloc, free etc). So, it will not include the size of the gaurd nodes. If we check mallinfo implementation, the allocated size includes the size of guard nodes. So, initialize it to proper value.
before fix :
[tc_umm_heap_get_heap_free_size] FAIL [Line : 485] umm_get_heap_free_size : Values (free_size == 0x736c0) and (info.fordblks == 0x736a0) are not equal
after fix :
[tc_umm_heap_get_heap_free_size] PASS
.
.
.########## Kernel TC End [PASS : 415, FAIL : 0] ##########

mm_heap/mm_initialize.c: set total_alloc_size to include first and last node

---

os/board/common/crashdump.c
tools/trap/HowToUseTrap.md
tools/trap/trap.c
tools/trap/trap.h

- This change allows dumping of a particular file by name/path from a crashed TizenRT device
USAGE: - After TizenRT device crashes
> 
> ************************************************************************************************
>                 Disconnect this serial terminal and run Dump Tool
> ************************************************************************************************
> 
> 
> /TizenRT/tools/trap$ sudo ./trap.sh 
> Please enter serial port adapter:
> For example: /dev/ttyUSB1 or /dev/ttyACM0
> Enter:
> /dev/ttyUSB1
> Target device locked and ready to DUMP!!!
> Choose from the following options:-
> 1. RAM Dump
> 2. Userfs Dump
> 3. Both RAM and Userfs dumps
> 4. External Userfs Partition Dump
> 5. Dump …

TRAP: Add functionality to dump a file from userfs partition on crash

---

framework/src/wifi_manager/wifi_manager_profile.c
os/include/tinyara/ss_slot_index.h

It is difficult to find the secure storage slots currently in use, and there is a possibility of duplicate use. So I collected  the secure storage slots currently in use in one header. (exclude example codes & not currently used code)

os/include/tinyara : Add definition to ss_slot_index header file

---

os/arch/arm/include/armv8-m/irq.h
os/arch/arm/src/armv8-m/up_schedulesigaction.c
os/arch/arm/src/armv8-m/up_sigdeliver.c

set the XPSR value to ARMV8M_XPSR_T to enusure that the T bit is 1 during signal handling. Set EXC_RETURN to thread mode when handling signal if in handler mode, to avoid the integrity check while restoring context in HANDLER mode.

[DO NOT MERGE][TESTING REQUIRED]arm/armv8-m: fix issues in signal handling

---

os/include/tinyara/arch.h

ARMV7A does not use NSC (Non Secure Callable) approach for calling secure APIs from non secure side. As a result APIs to allocate and free secure context are no longer required. However, RTK vendor code for SE tries to call these APIs, which is causing build error. This commit provides dummy defines for these APIs to prevent the errors.

tinyara/arch.h: Add dummy TZ APIs for ARMV7A

---

apps/examples/board_specific_demo/ameba_secure_storage_demo/Kconfig
os/se/ameba/rtl_security_api_wrapper_tz.c
os/se/ameba/security_ameba_wrapper_tz.c

Removed the depends on ARMV8M_TRUSTZONE for secure storage example apps/examples/board_specific_demo/ameba_secure_storage_demo/Kconfig
Removed the SE dummy API and handle in arch.h by Samsung os/se/ameba/rtl_security_api_wrapper_tz.c
Added the arch.h header file for SE code
os/se/ameba/security_ameba_wrapper_tz.c

os/se: RTL8730E Remove the SE dummy API

---

os/kernel/log_dump/log_dump.c

when the log is outputted while the scheduled lock is called, hang can be occur. 
because log_dump is waitting that compress is finish using only while()
So, even if log dump waits, context switching does not occur to log dump thread, so while() continues to circulate.

log_dump: fix log_dump hang issue

---

os/kernel/log_dump/log_dump.c

when the log is outputted while the scheduled lock is called, hang can be occur. 
For this, applied a8822cb commit. but This is breaking the intention of blocking context switching using sched_lock in the application, cpu is forcibly handed over to another thread.
So, This commit adds so that there is no compress operation when the sched_lock is stuck.

log_dump: change to not compress operation during sched_lock

---

framework/include/preference/preference.h
os/include/tinyara/preference.h

- PREFERENCE_TYPE macros are only used by the preference framework code so they need not be defined in kernel/../preference.h header file

preference: Move PREFERENCE_TYPE macros to framewrk/../preference.h

---

os/board/esp32_devkit/src/esp32_boot.c
os/board/rtl8720e/src/rtl8720e_boot.c
os/board/rtl8721csm/src/rtl8721csm_boot.c
os/board/rtl8730e/src/rtl8730e_boot.c

- Correct the names of functions <esp32_devKit/amebad/amebalite/amebasmart>_mount_partions to <...>_mount_partitions

os/board: Correct partition mounting function names

---

os/kernel/binary_manager/binary_manager_load.c

During Secure fault, the text addresses of the binaries loaded are not printed. As a result, we are unable to use addr2line. So, print the text start address of loaded binaries with the success message.
```
binary_manager_load_binary: Load success! [Name: common] [Version: 200204] [Partition: A] [Text start : 0x02100020] [Compressed Binary]
binary_manager_load_binary: Load success! [Name: app1] [Version: 190412] [Partition: A] [Text start : 0x021fb6e0] [Compressed Binary]
binary_manager_load_binary: Load success! [Name: app2] [Version: 190412] [Partition: A] [Text start : 0x02279520] [Compressed Binary]
```

kernel/binary_manager: print text start address of binary

---

os/arch/arm/src/amebad/Kconfig

Fix the occurrence of syntax errors because quotation marks are not closed

amebad/Kconfig: fix syntax error

---

apps/platform/gnu/Kconfig
lib/libxx/Kconfig

In the case of flat, CONFIG_HAVE_CXXINITIALIZE is required and in the
case of loadable, CONFIG_BINFMT_CONSTRUCTORS is required for cpp static
constructors initialization. Hence, select them appropriately when cpp is
enabled. Users need not select them specially as from now on they are enabled
by default.
Make CONFIG_HAVE_CXXINITIALIZE dependent on BUILD_FLAT so users will not
enable it in loadable configs by mistake

platform/gnu, libxx: select config appropriately for static constructors init

---

build/configs/rtl8720e/Make.defs
build/configs/rtl8721csm/Make.defs
build/configs/rtl8730e/Make.defs

This flag specifies that the compiler places uninitialized global variables in the BSS section of the object file. It is ok to always have the fno-common flag, so I set the flag to avoid confusion.

build/configs/rtl87XX: Set -fno-common flag always

---

build/configs/rtl8721csm/rtl8721csm_make_bin.sh

ARM.exidx and ARM.extab sections are not being copied into the final binary, causing the exceptions to not work. Hence added them.
```
============ Test RTTI ==================================
extend
============ Test Exception =============================
Catch exception: runtime error
============ thread::operator= test =====================
Spawning 5 threads...
Done spawning threads. Now waiting for them to join:
pause of 1 seconds ended
pause of 2 seconds ended
pause of 3 seconds ended
```

configs/rtl8721csm: fix exception handling on tp1x

---

framework/src/preference/private_preference.c
framework/src/preference/shared_preference.c

- Add missing header file for shared and private preference.
" CC:  src/preference/private_preference.c
src/preference/private_preference.c: In function 'preference_set_int':
src/preference/private_preference.c:45:19: error: 'PREFERENCE_TYPE_INT' undeclared (first use in this function)
data.attr.type = PREFERENCE_TYPE_INT;
^~~~~~~~~~~~~~~~~~~  "
- Correct input parameter type for private preference functions to match function declarations in header file
" CC:  src/preference/private_preference.c
src/preference/private_preference.c:281:5: error: conflicting types for 'preference_set_changed_cb'
int preference_set_changed_cb(char *key, preference_changed_cb callback, void *user_data)
^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/preference/private_preference.c:30:0: …

framework/preference: Fix build issues with perefernce framework

---

os/kernel/debug/mem_leak_checker.c
os/mm/mm_heap/mm_heapinfo_parse_heap.c
os/mm/mm_heap/mm_mallinfo.c

The chunk of heap can know the address of the next chunk through `node = node + node->size`.
Using this, all chunks of the heap can be traversed in the forward direction.
If the heap is corrupted and the node->size becomes 0, It can't move to the next chunk, and the iteration turns infinite.
Also, It is Locked the heap during the heap traversing. As a result, it becomes deadlock.
Therefore, Add to check the node size and it to cause ASSERT if it is zero during traversing forward direction.
hang reproduce code:
```
int *val = (int*)malloc(sizeof(int) * 100);
val = val - 1;
*val = 0;
mallinfo();
```

mm/mm_heap, mem_leak_checker: fix heap corruption hang

---

os/arch/arm/src/armv8-m/up_blocktask.c

If thread is in the trustzone, (TCB)->tz_context is allocated. And when context switching while this thread is operating, saves the context related to the trustzone in (TCB)->tz_context.
Likewise in up_block_task, the tz_context of rtcb(running thread) must be checked and the context of the trustzone must be stored, but the tz_context of the wrong TCB is checked.
Therefore, Correct to check the tz_context of running tcb.

arch/arm/armv8-m/up_blocktask: Correct invaild tcb->tz_context check

---

os/include/debug.h

- Fix missing header file security_level.h error during smartfs pre-image build
- security_level.h file need not be copied to Nxfuse sources along with other dependant files during NXFUSE_HOST_BUILD as the functionality is not needed during Nxfuse pre-image build.

tools/nxfuse: Remove inclusion of security_level.h in case of NXFUSE build

---

os/board/rtl8730e/src/component/usrcfg/rtl8730e/ameba_wificfg.c
os/board/rtl8730e/src/project/realtek_amebaD2_va0_example/inc/inc_ap/platform_autoconf.h

* Set concurrent_enabled to false as concurrent mode is not used
* Fix issue of SoftAP having different MAC address from STA interface
* Refine high throughput macro definition for CA32, set in platform_autoconf.h

os/board/rtl8730e: fix SoftAP MAC addr, refine high tp macro

---

os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api_ext.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_trx.c
os/board/rtl8730e/src/component/wifi/promisc/wifi_promisc_inic_ipc.c
os/board/rtl8730e/src/component/wifi/wifi_interactive_mode.c

Build Warning
- Added macro checking for declare the unused variable as it depends on the macro on/off
- Changed the NULL checking to 0 
SVACE
- DEREF_OF_NULL.RET.STAT: Added the NULL pointer checking
- BUFFER_OVERFLOW.LIB.EX: Modified the API with correct pass in parameter for the size
- UNREACHABLE_CODE: Added macro to wrap it for cover the switch case break
- OVERFLOW_UNDER_CHECK: Declared the wlan_idx[NET_IF_NUM] with follow thw NET_IF_NUM value
- PROC_USE.VULNERABLE: Replaced strcpy with strncpy with pass in length
- TAINTED_INT.LOOP: Added the condition checking for the unsigned value

os/board/rtl8730e: Fix WiFi related Build Warning and SVACE

---

os/arch/arm/src/amebad/amebad_lowerhalf.c
os/arch/arm/src/amebalite/amebalite_lowerhalf.c
os/arch/arm/src/amebasmart/amebasmart_gpio_lowerhalf.c

Tested that by removing gpio int deinit** during gpio initialisation, pull up/ down is working.
The deinit interrupt function also clears out the previous parameters. To prevent doing so deinit, this line has been removed.

os/arch/arm/src/ameba: GPIO pull up/down fix

---

os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

* In wifi driver, wifi scan process will exit directly when the driver fw state is "under scan" or "under wifi connection". Before this commit the "len" param in scan buf is not cleared in this case. It will make parse_scan_with_ssid_res() runs into app_scan_result_handler() many times with empty scan_result_report and cause the heap corruption issue. This commit reset scan buf to all 0 in wlan driver in this case to fix the assert issue.
* previously when wpa3 sae auth fail, driver didn't change the fw state from "under wifi connection" to "not under wifi connection" immediately. This will lead to wifi scan is exited even though wifi connection already failed and completed. This commit adds reporting join status after wpa3 sae auth fail to change the driver fw state immediately in this …

os/board/rtl8721csm: fix assert with wifi scan with ssid

---

os/dutils.sh

The path to the crash logs when using trap with dutils is taken relative to the os folder (ex : ../tools/trap/testlogs) but the same path is also used when calling trap command from ```os/tools/trap```,
```
dutils.sh log : Executing: ramdumpParser.py -t ../tools/trap/testlogs -e tinyara.axf
```
which results in the following error,
```
../tools/trap/testlogs does not exist. Please provide the proper path for log_file...
```
So, added comment to provide the path relative to os folder and also have corrected the crash logs path by adding /root/tizenrt/os prefix

os/dutils.sh: fix path to crash logs when calling trap tool

---

apps/examples/testcase/le_tc/compression/compression_tc_main.c
apps/examples/testcase/le_tc/compression/tc_compress_read.c
apps/examples/testcase/le_tc/compression/tc_internal.h
os/compression/compress.c
os/compression/compress_read.c
os/drivers/Makefile
os/drivers/compression/Make.defs
os/drivers/compression/README.md
os/drivers/compression/compress.c
os/include/tinyara/compression.h
os/include/tinyara/fs/ioctl.h
os/kernel/init/os_bringup.c

- adds compression api at public header(compression.h)
- adds compression module in driver , so that it can be used by application
- driver is able to return the compressor compression type
- adds README file in drivers/compression module for more details
- creates testcases to test compression and decompression

os/drivers/compression: Adds compression driver module

---

os/board/rtl8721csm/src/rtl8721csm_boot.c

Current GPIO PA12 is in conflict with UART1 init

os/board/rtl8721csm: Remove GPIO PA12 initialisation

---

os/compression/compress.c
os/drivers/compression/README.md

This commit fixes the typos in os/drivers/compression/README.md file and os/compression/compress.c file.

drivers/compression: Fixes typos 

---

lib/libc/math/Make.defs
lib/libc/math/lib_erfc.c
lib/libc/math/lib_erfcf.c
lib/libc/math/lib_erfcl.c
lib/libc/math/lib_expm1.c
lib/libc/math/lib_expm1f.c
lib/libc/math/lib_expm1l.c
lib/libc/math/lib_llround.c
lib/libc/math/lib_llroundf.c
lib/libc/math/lib_llroundl.c
lib/libc/math/lib_lround.c
lib/libc/math/lib_lroundf.c
lib/libc/math/lib_lroundl.c
lib/libc/math/lib_nan.c
lib/libc/math/lib_nanf.c
lib/libc/math/lib_nanl.c
os/include/tinyara/math.h

Issue fixed: Libc caused build issues in libcxx.
libcxx/math.h functions' definitions are not found due to issue in old libc/math.h, which has definitions of same functions in form of macros.
This commit by Nuttx changes the macros to function declarations and defines them in separate files. Nuttx commit id: https://github.com/apache/nuttx/commit/df812d09a219495a8ba1d0c30a2e9ebc05c37f3b Commit message by nuttx:
math: Make this friendly with libcxx
- Turn some macros into functions
- Implement some type-agnostic functions. (Just use __builtin_xxx)
- Add some missing function prototypes (Just prototypes, not actually implemented in this commit)

Update libc->math using nuttx's commit to fix libc

---

os/fs/smartfs/smartfs_smart.c

- smartfs_sector_recovery() need not be invoked during Nxfuse image build because we are building a fresh image to flash to the partition and hence recovery is not required.
- Additionally, in the case of Nxfuse host build, we will always get the error message "CRITICAL BUG!! Root sector is gone!!" from smartfs_sector_recovery despite successful completion.

os/fs/smartfs: Skip smartfs_sector_recovery in Nxfuse image build

---

os/tools/check_package_size.py

In python, 'global' keyword is needed for usage of global variable. It is enough to declare 'global' keyword once in a function because 'if' context doesn't make new scope. With this change, the below build warning is fixed.
========== Verification of partition settings ========== => Partition verification SUCCESS!! The setting of all partitions is OK. ./tools/../tools/check_package_size.py:72: SyntaxWarning: name 'FAIL_TO_BUILD' is assigned to before global declaration
global FAIL_TO_BUILD

tools/check_pacakage_size.py: Declare 'global' keyword once

---

os/board/rtl8730e/src/component/os_dep/osdep_service_memory.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api_basic.c

- Use kmm_memalign instead of kmm_malloc in RTK malloc operations to align malloc to 64b to resolve cache operation issues on CA32
- Fix DCache_Clean for ssid array during wifi scan to ensure cache is cleaned properly for cache coherency

os/board/rtl8730e: Change alignment of malloc

---

os/arch/arm/src/amebasmart/Make.defs

amebasmart_i2c.c have dependency CONFIG_AMEBASMART_I2C_XXXX configuration
So, when deciding whether to include this file in build, we should check CONFIG_AMEBASMART_I2C, not CONFIG_I2C. 
The same goes for amebasmart_spi.c.
Therefore, Change CONFIG_I2C and CONFIG_SPI to each CONFIG_AMEBASMART_I2C and CONFIG_AMEBASMART_SPI.

os/arch/arm/amebasmart: Change peripheral config to board level config.

---

framework/include/security/security_common.h

There is a slot that stores AP information, but the required size has increased while storing multi-AP information. 
Since the number of slots is limited, it is more efficient to store the data by increasing the size of existing slots instead of dividing it into several slots. 
Therefore, this commit increase data slot size from 256 to 4096. 
SECURITY_MAX_CERT_BUF is also changed to 4096 for the identity with trt_se.h (product code)

framework/include/security : Increase secure storage data slot size

---

os/board/rtl8730e/src/component/os_dep/osdep_service_memory.c

- Set global variable "align" used in osdep_service_memory to static to protect variable from being overwritten

os/board/rtl8730e: Set alignment requirements in rtl8730e malloc

---

build/configs/rtl8730e/scripts/rlx8730e_img2.ld

- Changed file: os/arch/arm/src/armv7-a/arm_mmu.c
- After moving out all files to XIP, there is an unexpected delay in boot sequence (around 5 secs)
- Discovered that TLB invalidation operation is causing the delay
- Move several MMU related APIs to PSRAM, delay in boot sequence can be shorten (around 1 sec)
- Note: Commenting out mmu_invalidate_region() in mmu_l1_setentry() will not incur any delay in boot sequence, and able to boot up successfully. The operation flow should be checked in depth.

os/arch/arm/src/armv7-a: Place MMU mapping related APIs to PSRAM

---

os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/flash_api.c

Issue:
When perform smartfs "format" will causing hang.
Root Cause:
After implement the XIP changes, the flash api was default located to the XIP. 
For the flash related API must be locate to PSRAM.
Changes Note:
Add the SRAMDRAM_ONLY_TEXT_SECTION for the flash related API move to PSRAM. 
Add the FLASH_Write_Lock/Unlock to make sure before perform the flash operation, CA32 must be disable the IRQ.

os/board/rtl8730e: Move Flash Related API to PSRAM

---

os/mm/mm_heap/mm_initialize.c

mm_delaylist nodes are freeded during before a new malloc. If mm_delaylist has stale value, this will result undefined behaviour (mostly data abort as we try to access random address). Hence, initialize it to NULL.

mm/mm_heap: initialize mm_delaylist element to NULL during mm_initialize

---

os/kernel/task/task_terminate.c

Clean up in the above exithook function is dependent upon the task state during the exit (task can be blocked on mq and a differnt task could have killed it). As a result, we need to retain the task_state in tcb until exithook is done

kernel/task : retain task_state in tcb until task_exithook is finished

---

os/arch/arm/src/amebasmart/amebasmart_irq.c
os/arch/arm/src/amebasmart/chip.h
os/arch/arm/src/armv7-a/arm_vectors.S
os/arch/arm/src/imx6/chip.h
os/arch/arm/src/imx6/imx_irq.c

fiq stack is allocated in all cases as of now. Hence, allocate fiq stack only if CONFIG_ARMV7A_DECODEFIQ is enabled.

os/arch/arm: allocate fiq stack based on CONFIG_ARMV7A_DECODEFIQ

---

os/arch/arm/src/armv7-a/arm_assert.c

If CONFIG_BOARD_ASSERT_AUTORESET is enabled and occur crash(assertion), board will be rebooted. 
But, rebooting does not work with armv7-a, because CONFIG_BOARD_ASSERT_AUTORESET is not applied in armv7-a/arm_assert.c yet.
Therefore, Fix so that it reboots correctly when an assertion occurs.

armv7-a/arm_assert: fix board reset in assertion

---

os/arch/arm/src/amebasmart/amebasmart_pmc.c
os/arch/arm/src/amebasmart/amebasmart_pmhelpers.c
os/include/tinyara/pm/pm.h
os/pm/pm_procfs.c

- Update DVFS wrapper layer
- Fixed PM timer struct naming mismatch (For PR#6015)

os/arch/arm/src/amebasmart, os/pm: Refine PM DVFS and fix struct naming mismatch for RTL8730E

---

apps/examples/power/power_main.c
os/include/tinyara/pm/pm.h

-Update power_main with new APP control functionality - blocking and unblocking
power state transitions.
-We do not support triggering of PM_SLEEP from application side anymore.
-The application simply sleeps after blocking and unblocking state transition in
an infinite loop.
-NOTE: This application does not test DVFS functionality yet.

apps/examples/power: Modify Power Main example

---

os/pm/pm_procfs.c

-Procfs layer of PM should not be board dependant.
tunefreq depends on CONFIG_DVFS, which in turn depends on board support
-Unify function for unlocking PM state transition. We will always support
option of timer interrupt for waking up from PM_SLEEP, independant of board.
-We will not support the option of pushing the board to go to PM_SLEEP state
from the app itself, hence remove enter_sleep_write function.
-Correct alignment and spaces.

os/pm: Modify procfs layer interface for PM control

---

os/arch/arm/src/armv7-a/arm_assert.c
os/arch/arm/src/armv8-m/mpu.h
os/arch/arm/src/armv8-m/up_assert.c
os/binfmt/libelf/libelf_sections.c
os/kernel/task/task_dumptasks.c
os/mm/mm_heap/mm_check_heap_corruption.c
tools/debug/debugsymbolviewer.py
tools/trap/ramdumpParser.py

1. We have added API tags to assert logs and these tags are further used by trap for parsing.
2. We have added closing log line to assert log.
3. We do changes in trap tools to support the new log format of tp1x and AI Dual. 
4. Order sequence for Assert Log: 
- Assertion details
- Asserted task's stack details
- Asserted task's TCB info 
- Asserted task's register dump
- List of all tasks in the system
- List of MPU regions and permissions
- Loading location information
- Checking app heap for corruption
- Checking kernel heap for corruption
5. Attached the document containing Assert log and Trap run log.
[Sample Assert Log.txt](https://github.com/Samsung/TizenRT/files/14276064/Assert.Log.After.txt)
[Trap Run Log.txt](https://github.com/Samsung/TizenRT/files/13917645/Trap.Run.Log.txt)

tools/trap: Trap Tool support for armv8-m and armv7-a

---

apps/examples/power/power_main.c
os/arch/arm/src/amebasmart/amebasmart_idle.c
os/arch/arm/src/amebasmart/amebasmart_pmhelpers.c
os/include/tinyara/pm/pm.h
os/pm/pm_activity.c
os/pm/pm_procfs.c

os: Add functionality for timed PM state locking
-Add a timer API to pm layer that allows setting timed callbacks.
-This is currently used to relax PM state transition after a certain
time of locking.
-It may be expanded to other timed callbacks in the future
apps/examples/power: Fix bad sleep duration macro for power daemon
-Power daemon sleep duration value should be in seconds instead
of microseconds.

os: Add functionality for timed PM state locking

---

os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_ipc_api.c
os/board/rtl8730e/src/component/wifi/driver/include/rtw_autoconf.h

Change notes:
Also disabled CONFIG_AUTO_RECONNECT in rtw_autoconf.h

os/board/rtl8730e: fix wifi SVACE warnings

---

os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/drivers/audio/alc1019.c
os/include/tinyara/audio/alc1019.h

Set alc1019 apb buffer size to be equal to i2s DMA page size. Also increase i2s DMA page size to 2048

arm/src/amebasmart,drivers/audio: align alc1019 buffer size with DMA page size

---

os/arch/arm/src/amebasmart/amebasmart_boot.c

- Remove core shutdown operation during cold boot

os/arch/arm/src/amebasmart: Remove Secondary core shutdown during cold boot phase

---

os/include/tinyara/fs/ioctl.h

_COMPBASE ioctl value was duplicate with _THERMALBASE(which is used in product repo). 
This commit fix _COMPBASE ioctl value (0x2900 to 0x2a00)

os/include/tinyara/fs: Fix _COMPBASE ioctl

---

os/kernel/binary_manager/binary_manager_data.c

Common binary also is registered in binary table and managed by binary manager.
So if CONFIG_SUPPORT_COMMON_BINARY is enabled, add one to USER_BIN_COUNT for common binary.

kernel/binary_manager: Check the count of registered binaries before user binary registration

---

os/include/tinyara/pm/pm.h
os/pm/Kconfig

- lower the threshold from the current total transition time of 15 seconds which is too much to wait for
- Also board does not go to sleep if the total threshold time is more than 10 seconds
- This is a heuristic solution
- The threshold count for different states have been changed from (3,5,7) to (2,2,2)

os/pm/Kconfig: Changes default values of state change threshold count

---

os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/spi_api.c

Fix the divider to be even, as a requirement of the specs sheet

os/arch/arm/src/amebasmart: Fix SPI clock divider to be even number

---

apps/examples/lcd_test/example_lcd.c
os/drivers/lcd/st7789.c

The resolution values were swapped twice in driver and app when CONFIG_LCD_LANDSCAPE=y 
Fixed by removing swapping from app.

fix CONFIG_LCD_LANDSCAPE orientation

---

os/arch/arm/src/amebasmart/amebasmart_pmhelpers.c
os/include/tinyara/pm/pm.h
os/pm/Kconfig
os/pm/pm_activity.c
os/pm/pm_changestate.c
os/pm/pm_procfs.c

- This commits add methods to help board wake up for sending wifi keep alive signal. It stores time ticks of last time when wifi keep alive signal was sent and accordingly sets the sleep duration of board. So that board can wake up when next signal is supposed to be sent
- power_set_next_wakeup_interval() is added . This can be called from app side just after "wifi keep alive signal was sent" . This will set the WAKE_UP_TIMER again with the required time interval. This function will also store the time tick of the Wifi keep alive signal sent time. This can be used to calculate actual required sleep duration just before sleep.
- power_get_last_wifi_alive_send_time and power_get_current_time can be used to find difference between the time ticks of last wifi keep alive signal sent and now . …

os/pm: Adds PM functionalities for sending Wifi keep alive

---

os/pm/pm_procfs.c

- corrected name of power_get_last_wifi_alive_send_time function to fix compilation error.

os/pm/pm_procfs.c: fix build error

---

os/drivers/lcd/st7789.c

orientaton using config was set in init ioctl for lcd it is now set in st7789_lcdinitialize as well if init ioctl is not called

os/driver/lcd: set orientation in st7789_lcdintialize

---

os/board/rtl8730e/src/component/bluetooth/api/rtk_stack/rtk_stack_gattc.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_ota.c

Changes Note:
rtk_stack_gattc.c
SVACE: 287217
Added NULL pointer checking p_req before performance free.
ameba_ota.c
SVACE: 287218
Fix by pass the parameter "Cert" by reference, to avoid huge data pass in may lead the unnecessary performance loss.

os/board/rtl8730e: Fix SOC SVACE warning

---

os/include/tinyara/mmu.h

The build warning is ocurring as below. because missing void argument.
WARNING: function declaration isn't a prototype [-Wstrict-prototypes]
uint32_t *mmu_get_os_l1_pgtbl();
^~~~~~~~
Therefore, Add void argument in mmu header

include/tinyara/mmu.h: Add missing void argument

---

framework/src/preference/preference_callback.c
framework/src/preference/preference_init.c
framework/src/preference/private_preference.c
framework/src/preference/shared_preference.c
os/kernel/preference/preference_callback.c

If a thread registers callback, it is invoked when value of the given key in the preference changes. This callbacks operate based on signals and message queues. If there is a registered callback, it sends data to the created message queue and sends a signal then a handler that receives the callback deletes this created mq. So just return if registered callbacks are not  or sending callback messages are done.

kernel/preference: Return if registered callbacks are not exisiting or sending callback messages are done

---

os/arch/arm/src/amebasmart/amebasmart_spi.c

Set the correct SPI0 cs1 pin according to new h/w. SPI1 pins should we revised before using according to the h/w mappings.

arch/arm/src/amebasmart: update pin mappings for SPI0

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_peripheral/ble_tizenrt_server.c

- added in check to make sure the input connection handle belongs to server before returning the connection status

os/board/rtl8721csm: fix BLE get server connection status issue

---

os/binfmt/libelf/libelf_bind.c

currently we are only exporting global symbols which worked fine till now. But as we are expanding on cpp code, we also need to export weak symbols in common as they are required by app binary

binfmt/libelf: export weak symbols from common to support cpp code

---

os/include/assert.h
tools/nxfuse/mknxfuse.sh

tools/nxfuse, os/include: resolve smartfs build error
files modified: os/include/assert.h, tools/nxfuse/mknxfuse.sh
issue:
dq_cat.c and sq_cat.c needs DEBUGASSERT macro which is defined in .tizenrt/os/assert.h, but these files  are including assert.h from ubuntu. Below warning and linking error arises:
src/queue/sq_cat.c:42:3: warning: implicit declaration of function 'DEBUGASSERT' [-Wimplicit-function-declaration] DEBUGASSERT(queue1 != NULL && queue2 != NULL);
Linking nxfuse : error
obj/queue/dq_cat.o: In function dq_cat': /root/product/.tizenrt/tools/nxfuse/src/queue/dq_cat.c:42: undefined reference to DEBUGASSERT'
solution:
nxfuse is Linux application, it should not include TizenRT source code 1.set DEBUGASSERT() to empty when NXFUSE_HOST_BUILD is enabled 2.include os/include/assert.h …

Sync smartfs build failure fix commit

---

os/arch/arm/src/amebasmart/amebasmart_spi.c

SPI pins were modified to a newer board version, which is no longer used. So, revert the change.

arm/src/amebasmart: revert changes made SPI pins to support old board

---

os/drivers/Kconfig

New config was added for Virtual key driver event queue length. It was not added in Kconfig, adding it after review.

os/drivers: update Kconfig for VIRTKEY_QUEUE_LEN

---

os/arch/arm/src/amebasmart/amebasmart_spi.c

errno should be only checked if sem_wait fails, but here we are calling ASSERT by checking the errno even in the success case. Hence, modified the loop logic to check errno in case of failure.

arm/src/amebasmart: fix assert issue cause by wrong errno usage

---

os/arch/arm/src/amebad/amebad_spi.c

errno should be only checked if sem_wait fails, but here we are calling ASSERT by checking the errno even in the success case. Hence, modified the loop logic to check errno in case of failure.

arm/src/amebad: fix assert issue cause by wrong errno usage

---

os/kernel/init/os_bringup.c
os/se/security_level/security_level.c

If security_level is not set yet, it shows error log. 
Because of the log "error", it can be mistaken for abnormal operation. 
Therefore, this commit change the security level log to prevent confusion.

os/kernel/init/os_bringup.c: Change security_level log

---

os/include/tinyara/security_level.h
os/se/security_level/security_level.c

Set security level high in default (in case of failing to set security level or security level is not setting yet)

os/se/security_level: Set security level high in default

---

os/arch/arm/src/amebasmart/Make.defs
os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/arch/arm/src/amebasmart/amebasmart_smp.c
os/arch/arm/src/amebasmart/amebasmart_spi.c
os/arch/arm/src/amebasmart/amebasmart_timer_lowerhalf.c
os/arch/arm/src/armv7-a/arm_cpugating.c
os/arch/arm/src/armv7-a/arm_gicv2.c
os/arch/arm/src/armv7-a/gic.h
os/board/rtl8730e/src/component/os_dep/device_lock.c
os/board/rtl8730e/src/component/os_dep/osdep_service_critical.c
os/board/rtl8730e/src/component/os_dep/osdep_service_critical.h
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_flash_ram.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_trx.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_msg_queue.c

- Change to use enter/leave_critical_section instead of irqsave/irqrestore, for both arch and driver layer
- Reduce overhead for critical zone implementation in porting layer
- Driver Features verification pending due to several logic crashes
- Related PR: https://github.com/Samsung/TizenRT/pull/6049

os/arch/arm/src/amebasmart, os/board/rtl8730e: Update critical zone API usage for SMP

---

os/tools/check_package_header.py

SIGNING_SIZE is a header size of signing binary.
Since it depends on the type of board, this commit changes SINGING_SIZE to read from config file.

os/tools/check_package_header.py: Change SIGNING_SIZE

---

os/kernel/log_dump/log_dump.c

Fix the following problems.
1. When a part of the chunks of the log dump needs to be discarded due to insufficient kernel memory, the chunks are being freed but not subtracted from the total chunk size held by the log dump.
2. The current log dump structure must always have more than one log dump chunk. However, as above issue, all chunks can be freed, resulting in an abort.

os/kernel/log_dump: Fix wrong free log dump chunk.

---

os/board/rtl8730e/Kconfig
os/tools/mkldscript.py

-  In TRPK file, it might include several binaries together, which means the binary running on TizenLite might not be the starting address of the TRPK file.
- In return, we will face crash issue, since there is a address mismatch between the correct address and the current address of the apps binary (ie. the address of the apps binary should be calculated from the binary which is running on TizenLite, not the trpk file itself)

os: Fix XIP_ELF runtime loading crash issue

---

build/configs/rtl8730e/scripts/rlx8730e_img2.ld

-Kernel Flash usage reduced 59704
-Available heap increased 59712

build/configs/rtl8730e: Move BT debug info to virtual address

---

os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_flash_ram.c

- If unused API is being forcely allocated to some specific region, it will be included in final build and causing memory wastage
- Add macro to filter out unused API

os/board/rtl8730e: Remove unused API

---

os/tools/check_package_header.py

SIGNING_SIZE is the header size of signing user binary. But if CONFIG_USER_SIGN_PREPEND_SIZE is not set, SIGNING_SIZE value is 'None'. So it causes build error when directly convert SIGNING_SIZE type from string to int. This commit adds the process when the SIGNING_SIZE is none.

os/tools/check_package_header.py: Fix non-signing build error

---

os/binfmt/libxipelf/xipelf.c

filfd was not closed in xipelf_loadbinary. Hence added close at all exit points in the function.

binfmt/libxipelf: fix WID:35655979 defect caused by unclosed fd

---

build/configs/rtl8730e/loadable_apps_xip/defconfig
build/tools/amebasmart/gnu_utility/loadable_xip_elf.py
build/tools/amebasmart/gnu_utility/rtk_data_binary.py
os/board/rtl8730e/Kconfig
os/tools/mkldscript.py

- mkldscript for loadable is generic tool, to break the dependency, chip specific should implement the logic independently
- If trpk file contains multiple binary, the logic should be applied
- Add flash virtual starting address and trpk multiple binary macros in defconfig

os, build: Add support for loadable XIP_ELF offset calculation

---

framework/src/eventloop/eventloop_async.c

Fix Svace issue related to out of bounds array access. OVERFLOW_UNDER_CHECK	Buffer 'g_thread_safe_cb_list' of size 128 accessed at eventloop_async.c:130 can overflow, since its index 'list_idx' can have value 128 that is out of range, as indicated by preceding conditional expression at eventloop_async.c:125

framework/src/eventloop: Fix Svace issues

---

.circleci/config.yml

circleci has deprecated some Ubuntu images and advised use of default image.
Refer to : https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177/1 Linux Image Deprecations and EOL for 2024
The recommended tags to use are as follows:
default - latest stable version and version if do not specify anything edge - Development image of latest image

circleci: Change Ubuntu image version

---

os/arch/arm/src/amebasmart/amebasmart_idle.c

- In idle thread, apply "WFE" for cpu to enter low power state, under all PM states other than PM_SLEEP, as there is nothing to be done for idle thread under those PM states.
- If a state is locked (ie. state transition will not be happening), but we might still enter idle loop under some circumstances, in this case, WFE should also be applied as well, because there will be no system variable changes happening from idle thread

os/arch/arm/src/amebasmart: Improve power efficiency for RTL8730E

---

os/fs/driver/mtd/mtd_partition.c

Add partition number to partition procfs data.
It is read by "/proc/partitions"

fs/mtd: Add partition number to partition procfs data

---

os/arch/arm/src/amebasmart/amebasmart_timer_lowerhalf.c

- Normally, app uses lowest index for HW timer, such as /dev/timer0. But, currently the kernel and driver has allocated timer 0~2 for several usage:
- timer0: LP systimer
- timer1: PM one-shot wakeup timer
- timer2: Crash detector for KM4/KM0 cpu status
- Due to above reason, we have to remap the timer index, so that when app is using lower index timer, it will not cause conflict with the timer which already has designated usage.
- For example, if app use /dev/timer0, it actually uses HW timer 3, and the rules follow by incrementing the index

os/arch/arm/src/amebasmart: Remap timer index for app usage

---

lib/libc/misc/lib_envpath.c
lib/libc/misc/lib_hashmap.c
lib/libc/stdio/lib_asprintf.c
lib/libc/stdio/lib_vasprintf.c
lib/libc/string/lib_strdup.c
lib/libc/string/lib_strndup.c
lib/libxx/libxx_new.cxx
lib/libxx/libxx_newa.cxx
os/include/tinyara/mm/mm.h
os/mm/kmm_heap/kmm_calloc.c
os/mm/kmm_heap/kmm_malloc.c
os/mm/kmm_heap/kmm_memalign.c
os/mm/kmm_heap/kmm_realloc.c
os/mm/kmm_heap/kmm_zalloc.c
os/mm/mm_heap/mm_initialize.c
os/mm/mm_heap/mm_manage_allocfail.c
os/mm/umm_heap/umm_calloc.c
os/mm/umm_heap/umm_malloc.c
os/mm/umm_heap/umm_memalign.c
os/mm/umm_heap/umm_realloc.c
os/mm/umm_heap/umm_xalloc_user_at.c
os/mm/umm_heap/umm_zalloc.c

When a memory is alloc, we store the caller address requested by which code. However, if we wrap the alloc api and use it, the caller only looks at the wrapped api.
Therefore, we apply the DEBUG_SET_CALLER_ADDR macro to actually store the caller's address in alloc.

lib: Apply DEBUG_SET_CALLER_ADDR macro

---

apps/examples/rtc/rtc_main.c
os/include/tinyara/rtc.h

RTC doesnt work because of wrong initialization. Hence, initialize RTC with epoch time
```
[RTW]: ** Band = 2.4G and 5G **
System Information:
Version:
Platform: 3.1   Binary: 200204
Commit Hash: 85bd621
Build User: root@=
Build Time: 2024-06-19 10:57:01 IST
System Time: 19 Jun 2024, 00:00:00 [s] UTC Hardware RTC Support
TASH>>rtc
TASH>>=== RTC Accuracy Test ===
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
```

apps/examples/rtc: initialize prev time to epoch for RTC to work

---

os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c
os/include/tinyara/pm/pm.h
os/pm/pm_timedsuspend.c

this commits updates the time unit value from nanoseconds to milliseconds in timedstay api of PM during ble onboarding trigger operation.

os/board/rtl8730e: update timedstay interval for ble trigger

---

os/arch/arm/src/amebasmart/amebasmart_spi.c
os/board/rtl8730e/src/component/bluetooth/driver/platform/amebad2/hci/hci_platform.c
os/board/rtl8730e/src/component/bluetooth/os/tizenrt/osif_tizenrt.c

- Add refs count in SPI to prevent from multiple initialization

os/arch/arm/src/amebasmart: Add refs count in SPI to prevent from multiple initialization

---

os/include/tinyara/security_hal.h
os/se/ameba/Kconfig

Add AES-GCM mode and parameter to support AES-GCM encryption/decryption. AES-GCM mode needs 4 additional parameter.
- AAD (Additional Authentication Data)
- AAD length
- TAG (Authentication Tag)
- TAG length

os/include/tinyara/security_hal.h: Add AES-GCM mode

---

os/fs/Kconfig

Disable resource by default to avoid build failure of partition verification because of absence of 'resource' partition.

resource: Disable resource by default

---

os/include/tinyara/security_hal.h

Issue: Secure hardfault while booting
```
[rtl_readdecrypt_factorykey] Exit form here!arm_prefetchabort: Prefetch abort. PC: 00000000 IFAR: 00000000 IFSR: 00000008
security level: 1
```
Cause: sec_ops_s of security_ameba_wrapper_tz.c and security_hal.h are not matched.
Solve: Move GCM APIs to the end of sec_ops_s

os/include/tinyara/security_hal.h: Change the order of internal API of sec_ops_s

---

os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/wdt_api.c
os/board/rtl8730e/src/component/os_dep/osdep_service.h
os/board/rtl8730e/src/component/os_dep/osdep_service_misc.h
os/board/rtl8730e/src/component/soc/amebad2/fwlib/include/ameba.h
os/board/rtl8730e/src/component/soc/amebad2/fwlib/rom_common/Make.defs
os/board/rtl8730e/src/component/soc/amebad2/fwlib/rom_common/ameba_assert_rom.c

- Link BSP assert to Tizen Lite kernel assert
- Remove the assert in watchdog_stop, so that it would not affect the normal workflow of kernel failure crashes

os/board/rtl8730e: Revise BSP assert code

---

loadable_apps/Makefile
loadable_apps/loadable.mk
os/Makefile.unix
os/binfmt/Kconfig

If we use whole-archieve option, then full library gets included. Instead if not enabled, then only required symbols from the library will be picked
About ~350KB (7%) size reduction was observed on internal branch.

loadable_apps, binfmt: add config to use --whole-archieve option

---

build/configs/rtl8730e/rtl8730e_make_bin.sh
build/tools/amebasmart/gnu_utility/rtk_data_binary.py

- Get value from .config, to differentiate whether the data binary build is necessary
- Skip the operation if external flash is invalid

build/configs/rtl8730e: Revise rtk data binary build flow

---

os/Makefile.unix
os/tools/mkverifyappsize.py

Check whether L2 page table assigned per app are sufficient enough or not. We have to throw an error and stop further execution if they are not sufficient enough and print the exact amount of L2 page table required per app.

os/tools, os/Makefile.unix: verify whether l2 page table per app are sufficient or not

---

os/arch/arm/src/armv7-a/arm_assert.c
os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-m/up_busfault.c
os/arch/arm/src/armv7-m/up_hardfault.c
os/arch/arm/src/armv7-m/up_usagefault.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/armv8-m/up_busfault.c
os/arch/arm/src/armv8-m/up_hardfault.c
os/arch/arm/src/armv8-m/up_memfault.c
os/arch/arm/src/armv8-m/up_usagefault.c

When assert occurs, the assert log is printed continuously with the previous log. (It occurs only in AIDual)
```
E[MEDIA][audio_manager.c]::get_device_process_handler_mesecurity level: 0
===========================================================
Assertion details
===========================================================
```
This commit adds \n in front of security_level log to distinguish between normal log and assert log.

os/arch/arm/src/armv7-a/arm_assert.c: Add \n in security_level lldbg

---

os/binfmt/libxipelf/xipelf.c
tools/debug/debugsymbolviewer.py
tools/trap/ramdumpParser.py

add trap tool support for xip loadable apps

tools/trap: add trap tool support for xip loadable apps 

---

os/mm/mm_heap/mm_heapinfo_parse_heap.c
os/mm/mm_heap/mm_manage_allocfail.c

If watchdog is active, the large amount of logging in heapinfo_parse_heap() can cause reboots by Watchdog To prevent this, we added code to stop Watchdog in mm_manage_allocfail, but some chipsets do not support stopping Watchdog.
Therefore, we modified it so that Watchdog keepalive is called along with log output inside heapinfo_parse_heap(),
so that even if Watchdog stop is not supported, it will not be rebooted during log output.

mm: replace watchdog stop to watchdog keepalive

---

apps/system/utils/utils_ps.c
os/fs/procfs/fs_procfsproc.c
os/kernel/init/os_start.c

```ps``` command was not working properly with smp configs enabled. Idle task stack are not stored in heap region, instead they are stored in .bss region. For retrieving idle task stack, we should not search in heap region And this case was not handled properly for all cpu's idle task. So, we handle the case for every cpu's idle task.

os/fs/procfs, os/kernel/init: Fix issue in running the ps command with smp configs enabled

---

lib/libc/time/lib_gmtimer.c
os/arch/arm/src/stm32/stm32_rtcc.c
os/arch/arm/src/stm32l4/stm32l4_rtc.c

sync changes to gmtime_r, stm rtc drivers from nuttx
before :
TASH>>=== RTC Accuracy Test ===
[Total 0m passed] Time Difference : 86401s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
after :
TASH>>rtc
TASH>>=== RTC Accuracy Test ===
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s
[Total 0m passed] Time Difference : 1s

libc/time, arm/stm* : fix range of tm_yday in gmtime_r

---

os/arch/arm/src/amebasmart/amebasmart_flash.c
os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/arch/arm/src/amebasmart/amebasmart_mipi.c
os/arch/arm/src/amebasmart/amebasmart_pmhelpers.c
os/arch/arm/src/amebasmart/amebasmart_serial.c
os/arch/arm/src/amebasmart/amebasmart_spi.c
os/board/rtl8730e/src/component/bluetooth/api/rtk_bt_power_control.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2s_api.c
os/board/rtl8730e/src/component/soc/amebad2/misc/ameba_tizenrt_pmu.c
os/board/rtl8730e/src/component/soc/amebad2/misc/ameba_tizenrt_pmu.h
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api.c
os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c

- pm_register is removed from pm driver, changed to domain registration according to different driver module
- Old way: Register callback to PM driver, every PM state change will inform driver, some driver status will be checked to determine whether a PM state change is given approval
- Revised way: Register domain to PM driver, suspend/resume domain according to operation in different driver module

os/arch/arm/src/amebasmart: Revise BSP to follow PM new structure

---

os/kernel/wdog/wd_start.c
os/kernel/wdog/wdog.h
os/pm/pm_wakehandler.c

The pm_wakehandler is currently experiencing a hang. This is caused by the IDLE thread giving up the CPU while executing the pm_wakehandler. The pm_wakehandler is executed by the IDLE thread after the main core has awakened and the tick timer is still stopped. Therefore, if the IDLE thread gives up the CPU while executing the pm_wakehandler, it cannot regain the CPU without another thread voluntarily relinquishing it, which prevents the tick timer from restarting. This is because the tick timer is stopped and the RR scheduling does not work.
The pm_wakehandler includes the wd_expire operation. However, since the wd expire handler can include context switching operations such as sem_post or signals, the IDLE thread may give up the CPU.
Therefore, Change to so that, the suppressed tick is …

os: fix pm wakeup hang issue

---

os/drivers/pm/Make.defs
os/include/tinyara/pm/pm.h
os/kernel/init/os_bringup.c

The PM API can be used in many places. So, It is difficult to check CONFIG_PM in all codes. Therefore, even if CONFIG_PM is disabled, we change it so that the API can be provided as follows.
1. the PM driver is always enabled,
2. when CONFIG_PM is disabled, pm_sleep(milliseconds) is replaced with usleep(milliseconds * USEC_PER_MSEC).
3. The remaining APIs return OK without any action.

pm: Change to not check CONFIG_PM when using pm apis in other modules

---

os/arch/arm/src/amebasmart/amebasmart_spi.c

- Missing leave_critical_section for SPI initialization lead to several unexpected behaviour, thus add leave_critical_section to necessary places (ie. early return condition)

os/arch/arm/src/amebasmart: Update missing leave_critical_section

---

os/arch/arm/src/amebasmart/amebasmart_serial.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/gpio_irq_api.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/rtc_api.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/serial_api.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/spi_api.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/wdt_api.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_hp/ameba_sport.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/rom_common/ameba_tim_rom.c
os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c

- Currently the driver priority setting is according to cortex-M value range (ie. NVIC), but rtl8730e is running on cortex-A, which has it's own value range for setting irq priority (ie. GIC).
- This PR revise the wrong usage on irq priority for peripheral drivers
- Due to performance issue, Increase irq priority level for LCDC

os/board/rtl8730e: Update BSP driver irq priority running on cortex-A

---

lib/libc/machine/arm/Make.defs
lib/libc/machine/arm/setjmp.S
os/arch/arm/src/s5j/Make.defs
os/arch/arm/src/tiva/Make.defs

generally setjmp and longjump as provided as a part of libc. So, moved setjmp.S to libc. In this way, we also support setjmp in both flat and loadable.
Verification was done on artik flat, rtl8721csm flat, rtl8730e flat and loadable.
artik flat : 
```
TASH>>setjmp_test
diving(1, R, 0x2036584)
diving(2, R, 0x203646c)
diving(3, R, 0x2036344)
diving(4, R, 0x203621c)
diving(5, R, 0x20360f4)
diving(6, R, 0x2035fcc)
diving(7, R, 0x2035ea4)
diving(8, R, 0x2035d7c)
return(8, R, 0x2035d7c)
return(7, R, 0x2035ea4)
return(6, R, 0x2035fcc)
return(5, R, 0x20360f4)
return(4, R, 0x203621c)
return(3, R, 0x2036344)
return(2, R, 0x203646c)
return(1, R, 0x2036584)
setjmp does not break function return
diving(1, L, 0x2036584)
diving(2, L, 0x203646c)
diving(3, L, 0x2036344)
diving(4, L, 0x203621c)
diving(5, …
```

libc/machine/arm: move setjmp definition to libc for loadable

---

os/board/rtl8730e/src/component/bluetooth/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_blemgr.c

- add ble_server_set_device_name API to set BLE device name

os/board/rtl8730e: add API to set BLE device name

---

os/pm/pm_timedsuspend.c

When a thread call pm_timedsuspend multiple times within timer expiration, then pm_timedsuspend doesn't stoping the timer, instead it was rasing error. Now when pm_timedsuspend call multiple times within timer expiration, then it changes timer duration to remain suspended for given time if it is greater than current expiration time. If application provide zero time interval, then it cancel the timer immediately and resume the suspended domain.

os/pm: fix pm_timedsuspend cancel

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_blemgr.c

- NULL added to g_trble_drv_ops to match function in trble_ops struct

os/board/rtl8721csm: fix BLE function array mismatch due to PR6193

---

lib/libc/audio/lib_buffer.c
lib/libc/misc/lib_hashmap.c

The apb_alloc api is wrapping malloc apis.
So we don't know who was the requesting alloc memory using heapinfo.
Therefore, Add DEBUG_SET_CALLER_ADDR to update the caller address that requested the actual memory.

lib_buffer: add DEBUG_SET_CALLER_ADDR macro

---

os/mm/kmm_heap/kmm_realloc.c

if oldmem argument is NULL or not in heap address, we get a crash in mm_free_delaylist:103
When we call the mm_malloc API, we guarantee that the argument's heap is valid before calling it. Therefore, there is no NULL check for the heap argument in mm_malloc. So, when calling mm from kmm or umm, we need to pass the correct heap variable as an argument.
In this issue, when oldmem was passed as NULL in kmm_realloc, mm_get_heap returned NULL and caused a crash because mm_realloc was called with a NULL argument. To fix this,
Change to so that, if we cannot find the heap using oldmem, mm_realloc is not called with NULL.

kmm_realloc: fix crash issue case of oldmem is NULL

---

os/pm/pm_sleep.c

This commit resolve undefined reference to 'this_task' build error on pm_sleep.c with loadable_apps configuration without SMP.

os/pm: fix pm_sleep build error

---

os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/spi_api.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/include/ameba_spi.h
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_spi.c

1. from our experiment, frequent allocating/free gdma channel is causing unexpected behavior (ie. system stability issue)
2. thus we only allocate it once during the first spi operation

os/board/rtl8730e/src/component: change SPI dma channel allocation/free

---

os/Makefile.unix
os/Makefile.win

Set Tizen Lite platform version to 5.0.
It is shown in "System Informatin" when booting.
System Information:
Version:
Platform: 5.0	Binary: 200204

version: Set Tizen Lite version to 5.0

---

apps/examples/lcd_test/example_lcd.c

close the missing lcd fd in int main of example_lcd.c

apps/examples/lcd_test/:  Fix missing close fd in lcd example

---

os/drivers/pm/pm.c

This commit resolve ioctl overwrite issue of errno. Now pm_ioctl returning errno directly to fs_ioctl, which will set errno with given error.

os/drivers/pm: fix errno in pm_driver

---

tools/debug/debugsymbolviewer.py
tools/trap/ramdumpParser.py

The trap tool makes use of nm tool to look up the symbols. However the nm tool does not give exact line number for the given address. So, we change the trap tool to use nm only for symbol name and then get the exact line number using the addr2line tool.
Trap output before change:
==================
```
Stack_address	 Symbol_address	 Symbol location  Symbol_name		File_name
User stack
0x6068cbb4	 0xe01dc49	 kernel  	  sig_dispatch	/root/tizenrt/os/kernel/signal/sig_dispatch.c:435
0x6068cbc8	 0xe0293f9	 kernel  	  arm_sigdeliver	/root/tizenrt/os/arch/arm/src/armv7-a/arm_sigdeliver.c:71
0x6068cbd8	 0xe180521	 app1    	  libc_signal_main	/root/tizenrt/apps/examples/testcase/le_tc/kernel/tc_libc_signal.c:428
0x6068cc14	 0xe180521	 app1    	  libc_signal_main …
```

tools/debug: Modify the trap tool to print exact line number

---

apps/system/utils/README.md
apps/system/utils/utils_cpuload.c
os/crypto/random_pool.c
os/fs/procfs/fs_procfscpuload.c
os/fs/procfs/fs_procfsproc.c
os/include/tinyara/clock.h
os/kernel/sched/sched.h
os/kernel/sched/sched_cpuload.c
os/kernel/task/task_setup.c

This commit calculates cpu load for each core separately whereas previously it was only calculating for one core. This gives the cpu load percentage of each thread for their respective cores.
It also outputs only threads with more than 0 cpu loads
```
The previous output when when we tash command as "cpuload" was : 
TASH>> cpuload Started CPU monitor with interval 5.
PID | Pri |    2s |
--------------------------------------------------
0 |   0 |  99.1 | Idle Task
1 | 224 |   0.0 | hpwork
2 | 113 |   0.0 | lpwork
3 | 120 |   0.0 | EHCI Monitor
4 | 110 |   0.0 | LWIP_TCP/IP
5 | 250 |   0.0 | binary_manager
7 | 220 |   0.0 | /dev/mtdblock2
8 | 221 |   0.0 | msg_receiver
9 | 221 |   0.0 | multi_recv_nonblock
10 | 221 |   0.0 | multi_recv_block1
11 | 221 |   0.0 | multi_recv_block2
12 | 180 | …
```

os/kernel/sched: update cpuload measurement for smp

---

build/configs/rtl8730e/scripts/xipelf/userspace_all.ld
os/Makefile.unix

force text start to start at the start of flash partition. Also create map file for common which will be useful for debugging

build/configs, os: fix crash due to misaligned text and flash start

---

os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api_ext.c

- CSI config parameters will be passed from CA32 to KM4 for processing. Need to ensure config's buffer is aligned to prevent cache coherency issues
- Add an aligned temp buffer to store application's csi config to pass into KM4 to ensure the above point is met

os/board/rtl8730e: ensure cache coherency on csi config API

---

framework/src/tinyalsa/tinyalsa.c

apb->flags changed in wrong place, reset it when dequeue message received.

audio/tinyalsa : Fix pcm_drain logic properly

---

os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/drivers/audio/syu645b.c

1. change I2S_DMA_PAGE_SIZE 2048 -> 16384
2. change CONFIG_SYU645B_BUFFER_SIZE 2048 -> 16384
If the buffer size is too small, too many interrupts will be called, causing problems, so we allocate a larger size.
This is a temporary measure, and can be fixed later when the i2s problem is accurately analyzed.

drivers/audio: change DMA & audio buffer size

---

os/fs/procfs/fs_procfs.c
os/include/tinyara/pm/pm.h
os/pm/pm.h
os/pm/pm_domain_register.c
os/pm/pm_procfs.c

This commit extend pm_procfs to list all the domains inside 'proc/power/domains' directory based on domain_id. Now, every directory in proc/power has 'info' file which shows all the power management information related to current directory.

os/pm: Update pm_procfs to show domain information

---

os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c

- Remove while loop waiting for next frame display
- Introduce sem_wait to signal the next frame is ready to update
- Reduce CPU loading from continue checking, LCD threads will be block and be scheduled only when the resource becomes available.

os/board/rtl8730e: Change LCD update polling to semaphore

---

os/arch/arm/src/armv7-a/arm_assert.c
os/board/rtl8730e/src/component/wifi/wifi_interactive_mode.c
os/include/debug.h
os/kernel/debug/memdbg.c

For the below error the changes are made to resolve :
error: 'struct mm_heap_s' has no member named 'mm_nregions'
102 |   mllwdbg("Heap[%d] : size = %u, number of regions = %d\n", heap_idx, kheap[heap_idx].mm_heapsize, kheap[heap_idx].mm_nregions);
error: 'ifname' undeclared (first use in this function); did you mean 'rename'?
607 |    nvdbg("\n\r\nWIFI %s Status: Running", ifname[i]);
error: too few arguments to function 'wifi_set_mac_address'
886 |   nvdbg("\r\n%d", wifi_set_mac_address(argv[2]));
arm-none-eabi-ld: /root/tizenrt/os/../build/output/libraries/libarch.a(arm_gicv2_dump.o): in function `arm_gic_dumpregs':
/root/tizenrt/os/arch/arm/src/armv7-a/arm_gicv2_dump.c:115: undefined reference to `irqinfo'
arm-none-eabi-ld: /root/tizenrt/os/../build/output/libraries/libkernel.a(sysdbg. …

os/include : Fix compilation error after enabling all debug option.

---

os/arch/arm/src/armv7-a/arm_mmu.c

Previous code was checking only if size is multiple of section size for allocating section. Modified the code to allocate section if size >= section size. This also makes sure that during binary loading, each binary atmost will need 4 l2 pages, 2 for rw data atmost and 2 for rox data atmost.
Before changes :
```
mmu_allocate_app_l2_pgtbl: app_id : 0, l2idx : 0
mmu_allocate_app_l2_pgtbl: app_id : 0, l2idx : 1
mmu_allocate_app_l2_pgtbl: app_id : 0, l2idx : 2
mmu_allocate_app_l2_pgtbl: app_id : 0, l2idx : 3
mmu_allocate_app_l2_pgtbl: app_id : 0, l2idx : 4
mmu_allocate_app_l2_pgtbl: app_id : 0, l2idx : 5
mmu_allocate_app_l2_pgtbl: app_id : 0, l2idx : 6
mmu_allocate_app_l2_pgtbl: app_id : 1, l2idx : 0
mmu_allocate_app_l2_pgtbl: app_id : 1, l2idx : 1
mmu_allocate_app_l2_pgtbl: app_id : 1, l2idx …
```

arm/src/armv7-a: correct condition to allocate sections in mmu

---

os/syscall/syscall_names.c

Building loadable apps or loadable ext with sched info logs enabled for RTL8730e results in error for undefined symbol g_funcnames in os/syscall/syscall_names.c. This commit fixes the error by removing enclosing #if defined `__KERNEL__` directive and unused headers.

os/syscall: Fix link error when sched info logs enabled RTL8730e

---

os/drivers/audio/alc1019.c

change CONFIG_ALC1019_BUFFER_SIZE 2048 -> 16384
Commit is raised for RTL8730E rev 5 boards using ALC1019. 
Commit is based on following previous commit raised for rev 6 and above versions using SYU645B. https://github.com/Samsung/TizenRT/commit/e26b55ef1ca30c5f52c33a87d090232d4c51dbd1
For more details, please refer to above commit.

drivers/audio: change audio buffer size

---

framework/src/media/MediaPlayerImpl.cpp

MediaPlayerImpl.cpp: Free mBuffer memory after closing audio stream out
Issue: unprepare operation after MP3 file of 32K sample rate playback leads to heap corruption

MediaPlayerImpl.cpp: Free mBuffer memory after closing audio stream out

---

apps/examples/log_dump/log_dump_main.c
os/fs/procfs/fs_procfslogsave.c
os/include/tinyara/log_dump/log_dump.h
os/include/tinyara/log_dump/log_dump_internal.h
os/kernel/log_dump/log_dump.c

This commit adds an api to get the size of the compressed log dump.

log_dump: Add api to get size of the log dump

---

os/arch/arm/src/amebasmart/amebasmart_serial.c
os/board/rtl8730e/src/component/mbed/hal/serial_api.h
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/serial_api.c

- Do not change clock speed when baudrate is lower than 115200 during resume and suspend
- Corect serial tx empty check API

os/board/rtl8730e: Fix serial data corruption during wakeup

---

apps/shell/Kconfig
apps/shell/tash_security.c
external/include/mbedtls/mbedtls_tizenrt_config.h
external/mbedtls/Kconfig.protocol

Change TASH password encryption from SHA256 to PBKDF2 which already applied in previous version.
All of values used in this PR are sample.
- key length : 32 bytes (64 characters)
- salt : hard-coded with encrypted value (length = 16 bytes)
- iteration : 777
- default password : tizenrt

apps/shell : Apply PBKDF2 for TASH password

---

os/binfmt/libxipelf/xipelf.c
os/board/common/partitions.c
os/board/rtl8730e/src/rtl8730e_boot.c
os/board/rtl8730e/src/rtl8730e_ndp120.c
os/drivers/audio/syu645bscripts.h
os/kernel/binary_manager/binary_manager_verify.c
os/pm/pm_timedsuspend.c

libxipelf/xipelf.c:103:27: warning: assignment to 'uint32_t' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
libxipelf/xipelf.c:104:27: warning: assignment to 'uint32_t' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
libxipelf/xipelf.c:105:25: warning: assignment to 'uint32_t' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
libxipelf/xipelf.c:106:25: warning: assignment to 'uint32_t' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
libxipelf/xipelf.c:107:23: warning: assignment to 'uint32_t' {aka 'unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion] …

os: Resolve warning

---

os/drivers/pm/pm.c
os/include/tinyara/fs/ioctl.h
os/include/tinyara/pm/pm.h
os/pm/pm_suspendcount.c

This commit extends pm driver for pm suspend count. It adds API to get suspend
count of given domain id inside pm driver.

os/pm: Extend pm driver for pm suspend count

---

os/fs/driver/mtd/mtd_jedec.c

In the function "jedec_waitwritecomplete", it is assumed that "jedec_lock" has already been called, and it unlocks and locks again. However, the function "jedec_bytewrite" (which is called by "jedec_write") does not call "jedec_lock" first.
The jedec_lock contains a spi_lock, which prevents simultaneous access to spi. So, when the jedec_lock is used out of pairs, it simultaneously accesses the spi and causes a spi malfunction resulting in a device hang.
Therefore, To ensure atomic operation of the spi, Add a missing jedec_lock.

fs/driver/mtd/mtd_jedec: Add missing jedec_lock

---

apps/shell/tash_command.c

If a string longer than 15 characters is registered as a tash command like 'testtest_testsetup', there is an issue where the end of the string gets corrupted when the 'help' command is executed, resulting in output like 'testtest_testse.Y9'.
Since tash only copies the first 15 characters when registering a command, the last character in the buffer is being printed out as garbage.
To fix this, Add a null character '\0' at the 16th position so that even if a command with more than 15 characters is registered, the output value won't get corrupted.

apps/shell/tash_command: fix tash_help character breakage issue.

---

os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c

- fixed scan result data length field when it is scan response

os/board/rtl8730e: fix scan result type

---

os/drivers/ai-soc/ndp120/src/ndp120_api.c

Tested by adding a delay of 300ms, keyword data is present in the recordings.
```
ndp120_irq_handler_work: #################### winner : 0 summary : 61504 network_id : 0
[2024-09-27 12:05:41.311] ndp120_irq_handler_work: [#1 Hi-Bixby] matched: NN0:hi-bixby
[2024-09-27 12:05:41.314] #### onSpeechDetectionListener
[2024-09-27 12:05:41.328] Event SPEECH_DETECT_KD
[2024-09-27 12:05:41.328] #### [SD] keyword detected.
[2024-09-27 12:05:41.328] #### [MR] create succeeded.
[2024-09-27 12:05:41.632] #### [MR] setDataSource succeeded.
[2024-09-27 12:05:41.632] #### [MR] setObserver succeeded.
[2024-09-27 12:05:41.632] #### [MR] prepare succeeded.
[2024-09-27 12:05:41.632] startRecorder: set Current Recorder!!
[2024-09-27 12:05:41.635] ndp120_start_sample_ready: entry
[2024-09-27 12:05:41.648] …
```

Fix issue with audio tank init for NDP120, increase mic gain when using external clock

---

os/arch/arm/src/amebasmart/amebasmart_serial.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/serial_api.c

- Do not suspend and resume UART domain in IRQ, it only check FIFO not Tx buffer
- Suspend UART domain PM sleep while Tx init is set
- Correct the clock set when wake up

os/board/rtl8730e: Fix module sleep while UART buffer Tx buffer not empty

---

os/arch/arm/src/amebasmart/amebasmart_i2s.c

1. fill up all the dma pages during the first tx, this is to prevent if there are any delays/thread blocking, CPU might not have sufficient time to update the next page in IRQ handler, which will lead to noise
2. fill up all available dma pages in IRQ handler, to handle cases when there is any interrupt missed previously
3. increase page size from 2K to 4K, allow more time for CPU to update the next available page before dma trigger tx done irq. Tested and verified with Ai-lite + on-boading + bixby application original flow with 4K page size -> noise can be heard within 5mins with this commit -> no noise can be heard for more than 40mins

os/arch/arm/amebasamart: optimize I2S tx

---

os/arch/arm/src/armv7-a/arm_cpugating.c

Change Notes:
- Removed the API that was used for FreeRTOS.
- This mistake originated from the previous PR#6224, which unintentionally resulted API being added back.

os/arch/arm: Remove Unused API

---

framework/include/ble_manager/ble_common.h
framework/include/ble_manager/ble_manager.h
framework/src/ble_manager/ble_manager_api.c

- Since the `gap device name` is not used only in ble server, I modified it to define an API in ble_manager.h.
- Additionally, I defined the length of the `gap device name`, which is being used identically on each board, so that a string with corresponding length can be inputted.

framework/ble_manager: Rename api for setting gap_device_name

---

framework/src/media/FocusManager.cpp

During abndon focus, it already remove front item from list by pop_front.

framework/media : Fix abandonFocus issue.

---

apps/examples/ble_perfs/ble_perfs_main.c
apps/examples/ble_rmc/ble_rmc_main.c
apps/examples/ble_tester/ble_tester_main.c
apps/examples/testcase/ta_tc/ble_manager/itc/itc_blemanager_main.c
apps/examples/testcase/ta_tc/ble_manager/utc/utc_blemanager_main.c
framework/include/ble_manager/ble_client.h
framework/include/ble_manager/ble_manager.h
framework/include/ble_manager/ble_scan.h
framework/include/ble_manager/ble_server.h
framework/src/ble_manager/ble_manager_api.c
framework/src/ble_manager/ble_manager_autoconnect.c
framework/src/ble_manager/ble_manager_autoconnect.h
framework/src/ble_manager/ble_manager_common.h
framework/src/ble_manager/ble_manager_state.c

This reverts commit cb52843133e846c26cb141955b6f0fd44268ca40.
- To maintain compatibility with existing product codes, we postpone the renaming of functions.

Revert "framework/ble_manager: Add prefix 'ble_manager' to the function name"

---

os/drivers/ai-soc/ndp120/src/ndp120_api.c

If recording start is delayed after keyword extraction, then some audio data is lost. Fix this by moving the unread pointer to the match point so we start extraction right after the key word in the buffer.

ai-soc/ndp120: fix issue with missing data after keyword

---

os/kernel/binary_manager/binary_manager_resource.c

It takes too long to check CRC of large resource binary file. So binary manager skips crc checking resource binary when booting because it affects booting time.

kernel/binary_manager: Skip crc checking of resource binary when booting

---

apps/system/utils/README.md

This commit fixes minor typo from #s to #ps for correct link.

apps/system/utils/README.md: fix minor typo

---

apps/examples/board_specific_demo/ameba_mipi_demo/Kconfig
os/arch/arm/src/amebasmart/Kconfig
os/arch/arm/src/amebasmart/amebasmart_usb.c

Change Notes:
1. Change the select to depends on for the MIPI example. (ameba_mipi_demo/Kconfig)
- EXAMPLES_AMEBA_MIPI should be available only when AMEBASMART_MIPI is enabled, so using "depends on" is more suitable.
2. Remove the duplicate define AMEBASMART_MIPI. (amebasmart/Kconfig)
3. CleanUp the comment message. (amebasmart_usb.c)

os/arch/arm: Revise and CleanUp Config File

---

tools/uart_hw_test/uart_test.c
tools/uart_hw_test/uart_test_windows.c

Now the uart hardware test tool will include code to show tx time gap data (time gap between consecutive tx packet sent). It will show the minimum, maximum and average time gap in microsecond.
Following will be the output after new test result:
```
Enter UART port number : 4
Opened UART port : /dev/ttyUSB4
######################## UART Test Start #############################
######################################################################
Test Scenario 0: UART test only
######################################################################
[BAUD 115200 Tx] PASS
[BAUD 115200 Tx] tx packet gap stats(in usec):  Avg: 11.37  Min: 1.00  Max: 513.00
[BAUD 115200 Rx] PASS
[BAUD  38400 Tx] PASS
[BAUD  38400 Tx] tx packet gap stats(in usec):  Avg: 1.22  Min: 1.00  Max: 2.00
[BAUD  38400 Rx] …
```

tools/uart_hw_test: update tool to include tx time gap stats

---

os/arch/arm/src/armv7-a/arm_sigdeliver.c

When AMP is enabled, there is a prefetch abort during device boot up. During signal handling with SMP / AMP, the up_sigdeliver API calls leave_critical_section with the saved CPSR as an argument. At the end of leave_critical_section, this value is restored to the HW using irqrestore.
In the abort scenario, it is seen that the saved CPSR contains the user mode setting, where as we are still executing kernel code. As a result, when this CPSR value is updated, there is a prefetch abort upon executing the next instruction. To avoid this situation, we reset the mode setting value in the saved CPSR register to SYSTEM mode just before calling the leave_critical_section API.

os/arch/arm/src/armv7-a: Fix prefetch abort issue during AMP boot up

---

os/drivers/ai-soc/ndp120/src/ndp120_api.c
os/drivers/audio/ndp120_voice.c

Implement pause and resume for NDP120. We turn off the sample ready interrupts for pause, and then turn them back on for resume

os/drivers: implement pause and resume for NDP120

---

os/arch/arm/src/armv7-a/arm_dataabort.c
os/arch/arm/src/armv7-a/arm_prefetchabort.c

This patch changes the log format for data abort and prefetch abort logs to make it as same as fault handler's logs in armv8-m. It also corrects the indentation issues in the change intended files.
armv7-a old abort logs:
arm_dataabort: Data abort. PC: 0e16f0ba DFAR: 00000000 DFSR: 0000000d
armv7-a new abort logs after this commit:
print_dataabort_detail: ######################################################################### print_dataabort_detail: PANIC!!! Data Abort at instruction : 0x0e16f0ba
print_dataabort_detail: PC: 0e16f0ba DFAR: 00000000 DFSR: 0000000d
print_dataabort_detail: #########################################################################

 arch/armv7-a: change format of abort logs to match with ARMv8-M's

---

os/tools/set_bininfo.py

This script parses version configurations and write binary names using them. If there is a space at the end of the version string, an odd binary name can be generated during the + operation. So remove whitespace charaters by strip function.

os/tools/set_bininfo.py: Remove whitespace of version definition

---

os/userspace/up_userspace.c

```
/root/tizenrt/os/userspace/up_userspace.c:49:15: error: conflicting types for '_sdata'
49 | extern void * _sdata;
|               ^~~~~~
In file included from /root/tizenrt/os/include/tinyara/sched.h:75,
from /root/tizenrt/os/include/sched.h:72,
from /root/tizenrt/os/include/tinyara/arch.h:120,
from /root/tizenrt/os/userspace/up_userspace.c:43:
/root/tizenrt/os/include/tinyara/mm/mm.h:457:17: note: previous declaration of '_sdata' was here
457 | extern uint32_t _sdata;
|                 ^~~~~~
```
_sdata was defined as uint32_t in mm.h and void * in up_userspace.c. So, match both of them to uint32_t to resolve the build break

os/userspace: fix conflicting types issue for '_sdata'

---

apps/system/utils/fscmd.c

Previously, cat print out entire of buffer at once. But if there's new line or null character included in contents, it doesn't work properly. Hence print out character by character

utils/fscmd : Fix cat to display contents properly

---

apps/examples/uart_loopback/Kconfig
apps/examples/uart_loopback/Kconfig_ENTRY
apps/examples/uart_loopback/Make.defs
apps/examples/uart_loopback/Makefile
apps/examples/uart_loopback/uart_loopback.c

This is a test example where you can short-circuit the uart tx and rx boards to perform a loopback test. This test sends "1234567890abcdefghijklmnopqrstuvwxyz" and recive same string
You can use CONIFG_UART_LOOPBACK_PORT to specify the port for the loopback test.
[TEST RESULT]
TASH>>uart_loopback
TASH>>######################### UART HW test START #########################
SEND SIZE:   37
SEND UART:   1234567890abcdefghijklmnopqrstuvwxyz
RECIVE SIZE: 37
RECIVE UART: 1234567890abcdefghijklmnopqrstuvwxyz
UART LOOPBACK TEST: PASSED
;######################### UART HW test END ###########################

apps/examples: add uart_loopback_test

---

os/arch/arm/src/amebasmart/amebasmart_serial.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ap_peripheral/ameba_loguart.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/include/ameba_loguart.h

1. implement loguart interrupt mode, remove polling of tx fifo in LOGUART_PutChar which affects performance
2. add polling of tx fifo in up_putc to prevent data loss for lldbg and other low level debugging that put data directly into fifo instead of irq.

os/arch/arm/src/amebasmart: implement loguart interrupt mode

---

framework/src/ble_manager/ble_manager_state.c
os/board/rtl8730e/src/component/bluetooth/driver/platform/amebad2/hci/hci_platform.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_blemgr.c

- add hci_platform_get_ble_mac_address api to get address from efuse
- hci_platform_get_ble_mac_address can be used before BLE init

os/board/rtl8730e: get BLE MAC address before BLE init

---

os/arch/arm/src/amebasmart/amebasmart_serial.c

The uart_disabletxint is called in uart_write() and uart_xmitchars which is operating in UART TX ISR.
Since context switching can occur within the rtl8730e_up_txint function, the bsp_pm_domain_control() function may be called twice contrary to its intention. Therefore, that section is protected as a critical section.

amebasmart_serial: Fix concurrency issue in uart_disabletxint

---

apps/shell/tash_main.c

Issue: Fail TASH input when secured TASH is enabled.
Cause: Open tash_pm_open_driver after tash_check_security
Solve: Move tash_pm_open_driver before tash_check_security

apps/shell/tash_main.c: Fix board sleep during TASH password input

---

os/arch/arm/src/amebasmart/amebasmart_serial.c

1. loguart isr should set lower than other peripheral priority

os/arc/arm/src/amebasmart: set loguart isr priority as lowest

---

os/kernel/binary_manager/binary_manager.h
os/kernel/binary_manager/binary_manager_resource.c

This is recovery steps when binary in active partition is broken.
1. CONFIG_USE_BP is enabled 1) Check bootparam. 2) Check resource binary with index based on bootparam. 3) If it is invalid, check another binary in opposite partition. 4) If opposite binary is valid, update bootparam with its index.
2. CONFIG_USE_BP is disabled 1) Check resource parititions 2) Check binary with the latest version 3) If it is invalid, check another binary in opposite partition. 4) If opposite binary is valid, update bootparam with its index.
But step 3 and 4 are missing in handling resource binary.

os/kernel/binary_manager: Add recovery logic when active partition is broken for resource

---

os/arch/arm/src/amebasmart/amebasmart_reboot_reason.c

- Determine reboot reaso 251 to is due to which core and print it

os/arch/arm/src/amebasmart: Determine reboot by which core and print it

---

os/include/tinyara/pm/pm.h
os/pm/pm_initialize.c
os/pm/pm_metrics.c
os/pm/pm_procfs.c

This commit resolve the below build warnings:
```
warning: 'pm_state_name' defined but not used
warning: 'wakeup_src_name' defined but not used
warning: unused variable 'pm_state'
warning: assignment discards 'const' qualifier from pointer target type
warning: assignment to 'pm_metric_t *' {aka 'struct pm_metric_s *'} from 'int' makes pointer from integer without a cast
```

os/pm: resolve build warnings

---

os/include/tinyara/lcd/lcd.h

UI build triggers warning , need forward declaration of structure

os/include/tinyara/lcd: forward declare struct to avoid warnings

---

os/drivers/input/touchscreen.c
os/include/tinyara/input/touchscreen.h

Add support for Touch wakeup and touch suspend. Added ioctl for it

os/drivers/input: Add ioctl for Touch Wakeup and suspend

---

apps/examples/wakerec/wakerec.cxx
os/board/rtl8730e/src/rtl8730e_ndp120.c
os/drivers/ai-soc/ndp120/src/ndp120_api.c
os/drivers/ai-soc/ndp120/src/syntiant_portability.c
os/drivers/audio/ndp120_voice.c

when "SYNTIANT_NDP_ERROR_DATA_REREAD" error occurs, zero is returned in the argument extract size as no bytes are extracted. However, in the next iteration, zero is passed as extract size, causing to extract the entire audio tank, hence corrupting the heap. This exactly matches the crash we observed as the heap corrupted (around 60KB) matches the size of the audio tank (60KB)

Sync NDP drivers code

---

os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2s_api.c

It was observed on some board that the BCLK signal of I2S is glitchy during rapid sleep/resume 
This lead to 2 issues:
- BCLK stuck high when wakeup causing audio unable to play as WCLK cannot be generated. Board unable to sleep as I2S TX is never completed
- BCLK generated but audio buffer is corrupted causing noise, since the bits are invalid when BCLK glitches
This fix completely turns off peripheral clock for I2S2/3 and ensure complete deinit during PG 
After power state change, this fix ensure that clock latches to correct frequency. There is no impact to wakeup time as the clock init delay is done in full resume
Verification: BCLK signal is cleanly generated, audio playback is clean without distortion after ~30 playback attempts

os/board/rtl8730e: fix clock instability of I2S when entering/exiting PG

---

os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2s_api.c

1. Only pinmux MCLK if required
2. remove I2S2 MCLK since it is not required in pinmux table

os/arch/arm/src/amebasmart: remove PB22 for I2S2 MCLK

---

os/drivers/pm/pm.c
os/include/tinyara/fs/ioctl.h
os/include/tinyara/pm/pm.h
os/kernel/init/os_start.c
os/pm/pm.h
os/pm/pm_idle.c
os/pm/pm_initialize.c
os/pm/pm_metrics.c

This commit enable applications to start power
management system. This API should be called
when board is ready to transition into low
power state. This API helps PM to remove the
use of `PM_IDLE_DOMAIN` outside the scope of PM.
`pm_start` - This API meant to be called during app
initialization to enable low power state transition.
In PM side we can reduce some of the costlier operation
based on the `is_running` flag. In the event of crash
and app reloading, this API can be used for reinitialization.
`pm_resume` - This API removes pm state transition lock for
specific domain. It has domain information, which helps PM
to do domain specific operation, like "when LCD domain get
resume, do backlight dimming". This should be used in pair
with `pm_suspend` API.
`pm_suspend` and `pm_resume` are …

os: Add pm_start api

---

os/board/rtl8730e/src/rtl8730e_boot.c

This commit brings up PB22 gpio pin. This pin will be used as wake up source for lcd.

rtl8730e_boot.c: bringup gpio PB22 pin for lcd

---

os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/arch/arm/src/amebasmart/amebasmart_spi.c

1. each priv struct should only be made available if it is enabled in menuconfig
2. it will return NULL when port is not enabled, error handling should be added in places calling intialization

os/arch/arm/src/amebasmart: add related macro on peripherals priv struct

---

os/include/tinyara/input/touchscreen.h

There was a build error in UI like below.
```
include/tinyara/input/touchscreen.h:191:2: error: 'sem_t' does not name a type
191 |  sem_t sem;
|  ^~~~~
include/tinyara/input/touchscreen.h:194:2: error: 'sem_t' does not name a type
194 |  sem_t pollsem;
```
Add missing header(semaphore.h) to fix build error.

os/include/tinyara/input/touchscreen.h: Add missing header

---

os/board/rtl8730e/src/rtl8730e_ist415.c

If you call GPIO_WriteBit right after calling I2c_write, there is an issue where the FIFO does not become empty after putting data in I2C FIFO. (I2C_BIT_TFE)
we have to check two point.
1. Why is there a problem with using I2C immediately after writing to GPIO?
2. When writing to I2C, do we have to put it in the FIFO and wait for the FIFO to be empty?
The changes is workarount adding delay

os/board/rtl8730e: Workaround fix I2C hang issue during boot

---

os/arch/boardctl.c

To check who called to reset the board, add outputting the pid running the boardctl.

arch/boardctl: Add printing board reset caller pid.

---

os/drivers/lcd/lcd_dev.c

When the LCD backlight is on, defer the PM operation. During LCD initialization, the LCD backlight is set to maximum power, but since we are not calling pm_suspend, the board enters sleep mode after LCD initialization.
Therefore, Add calling pm_suspend in lcd init.

os/drivers/lcd: Add suspend pm operation during lcd init.

---

os/board/rtl8730e/src/rtl8730e_ist415.c

The workaround message for ist415 driver is replaced to indicate the root cause due to LDO voltage unstable before soft startup is complete (~500us)

os/board/rtl8730e/src: update ist415 gpio reset delay workaround message

---

os/arch/arm/src/armv7-a/arm_assert.c
os/arch/arm/src/armv7-a/arm_doirq.c

Assert logs wrongly indicate the crash to be in irq context when the actual crash is in normal context, but on a different cpu. The issue is happening due to missing code to check the proper cpu when SMP is enabled.

os/arch/arm/src/armv7-a: Fix wrong assert logs

---

os/arch/arm/src/amebasmart/amebasmart_usb.c
os/arch/arm/src/armv7-a/arm_initialize.c

1. allow it to boot normally even with no USB attached, use task instead of busy wait for usb init.
2. once USB attached, logs and tash can be input from usb port.

os/arch/arm/src/amebasmart: allow booting normally when USB not attached

---

os/fs/driver/mtd/smart.c

If a thread writes something in fs when eraseing whole fs, it can make some fs corruptions. So I add irq lock when calling bulkerase to avoid scheduling.

fs/driver/mtd: Lock irq when erasing fs to avoid fs corruption

---

os/board/rtl8730e/src/component/usrcfg/rtl8730e/ameba_pinmapcfg.c
os/board/rtl8730e/src/rtl8730e_boot.c

Change Notes:
The current pinmapcfg is based on the AILite modules (consolidated AILite, AILite+ and AILite+W).
Samsung requires modifications to the PuPd for both cases: Func PuPd and Sleep PuPd.
Refer to the UM0602_RTL8730E_pinmux_v1.3(85339)_241212.xls.

os/board/rtl8730e: Modify PinMode AILite

---

os/board/rtl8730e/src/component/bluetooth/api/rtk_stack/rtk_stack_le_gap.c
os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_blemgr.c

- when extended adv and scan is turned on, legacy scan may stop unexpectedly
- with this commit extended scan will always be used when extended adv and extended scan is turned on

os/board/rtl8730e: fix scan stop when extended adv and extended scan is enabled

---

apps/system/utils/fscmd.c

Previously the cat is printing newline after every 100th character which
leads to line break for read data from file. This commit resolve this
issue by reverting the code changes.
Before:
```
TASH>>cat /proc/power/domains/info
DOMAIN ID |            DOMAIN NAME            | SUSPEND COUNTS
-----------|-----------------------
------------|----------------
0 |                              IDLE |              0
1 |                            SCREEN |              0
2 |                              UART |              1
3 |
SPI |              0
4 |                              TASH |              2
```
After:
```
TASH>>cat /proc/power/domains/info
DOMAIN ID |            DOMAIN NAME            | SUSPEND COUNTS
-----------|-----------------------------------|----------------
0 | …
```

apps/system/utils: fix cat to display contents properly

---

os/include/signal.h
os/include/stdlib.h

Issue: Getting below build warnings
```
include/signal.h:590:83: WARNING: 'int sigaction(int, const sigaction*, sigaction*)' hides constructor for 'struct sigaction' [-Wshadow]
590 | int sigaction(int sig, FAR const struct sigaction *act, FAR struct sigaction *oact);
include/stdlib.h:603:30: WARNING: 'mallinfo mallinfo()' hides constructor for 'struct mallinfo' [-Wshadow]
603 | struct mallinfo mallinfo(void);
```
Cause: the struct `sigaction` and function `sigaction` is declared with same
name. During compilation they were part of same  namespace that's
causing shadowing of struct with function declaration. Same is true for
`mallinfo`
Resolution: Disable shadow warning during function declaration and
enable it after declaration.
Note: GCC>=7 doesn't throw this error with -Wshadow flag. …

os/include: resolve build warnings

---

os/arch/arm/include/reboot_reason.h
os/arch/arm/src/armv7-a/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c
os/arch/arm/src/common/up_reboot_reason.c
os/arch/arm/src/stm32h745/stm32h745_systemreset.c
os/include/tinyara/reboot_reason.h

Earlier, ASSERT(PANIC) cases used to have same reboot reason as user intended reboot function (boardctl). So now, this patch adds new reboot reason for ASSERT cases to seperate out the reason.
Updated reboot reason:
REBOOT_SYSTEM_USER_INTENDED        = 56, /* Reboot from user intention */
REBOOT_SYSTEM_ASSERT               = 59, /* Reboot from ASSERT or PANIC */

os/arch/arm: separate the reboot reason for assert and boardctl reboot

---

os/arch/arm/src/armv7-a/arm_dataabort.c
os/arch/arm/src/armv7-a/arm_prefetchabort.c

This commit introduces a new line code in assert logs so that user can distinguish between normal logs and crash logs.

os/arch/armv7-a: new line to distinguish between normal and crash logs

---

apps/examples/ble_rmc/ble_rmc_main.c
os/board/rtl8730e/src/component/bluetooth/example/ble_central/ble_tizenrt_client.c
os/board/rtl8730e/src/component/bluetooth/example/ble_peripheral/ble_tizenrt_server.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_blemgr.c

- add function to update BLE connection parameter for slave and master

os/board/rtl8730e: add connection parameter update for BLE

---

os/arch/arm/src/amebasmart/amebasmart_i2c.c

it's calling sem_wait for i2c usage.
The i2c hang issue is occuring if it is using i2c in work queue.
The work queue operation is using signal a lot, and The signal can wakeup a sem blocking with return EINTR errno. So, we should check if errno is EINTR, then we call sem_wait again.
The i2c hang issue is wrong check condition for calling sem_wait again above case . The while condition should be ret != OK.

os/arch/arm/amebasmart: Fix I2C hang issue.

---

os/board/rtl8730e/src/component/os/tizenrt/rtk_netmgr.c

- Problem: When scan_ap_config_count is 0, will print "Can't malloc memory for channel list"
- Root cause: malloc(0) returns NULL
- Fix: Add check before malloc
- Add multi scan scenario: If config is not NULL, scan_all is false, scan_ap_config_count is 0, then do not scan

os/board/rtl8730e: fix multi scan ap config count 0

---

os/board/rtl8730e/src/component/wifi/api/wifi_ind.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api_basic.c

- Previously, both wifi_disconnect and wifi_join_status_indicate could trigger TizenRT wifi linkdown callback
- Re-arrange flow such that TizenRT wifi linkdown callback is only called from RTK wifi disconnect handler for STA mode

os/board/rtl8730e: Optimize wifi disconnect handler

---

os/drivers/lcd/lcd_dev.c

Replaced the global LCD HAL layer instance with a local declaration within the lcddev_register() function to reduce memory usage and passed this instance to LCD_FLUSH_THREAD by converting its address to a string using atoi() function.

Remove global structure in LCD HAL Layer

---

os/include/assert.h
os/include/tinyara/mm/mm.h
os/include/tinyara/wdog.h
os/kernel/wdog/Make.defs
os/kernel/wdog/wd_dbg.c
os/kernel/wdog/wd_initialize.c
os/kernel/wdog/wd_start.c
os/kernel/wdog/wdog.h
os/mm/mm_heap/mm_heap_dbg.c

This PR adds debug log in wd_expiration. It logs the  wdog structure
value which can be useful to debug the cause of timer expiration fail.
This PR also modifies the wdog struct to keep track of process pid
which is responsible for timer creation.

os/kernel/wdog: add debug logs in wd_expiration

---

apps/shell/tash_main.c

Issue: Showing TASH command before TASH login
```
PASSWORD>>
PASSWORD>>*
ocf              otn
TASH>>o
ocf              otn
TASH>>o
ocf              otn
TASH>>o
ocf              otn
```
Cause: Allow tab operation before TASH login
Solve: Allow tab key only after TASH login

apps/shell/tash_main.c: Disable Tab Key before verifying TASH password

---

os/arch/arm/src/armv7-a/arm_schedulesigaction.c

The up_schedule_sigaction increases the target task's stack frame to execute the sigaction operation,
allowing the sigdeliver operation to be performed before the running operation.
Since it changes the stack, SP, and PC, it should be protected from IRQ operations including context switching.
If unprotected, a context switch may occur during the change of stack and PC, causing the target task to operate with incorrect stack SP and resulting in a crash.

os/arch/armv7-a: Add enter_critical_section in up_schedule_sigaction

---

os/arch/arm/src/armv7-a/arm_cpupause.c
os/include/tinyara/spinlock.h
os/kernel/irq/irq_csection.c

To pause the cpu, cpu should call `up_cpu_paused`. The call to `up_cpu_paused` will get missed when `g_cpu_irqlock` is unlocked (means none of the cpu having access to irqlock), `arm_pause_handler` rely on `enter_critical_section` to pause the cpu, it must handle `up_cpu_pausereq` without any fail, otherwise other cpu will wait forever in spinlock.
Change `while` loop to `do-while` loop in `irq_waitlock`, which will ensure there is no pending `up_cpu_pausereq` before getting lock on `g_cpu_irqlock` otherwise pause request will get missed.
The `SP_DMB` is needed to ensure both cpu read correct spinlock value.
The `spin_lock(&g_cpu_resumed[cpu])` is moved upward in code to avoid race condition between cpus.

os: fix amp hang issue

---

os/kernel/sched/Make.defs
os/kernel/sched/sched.h
os/kernel/sched/sched_addreadytorun.c
os/kernel/sched/sched_checkstackoverflow.c
os/kernel/sched/sched_removereadytorun.c

This commit changes logging method from dbg to lldbg to print stack overflow information. This is done because after stack overflow, using dbg does not work because of more stack memory requirement. But in the lldbg case, it uses low level syslog, so it uses minimal stack memory.
logs before:
```
cycle in normal thread done
stack base ptr of normal thread is 0xdeadbeef
cycle in recursive thread done with cnt 423
security level: 0
===========================================================
Assertion details
===========================================================
print_assert_detail: Assertion failed CPU0 at file: sched/sched_removereadytorun.c line 125 task: recusrsive_thread pid: 20
print_assert_detail: Assert location (PC) : 0x0e01b587
```
logs after changing to lldbg:
```
cycle in …
```

kernel/sched: fix logging after stack overflow

---

os/drivers/memory/mminfo.c
os/include/tinyara/mm/mm.h
os/mm/kmm_heap/kmm_calloc.c
os/mm/kmm_heap/kmm_malloc.c
os/mm/kmm_heap/kmm_memalign.c
os/mm/kmm_heap/kmm_realloc.c
os/mm/kmm_heap/kmm_zalloc.c
os/mm/mm_heap/mm_mallinfo.c
os/mm/mm_heap/mm_manage_allocfail.c
os/mm/umm_heap/umm_calloc.c
os/mm/umm_heap/umm_malloc.c
os/mm/umm_heap/umm_memalign.c
os/mm/umm_heap/umm_realloc.c
os/mm/umm_heap/umm_zalloc.c

Modify mm_manage_allocfail API to print alignment value for which the allocation has failed.

os/drivers, os/mm: Modify mm_manage_allocfail to print alignment

---

os/kernel/sched/sched_checkstackoverflow.c

The current code updates critical section to ensure use of critical section to print lldbg logs only when stack overflow occurs. Previously it was happening everytime sched_removereadytorun api is called.
Verified on both SMP and NON SMP case

sched/sched_checkstackoverflow: update critical section check

---

os/drivers/input/ist415.c
os/drivers/input/ist415.h
os/drivers/input/ist415_misc.c
os/drivers/input/ist415_misc.h
os/drivers/input/ist415_update.c

1. Apply semaphore related to the IC reset of ist415.
2. Apply recording mode to the ist415_cmd.

Add ist415 semaphore and recording mode.

---

apps/examples/uart_loopback/uart_loopback.c

Add '-p' and '--port' option
The option is set the uart port ttySx as ttyS1 or ttyS2, etc. The option input type is integer.

apps/examples/uart_loopback: Add option uart port selection

---

os/arch/arm/src/armv7-a/arm_dataabort.c
os/arch/arm/src/armv7-a/arm_prefetchabort.c
os/arch/arm/src/armv7-a/arm_undefinedinsn.c
os/mm/mm_heap/mm_manage_allocfail.c

When assert or fault happens due to abort or mem alloc failure, we need to update the reboot reason immediately and then start printing the detailed logs. When we update reboot reason, the KM4 core will avoid printing its own logs, which might otherwise result in log mixup while printing important information about assert situation.

os/mm, os/arch: Update reboot reason before printing logs

---

os/arch/arm/src/armv7-a/arm_schedulesigaction.c

This patch fix the assert issue happened on product with commit ("os/arch/armv7-a: add api to pause and resume all CPUs") If signaling task is scheduled on the current CPU, then we don't need to resume the other CPUS as we don't pause them before.
This patch is tested on both public and ecode. We are not able to reproduce the reported assert with the patch.

arch/armv7-a: fix assert in up_cpu_resume() with common pause API

---

os/arch/arm/src/armv7-a/arm_gicv2.c
os/include/tinyara/arch.h

This commit adds a new API for gic module. It adds "up_affinity_irq" api that sets affinity of irq(SPI) to a specific core. Note that it does not support assigning multiple core yet.

armv7-a/arm_gicv2.c: add api for setting irq affinity

---

framework/src/ble_manager/ble_manager_state.c

- In the case where the LL connection establishment fails or pairing fails while entering the BLE_CLIENT_CONNECTING state after a connect request from the client, neither the connected callback nor the disconnected callback is called, resulting in continued waiting. Therefore, I modified it so that when connection or pairing fails, the disconnected callback is called to allow reconnection attempts.
Related PR : PR #6649

framework/ble_manager: Call disconnected callback when connection or pairing failed in client

---

os/drivers/Makefile
os/drivers/silent_reboot/Make.defs
os/drivers/silent_reboot/silent_reboot_driver.c
os/include/tinyara/fs/ioctl.h
os/include/tinyara/reboot_reason.h
os/include/tinyara/silent_reboot.h
os/kernel/Kconfig
os/kernel/Makefile
os/kernel/init/os_bringup.c
os/kernel/silent_reboot/Make.defs
os/kernel/silent_reboot/silent_reboot.c

- Support silent reboot driver for ioctl (lock, unlock, delay, checkmode)
- Set silent mode based on reboot reason
- Support periodic silent reboot when all the following conditions are satisfied.
- Random time in (00:00 ~ 5:00 am) after 7 days from system boot.
- No lock

os/kernel: Support silent reboot

---

apps/examples/touchscreen/touchscreen_main.c
os/drivers/input/touchscreen.c
os/include/tinyara/input/touchscreen.h

Added two new IOCTL commands TSIOC_ENABLE and TSIOC_DISABLE to enable and disable the touch functionality in the touch driver.

os/drivers/input/touchscreen.c: Add IOCTL for enabling and disabling touch

---

os/drivers/input/ist415.c

- Modify `ist415_disable_touch()` to call `ist415_suspend_device()`, changing the power mode accordingly and disabled touch when knockknock is enabled to optimize power consumption.
- Modify `ist415_enable_touch()` to call `ist415_resume_device()`, restoring appropriate power mode and enable the touch when knockknock is enable.

os/drivers/input/ist415.c: Update ist415_disable_touch() and ist415_enable_touch() logic

---

os/drivers/silent_reboot/Make.defs
os/drivers/silent_reboot/silent_reboot_driver.c
os/kernel/init/os_bringup.c
os/kernel/silent_reboot/silent_reboot.c

Build and Register silent_reboot driver when CONFIG_SILENT_REBOOT is enabled only to reduce unnecessary memory usages.

silent_reboot: Build and Register silent_reboot driver when CONFIG_SILENT_REBOOT is enabled only

---

apps/shell/tash_sleep.c
apps/shell/tash_usleep.c

Issue: NULL Pointer dereference vulnerability can be occurred in tash_sleep / tash_usleep
Reference: https://github.com/Samsung/TizenRT/issues/6617
Solved: Add NULL pointer check for args[1]

apps/shell/tash_sleep.c: Add NULL check for args

---

os/mm/mm_heap/mm_manage_allocfail.c

Reboot reason update code is missing in alloc fail scenario.

os/mm: Add missing code for reboot reason

---

os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/board/rtl8730e/src/rtl8730e_st7789.c

-Only disable SWD when PA_14 is in use
-Prevent all LCD model to disable SWD

os/board/rtl8730e: Only disable SWD when PA_14 is in use

---

os/board/rtl8721csm/src/component/os/tizenrt/rtk_blemgr.c

-Adding NULL to sync BLE APIs table
-To prevent APIs mismatch

os/board/rtl8721csm: Sync the BLE APIs table

---

os/drivers/input/ist415.c
os/drivers/input/ist415.h

Change to tunr off ist415 power when touch is disabled from apps for reduce power consumption.

os/driver/input/ist415: Change to power off when touch disabling

---

os/tools/mkverifyappsize.py

we need only 4 l2 pages at maximum for each app. 2 pages for the start and end of read only region, and two pages for the start and end of write-read region. Hence, maximum number is 4.

os/tools: fix condition for checking max l2 pages needed for binary

---

os/board/rtl8730e/src/component/lwip/api/lwip_netconf.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api.c

This PR consists of two commits
1. modify RTK API to obtain LWIP info using APIs from TizenRT netlib
2. modify hook for PMU_WLAN_DEVICE to fix Host Unknown API(0)!

os/board/rtl8730e/src: update ip addr hook for pm

---

os/drivers/input/ist415.c
os/drivers/input/ist415_misc.c
os/drivers/input/ist415_misc.h

- Add tmode command.
- tmode is a command that disables Alive and Interrupt to connect the Tool for CS noise testing.

driver/input: Add ist415 tmode command

---

os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/lcd/mipi_lcd.c

1. There will be cases when LCD power off is called, but module do not enter PG. In this case, the lcdc and mipi drivers need not to re-initialize when LCD power on is called.
2. When LCD power on, we need to switch MIPI to cmd mode to send the lcd init cmd.
3. Fix UI coordinate offset shift gradually in lcd power on/off long run test

os/board/rtl8730e/src: modify LCD power on/off flow

---

external/mbedtls/x509_create.c

Issue: Integer Overflow vulnerability in Mbed TLS 2.x before 2.28.7 and 3.x before 3.5.2, allows attackers to cause a denial of service (DoS) via mbedtls_x509_set_extension(). (CVE-2024-23775)
Solve: Ensure that a length of SIZE_MAX cannot be passed into mbedtls_x509_set_extension()
https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2024-01-2/# 
https://github.com/Mbed-TLS/mbedtls/blob/v3.6.2/library/x509_create.c#L385

external/mbedtls/x509_create.c: Fix CVE-2024-23775

---

os/board/rtl8730e/src/component/soc/amebad2/fwlib/rom_common/ameba_gpio_rom.c

1. With SMP/AMP, there might be race condition when both Core 0 and Core 1 attempt to modify the GPIO simultaneously, causing the the value pin to be abnormal
2. enter_critical_section is required to ensure that only one core can modify the GPIO register at any given time, we can prevent simultaneous access to the GPIO data register, thus eliminating the race condition.

os/board/rtl8730e/src/compoent: add critical section to GPIO write bit

---

os/pm/pm_idle.c

During the callback operation for suspending device, if another thread is awakened by sem_post, context switching may occur. This can cause the irq disable to be released, allowing the tick irq to occur, and cpu1 may already be in a hotplug situation, causing device hang due to cpu_pause being called for scheduling.
Therefore, Add sched_lock during board sleep.

os/pm: Add sched_lock to avoid context switching during pm_idle

---

os/drivers/silent_reboot/silent_reboot_driver.c
os/include/tinyara/silent_reboot.h
os/kernel/silent_reboot/silent_reboot.c

Change return type from int to bool because it just get gloval variable value and always return OK.

silent_reboot: Change return type of silent_reboot_is_silent_mode to bool

---

os/arch/arm/src/amebasmart/amebasmart_mipi.c

1. add 5s timeout for the send_cmd_done to prevent stucked in infinite loop

os/arch/arm/src/amebasmart: add timeout for mipi transfer

---

os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/lcd/mipi_lcd.c
os/include/tinyara/lcd/mipi_lcd.h

Command mode keeps the LCD in black frame which is needed just after power on.
APP will send its buffer after power on and then mipi mode will be changed to video

os/drivers/lcd: Use command mode to turn screen to black after power on

---

framework/src/ble_manager/ble_manager_lwnl.c
os/include/tinyara/ble/ble_manager.h
os/net/blemgr/bledev.c
os/net/blemgr/bledev_mgr_server.c

- Resolved the issue where the config passed to the driver in the function that calls the newly added server config after ble_manager init is NULL.
- Set the profile count value to 0 in g_server_null_config

framework/ble_manager : Fix the issue of server config being passed as NULL value

---

os/arch/arm/src/armv7-a/arm_schedulesigaction.c

When we perform signaling a task and the task is running on some other CPU, we need to pause the other CPU only. We don't need to pause all other CPUs. This patch fixes it.

os/arch/armv7-a: Modify cpu pause-resume during signal handling

---

os/kernel/sched/sched_cpuselect.c

On running memleak assertion error is coming. This error is because the task has max priority and while assigning cpu, the condition checks for the tasks which has priority less than max priority thus cpu value remains impossible value.
Result log after fixing and running memleak-
Kernel :
*** NO MEMORY LEAK.
Below are text addresses of loadable apps (and common binary if enabled) :
The pc value of the allocation can be obtained by subtracting the text start address of the appropriate binary
[common] Text Addr : 0xe161010, Text Size : 8679424
[app1] Text Addr : 0xe9a8030, Text Size : 4894720
app1 :
*** NO MEMORY LEAK.

os/kernel/sched: Fix for memleak not working with AMP

---

os/arch/arm/src/amebasmart/amebasmart_mipi.c
os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/lcd/mipi_lcd.c

1. when lcd power off, it switches to cmd mode, we should keep it in cmd mode, and set lcdonoff as LCD_OFF
2. So that when lcd power on, we do not need to switch to cmd again to send init cmd table
3. move video mode switch out from rtl8730e_enable_lcdc so that when wake up from PG, it stays in cmd mode
4. when lcd power off, we need to check if there is pending framedone interrupt in LCDC before disable irq, and if there is, sem_post, to prevent g_next_frame_block being hold during lcd power off, and when power on again, it could not send next frame. Eg: fps_test() is sending frames very fast, so it will hit the case where it sem_wait at rtl8730e_lcd_put_area and at the same time lcd power off.

os/driver/lcd: modify lcd power on off flow

---

os/arch/arm/src/amebasmart/amebasmart_mipi.c

1. send_cmd_done flag is updated in ISR, add volatile to prevent compiler from optimizing out memory reads, ensures the latest value is always read from memory.
2. since it is just a flag, use u8 instead of u32.

os/arch/arm/src/amebasmart: declare send_cmd_done flag as volatile

---

os/kernel/silent_reboot/silent_reboot.c

While building getting this error:
arm-none-eabi-ld: /root/tizenrt/os/../build/output/libraries/libkernel.a(silent_reboot.o): in function `silent_reboot_delay':
/root/tizenrt/os/kernel/silent_reboot/silent_reboot.c:309: undefined reference to `get_errno'
arm-none-eabi-ld: /root/tizenrt/os/../build/output/libraries/libkernel.a(silent_reboot.o): in function `silent_reboot_force_perform_after_timeout':
/root/tizenrt/os/kernel/silent_reboot/silent_reboot.c:340: undefined reference to `get_errno'
To solve this added reference of get errno.

os/kernel/silent_reboot: Add reference in silent reboot delay

---

os/binfmt/binfmt_execmodule.c
os/binfmt/binfmt_loadbinary.c
os/kernel/binary_manager/binary_manager.h
os/mm/Makefile
os/mm/mm_heap/mm_manage_allocfail.c

This commit adds code to update printing logs after memory allocation failure in user heap. Previously, It was only printing user heap summary and node info. But now it will also print logs for the summary of kernel heap information.
Below is the updated logs after user heap memory alloc error (memory overflow) :
```
Inside thread2_task
Assigned 10Kb mm_manage_alloc_fail: Allocation failed from user heap.
mm_manage_alloc_fail:  - requested size 1024000
mm_manage_alloc_fail:  - caller address = 0x0e16ed59
mm_manage_alloc_fail:  - largest free size : 60960
mm_manage_alloc_fail:  - total free size   : 69248
mm_check_heap_corruption: Heap start = 0x63a81230 end = 0x63f7fff0
mm_check_heap_corruption: No heap corruption detected …
```

os/mm: update crash logs of memory alloc failure

---

os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/input/touchscreen.c
os/drivers/lcd/lcd_dev.c
os/drivers/lcd/mipi_lcd.c

During initialization if silent reboot is detected,
LCD backlight is off
Touch is disabled
By default LCD backlight is set to 0,
It has been verified for LCD and touch both

Silent reboot check

---

os/board/rtl8730e/src/component/bluetooth/api/rtk_stack/rtk_stack_gatts.c

-alloc_ind is not clear, caused accidentally free of memory
-Clear alloc_ind field in struct rtk_bt_gatt_service

os/board/rtl8730e: Fix incorrect BLE init that causes double free in deinit

---

os/drivers/lcd/mipi_lcd.c

The issue was that LOGO couldn't be displayed properly due to MSB and LSB bits were interchanged. This commit  fix this bug. Increase in sharpness in LOGO

os/drivers/lcd/mipi_lcd.c/: Fix LOGO when fill data in buffer interchange MSB and LSB bits

---

os/arch/arm/src/armv7-a/arm_assert.c

Initially app heap is only check when crash location is in app. So changes are added to check each app heap if crash is in kernel. So app heap is always check. For testing whether app heap is check or not, kernel side is made to crash and these are logs- =========================================================== Loading location information
=========================================================== elf_show_all_bin_section_addr: [common] Text Addr : 0xe161010, Text Size : 8679424 elf_show_all_bin_section_addr: [app1] Text Addr : 0xe9a8030, Text Size : 4894720 =========================================================== Checking each app heap for corruption
=========================================================== Checking app index 1 …

os/arch/arm/src: Fix for checking app heap always during crash

---

os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_blemgr.c

- previously for ble_server_get_conn_handle_by_addr and ble_server_get_mac_addr_by_conn_handle, the input and output BLE address are reversed
- fixed address reversal in these 2 APIs

os/board/rtl8730e: fix BLE address reverse

---

os/arch/arm/src/armv7-a/arm_assert.c
os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c

This patch adds the condition check to avoid the series of aborts.
Test Results:
=========================================================== Checking kernel heap for corruption
=========================================================== mm_check_heap_corruption: Heap start = 0x6011c440 end = 0x6027fff0 mm_check_heap_corruption: No heap corruption detected
print_dataabort_detail: #########################################################################
print_dataabort_detail: PANIC!!! Data Abort at instruction : 0x0e0013b6
print_dataabort_detail: PC: 0e0013b6 DFAR: 00000000 DFSR: 0000080d
print_dataabort_detail: #########################################################################
boardctl: Board will Reboot now. pid: 20

os/arch/armv7-a: Add condition to avoid recursive abort

---

os/arch/arm/src/armv7-a/arm_assert.c
os/arch/arm/src/armv7-m/up_assert.c
os/arch/arm/src/armv7-r/arm_assert.c
os/arch/arm/src/armv8-m/up_assert.c

This patch adds new variable abort_state for recursive abort to avoid conflict with existing variable abort_mode.
Test results:
=========================================================== Loading location information
=========================================================== elf_show_all_bin_section_addr: [common] Text Addr : 0xe161010, Text Size : 3112960 elf_show_all_bin_section_addr: [app1] Text Addr : 0xe459030, Text Size : 1417216
print_dataabort_detail: #########################################################################
print_dataabort_detail: PANIC!!! Data Abort at instruction : 0x0e001340
print_dataabort_detail: PC: 0e001340 DFAR: 00000000 DFSR: 0000080d
print_dataabort_detail: #########################################################################
boardctl: Board will …

arch/arm: fix variable conflict by adding new one for recursive abort

---

os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c

For PWM control of the backlight of the ST7785 and ST7701SN LCDs, the maximum brightness is achieved when the PWM output is 0. Therefore, after booting and initializing the PWM, since the output power is 0, the LCD backlight is set to maximum brightness.
Since we only set the LCD backlight to maximum brightness in cases other than silent reboots, to set the default backlight brightness to 0 after booting, we need to set the PWM output power to 100 (MAX) after booting.
Therefore, Add to set lcd backlight 0 during lcd init.

os/board/rtl8730e/rtl8730e_mipi_lcdc: Change to booting backlight 0

---

os/drivers/input/ist415.c

The method of checking whether the touch IC is turned off using the forcedoff variable is only possible when the app forcibly turns off the touch IC.
To prevent I2C reads when the IC is reset due to other logic such as lockup, Change it to check the "enable" variable, which is disabled during power off.

os/drivers/input/ist415: Change to check the IC off state as "enable"

---

os/drivers/input/ist415.c

-Move wd_create() just above the ist415_start() call inside ist415_initialize() to ensure the watchdog is created before being started. -Remove wd_start() from ist415_initialize() since it is already called inside ist415_start() and was redundant.

os/drivers/input/ist415.c: Fix watchdog setup order

---

os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/board/rtl8730e/src/component/mbed/hal/i2c_api.h
os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2c_api.c

This commit refactors peripheral object to remove kmm_free in suspend flow
The memory region is instead reused by memset to 0 and then reinitialized

os/arch/arm/src/amebasmart: refactor peripheral suspend flow memory management

---

os/board/rtl8730e/src/component/bluetooth/example/ble_scatternet/scatternet.c

-Reserve BLE MAC address before passing it to BLE manager

os/board/rtl8730e: BLE reserve MAC address before returning

---

os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/arch/arm/src/amebasmart/amebasmart_i2s.c
os/arch/arm/src/amebasmart/amebasmart_i2s.h
os/board/rtl8730e/src/rtl8730e_alc1019.c
os/board/rtl8730e/src/rtl8730e_i2schar.c
os/board/rtl8730e/src/rtl8730e_syu645b.c

the board sleep seqeunce is in idle.
So, we can't call sem_wait in this time because we can't give up the cpu in idle.
Therefore, Remove sem calling situation during enter PG

os/arch/arm/amebasmart: Remove sem calling during enter PG.

---

os/board/rtl8730e/src/rtl8730e_ist415.c
os/drivers/input/ist415.c

The ist415_initialize () function had several error return paths where allocated resources such as semaphores, watchdog timers, and kernel threads were not properly released. This could lead to memory leaks on initialization failure. This commit ensures that all allocated resources are correctly cleaned up in all failure scenarios.

os/drivers/input/ist415.c: Fix memory leaks in ist415_initialize() on error paths

---

os/kernel/sched/sched_removereadytorun.c

Assert fail is observed at below lines of code.
ntcb = (FAR struct tcb_s *)rtcb->flink;
DEBUGASSERT(ntcb != NULL);
However, we need to check the flink only if the list is runnable. Otherwise the list can be empty and we dont need to check flink.

os/kernel/sched: Fix assert fail in remove readytorun

---

os/drivers/memory/mminfo.c
os/include/tinyara/fs/ioctl.h
os/include/tinyara/kmalloc.h
os/include/tinyara/mm/mm.h
os/kernel/sched/sched_garbage.c
os/mm/mm_heap/mm_malloc.c
os/mm/mm_heap/mm_manage_allocfail.c
os/mm/mm_heap/mm_memalign.c

When a task or thread is terminated, we place the stack details in a queue and it will be freed at a later point using the LPWORK thread. However, if LPWORK is not able to run due to some reason, then we run into "out of mem" error.
This commit adds code to check and release all the dead task stack space when we run into "out of mem" scenario.
Test results
===============
```
Test stack free for dead tasks
Create 5 tasks with 100KB stack
up_create_stack: Stack = 0x6028bff0
up_create_stack: Stack = 0x602a54d0
up_create_stack: Stack = 0x602be9b0
up_create_stack: Stack = 0x602d7e90
up_create_stack: Stack = 0x602f1370
Sleep for 10 secs
task_0 start
task_1 start
task_2 start
task_3 start
task_4 start
task_0 exit
task_1 exit
task_2 exit
task_3 exit
task_4 exit
All 5 tasks must be dead by now. …
```

os/mm, os/drivers, os/include: Fix mem alloc fail due to dead task stack

---

os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e/i2c_api.c
os/board/rtl8730e/src/component/soc/amebad2/fwlib/ram_common/ameba_i2c.c

1. add timeout to break from infinite loop when waiting for i2c rx flag in case error occur in middle of rx
2. in case where i2c stucked in trap state, we should only re-try limited times to prevent infinite loop.

os/board/rtl8730e/src: add timeout for i2c read

---

os/drivers/input/ist415.c

- Fixed an issue where sem_wait and sem_post did not match depending on the conditions.

driver/input/ist415: Patch semaphore issue.

---

os/mm/mm_heap/mm_memalign.c

This commit fix build error due to an uninitialized variable.

mm/mm_heap/mm_memalign.c: Fix build error

---

os/arch/arm/src/amebasmart/amebasmart_i2c.c
os/board/rtl8730e/src/rtl8730e_ist415.c

since we are calling up_i2cuninitialize and up_i2cinitialize during ist415 TSC power on/off sequence for recovery I2C operation.
but the up_i2cuninitialize has sem_destroy
so the sem is destoryed, but a crash is occurring by accessing the sem from another thread.
we just need i2c operation recovery, therefore replace up_i2cuninitialze to amebasmart_i2c_deinit

arch/amebasmart, board/rtl8730e: Fix i2c sem corruption issue

---

os/drivers/input/ist415.c
os/drivers/input/ist415.h

Touch is a user interaction, so when a touch is detected, the power management is delayed
for a certain period to prevent entering power sleep mode.
Furthermore, when I2C is used for checking the touch IC alive, the PM is also delayed
to avoid entering power sleep mode and blocking the I2C.

drivers/input: Add suspending PM when a touch input.

---

os/include/tinyara/clock.h
os/kernel/clock/clock_initialize.c

The clock_getinittime returns system initalized time

kernel/clock: Add clock_getinittime API

---

os/kernel/pthread/pthread.h
os/kernel/pthread/pthread_completejoin.c
os/kernel/pthread/pthread_condtimedwait.c
os/kernel/pthread/pthread_condwait.c
os/kernel/pthread/pthread_create.c
os/kernel/pthread/pthread_detach.c
os/kernel/pthread/pthread_initialize.c
os/kernel/pthread/pthread_join_internal.c
os/kernel/pthread/pthread_mutex.c
os/kernel/pthread/pthread_mutexlock.c

According to posix standard, if a pthread is waiting to aquire mutex and gets interrupted by a signal, then it is supposed to execute the signal and then continue to wait for the mutex.
Previously, our code allowed to pass an argument which decided whether an EINTR error is retured or not. Since this is not posix compliant behavior, this commit removes this argument.
Kernel tc has be verified with this commit.

os/kernel/pthread: Pthread mutex wait must not reutrn EINTR

---

os/dutils.sh

This patch adds custom path support for toolchain command while using dutils script.

os: add custom path support for toolchain command

---

tools/trap/cli/logParser.py

This patch fixes issue of trap not working by adding the required self keyword to the variable in logparser.py

tools/trap: add missing "self" keyword to the variable in trap tool

---

tools/trap/cli/logParser.py

The crash point was not being printed properly for armv7a related aborts such as data abort, prefetch abort and undefinedins. This is because the trap tool was missing the logic to parse these abort types.
```
Data abort output before this commit
==================================================================
1. Crash Binary             : app1
2. Crash type               : code assertion by code ASSERT or PANIC
3. Crash point
- armv7-a/arm_dataabort.c line 218 task: preLoader pid: 111
Data abort output with this commit
==================================================================
1. Crash Binary             : app1
2. Crash type               : data abort
Crash log
- Assertion failed CPU0 at file: armv7-a/arm_dataabort.c line 218 task: preLoader pid: 111
3. Crash point (PC or LR)
[ …
```

tools/trap: Handle armv7a related aborts in trap tool

---

os/arch/arm/src/common/up_restoretask.c
os/binfmt/binfmt_arch_apis.c
os/kernel/task/task_setup.c

If a kernel thread gets created from an app thread, then it must not inherit the app uheap, uspace and memory protection data.

os/kernel/task: Kernel thread must not inherit app's heap, etc..

---

os/arch/arm/src/amebasmart/amebasmart_enet.c
os/board/rtl8730e/src/component/os/tizenrt/ethernetif_tizenrt.c
os/board/rtl8730e/src/component/os/tizenrt/rtk_netmgr.c
os/board/rtl8730e/src/component/usrcfg/rtl8730e/ameba_wificfg.c
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_trx.c

- Certain parts of wifi porting code requires to be changed if concurrent mode is supported in the future
- Main point is to ensure wlan index on the application side is matched to the correct interface in wifi driver
- Use preprocessor CONFIG_RTK_CONCURRENT_MODE to set the right code flow based on whether concurrent mode is supported

os/board/rtl8730e: Modify wifi porting layer to prep for concurrent

---

os/include/tinyara/clock.h
os/kernel/clock/clock_initialize.c

Correct a tpyo in description
initalized -> initialized

os/kernel/clock: Correct a typo in description

---

os/arch/arm/src/amebasmart/amebasmart_smp.c
os/arch/arm/src/armv7-a/arm_cpugating.c

If this cpu has already been paused, then we
will not perform gating. However, we will set
the gating flag as if gating is performed. This
is because, the main intention of both gating and
pausing the cpu is to prevent the cpu from running. Since this is already handled and cpu is in pause state, we can perform critical opertion assuming gating is done. At a future point of time, the cpu will get resumed by the code which had initially paused it
NOTE: This only works for 2 cpu case, in case of more cpus, we need to redesign the pause and gating logic such that only the cpu or the task which called pause is allowed to call resume.

arch/armv7-a: Change cpu gating logic when cpu is already paused

---

os/arch/arm/src/amebasmart/amebasmart_smp.c
os/arch/arm/src/amebasmart/amebasmart_timerisr.c
os/arch/arm/src/armv7-a/arm_cpugating.c
os/arch/arm/src/armv7-a/arm_cpupause.c
os/arch/arm/src/armv7-a/arm_cpustart.c

This PR demonstrates functional switching of systick count when pausing a core.
As systick is counted by each individual core's timer PPI, it will trigger independently of each other. Currently, this will cause the system tick to have multiple count and affect OS timing.
To avoid multiple counting, only one core will be allowed to increment the common OS tick counter
If Core0 happens to be paused, then the other core should take over, and then return control when Core0 resumes
Please check with flat_dev_ddr config

os/arch/arm/src: SMP/AMP migrate systick control to running core during pause

---

apps/system/utils/utils_ps.c
os/fs/procfs/fs_procfsproc.c
os/include/tinyara/binfmt/binfmt.h
os/include/tinyara/sched.h
os/kernel/init/os_start.c

Remove conditional directives use from all enums in os/include

os/include: Remove conditional directives use from all enums.

---

os/arch/arm/src/amebasmart/amebasmart_i2s.c

i2s driver allocate wd when it initialized. Hence it should not set as null even if suspend called.

rtl8730/i2s : do not set watch dog as a null when i2s_suspend called

---

os/binfmt/binfmt_unloadmodule.c

This commit updates binfmt/binfmt_unloadmodule.c file to remove warning message during build. Follwing is the logs during build before this changes:
binfmt_unloadmodule.c: In function 'unload_module': binfmt_unloadmodule.c:138:6: warning: unused variable 'section_idx' [-Wunused-variable]
138 |  int section_idx;
|      ^~~~~~~~~~~

os/binfmt: Fix code to remove warning message during build

---

os/board/rtl8730e/src/component/wifi/driver/include/autoconf_8730e.h

- Set maximum STA connections allowed in SoftAP mode to 3

os/board/rtl8730e: Limit max STA connection in SoftAP

---

os/board/rtl8730e/src/component/wifi/api/wifi_ind.c
os/board/rtl8730e/src/component/wifi/driver/include/wifi_intf_drv_to_upper.h
os/board/rtl8730e/src/component/wifi/inic/inic_ipc_host_api_basic.c

- wifi_disconn_hdl will set error_flag based on join status failure
Co-authored-by: jwei5 <48531347+jwei5@users.noreply.github.com>

os/board/rtl8730e: print connection fail reason code for wifi sta mode

---

os/include/tinyara/kmalloc.h
os/kernel/init/os_start.c
os/kernel/sched/sched.h
os/kernel/sched/sched_free.c

In a flat build, sched_kfree is used, which adds addresses to the queue but does not free memory because sched_kcleanup is excluded from the build.
This results in memory accumulation in the g_delayed_kfree queue, leading to allocation failures during prolonged operation.
The issue arises because sched_kfree is enabled under the condition #if defined(CONFIG_MM_KERNEL_HEAP),
while sched_kcleanup is enabled only under #if (defined(CONFIG_BUILD_PROTECTED) || defined(CONFIG_BUILD_KERNEL)) && defined(CONFIG_MM_KERNEL_HEAP).
In flat builds (where CONFIG_BUILD_PROTECTED and CONFIG_BUILD_KERNEL are disabled), sched_kfree is active, but sched_kcleanup is excluded,
causing memory to accumulate without being freed.
To resolve this, the activation condition for sched_kfree has been updated to include …

kernel/sched: Fix sched_kfree Memory Leak in flat build

---

os/kernel/sched/sched_unlock.c

- Fix the function name from undefined function `sched_reassess_timer` to correct function `sched_timer_reassess` in `sched_unlock.c`.
- `CONFIG_SMP` not defined case has right function name. (line 275)

os/kernel: Rename function name in sched_unlock

---

os/kernel/irq/irq_csection.c

- Correct the input parameter comment from rtcb to cpu in irq_cpu_locked.
- Write a description of input parameter `cpu`.

os/kernel/irq: Correct the input parameter comment in irq_cpu_locked.

---

external/include/libcxx/cmath
os/include/tinyara/math.h

This resolves the linkage error(multiple definitions) when `cmath` header is included multiple times.
and
The original implementation returned true for NaN due to flawed comparison logic.  
This replaces `(x != NAN)` with `!isnan(x)` to correctly handle NaN values.

external/libcxx: Fix linkage error and implementation error of math

---

os/drivers/lcd/Kconfig

Update LCD_LOGO Kconfig to disable by default.
LCD logo is not essential.

os/drivers/lcd: Update LCD_LOGO config

---

external/libcxx-test/std/containers/associative/map/map.modifiers/erase_iter.pass.cpp
external/libcxx-test/std/containers/associative/multimap/multimap.modifiers/erase_iter.pass.cpp
external/libcxx-test/std/containers/unord/unord.map/unord.map.modifiers/erase_const_iter.pass.cpp
external/libcxx-test/std/containers/unord/unord.multimap/unord.multimap.modifiers/erase_const_iter.pass.cpp
external/libcxx-test/support/is_transparent.h
external/libcxx-test/support/private_constructor.hpp
external/libcxx-test/support/test_allocator.cpp

Issue:
When upgrading to C++14, the build of `Map` test failed due to missing `TemplateConstructor` and comparison operators for `PrivateConstructor`. These were likely excluded previously because TizenLite merges all tests into a single executable, causing linker errors ("multiple definitions").
Fix:
Resolve ODR violation by declaring missing operators as `inline` and `static` functions in the shared header.
Reference:
The approach is inspired by LLVM’s test structure (https://github.com/llvm/llvm-project/tree/main/libcxx/test).
This commit makes libcxx-test can be built in C++14.

external/libcxx-test: Fix build issue in C++14

---

apps/examples/testcase/le_tc/kernel/tc_libc_signal.c
apps/examples/testcase/le_tc/kernel/tc_pthread.c
apps/examples/testcase/le_tc/kernel/tc_task.c

On running kernel_tc following testcases are failing- [tc_pthread_set_get_affinity] FAIL [Line : 1641] pthread create : Values (ret_chk == 0x0) and (22 == 0x16) are not equal [tc_task_task_restart] FAIL [Line : 292] task_restart : Values (ret_chk == 0xffffffff) and (0 == 0x0) are not equal [tc_task_task_reparent] FAIL [Line : 531] task_reparent : Values (tc_reparent_chk == 0x2) and (0 == 0x0) are not equal [tc_libc_signal_sigwait] FAIL [Line : 425] waitpid : Values (recv_ret == 0xffffffff) and (ERROR == 0xffffffff) are equal

apps/examples/testcase/le_tc/kernel: Fix failing kernel testcases

---

external/include/libcxx/cmath
os/include/tinyara/math.h

`cmath` should include libcxx internal `math.h`
but it has included the wrong `math.h` from `os/include/math.h`
and the `isfinite()` macro was incorrectly implemented.
- isfinite(NAN) incorrectly returned true.
- Caused by (x != NAN) which always evaluates to true for NaN (since NaN != NaN).
This fixes the wrong inclusion by changing the angle bracket to quote mark
and replace the wrong implementation of `isfinite`.
This **REVERTS** the old wrong workaround to provide isinf, isfinite, isnan.

external/libcxx/cmath: Fix incorrectly included and implemented math.h

---

os/mm/mm_heap/mm_check_heap_corruption.c
os/mm/mm_heap/mm_free.c
os/mm/mm_heap/mm_heap_dbg.c
os/mm/mm_heap/mm_malloc.c
os/mm/mm_heap/mm_memalign.c
os/mm/mm_heap/mm_node.h
os/mm/mm_heap/mm_realloc.c
os/mm/mm_heap/mm_shrinkchunk.c

mm/mm_heap: add mm_dump_heap_free_node_list function
add mm_dump_heap_free_node_list function.
This function prints the hex valuse contents of heap free nodes using heap free node list.
example logs:
` #########################################################################################
Dump heap free node list
[ndx], [HEAD]: [FREE NODES(SIZE)]
` #########################################################################################
0, 1003dc80:
1, 1003dc98:
2, 1003dcb0:
3, 1003dcc8: 0200f220(240)
4, 1003dce0:
5, 1003dcf8: 02012dc0(592) 02016b70(576)
6, 1003dd10: 0201eb70(1488)
7, 1003dd28:
8, 1003dd40:
9, 1003dd58:
10, 1003dd70:
11, 1003dd88:
12, 1003dda0:
13, 1003ddb8:
14, 1003ddd0:
15, 1003dde8:
16, 1003de00: 02201a10(1828320)
17, 1003de18:
18, 1003de30:
` …

add DEBUGASSERT_MM_FREE_NODE macro 

---

os/board/rtl8720e/src/component/bluetooth/example/ble_central/ble_tizenrt_client.c
os/board/rtl8730e/src/component/bluetooth/example/ble_central/ble_tizenrt_client.c
os/board/rtl8730e/src/component/bluetooth/example/ble_peripheral/ble_tizenrt_server.c

-Added 3 second timeout for while
-Prevent hang forever when GAP state not change

os/board/rtl8730e: Revise BLE while loop condition

---

os/arch/arm/src/amebasmart/amebasmart_mipi.c
os/board/rtl8730e/src/rtl8730e_mipi_lcdc.c
os/drivers/lcd/Kconfig
os/drivers/lcd/mipi_lcd.c
os/drivers/lcd/st7785.c
os/include/tinyara/lcd/mipi_lcd.h

This commit fixes several issues in MIPI driver when certain LCDs are forcefully disconnected and reconnected, causing the driver stack to stop TX/RX. This issue was verified to happen on ST7785 panels, but not on ST7701 panels (using the respective configs)
The init sequence is retried multiple times (power cycle -> reset lcd -> reset driver stack)
Additional error handling is added for MIPI DPHY error cases such as ERRCONTROL and ERRSYNCESC, which happen when the LCD is out of sync with the MIPI host
```
TASH>>
TASH>>lcd_test
TASH>>=== LCD demo ===
xres : 320, yres:240
<--- LCD is detached during the test (display colors/patterns)
lcddev_ioctl: LCD Backlight 100 -> 0
lcd_setpower: Powering down the LCD
lcd_setpower: Switch to CMD mode
lcd_setpower: Changed lcd backlight to 0 …
```

os/drivers/lcd: Fix LCD mipi reinit flow

---

apps/system/utils/Kconfig
apps/system/utils/utils_stackmonitor.c
os/kernel/debug/Make.defs
os/kernel/debug/dbg_termination_info.c
os/kernel/debug/debug.h
os/kernel/task/task_prctl.c

- Add CONFIG_STACKMONITOR_DISABLE_DEAD_THREAD (bool, default n).
- When enabled, dead thread stack infos are not stored, reducing RAM consumption.
- When disabled, the stack monitor retains stack info of threads that have exited.

apps/system/utils/stackmonitor : Add config to toggle dead thread stack info

---

os/kernel/clock/clock_getres.c
os/kernel/clock/clock_gettime.c
os/kernel/environ/env_getenvironptr.c
os/kernel/pthread/pthread_keycreate.c
os/kernel/sched/sched_waitpid.c

For some syscalls, there are security issues because null check is not performed in corresponding kernel apis. This pr adds null check

os/kernel/: Add null check to some kernel api

---

os/.gitignore

the .download file is generated during bianry download script and app_size_file is generated in mkverifyappsize.py os.system('size ' + file_path + ' > ' + APP_SIZE_FILE)
So two files are generated by script.
Therefore, Add gitignore

os/.gitignore: Add gitignore ".download", "app_size_file" files

---

apps/examples/lcd_test/Makefile
apps/examples/lcd_test/example_lcd.c
apps/examples/lcd_test/lcd_verification.c

Add test functionality for LCD verification. Implemented the following test cases:
- Checkerboard pattern test
- Line drawing test (horizontal, vertical, diagonal)
- Circle test for distortion check
- Sliding frame test (left-right and top-down)
- Gradual brightness test (Increases brightness from 0 to 100 and vice-versa)

apps/examples/lcd_test/examples_lcd.c: Add verification test support for LCD

---

os/arch/arm/src/armv7-a/arm_cpuhotplug.c
os/include/tinyara/arch.h
os/kernel/irq/irq_csection.c
os/pm/pm_idle.c

Fix a deadlock issue that occurs after recent systick control migration commits (0192d1ef1, 96706497d, 6e46e19bc) where CPU1 receiving IRQ interrupts.
The deadlock scenario:
- CPU0 calls enter_critical_section() and requests CPU1 hotplug, then waits
- CPU1 receives tick IRQ and calls enter_critical_section(), waiting for completion
- This creates a circular dependency where both CPUs wait for each other
Solution:
when a secondery CPU is waiting for critical section entry while a hotplug request is pending, abort the hotplug operation and pm entering sleep.
Add Optimize spinlock-based synchronization for CPU hotplug requests.

arch: armv7-a: Fix deadlock between CPU hotplug and IRQ critical section

---

os/drivers/pm/pm.c
os/include/tinyara/pm/pm.h
os/pm/pm.h
os/pm/pm_changestate.c
os/pm/pm_domain_register.c
os/pm/pm_idle.c
os/pm/pm_resume.c
os/pm/pm_suspend.c
os/pm/pm_wakehandler.c

This commit reorganizes the PM metrics related macros in the header files to improve code clarity and maintainability.
And, Remove #ifdef CONFIG_PM_METRICS in entire PM metrics api used location to consistency.
This change helps prevent potential compilation issues and makes the code more readable by centralizing the conditional macro definitions.

pm: Fix wrong pm metrics macros and remove checking CONFIG_PM_METRICS

---

os/pm/pm.h

The semicolon was missed at void pm_metrics_update_wakehandler(clock_t missing_tick, pm_wakeup_reason_code_t wakeup_src)
Add semicolon

pm/pm.h: Add missing semicolon

---

os/board/rtl8721csm/src/libs/RELEASE_NOTE.txt

- Add IGTK check when receive group rekey from AP
- If PMF is enabled, received management frames will skip software decryption if hardware decryption is used already

os/board/rtl8721csm: Fix delayed download due to ADDBA negotation failure with AP

---

os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/example/ble_scatternet/ble_tizenrt_scatternet_app.c

- moved BLE indication semaphore release before calling app layer callback p_func
- to avoid semaphore not released due to action is done in app layer callback p_func

os/board/rtl8721csm: fix BLE indicate semaphore release

---

apps/examples/security_test/hal/hal_auth_test.c

1. get_hmac
- `HAL_HMAC_SHA256` -> `HAL_KEY_HMAC_SHA256`
- `mode` in `hal_generate_key` is `hal_key_type`
- `HAL_HMAC_SHA256` is `hal_hmac_type`, which is used in `hal_get_hmac`
2. ecdsa_sign
- `HAL_HMAC_SHA256` -> `HAL_HASH_SHA256`
- `hash_t` in `hal_ecdsa_mode` is `hal_hash_type`

apps/examples/security_test/hal/hal_auth_test.c: Fix invalid parameter
