- apps/system/utils/kdbg_stackmonitor.c
… in stack monitor
When enable CONFIG_DEBUG_MM_HEAPINFO, stackmonitor can show the peak size of heap per thread
> Expand to show the peak size of heap

- apps/system/init/init.c
- os/include/inttypes.h
- os/kernel/Kconfig
fix warnings on compilation and menuconfig
> Common warnings

- apps/system/utils/kdbg_heapinfo.c
- os/include/tinyara/mm/mm.h
- os/mm/mm_heap/mm_heapinfo.c
in heapinfo, there are 4 options
i: initialize the heapinfo
a: show the all allocation details
p(#): show the specific pid allocation details
f: show the free list
> add the feature to show the details per pid in heapinfo

- build/configs/sidk_s5jt200/openocd/s5jt200_silicon_evt0_fusing_flash_all.cfg
> Return exit code 0 after using openocd script

- os/kernel/semaphore/sem_wait.c
CONFIG_TINYARA_DEBUG is not supported
> remove unncessary codes

- README.md
- build/configs/sidk_s5jt200/README.md
add a link which has environment set-up for sidk_s5jt200
> modify readme for tizen wiki and sidk_s5jt200

- os/tools/configure.sh
- os/tools/setenv.sh
Add usage for setenv.sh. Remove default toolchain path
> Locate setenv.sh in os/tools

- build/output/libraries/README.txt
modify legacy explanations and add a method to add external libraries
> modify contents of libraries's README

- build/configs/sidk_s5jt200/hello_with_tash/Make.defs
- build/configs/sidk_s5jt200/kernel_sample/Make.defs
- build/configs/sidk_s5jt200/sidk_s5jt200_download.sh
- build/configs/sidk_s5jt200/tc/Make.defs
It makes we can download a binary using make download ALL for sidk_s5jt200.
> modify codes for programming on sidk_s5jt200

- os/tools/memstats_gnueabil.py
reflect SPIN's modification into GitHub
> Fix bug in memstat tool

- apps/examples/iperf/iperf_tcp_info.c
- apps/wpa_supplicant/Makefile
- os/drivers/net/Kconfig
I've encountered some trivial errors and warnings while trying to build the latest master branch of TizenRT with artik053/nettest configuration. I am sure that some of them were never seen before. It is hard to figure out why it started to happen at this time.
This commit fixes those errors I've found. Please review.
> Fix artik053

- os/drivers/usbhost/usbhost_storage.c
- os/fs/driver/mtd/ftl.c
- os/fs/driver/mtd/mtd_partition.c
- os/fs/driver/mtd/mtd_procfs.c
- os/fs/driver/mtd/smart.c
- os/fs/procfs/fs_skeleton.c
- os/fs/smartfs/smartfs_procfs.c
typo: numer -> number, attribtes -> attributes
> Fix typos in files of os/drivers

- lib/libc/time/lib_daysbeforemonth.c
Month starts from 0 to 11(Jan to Dec)
> Add a description for clock_daysbeforemonth

- apps/examples/wakaama_client/wakaama_client.c
- apps/wpa_supplicant/src/common/wpa_ctrl.c
- framework/include/dm/dm_connectivity.h
- framework/src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c
[Description] Added new APIs to DM module to start device in WiFi STA mode, perform DHCP and WiFi channel scans
> [Title] New DM connectivity APIs for WiFi start, DHCP and scan

- framework/src/iotbus/iotapi_evt_handler.c
- framework/src/iotbus/iotbus_gpio.c
- applying changed gpio logic
- add iotapi log configs
> Fix iotbus bugs

- os/arch/arm/src/artik053/src/Makefile
- os/arch/arm/src/sidk_s5jt200/src/Makefile
fix compilation error on boardctl
> Boardctl error

- apps/examples/telnetd/Makefile
- build/configs/artik053/artik053_download.sh
- os/arch/Kconfig
- os/arch/arm/src/armv7-r/arm_assert.c
- os/arch/arm/src/armv7-r/arm_vectors.S
- os/arch/arm/src/common/up_internal.h
- os/drivers/usbdev/Make.defs
- os/drivers/usbdev/cdcacm.c
- os/drivers/usbdev/cdcacm.h
- os/drivers/usbdev/cdcacm_desc.c
- os/drivers/usbdev/composite.c
- os/drivers/usbdev/composite.h
- os/drivers/usbdev/composite_desc.c
- os/drivers/usbdev/pl2303.c
- os/drivers/usbdev/usbdev_strings.c
- os/drivers/usbdev/usbdev_trace.c
- os/drivers/usbdev/usbdev_trprintf.c
- os/drivers/usbdev/usbmsc.c
- os/drivers/usbdev/usbmsc.h
- os/drivers/usbdev/usbmsc_desc.c
- os/drivers/usbdev/usbmsc_scsi.c
- os/drivers/wireless/scsc/Make.defs
- os/include/tinyara/irq.h
- os/kernel/irq/irq_dispatch.c
- os/kernel/wdog/wd_create.c
- os/kernel/wdog/wd_delete.c
Someone removed commits from master. This is a pull reqeust them to recover.
> Recover master

- external/Kconfig
…of undeclared variable errors with a more understandable #error statement
> Added a condition check for DM wifi setting. This will replace a lot of undeclared variable errors with a more understandable #error statement

- os/include/tinyara/logm.h
- os/logm/Kconfig
- os/logm/Makefile
- os/logm/logm.c
- os/logm/logm.h
- os/logm/logm_get.c
- os/logm/logm_process.c
- os/logm/logm_set.c
- os/logm/logm_start.c
- os/logm/logm_tashcmds.c
- os/logm/logm_test.c
. Change logic of buffer usage
. Support tash commands for logm configuration in run-time
. Support prepending timestamp to messages
. Clean unnessasary codes
> Update logm module

- os/tools/mkconfig.c
remove slash about comment in mkconfig
> change wrong comment in mkconfig

- apps/system/utils/fscmd.c
Use arguments as function parameters directly in tash_cat function.
That can be validated by argc.
> Use arguments as function parameters directly in tash_cat function.

- apps/system/utils/Kconfig
- apps/system/utils/Makefile
- apps/system/utils/kdbg_commands.h
- apps/system/utils/kdbg_uptime.c
- apps/system/utils/kernelcmd.c
Add uptime to TASH commands
uptime print how long the system has been running
> Add uptime to TASH commands

- os/tools/memstats_gnueabil.py
Change-Id: Ic7d44d03c84e5b2507ac6d2b0af9d5c5d176f493
Signed-off-by: Youngeun Park <youngeun.park@samsung.com>
> Update memstats_gnueabil.py to print objects sizes in a sorted manner

- os/kernel/pthread/pthread_condwait.c
pthread_condwait should give mutex, take cond->sem, then take mutex
> Fix error in pthread_condwait

- apps/system/utils/kdbg_date.c
- apps/system/utils/kdbg_heapinfo.c
- apps/system/utils/kdbg_kill.c
- apps/system/utils/kdbg_stackmonitor.c
Update usage and syntax for some kdbg commands, date, heapinfo, stkmon, kill and killall
> Update usage and syntax for some kdbg commands

- os/fs/mount/fs_mount.c
Add and Modify comment about returned value in fs mount function
> Add and Modify comment about returned value in fs mount function

- apps/examples/slsiwifi/Kconfig
- apps/examples/smart/Kconfig
- apps/wpa_supplicant/Kconfig
- os/drivers/Kconfig
- os/drivers/wireless/Kconfig
1. fix incorrect sentence
2. remove duplicated comments
3. add comments to split different modules
> modify Kconfig

- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_conn.c
- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_lwm2m.c
- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_main.c
@Taejun-Kwon Please review the changes to utc
@sunghan-chang Please check coding format if ok
> Modified DM utc to fix build errors

- os/kernel/task/task_delete.c
> Follow coding style in task_delete.c

- apps/system/utils/kdbg_heapinfo.c
- apps/system/utils/kdbg_ps.c
- apps/system/utils/kdbg_stackmonitor.c
- os/mm/mm_heap/mm_heapinfo.c
New changes can be verified using TASH
1) with CONFIG_MAX_TASKS=0
TASH>>ps
PID | PRIO | FLAG |  TYPE   | NP |  STATUS
------|------|------|---------|----|--------
0 |    0 | FIFO | KTHREAD |    | READY
1 |  224 | RR   | KTHREAD |    | WAITSIG
3 |  125 | RR   | TASK    |    | RUNNING
2) with CONFIG_MAX_TASKS=31
TASH>>ps
PID | PRIO | FLAG |  TYPE   | NP |  STATUS  | NAME
----|------|------|---------|----|----------|----------
0 |    0 | FIFO | KTHREAD |    | READY    | Idle Task
1 |  224 | RR   | KTHREAD |    | WAITSIG  | hpwork
3 |  125 | RR   | TASK    |    | RUNNING  | tash
> Cosmetic changes for "ps" command output

- os/fs/procfs/fs_procfsproc.c
- os/fs/procfs/fs_procfsuptime.c
- os/fs/procfs/fs_procfsversion.c
Add or delete '\n' to values read from procfs
> Modify values read from procfs to match output formats

- apps/examples/testcase/le_tc/filesystem/fs_main.c
Remove aio feature, add description of Tizen Style
> Apply latest tc of fs

- os/kernel/semaphore/sem_tickwait.c
Some functions (sem_trywait()) inside wd_delete() may fail and set the
errorno. this would override the any errors set by previous logic.
In recursice  error scenario, catch the first error and set it as errorno
> Fix: Avoid overwriting the first error set by sem_wait()

- os/kernel/semaphore/sem_holder.c
Return values are NULL, however it's mentioned as OK and ERROR, Correct the same
> sem_holder : Modify the incorrect description

- apps/examples/testcase/le_tc/kernel/tc_task.c
1. modify that checking the creation more than the CONFIG_MAX_TASKS
2. Fix the immortal tc_vfork task
> Modify the tc_task for vfork

- apps/examples/testcase/ta_tc/systemio/utc/Kconfig
- framework/include/iotbus/iotbus_i2c.h
- framework/include/iotbus/iotbus_spi.h
- framework/src/iotbus/iotapi_evt_handler.c
- framework/src/iotbus/iotbus_i2c.c
- framework/src/iotbus/iotbus_spi.c
Modify SYSTEMIO APIs parameter and fix build error
> Modify SYSTEMIO APIs parameter and fix build error

- apps/examples/testcase/le_tc/kernel/tc_libc_stdio.c
> Fix asprintf tc

- apps/examples/iotivity_simpleserver/README.md
- external/iotivity/README.md
- external/iotivity/iotivity_1.2-rel/README.md
Please review @lssgood @sangwon03 
If you have any additional comments to update README, please mention that.
> Add README for IoTivity and a sample app

- apps/examples/iotbus_test/Kconfig
- apps/examples/iotbus_test/Kconfig_ENTRY
- apps/examples/iotbus_test/Make.defs
- apps/examples/iotbus_test/Makefile
- apps/examples/iotbus_test/iotbus_test_main.c
Add new iotbus app for gpio usage
> Add new iotbus app for gpio usage

- apps/examples/testcase/le_tc/kernel/tc_libc_stdio.c
- apps/examples/testcase/le_tc/kernel/tc_libc_stdlib.c
- apps/examples/testcase/le_tc/kernel/tc_libc_timer.c
- apps/examples/testcase/le_tc/kernel/tc_pthread.c
- apps/examples/testcase/le_tc/kernel/tc_semaphore.c
- apps/examples/testcase/le_tc/kernel/tc_task.c
Refactor sscanf, pthread_mutex, pthead_once, sem_timedwait, prctl, sem_destroy, strftime, qsort, strtod, bsearch
> Kernel tc refactoring

- apps/examples/testcase/le_tc/network/tc_net_accept.c
Please review @junmin-kim @jeongchanKim
> Change a name of testcase to avoid a conflict with math functions.

- apps/examples/testcase/tc_common.h
> Modify macro in tc_common.h

- os/include/stdlib.h
- os/include/tinyara/math.h
Change-Id: I275d42bbdb3f36da935c5d0d3e23d58c34f20b65
> Add the doxygen format comments for stdlib.h, math.h

- lib/libc/stdio/lib_fopen.c
- os/fs/mount/fs_umount.c
- os/fs/vfs/fs_rename.c
Fix typing error and wrong logic
> Fix somethings wrong in fs functions

- apps/examples/testcase/le_tc/kernel/tc_libc_pthread.c
- apps/examples/testcase/le_tc/kernel/tc_libc_stdio.c
- apps/examples/testcase/le_tc/kernel/tc_sched.c
- apps/examples/testcase/le_tc/kernel/tc_semaphore.c
Refactor  semaphore, libc_pthread, sprintf, sched_gettcb
> Refactor kernel tc

- build/configs/artik053/tash/Make.defs
- build/configs/sidk_s5jt200/hello/Make.defs
- build/configs/sidk_s5jt200/kernel_sample/Make.defs
- build/configs/sidk_s5jt200/tc/Make.defs
Add -Werror config and fix file path comment
> Build config

- apps/examples/testcase/le_tc/kernel/tc_group.c
- apps/examples/testcase/le_tc/kernel/tc_libc_spawn.c
- apps/examples/testcase/le_tc/kernel/tc_sched.c
CONFIG_USERMAIN_STACKSIZE should be used for main task stacksize
> Replace CONFIG_USERMAIN_STACKSIZE with other name in tc

- .travis.yml
to use Travis CI, .travis.yml is needed.
from this commit, if new pull request or branch has this file, travis would build tizenrt automatically with commits
> Add .travis.yml for CI env

- .travis.yml
- README.md
- Travis CI builds 3 configs(tash/nettest/minimal).
- README shows the result of build with latest master
> Travis & README update

- apps/shell/Makefile
- apps/shell/tash_command.c
- apps/shell/tash_internal.h
- apps/system/utils/Makefile
- apps/system/utils/fscmd.c
- apps/system/utils/netcmd.c
- os/include/tinyara/fs/fs_utils.h
Add conditionals of CONFIG_DISABLE_ENVIRON to functions which have dependency on it
> Add conditionals regarding CONFIG_DISABLE_ENVIRON

- apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
- framework/src/arastorage/aql_exec.c
- framework/src/arastorage/db_options.h
- framework/src/arastorage/index_bplustree.c
- framework/src/arastorage/index_manager.c
- framework/src/arastorage/relation.c
1. Some bug fixes discovered in the process of expanding tc .
2. Expanded tc to increase code coverage.
> Changes in arastorage 

- apps/examples/sysio_test/sysio_main.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c
- framework/include/iotbus/iotbus_spi.h
- framework/src/iotbus/iotbus_spi.c
Remove the unavailable iotbus_spi api funtion
> Remove the unavailable iotbus_spi api funtion

- tools/ramdump/ramdump_protocol.txt
I corrected the errata in txt file and filename.
> correction of errata (protocal --> protocol)

- lib/libc/math/lib_cbrtl.c
- lib/libc/math/lib_exp2l.c
- lib/libc/math/lib_modf.c
- lib/libc/math/lib_modff.c
- lib/libc/math/lib_modfl.c
- lib/libc/math/lib_remquol.c
- lib/libc/math/lib_roundf.c
- lib/libc/math/lib_sqrt.c
- lib/libc/math/lib_sqrtf.c
- lib/libc/math/lib_sqrtl.c
1)Typo fixes.
2)Fix for sqrtf.
> Libc math: Refactoring

- apps/tools/update_config.sh
update_config.sh uses bash syntax
> Use #!bin/bash in update_config.sh

- apps/examples/ftpd/Kconfig
- apps/examples/ftpd/Kconfig_ENTRY
- apps/examples/ftpd/Make.defs
- apps/examples/ftpd/Makefile
- apps/examples/ftpd/ftpd.h
- apps/examples/ftpd/ftpd_main.c
- apps/examples/xmlrpc/Kconfig
- apps/examples/xmlrpc/Kconfig_ENTRY
- apps/examples/xmlrpc/Make.defs
- apps/examples/xmlrpc/Makefile
- apps/examples/xmlrpc/calls.c
- apps/examples/xmlrpc/xmlrpc_main.c
Added FTP server sample application
> Added FTP server sample application

- lib/libc/math/lib_tanh.c
- lib/libc/math/lib_tanhf.c
- lib/libc/math/lib_tanhl.c
libc/math: Fix implementation of tanh(),tanhf(),tanhl() API
> Fix wrong API implementations

- apps/tools/create_appspec.sh
1. execute it as bash intead of sh
2. check existance of Kconfig_ENTRY
> refactoring create_appspec.sh

- apps/examples/smtp_client/Kconfig
- apps/examples/smtp_client/Kconfig_ENTRY
- apps/examples/smtp_client/Make.defs
- apps/examples/smtp_client/Makefile
- apps/examples/smtp_client/smtp_client.c
- apps/netutils/tftpc/tftpc_get.c
- apps/system/utils/Makefile
- apps/system/utils/netcmd.c
- apps/system/utils/netcmd_tftpc.c
- apps/system/utils/netcmd_tftpc.h
Added TFTP client sample application
> Refactoring TFTP client

- apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
- framework/src/arastorage/aql_exec.c
- framework/src/arastorage/index_bplustree.c
- framework/src/arastorage/index_manager.c
- framework/src/arastorage/relation.c
- framework/src/arastorage/relation.h
- framework/src/arastorage/storage_interface.c
Cleanup function implemented to facilitate re-execution of arastorage utc. 
Remove re-implemented to support index removal.
> Changes in arastorage

- os/pm/pm_test.c
> pm/pm_test: fix 'unused variable'

- os/fs/driver/mtd/Kconfig
> fs/mtd/Kconfig: fixed MTD menuconfig suboptions visibility

- os/mm/mm_heap/mm_realloc.c
> mm/mm_realloc: fix 'unused variable'

- build/configs/artik053/.buildSpec.xml
- build/configs/artik053/.debugSpec.xml
- build/configs/artik053/.flashSpec.xml
- build/configs/qemu/.buildSpec.xml
- build/configs/qemu/.flashSpec.xml
- build/configs/sidk_s5jt200/.buildSpec.xml
- build/configs/sidk_s5jt200/.flashSpec.xml
1. add ${PROJECT_PATH} on path
2. remove "linux" on name
> add ${PROJECT_PATH} on path and remove "linux" on name for IDE meta files

- apps/examples/testcase/le_tc/kernel/tc_umm_heap.c
If the lageset chunck < alloc size, malloc failure is right behavior
> Fix tc_umm_heap_random_malloc to consider insufficient memory

- apps/examples/testcase/le_tc/kernel/tc_semaphore.c
- apps/examples/testcase/le_tc/kernel/tc_umm_heap.c
- framework/src/arastorage/index_bplustree.c
- lib/libc/math/libm.h
- os/drivers/bch/bch.h
- os/drivers/rtc.c
- os/drivers/wireless/scsc/misc/utils_misc.h
- os/drivers/wireless/scsc/wlan_80211_utils.h
- os/drivers/wireless/scsc/wpa_driver_copy.h
- os/fs/driver/block/driver.h
- os/kernel/pthread/pthread.h
on apps/examples/testcase, framework, lib, os/drivers, os/fs and os/kernel
> fix violations of coding rule

- apps/examples/testcase/le_tc/kernel/tc_libc_pthread.c
- apps/examples/testcase/le_tc/kernel/tc_pthread.c
> Fix Coding Rule Violation on pthread TC's

- apps/examples/ftpc/Kconfig
- apps/examples/ftpc/Kconfig_ENTRY
- apps/examples/ftpc/Make.defs
- apps/examples/ftpc/Makefile
- apps/examples/ftpc/ftpc.h
- apps/examples/ftpc/ftpc_cmds.c
- apps/examples/ftpc/ftpc_main.c
Added ftp client sample application
> Added ftp client sample application

- apps/system/utils/kdbg_date.c
> Fix coding rule violation

- apps/Directory.mk
- apps/Makefile
- os/Makefile.unix
The external and apps folder need to use the external folder path.
> Deliver the EXTDIR definition for external folder path on Makefile

- framework/include/dm/dm_connectivity.h
External API -> Internal API for DM_Connectivity
> External API -> Internal API for DM_Connectivity

- apps/examples/easysetup/easysetup_main.c
- apps/examples/iperf/iperf_main.c
- apps/netutils/dhcpc/dhcpc.c
- os/net/tls/easy_tls.c
* SVACE fix
1) WGID : 97957 
2) WGID : 97980 
3) WGID : 149437 
4) WGID : 150201 
5) WGID : 149787
> Svace Bug Fix

- apps/examples/artik_demo/Kconfig
- apps/examples/artik_demo/artik_demo.c
Signed-off-by: Sanjeev BA <iamsanjeev@gmail.com>
> Fix Artik Demo example.

- apps/examples/testcase/le_tc/ttrace/ReadMe.txt
- lib/libc/ttrace/lib_ttrace.c
create_packet_u function is changed to create_packet_uid
> Fix unchanged function name in lib_ttrace.c and update readme

- os/net/lwip/src/api/sockets.c
> Fix LWIP EOF issue when one side closed connection

- os/net/lwip/src/api/sockets.c
> Fix LWIP-socket invalid error mapping

- os/net/lwip/src/api/api_msg.c
- os/net/lwip/src/core/tcp.c
> Fix LWIP address reuse issue

- apps/tools/create_appspec.sh
- external/iotivity/README.md
> apps/tools: fix typo at create_appspec.sh

- os/include/pthread.h
- os/include/signal.h
- os/include/stdio.h
- os/include/stdlib.h
- os/include/tinyara/math.h
- os/include/tinyara/ttrace.h
- os/include/unistd.h
- pthread.h, signal.h, stdio.h, stdlib.h, unistd.h, tinara/math.h, tinyara/ttrace.h
> Modify since in doxygen for Tizen RT v1.1

- framework/include/mqtt/mqtt_api.h
Add 'since' at mqtt APIs for doxygen
> Add 'since' at mqtt APIs for doxygen

- apps/examples/testcase/le_tc/filesystem/fs_main.c
This patch adds TC's for API's namely:
freopen,remove,setbuf,setvbuf
> Code coverage(libc/stdio): add test cases for stdio API's

- os/include/tinyara/logm.h
> Add doxygen for logm APIs in tinyara/logm.h

- framework/src/iotbus/iotapi_evt_handler.c
1. Add thread_detach
2. define constant value
3. remove unused variable
> Fix some bugs of iotapi_evt_handler

- apps/examples/testcase/le_tc/kernel/tc_libc_signal.c
Created timer should be deleted
> Delete timer at the end of tc_libc_signal_sigpause

- os/fs/driver/mtd/smart.c
- os/fs/smartfs/smartfs.h
- os/fs/smartfs/smartfs_smart.c
- os/fs/smartfs/smartfs_utils.c
Signed-off-by: Kavya <kavya.nunna@partner.samsung.com>
> Apply Fixed Code of Smartfs journaling

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/le_tc/kernel/tc_environ.c
- apps/examples/testcase/le_tc/kernel/tc_errno.c
- apps/examples/testcase/le_tc/kernel/tc_group.c
- apps/examples/testcase/le_tc/kernel/tc_libc_spawn.c
- apps/examples/testcase/le_tc/kernel/tc_libc_stdio.c
- apps/examples/testcase/le_tc/kernel/tc_libc_string.c
- apps/examples/testcase/le_tc/kernel/tc_libc_timer.c
- apps/examples/testcase/le_tc/kernel/tc_sched.c
- apps/examples/testcase/le_tc/kernel/tc_timer.c
- apps/examples/testcase/le_tc/kernel/tc_umm_heap.c
- apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
- apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_i2c.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_pwm.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_uart.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_i2c.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_pwm.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_uart.c
- apps/examples/testcase/tc_common.h
1. Remove tc macro, TC_ASSERT_NOT_NULL and change all using it to TC_ASSERT_NEQ
2. Change TC_ASSERT for checking NULL to TC_ASSERT_NEQ in fs tc
> Fix tc - Use TC_ASSERT_EQ/NEQ for checking whether a ptr is NULL or not

- external/Kconfig
1. Move a comment location to show title when iotivity is enabled.
2. Iotivity is an one component of external so that it makes menuconfig.
3. Remove a dependancy from all of iotivity configs and make a conditional
> iotivity: modify Kconfig

- build/configs/artik053/audio/Make.defs
- build/configs/artik053/extra/Make.defs
- build/configs/artik053/hello/Make.defs
- build/configs/artik053/iotivity/Make.defs
- build/configs/artik053/kernel_sample/Make.defs
- build/configs/artik053/minimal/Make.defs
- build/configs/artik053/nettest/Make.defs
- build/configs/artik053/tash/Make.defs
- build/configs/artik053/tc/Make.defs
- build/configs/artik053/typical/Make.defs
- build/configs/artik053/wifi_test/Make.defs
- build/configs/sidk_s5jt200/hello/Make.defs
- build/configs/sidk_s5jt200/hello_with_tash/Make.defs
- build/configs/sidk_s5jt200/kernel_sample/Make.defs
- build/configs/sidk_s5jt200/sidk_tash_aws/Make.defs
- build/configs/sidk_s5jt200/sidk_tash_wlan/Make.defs
- build/configs/sidk_s5jt200/tc/Make.defs
- external/aws/Makefile
- external/aws/certs/Make.defs
- external/aws/external_libs/jsmn/Make.defs
- external/aws/platform/TizenRT/common/Make.defs
- external/aws/platform/TizenRT/mbedtls/Make.defs
- external/aws/samples/TizenRT/shadow_sample/Make.defs
- external/aws/samples/TizenRT/shadow_sample_console_echo/Make.defs
- external/aws/samples/TizenRT/subscribe_publish_cpp_sample/Make.defs
- external/aws/samples/TizenRT/subscribe_publish_library_sample/Make.defs
- external/aws/samples/TizenRT/subscribe_publish_sample/Make.defs
To buile some C++ files, external/include should be included.
> fix compilation errors on aws

- external/include/mbedtls/config.h
- external/iotivity/build_iotivity.sh
- external/mbedtls/ssl_tls.c
- mbedtls has changed with folder structure and configs, it is needed to modify some configs
> Modify tls configs for iotivity

- apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c
remove TC_ASSERT API of IoTBus(N/A TC)
> remove TC_ASSERT API of IoTBus(N/A TC)

- apps/examples/easysetup/wifi_api.h
- apps/examples/ftpc/ftpc_main.c
- apps/examples/ftpd/ftpd.h
- apps/examples/libcoap_client/libcoap-client.c
- apps/examples/libcoap_server/libcoap-server.c
- apps/examples/lwm2m_test/commandline.c
- apps/examples/lwm2m_test/lwm2m_client_main.c
- apps/examples/lwm2m_test/lwm2m_server_main.c
- apps/examples/lwm2m_test/lwm2mclient.h
- apps/examples/lwm2m_test/object_location.c
- apps/examples/nettest/linux-nettest.c
- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
- apps/examples/tls_benchmark/tls_benchmark_main.c
- apps/examples/websocket/websocket_main.c
- apps/examples/wifi_test/wifi_test.c
- framework/src/wifi_manager/wifi_manager.c
- os/arch/arm/src/s5j/s5j_i2c.c
- os/fs/driver/mtd/smart.c
- open brace '{' following function declarations go on the next line
- please, no spaces at the start of a line
- code indent should use tabs where possible
- space required before the open parenthesis '('
> Fix coding rule

- os/Directories.mk
- os/KernelLibs.mk
- os/ProtectedLibs.mk
Add audio directory to KERNDEPDIR and library to TINYARALIBS becuase this is in kernel-space.
> Update Directories.mk, KernelLibs.mk and ProtectedLibs.mk for audio support

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/le_tc/kernel/tc_libc_misc.c
Adds tc for lib_dumpbuffer, sendfile and match api's.
NOTE: As lib_dumpbuffer return void, the success or failure result should be
checked manually by looking into tc output.
It has 2 cases,
1. dumps "53414d53554e472d54697a656e5254 SAMSUNG-TizneRT"
2. dumps "0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a ................................" (i.e, 256 "0a")
> TC: Add missing test cases of Libc misc

- framework/include/st_things/st_things.h
- framework/include/st_things/st_things_types.h
This is SmartThings Things (st_things) SDK header files.
> SmartThings_things SDK Header

- framework/src/wifi_manager/wifi_utils.c
Fixed an argument bug in WiFiRegisterLinkCallback
( linkdown_handler -> linkup_handler )
> Fixed an argument bug in WiFiRegisterLinkCallback

- lib/libc/net/lib_inetaddr.c
fixed bug of libc(lib_inetaddr)
- The inet_aton function is not fully implemented.
> fix bug of libc(lib_inetaddr)

- framework/src/wifi_manager/wifi_utils.c
1. fix wrong if statement which causes unreachability
2. fix if statement not to compare the entire array with 0
> Fix Svace issues in wifi_utils.c

- apps/examples/iperf/iperf_util.c
1. use snprintf instead of sprintf
> Fix Svace issue in iperf_util.c: use snprintf instead of sprintf

- apps/examples/dnsclient_test/dnsclient_main.c
1. fix missing null ternimation when strncpy()
> Fix Svace issue in dnsclient_main.c

- external/iotjs/build.config
- external/iotjs/src/platform/tizenrt/iotjs_main.c
-result print in debug mode
-include all module
> Modify IoT.js for kindly test

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_conn.c
- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_lwm2m.c
- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_main.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_i2c.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_pwm.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_sysio_main.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_uart.c
- apps/examples/tls_benchmark/tls_benchmark_main.c
- framework/include/st_things/st_things.h
- lib/libc/net/lib_inetaddr.c
- please, no spaces at the start of a line
- code indent should use tabs where possible
- space prohibited before that close parenthesis ')'
- space required after that ';'
> Fix coding rule error

- os/include/tinyara/streams.h
Add doxygen for stream APIs in include/tinyara/streams.h
Additionally, there are testcases for these functions in fs tc except internal functions
> Add doxygen for stream API in include/tinyara/streams.h

- apps/examples/testcase/ta_tc/device_management/utc/Kconfig
- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_conn.c
- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_lwm2m.c
- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_main.c
1. Connect WiFi at startup, 
2. Provide valid tx power for set TX power API
> Fix unit testcases for DM

- framework/src/iotbus/iotbus_gpio.c
- framework/src/iotbus/iotbus_pwm.c
pwm_get_duty_cyle : return pecentage value
gpio_set_direction : ioctl when IOTBUS_GPIO_DIRECTION_NONE
> Add missed logic of iotbus

- external/iotjs/build.target
to remove build warnning, fix build config
> Fix iot.js build config

- build/configs/artik053/README.md
- build/configs/artik053/artik053_download.sh
- build/configs/artik053/tools/openocd/partition_map.cfg
- tools/fs/README_ROMFS.md
- Update README and partition_map.cfg to guide about ROMFS and its partition
- Update artik053 download file to remove the temporary cfg file after flashing is done
related commit id : fa2cd4cc75ce3ef66212dfe4b615b0e4250135
> Update download file and README for ROMFS (related commit :  fa2cd4c )

- os/net/socket/recvmsg.c
Remove unnecessary log output
- net/socket/recvmsg
> Remove unnecessary log output

- os/drivers/gpio/gpio.c
gpio.c is synchronized with ARTIK053 repo.
> fix the issue that didn't receive event from gpio pin.

- build/configs/artik053/artik053_download.sh
1. Split romfs stubs from main
2. Support low-case character for ALL option
3. Remove temporarily file, romfs_flashing.cfg when execution is failed
> artik053: cleanup download script

- framework/include/tinyalsa/tinyalsa.h
Added doxygen script for audio framework
> Added doxygen script for audio framework

- os/fs/smartfs/Kconfig
- os/fs/smartfs/smartfs_utils.c
Sometimes eletronic power grow up after power off, in this case
FS treats writing logging finished properly.
> Apply verification code for transaction logging.

- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
- framework/include/wifi_manager/wifi_manager.h
- framework/src/wifi_manager/wifi_manager.c
1. relocate w_mutex to protect g_manager_info and to prevent wifi_utils apis from being called simultaneously
2. add mac_addr in wifi_manager_get_info() api
> Adjust the critical sections of wifi_manager

- os/arch/arm/src/tiva/Make.defs
This reverts commit 16d1bd0fbe1f16c8745eafc48c21cd6c9152863f.
> Revert "Remove setjmp.S in tiva/Make.defs"

- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_conn.c
- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_lwm2m.c
- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_main.c
@pillip8282 Could you please review and merge if found alright? Thank you.
> fixed build errors (conn linkUpEvent callback signature) and run-time (improper argument for set_tx_power) errors for DM itc

- framework/include/iotbus/iotbus_pwm.h
- framework/src/iotbus/iotbus_pwm.c
- os/include/tinyara/pwm.h
> Refactor iotbus PWM

- os/drivers/wireless/scsc/max_buf.c
- os/drivers/wireless/scsc/max_buf.h
- os/drivers/wireless/scsc/misc/mifintrbit.c
- os/drivers/wireless/scsc/misc/utils_misc.h
- os/drivers/wireless/scsc/t20_ops.c
Removed unused max_buf APIs
Change-Id: If8f492aa7fa672a075ae4aa212f8df366365874d
Signed-off-by: Debasish Das <d.das@samsung.com>
Conflicts:
os/drivers/wireless/scsc/misc/utils_misc.h
> [DRIVER] max_buf code cleanup

- os/include/net/lwip/debug.h
- os/include/net/lwip/lwipopts.h
- os/net/lwip/configs/debug/Kconfig
Add on off options for a network stack in menuconfig.
> net:lwip Add on/off options for assert and error at Kconfig in lwIP

- os/drivers/audio/alc5658.c
From returning a pointer to returning index. Because of the structure size issue.
> Modify sample rate entry function usage

- .travis.yml
- Add qemu/tc_64k config for Travis CI
- Travis will check build status include qemu/tc_64k
> Add build_config in Travis CI

- framework/src/tinyalsa/tinyalsa.c
add nuttx's license into tinyalsa.c
> Add nuttx license in tinyalsa.c

- apps/examples/st_things/Kconfig
- apps/examples/st_things/Make.defs
- apps/examples/st_things/Makefile
- apps/examples/st_things/README.md
- apps/examples/st_things/contents/sampleDevice.json
- apps/examples/st_things/sample_light_things.c
- apps/examples/st_things/sample_light_user.c
- apps/examples/st_things/st_things_sample.h
- apps/examples/st_things/st_things_sample_main.c
Example files for st_things.
This is an example sample for SmartThings Things SDK.
> Add st_things example

- apps/examples/st_things/sample_light_things.c
For using iotbus, iotapi_initialize is necessary.
> Fix the st_things example bug

- framework/include/st_things/st_things.h
- framework/src/st_things/things_stack/src/common/easy-setup/resource_handler.c
When coping the ssid, there is an error. That is fixed.
> Fix the st_things framework bug

- os/include/fixedmath.h
Remove @cond~@endcond comment and add @since comment for doxygen
> Fix doxygen comment in include/fixedmath.h

- framework/src/st_things/things_stack/src/common/cloud/cloud_manager.c
- framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
- framework/src/st_things/things_stack/src/common/utils/things_hashmap.c
- framework/src/st_things/things_stack/src/stack/things_stack.c
-  Add null check statement after allocating memory
- Delete unreachable statement
> Fix svace error in st_things

- external/iotjs/src/modules/iotjs_module_dns.c
- external/iotjs/src/modules/iotjs_module_tcp.c
Fix memory leak reported by SVACE.
> Fix memory leak on iotjs_module dns and iotjs_module tcp

- framework/src/st_things/st_things_logger.c
- framework/src/st_things/things_stack/src/common/cloud/cloud_manager.c
- framework/src/st_things/things_stack/src/common/easy-setup/easysetup.c
- framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
- framework/src/st_things/things_stack/src/common/framework/things_resource.c
- framework/src/st_things/things_stack/src/common/utils/things_network.c
Fix static analysis defects on ST Things
Fix the dereferenced pointers and check null termination when using strncat and strncpy.
> Fix the svace error in /framework/st_things folder 

- external/iotjs/src/modules/iotjs_module_adc.c
- external/iotjs/src/platform/tizenrt/iotjs_module_gpio-tizenrt.c
> IoT.js: Fix static analysis defects

- framework/src/wifi_manager/wifi_manager.c
- Quick Fix for hanging during wifi mode change
- remove mutex lock/unlock to prevent lock up
> Remove the mutex in wifi_linkdown_event_func

- os/include/dirent.h
- os/include/errno.h
- os/include/fcntl.h
- os/include/inttypes.h
- os/include/libgen.h
- os/include/mqueue.h
- os/include/poll.h
- os/include/pthread.h
- os/include/sched.h
- os/include/semaphore.h
- os/include/signal.h
- os/include/spawn.h
- os/include/stdio.h
- os/include/stdlib.h
- os/include/string.h
- os/include/sys/ioctl.h
- os/include/sys/mount.h
- os/include/sys/select.h
- os/include/sys/stat.h
- os/include/sys/wait.h
- os/include/syslog.h
- os/include/termios.h
- os/include/time.h
- os/include/tinyara/clock.h
- os/include/unistd.h
1. replace POSIX APIs -> POSIX API
2. remove unnecessary square bracket
> Modify doxygen comment for POSIX API and SYSTEM CALL API

- .travis.yml
1. Add st_things build configuration
2. Install cmake and scons
> travis: add new build config and install new tools in docker

- apps/examples/testcase/le_tc/network/Kconfig
- apps/examples/testcase/le_tc/network/Make.defs
- apps/examples/testcase/le_tc/network/network_tc_main.c
- apps/examples/testcase/le_tc/network/tc_net_dup.c
Add dup testcases for socket desciptors.
It test unit test case at os/net/socket/net_dupsd* files
> net:tc add dup() testcase

- os/include/sys/ioctl.h
- os/include/sys/time.h
- os/include/tinyara/math.h
replace POSIX APIs -> POSIX API
> Modify doxygen comment for POSIX API in include/sys and include/tinyara

- .travis.yml
- Add artik053/iotjs build config in Travis CI.
- Remove duplicated test configs in Travis CI.
> travis: Adjust build configs in Travis CI

- framework/include/arastorage/arastorage.h
- Fix wrong comments of each APIs
- Add information about header file to @details
> Update doxygen in arastorage.h

- apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
1. remove registering of TASH comand to run it automatically
2. add "static" for local functions
3. alignment of definitions
> modify arastorage testcase

- apps/examples/testcase/le_tc/kernel/tc_environ.c
> testcase/environ : check null case when getenv()

- external/webserver/http_string_util.c
- Add the code to check that the resulting string is null-terminated.
- Add the code for url length to respect the buffer sizes.
> Fix stack buffer overflow in webserver

- apps/examples/testcase/Kconfig
- apps/examples/testcase/Makefile
- apps/examples/testcase/ta_tc/wifi_manager/itc/Kconfig
- apps/examples/testcase/ta_tc/wifi_manager/itc/Make.defs
- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
- apps/examples/testcase/tc_main.c
@ apps/examples/testcase/ta_tc/wifi_manager/itc , Add ITCs for wifi_manager
> Add ITCs for Wifi_manager Module

- framework/src/st_things/things_stack/src/common/framework/inc/things_data_manager.h
- framework/src/st_things/things_stack/src/common/framework/inc/things_server_builder.h
- framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
- framework/src/st_things/things_stack/src/common/framework/things_server_builder.c
- framework/src/st_things/things_stack/src/common/inc/things_def.h
1. Get the manufacturerName from JSON
2. Set the manufacturerName from User define.
3. Remove unnecessary define
> st_things : Get the manufacturerName from JSON

- apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c
- framework/include/iotbus/iotbus_gpio.h
- framework/src/iotbus/iotbus_gpio.c
- os/include/tinyara/gpio.h
removed unsupported gpio output mode
artik053 board is not support below 2 mode.
IOTBUS_GPIO_DRIVE_NONE
IOTBUS_GPIO_DRIVE_PUSHPULL
> removed unsupported gpio output mode

- apps/examples/st_things/contents/sampleDevice.json
- apps/examples/st_things/sample_light_things.c
- apps/examples/st_things/sample_light_user.c
- Add 2 dimmer resources
- Add handlers for additional resources
> st_things: update st_things sample app

- apps/examples/testcase/Kconfig
- apps/examples/testcase/Makefile
- apps/examples/testcase/ta_tc/mqtt/itc/Kconfig
- apps/examples/testcase/ta_tc/mqtt/itc/Make.defs
- apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c
- apps/examples/testcase/tc_main.c
@ apps/examples/testcase/ta_tc/mqtt/itc , Add ITCs for mqtt module
> apps/examples/testcase/ta_tc/mqtt/itc : Add ITCs for MQTT Module

- apps/examples/st_things/sample_light_things.c
- apps/examples/st_things/sample_light_user.c
> st_things: apply tizenrt coding rule

- external/mdns/mdns.c
1) fix overflow when mdns is parsing the packet
2) checking cycle reference when it is parsing the packet
https://www.kb.cert.org/vuls/id/23495
3) adding a buffer overflow check when it is converting a name label
> protocol:mdns fix vulnerability at mdns

- framework/include/iotbus/iotbus_gpio.h
- framework/include/iotbus/iotbus_i2c.h
- framework/include/iotbus/iotbus_pwm.h
- framework/include/iotbus/iotbus_spi.h
- framework/include/iotbus/iotbus_uart.h
You can see which path should be included to use iotbus APIs.
> Add header file info in iotbus API's doxygen comment

- external/wakaama/core/er-coap-13/er-coap-13.c
Two cases of heap buffer overflows are considered:
1. When packet length is less than the coap header length of 4 bytes
2. when the option byte lengths have values far greater than what the packet buffer capacity. In this case, especially when merging contiguous location query coap options, buffer overflow tends to occur. 
3. Functions modified: coap_parse_message, and coap_merge_multi_option.
> Fix er-coap parsing in wakaama to handle heap buffer overflows

- external/include/json/cJSON.h
- external/json/cJSON.c
It will fix the below vulnerability issues existed at old version
https://www.talosintelligence.com/reports/TALOS-2016-0164/
> external:cjson update cJSON to the version 1.5.7 released Jun 29 2017

- apps/examples/st_things/sample_light_user.c
- add the usage how to deliver user data to sever
> examples/st_things: add user data in response msg

- external/webclient/webclient.c
- external/webserver/http_client.c
> Revert "Add an error handling code and an initialization function in webserver&client"

- framework/src/arastorage/aql_lexer.c
- framework/src/arastorage/aql_parser.c
- framework/src/arastorage/lvm.c
- framework/src/arastorage/lvm.h
1. add checking the length of input data before allocating it to buffer with fixed size
2. change return type of some functions in lvm and related somethings to check result of them.
> arastorage : add change return type of some functions and missing checking error case

- external/webclient/webclient.c
- external/webserver/http_client.c
- Add error handling codes in webserver and webclient if http_parse_massage function receives an error return.
> Add error handling functions in webserver&client

- apps/examples/iotivity_simpleserver/mkfsdata.pl
- apps/shell/tash_init.c
- external/iotjs/src/js/buffer.js
- external/iotjs/src/js/dgram.js
- framework/src/wifi_manager/wifi_net.c
- os/fs/driver/mtd/ftl.c
- os/fs/procfs/fs_procfscm.c
- os/fs/procfs/fs_procfsversion.c
- os/net/lwip/COPYING
- os/pm/pm_procfs.c
1. add missing our copyright and license
2. add missing original copyright and license to files got from external open source.
> license : add missing copyright and license text

- framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
- check the return value of cJSON whether it is null or not
- apply tizenrt coding rule.
>  framework/st_things: apply coding style and check null value

- os/include/arpa/inet.h
- os/include/net/lwip/netif.h
- os/include/netdb.h
- os/include/netinet/ether.h
- os/include/sys/socket.h
You can see which path should be included to use network libs APIs.
> doxygen : Add header file info for network libs APIs

- framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
- artik053 supports 32 bytes for ssid.
- limit the length of ssid.
- apply tizenrt coding rule
> framework/st_things: fix ssid format

- README.md
- build/configs/artik053/README.md
1. QEMU is supported so that we should add it there.
2. Remove wrong content and an unncessary space
> README: add a new board and modify content

- framework/include/wifi_manager/wifi_manager.h
Add details info for wifi_manager
* @details @b #include <wifi_manager/wifi_manager.h>
> doxygen : Add header file info for wifi_manager

- apps/include/shell/tash.h
clean up on tash.h for doxygen
> Refactor on TASH

- apps/tools/update_config.sh
If user enables a new app and calls update_config.sh,
updated_config.sh will concatenate new app config with .config
> Fix update_config.sh to consider the new app scenario

- build/configs/artik053/.flashSpec.xml
- build/configs/qemu/.flashSpec.xml
- build/configs/sidk_s5jt200/.flashSpec.xml
Add below description about flash options
ALL : Download all binaries and images
ERASE_USERFS : Erase user file system
> Add desc about flash options in flashSpec.xml

- build/configs/artik053/README.md
- build/configs/artik053/audio/README.md
- build/configs/artik053/extra/README.md
- build/configs/artik053/hello/README.md
- build/configs/artik053/iotivity/README.md
- build/configs/artik053/iotjs/README.md
- build/configs/artik053/kernel_sample/README.md
- build/configs/artik053/minimal/README.md
- build/configs/artik053/nettest/README.md
- build/configs/artik053/st_things/README.md
- build/configs/artik053/tash/README.md
- build/configs/artik053/tc/README.md
- build/configs/artik053/typical/README.md
- build/configs/artik053/wifi_test/README.md
Add missed configurations and add descriptions which features are enabled.
> artik053/README.md : Add Configuration Sets and its descriptions

- os/drivers/wireless/scsc/ba.c
- os/drivers/wireless/scsc/fapi.h
- os/drivers/wireless/scsc/fw_test.c
- os/drivers/wireless/scsc/hip4.c
- os/drivers/wireless/scsc/max_buf.c
- os/drivers/wireless/scsc/max_buf.h
- os/drivers/wireless/scsc/mgt.c
- os/drivers/wireless/scsc/mgt.h
- os/drivers/wireless/scsc/misc/mx_mmap.c
- os/drivers/wireless/scsc/mlme.c
- os/drivers/wireless/scsc/netif.c
- os/drivers/wireless/scsc/rx.c
- os/drivers/wireless/scsc/sap_ma.c
- os/drivers/wireless/scsc/sap_mlme.c
- os/drivers/wireless/scsc/tx.c
- os/drivers/wireless/scsc/udi.c
More cleanup for max_buf
Signed-off-by: Debasish Das <d.das@samsung.com>
> max_buf more cleanups

- docs/HowToAddStaticLibrary.md
- docs/Porting_Guide.md
When we want to include static (built) library, there are two methods.
This document shows them.
> Docs: add how to add static library

- docs/HowToUseWPASupplicant.md
- docs/Porting_Guide.md
Add documentation on how to use wpa_supplicant with a new WiFi driver.
> Add porting guide for WiFi

- apps/examples/nettest/nettest.c
Add a broacast sample to the nettest example
> example/nettest: Add broadcast sending example

- apps/examples/wifi_manager_sample/Kconfig
- apps/examples/wifi_manager_sample/Kconfig_ENTRY
- apps/examples/wifi_manager_sample/Make.defs
- apps/examples/wifi_manager_sample/Makefile
- apps/examples/wifi_manager_sample/README.txt
- apps/examples/wifi_manager_sample/wm_test.c
Wi-Fi control program in tash using wifi_manager APIs
> example/wifi_manager: Add wifi manager sample program

- apps/examples/dnsclient_test/Kconfig
- apps/examples/wifi_manager_sample/Kconfig
- apps/tools/create_appspec.sh
create_appspec.sh will search USER_ENTRYPOINT and find the main func
Add missed config USER_ENTRYPOINT at some app Kconfig
> Modify create_appspec.sh to read USER_ENTRYPOINT

- docs/Porting_Guide.md
Addition of Policy and Caution to Porting Guide
> Addition of Policy and Caution to Porting Guide

- apps/examples/fs_helper/write_remove_test.c
Fix for File Pointer Resource Leak in Application write_remove_test
> Fix for File Pointer Resource Leak in Application write_remove_test

- README.md
- build/configs/qemu/README.md
TizenRT/README.md : QEMU is not board
TizenRT/build/configs/qemu/README.md : Add more description about information
> Modify README.md about QEMU

- docs/HowToUseMultiHeap.md
When we want to use multi-heap region, we should modify two sections.
This document shows them.
> Docs:add how to use multi-heap region

- os/audio/pcm_decode.c
> Fix build error in audio/pcm_decode.c

- apps/HowtoAddNewApp.md
- apps/README.md
1. tidy up README of apps
2. add new README to describe how to add new app
> Apps readme

- docs/HowToUseSmartFS.md
- docs/Porting_Guide.md
This patch adds the smartfs filesystem usage guide on
new board.
> docs : update filesystem usage guide

- tools/ttrace_parser/scripts/parse_dump.c
fixes below leaks:
tools/ttrace_parser/scripts/parse_dump.c:174]: (error) Memory leak: buffer
tools/ttrace_parser/scripts/parse_dump.c:201]: (error) Resource leak: file
> (tools): fix memory/resource leaks

- apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_sysio_main.c
remove white space of tc according to coding rules.
> remove white space of tc

- apps/examples/testcase/ta_tc/systemio/itc/itc_i2c.c
apps/examples/testcase/ta_tc/systemio/itc :
filename : itc_i2c.c
add new scenario testcase for itc_i2c: 
itc_iotbus_i2c_set_frequency_address_p()
itc_iotbus_i2c_write_read_all_freq_p()
itc_iotbus_i2c_init_n()
itc_iotbus_i2c_stop_n()
itc_iotbus_i2c_set_frequency_n()
itc_iotbus_i2c_set_address_n()
itc_iotbus_i2c_set_address_after_stop_n()
> testcase/systemio/itc : enhance itc_iotbus_i2c_write_read_p

- apps/examples/wifi_manager_sample/wm_test.c
parsing parameters to test an auto mode was wrong.
the number of parameters was not match.
> apps/wifi_manager_sample: fix the bug in the auto test

- tools/doxygen/libs_env/doxygen_libs_env.txt
- tools/doxygen/libs_env/mainpage.dox
- tools/doxygen/public/doxygen_public.txt
- tools/doxygen/public/mainpage.dox
change some config file changes and directory structure to put the file to display the main page of document in doxygen directory.
> tools/doxygen: add document mainpage file

- apps/examples/testcase/ta_tc/systemio/itc/itc_pwm.c
File : apps/examples/testcase/ta_tc/systemio/itc/itc_pwm.c
Description : add new scenarios testcase for PWM
Scenarios testcase name : 
itc_pwm_set_get_different_duty_cycle_p
itc_pwm_set_get_different_period_p
itc_pwm_open_n
itc_pwm_close_n
itc_pwm_set_duty_cycle_n
itc_pwm_set_duty_cycle_after_close_n
itc_pwm_get_duty_cycle_n
itc_pwm_get_duty_cycle_after_close_n
itc_pwm_set_period_n
itc_pwm_set_period_after_close_n
itc_pwm_get_period_n
itc_pwm_get_period_after_close_n
itc_pwm_set_enabled_is_enabled_n
> apps/testcase/systemio: add new pwm scenarios TC

- build/configs/artik053/.flashSpec.xml
- build/configs/artik053/artik053_download.sh
Add new option, ERASE_ALL, on download script.
"make download ERASE_ALL" will erase all of partitions.
> configs/artik053: Support erasing all of partitions.

- framework/include/st_things/st_things_types.h
1. Add include path for each apis
if not, we cannot know which header we should include for using that api
2. delete spaces in indentation.
>  framework/st_things: Add include path

- os/include/tinyara/mm/mm.h
- os/mm/mm_heap/mm_heapinfo.c
- os/mm/mm_heap/mm_malloc.c
1. modified size value cannot be negative.
2. size_t type value can be printed with %u.
> mm : Modify memory size type to size_t and modify printed msg for size to %u

- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
TC's for pcm_drain and pcm_drop are being added in audio utc.
> testcase/audio/utc: Adding tc's for new APIs

- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
Reverts Samsung/TizenRT#972
We need to wait for fixing bug in i2s layer.
> Revert "testcase/audio/utc: Adding tc's for new APIs"

- apps/examples/st_things/contents/sampleDevice.json
- apps/examples/st_things/sample_light_things.c
- framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
1. framework/st_things: Json replace manufacturerid with manufacturerName
We are going to change sampleDevice.json.
So change the source code that gets the content from the json that changes.
The source code path to change is framework / src / st_things / things_stack / src / common / framework / things_data_manager.c.
2. framework/st_things: fix memory overload
In the second commit, there is over-allocation of memory. Modify this.
3. framework/st_things: MNID, SID Length-Limited Bug Fix
manufacture_name (MNID: 4 bytes) and setup_id (SID: 3 bytes) must be fixed sizes. If not the specified byte size, add logic to stop the operation.
4. apps/examples: Modify ST_Things Json File
Apply changes to Json file
> framework/st_things: Json modify and Fix memory leaks. 

- external/iotjs/deps/libtuv/cmake/option/option_arm-tizenrt.cmake
Remove unnessary libtuv library(os/lib) copy
> Remove unnecessary library (os/lib) copy

- README.md
The link to wiki provides what TizenRT is and How to use it.
> README: Make a link to wiki of TizenRT github

- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_conn.c
apps/testcase/dm/itc :
filename : itc_dm_conn.c
add new scenario testcase for dm connection itc module: 
itc_dm_conn_get_address_n
itc_dm_conn_get_channel_n
itc_dm_conn_get_interface_n
itc_dm_conn_get_rssi_n
itc_dm_conn_get_adress_channel_after_set_tx_power_p
itc_dm_conn_get_interface_rssi_after_set_tx_power_p
itc_dm_conn_set_tx_power_n
itc_dm_conn_get_tx_power_n
itc_dm_conn_re_register_linkup_p
itc_dm_conn_get_address_channel_after_register_linkup_p
itc_dm_conn_get_interface_rssi_after_register_linkup_p
itc_dm_conn_setget_tx_power_after_register_linkup_p
itc_dm_conn_register_linkup_n
itc_dm_conn_unregister_linkup_n
itc_dm_conn_re_register_linkdown_p
itc_dm_conn_get_address_channel_after_register_linkdown_p
itc_dm_conn_get_interface_rssi_after_register_linkdown_p …
> testcase/dm/itc : scenario for DM connection ITC:

- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
apps/examples/testcase/ta_tc/wifi_manager/itc :
add new scenario testcases for wifi manager module
> apps/testcase/wifi_manager : add new scenario testcase

- docs/HowToUseRamdump.md
- os/arch/Kconfig.board
- os/arch/arm/src/artik05x/src/Makefile
- os/arch/arm/src/artik05x/src/artik053_crashdump.c
- os/arch/arm/src/s5j/s5j_serial.c
- os/tools/mkconfig.c
- tools/ramdump/.gitignore
This patch adds the ramdump serial upload support for artik053 board.
Please follow docs/HowToUseRamdump.md
> artik053 : ramdump upload via serial

- docs/HowToUseIotivity.md
To use IoTivity feature, there are IoTivity information and build guide.
> docs: Add how to use iotivity

- apps/examples/testcase/tc_common.h
file path : apps/examples/testcase/
file name : tc_common.h
> testcase/tc_common.h: Modify Test Log Format

- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
> testcase/ta_tc/audio/utc : Modify Test Log Format

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
- apps/examples/testcase/le_tc/network/network_tc_main.c
- apps/examples/testcase/le_tc/ttrace/ttrace_tc_main.c
- apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
- apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c
- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_main.c
- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_main.c
- apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c
- apps/examples/testcase/ta_tc/mqtt/utc/utc_mqtt_main.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_sysio_main.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_sysio_main.c
- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
1. Modify locations of checking semaphore
2. Modify sentense of start and end testcase
> apps/testcase: refactor

- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
File Path: apps/examples/testcase/ta_tc/wifi_manager/itc
File name: itc_wifi_manager_main.c
modify ITC for revised wifi-manager for below reasons:
1. sta_connected callback has an argument for wifi_manager_result_e
2. no need to set STA after init()
3. check for correct return types
> apps/testcase/wifimanager : modify ITC for revised wifi-manager

- framework/include/st_things/st_things.h
- framework/include/st_things/st_things_types.h
- framework/src/st_things/st_things.c
- framework/src/st_things/st_things_logger.c
- framework/src/st_things/st_things_logger.h
- framework/src/st_things/st_things_representation.c
- framework/src/st_things/st_things_representation.h
- framework/src/st_things/st_things_request_handler.c
- framework/src/st_things/st_things_request_handler_collection.c
- framework/src/st_things/st_things_request_handler_collection.h
Modification of coding rule violation
> framework/st_things: fix coding rule

- apps/examples/testcase/ta_tc/systemio/utc/utc_gpio.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_i2c.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_pwm.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_uart.c
Naming rule is {TC Category}_{Module}_{Function Name}_{Positive/Negative}_{Additional Information}()
so that I add module name as systemio.
> testcase/systemio/utc: Modify name of functions

- framework/src/st_things/things_stack/src/stack/things_stack.c
- modify the callback to notify success/fail results according to the user callback changes in wifi_manager.
- related conmmit: e21b7aace626e32f1cc9743618fbdd608a7b225e
> framework/st_things: modify the sta_connected callback to show results

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
- apps/examples/testcase/le_tc/network/network_tc_main.c
- apps/examples/testcase/le_tc/ttrace/ttrace_tc_main.c
- apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
- apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c
- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
- apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c
- apps/examples/testcase/ta_tc/mqtt/utc/utc_mqtt_main.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_sysio_main.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_sysio_main.c
- apps/examples/testcase/tc_main.c
If CONFIG_TASH is enabled, tc_main installs tc commands.
Else tc_main make task and run tc.
> Make all tc execute via tash command

- framework/include/tinyalsa/tinyalsa.h
- framework/src/tinyalsa/tinyalsa.c
Remove commented code and unused code, enums, structs, flags, etc..
> TinyAlsa : Code clean up

- docs/HowToUsePeripheral.md
- docs/Porting_Guide.md
This contains what should do to use uart. Others will be filled.
> docs: add "how to use peripheral.md" for uart

- external/iotivity/README.md
To clarity the building steps, modify IoTivity README.
> README: Modify IoTivity README

- os/Makefile.unix
- os/Makefile.win
TizenRT v1.1 was released at Oct. 27, 2017
> version : change to 1.1

- docs/HowToUseMPU.md
- docs/Porting_Guide.md
Adds guide to Initialize MPU and Setting up MPU regions
> docs: Add MPU Init and Region setup guide

- apps/examples/testcase/le_tc/kernel/tc_semaphore.c
This patch adds left over cases for API's:
kernel/semaphore:
sem_setprotocol()
sem_tickwait()
> Codecoverage: add corner cases for semaphore TC's 

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/le_tc/kernel/Kconfig
- apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
- apps/examples/testcase/le_tc/kernel/tc_internal.h
- apps/examples/testcase/le_tc/network/network_tc_main.c
- apps/examples/testcase/le_tc/network/tc_internal.h
- apps/examples/testcase/le_tc/ttrace/ttrace_tc_main.c
- apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
- apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
- apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c
- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
- apps/examples/testcase/ta_tc/device_management/itc/itc_dm_main.c
- apps/examples/testcase/ta_tc/device_management/utc/utc_dm_main.c
- apps/examples/testcase/ta_tc/device_management/utc/utc_internal.h
- apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c
- apps/examples/testcase/ta_tc/mqtt/utc/utc_mqtt_main.c
- apps/examples/testcase/ta_tc/systemio/itc/itc_sysio_main.c
- apps/examples/testcase/ta_tc/systemio/utc/utc_internal.h
- apps/examples/testcase/ta_tc/systemio/utc/utc_sysio_main.c
- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
- apps/examples/testcase/tc_common.h
- apps/examples/testcase/tc_main.c
When CONFIG_TASH is enabled, every tc will be executed by shell.
Every TC execution should be separated to protect global variables and
abnormal operation. New function, tc_handler takes care of it using semaphore.
> examples/testcase: refactor every tc main to check tc status

- apps/examples/i2schar/i2schar_receiver.c
- os/arch/arm/src/artik05x/src/artik055_i2schar.c
- os/arch/arm/src/s5j/s5j_dma.c
- os/arch/arm/src/s5j/s5j_i2s.c
- os/drivers/audio/i2schar.c
Some small changes in applications and environment, and big update if I2S driver.
> Updates for I2S driver

- apps/examples/testcase/le_tc/kernel/tc_timer.c
This patch adds missing corner cases for following API's:
timer_create()
timer_delete()
timer_settime()
timer_gettime()
timer_getoverrun()
> le_tc/timer: Add corner cases and missing API's in timer TC

- apps/shell/tash_main.c
- apps/system/readline/readline_common.c
- lib/libc/stdio/lib_avsprintf.c
- os/drivers/gpio/gpio.c
- os/drivers/i2c/i2c_uio.c
- os/fs/driver/mtd/mtd_config.c
- os/fs/procfs/fs_procfsproc.c
- os/fs/vfs/fs_fdopen.c
- os/pm/pm_procfs.c
1. Removes a part/line of codes where assigned values are never used.
2. Adds missed conditional check and config dependency
3. Remove Dead Initialization Codes.
> Refactor: Remove dead codes

- apps/examples/testcase/le_tc/kernel/tc_sched.c
This patch adds corner cases for following API's:
waitid()
waitpid()
sched_setparam()
sched_getparam()
sched_setpriority()
sched_setscheduler()
sched_rr_get_interval()
> le_tc/ched: Add corner cases for sched TC's

- os/fs/vfs/fs_poll.c
cherry-picked 027a446 from nuttx
poll: fix poll for regular files and block devices.  Open Group documentation tells that poll (and select) support regular files and that 'Regular files shall always poll TRUE for reading and writing'.
> fs/poll: support poll for regular files and block devices

- apps/examples/testcase/le_tc/filesystem/fs_main.c
If current tc is run with TASH simultanously, it can be affected by holding uart device.
> testcase/filesystem : change the scenario of poll tc about polling regular file instead of stdin, stdout

- docs/HowToUseRamdump.md
- tools/ramdump/gui_dumpParser.py
Using tkinter, this python script set arguments of dumpPaser
and redirect them to dumpParser.py
> Support GUI of dumpParser

- build/configs/artik05x/artik05x_download.sh
1. remove checking openocd installation
because artik05x is not working on original openocd
2. change a permission to 755
3. fix wrong information
> config/artik05x: change a permission and tidy up a bit

- build/configs/artik05x/artik05x_download.sh
1. remove checking openocd installation
because artik05x is not working on original openocd
2. change a permission to 755
3. fix typo
> config/artik05x: refactoring

- tools/ramdump/dumpParser.py
Refactor dumpParser.py for encapsulation
Use 'with' statement to make sure fd is closed after use
> Delete fd members of dumpParser object

- apps/include/system/sysdbgapp_init.h
- apps/system/init/init.c
- apps/system/sysdbg/Kconfig
- apps/system/sysdbg/Make.defs
- apps/system/sysdbg/Makefile
- apps/system/sysdbg/sysdbgapp_init.c
- lib/libc/semaphore/sem_init.c
- os/Kconfig.debug
- os/arch/arm/src/armv7-r/arm_blocktask.c
- os/arch/arm/src/armv7-r/arm_releasepending.c
- os/arch/arm/src/armv7-r/arm_reprioritizertr.c
- os/arch/arm/src/armv7-r/arm_sigdeliver.c
- os/arch/arm/src/armv7-r/arm_unblocktask.c
- os/arch/arm/src/common/up_exit.c
- os/include/tinyara/debug/sysdbg.h
- os/kernel/Makefile
- os/kernel/debug/Make.defs
- os/kernel/debug/sysdbg.c
- os/kernel/init/os_start.c
- os/kernel/irq/irq_dispatch.c
- os/kernel/semaphore/sem_destroy.c
- os/kernel/semaphore/sem_post.c
- os/kernel/semaphore/sem_recover.c
- os/kernel/semaphore/sem_trywait.c
- os/kernel/semaphore/sem_wait.c
- os/kernel/semaphore/sem_waitirq.c
This has 2 commits . kindly review
1.  os side changes for debug framework
2. application changes for using debug framework
> New debug framework

- apps/examples/nettest/nettest.c
add new example for showing how to receive broadcast data
> example/nettest: add receive broadcast example

- apps/examples/media_test/media_test_main.c
- apps/examples/media_test/server/server_example_linux.c
- framework/src/media/media_player.c
- framework/src/media/media_recorder.c
modify deadlock and error. modify server_linux.
> framework/src/media: modify media logic. 

- os/drivers/audio/alc5658.c
- os/drivers/audio/alc5658.h
Alc5658 driver don't register for underrun i2s error notification
> Alc5658 driver changes

- framework/src/st_things/things_stack/src/common/framework/things_data_manager.c
> framework: Fixed a error in file path.

- os/arch/arm/src/armv7-r/arm_assert.c
get_symbol() api does file system operations like open
seek, close etc. If there is a crash inside filesystem
it enters to abort mode and since get_symbol is used inside
abort_handler to print the symbol names infront of callstack,
It will call filesystem apis again. This would cause recursive
abort. This patch fixes this recursive abort.
> Avoid recursive abort by get_symbol in arm_assert.c

- apps/examples/testcase/le_tc/drivers/Kconfig
- apps/examples/testcase/le_tc/kernel/Kconfig
- os/drivers/Kconfig
- os/drivers/Makefile
- os/drivers/testcase/Kconfig
- os/drivers/testcase/Make.defs
- os/drivers/testcase/testcase_drv.c
- os/include/tinyara/fs/ioctl.h
- os/include/tinyara/testcase_drv.h
- os/kernel/init/os_start.c
This commit contains the initial changes for kernel test case (code coverage test) framework.
> Kernel testcase framework

- docs/HowToUsePeripheral.md
Add i2c porting instructions on pheripherals porting guide.
> Porting guide update for pehipherals

- docs/HowToPortTizenRTOnWiFiChipset.md
Edit WiFi porting guide to describe how to interface WiFi Manager to new chipset's supplicant software.
> Edit WiFi Porting Guide

- apps/examples/media_test/README.md
This document explains that how to build and use this example.
> examples/media: Add README.md for media test example

- build/configs/artik053/audio/Make.defs
- build/configs/artik053/extra/Make.defs
- build/configs/artik053/hello/Make.defs
- build/configs/artik053/iotivity/Make.defs
- build/configs/artik053/iotjs/Make.defs
- build/configs/artik053/kernel_sample/Make.defs
- build/configs/artik053/minimal/Make.defs
- build/configs/artik053/nettest/Make.defs
- build/configs/artik053/st_things/Make.defs
- build/configs/artik053/tc/Make.defs
- build/configs/artik053s/nettest/Make.defs
- build/configs/artik053s/st_things/Make.defs
- build/configs/artik055s/audio/Make.defs
- build/configs/artik055s/minimal/Make.defs
- build/configs/artik055s/nettest/Make.defs
- build/configs/artik055s/st_things/Make.defs
- build/configs/artik05x/artik05x_ota.sh
- os/Makefile.unix
functionality for attaching crc and signing to tinyara binary
> makefile: Add making ota img functionality for artik05x

- os/arch/arm/src/armv7-m/up_assert.c
- Adds 'up_showtasks' function in crash dump state
- 'up_showtasks' prints list of all tasks in the system
with PID and amount of stack used
> arch/src/armv7-m: Add function to show tasks info

- apps/examples/wifi_manager_sample/wm_test.c
- framework/include/wifi_manager/wifi_manager.h
- framework/src/wifi_manager/Kconfig
- framework/src/wifi_manager/Make.defs
- framework/src/wifi_manager/wifi_manager.c
- framework/src/wifi_manager/wifi_profile.c
- framework/src/wifi_manager/wifi_profile.h
Add wifi manager APIs to store the connected AP information in persistent storage
> framework/wifi_manager: add wifi manager configuration get/set features

- apps/examples/testcase/ta_tc/arastorage/itc/itc_arastorage_main.c
Remove below ITCs:
itc_arastorage_db_print_header_n_after_deinit
itc_arastorage_cursor_get_count_n_after_deinit
itc_arastorage_cursor_get_row_n_after_deinit
Signed-off-by: bipinkumar <bipin.k@samsung.com>
> Remove three ITC from itc_arastorage_main.c

- apps/examples/testcase/le_tc/network/tc_net_socket.c
fix svace issues of socket API testcases
> testcase/network: fix svace issue

- framework/src/st_things/things_stack/things_api.h
- framework/src/st_things/things_stack/things_def.h
- framework/src/st_things/things_stack/things_stack.c
- Apply versioning rules for ST_Things backwards compatibility
> framework/st_things : Apply version control rules

- apps/examples/testcase/le_tc/kernel/Kconfig
- apps/examples/testcase/le_tc/kernel/Make.defs
- apps/examples/testcase/le_tc/kernel/itc_environ.c
- apps/examples/testcase/le_tc/kernel/itc_libc_pthread.c
- apps/examples/testcase/le_tc/kernel/itc_libc_semaphore.c
- apps/examples/testcase/le_tc/kernel/itc_libc_spawn.c
- apps/examples/testcase/le_tc/kernel/itc_pthread.c
- apps/examples/testcase/le_tc/kernel/itc_sched.c
- apps/examples/testcase/le_tc/kernel/itc_semaphore.c
- apps/examples/testcase/le_tc/kernel/itc_timer.c
- apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
- apps/examples/testcase/le_tc/kernel/tc_internal.h
files:
itc_libc_pthread.c: add new tc for kernel libc pthread.
itc_libc_semaphore.c : add new tc for libc semaphore
itc_semaphore.c : add new tc for kernel semaphore
itc_sched.c : add new tc for kernel sched
itc_timer.c : add new tc for kernel timer
itc_environ.c : add new tc for kernel environ
itc_libc_spawn.c : add new tc for libc spawn
itc_pthread.c : add new tc for kernel pthread
>  le_tc/kernel : add new ITC for kernel

- framework/include/iotbus/iotbus_gpio.h
- framework/include/iotbus/iotbus_i2c.h
- framework/include/iotbus/iotbus_pwm.h
- framework/include/iotbus/iotbus_spi.h
- framework/include/iotbus/iotbus_uart.h
- framework/src/iotbus/iotbus_gpio.c
- framework/src/iotbus/iotbus_i2c.c
- framework/src/iotbus/iotbus_pwm.c
- framework/src/iotbus/iotbus_spi.c
- framework/src/iotbus/iotbus_uart.c
- make wrappers for each component, i2c, gpio, pwm, spi, and uart
- apply coding rule and clean the source codes
> framework/iotbus : make wrappers for each component and clean the source codes

- framework/src/st_things/Kconfig
- framework/src/st_things/things_stack/cloud/cloud_connector.c
- framework/src/st_things/things_stack/framework/Make.defs
- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.h
- framework/src/st_things/things_stack/framework/things_security_manager.c
- framework/src/st_things/things_stack/framework/things_security_manager.h
- framework/src/st_things/things_stack/framework/things_sss_manager.c
- framework/src/st_things/things_stack/framework/things_sss_manager.h
- framework/src/st_things/things_stack/things_stack.c
- enable artik h/w certificate & key
- apply TizenRT coding rule
> framework/st_things: Support Artik H/W Certificate & Key

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/le_tc/filesystem/tc_fs_procfs.c
- apps/examples/testcase/le_tc/filesystem/tc_internal.h
Adds tc for 
fs/dirent
fs/mount
fs/procfs
fs/smartfs
fs/driver/mtd
fs/vfs
fs/driver/block
> testcase/le_tc/filesystem : Add testcases for filesystem

- apps/examples/webclient/webclient_main.c
- external/webclient/webclient.c
fix bad request bug
add debug message
> external/webclient : fix bad request parameter

- os/arch/arm/src/armv7-m/up_schedulesigaction.c
- Fix logic that determines if there is a pending signal action before
scheduling the next signal action.
- Both the test and the scheduling action need to be atomic.
This patch is back ported from Nuttx
> ARMv7-M: Fix logic in up_sechedule_sigaction

- external/webserver/http_client.c
modifying the length value when to call callback function
> external/webclient : fix chunked data length

- apps/examples/webclient/webclient_main.c
- external/webserver/http_client.c
fix error in downloaded data
separate header and body data
> external/webclient : Header data and body data separation

- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
- framework/src/tinyalsa/tinyalsa.c
- os/include/tinyara/audio/audio.h
- Modified logic in mmap begin and commit api's
- Fixed assert and error checking procedures in audio UTC for mmap api's
- Fixed flag and structure variables in tinyalsa
> [Audio] Fix issues in Tinyalsa and AudioUTC for MMAP

- docs/HowToUsePeripheral.md
> Update HowToUsePeripheral document

- README.md
- build/configs/artik053/README.md
- build/configs/artik053s/README.md
- build/configs/artik055s/README.md
- build/configs/qemu/README.md
- build/configs/sidk_s5jt200/README.md
Some caution sentences are added.
1. Add recommandation to do TizenRT quick start first before setting board env
2. Add how to check configuation list
3. Add caution of exporting path
> Modify README of TizenRT and boards

- apps/system/utils/README.md
- docs/HowToDebug.md
Add a document to describe shell commands on apps/system/utils folder
and make a link it to HowToDebug.md file
> docs: add shell commands descriptions and make a link on HowToDebug.md

- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
- os/drivers/audio/alc5658.c
Prepare helps to handle overflow and underflow errors in audio
> Add prepare support in audio for alc5658 codec

- apps/system/utils/README.md
Update brief explanations and examples for each commands.
> system/utils: Update descriptions for shell commands in README.md

- framework/Makefile
frameworks .cxx files can be compiled
> Add CXXOBJS recipe in frameworks

- apps/system/utils/README.md
- apps/system/utils/fscmd.c
Add descriptions of cat, cd, df, ls, mkdir, mkrd, mksmartfs, rm, rmdir, pwd, mount, umount commands
> add commands list for file system functionalities on README

- apps/examples/iotivity_simpleserver/simpleServer.c
Change-Id: I292ae9c3f1fc846e76e860e3dc04637d8a0c0885
> iotivity: Add support for ARTIK055S to iotivity_simpleserver

- framework/src/st_things/things_stack/fota/fmwup_api.c
…tr type.
Modify int type to str type.
> framwork/st_things: apply string type on FIRMWARE_PROPERTY_UPDATE

- framework/src/st_things/things_stack/things_stack.c
- Delete stored wifi profile information
> framework/st_things : Delete wifi profile information on reset

- framework/src/st_things/things_stack/cloud/cloud_manager.c
- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- framework/src/st_things/things_stack/easy-setup/easysetup_manager.h
- framework/src/st_things/things_stack/utils/things_network.c
- framework/src/st_things/things_stack/utils/things_ping.c
- framework/src/st_things/things_stack/utils/things_ping.h
- remove pipe logic
- change typing error
> framework/st_things : logic cleanup

- os/kernel/task/task_create.c
- os/kernel/task/task_setup.c
- os/mm/mm_heap/mm_heapinfo.c
…lues.
In previous, stack information is presented with -2, meaningless value.
So Change to meaningful value like PID(S).
> kdbg/heapinfo : Show the stack information to which task/thread allocated

- README.md
- build/configs/artik053/README.md
- build/configs/artik053s/README.md
- build/configs/artik055s/README.md
- docs/TroubleShooting.md
1. Simplify the sequence of board-specific environment-setup and programming method.
2. Add new troubleshooting document.
3. Add sentences on top README to know what information is.
> README: tidy up existing docs and add new troubleshooting doc

- os/kernel/pthread/pthread_create.c
- os/mm/mm_heap/mm_heapinfo.c
And Add tcb checking logic which tcb is alive or not.
> kdbg/heapinfo : Add missing pid assignment logic for pthread_create

- docs/TroubleShooting.md
This commit shows how to resolve a problem on mconf usage.
> docs/TroubleShooting: add a solution of Kconfig-frontend issues

- framework/src/st_things/things_stack/cloud/cloud_manager.c
- framework/src/st_things/things_stack/easy-setup/resource_handler.c
- framework/src/st_things/things_stack/fota/fmwup_util_data.c
- framework/src/st_things/things_stack/framework/things_resource.c
- framework/src/st_things/things_stack/framework/things_security_manager.c
- framework/src/st_things/things_stack/framework/things_server_builder.c
- framework/src/st_things/things_stack/utils/things_hashmap.c
- framework/src/st_things/things_stack/utils/things_list.c
- Pair alignment (things_malloc / things_calloc / things_free)
> framework/st_things : Memory allocation and free modification

- apps/examples/testcase/ta_tc/audio/utc/utc_audio_main.c
- os/arch/arm/src/s5j/s5j_i2s.c
- os/drivers/audio/alc5658.c
- os/include/tinyara/audio/i2s.h
Below issues fixed:
Missing underrun handling code in some UTC's
Fix I2S stop / pause / resume API's which was causing failure in MMAP related audio UTC's
> [AUDIO] Fix audio UTC failure issues

- docs/HowToUseAudio.md
Add a new document HowToUseAudio.md on how to use audio.
> Add guide for audio usage.

- framework/src/st_things/things_stack/cloud/cloud_connector.c
- framework/src/st_things/things_stack/cloud/cloud_manager.c
- framework/src/st_things/things_stack/easy-setup/resource_handler.c
- framework/src/st_things/things_stack/fota/fmwup_util_data.c
- framework/src/st_things/things_stack/framework/things_security_manager.c
- framework/src/st_things/things_stack/memory/Make.defs
- framework/src/st_things/things_stack/memory/things_string.c
- framework/src/st_things/things_stack/memory/things_string.h
- framework/src/st_things/things_stack/utils/things_network.c
- framework/src/st_things/things_stack/utils/things_ping.c
- Change to things_strdup for debugging by st_things module
> framework/st_things : Change strdup to things_strdup

- framework/src/st_things/things_stack/framework/things_data_manager.c
Delete the logic and functions that contain user_def_dev_list.
> framework/st_things : remove unused code "user_def_dev_list".

- docs/HowToUseAudio.md
- docs/HowToUseTinyAlsa.md
Add HowTo document for TinyAlsa usage and refer to it from HowTo document for Audio
> [Audio] Add documentation for TinyAlsa

- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.h
- framework/src/st_things/things_stack/utils/things_hashmap.c
> Revert "framework/st_things : Improve Things Data Manager to reduce memory usage."

- framework/src/st_things/things_stack/cloud/cloud_manager.c
- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- framework/src/st_things/things_stack/framework/things_server_builder.c
- framework/src/st_things/things_stack/things_stack.c
- framework/src/st_things/things_stack/utils/things_ping.c
- framework/src/st_things/things_stack/utils/things_rtos_util.c
- framework/src/st_things/things_stack/utils/things_rtos_util.h
- framework/src/st_things/things_stack/utils/things_wait_handler.c
- add const
- change thread creation logic and thread names
> framework/st_things : change thread creation logic and thread names

- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.h
- framework/src/st_things/things_stack/utils/things_hashmap.c
We have decided the max length of path and ssid as 32.
Now, the those size cannot be over 32.
> framework/st_things : Change max length of path and ssid as 32.

- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.h
- framework/src/st_things/things_stack/utils/things_hashmap.c
Some logic has changed to use pointer instead of array when resource was created to reduce memory usage.
> framework/st_things : Improve Things Data Manager to reduce memory usage.

- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.h
- Remove unused variables
- Add "speckVersion", "dataModelVersion" JSON parsing logic
- Change the return logic due to JSON error
- Remove init_things_info_file function
> framework/st_things : st things data manager refactoring

- apps/examples/st_things/sample_light_things.c
- Logic processing based on the result of st_things_start()
> framework/st_things : Processing the result of st_things_start()

- framework/src/st_things/st_things_util.c
- chamge "malloc" to "things_malloc"
- chagne "free" to "things_free"
> framework/st_things : change "malloc" to "things_malloc"

- lib/libc/Kconfig
- lib/libc/stdio/lib_sscanf.c
Current sscanf did not support regular expression parsing which is required for libcurl.
> Merge CONFIG_LIBC_SCANSET from NuttX upstream code

- apps/examples/testcase/ta_tc/systemio/itc/itc_spi.c
- framework/include/iotbus/iotbus_spi.h
- framework/include/iotbus/iotbus_uart.h
- framework/src/iotbus/Kconfig
- framework/src/iotbus/iotbus_gpio.c
- framework/src/iotbus/iotbus_i2c.c
- framework/src/iotbus/iotbus_internal.h
- framework/src/iotbus/iotbus_pwm.c
- framework/src/iotbus/iotbus_spi.c
- framework/src/iotbus/iotbus_uart.c
1. add dependancies on iotbus configs
2. remove empty functions with disabled config
3. add new config, DEBUG_IOTBUS
> refactoring on Iotbus

- tools/ramdump/HowToUseRamdump.md
1. Add summary at top of doc
2. Split subsection into build and upload from upload
3. Change subsection titles to "how to" format
4. Fix typo
> tools/ramdump: modify README for summary and subsection

- docs/HowToDebug.md
- docs/HowToUseLoggingSystem.md
- os/logm/README.md
These files describe debugging and logging system.
- Debug messages
- How to use logging system
- How to use LogM
> readme: add readme about debugging and logging

- framework/src/st_things/things_stack/things_stack.c
- Change "wifi_manager_init()" to "things_initialize_stack()"
> framework/st_things : Change location of Wifi_init()

- framework/src/st_things/things_stack/cloud/cloud_manager.c
- framework/src/st_things/things_stack/easy-setup/easysetup.c
- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- framework/src/st_things/things_stack/easy-setup/es_common.h
- framework/src/st_things/things_stack/easy-setup/resource_handler.c
- framework/src/st_things/things_stack/easy-setup/resource_handler.h
- 3rd party does not need sub device
- Sub device changed to configuration
> framework/st_things : disable sub device publish

- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- remove unnecessary variables variable(is_set_device_property)
- change return value (int -> enum)
- set the device name from data_manager in esm_set_device_preperty
> framework/st_things : remove unnecessary variables & logic

- README.md
- os/arch/Kconfig.chip
1. make a dependacy RAM_DDR_XXX with DDR
2. modify syntax of help
3. move location of DDR
4. add "cy4390x" on supported board / emulator of README
> tidy up for cy4390x

- framework/src/st_things/things_stack/fota/fmwup_util_data.c
- framework/src/st_things/things_stack/framework/things_data_manager.c
1. Add header in fmwup_util_data.c
2. Fix syntax error in things_data_manager.c
> framework/st_things : Fix a build errors.

- apps/examples/testcase/le_tc/kernel/tc_pthread.c
1. apps/testcase/kernel: remove a testcase for pthread join info
2. apps/testcase/kernel: modify pthread key testcase
3. apps/testcase/kernel: refactoring on tc_pthread_pthread_setschedprio
> refactoring and modify tc_pthread

- os/net/Kconfig
Change the Ethernet MTU size when making menuconfig
> Enable Ethernet MTU size when making menuconfig

- os/drivers/audio/alc5658.c
- os/drivers/audio/alc5658.h
Add support to mute and unmute alc5658 codec for headphones ONLY
> Audio: Add mute support for alc5658 audio codec

- external/WICED/Kconfig
- os/arch/Kconfig.chip
1. external/WICED: modify Kconfig
2. os/arch: remove dependancy between DDR and ARCH_BOARD_CY4390X
> refactoring on Kconfig

- README.md
- docs/HowtoClean.md
- docs/HowtoInstallKconfigFrontend.md
1. docs: add a trouble shooting link on kconfig-frontend doc
2. docs: add how to clean built and configured files
> add Readme

- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- framework/src/st_things/things_stack/easy-setup/resource_handler.c
- framework/src/st_things/things_stack/easy-setup/resource_handler.h
- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/things_api.h
- framework/src/st_things/things_stack/things_stack.c
- framework/src/st_things/things_stack/things_types.h
- framework/src/st_things/things_stack/utils/things_network.c
- framework/src/st_things/things_stack/utils/things_network.h
- Refactoring of things_network
- Move wifi_manager related logic
- Remove unnecessary logic
> framework/st_things : Network related module merged into things_network

- framework/src/st_things/things_stack/cloud/cloud_connector.c
- framework/src/st_things/things_stack/cloud/cloud_connector.h
- framework/src/st_things/things_stack/cloud/cloud_manager.c
- framework/src/st_things/things_stack/cloud/cloud_manager.h
- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- framework/src/st_things/things_stack/framework/things_req_handler.c
- framework/src/st_things/things_stack/utils/things_network.c
- framework/src/st_things/things_stack/utils/things_ping.c
- framework/src/st_things/things_stack/utils/things_wait_handler.c
- framework/src/st_things/things_stack/utils/things_wait_handler.h
- Variables used inside st_things : add "things_" prefix for readability
> framework/st_things : add "things_" prefix on st_things internal APIs.

- docs/HowToDevelopThingsUsingSTThings.md
- rename "SmartThings Things" to "ST Things"
- remove sdk
> docs/st_things : update st things guide

- apps/system/utils/kdbg_heapinfo.c
- apps/system/utils: Fix build error in heapinfo
> Fix build error in heapinfo util

- .travis.yml
- Update arm-gcc version from 4.9 to 6.3
- Add artik053/grpc config to test grpc build
> Update arm-gcc version in Travis CI

- framework/src/st_things/things_stack/things_api.h
- framework/src/st_things/things_stack/things_stack.c
- remove unused variables and functions in things_api.h and things_stack
> framework/st_things : Remvoe unused functions / variables

- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
> testcase/wifi-manager: wifi_manager UTC bug fix

- apps/examples/testcase/le_tc/kernel/Kconfig
- apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
- apps/examples/testcase/le_tc/kernel/tc_libc_semaphore.c
1. testcase/kernel: fix a compilation error on semaphore 
2. testcase/kernel: remove unncessary semaphore dependancy
> refactoring on Kernel tc

- docs/HowToDevelopThingsUsingSTThings.md
- docs/HowToDevelopThingsWithTizenStudioForRT.md
- The Samsung Connect mobile app has been changed to SmartThings
> docs/st_things : update mobile app name.

- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
> testcase/wifi_manager: fix wifi_manager itc bug

- framework/src/media/FileOutputDataSource.cpp
add an exception handling in file reopen.
> media : add logic for reopen case

- apps/system/utils/Kconfig
- apps/system/utils/Makefile
- apps/system/utils/netcmd.c
- apps/system/utils/netcmd_ping.c
- Add new configs to control ping utility in build system
- Fix coding rule violations
- Fix divide by zero problem in ping utility output
> Refactor ping utility code

- .clang-format
This is TizenRT style custom clang-format file
User can format cpp files using .clang-format
USAGE : clang-format -style=file -i "filename"
> tools: Add .clang-format at TizenRT dir

- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/RecorderObserverWorker.cpp
- framework/src/media/RecorderWorker.cpp
1. fix wrong reference count for recorderworker
2. add missing mutex
3. add logic for exception case of dequeue
> media : bug fix for media recorder

- apps/examples/testcase/ta_tc/mqtt/utc/utc_mqtt_main.c
sometimes a callback from mqtt stack is called before utc waits it.
so instead of pthread_cond_signal, the utc for mqtt calls semaphore.
> testcase/mqtt: fix mqtt utc signal issue

- framework/src/media/MediaPlayerImpl.cpp
Sync with 5e871e64c7ff463a1f5581d5321a7d37146a6a98
> media: Take mutex at MediaPlayerImpl.notifySync

- lib/libc/math/lib_asin.c
- lib/libc/math/lib_asinf.c
- lib/libc/math/lib_asinl.c
- lib/libc/math/lib_cbrt.c
- lib/libc/math/lib_cbrtf.c
- lib/libc/math/lib_cbrtl.c
- lib/libc/math/lib_erf.c
- lib/libc/math/lib_erff.c
- lib/libc/math/lib_erfl.c
- lib/libc/math/lib_hypot.c
- lib/libc/math/lib_hypotl.c
- lib/libc/math/lib_jn.c
- lib/libc/math/lib_jnf.c
- lib/libc/math/lib_log.c
- lib/libc/math/lib_logf.c
- lib/libc/math/lib_logl.c
> Declare each variable in new line.
> Use correct exp*() api.
> libc/math: Fix violation of code rule

- os/drivers/audio/alc5658.c
This patch checks / validates the pointer validity before access.
The system might crash if addresses are not validated before use.
Signed-off-by: Girish K S <ks.giri@samsung.com>
> audio: alc: Handle the NULL pointer exception

- apps/examples/testcase/le_tc/kernel/tc_libc_math.c
- lib/libc/math/lib_erf.c
- lib/libc/math/lib_erff.c
- lib/libc/math/lib_erfl.c
- libc/math: Fix wrong implementation of err*() functions
- le_tc/kernel: Fix wrong expected values in math tc 
- le_tc/kernel: Fix wrong data type of declaration
> Fix math tc issues

- framework/include/media/FileInputDataSource.h
- framework/include/media/InputDataSource.h
- framework/src/media/FileInputDataSource.cpp
FileInputDataSource.seek() calls fseek()
> media: Add readAt method in FileInputDataSource

- apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_player.cpp
Add simple test of MediaPlayer methods.
getState, create, destroy, setDataSource,
prepare, unprepare, setVolume, getVolume
> testcase : Add MediaPlayer utc

- framework/src/media/FileInputDataSource.cpp
flcose(nullptr) could occur an error.
> media: Add nullptr check at FileDataSource.close

- framework/include/media/MediaRecorder.h
- framework/src/media/FileOutputDataSource.cpp
- framework/src/media/MediaRecorder.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
- framework/src/media/RecorderObserverWorker.cpp
- framework/src/media/RecorderWorker.cpp
code clean up for mediarecorder
> media : clean up for mediarecorder

- apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_recorder.cpp
add utc using gtest for media recorder
> testcase : add utc for media recorder

- framework/src/media/MediaPlayerImpl.h
mInputDataSource should be a unique_ptr
> media: Fix a wrong data type at MediaPlayerImpl

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- Merge 'destroy_audio_stream_in/out' functions into 'reset_audio_stream_in/out' functions, respectively.
> Modify reset logics of the audio manager

- framework/include/media/DataSource.h
- framework/src/media/DataSource.cpp
fix wrong return type of datasource
> media : fix wrong data type for datasource

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- os/drivers/audio/alc5658.c
- os/drivers/audio/alc5658.h
- os/drivers/audio/alc5658scripts.h
- os/include/tinyara/audio/audio.h
1. 'get_max_audio_volume' function to return the maximum volume is added.
2. 'get/set_audio_volume()' are seperated for input/output.
3. IOCTL flags for inquiring mic volumes in alc5658.c are added.
> Add volume setting/getting logics for input audio devices

- framework/src/media/audio/audio_manager.c
- The volume scaling calcuation considering interger variables are adjusted.
> Fix a volume conversion of volume between audio manager and alc5658

- framework/src/media/audio/audio_manager.c
- Unnecessary poiter variables are deleted.
> media: Refactor set/get volume code

- apps/examples/testcase/ta_tc/media/utc/utc_media_player.cpp
- framework/src/media/MediaPlayerImpl.cpp
MediaPlayer.setVolume checks input param using get_max_audio_volume
> media: Use get_max_audio_volume instead of literal

- apps/examples/testcase/ta_tc/media/utc/utc_media_player.cpp
Check onPlaybackStarted, onPlaybackFinished, onPlaybackError callback
> testcase: Add setObserver utc of MediaPlayer

- framework/include/media/DataSource.h
- framework/include/media/FileInputDataSource.h
- framework/include/media/FileOutputDataSource.h
- framework/src/media/FileInputDataSource.cpp
- framework/src/media/FileOutputDataSource.cpp
DataSource.close returns success or not
> media: Return bool when DataSource.close()

- apps/examples/mediarecorder/mediarecorder_main.cpp
- framework/src/media/MediaQueue.cpp
- framework/src/media/MediaQueue.h
- framework/src/media/PlayerObserverWorker.cpp
- framework/src/media/PlayerWorker.cpp
- framework/src/media/RecorderObserverWorker.cpp
- framework/src/media/RecorderWorker.cpp
refactoring media queue and thread modeling
> media : refactoring for media framework

- apps/examples/testcase/ta_tc/media/utc/utc_media_player.cpp
For testing setObserver, use wait() and notify_one()
> media_utc: Use conditional variable for test

- framework/src/media/PlayerWorker.cpp
- framework/src/media/RecorderWorker.cpp
an incorrect state was fixed when doing "dequeue"
> media : fix wrong condition for worker

- apps/examples/mediaplayer/mediaplayer_main.cpp
- framework/src/media/Decoder.cpp
- framework/src/media/Decoder.h
- framework/src/media/MediaQueue.h
- framework/src/media/PlayerWorker.cpp
- framework/src/media/RecorderWorker.cpp
- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
This PR is not completed. We should co-work with SRC-N on this PR.
Please consider.
**This PR has a dependency to the PR1576, So It can make a build failure temporarily.**
> media: Add Resampler

- framework/src/media/MediaQueue.cpp
- framework/src/media/MediaQueue.h
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
- framework/src/media/RecorderObserverWorker.cpp
- framework/src/media/RecorderObserverWorker.h
- framework/src/media/RecorderWorker.cpp
- framework/src/media/RecorderWorker.h
1. fix timing issues for thread
2. code cleanup for recorder
> media : refactoring for media recorder

- framework/src/media/MediaPlayerImpl.h
- framework/src/media/MediaQueue.cpp
- framework/src/media/MediaQueue.h
- framework/src/media/PlayerObserverWorker.cpp
- framework/src/media/PlayerObserverWorker.h
- framework/src/media/PlayerWorker.cpp
- framework/src/media/PlayerWorker.h
1. fix timing issues for thread
2. code cleanup
> media: refactoring for media player

- apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
test APIs: open, close, isPrepare, read, readAt
> media_utc: Add FileInputDataSource utc

- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.c
- st_things Logic modification to save state to file (fread, data size argument in fwrite)
- code refactoring : save cloud data uncessarily many times.
remove default ci server address.
> framework/st_things : modify to save cloud data unnecessarily many times.

- framework/src/st_things/Make.defs
- framework/src/st_things/st_things_request_handler.c
- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.h
- framework/src/st_things/things_stack/framework/things_server_builder.c
- framework/src/st_things/things_stack/framework/things_server_builder.h
- framework/src/st_things/things_stack/things_api.h
- modify collection resource links type
- add ST_THINGS_COLLECTIOn feature (default : disable)
> framework/st_things : disable collection resource feature

- apps/examples/testcase/ta_tc/media/utc/utc_media_recorder.cpp
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
- framework/src/media/audio/audio_manager.c
- os/drivers/audio/alc5658.c
modify logic and tc for volume in media recorder
> media: modify logic and tc for volume

- apps/examples/testcase/ta_tc/mqtt/itc/itc_mqtt_main.c
Changes in function:
1.use semaphore in MACRO's ITC_MQTT_WAIT_SIGNAL, ITC_MQTT_SEND_SIGNAL
2.use semphore init, deinit in function _itc_mqtt_init, _itc_mqtt_deinit
3.de-initialise handle with NULL in function itc_mqtt_deinit_n_redeinit_client to deallocate memory
> testcase/mqtt/itc: use semaphore in place of pthread condition variable

- apps/examples/testcase/le_tc/network/tc_net_accept.c
- apps/examples/testcase/le_tc/network/tc_net_bind.c
- apps/examples/testcase/le_tc/network/tc_net_close.c
- apps/examples/testcase/le_tc/network/tc_net_connect.c
- apps/examples/testcase/le_tc/network/tc_net_dup.c
- apps/examples/testcase/le_tc/network/tc_net_fcntl.c
- apps/examples/testcase/le_tc/network/tc_net_getpeername.c
- apps/examples/testcase/le_tc/network/tc_net_getsockname.c
- apps/examples/testcase/le_tc/network/tc_net_getsockopt.c
- apps/examples/testcase/le_tc/network/tc_net_ioctl.c
- apps/examples/testcase/le_tc/network/tc_net_listen.c
- apps/examples/testcase/le_tc/network/tc_net_recv.c
- apps/examples/testcase/le_tc/network/tc_net_recvfrom.c
- apps/examples/testcase/le_tc/network/tc_net_send.c
- apps/examples/testcase/le_tc/network/tc_net_sendto.c
- apps/examples/testcase/le_tc/network/tc_net_setsockopt.c
- apps/examples/testcase/le_tc/network/tc_net_shutdown.c
- apps/examples/testcase/le_tc/network/tc_net_socket.c
- external/dhcpc/dhcpc.c
- external/dhcpd/dhcpd.c
- framework/src/wifi_manager/wifi_manager.c
> network/tc: fix network issues in testcases

- apps/examples/testcase/tc_main.c
> apps/example/testcase: Install media_utc

- apps/system/utils/netcmd.c
- apps/system/utils/netcmd_ping.c
fix svace issues in network program.
> network: fix svace issues

- framework/src/media/audio/audio_manager.c
Some logic that placed in the loop can be out of the loop.
> media: Modify get closest samprate logic

- apps/examples/testcase/le_tc/kernel/Kconfig
- apps/examples/testcase/le_tc/kernel/kernel_tc_main.c
- apps/examples/testcase/le_tc/kernel/tc_errno.c
- apps/examples/testcase/le_tc/kernel/tc_libc_signal.c
- apps/examples/testcase/le_tc/kernel/tc_libc_stdio.c
- apps/examples/testcase/le_tc/kernel/tc_libc_string.c
- apps/examples/testcase/le_tc/kernel/tc_libc_unistd.c
- apps/examples/testcase/le_tc/kernel/tc_pthread.c
1. testcase/kernel: user-enable strerror feature on errno and str 
2. testcase/kernel: cover testcases with proper conditionals to fix build breaks
> testcase/kernel: remove unncessary dependancy and cover testcases with CONFIG_XX

- framework/src/st_things/st_things_request_handler.c
Add error handling codes.
There were lack of considerations on error handling.
If it shows an error, the error will be handled at the end of function with freeing the memories.
> framework/st_things : improve function logic of 'get_supported_properties'.

- framework/src/media/audio/audio_manager.c
> media: Prevent memcpy size can be a negative value

- framework/src/st_things/things_stack/port_tinyara.c
- framework/src/st_things/things_stack/utils/things_ping.c
- netlib_get_ipv4addr, netlib_get_dripv4addr, netlib_getifstatus return value check.
If the return value is -1, it is not set normally.
> framework/st_things : Fix issue that did not check return value

- apps/examples/wifi_manager_sample/wm_test.c
I change coding style of functions in wm_test.c
> examples/wifi_manager_sample: Change function coding style

- framework/src/media/audio/audio_manager.c
1. Merge find_in/out_audio_card to one function
2. Remove useless code
3. Clean duplicated code to get samplerate & volume at the same time
4. Add missing configs
> media: Clean duplicated code in audio_manager

- framework/include/media/DataSource.h
- framework/include/media/FileInputDataSource.h
- framework/include/media/FileOutputDataSource.h
- framework/include/media/InputDataSource.h
- framework/include/media/MediaPlayer.h
- framework/include/media/MediaPlayerObserverInterface.h
- framework/include/media/MediaRecorder.h
- framework/include/media/MediaRecorderObserverInterface.h
- framework/include/media/MediaUtils.h
- framework/include/media/OutputDataSource.h
All Media Framework APIs are included in MEDIA group
> media: Make MEDIA doxygen group

- apps/examples/st_things/light/contents/device_def.json
- apps/examples/st_things/light/sample_light_user.c
Add the necessary parts when sample_light works.
> apps/st_things : Fix the example in sample_light.

- apps/system/utils/netcmd.c
- apps/system/utils/netcmd.h
- fix error message format (saved in Netcmd.h) to unify macro format type
- change nvdbg to printf for ifconfig in order to provide user level log output
> apps/netcmd: Fix output debug messages

- apps/examples/testcase/le_tc/kernel/tc_libc_math.c
- apps/examples/testcase/le_tc/kernel/tc_libc_string.c
strtof and strtold convert a string to float/long double value.
> testcase/le_tc: Add libc testcase

- framework/src/media/Kconfig
- os/Kconfig.debug
subsystem debug configurations are located at Kconfig.debug
> Kconfig.debug: Move media debug configuration

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
- framework/src/media/PlayerWorker.cpp
- framework/src/media/PlayerWorker.h
All state changes are executed at Worker.
It removes hazard of race condition
> framework/media: Modify state change logic

- apps/examples/mediarecorder/mediarecorder_main.cpp
- framework/include/media/FileOutputDataSource.h
- framework/include/media/MediaRecorder.h
- framework/src/media/MediaRecorder.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
- framework/src/media/RecorderObserverWorker.cpp
- framework/src/media/RecorderWorker.cpp
- framework/src/media/RecorderWorker.h
all states were modified to change only through the record worker
> media: modify logic for manage the recorder state

- framework/src/media/audio/audio_manager.c
- get_hardware_params() is moved out from a while loop.
> media: Modify recursive calls in searching audio cards

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
modified it with tc which does not use gmock and gtest
> media : modify tc for media recorder

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
Sync MediaPlayerImpl.setObserver, setDataSource
> media: Sync Player with Recorder

- os/kernel/pthread/pthread_mutexdestroy.c
Please refer tc_pthread_pthread_mutex_destroy logic.
Main thread makes new thread which has lower priority than main.
And then, main calls pthread_join() to wait finishing new thread.
New thread just locks mutex and exit without unlocking.
After new thead is end, main wakes up and calls pthread_mutex_destroy.
But because main has higher prioriry than new, new thread can not
destroy scheduler's information, g_pidhash list.
Due to this, destroy function returns EBUSY even though new thread
is end.
To fix above, add more checking conditional inside destroy function.
1. is it pthread?
2. is it valid join structure?
3. is it marked as terminated?
> kernel/pthread/mutex: add checking exiting pthread to destroy

- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
- change tc api from 'wifi_utils' to 'wifi_manager'
> testcase/wifi_manager: Fix wrong usage of wm apis

- apps/examples/mediaplayer/mediaplayer_main.cpp
- apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_player.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- framework/include/media/MediaPlayerObserverInterface.h
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/PlayerObserverWorker.h
ref) https://github.com/Samsung/TizenRT/pull/1703
1. pause function is async.
inform to users for result of paused.
2. modify tc for onPaused
> media: Add onPaused function for user player cb

- apps/examples/mediarecorder/mediarecorder_main.cpp
- apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_recorder.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
- framework/include/media/MediaRecorderObserverInterface.h
- framework/src/media/FileOutputDataSource.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
1. pause function is async.
inform to users for result of paused.
2. add tc for onPaused
> media: add onPaused function for user callback

- os/arch/arm/src/artik05x/src/artik05x_tash.c
- os/fs/driver/mtd/rammtd/rammtd.c
1. Add check routine when it alloc rammtd space
2. memset when rammtd initialized
> fs : clear rammtd space when it initialize

- framework/src/media/PlayerWorker.cpp
> media: Modify PlayerWorker logic

- framework/src/media/MediaRecorderImpl.cpp
The condition of resume is needed.
> add missing state for paused case

- apps/examples/mediaplayer/mediaplayer_main.cpp
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/PlayerWorker.cpp
If old player and new player is same, do not pause old player
> media: Fix startPlayer logic

- framework/src/media/MediaRecorderImpl.cpp
our framework support multi instance.
add missing condition for compare the same recorder.
> media: add logic for resume case

- apps/examples/mediarecorder/mediarecorder_main.cpp
media recorder support the control the volume
add volume up and down cases for recorder example
> media: modify recorder example for control the volume

- framework/include/media/MediaPlayer.h
- framework/src/media/MediaPlayer.cpp
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
This API has not been implemented yet and has been removed
> media: remove seekTo function

- apps/examples/st_things/msghandling/contents/deivce_def.json
- apps/examples/st_things/msghandling/sample_msghandling_things.c
- apps/examples/st_things/msghandling/sample_msghandling_user.c
This example can explain how to handle string array attribute from payload.
> apps/examples/st_things : update example of message handling.

- apps/examples/testcase/le_tc/kernel/tc_libc_string.c
using math apis such as round, fabs, CONFIG_LIBM is needed
> testcase/libc_string: Add ifdef condition which needed LIBM

- apps/examples/testcase/le_tc/kernel/itc_pthread.c
testcase :
itc_pthread_key_create_set_get_specific_p_multitime -> call of create key and destroy key in subroutine.
> apps/testcase/kernel: changes in ITC of pthread in itc_pthread.c

- framework/src/media/Make.defs
- framework/src/media/MediaWorker.cpp
- framework/src/media/MediaWorker.h
- framework/src/media/PlayerObserverWorker.h
- framework/src/media/PlayerWorker.cpp
- framework/src/media/PlayerWorker.h
- framework/src/media/RecorderObserverWorker.cpp
- framework/src/media/RecorderObserverWorker.h
- framework/src/media/RecorderWorker.cpp
- framework/src/media/RecorderWorker.h
PlayerWorker, PlayerObserverWorker, RecordWorker, RecordObserverWorker
inherit MediaWorker
> media: Add MediaWorker

- apps/examples/testcase/ta_tc/audio/itc/itc_audio_main.c
itc_audio_pcm_readi_p
1.give the proper frame count in pcm_readi
Signed-off-by: sri <sri@s.sa.corp.samsungelectronics.net>
> apps/testcase/audio : give the frame count in pcm_readi

- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
- framework/src/wifi_manager/wifi_manager.c
- Add UTCs for WiFi Manager to save/get/reset AP configuration
> testcase/wifi-manager: Add wifi_manager UTCs

- framework/src/media/audio/resample/samplerate.c
- framework/src/media/audio/resample/samplerate.h
In the struct src_data_s,  should set data_out and out_buf_length by user.
@Taejun-Kwon
> audio/resampler: interface update.

- framework/include/media/DataSource.h
- framework/include/media/FileInputDataSource.h
- framework/include/media/InputDataSource.h
- framework/include/media/MediaTypes.h
- framework/src/media/FileInputDataSource.cpp
- framework/src/media/InputDataSource.cpp
- framework/src/media/Make.defs
- framework/src/media/utils/MediaUtils.cpp
- framework/src/media/utils/MediaUtils.h
1. Remove MediaUtils.h from framework/include/media
2. Create media folders to maintain media utils
3. clean include codes related to MediaUtils.h
4. Add MediaTypes.h to provide Media Type instead of MediaUtils.h
> Media : Clean folder structure

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaWorker.cpp
- framework/src/media/MediaWorker.h
- framework/src/media/PlayerObserverWorker.cpp
- framework/src/media/PlayerObserverWorker.h
- framework/src/media/PlayerWorker.cpp
- framework/src/media/PlayerWorker.h
- framework/src/media/RecorderObserverWorker.cpp
- framework/src/media/RecorderObserverWorker.h
- framework/src/media/RecorderWorker.cpp
- framework/src/media/RecorderWorker.h
MediaPlayer, MediaRecord can not access MediaQueue
> media: Conceal MediaQueue

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
- framework/src/media/PlayerWorker.cpp
> media: Move playback logic in MediaPlayerImpl

- framework/src/wifi_manager/wifi_manager.c
- Modify log to easily verify the operation of AUTOCONNECT (for tc).
> framework/wifi_manager: Change log of RECONNECT state

- framework/include/wifi_manager/wifi_manager.h
- framework/src/wifi_manager/wifi_manager.c
- Add state, softap_disconnecting, to handle disconnect callback
when state transition occurs from STA connected to SoftAP
> framework/wifi_manager: Fix state transition err from STA connected to SoftAP

- framework/include/media/InputDataSource.h
- framework/src/media/Decoder.cpp
- framework/src/media/FileInputDataSource.cpp
- framework/src/media/InputDataSource.cpp
- framework/src/media/MediaPlayerImpl.cpp
1. Remove decode logic to read function in InputDataSource
2. Add feof into read to check position reaches end of file
> media : remove decode logic from playerImpl to InputDataSource

- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
- Add mutex wait/send signal for scanning function
- Test functions to save/get/reset AP info in file system after the connection is successfully finished
- Modify return type verification for utc_wifi_manager_save_config_n
> testcase/wifi_manager: WiFi Manager UTC bug fix

- framework/src/media/FileInputDataSource.cpp
- framework/src/media/InputDataSource.cpp
- framework/src/media/Make.defs
1. remove trailing blank
2. Align pointer to right
> media: Apply coding rule

- framework/src/media/Make.defs
MediaUtils.cpp was added twice
> media: Remove dupliacated CXXSRC

- os/kernel/environ/env_dup.c
Fix an error in the duplication of the child tasks environment in the special case
where the parent's environment was created, but then all of the variables were unset.
In that case, there is still an allocation in place but the size of the allocation is zero.
This case was not being handled correctly when a child task attempts to create its environment
and inherit the zero-size parent environment. Noted by Anthony Merlino.
`This patch is back-ported from Nuttx.`
> kernel/environ: Fix an error in the duplication of the child tasks environment

- apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c
- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
1st argument of TC macro should be function name which is tested by testcase, not testcase name
> testcase/task_manager, wifi_manager: modify giving 1st argument of TC macro

- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- A wrong calculation in the buffer address of input stream is fixed.
> media: fix audio manager resampling

- os/drivers/audio/alc5658.c
Fix to use take sem before I2S_STOP
> Audio : Fix wrong usuage of takesem

- apps/examples/task_manager_sample/README.md
- apps/examples/task_manager_sample/action_manager.c
- apps/examples/task_manager_sample/alarm.c
- apps/examples/task_manager_sample/user.c
- apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c
- framework/include/task_manager/task_manager.h
- framework/src/task_manager/Make.defs
- framework/src/task_manager/task_manager_core.c
- framework/src/task_manager/task_manager_restart.c
The restart API supports functionality to restart running task.
> framework/task_manager: implement task manager restart API

- framework/src/wifi_manager/wifi_manager.c
- framework/src/wifi_manager/wpa_wifi_utils.c
- Modify return format and exception handling to increase code coverage
> framework/wifi_manager: Modification of API return format 

- apps/examples/testcase/Makefile
- apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c
Add testcases for added APIs (task_manager_set_broadcast_handler() and task_manager_broadcast()).
> testcase/task_manager: Add testcases about the broadcast functionality

- apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
Modify utc/media according to media framework changes.
refer https://github.com/Samsung/TizenRT/pull/1818
> testcase/media: Modify utc according to #1818

- framework/src/st_things/things_stack/cloud/cloud_manager.c
- framework/src/st_things/things_stack/utils/things_ping.c
It has shown an error when reset request receives from client.
The error cause is racing between ping, ca and session keep alive threads.
1. The ping apply mutex logic to common used variable.
2. Ping thread will terminate when tcp session disconnected.
> framework/st_things : improve things ping.

- tools/ramdump/HowToUseRamdump.md
1. typo : terminal, dumpParser
2. modify description about ramdump step
> tools/ramdump/readme: Modify typo and awkward description

- framework/src/media/InputDataSource.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/RecorderWorker.cpp
This is for using debug messages.
> media: Include missed debug.h

- apps/examples/testcase/le_tc/filesystem/fs_main.c
This reverts commit 025cd752928a44adb72ad093ce0c65a7e1bfd6e2.
> Revert "testcase/filesystem: Fix fs readdir() tc failure"

- apps/examples/wifi_manager_sample/wm_test.c
- Add a counter value for API call failure; the value counts the number of API calls
which are expected to be successfully invoked, but failed.
- Change to allow mutex wait only after succesful API call
> apps/example/wifi_manager: Modification of Wifi Manager Auto-test

- apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c
- framework/include/task_manager/task_manager.h
- framework/src/task_manager/Kconfig
- framework/src/task_manager/task_manager_broadcast.c
- framework/src/task_manager/task_manager_core.c
- framework/src/task_manager/task_manager_getinfo.c
- framework/src/task_manager/task_manager_interface.c
- framework/src/task_manager/task_manager_internal.h
- framework/src/task_manager/task_manager_pause.c
- framework/src/task_manager/task_manager_register.c
- framework/src/task_manager/task_manager_restart.c
- framework/src/task_manager/task_manager_resume.c
- framework/src/task_manager/task_manager_set_callback.c
- framework/src/task_manager/task_manager_start.c
- framework/src/task_manager/task_manager_terminate.c
- framework/src/task_manager/task_manager_unicast.c
- framework/src/task_manager/task_manager_unregister.c
- os/Kconfig
- os/drivers/task_manager/task_manager_drv.c
- change the prefix of defined command types from TASKMGT to TASKMGR
- add missing logics and delete unnesassary codes
> framework/task_manager: clean the source codes in task manager

- os/Makefile.unix
- os: update info about running of build configuration tool
- os: Add support for nconfig frontend 'make nconfig'
> build configuration method refactor and enhancment

- apps/examples/st_things/msghandling/sample_msghandling_user.c
It is applied st things the OCF specs.
Please refer below address.
https://github.com/Samsung/SmartThings/blob/master/internal/definition/Cloud-connected/ocf/RAML
> apps/example/st_things : update request handling example.

- framework/src/media/audio/audio_manager.c
1. Before return, apply pthread_unlock
> media/audio_manager : apply pthread_unlock when missing case

- apps/examples/testcase/le_tc/network/tc_net_accept.c
- apps/examples/testcase/le_tc/network/tc_net_bind.c
- apps/examples/testcase/le_tc/network/tc_net_getpeername.c
- apps/examples/testcase/le_tc/network/tc_net_listen.c
- apps/examples/testcase/le_tc/network/tc_net_recv.c
- apps/examples/testcase/le_tc/network/tc_net_recvfrom.c
- apps/examples/testcase/le_tc/network/tc_net_send.c
- apps/examples/testcase/le_tc/network/tc_net_sendto.c
- apps/examples/testcase/le_tc/network/tc_net_shutdown.c
Fix code that violates the coding rules specified in wiki.tizen.org
> network/tc: Fix violations of coding rule

- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
New testcase's :
1.itc_wifi_manager_connect_ap_config_p  -> use to connect a AP with all SSID configuration.
2.itc_wifi_manager_save_get_config_p    -> use to save the configuration parameter and then geting saved configuration parameter
3.itc_wifi_manager_get_remove_config_p  -> use to get configuration parameter and removing ap configuration after get.
4.itc_wifi_manager_remove_get_config_p  -> use to remove then get configuration parameter of ap.
5.itc_wifi_manager_get_config_n         -> This is a negative tc in which we try to get ap configuration parameter even without saving.
6.itc_wifi_manager_connect_ap_config_n  -> This is a negative tc in which we try to connect with ap with invalid parameter.
> apps/testcase/wifi_manager : add ITC testcase for WiFi manager

- apps/examples/mediastreamer/mediastreamer_main.cpp
- Fix an app build error when adding onRecordPaused interface in MediaRecorderObserverInterface
> framework/media : Fix MediaStreamer Sample App build error

- README.md
- apps/builtin/README.md
- docs/API_Reference/README.md
- docs/HowToAddnewBoard.md
- docs/HowToDevelopThingsWithTizenStudioForRT.md
- docs/HowToManageDeviceModel.md
- docs/HowToPortTizenRTOnWiFiChipset.md
- docs/HowToUseAudio.md
- docs/HowToUseMPU.md
- docs/HowToUsePeripheral.md
- docs/HowToUseSmartFS.md
- docs/HowToUseTinyAlsa.md
- docs/Porting_Guide.md
- docs/TroubleShooting.md
- os/logm/README.md
specifc -> specific
comming -> coming
excutes -> executes
practise -> practice
desgin -> design
mandantory -> mandatory
Exploer -> Explorer
devcie -> device
refet -> refer
libary -> library
attirbute -> attribute
diable -> disable
initialzation -> initialization
messgaes -> messages
ect -> etc
instace, instanse -> instance
initialzed -> initialized
dependant -> dependent
menchanism -> mechanism
accross -> across
ingore -> ignore
avaialable -> available
occured -> occurred
argumens -> arguments
dedcides -> decides
queueing -> queuing
temporarilliy -> temporarily
> README: fix typo

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- os/fs/Kconfig
- os/fs/fs_initialize.c
- os/fs/mount/fs_mount.c
- os/fs/tmpfs/Kconfig
- os/fs/tmpfs/Make.defs
- os/fs/tmpfs/fs_tmpfs.c
- os/fs/tmpfs/fs_tmpfs.h
- os/include/tinyara/fs/dirent.h
- os/include/tinyara/fs/fs.h
This  first patch adds tmpfs feature into TizenRT 
The second patch adds conditional checks  in filesystem tc which support tmpfs.
> Add tmpfs filesystem into TizenRT

- framework/include/media/FocusChangeListener.h
- framework/include/media/FocusManager.h
- framework/include/media/FocusRequest.h
- framework/src/media/FocusManager.cpp
- framework/src/media/FocusRequest.cpp
- framework/src/media/Make.defs
FocusManager supports requestfocus and abandonfocus.
If focus change, FocusChangeListener invoke callback.
> media: Add FocusManager

- framework/src/st_things/st_things.c
- framework/src/st_things/things_stack/easy-setup/easysetup_manager.c
- When the file does not exist, it is not an error but it is output as an error.
- Fix missing TAG in first parameter of THINGS_LOG_D
> framework/st_things : Correct mistakes in the error log

- framework/src/st_things/Kconfig
- framework/src/st_things/things_stack/framework/things_data_manager.c
- Modify logic to store cloud data in secure storage
> framework/st_things : Using Secure Storage features

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/audio/audio_manager.c
- os/drivers/audio/alc5658.c
MediaPlayer call audio_manager pause API when MediaPlayer is paused
> media: Add missed logic in MediaPlayer pause

- apps/examples/mediaplayer/mediaplayer_main.cpp
mediaplayer_main have a MediaPlayerController.
It controls two MediaPlayer.
> apps/mediaplayer: Add FocusManaging scenario

- framework/src/st_things/things_stack/framework/things_req_handler.c
- framework/src/st_things/things_stack/things_api.h
- framework/src/st_things/things_stack/things_stack.c
- framework/src/st_things/things_stack/utils/things_network.c
- Change the location where Wifi turns on (at startup -> after creating the resource)
- If initialize fails, exception handling at start
- Remove useless code(g_quit_flag)
- Remove the variable that was being used incorrectly(is_there_module_inited)
> framework/st_things : If initialize fail exception handling at start

- framework/include/media/FileOutputDataSource.h
- framework/src/media/FileOutputDataSource.cpp
Description says `if error occurred, it returns -1`
Match description and implement
> media: Modify FileOutputDataSource return value

- framework/include/media/BufferOutputDataSource.h
- framework/src/media/BufferOutputDataSource.cpp
- framework/src/media/Make.defs
Data out through the buffer.
Callback should be used.
> framework/media : Add BufferOutputDataSource.

- framework/src/st_things/things_stack/utils/things_network.c
It has a bug which It returned an error when tried to connect removed WIFI after just booted and then does not try the auto reconnection.
So, through commit, things can try to connect ap until the AP discovered.
> framework/st_things] fix an bug which can not connect any AP after rebooted

- framework/src/media/MediaWorker.cpp
- framework/src/media/MediaWorker.h
This reverts commit bdaccf67cbfe19a33cfbf7e438d06b4da6205c50.
> media: Revert "media: Make MediaWorker immortal"

- framework/src/st_things/things_stack/cloud/cloud_connector.c
- framework/src/st_things/things_stack/cloud/cloud_manager.c
- Unnecessary Logic Cleanup (Default Server)
- Remove unused logic
> framework/st_things : Fix unnecessary cloud connectivity logic

- framework/src/wifi_manager/wpa_wifi_utils.c
- Modify a bad log in wifi_utils_scan_ap
> framework/wifi_utils: Fix bad log in scan function

- external/slsi_wifi/slsi_wifi_api.c
- framework/src/st_things/things_stack/things_stack.c
- framework/src/wifi_manager/wifi_profile.c
- os/drivers/wireless/scsc/t20_ops.c
* Fix few memory leak, fd leak, unutilized variables
> memory leak fixes

- apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c
- framework/src/task_manager/task_manager_core.c
- framework/src/task_manager/task_manager_internal.h
- framework/src/task_manager/task_manager_register.c
1. Modify registering task and pthread and fix typo
2. Add task_manager_register_task/pthread TCs
> task_manager: Modify task_manager_register_task/pthread and Add TCs

- framework/src/media/MediaPlayerImpl.cpp
- There is a funtion (notifySync) for sync via workqueue, but it is not actually use.
> framework/media : Change to use notifySync function

- framework/src/media/FileOutputDataSource.cpp
- framework/src/media/SocketOutputDataSource.cpp
- SocketOutputDataSource::write return type is ssize_t
> framework/media : Correct wrong casting type.

- lib/libc/time/lib_localtime.c
- os/include/time.h
tzset is changed to public API.
This commit is cherry-picked from nuttx(f087e35)
> [libc/time] A little localtime clean-up

- apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c
- framework/include/task_manager/task_manager.h
- framework/src/task_manager/task_manager_core.c
- framework/src/task_manager/task_manager_getinfo.c
- framework/src/task_manager/task_manager_internal.h
- framework/src/task_manager/task_manager_set_callback.c
- framework/src/task_manager/task_manager_unicast.c
1. Change the type of data field in tm_response_t
2. Add task_manager_reply_unicast API and its TC
> framework/task_manager: Add sync type unicast functionality and its tc

- os/include/debug.h
Add missing task manager debug defines
> include/debug.h: Modify debug defines of task manager

- apps/examples/smart_test/smart_test.c
- framework/src/st_things/things_stack/framework/things_sss_manager.c
Apply the coding rule in things_sss_manager.c
Correct English grammar and typo errors
> Apply the coding rule and fix typo errors

- apps/examples/eventloop/Kconfig
- apps/examples/eventloop/Make.defs
- apps/examples/eventloop/Makefile
- apps/examples/eventloop/eventloop_sample_main.c
- framework/include/eventloop/eventloop.h
- framework/src/eventloop/Kconfig
- framework/src/eventloop/Make.defs
- framework/src/eventloop/eventloop_internal.h
- framework/src/eventloop/eventloop_loop.c
- framework/src/eventloop/eventloop_timer.c
- os/Kconfig
- os/Kconfig.debug
- os/include/debug.h
User can add and delete timer to be called once or every seconds.
> framework/eventloop: Implement eventloop timer APIs

- apps/system/utils/README.md
- apps/system/utils/fscmd.c
- Adds description of 'echo' command.
- Modifies description of 'cat' command.
- Adds '--help' option to cat command.
> system/utils: Update README.md

- apps/examples/iotjs_startup/.gitignore
- apps/examples/iotjs_startup/Kconfig
- apps/examples/iotjs_startup/Kconfig_ENTRY
- apps/examples/iotjs_startup/Make.defs
- apps/examples/iotjs_startup/Makefile
- apps/examples/iotjs_startup/README.txt
- apps/examples/iotjs_startup/iotjs_startup_main.c
It has been tested on ARTIK055s's nettest image,
along a WPA2+AES AP.
Change-Id: I633ea759cacaab632b56a24ba7cb7e7b5debb5fb
Signed-off-by: Philippe Coval <p.coval@samsung.com>
> iotjs: Add startup script for iotjs

- framework/src/media/MediaPlayerImpl.h
- framework/src/media/PlayerWorker.cpp
> media: Change the access specifier of MediaPlayer

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
stopByERror make state PLAYER_STATE_READY to stop playback
> media: Add errcode param in stopImpl function

- apps/examples/mediarecorder/mediarecorder_main.cpp
Since ramfs is not uesd, correct it.
> apps/mediarecorder: modify filepath from ramfs to tmp.

- .travis.yml
- add genromfs
- add kconfig-frontends
> travis: update docker image version

- framework/include/eventloop/eventloop.h
- framework/src/eventloop/eventloop_loop.c
- framework/src/eventloop/eventloop_timer.c
- In default, a task has its own loop.
User can add and handle the event in its own loop.
> framework/eventloop: Implement loop per task

- apps/examples/testcase/ta_tc/task_manager/utc/utc_task_manager_main.c
- framework/include/task_manager/task_manager.h
- framework/src/task_manager/task_manager_cleaninfo.c
- framework/src/task_manager/task_manager_core.c
- framework/src/task_manager/task_manager_getinfo.c
app_info_s and app_info_list_s is task manager structure.
for readability, add prefix "tm_"
> framework/task_manager: Add prefix "tm_" to app information structure

- os/tools/download.sh
--help shows how to use this command.
> tools: add usages on download.sh

- apps/examples/mediaplayer/mediaplayer_main.cpp
- apps/examples/mediarecorder/mediarecorder_main.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- framework/include/media/MediaPlayerObserverInterface.h
- framework/src/media/MediaPlayer.cpp
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
Modify like below
`onPlaybackCb(Id id) -> onPlaybackCb(MediaPlayer &player)`
and apply coding rule
> media: Replace id with MediaPlayer as cb argument

- external/grpc/README.md
update gRPC README with details describing how to install gRPC 1.9.0 on Linux environment.
> update gRPC README.md

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/system/utils/fscmd.c
- lib/libc/lib_internal.h
- lib/libc/stdio/lib_tempnam.c
- lib/libc/stdio/lib_tmpnam.c
- lib/libc/stdlib/Make.defs
- lib/libc/stdlib/__randname.c
- lib/libc/stdlib/lib_mkstemp.c
- lib/libc/stdlib/lib_mktemp.c
- os/include/stdlib.h
- libc/stdlib: Re-implement mktemp()
- libc/stdlib: Modify mkstemp() implementation
- libc/stdio: Modify implementation of tmpnam and tempnam
- testcase/filesystem: Refactor test cases of tmpnam and tempnam
> Fix implementation of mktemp 

- os/drivers/gpio/gpio.c
Cherry picked from internal git
> GPIO modification

- external/grpc/README.md
Update gRPC README.md with details on how to install Protocol Buffers in host environment.
> Update grpc readme with Protobuf installation

- framework/include/media/FileInputDataSource.h
- framework/include/media/InputDataSource.h
- framework/src/media/FileInputDataSource.cpp
- framework/src/media/InputDataSource.cpp
Add seek api
readAt is combined seek and read
> media: Add seek api

- framework/src/wifi_manager/wpa_wifi_utils.c
code indent should use tabs where possible
> framework/wifi_manager: Apply coding rule

- apps/examples/eventloop/eventloop_sample_main.c
- apps/system/init/init.c
- framework/include/eventloop/eventloop.h
- framework/src/eventloop/Make.defs
- framework/src/eventloop/eventloop_task.c
- framework/src/eventloop/eventloop_timer.c
- os/include/signal.h
- os/include/tinyara/eventloop.h
- os/kernel/Kconfig
Event loop framwork supports an independent loop.
It is started when system start and waits for the event from a task.
If some tasks add event by calling async functions, this event is added a loop of event loop task.
And then event loop task wakes up and handles added event.
. eventloop_add_timer_async
> framework/eventloop: Implement async event handling.

- apps/examples/testcase/le_tc/kernel/tc_sched.c
1. Because the testcase of waitid has a wrong test,
let's remove it.
[tc_sched_waitid] FAIL [Line : 372] waitid : Values (ret_chk == 0x0) and (-1 == 0xffffffff) are not equal
2. Because the function name should have what it does,
let's rename it.
3. Let's remove unnecessary definitions.
> testcase/kernel/sched: remove unncessary logic and refactor

- apps/examples/mediaplayer/mediaplayer_main.cpp
- apps/examples/mediarecorder/mediarecorder_main.cpp
- apps/examples/testcase/ta_tc/media/itc/itc_media_mediaplayer.cpp
- apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_player.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
PLAYER_ERROR will be split.
So check whether result is PLAYER_OK
> media: Check result using PLAYER_OK

- apps/examples/mediarecorder/mediarecorder_main.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
- framework/include/media/MediaRecorder.h
- framework/include/media/MediaRecorderObserverInterface.h
- framework/src/media/MediaRecorder.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
Integrate the error type of the recorder
> media: modify error types for recorder

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- framework/include/media/MediaPlayer.h
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
Rename player_result_t to player_error_t
> media: Modify player_error_e 

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
Add error handling logics
for filesystem and file open file cases
> add defense code for player TC

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
[get/set]VolumePlayer -> [get/set]PlayerVolume
> media: Rename get/set volume internal function

- framework/include/wifi_manager/wifi_manager.h
- Add extern "C" for __cplusplus in wifi_manager.h
> framework/wifi_manager: Add extern "C" in header

- README.md
- docs/InstallAdReq.md
That shows necessary installation to use some features.
> README: add AdvancedEnv tab

- framework/include/media/MediaRecorder.h
The annotation was changed incorrectly.
> media: modify the annotation for MediaRecorder header

- framework/include/media/MediaPlayer.h
- framework/include/media/MediaRecorder.h
The annotation was changed incorrectly.
> modify the annotation for media header

- framework/include/media/BufferOutputDataSource.h
- framework/src/media/BufferOutputDataSource.cpp
Align pointer to right
Remove unnecessary '\'
> media: Apply coding rule in BufferOutputDataSource

- README.md
- build/configs/artik053/README.md
- build/configs/artik053s/README.md
- build/configs/artik055s/README.md
- build/configs/qemu/README.md
- build/configs/sidk_s5jt200/README.md
- docs/HowToSetEnv.md
- os/dbuild.sh
- add docker build script.
- add guide in docs.
> build/script: add docker build script.

- README.md
- os/tools/configure.sh
1. README: add dot at numbering
2. os/tools/configure: guide dbuild.sh to execute distclean
> modify build/configuration guidance for docker

- external/libtuv/source/tinyara/uv_tinyara_io.c
- external/libtuv/source/unix/uv_unix_signal.c
- external/libtuv/source/uv_loop.c
- external/libtuv: update some logics in libtuv
- external/libtuv: change logic of uv__signal_lock/unlock
> external/libtuv: update libtuv

- apps/system/utils/README.md
- apps/system/utils/fscmd.c
This patch fixes the wrong logic of writing into a file using 'echo' command.
> system/utils: Refactor implementation of 'echo'

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
LOG_STATE() print current state
> media: Add state logging macro

- README.md
- apps/builtin/README.md
- apps/shell/README.md
- apps/system/utils/README.md
- build/configs/artik053/README.md
- build/configs/artik053s/README.md
- build/configs/artik055s/README.md
- build/configs/sidk_s5jt200/README.md
- external/iotivity/README.md
- framework/src/task_manager/README.md
- os/logm/README.md
1. add caution of menuconfig in Docker env
2. "through menuconfig" -> "with menuconfig"
3. use [*] or [ ] instead of "to y" or "to n" to show clearly how to set
> Readme: tidy up

- framework/include/media/BufferInputDataSource.h
- framework/include/media/InputDataSource.h
- framework/include/media/MediaPlayerObserverInterface.h
- framework/src/media/BufferInputDataSource.cpp
- framework/src/media/Make.defs
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
> media: Add BufferInputDataSource

- external/libtuv/source/tinyara/Make.defs
- external/libtuv/source/tinyara/uv_tinyara_signal.c
- external/libtuv/source/unix/Make.defs
- external/libtuv: Move and rename a file about signal event.
- external/libtuv: Modify a global signal tree to a array to signal tree.
> external/libtuv: Modify signal tree of libtuv

- apps/examples/mediarecorder/mediarecorder_main.cpp
Save data to file by buffer and play the file.
> app/mediarecorder: Add BufferOutputDataSource app.

- apps/examples/mediaplayer/mediaplayer_main.cpp
To prepare mediaplayer, datasource should be set.
> examples/mediaplayer: Set source at PLAYER_START

- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- os/drivers/audio/Kconfig
- os/drivers/audio/alc5658.c
- os/drivers/audio/audio_null.c
- os/include/tinyara/audio/audio.h
1. Add constant of audio ioctl
2. Add device process checker in audio manager
3. Add stream policy rule
4. Expand sound card & device structure
5. Add change device logic
6. Add audio manager dump
7. clean card & mutex logic
> framework/media : Add Audio Interface for Speech Detecter

- framework/src/media/InputDataSource.cpp
registerDecoder should check return value of Decoder::create
> media: Fix registerDecoder bug

- apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
Check return value to find test fail
> media/utc: Add return check at utc

- external/libtuv/source/uv_handle.c
- external/libtuv/source/uv_loop.c
- external/libtuv/source/uv_run.c
- framework/src/eventloop/eventloop_loop.c
- framework/eventloop: add closing loop when all works in loop are finished
- external/libtuv: update missing logics related to signal and loop
- framework/eventloop: fix loop closing procedure
> framework/eventloop: Fix issues about loop closing

- framework/src/media/Decoder.cpp
- framework/src/media/Decoder.h
- framework/src/media/Encoder.cpp
- framework/src/media/Encoder.h
Remove useless constructors.
All member are initialized at construction time.
Apply coding rule.
Fix some #ifdef macro.
> media: Refactor Decoder, Encoder

- apps/examples/testcase/ta_tc/media/utc/Make.defs
- apps/examples/testcase/ta_tc/media/utc/utc_media_focusmanager.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_focusrequest.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
- framework/include/media/FocusRequest.h
- framework/src/media/FocusRequest.cpp
Add FocusRequest, FocusManager utc
Fix id setting logic.
> media/utc: Add focus API utc

- framework/src/media/InputDataSource.cpp
- framework/src/media/MediaWorker.cpp
- framework/src/media/OutputDataSource.cpp
Add missed initializer in MediaWorker, InputDataSource, OutputDataSource
> media: Add missed initializer

- apps/examples/mediaplayer/mediaplayer_main.cpp
- framework/include/media/MediaTypes.h
- framework/src/media/FileInputDataSource.cpp
- framework/src/media/utils/MediaUtils.cpp
- framework/src/media/utils/MediaUtils.h
Audio type acc, mp3, wave header parsing.
> framework/media: Add audio header parsing.

- apps/examples/testcase/ta_tc/wifi_manager/utc/utc_wifi_manager_main.c
- Add UTC of wifi_manager_get_connected_config
- Add UTC of wifi_manager_get_stats
> apps/testcase/wifi_manager: add UTCs of newly added public APIs

- framework/src/media/audio/audio_manager.c
- A default sample rate is now set as the maximum one supported by the device.
> framework/media: Fix the search logic for the closest sample rate.

- docs/HowToUseIoTjs.md
Signed-off-by: Ziran Sun <ziran.sun@samsung.com>
> Update IoTjs documentation.

- framework/include/eventloop/eventloop.h
- framework/src/eventloop/Make.defs
- framework/src/eventloop/eventloop_event.c
- framework/src/eventloop/eventloop_internal.h
- os/include/signal.h
- os/kernel/Kconfig
User can add, delete handler for specific event and send event like broadcast.
> framework/eventloop: Implement eventloop event APIs

- apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
- framework/src/media/FileInputDataSource.cpp
At FileInputDataSource::read, check isPrepare() returns true
> media: Check file is prepared before read the file

- apps/examples/mediaplayer/BufferInputDataSource.cpp
- apps/examples/mediaplayer/BufferInputDataSource.h
- apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
- framework/include/media/FileInputDataSource.h
- framework/include/media/InputDataSource.h
- framework/src/media/FileInputDataSource.cpp
- framework/src/media/InputDataSource.cpp
> media: Revert seek and readAt

- apps/examples/testcase/ta_tc/media/utc/utc_media_bufferoutputdatasource.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_fileinputdatasource.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_fileoutputdatasource.cpp
getAudioType_p, setAudioType_p and setAudioType_n are added.
> apps/testcase/media: Add testcase for new api

- framework/src/eventloop/eventloop_async.c
1. Add insert NULL value procedures is func_handle remove process.
2. Manual func_handle remove procedures are replaced with static fucntion (eventloop_func_handle_remove).
> framework/eventloop: Add insert NULL value procedure

- apps/examples/eventloop/eventloop_sample_main.c
- framework/include/eventloop/eventloop.h
- framework/src/eventloop/eventloop_async.c
- framework/src/eventloop/eventloop_event.c
- framework/src/eventloop/eventloop_timer.c
- framework/eventloop: Change return type of timeout_callback and logic about cleaning used resources
- framework/eventloop: Change input of event and async call APIs
> framework/eventloop: Modify eventloop APIs

- framework/include/task_manager/task_manager.h
- framework/include/task_manager/task_manager_broadcast_list.h
task_manager.h
messges -> messages
builtin -> buillt-in
deallocation -> de-allocation
task_manager_broadcast_list.h
messges -> messages
asceding -> ascending
> framework/task_manager: Fix typo and Modify expressions

- framework/src/media/InputHandler.cpp
InputHander needs <tinyara/config.h>
> media: Include missed header at InputHandler

- framework/include/media/BufferObserverInterface.h
- framework/include/media/BufferOutputDataSource.h
- framework/include/media/DataSource.h
- framework/include/media/FileInputDataSource.h
- framework/include/media/FileOutputDataSource.h
- framework/include/media/InputDataSource.h
- framework/include/media/MediaPlayer.h
- framework/include/media/MediaPlayerObserverInterface.h
- framework/include/media/MediaRecorder.h
- framework/include/media/MediaRecorderObserverInterface.h
- framework/include/media/MediaTypes.h
- framework/include/media/OutputDataSource.h
- framework/include/media/SocketOutputDataSource.h
- framework/include/tinyalsa/tinyalsa.h
- framework/src/media/MediaPlayerImpl.h
- framework/src/media/MediaRecorderImpl.h
- framework/src/media/utils/MediaUtils.h
- All "TizenRT v2.0 PRE" in framework/include/media are updated as "TizenRT v2.0".
> framework/media: change a version to TizenRT 2.0 at Doxygen

- apps/examples/nettest/nettest.c
- apps/examples/testcase/le_tc/network/tc_internal.h
- apps/examples/testcase/le_tc/network/tc_net_getpeername.c
- apps/examples/testcase/le_tc/network/tc_net_getsockopt.c
- apps/examples/testcase/le_tc/network/tc_net_setsockopt.c
- apps/examples/testcase/le_tc/network/tc_net_socket.c
- os/net/lwip/src/api/sockets.c
fix bugs in network testcases which is reported by svace tool.
WGID : 257910
WGID : 282855
WGID : 218015
WGID : 218025
WGID : 226994
WGID : 227086
> network/testcases: fix bugs in network testcases

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
Move out TC_SUCCESS_RESULT() in the goto statement.
> apps/example/testcase : Fix mediaplayer and mediarecorder UTC

- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/framework/things_data_manager.h
Added Api for getting accesss token and uid of cloud So that when called dm_get_access_token()
and dm_get_uid() then it will not return NULL and will get the required values
> framework/st_things : Adding apis for getting access token and uid of cloud

- apps/examples/mediaplayer/BufferInputDataSource.cpp
- apps/examples/mediaplayer/BufferInputDataSource.h
- framework/src/media/utils/MediaUtils.cpp
Fix SVACE issues
WGID: 218104, 285370, 285371
> audio/media: Fix svace issues

- framework/include/dm/dm_connectivity.h
- framework/include/eventloop/eventloop.h
- framework/include/iotbus/iotbus_gpio.h
- framework/include/task_manager/task_manager.h
- framework/include/wifi_manager/wifi_manager.h
- os/Makefile.unix
- os/Makefile.win
- os/include/inttypes.h
- os/include/pthread.h
- os/include/stdlib.h
- os/include/time.h
update TizenRT version and APIs version to 2.0
> update TizenRT version

- framework/include/media/BufferOutputDataSource.h
- framework/include/media/FileOutputDataSource.h
- framework/include/media/OutputDataSource.h
- framework/include/media/SocketOutputDataSource.h
- framework/src/media/BufferOutputDataSource.cpp
- framework/src/media/FileOutputDataSource.cpp
- framework/src/media/Make.defs
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
- framework/src/media/OutputDataSource.cpp
- framework/src/media/OutputHandler.cpp
- framework/src/media/OutputHandler.h
- framework/src/media/SocketOutputDataSource.cpp
OutputHandler controls encoder and streambuffer which were handled by
OutputDataSource.
Related method and variables are moved to OutputHandler.
> media: Add OutputHandler

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
> apps/example/media: Add TC_SUCCESS_RESULT() statement

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
- framework/src/media/audio/audio_manager.c
1. Ioctl return ERROR if failed, so added errno to check return type
2. Fix utc properly.
> framework/media : Fix logic of set_audio_volume

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
Delete new line after parenthesis.
> apps/example/media: Fix coding rule violations

- framework/include/media/FocusChangeListener.h
- framework/include/media/FocusManager.h
- framework/include/media/FocusRequest.h
Add doxygen comment in FocusChangeListener, FocusManager, FocusRequest
> media: Add doxygen of media focus

- os/drivers/audio/Kconfig
- os/drivers/audio/Make.defs
- os/drivers/audio/cx20921.c
- os/drivers/audio/cx20921.h
- os/drivers/audio/tas5749.c
- os/drivers/audio/tas5749.h
- os/drivers/audio/tas5749reg.h
- os/drivers/audio/tas5749scripts.h
- os/include/tinyara/audio/cx20921.h
- os/include/tinyara/audio/tas5749.h
Support bew audio drivers, cx20921 and tas5749.
> drivers/audio: add new audio drivers, cx20921 and tas5749

- framework/src/task_manager/task_manager_core.c
- framework/src/task_manager/task_manager_internal.h
1. taskmgr_dealloc_cb_info will release information about stop and exit callback
2. taskmgr_handle_tcb will open taskmgr_drv and call ioctl for task manager
3. add close for g_taskmgr_fd
4. unify the macro of stop, exit and user data callback information
> framework/task_manager: Refactoring for task manager core

- apps/examples/wakaama_client/Makefile
- external/audiocodec/Makefile
- external/gmock/Makefile
- external/grpc/Makefile
- external/libopus/Makefile
- external/protobuf/Makefile
- external/swepd/Makefile
Remove unnecessary codes and modify to work on each folder structure
> external, apps: refactoring on Makefile

- framework/src/st_things/things_stack/things_stack.c
- framework/src/st_things/things_stack/utils/things_ping.c
1) When RESET operation starts, 'b_reset_continue_flag' flag is set to true. But it was not set to false after RESET.
This patch handles it.
Problem solved with this change: Ping thread gets created successfully after soft RESET.
2) Mutex used for ping list was not unlocked properly in few functions.
This patch handles it.
Problem solved with this change: Avoids deadlock.
> framework/st_things: Fix in Reset and Ping logic.

- external/grpc/src/core/lib/gpr/thd_posix.cc
- fix grpc thread naming issue
> external/grpc: fix grpc thread name

- apps/examples/task_manager_sample/action_manager.c
- apps/examples/task_manager_sample/user.c
As APIs of task manager are changed, APIs which were used in task manager sample were modified.
> examples/task_manager_sample: Modify the APIs used in the sample according to the modified APIs.

- tools/ttrace_parser/scripts/parse_dump.c
> Correct type error

- apps/examples/mtdpart/mtdpart_main.c
> type error

- framework/src/st_things/things_stack/framework/things_security_manager.c
> Correct English Spelling

- os/fs/driver/mtd/m25px/m25px.c
In some platforms m25px driver is used for winbond serial flash.
and M25P128 configuration is not compatible with Q type W25Q128JV.
This patch adds a valid configuration for W25Q128x serial flash
> driver/mtd : correct W25Q128JV configuration in m25px driver

- external/curl/smtp.c
detailed description is in https://github.com/curl/curl/commit/ba1dbd78e5f1ed67c1b8d37ac89d90e5e330b628
> external/curl: apply patch that is reported in avas

- apps/system/utils/netcmd_netmon.c
- Add wifi command to extract status and conneciton info
> app/utils/netcmd_netmon: Add wifi command to extract wifi info

- apps/examples/testcase/ta_tc/media/utc/Make.defs
- apps/examples/testcase/ta_tc/media/utc/utc_media_main.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp
This is the skeletion of SpeechDetector testcase
> apps/examples/testcase: Add SpeechDetector tc

- framework/src/media/utils/MediaUtils.cpp
1. Fix missed free
2. Improve log
> framework/media : Fix leakage in header_parsing

- framework/src/media/voice/SpeechDetector.cpp
These errata make SpeechDetector not be init
> media: Fix errata in SpeechDetector::init

- framework/include/media/voice/SpeechDetector.h
- framework/src/media/voice/EndPointDetector.h
- framework/src/media/voice/HardwareEndPointDetector.cpp
- framework/src/media/voice/HardwareEndPointDetector.h
- framework/src/media/voice/SoftwareEndPointDetector.cpp
- framework/src/media/voice/SoftwareEndPointDetector.h
- framework/src/media/voice/SpeechDetector.cpp
Since SpeechDetector::initEndPointDetect waits EPD, split it into init
and start
> media: Add SpeechDetector::startEndPointDetect

- docs/HowToAddnewBoard.md
Previous is not enough to know how to add a new board.
This commit describes details.
> docs: rewrite HowToAddnewBoard.md

- os/include/net/lwip/sockets.h
- os/include/sys/socket.h
- Add msghdr structure in os/include/sys/socket.h following POSIX
- Remove dependency of CONFIG_NET_SOCKET on recvmsg and sendmsg
> os/sys/socket: Add msghdr structure in socket.h

- docs/HowToUseSmartFS.md
The following are the changes:
* Updated in accordance to latest artik05x.
* Fixed spacing & grammatical errors.
> docs: Update HowToUseSmartFS.md

- apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp
- framework/src/media/voice/SoftwareEndPointDetector.cpp
- framework/src/media/voice/SoftwareKeywordDetector.cpp
- framework/src/media/voice/SpeechDetector.cpp
add utc_media_SpeechDetector::startKeywordDetect,
SpeechDetector::startEndPointDetect utc
> media: Add SpeechDetector startKD, startEPD utc

- framework/src/media/voice/HardwareKeywordDetector.cpp
- framework/src/media/voice/HardwareKeywordDetector.h
Check time to implement timeout.
Remove pthread.
> media: Check timeout in startKeywordDetect

- apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp
- framework/include/media/voice/SpeechDetector.h
- framework/src/media/voice/EndPointDetector.h
- framework/src/media/voice/HardwareEndPointDetector.cpp
- framework/src/media/voice/HardwareEndPointDetector.h
- framework/src/media/voice/SoftwareEndPointDetector.cpp
- framework/src/media/voice/SoftwareEndPointDetector.h
- framework/src/media/voice/SpeechDetector.cpp
> media: Remove SpeechDetector::processEPDFrame

- apps/examples/testcase/ta_tc/media/utc/utc_media_speechdetector.cpp
- framework/include/media/voice/SpeechDetector.h
- framework/src/media/voice/SpeechDetector.cpp
SpeechDetector::deinitXXX returns false if it is already deinit
> media: Modify SpeechDetector deinit return value

- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- framework/src/media/voice/HardwareEndPointDetector.cpp
- framework/src/media/voice/HardwareKeywordDetector.cpp
start_stream_in_device_process, stop_stream_in_device_process have type paramter
> media: Add device_process_subtype_t parameter

- framework/src/media/MediaPlayerImpl.cpp
> framework/media: Add onPlaybackStopped in notifyObserver.

- framework/src/media/audio/audio_manager.c
while and sleep make timing issue
> media: Wait 1 sec for receiving mq

- framework/include/media/voice/SpeechDetector.h
These comments are needed to use doxygen
> media: Add doxygen comment in SpeechDetector.h

- os/kernel/Kconfig
Add description about a unit of time constant values in cpuload
> kernel/cpuload: Add description about a unit of time constant in cpuload

- os/include/stdbool.h
Fix a minor enumeration issue.
> os/include: Fix documentation of CONFIG_C99_BOOL8 in stdbool.h

- apps/examples/st_things/light/sample_light_things.c
- apps/examples/st_things/light/sample_light_user.c
- framework/include/st_things/st_things.h
- framework/src/st_things/st_things.c
Modify example of sample_light_things to send push notification to cloud and user receive a pop up message
> framework/st_things : Add push notification to cloud in st things .

- os/drivers/audio/audio_null.c
It is better than using while-sleep statement
> drivers/audio: Use sem to start process thread

- docs/HowToUseLWIP.md
- docs/Porting_Guide.md
- Add LWIP porting guide document
> docs: Add LWIP porting guide

- framework/src/wifi_manager/wifi_manager.c
- framework/src/wifi_manager/wifi_profile.c
- Copy SSID and PASSPHRASE up to maximum value, and put NULL at the maximum
> framework/wifi_manager: Enhance string management

- lib/libc/README.txt
End of the line 9 : kerne -->kernel
>  lib/libc/README.txt : fix a spelling error

- tools/ramdump/gui_dumpParser.py
This scripts catch addr from "[<addr>]" and run addr2line
> tools/ramdump: Add callstack log parsing feature

- docs/HowToConfirmNetworkPorting.md
- docs/Porting_Guide.md
- Add network porting guide how to test the network performance to verify the successful network stack porting
> docs: How To Test Network Performance

- apps/examples/task_manager_sample/action_manager.c
- apps/examples/task_manager_sample/task_manager_sample_main.c
- Fix typos in log (successfully)
> app/task_manager_sample : Fix typos in log

- framework/src/media/voice/EndPointDetector.h
- framework/src/media/voice/HardwareEndPointDetector.cpp
- framework/src/media/voice/HardwareEndPointDetector.h
- framework/src/media/voice/HardwareKeywordDetector.cpp
- framework/src/media/voice/HardwareKeywordDetector.h
- framework/src/media/voice/KeywordDetector.h
- framework/src/media/voice/SoftwareEndPointDetector.cpp
- framework/src/media/voice/SoftwareEndPointDetector.h
- framework/src/media/voice/SoftwareKeywordDetector.cpp
- framework/src/media/voice/SoftwareKeywordDetector.h
- framework/src/media/voice/SpeechDetector.cpp
negative timeout means infinite timeout
> media/voice/SpeechDetector: Get negative timeout

- apps/examples/testcase/ta_tc/wifi_manager/itc/itc_wifi_manager_main.c
bipin.k created Pull Request for WifiManager ITC development
> [TA_TC WifiManager]development of ITC testcase

- apps/examples/cxxtest/cxxtest_main.cxx
Add thread::operator=, thread::joinable, thread::join
sample examples.
> apps/cxxtest: add sample test for threads

- framework/src/task_manager/task_manager_core.c
1. Reduce type castings
Preveously there were too many type castings which deteriorate readablity.
Therefore the following modifications have been applied.
- Remove unnecessary type casting.
- Modify the input of internal function to remove type castings.
2. Redefine Defines and applied
Previously, Defines included some type castings, therefore these Defines was not able to apply other cases.
As type castings were removed, new Defines can be applied generally.
Following Defines have been redefined and applied to task_manager_core.c.
- #define CB_MSG_OF(X)       (X)->cb_data->msg
- #define CB_MSGSIZE_OF(X)   (X)->cb_data->msg_size
(Previous Defines)
- #define CB_FUNC_OF(X)      ((tm_termination_info_t *)X)->cb
- #define CB_DATA_OF(X)      ((tm_termination_info_t *)X)->cb_data
- #define …
> framework/task_manager: Apply more general Defines

- apps/examples/testcase/le_tc/network/itc_net_connect.c
> [ITC] Fixing mismatch in data bytes sent and received between server and client

- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- Channel resampling is added for the case that a requested channel and a supported channel are different.
- Buffer size calculation logic is changed to use a requested channel.
> framework/media: Add rechanneling

- framework/src/media/voice/HardwareEndPointDetector.cpp
- framework/src/media/voice/HardwareEndPointDetector.h
- framework/src/media/voice/HardwareKeywordDetector.cpp
- framework/src/media/voice/HardwareKeywordDetector.h
- framework/src/media/voice/SpeechDetector.cpp
> media/voice: Get I2S card id and device id

- os/drivers/audio/Kconfig
- os/drivers/audio/alc5658.c
- os/drivers/audio/alc5658.h
- os/drivers/audio/audio_null.c
- os/drivers/audio/cx20921.c
- os/drivers/bch/bchlib_cache.c
- os/drivers/rtc.c
os/drivers/audio/alc5658.c : Modify a typo …
os/drivers/audio/alc5658.h : Modify a typo …
os/drivers/audio/Kconfig : Modify a typo …
os/drivers/audio/cx20921.c : Modify a typo …
os/drivers/audio/audio_null.c : Modify a typo …
os/drivers/bch/bchlib_cache.c : Modify a typo …
os/drivers/rtc.c : Modify a typo …
Thank you~! Have a good day!
> Typo codingrule

- framework/src/st_things/things_stack/cloud/cloud_manager.c
1. Fixes indentation with spaces.
2. The tab cannot be placed middle of lines.
> framework/st_things: making the code align.

- apps/examples/speech_detector_test/speech_detector_test_main.cpp
This example provides the following scenarios:
1. Detect keyword
2. Record
3. Detect Endpoint
4. Play recorded file
> examples/speech_detector_test: Improve sd example

- os/fs/driver/mtd/smart.c
- os/include/tinyara/fs/fs.h
- Weird words and sentences are modified.
> os/fs: Fix typos in comments.

- docs/HowToUseTinyAlsa.md
Fix misspelling : TinyAsla -> TinyAlsa
> docs: Fix misspelling

- framework/src/st_things/things_stack/framework/things_req_handler.c
- framework/src/st_things/things_stack/framework/things_req_handler.h
- framework/src/st_things/things_stack/things_def.h
Stop SoftAP request from ST Cloud (Through POST request) is neither used nor fully implemented.
So I am removing the code related to it.
> framework/st_things: Remove unused "Stop SoftAP from Cloud" feature.

- framework/include/wifi_manager/wifi_manager.h
- Modifiy contents of docs for wifi_manager_connect_ap and wifi_manager_connect_ap_config
> framework/wifi_manager: Revise API documentation

- os/net/Kconfig
- Modify configuration description
External DHCP -> Default DHCP
Internal DHCP -> Optional LwIP DHCP
> external/DHCP: Modify description of configuration

- apps/examples/fota_sample/fota_sample.c
- apps/examples/ftpc/ftpc_cmds.c
- apps/examples/kernel_sample/kernel_sample_main.c
- apps/examples/libcoap_client/libcoap-client.c
- apps/examples/sensorbd_demo/examples/i2c_tcs34725.c
- apps/examples/task_manager_sample/action_manager.c
- apps/examples/task_manager_sample/task_manager_sample_main.c
- apps/examples/telnetd/telnetd.c
- framework/src/st_things/things_stack/cloud/cloud_manager.c
- os/drivers/audio/Kconfig
- os/drivers/audio/alc5658.c
- os/drivers/audio/alc5658.h
- os/drivers/audio/audio_null.c
- os/drivers/audio/cx20921.c
- os/drivers/bch/bchlib_cache.c
- os/drivers/rtc.c
sync with typo_codingrule branch to push fixing typos and fixing violations of coding rules
> fix typos and fixing violations of coding rules

- apps/system/utils/netcmd_netmon.c
- Print messages when the STA is trying to reconnect
> apps/netmon: Add print messages for reconnecting status

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
utc_media_MediaRecorder_getMaxVolume_p tests getMaxVolume()
> media/utc: Fix getMaxVolume utc

- apps/examples/speech_detector_test/speech_detector_test_main.cpp
- framework/include/media/voice/SpeechDetector.h
- framework/src/media/voice/EndPointDetector.h
- framework/src/media/voice/HardwareEndPointDetector.cpp
- framework/src/media/voice/HardwareEndPointDetector.h
- framework/src/media/voice/SoftwareEndPointDetector.cpp
- framework/src/media/voice/SoftwareEndPointDetector.h
- framework/src/media/voice/SpeechDetector.cpp
detectEndPoint returns whether epd is triggered.
> media/voice: Add detectEndPoint

- framework/src/media/HttpStream.cpp
- framework/src/media/voice/HardwareEndPointDetector.cpp
1. HardwareEndPointDetector.cpp
Missing return value assignment.
2. HttpStream.cpp
Not initialize class member: mInitializedFlag
@Taejun-Kwon
> framework/media: Fix issues svace reported

- apps/examples/mediarecorder/mediarecorder_main.cpp
- framework/src/media/FileOutputDataSource.cpp
- framework/src/media/OutputHandler.cpp
- framework/src/media/utils/MediaUtils.cpp
- framework/src/media/utils/MediaUtils.h
The wav file dose not require a encoder.
Just write a wav header at the top of the file.
> framework/media : Add wav format to media record list.

- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
remove meaningless annotations.
> media: remove unnecessary annotations

- framework/src/media/MediaPlayerImpl.cpp
This TODO comment was added in #2011 and completed in #2088
> framework/media: Remove complete TODO comment

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediaplayer.cpp
- framework/include/media/MediaPlayer.h
- framework/src/media/MediaPlayer.cpp
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
isPlaying() checks whether MediaPlayer is playing
> framework/media: Add MediaPlayer.isPlaying API

- os/crypto/blake2s.c
- os/crypto/random_pool.c
[SPC_M_OPR] space required after that ','
[IDT_M_TAB] please, no spaces at the start of a line
> crypto: Fix coding rule violation

- framework/src/arastorage/index_bplustree.c
1. get_next, unset lock for abnormal case
2. get_next, update cache range update get new bucket
3. modify_cache, unlock mutex before return for exceptional case
@Taejun-Kwon @jeongarmy
> framework/arastorage: fix logic issue and lock release for bptree 

- apps/system/init/init.c
- framework/include/media/media_init.h
- framework/src/media/Make.defs
- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- framework/src/media/media_init.c
media_init initialize media framework
> framework/media: Add media_init

- framework/src/media/utils/MediaUtils.cpp
'convertLittleEndian' function is not necessary.
> framework/media: remove unused function.

- apps/examples/testcase/ta_tc/media/utc/utc_media_mediarecorder.cpp
- framework/include/media/MediaRecorder.h
- framework/src/media/MediaRecorder.cpp
- framework/src/media/MediaRecorderImpl.cpp
- framework/src/media/MediaRecorderImpl.h
Add API to check if it is currently recording.
> framework/media: Add isRecording API to check recording status

- apps/examples/setjmp/setjmp_longjmp_test.c
setjmp/setjmp_longjmp_test.c: add missing variables in function
add missing variables in function at line 144, 158.
> setjmp/setjmp-longjmp-test.c: add missing variables in function

- framework/src/media/FileOutputDataSource.cpp
- framework/src/media/utils/MediaUtils.cpp
1. fix memory leaked issue.
2. fix strcpy overflow issue, using safe strncpy.
Above issues are reported by SVACE
3. move fclose from createWavHeader() to FileOutputDataSource::open()
4. ffush stream buffer before ftell to get correct file size
@Taejun-Kwon @YiHyunJin
> framework/media: Fix issues regarding wave header

- framework/include/task_manager/task_manager.h
> framework/task_manager: Modify doxygen comment

- build/configs/artik05x/artik05x_download.sh
ARTIK download script uses hardcoded partition name for ALL options.
Since the partition names are part of Kconfig file, it is NOT correct
to use hard coded values. This commit reads the partition names
from .config file if present, otherwise it reads the default parttion
names from Kconfig file.
> Fix ARTIK download script.

- apps/examples/testcase/ta_tc/arastorage/utc/utc_arastorage_main.c
- framework/src/arastorage/index_bplustree.c
- framework/src/arastorage/index_manager.c
- framework/src/arastorage/relation.c
add delete function for bplustree algorithm
apply it to tuple remove processing
@Taejun-Kwon @jeongarmy
> framework/arastorage: enhance bptree indexing feature

- os/dbuild.sh
- before run a new container of docker, check the latest version of image from docker hub
> dbuild: Add docker command to maintain latest version

- .travis.yml
- Add protection branch in CI process
- disable submodules update to avoid time out
> travis: Adding new branch in CI

- os/dbuild.sh
- dbuild.sh will use specific docker version to maintain build env.
> dbuild: Add docker image version to maintain latest ver.

- framework/include/media/stream_info.h
- framework/src/media/Make.defs
- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/audio_manager.h
- framework/src/media/media_init.c
- framework/src/media/stream_info.c
> framework/media: Add stream_info

- apps/examples/testcase/ta_tc/media/utc/utc_media_focusmanager.cpp
- apps/examples/testcase/ta_tc/media/utc/utc_media_focusrequest.cpp
- framework/include/media/FocusRequest.h
- framework/src/media/FocusRequest.cpp
FocusRequest should own its stream_info
> framework/media: Add FocusRequest.setStreamInfo()

- apps/examples/testcase/le_tc/kernel/tc_sched.c
- os/kernel/sched/sched_waitid.c
- os/kernel/sched/sched_waitpid.c
- testcase/kernel: Fix wrong condition for checking result in testcase for waitid with P_ALL
- testcase/kernel: Fix wrong idtype for waitpid with P_PID
- kernel/sched: Add missing logic for verifying idtype
> kenel, testcase: Fix wrong usages in testcases and Add missing logics for waitid

- framework/include/media/MediaPlayer.h
- framework/src/media/MediaPlayer.cpp
- framework/src/media/MediaPlayerImpl.cpp
- framework/src/media/MediaPlayerImpl.h
MediaPlayer should hold stream_info
> framework/media: Add MediaPlayer::setStreamInfo

- apps/examples/mediaplayer/mediaplayer_main.cpp
FocusRequest needs to set stream_info
> apps/mediaplayer: Set stream_info

- external/curl/curl_config.h
> Add a copyright in curl_config.h

- os/binfmt/elf.c
- os/binfmt/libelf/libelf_bind.c
- os/binfmt/libelf/libelf_init.c
- os/binfmt/libelf/libelf_load.c
- os/binfmt/libelf/libelf_read.c
- os/include/elf32.h
> os/binfmt : fix coding rules

- docs/HowToUseLWIP.md
- Add an explanation how to control flags depending on driver's status, and
how to manage pbuf for input/output.
> docs/HowToUseLWIP: Add an explanation how to control flags and pbuf

- external/mbedtls/timing.c
- Change MBED_TIZNERT to MBED_TIZENRT
> external/mbedtls: Modify a typo of MBED_TIZENRT

- apps/system/utils/netcmd_ping.c
lwip_getaddrinfo is a kernel API, use getaddrinfo.
> Replace lwip_getaddrinfo with getaddrinfo

- external/error_report/error_report.c
At present, error report module uses REALTIME clock for getting timestamps. The recorded values can be affected by a change of time base during runtime (on response from NTP server, for example). As a fix, we choose relative timestamps instead.
> external/error_report: Fix timestamp, use MONOTONIC instead of REALTIME

- os/fs/driver/mtd/smart.c
- os/include/tinyara/fs/mtd.h
fs/mtd : Increase erasesize and blocksize of mtd_geometry_s
> fs/mtd : Increase erasesize and blocksize of mtd_geometry_s

- os/Kconfig
- os/arch/arm/src/armv7-r/mpu.h
- os/arch/arm/src/s5j/mpu-reg.h
- os/arch/arm/src/s5j/s5j_boot.c
- os/include/tinyara/mm/mm.h
- os/mm/mm_heap/Make.defs
- os/mm/mm_heap/mm_partition_mgr.c
Add configs for Application Binary Separation
Implement RAM partition manager for App binary separation
MPU configuration changes
> App binary separation Memory partitions

- apps/examples/testcase/le_tc/kernel/tc_roundrobin.c
- apps/examples/testcase/le_tc/kernel/tc_semaphore.c
- os/drivers/testcase/kernel_testcase_drv.c
- os/include/tinyara/testcase_drv.h
Tset sem_tickwait through the virtual driver.
> testcase/kernel : Use a virtual driver to test kernel internal API

- framework/src/st_things/things_stack/framework/things_data_manager.c
1. strlen(NULL) cause crash.
2. in case of debugging, print THINGS_ERROR as a tag string cause crash.
@Hyunjun85
> framework/st_things: Fix issues to avoid crash

- apps/examples/testcase/le_tc/tcp_tls/tcp_tls_stress.c
- apps/examples/wifi_manager_sample/wm_test_stress.c
- external/include/stress_tool/st_perf.h
- Modify ST_EXPECT to ST_EXPECT_EQ
- Add ST_EXPECT_EQ2 for handling two types of return values
- Modify corresponding applications using stress test tool
> external/stress_tool: Add ST_EXPECT_EQ2 and ST_EXPECT_NEQ

- os/board/artik05x/userspace/up_userspace.c
This patch adds config check for system pre-application init
Signed-off-by: Nilabh <n.shant@partner.samsung.com>
> artik05x/userspace: Add config dependency (CONFIG_SYSTEM_PREAPP_INIT)

- os/tools/mkheader.py
Python script generates header for Binary manager.
header information :
/ header size (2byte) / binary type (2byte) / binary size (4byte)
/ Binary name (16byte) / Binary version (12byte)
/ Kernel version (8byte) / Jump address (4byte)
> os/tools : Introduce a binary header generator 'mkheader.py'

- apps/examples/security_test/Kconfig
- apps/examples/security_test/Kconfig_ENTRY
- apps/examples/security_test/hal/Kconfig
- apps/examples/security_test/hal/Kconfig_ENTRY
- apps/examples/security_test/hal/Make.defs
- apps/examples/security_test/hal/Makefile
- apps/examples/security_test/hal/hal_auth_test.c
- apps/examples/security_test/hal/hal_crypto_test.c
- apps/examples/security_test/hal/hal_keymgr_test.c
- apps/examples/security_test/hal/hal_ss_test.c
- apps/examples/security_test/hal/hal_test.h
- apps/examples/security_test/hal/hal_test_main.c
- apps/examples/security_test/hal/hal_test_utils.c
- apps/examples/security_test/hal/hal_test_utils.h
- apps/examples/security_test/see_api/Kconfig
- apps/examples/security_test/see_api/Kconfig_ENTRY
- apps/examples/security_test/see_api/Make.defs
- apps/examples/security_test/see_api/Makefile
- apps/examples/security_test/see_api/see_test_main.c
- os/arch/arm/src/s5j/Make.defs
- os/arch/arm/src/s5j/sss/security_hal_wrapper.c
- os/include/tinyara/security_hal.h
- Provide a generic format of security_hal (security_hal.h)
apps/examples/security_test: Refactor security_test example features
- Add security_hal testcases
- Refactor security test in apps/examples/security_test for see_api testcases
- os/arch/s5j: Add a security hal wrapper for Artik isp
> Add security_hal features

- external/esp_idf_port/esp32/Kconfig
- external/esp_idf_port/esp32/Makefile
- external/esp_idf_port/esp32/spi_ram/esp_heap_caps.h
- external/esp_idf_port/esp32/spi_ram/heap_caps.c
- external/esp_idf_port/esp32/spi_ram/spiram.c
- external/esp_idf_port/esp32/spi_ram/spiram_psram.c
- external/esp_idf_port/esp32/spi_ram/spiram_psram.h
- os/arch/xtensa/src/esp32/esp32_allocateheap.c
- os/arch/xtensa/src/xtensa/xtensa.h
- os/arch/xtensa/src/xtensa/xtensa_initialize.c
- os/board/esp32_devkit/src/esp32_boot.c
enable spiram on ESP, and add it to TizenRT mm
@jeongchanKim @sunghan-chang
> external/esp_idf_port: enable spiram on ESP

- os/binfmt/binfmt_loadbinary.c
This commit contains following changes:
- Allocate RAM partition before loading application
- Use the application's heap in its RAM partition to load elf sections
- Free RAM partition during unload or error scenarios
These changes are enabled only if CONFIG_APP_BINARY_SEPARATION is set.
Aligning with patch #2864
> Modify load_binary api to use RAM partitions

- apps/system/utils/fscmd.c
remove commands that are not currently in use
> apps/utils/fs : remove mkrd and mksmartfs commands

- apps/examples/testcase/le_tc/kernel/tc_libc_misc.c
- lib/libc/misc/lib_crc32.c
The crc32 function was not operate. So modified to operate.
> libc/misc : Fix crc32 algorithm

- apps/examples/syscall_performance/Kconfig
- apps/examples/syscall_performance/Kconfig_ENTRY
- apps/examples/syscall_performance/Make.defs
- apps/examples/syscall_performance/Makefile
- apps/examples/syscall_performance/README.txt
- apps/examples/syscall_performance/syscall_performance_main.c
Usage -
- For :
fun(args...);
- Make call like this:
tc_performance(fun, number_arguments, args...);
> Variadic macro for comparing System/Function call performance

- framework/src/wifi_manager/slsi_wifi_utils_lwnl80211.c
- os/drivers/lwnl/Kconfig
- os/drivers/lwnl/lwnl80211.c
- os/drivers/lwnl/slsi_drv.c
- os/include/debug.h
- os/include/tinyara/lwnl/lwnl80211.h
- os/include/tinyara/lwnl/slsi_drv.h
- Add lwnl80211 debug called nldbg/nlvdbg when CONFIG_DEBUG_LWNL80211_ERROR/INFO
- Add SLSI driver's debug called sddbg/sdvdbg when CONFIG_DEBUG_LWNL80211_SLSI_ERROR/INFO
- Remove wifi util's own debug options WU_LOG and change them to ndbg
> include/debug: Add lwnl80211 and slsi driver logging

- os/tools/mkbinheader.py
1. Static RAM size : Extract the value from size command with elf in linux
2. Dynamic RAM size : User input
> os/tools/mkbinheader : Add calculating the RAM size

- framework/src/media/voice/SoftwareEndPointDetector.cpp
- framework/src/media/voice/SoftwareEndPointDetector.h
EPD doesn't detect speech -> no-speech, but detects no-speech.
Add holdTime to detect no-speech for a period of time.
> framework/media: Modify SW EPD logic

- framework/src/media/utils/MediaUtils.cpp
The logic to find header of mp3 is incorrect
> framework/media: fix mp3 header parsing

- docs/HowToPortTizenRTOnWiFiChipset.md
- Add a document how to add lwnl80211 interface, considering user and kernel process seperation
> docs/HowToPortTizenRTOnWiFiChipset.md: Add lwnl80211 implementation

- apps/examples/elf/micomapp/Makefile
- apps/examples/elf/wifiapp/Makefile
- os/kernel/binary_manager/binary_manager.h
- os/kernel/binary_manager/binary_manager_load.c
The binary manager should check the checksum before loading.
> kernel/binary_manager : Use logic to check checksum with crc

- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/system/utils/fscmd.c
- Relace kernel-level mountpoint functions into new ones for binary separation.
> app/system: Add user-level mountpoint functions

- apps/include/system/binary_update.h
- apps/system/update/Kconfig
- apps/system/update/Make.defs
- apps/system/update/Makefile
- apps/system/update/binary_update.c
- os/include/tinyara/binary_manager.h
- os/kernel/binary_manager/binary_manager.c
- os/kernel/binary_manager/binary_manager.h
- os/kernel/binary_manager/binary_manager_getinfo.c
- os/kernel/binary_manager/binary_manager_load.c
Support api for binary update.
load_new_binary :
This function is a function that loads a new binary.
get_binary_info :
This function get with binary information.
get_binary_info_all :
This function get with all binary information.
clean_binary_info_list :
This function clears binary information list.
> system/update : Add support of binary update

- apps/examples/mediaplayer/mediaplayer_main.cpp
- framework/src/media/audio/audio_manager.c
- framework/src/media/audio/resample/samplerate.c
- Refine resampleing logic in src_simple().
- Update audio manage code about rechanneling.
- Update mediaplayer example code for easy test.
@Taejun-Kwon @xixidodo
> framework/media: call src_simple() API for rechanneling in audio manager

- .travis.yml
- add imxrt1020/1050 board for build test.
> travis: add imxrt1020/1050 board configurations

- framework/include/security/security_auth.h
- framework/include/security/security_common.h
- framework/src/seclink/seclink.c
- framework/src/security/security_auth.c
- framework/src/security/security_common.c
- framework/src/security/security_internal.h
- framework/src/security/security_utils.c
- Add or modify security authentication APIs
> framework/security_api: Add security_auth APIs

- apps/examples/elf/wifiapp/wifiapp.c
- apps/examples/mpu/mpu_test.c
- apps/system/binary_update/binary_update.c
- apps/system/init/init.c
- os/arch/arm/src/armv7-m/up_mpu.c
- os/arch/arm/src/imxrt/imxrt_allocateheap.c
- os/arch/arm/src/imxrt/imxrt_start.c
- os/arch/arm/src/imxrt/mpu-reg.h
- os/binfmt/binfmt_exec.c
- os/binfmt/binfmt_loadbinary.c
- os/kernel/binary_manager/binary_manager_load.c
- os/mm/mm_heap/mm_partition_mgr.c
Fix build warnings during build of loadable_elf_apps and
nxp_demo_protected configurations.
> Fix build warnings

- apps/examples/testcase/le_tc/filesystem/Kconfig
- apps/examples/testcase/le_tc/filesystem/Make.defs
- apps/examples/testcase/le_tc/filesystem/fs_main.c
- apps/examples/testcase/le_tc/filesystem/tc_fs_tmpfs.c
Add a testcase to cover the code of tmpfs mountpt operations.
> apps/example/testcase/filesystem: Add tmpfs Mountpt operations testcase

- os/drivers/analog/Kconfig
- os/drivers/analog/adc.c
- os/include/tinyara/analog/adc.h
- update poll notify function for ADC.
> drivers/analog: update poll event for ADC

- framework/include/iotbus/iotbus_adc.h
- framework/include/iotbus/iotbus_error.h
- framework/include/iotbus/iotbus_pwm.h
- framework/include/iotbus/iotbus_uart.h
- framework/src/iotbus/Kconfig
- framework/src/iotbus/Make.defs
- framework/src/iotbus/iotbus_adc.c
- framework/src/iotbus/iotbus_gpio.c
- framework/src/iotbus/iotbus_pwm.c
- os/drivers/pwm.c
- os/include/tinyara/pwm.h
- add iotbus_pwm APIs : iotbus_pwm_set_idle, iotbus_pwm_set_duty_cycle_in_integer
- implement iotbus_adc
> framework/iotbus: implement iotbus_adc/iotbus_pwm APIs

- apps/examples/security_test/linux/SConstruct
- apps/examples/security_test/linux/config.h
- apps/examples/security_test/linux/main.c
- apps/examples/security_test/linux/run_gcov.py
- apps/examples/security_test/security_api/security_api_auth_test.c
- apps/examples/security_test/security_api/security_api_crypto_test.c
- apps/examples/security_test/security_api/security_api_keymgr_test.c
- apps/examples/security_test/security_api/security_api_ss_test.c
- apps/examples/security_test/security_api/security_api_test.c
- apps/examples/security_test/security_api/security_api_utils.c
- framework/src/seclink/seclink.c
- framework/src/security/security_auth.c
- framework/src/security/security_common.c
- framework/src/security/security_crypto.c
- framework/src/security/security_internal.h
- framework/src/security/security_keymgr.c
- framework/src/security/security_ss.c
- framework/src/security/security_utils.c
- os/drivers/seclink/seclink_drv_linux.c
- os/drivers/seclink/seclink_drv_utils.h
- os/include/tinyara/seclink.h
- os/include/tinyara/security_hal.h
- os/se/virtual/hal_virtual.c
security: fix build warning
security: Add building security on Linux
> build security API on linux 

- os/arch/arm/src/imxrt/Make.defs
- os/arch/arm/src/imxrt/imxrt_gpt.c
- os/arch/arm/src/imxrt/imxrt_gpt.h
- os/arch/arm/src/imxrt/imxrt_pit.c
- os/arch/arm/src/imxrt/imxrt_pit.h
- os/arch/arm/src/imxrt/imxrt_qtmr.c
- os/arch/arm/src/imxrt/imxrt_qtmr.h
> Add Timer API for imxrt

- framework/include/iotbus/iotbus_common.h
- framework/include/iotbus/iotbus_error.h
- framework/include/iotbus/iotbus_uart.h
- framework/src/iotbus/Make.defs
- framework/src/iotbus/iotapi_dev_handler.c
- framework/src/iotbus/iotapi_dev_handler.h
- framework/src/iotbus/iotbus_adc.c
- framework/src/iotbus/iotbus_uart.c
- os/drivers/Kconfig
- os/drivers/Makefile
- os/drivers/iotdev/Kconfig
- os/drivers/iotdev/Make.defs
- os/drivers/iotdev/iotdev.c
- os/include/tinyara/iotdev.h
- os/include/tinyara/serial/serial.h
- os/kernel/init/os_start.c
- add iotbus uart APIs(async_write, set_interrupt)
- implement interrupt handler.
> framework/iotbus: implement iotbus uart APIs

- .gitignore
- os/arch/arm/src/imxrt/imxrt_gpt.h
- os/arch/arm/src/imxrt/imxrt_pit.h
- os/arch/arm/src/imxrt/imxrt_qtmr.c
- os/arch/arm/src/imxrt/imxrt_qtmr.h
- os/drivers/timer.c
ERROR: [IDT_M_TAB] code indent should use tabs where possible
ERROR: [IDT_M_TAB] please, no spaces at the start of a line
> arch/imxrt: fix violations of coding rules

- apps/examples/testcase/ta_tc/systemio/utc/Kconfig
- apps/examples/testcase/ta_tc/systemio/utc/utc_spi.c
- framework/src/iotbus/iotbus_spi.c
- os/arch/arm/src/imxrt/Kconfig
- os/arch/arm/src/imxrt/imxrt_lpspi.c
- os/board/imxrt1050-evk/src/imxrt_boot.c
- Call up_spilinitialze and register spi dirver
> arch/arm/imxrt: Add spi initialization logic

- os/arch/arm/src/imxrt/imxrt_gpio.c
- os/arch/arm/src/imxrt/imxrt_gpio_lowerhalf.c
- os/board/imxrt1050-evk/src/imxrt_boot.c
- fix gpio read reg value
- add gpio pull operation
> arch/arm/imxrt: implement gpio read/pull opreation

- apps/examples/testcase/le_tc/kernel/tc_libc_timer.c
Add libc timer testcase to improve coverage
> apps/examples/testcase: Add libc timer testcase

- apps/examples/elf/micomapp/Makefile
- apps/examples/elf/wifiapp/Makefile
This patch modifies the app binary path.
> elf/apps/Makefile: Modify binary path in app Makefiles

- os/arch/arm/src/imxrt/imxrt_ehci.c
- os/arch/arm/src/imxrt/imxrt_usbhost.c
- Modify syslog to udbg
- Modify uinfo and uerr self-defined printf definitions to udbg
> arch/imxrt: Modify self-defined printf and syslog

- apps/examples/testcase/Kconfig
- Fix security utc Kconfig sourcing directoy
> apps/examples: Modify Kconfig of examples for security utc

- os/Kconfig.debug
- os/drivers/timer.c
- os/include/debug.h
Let's define debug feature in debug stubs.
> debug/timer: move definitions of timer debug configs to debug

- build/configs/imxrt1050-evk/loadable_elf_apps/defconfig
> configs/imxrt1050-evk/loadable_elf_apps: enable SDRAM_PRIMARY and SPI

- os/binfmt/binfmt_loadbinary.c
- os/include/tinyara/binary_manager.h
- os/include/tinyara/binfmt/binfmt.h
- os/kernel/binary_manager/binary_manager.h
- os/kernel/binary_manager/binary_manager_load.c
This commit have included the necessary information in the structure
for the binary load.
> kernel/binary_manager : Use the structure for load_binary

- framework/src/st_things/things_stack/utils/things_network.c
- framework/src/st_things/things_stack/utils/things_ping.c
- Change a stack object `is_wifi_retry_connect` to be static
- Update logic to make ping thread desrtoyed promptly
>  framework/st_things: Improve st_things stack robustness

- os/arch/arm/src/imxrt/chip/imxrt_wdog.h
- os/arch/arm/src/imxrt/imxrt_wdog.c
- os/arch/arm/src/imxrt/imxrt_wdog.h
1. add watchdog api
2. add hw reset function
> Add Watchdog for iMXRT

- framework/include/iotbus/iotbus_adc.h
- framework/include/iotbus/iotbus_spi.h
- framework/src/iotbus/iotbus_adc.c
- framework/src/iotbus/iotbus_spi.c
- add timeout param in adc_get_sample
- add set_config API in iotbus_spi
> framework/iotbus: update iotbus spi/adc API

- external/esp_idf_port/esp32/esp32_wifi_utils.c
In some situation, esp32 wifi will connect AP failed for the first time,
Giving chance to reconnect will improve this case.
@pilseob.kang
@sh.byeon
> external/esp_idf_port: Add retry times when esp32 wifi disconnected.

- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/logging/things_logger.c
- framework/src/st_things/things_stack/utils/things_hashmap.c
- framework/src/st_things/things_stack/utils/things_network.c
Applying svace result to provide code quality.
> framework/st_things: fix error and warnings.

- apps/examples/elf/wifiapp/wifiapp.c
Add missing logics for exiting from switch context and while loop.
> examples/elf: Add missing logics for exiting from switch context and while loop

- os/arch/arm/src/imxrt/Kconfig
- os/arch/arm/src/imxrt/Make.defs
- os/arch/arm/src/imxrt/imxrt_gpt.c
- os/arch/arm/src/imxrt/imxrt_gpt.h
- os/arch/arm/src/imxrt/imxrt_timer_lowerhalf.c
- os/board/imxrt1050-evk/src/imxrt_boot.c
- os/include/tinyara/timer.h
This is mandatory to use HW timer in user context.
> arch/imxrt/gpt: add timer interface

- apps/examples/elf/micomapp/messaging.c
- os/kernel/messaging/messaging.c
- apps/examples/elf : Add break in wifiapp.c and change priority in /micomapp/Messaging.c
- os/kernel/messaging : modify messaging_append_receiver
> apps/examples/elf : Add break in wifiapp.c and change priority in /micomapp/Messaging.c, os/kernel/messaging : modify messaging_append_receiver

- os/board/esp32_devkit/src/esp32_appinit.c
make sure function board_app_initialize() be same with its prototype in os\include\tinyara\board.h;
> os/arch/xtensa: change argment of function board_app_initialize() in defination;

- build/configs/imxrt1020-evk/scripts/flash-ocram.ld
- build/configs/imxrt1020-evk/scripts/kernel-space-dtcm.ld
- build/configs/imxrt1020-evk/scripts/kernel-space.ld
- build/configs/imxrt1050-evk/scripts/flash-ocram.ld
- build/configs/imxrt1050-evk/scripts/kernel-space-dtcm.ld
- build/configs/imxrt1050-evk/scripts/kernel-space.ld
- os/board/imxrt1020-evk/src/imxrt_boot.c
- os/board/imxrt1050-evk/src/imxrt_boot.c
Modify linker scripts to fix flexspi flash configuration issue
> build/configs: Fix reset issue at imxrt flash init

- apps/system/utils/fscmd.c
Fix a function that causes a leak
> apps/system/utils: Fix fscmd leak

- apps/AppLibs.mk
- apps/examples/elf/wifiapp/Makefile
link available user libraries with micom and wifi applications
> apps/examples/elf: Update Makefile to auto link libraries with wifi-micom apps

- os/arch/arm/src/armv7-m/mpu.h
- os/arch/arm/src/armv7-m/up_svcall.c
- os/arch/arm/src/imxrt/imxrt_mpuinit.c
- os/arch/arm/src/imxrt/mpu-reg.h
This reverts commit eba7176a2a4169264db07f6b2590e2c1a4f02c54.
> Revert "os/arch/arm/src: Fix performance issue caused by MPU settings"

- apps/system/utils/netcmd_ping.c
- lib/libc/netdb/lib_gethostbyname.c
- os/net/netdev/netdev_ioctl.c
net/netdev_ioctl: Modify lwip_func_ioctl (commit 282879c)
- Modify libc gethostbyname to return user-space global variable
- Modify libc getaddrinfo to return user-space local variable
app/system/utils: Modify ping not to use LwIP API directly (commit 8134012)
- Modify lwip_freeaddrinfo to freeaddrinfo libc
> net/netdev_ioctl: Modify lwip_func_ioctl 

- apps/examples/testcase/le_tc/kernel/tc_libc_signal.c
Add sigwait testcase to improve coverage
IMXRT1050-EVKB log :
User-defined signal 1 (POSIX): SIGUSR1
SIGUSR1
[tc_libc_signal_psignal] PASS
[tc_libc_signal_sigemptyset] PASS
[tc_libc_signal_sigfillset] PASS
[tc_libc_signal_sigaddset] PASS
[tc_libc_signal_sigdelset] PASS
[tc_libc_signal_sigismember] PASS
[tc_libc_signal_sigignore] PASS
[tc_libc_signal_raise] PASS
[tc_libc_signal_sigset] PASS
[tc_libc_signal_signal] PASS
[tc_libc_signal_sigwait] PASS
sigpause test : Before Pause
sigpause test : 2 sec After Pause
[tc_libc_signal_sigpause] PASS
> apps/examples/testcase/le_tc/kernel : Add sigwait testcase

- apps/examples/elf/Kconfig
- apps/examples/elf/micomapp/messaging.c
- apps/examples/elf/wifiapp/messaging.c
If CONFIG_MESSAGING_TEST_REPETITION_NUM set to positive number, messaging f/w test will run repetedely.
If CONFIG_MESSAGING_TEST_REPETITION_NUM set to 0 or negative number, messaging f/w test will run infinitely.
> apps/examples/elf : Support messaging f/w test repetiton running

- external/dhcpc/dhcpc_lwip.c
- os/include/netdb.h
- os/include/tinyara/net/ip.h
- os/net/netdev/Make.defs
- os/net/netdev/netdev_dhcpc.c
- os/net/netdev/netdev_dhcpd.c
- os/net/netdev/netdev_ioctl.c
- Modify DHCP application to use ioctl when the application uses LwIP's DHCPC/D
> external/dhcp: Running LwIP DHCP over ioctl

- framework/src/iotbus/iotbus_adc.c
- framework/src/iotbus/iotbus_uart.c
- os/arch/arm/src/imxrt/chip/imxrt102x_config.h
- os/arch/arm/src/imxrt/chip/imxrt102x_memorymap.h
- os/arch/arm/src/imxrt/chip/imxrt105x_config.h
- os/arch/arm/src/imxrt/imxrt_adc.c
- os/arch/arm/src/imxrt/imxrt_adc.h
- os/board/imxrt1020-evk/src/imxrt_boot.c
- os/board/imxrt1050-evk/src/imxrt_boot.c
- enable gpio/adc initialize in imxrt1020
- change gpio/adc conifg in imxrt1020/1050
> arch/imxrt1020: enable gpio/adc init in imxrt1020-evk

- .travis.yml
- travisCI tests the loadable_elf_apps config only with protection branch
> travisCI: enable loadable_elf_apps config only in protection branch

- framework/src/st_things/things_stack/easy-setup/easysetup.c
- framework/src/st_things/things_stack/framework/things_data_manager.c
- framework/src/st_things/things_stack/things_stack.c
- framework/src/st_things/things_stack/utils/things_network.c
Fix error implicit error and anormal workings.
> framework/st_things: fix logical error.

- framework/src/iotbus/iotbus_uart.c
- iotbus_uart handler includes device number
> framework/iotbus: add device num in uart handler

- external/rtk_wifi/rtk_wifi_utils.c
- os/drivers/wireless/realtek/wifi_util_interface/rtk_drv_lwnl80211.c
- os/drivers/wireless/realtek/wifi_util_interface/wifi_interactive_mode.c
- Remove unused scanning implementation in rtk_wifi_utils
- Modify scanning handler logic
- Fix memory leak after handling scanning data
> os/drivers/wireless: Modify scanning result handler

- apps/examples/testcase/le_tc/filesystem/fs_main.c
testcase/filesystem : Test more negative cases of setvbuf() 
1. Fail to file open
2. Invalid mode check
3. If a buffer pointer is provided, then it must have a non-zero size
4. Reuse buffer
5. EBUSY test
IMXRT1050-EVKB log :
[tc_libc_stdio_setvbuf] PASS
> testcase/filesystem : Test more negative cases of setvbuf()

- framework/include/iotbus/iotbus_adc.h
- framework/include/iotbus/iotbus_error.h
- framework/include/iotbus/iotbus_gpio.h
- framework/include/iotbus/iotbus_i2c.h
- framework/include/iotbus/iotbus_pwm.h
- framework/include/iotbus/iotbus_spi.h
- framework/include/iotbus/iotbus_uart.h
- framework/src/iotbus/Make.defs
- framework/src/iotbus/iotapi_dev_handler.c
- framework/src/iotbus/iotapi_evt_handler.c
- framework/src/iotbus/iotapi_sig_handler.c
- framework/src/iotbus/iotapi_sig_handler.h
- framework/src/iotbus/iotbus_adc.c
- framework/src/iotbus/iotbus_gpio.c
- framework/src/iotbus/iotbus_pwm.c
- framework/src/iotbus/iotbus_spi.c
- framework/src/iotbus/iotbus_uart.c
- os/arch/arm/src/imxrt/imxrt_gpio.c
- os/arch/arm/src/imxrt/imxrt_gpio_lowerhalf.c
- os/drivers/gpio/gpio.c
- os/drivers/iotdev/Make.defs
- os/drivers/iotdev/iotbus_sig.c
- os/include/debug.h
- os/include/signal.h
- os/include/tinyara/fs/ioctl.h
- os/include/tinyara/gpio.h
- os/include/tinyara/iotbus_sig.h
- os/kernel/init/os_bringup.c
- os/kernel/init/os_start.c
- add gpio falling/rising interrupt handler in iotbus
- adjust iotbus/io driver code.
> framework/iotbus: add system I/O interrupt handling process

- apps/examples/security_test/linux/run_gcov.py
- E302 expected 2 blank lines, found 1
- E701 multiple statements on one line (colon)
> examples/security_test: Use PEP8 style

- apps/system/utils/fscmd.c
- '-r' option is added to "rm" so that users can delete multiple files easily.
> app/system: Add an option for 'rm' to delete files/folders recursively.

- framework/src/st_things/things_stack/framework/things_req_handler.c
- framework/src/st_things/things_stack/utils/things_network.c
It has been getting bad effect to performance.
and now, the logs doesn't need.
> framework/st_things: remove unnecessary logs.

- apps/examples/timer/timer_main.c
This patch start/stop timer in thread to avoid any delay of scheduling. Otherwise would results stacking of timer events, which eventually result in stack corruption with high resolution timer.
> apps/examples/timer: Handling Timer start and stop in timer thread

- os/arch/arm/src/imxrt/Make.defs
- os/arch/arm/src/imxrt/imxrt_pit.c
- os/arch/arm/src/imxrt/imxrt_pit.h
- os/board/imxrt1020-evk/src/imxrt_boot.c
- os/board/imxrt1050-evk/src/imxrt_boot.c
- os/include/tinyara/timer.h
Implement PIT timer with 4 channels 32-bit counters
Supports Chain mode for higher count
Support LifeTime counter
> os/arch/arm/src/imxrt : Add PIT Timer

- os/arch/arm/src/imxrt/imxrt_pit.c
This patch modifies lifetime timer support for imxrt.
> imxrt/pit: Modify lifetime timer support

- os/include/tinyara/bluetooth/bluetooth.h
- os/include/tinyara/bluetooth/bt_core.h
- os/include/tinyara/bluetooth/conn.h
- os/net/bluetooth/Make.defs
- os/net/bluetooth/bluetooth.c
- os/net/bluetooth/bt_hcicore.h
- os/net/bluetooth/conn_internal.h
[Bluetooth] Provide bluetooth functions
> [Bluetooth] Provide bluetooth functions

- framework/include/iotbus/iotbus_adc.h
- framework/src/iotbus/iotbus_adc.c
- os/arch/arm/src/imxrt/imxrt_adc.c
- set ADC with higest sampling rate config
> arch/imxrt/adc: set ADC with  highest sampling rate config

- os/kernel/binary_manager/binary_manager_callback.c
> kernel/binary_manager : Fix typo

- os/include/tinyara/bluetooth/bluetooth.h
- os/include/tinyara/bluetooth/bt_hci.h
- os/include/tinyara/bluetooth/conn.h
- os/net/bluetooth/bluetooth.c
- os/net/bluetooth/bt_atomic.h
- os/net/bluetooth/bt_hcicore.c
- os/net/bluetooth/bt_hcicore.h
[Bluetooth] Implemented bluetooth enable, create id, delete id
> [Bluetooth] Implemented bluetooth enable, create id, delete id

- os/net/bluetooth/bt_atomic.c
- os/net/bluetooth/bt_conn.c
- os/net/bluetooth/bt_hcicore.c
- os/net/bluetooth/bt_ioctl.c
- os/net/bluetooth/bt_netdev.c
- os/net/bluetooth/bt_queue.c
- os/net/bluetooth/iob/iob_alloc_qentry.c
- os/net/bluetooth/iob/iob_free_qentry.c
- os/net/bluetooth/iob/iob_initialize.c
Fix net/bluetooth warning messages.
> net/bluetooth: Fix warning messages
